# -*- coding: utf-8 -*-
"""Shared research-field taxonomy for faculty coverage / elite-gap audits."""
import re

FIELDS = {
    "AI / Machine Learning": [r"\bAI\b", r"machine learning", r"deep learning", r"ปัญญาประดิษฐ์", r"แมชชีน", r"neural network", r"natural language", r"computer vision", r"data mining"],
    "Data Science / Statistics": [r"data scien", r"data mining", r"big data", r"statistic", r"วิทยาการข้อมูล", r"สถิติ", r"analytics"],
    "Software / Information Sys": [r"software", r"information system", r"เทคโนโลยีสารสนเทศ", r"วิทยาการคอมพิวเตอร์", r"database", r"cloud", r"ซอฟต์แวร์", r"web ", r"\bit\b"],
    "Cybersecurity": [r"securit", r"cyber", r"ปลอดภัย", r"cryptograph"],
    "Computer Engineering / IoT": [r"computer eng", r"embedded", r"\biot\b", r"internet of things", r"sensor", r"vlsi", r"สมองกลฝังตัว", r"วิศวกรรมคอมพิวเตอร์", r"microcontroller"],
    "Robotics / Automation": [r"robot", r"automation", r"อัตโนมัติ", r"หุ่นยนต์", r"mechatron", r"control system", r"ระบบควบคุม"],
    "Renewable Energy / Power": [r"renewable", r"solar", r"photovoltaic", r"power system", r"พลังงาน", r"แสงอาทิตย์", r"microgrid", r"smart grid", r"battery", r"energy"],
    "Electrical / Electronics": [r"electrical", r"electronic", r"ไฟฟ้า", r"อิเล็กทรอนิกส์", r"telecommunicat", r"antenna", r"signal process", r"circuit"],
    "Mechanical / Manufacturing": [r"mechanical", r"manufactur", r"thermodynam", r"เครื่องกล", r"อุตสาหการ", r"ผลิต", r"cfd", r"finite element", r"industrial eng"],
    "Civil / Structural": [r"civil", r"structur", r"geotechnic", r"โยธา", r"โครงสร้าง", r"คอนกรีต", r"concrete", r"transport eng"],
    "Chemical / Process Eng": [r"chemical eng", r"process eng", r"เคมีวิศวกรรม", r"polymer", r"catalys"],
    "Materials Science": [r"material", r"วัสดุ", r"nanotech", r"นาโน", r"composite", r"ceramic", r"thin film", r"semiconductor"],
    "Biotechnology / Molecular": [r"biotech", r"molecular", r"gene", r"genomic", r"recombinant", r"พันธุ", r"cell culture", r"microbiol", r"จุลชีว", r"enzyme", r"protein"],
    "Biomedical / Medical Eng": [r"biomedical", r"medical device", r"biomechan", r"biosensor", r"ชีวการแพทย์", r"medical imag", r"tissue eng"],
    "Clinical Medicine": [r"\bmedic", r"clinical", r"surgery", r"surgical", r"oncolog", r"cardi", r"pediatric", r"แพทย์", r"อายุร", r"ศัลย", r"เวช", r"patholog", r"radiolog"],
    "Pharmacy / Pharmaceutical": [r"pharmac", r"drug deliv", r"เภสัช", r"medicinal chem", r"toxicolog"],
    "Public Health / Epidemiology": [r"public health", r"epidemiolog", r"สาธารณสุข", r"health promotion", r"สุขภาพ"],
    "Nursing": [r"nursing", r"พยาบาล"],
    "Dentistry": [r"dent", r"ทันต"],
    "Veterinary / Animal Sci": [r"veterin", r"สัตวแพทย์", r"animal sci", r"livestock", r"ปศุสัตว์"],
    "Agriculture / Agronomy": [r"agronom", r"crop", r"soil", r"plant", r"botan", r"เกษตร", r"พืช", r"ดิน", r"rice", r"horticultur", r"greenhous"],
    "Food Science": [r"food", r"อาหาร", r"nutrit", r"โภชนา", r"ferment", r"dairy"],
    "Environment / Ecology": [r"environment", r"ecolog", r"climate", r"wastewater", r"water treat", r"สิ่งแวดล้อม", r"นิเวศ", r"มลพิษ", r"pollut", r"waste", r"biodivers"],
    "Marine / Fisheries": [r"marine", r"fisher", r"ocean", r"ทะเล", r"ประมง", r"aquacultur"],
    "Forestry / Natural Res": [r"forest", r"ป่าไม้", r"natural resource", r"conservation", r"wildlife"],
    "Physics / Applied Physics": [r"physic", r"ฟิสิกส์", r"quantum", r"optics", r"laser", r"plasma", r"astro"],
    "Mathematics": [r"mathemat", r"คณิต", r"algebra", r"topolog", r"optimi"],
    "Chemistry": [r"chemis", r"เคมี", r"organic chem", r"analytical chem", r"electrochem"],
    "Business / Management": [r"business", r"managements", r"management", r"entrepreneur", r"บริหาร", r"จัดการ", r"\bmba\b", r"leadership", r"strateg"],
    "Accounting / Finance": [r"account", r"financ", r"บัญชี", r"การเงิน", r"invest", r"banking", r"audit"],
    "Marketing": [r"marketing", r"ตลาด", r"branding", r"consumer behav"],
    "Economics": [r"econom", r"เศรษฐ", r"econometric"],
    "Law": [r"law\b", r"legal", r"นิติ", r"กฎหมาย", r"jurisprud"],
    "Political Science": [r"politic", r"รัฐศาสตร์", r"governance", r"public policy", r"นโยบาย"],
    "Public Admin": [r"public admin", r"รัฐประศาสน", r"ราชการ"],
    "Education / Pedagogy": [r"educat", r"teach", r"curricul", r"pedagog", r"การศึก", r"ครุศาส", r"learning teach", r"stem educ", r"การเรียนการสอน"],
    "Educational Technology": [r"educational technolog", r"เทคโนโลยีการศึกษา", r"e-learning", r"blended learning", r"instructional design"],
    "Psychology / Counseling": [r"psycholog", r"counsel", r"จิตวิทยา", r"behavior", r"behaviour"],
    "Sociology / Anthropology": [r"sociolog", r"anthropolog", r"สังคมวิทย", r"มานุษย", r"community", r"ชุมชน"],
    "Thai / Languages / Linguistics": [r"linguistic", r"language", r"ภาษา", r"translation", r"literature", r"วรรณกรรม", r"อักษรศาส"],
    "History / Archaeology": [r"histor", r"archaeolog", r"ประวัต", r"โบราณ", r"muse"],
    "Communication / Media": [r"communicat", r"media", r"journalis", r"นิเทศ", r"สื่อสาร", r"public relation", r"broadcast"],
    "Architecture / Urban Design": [r"architect", r"urban", r"สถาปัต", r"เมือง", r"interior", r"ภูมิสถา"],
    "Fine / Applied Arts / Design": [r"art\b", r"design", r"ดนตรี", r"ศิลปะ", r"ออกแบบ", r"music", r"theater", r"นาฏ", r"visual art", r"dance"],
    "Sport Science / PE": [r"sport", r"physical educ", r"พลศึกษา", r"กีฬา", r"exercise"],
    "Tourism / Hospitality": [r"touris", r"hotel", r"hospitality", r"ท่องเที่ยว", r"บริการ"],
    "Library / Information": [r"librar", r"information scien", r"บรรณ", r"สารนิเทศ", r"archiv"],
    "Logistics / Supply Chain": [r"logistic", r"supply chain", r"โซ่อุปทาน", r"โลจิสติก", r"operations research"],
    "Textile / Fashion": [r"textile", r"fashion", r"สิ่งทอ", r"เย็บผ้า"],
    "Mining / Geology / Geo": [r"geolog", r"mining", r"petroleum", r"ธรณี", r"แร่", r"เหมือง", r"gemolog", r"earth sci", r"geograph", r"ภูมิศาส", r"\bgis\b"],
    "Aerospace / Automotive": [r"aerospace", r"aviation", r"aircraft", r"ยานอวกาศ", r"automotive", r"vehicle"],
    "Nuclear / Radiation": [r"nuclear", r"radiat", r"นิวเคลียร์", r"รังสี"],
    "HCI / UX": [r"human.computer", r"\bhci\b", r"\bux\b", r"usability", r"interaction design", r"human factor", r"ergonom"],
    "Social Work / Development": [r"social work", r"develop stud", r"พัฒนาสังคม", r"สวัสดิการ", r"welfare", r"gender"],
    "Agribusiness / Extension": [r"agribusiness", r"extension", r"ส่งเสริมการเกษตร"],
}

compiled = {k: [re.compile(p, re.I) for p in v] for k, v in FIELDS.items()}
