# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')
import os, json, pathlib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.core.database import SessionLocal, engine, Base
from app.models.db_models import CourseDB
from app.core.embedding_service import embedding_service
def emb_text(c):
    hl=", ".join(c.get("curriculum_highlights",[]))
    cp=", ".join(c.get("career_paths",[]))
    tags=", ".join(c.get("tags",[]))
    return f"{c['title_th']} {c.get('title_en','')}. University: {c['university']} {c['university_th']}. Faculty: {c['faculty']} {c['faculty_th']}. Department: {c.get('department','')} {c.get('department_th','')}. Degree: {c['degree_level']} {c.get('degree_name','')}. Description: {c.get('description','')}. Highlights: {hl}. Careers: {cp}. Tags: {tags}."
CMU_BACHELOR = [
  {"id":"cmu_edu_cmu_primary_bed","title_th":"หลักสูตรครุศาสตรบัณฑิต สาขาวิชาการประถมศึกษา","title_en":"Bachelor of Education Program in Elementary Education","degree_level":"ปริญญาตรี","degree_name":"ค.บ. (การประถมศึกษา)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of Elementary Education","department_th":"ภาควิชาการประถมศึกษา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"ผลิตครูประถมศึกษาที่เชี่ยวชาญสะเต็มศึกษาและการจัดการเรียนรู้บูรณาการสำหรับโรงเรียนภาคเหนือ","curriculum_highlights":["Integrated Learning Design Primary","STEM for Young Learners","Classroom Action Research","Lanna Local Curriculum","Teaching Practicum"],"career_paths":["Primary School Teacher","Curriculum Developer","Education Officer","Tutor Entrepreneur","Content Creator Education"],"tags":["Elementary Education","CMU","Teacher"],"website_url":"https://www.edu.cmu.ac.th"},
  {"id":"cmu_edu_early_bed","title_th":"หลักสูตรครุศาสตรบัณฑิต สาขาวิชาการศึกษาปฐมวัย","title_en":"Bachelor of Education Program in Early Childhood Education","degree_level":"ปริญญาตรี","degree_name":"ค.บ. (การศึกษาปฐมวัย)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of Early Childhood Education","department_th":"ภาควิชาการศึกษาปฐมวัย","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นจิตวิทยาเด็กปฐมวัย การเล่นเพื่อเรียนรู้ และภาษาแม่ล้านนา","curriculum_highlights":["Early Childhood Development Psychology","Play-Based Learning Lanna","Early Literacy & Numeracy","Inclusive Early Childhood","Practicum Child Centers"],"career_paths":["Early Childhood Teacher","Child Development Specialist","Kindergarten Manager","Child Media Developer","Researcher"],"tags":["Early Childhood","CMU","Education"],"website_url":"https://www.edu.cmu.ac.th"},
  {"id":"cmu_edu_eng_bed","title_th":"หลักสูตรครุศาสตรบัณฑิต สาขาวิชาภาษาอังกฤษ","title_en":"Bachelor of Education Program in English","degree_level":"ปริญญาตรี","degree_name":"ค.บ. (ภาษาอังกฤษ)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of English Education","department_th":"ภาควิชาภาษาอังกฤษ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"ผลิตครูภาษาอังกฤษที่เชี่ยวชาญ CEFR และ AI เพื่อการสอน","curriculum_highlights":["Communicative Language Teaching","CEFR Assessment & Testing","AI Tools for English Teaching","Intercultural Communication","English Practicum"],"career_paths":["English Teacher","Language School Owner","Curriculum Designer","Influencer Education","Translator Teacher"],"tags":["English Education","CMU","Teacher"],"website_url":"https://www.edu.cmu.ac.th"},
  {"id":"cmu_huso_thai_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาไทย","title_en":"Bachelor of Arts Program in Thai Language","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาไทย)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Humanities","faculty_th":"คณะมนุษยศาสตร์","department":"Department of Thai","department_th":"ภาควิชาภาษาไทย","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นภาษาไทย วรรณกรรมล้านนา และคติชนวิทยาเหนือ","curriculum_highlights":["Thai Linguistics & Lanna Literature","Lanna Folklore & Culture","Creative Writing & Editing","Thai for Media","Lanna Heritage Conservation"],"career_paths":["Thai Teacher","Editor","Cultural Officer","Media Creator","Researcher"],"tags":["Thai Language","Lanna","CMU","Humanities"],"website_url":"https://www.human.cmu.ac.th"},
  {"id":"cmu_huso_eng_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาอังกฤษ","title_en":"Bachelor of Arts Program in English","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาอังกฤษ)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Humanities","faculty_th":"คณะมนุษยศาสตร์","department":"Department of English","department_th":"ภาควิชาภาษาอังกฤษ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นภาษาอังกฤษเชิงวิชาการ ธุรกิจ และวรรณกรรม","curriculum_highlights":["Academic English & Writing","Business English & Presentation","English Literature & Culture","Translation & Interpretation","English for Digital Communication"],"career_paths":["English Teacher","Translator","Content Writer","Coordinator International","Graduate Studies"],"tags":["English","CMU","Humanities"],"website_url":"https://www.human.cmu.ac.th"},
  {"id":"cmu_huso_history_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาประวัติศาสตร์","title_en":"Bachelor of Arts Program in History","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ประวัติศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Humanities","faculty_th":"คณะมนุษยศาสตร์","department":"Department of History","department_th":"ภาควิชาประวัติศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นประวัติศาสตร์ล้านนา ไทย และเอเชียตะวันออกเฉียงใต้","curriculum_highlights":["Lanna & Thai History","Southeast Asian History","Oral History & Archive","Museum Studies Lanna","Digital History"],"career_paths":["Historian","Museum Curator","Archivist","Cultural Officer","Teacher"],"tags":["History","Lanna","CMU","Museum"],"website_url":"https://www.human.cmu.ac.th"},
  {"id":"cmu_fine_art_bfa","title_th":"หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชาศิลปะไทย","title_en":"Bachelor of Fine Arts Program in Thai Art","degree_level":"ปริญญาตรี","degree_name":"ศล.บ. (ศิลปะไทย)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Fine Arts","faculty_th":"คณะวิจิตรศิลป์","department":"Department of Thai Art","department_th":"ภาควิชาศิลปะไทย","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นจิตรกรรมไทย ประติมากรรมล้านนา และศิลปะร่วมสมัยเหนือ","curriculum_highlights":["Thai Painting & Lanna Sculpture","Contemporary Art Northern","Art History Lanna","Gallery Management","Graduation Exhibition Lanna"],"career_paths":["Visual Artist","Art Curator","Gallery Manager","Art Teacher","Cultural Entrepreneur"],"tags":["Thai Art","Lanna","CMU","Fine Arts"],"website_url":"https://www.finearts.cmu.ac.th"},
  {"id":"cmu_arch_barch","title_th":"หลักสูตรสถาปัตยกรรมศาสตรบัณฑิต","title_en":"Bachelor of Architecture Program","degree_level":"ปริญญาตรี","degree_name":"สถ.บ. (สถาปัตยกรรมศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Architecture","faculty_th":"คณะสถาปัตยกรรมศาสตร์","department":"Department of Architecture","department_th":"ภาควิชาสถาปัตยกรรมศาสตร์","program_type":"ภาคปกติ","duration_years":"5 ปี","total_credits":"165 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"200,000 บาท","description":"เน้นสถาปัตยกรรมล้านนา สถาปัตยกรรมเขตร้อน และผังเมืองเชียงใหม่","curriculum_highlights":["Lanna Vernacular Architecture","Tropical Architecture Studio","Urban Design Chiang Mai","Sustainable Green Building","Architectural Conservation Lanna"],"career_paths":["Architect","Urban Designer","Conservation Architect","Interior Designer","Project Manager"],"tags":["Architecture","Lanna","CMU","Sustainable"],"website_url":"https://www.arc.cmu.ac.th"},
  {"id":"cmu_nurse_bns","title_th":"หลักสูตรพยาบาลศาสตรบัณฑิต","title_en":"Bachelor of Nursing Science Program","degree_level":"ปริญญาตรี","degree_name":"พย.บ. (พยาบาลศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Faculty of Nursing","department_th":"คณะพยาบาลศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"142 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"176,000 บาท","description":"ผลิตพยาบาลวิชาชีพตามมาตรฐานสภาการพยาบาล ร่วมกับ รพ.มหาราชนครเชียงใหม่","curriculum_highlights":["Adult & Elderly Nursing Maharaj","Pediatric & Maternity Nursing","Community Health Nursing North","Nursing Ethics & Leadership","Clinical Practicum Maharaj"],"career_paths":["Registered Nurse","Community Health Nurse","Hospital Nurse","Nurse Educator","Health Entrepreneur"],"tags":["Nursing","CMU","Maharaj Hospital"],"website_url":"https://www.nurse.cmu.ac.th"},
  {"id":"cmu_pharm_bpharm","title_th":"หลักสูตรเภสัชศาสตรบัณฑิต","title_en":"Bachelor of Pharmacy Program","degree_level":"ปริญญาตรี","degree_name":"ภ.บ. (เภสัชศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Pharmacy","faculty_th":"คณะเภสัชศาสตร์","department":"Faculty of Pharmacy","department_th":"คณะเภสัชศาสตร์","program_type":"ภาคปกติ","duration_years":"6 ปี","total_credits":"220 หน่วยกิต","tuition_per_semester":"28,000 บาท","tuition_total":"336,000 บาท","description":"เน้นการบริบาลทางเภสัชกรรม สมุนไพรล้านนา และเภสัชกรรมชุมชนเหนือ","curriculum_highlights":["Clinical Pharmacy & Pharmacotherapy","Lanna Herbal Medicine & Natural Products","Community Pharmacy North","Industrial Pharmacy GMP","Hospital Pharmacy Maharaj"],"career_paths":["Pharmacist","Clinical Pharmacist","Community Pharmacist","Industrial Pharmacist","Herbal Researcher"],"tags":["Pharmacy","CMU","Lanna Herbal"],"website_url":"https://www.pharmacy.cmu.ac.th"},
  {"id":"cmu_vet_dvm","title_th":"หลักสูตรสัตวแพทยศาสตรบัณฑิต","title_en":"Doctor of Veterinary Medicine Program","degree_level":"ปริญญาตรี","degree_name":"สพ.บ. (สัตวแพทยศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Veterinary Medicine","faculty_th":"คณะสัตวแพทยศาสตร์","department":"Faculty of Veterinary Medicine","department_th":"คณะสัตวแพทยศาสตร์","program_type":"ภาคปกติ","duration_years":"6 ปี","total_credits":"220 หน่วยกิต","tuition_per_semester":"32,000 บาท","tuition_total":"384,000 บาท","description":"ผลิตสัตวแพทย์ที่เชี่ยวชาญช้าง สัตว์ป่าเหนือ และ One Health ล้านนา","curriculum_highlights":["Elephant & Wildlife Medicine Chiang Mai","Small & Large Animal Surgery","One Health & Zoonoses North","Vet Public Health Lanna","Clinical Rotation Vet Hospital CMU"],"career_paths":["Veterinarian","Wildlife Vet","Elephant Vet","One Health Officer","Vet Entrepreneur"],"tags":["Veterinary Medicine","Elephant","CMU","One Health"],"website_url":"https://www.vet.cmu.ac.th"},
  {"id":"cmu_dent_dds","title_th":"หลักสูตรทันตแพทยศาสตรบัณฑิต","title_en":"Doctor of Dental Surgery Program","degree_level":"ปริญญาตรี","degree_name":"ท.บ. (ทันตแพทยศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Dentistry","faculty_th":"คณะทันตแพทยศาสตร์","department":"Faculty of Dentistry","department_th":"คณะทันตแพทยศาสตร์","program_type":"ภาคปกติ","duration_years":"6 ปี","total_credits":"220 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"420,000 บาท","description":"ผลิตทันตแพทย์ที่เชี่ยวชาญทันตกรรมชุมชนเหนือและทันตกรรมดิจิทัล","curriculum_highlights":["Oral Surgery & Community Dentistry North","Digital Dentistry CAD/CAM","Orthodontics & Pediatric Dentistry","Dental Public Health Lanna","Clinical Dentistry Maharaj"],"career_paths":["Dentist","Community Dentist","Orthodontist Trainee","Dental Entrepreneur","Academic Dentist"],"tags":["Dentistry","CMU","Digital Dentistry"],"website_url":"https://www.dent.cmu.ac.th"},
  {"id":"cmu_agri_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเกษตรศาสตร์","title_en":"Bachelor of Science Program in Agriculture","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เกษตรศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Agriculture","faculty_th":"คณะเกษตรศาสตร์","department":"Department of Agriculture","department_th":"ภาควิชาเกษตรศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นเกษตรแม่นยำสูง เกษตรอินทรีย์ล้านนา และเทคโนโลยีเกษตรอัจฉริยะดอย","curriculum_highlights":["Precision Agriculture & Smart Farm Doi","Organic Farming Lanna","Soil & Water Management North","Horticulture & Highland Crops","Agri Business & Royal Project"],"career_paths":["Agriculturist","Smart Farmer","Organic Farming Entrepreneur","Agri Extension Officer","Researcher Agriculture"],"tags":["Agriculture","Smart Farm","Lanna","CMU"],"website_url":"https://www.agri.cmu.ac.th"},
  {"id":"cmu_econ_ba","title_th":"หลักสูตรเศรษฐศาสตรบัณฑิต","title_en":"Bachelor of Economics Program","degree_level":"ปริญญาตรี","degree_name":"ศ.บ. (เศรษฐศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Department of Economics","department_th":"ภาควิชาเศรษฐศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นเศรษฐศาสตร์พัฒนาภาคเหนือ เศรษฐกิจสร้างสรรค์ล้านนา และเศรษฐมิติ","curriculum_highlights":["Development Economics North","Lanna Creative Economy","Econometrics & Data Analysis","International Economics ASEAN","Policy Lab Economics CMU"],"career_paths":["Economist","Economic Analyst North","Policy Researcher","Financial Analyst","Consultant"],"tags":["Economics","CMU","Lanna Creative"],"website_url":"https://www.econ.cmu.ac.th"},
  {"id":"cmu_law_llb","title_th":"หลักสูตรนิติศาสตรบัณฑิต","title_en":"Bachelor of Laws Program","degree_level":"ปริญญาตรี","degree_name":"น.บ. (นิติศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Law","faculty_th":"คณะนิติศาสตร์","department":"Department of Law","department_th":"ภาควิชานิติศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"135 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นกฎหมายล้านนา กฎหมายธุรกิจ และกฎหมายชุมชนเหนือ","curriculum_highlights":["Lanna Customary Law & Thai Law","Business Law & Community Law North","Moot Court Chiang Mai","Legal Clinic Lanna","Law & Technology"],"career_paths":["Lawyer","Legal Officer","Corporate Counsel","Judge/Prosecutor Trainee","Legal Consultant"],"tags":["Law","Lanna Law","CMU"],"website_url":"https://www.law.cmu.ac.th"},
  {"id":"cmu_pol_ba","title_th":"หลักสูตรรัฐศาสตรบัณฑิต","title_en":"Bachelor of Arts Program in Political Science","degree_level":"ปริญญาตรี","degree_name":"ร.บ. (รัฐศาสตร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Political Science and Public Administration","faculty_th":"คณะรัฐศาสตร์และรัฐประศาสนศาสตร์","department":"Department of Political Science","department_th":"ภาควิชารัฐศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการเมืองล้านนา นโยบายสาธารณะ และการปกครองท้องถิ่นเหนือ","curriculum_highlights":["Lanna Politics & Local Governance North","Public Policy Analysis","International Relations ASEAN","Political Theory & Research","Internship Local Government"],"career_paths":["Political Scientist","Policy Analyst","Local Government Officer","Diplomat Assistant","Researcher"],"tags":["Political Science","CMU","Lanna"],"website_url":"https://www.pol.cmu.ac.th"},
  {"id":"cmu_sci_compsci_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์","title_en":"Bachelor of Science Program in Computer Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาการคอมพิวเตอร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Computer Science","department_th":"ภาควิชาวิทยาการคอมพิวเตอร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นทฤษฎีการคำนวณ AI และวิทยาการข้อมูลเพื่ออุตสาหกรรมซอฟต์แวร์เหนือ","curriculum_highlights":["Theory of Computation & Algorithms","AI & Machine Learning","Data Science & Big Data","Software Engineering","CS Project Lanna"],"career_paths":["Software Engineer","AI Engineer","Data Scientist","System Analyst","Researcher"],"tags":["Computer Science","CMU","AI"],"website_url":"https://www.cscmu.cmu.ac.th"},
  {"id":"cmu_eng_cpe_beng2","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์ (นานาชาติ)","title_en":"Bachelor of Engineering Program in Computer Engineering (International Program)","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมคอมพิวเตอร์)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Computer Engineering","department_th":"ภาควิชาวิศวกรรมคอมพิวเตอร์","program_type":"นานาชาติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"50,000 บาท","tuition_total":"400,000 บาท","description":"หลักสูตรนานาชาติ 100% English เน้น AI Cloud และสหกิจนานาชาติ","curriculum_highlights":["International AI & Cloud Systems","Cybersecurity & Blockchain English","Global Software Engineering","International Co-op","Capstone International"],"career_paths":["International Software Engineer","Cloud Architect","Cybersecurity Specialist","Global Consultant","Graduate Studies Abroad"],"tags":["Computer Engineering","International Program","CMU"],"website_url":"https://www.cpe.eng.cmu.ac.th"},
  {"id":"cmu_business_bba","title_th":"หลักสูตรบริหารธุรกิจบัณฑิต","title_en":"Bachelor of Business Administration Program","degree_level":"ปริญญาตรี","degree_name":"บธ.บ. (บริหารธุรกิจ)","university":"Chiang Mai University","university_th":"มหาวิทยาลัยเชียงใหม่","faculty":"Faculty of Business Administration","faculty_th":"คณะบริหารธุรกิจ","department":"Department of Business Administration","department_th":"ภาควิชาบริหารธุรกิจ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นบริหารธุรกิจล้านนาสร้างสรรค์ การท่องเที่ยวเชิงวัฒนธรรม และสตาร์ทอัพเหนือ","curriculum_highlights":["Lanna Creative Business & Tourism","Startup & Innovation North","Marketing & Finance CMU","Business Analytics & Digital","Internship Business Chiang Mai"],"career_paths":["Business Manager","Entrepreneur Lanna","Marketing Specialist","Financial Analyst","Startup Founder"],"tags":["Business Administration","CMU","Lanna"],"website_url":"https://www.ba.cmu.ac.th"},
]
print(f"Prepared {len(CMU_BACHELOR)} CMU bachelor")
out=pathlib.Path("backend/data/courses_new/courses_cmu_bachelor_expansion.json")
with open(out,'w',encoding='utf-8') as f:
    json.dump(CMU_BACHELOR,f,ensure_ascii=False,indent=2)
print(f"Saved to {out}")
Base.metadata.create_all(bind=engine)
session=SessionLocal()
ins=upd=0
for c in CMU_BACHELOR:
    et=emb_text(c)
    try:
        vec=embedding_service.get_embedding(et)
        if vec and len(vec)!=768:
            vec=None
    except Exception as e:
        print(f"emb fail {c['id']}: {e}")
        vec=None
    ex=session.query(CourseDB).filter_by(id=c["id"]).first()
    if ex:
        for k,v in c.items():
            setattr(ex,k,v)
        ex.embedding_text=et
        if vec:
            ex.embedding=vec
        upd+=1
        print(f"Updated {c['id']}")
    else:
        db=CourseDB(id=c["id"], title_th=c["title_th"], title_en=c.get("title_en"), degree_level=c["degree_level"], degree_name=c.get("degree_name"), university=c["university"], university_th=c["university_th"], faculty=c["faculty"], faculty_th=c["faculty_th"], department=c.get("department"), department_th=c.get("department_th"), program_type=c.get("program_type","ภาคปกติ"), duration_years=c.get("duration_years"), total_credits=c.get("total_credits"), tuition_per_semester=c.get("tuition_per_semester"), tuition_total=c.get("tuition_total"), description=c.get("description"), curriculum_highlights=c.get("curriculum_highlights",[]), career_paths=c.get("career_paths",[]), tags=c.get("tags",[]), website_url=c.get("website_url"), embedding_text=et, embedding=vec if vec else None)
        session.add(db)
        ins+=1
        print(f"Inserted {c['id']} emb={'OK' if vec else 'NULL'}")
    if (ins+upd)%20==0:
        session.commit()
session.commit()
print(f"Done CMU bachelor ins={ins} upd={upd}")
from sqlalchemy import text as t
with engine.connect() as conn:
    total=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Chiang Mai University'")).scalar()
    tri=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Chiang Mai University' AND degree_level='ปริญญาตรี'")).scalar()
    tho=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Chiang Mai University' AND degree_level='ปริญญาโท'")).scalar()
    print(f"CMU total {total} ตรี {tri} โท {tho} {'ตรี>โท' if tri>tho else 'โท>ตรี'}")
    tot_all=conn.execute(t("SELECT COUNT(*) FROM courses")).scalar()
    print(f"DB total: {tot_all}")
session.close()
