# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')
import os, json, pathlib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.core.database import SessionLocal, engine, Base
from app.models.db_models import CourseDB
from app.core.embedding_service import embedding_service
def emb_text(c):
    hl=", ".join(c.get("curriculum_highlights",[]))
    cp=", ".join(c.get("career_paths",[]))
    tags=", ".join(c.get("tags",[]))
    return f"{c['title_th']} {c.get('title_en','')}. University: {c['university']} {c['university_th']}. Faculty: {c['faculty']} {c['faculty_th']}. Department: {c.get('department','')} {c.get('department_th','')}. Degree: {c['degree_level']} {c.get('degree_name','')}. Description: {c.get('description','')}. Highlights: {hl}. Careers: {cp}. Tags: {tags}."
CU_COURSES = [
  # === FACULTY OF SCIENCE expansion (15) ===
  {"id":"cu_sci_bio_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาชีววิทยา","title_en":"Bachelor of Science Program in Biology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ชีววิทยา)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Biology","department_th":"ภาควิชาชีววิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นชีววิทยาโมเลกุล นิเวศวิทยา ความหลากหลายทางชีวภาพ และชีววิทยาระบบเพื่อวิจัยและนวัตกรรมชีวภาพ","curriculum_highlights":["Molecular Biology & Genetics","Ecology & Biodiversity of Thailand","Systems Biology & Bioinformatics","Conservation Biology Fieldwork","Biology Research Project"],"career_paths":["Biologist","Conservation Scientist","Bioinformatics Analyst","Research Scientist","Science Teacher"],"tags":["Biology","Molecular Biology","Biodiversity","CU","Science"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_chem_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเคมี","title_en":"Bachelor of Science Program in Chemistry","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เคมี)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Chemistry","department_th":"ภาควิชาเคมี","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นเคมีวิเคราะห์ เคมีอินทรีย์ เคมีเชิงฟิสิกส์ และวัสดุนาโนเพื่ออุตสาหกรรมและพลังงานสะอาด","curriculum_highlights":["Analytical & Organic Chemistry Lab","Physical Chemistry & Spectroscopy","Nanomaterials & Polymer Chemistry","Chemical Instrumentation","Chemistry Research Capstone"],"career_paths":["Chemist","Materials Scientist","Analytical Chemist","R&D Chemist","Quality Control Specialist"],"tags":["Chemistry","Nanomaterials","CU","Science"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_phys_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาฟิสิกส์","title_en":"Bachelor of Science Program in Physics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ฟิสิกส์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Physics","department_th":"ภาควิชาฟิสิกส์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นฟิสิกส์ทฤษฎี ฟิสิกส์วัสดุ พลังงาน และดาราศาสตร์ฟิสิกส์เพื่อเทคโนโลยีควอนตัมและพลังงานสะอาด","curriculum_highlights":["Quantum Physics & Materials","Renewable Energy Physics","Computational Physics with Python","Optics & Photonics Lab","Physics Research Project"],"career_paths":["Physicist","Materials Physicist","Energy Technologist","Data Scientist","Science Educator"],"tags":["Physics","Quantum","Energy","CU"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_math_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาคณิตศาสตร์","title_en":"Bachelor of Science Program in Mathematics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (คณิตศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Mathematics","department_th":"ภาควิชาคณิตศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นคณิตบริสุทธิ์ ประยุกต์ คณิตศาสตร์การเงิน และวิทยาการข้อมูลคณิตศาสตร์","curriculum_highlights":["Pure & Applied Mathematics","Financial Mathematics & Actuarial","Statistics & Data Science Math","Mathematical Modeling","Math Research Seminar"],"career_paths":["Mathematician","Actuary","Data Analyst","Quantitative Analyst","Math Teacher"],"tags":["Mathematics","Actuarial","CU","Science"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_stat_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสถิติ","title_en":"Bachelor of Science Program in Statistics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (สถิติ)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Statistics","department_th":"ภาควิชาสถิติ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นสถิติคณิตศาสตร์ วิทยาการข้อมูล และการวิเคราะห์เชิงสถิติสำหรับธุรกิจและการแพทย์","curriculum_highlights":["Mathematical Statistics & Probability","Biostatistics & Clinical Trials","Data Science & Machine Learning","Statistical Computing (R)","Statistical Consulting Lab"],"career_paths":["Statistician","Biostatistician","Data Scientist","Market Research Analyst","Risk Analyst"],"tags":["Statistics","Biostatistics","Data Science","CU"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_compsci_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์","title_en":"Bachelor of Science Program in Computer Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาการคอมพิวเตอร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Computer Science","department_th":"ภาควิชาวิทยาการคอมพิวเตอร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นทฤษฎีการคำนวณ อัลกอริทึม ปัญญาประดิษฐ์ และวิทยาการข้อมูลเพื่ออุตสาหกรรมซอฟต์แวร์","curriculum_highlights":["Theory of Computation & Algorithms","Artificial Intelligence & Machine Learning","Database & Big Data Systems","Software Engineering & Systems","CS Senior Project"],"career_paths":["Software Engineer","AI Engineer","Data Scientist","System Analyst","Researcher"],"tags":["Computer Science","AI","CU","Science"],"website_url":"https://www.cs.chula.ac.th"},
  {"id":"cu_sci_marine_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์ทางทะเล","title_en":"Bachelor of Science Program in Marine Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาศาสตร์ทางทะเล)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Marine Science","department_th":"ภาควิชาวิทยาศาสตร์ทางทะเล","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นสมุทรศาสตร์ นิเวศวิทยาทางทะเล การจัดการทรัพยากรทางทะเลอ่าวไทยและอันดามัน","curriculum_highlights":["Physical & Chemical Oceanography","Marine Ecology & Coral Reef","Marine Resource Management","Marine Pollution & Conservation","Fieldwork Andaman & Gulf"],"career_paths":["Marine Scientist","Oceanographer","Marine Conservation Officer","Environmental Consultant","Researcher Marine"],"tags":["Marine Science","Oceanography","CU","Conservation"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_foodtech_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีทางอาหาร","title_en":"Bachelor of Science Program in Food Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคโนโลยีทางอาหาร)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Food Technology","department_th":"ภาควิชาเทคโนโลยีทางอาหาร","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นเคมีอาหาร จุลชีววิทยาอาหาร วิศวกรรมอาหาร และการประกันคุณภาพอาหารระดับส่งออก","curriculum_highlights":["Food Chemistry & Microbiology","Food Processing & Engineering","Food Safety & HACCP","Sensory Evaluation & Product Development","Food Factory Internship"],"career_paths":["Food Scientist","Food Technologist","QA Manager Food","Product Developer","Food Safety Auditor"],"tags":["Food Technology","CU","Science","HACCP"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_env_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์สิ่งแวดล้อม","title_en":"Bachelor of Science Program in Environmental Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาศาสตร์สิ่งแวดล้อม)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Environmental Science","department_th":"ภาควิชาวิทยาศาสตร์สิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นมลพิษ การจัดการสิ่งแวดล้อมเมืองหลวง PM2.5 และการพัฒนาที่ยั่งยืนกรุงเทพ","curriculum_highlights":["Environmental Monitoring & PM2.5","EIA & Strategic Environmental Assessment","Waste & Circular Economy","GIS for Environment","Environmental Fieldwork Bangkok"],"career_paths":["Environmental Scientist","EIA Consultant","Sustainability Officer","Pollution Control Specialist","GIS Analyst"],"tags":["Environmental Science","EIA","PM2.5","CU"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_material_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวัสดุศาสตร์","title_en":"Bachelor of Science Program in Materials Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วัสดุศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Materials Science","department_th":"ภาควิชาวัสดุศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นวัสดุนาโน พอลิเมอร์ เซรามิก และวัสดุพลังงานเพื่ออุตสาหกรรม EV และเซมิคอนดักเตอร์","curriculum_highlights":["Nanomaterials & Characterization","Polymer & Composite Materials","Semiconductor & Electronic Materials","Materials for Energy (EV Battery)","Materials Lab & Research Project"],"career_paths":["Materials Scientist","Polymer Engineer","Battery Materials Specialist","Semiconductor Engineer","R&D Specialist"],"tags":["Materials Science","Nanomaterials","EV Battery","CU"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_biotech_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีชีวภาพ","title_en":"Bachelor of Science Program in Biotechnology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคโนโลยีชีวภาพ)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Biotechnology","department_th":"ภาควิชาเทคโนโลยีชีวภาพ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นวิศวกรรมพันธุศาสตร์ โปรตีน และชีวกระบวนการเพื่อเภสัชภัณฑ์และ BCG Economy","curriculum_highlights":["Genetic Engineering & CRISPR","Protein Engineering & Bioprocess","Fermentation & Bioreactor","Bioinformatics & Genomics","Biotech Entrepreneurship Lab"],"career_paths":["Biotechnologist","Protein Engineer","Fermentation Specialist","Bioinformatics Analyst","Biotech Entrepreneur"],"tags":["Biotechnology","CRISPR","CU","BCG"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_geo_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาธรณีวิทยา","title_en":"Bachelor of Science Program in Geology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ธรณีวิทยา)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Geology","department_th":"ภาควิชาธรณีวิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"21,000 บาท","tuition_total":"168,000 บาท","description":"เน้นธรณีวิทยาปิโตรเลียม อุทกธรณีวิทยา และภัยพิบัติทางธรณีภาคกลาง","curriculum_highlights":["Petroleum Geology & Exploration","Hydrogeology & Groundwater","Geological Hazards & Earthquakes","GIS & Remote Sensing Geology","Geological Field Camp"],"career_paths":["Geologist","Petroleum Geologist","Hydrogeologist","Environmental Geologist","GIS Specialist"],"tags":["Geology","Petroleum","CU","Science"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_micro_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาจุลชีววิทยา","title_en":"Master of Science Program in Microbiology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (จุลชีววิทยา)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Microbiology","department_th":"ภาควิชาจุลชีววิทยา","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"วิจัยจุลชีววิทยาทางการแพทย์ จุลินทรีย์ก่อโรค และการดื้อยา","curriculum_highlights":["Medical Microbiology & Pathogenesis","Antimicrobial Resistance (AMR)","Virology & Emerging Diseases","Thesis Microbiology","Clinical Microbiology Lab"],"career_paths":["Microbiologist Researcher","Clinical Microbiologist","AMR Specialist","Pharma R&D","Academic"],"tags":["Microbiology","AMR","CU","Master Degree"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_bio_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาชีววิทยา","title_en":"Doctor of Philosophy Program in Biology","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (ชีววิทยา)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Biology","department_th":"ภาควิชาชีววิทยา","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"210,000 บาท","description":"วิจัยความหลากหลายทางชีวภาพและการอนุรักษ์ระดับโมเลกุล","curriculum_highlights":["Biodiversity Genomics","Conservation Genetics","Dissertation Biology","International Field Research","Publication in High-Impact Journals"],"career_paths":["Biology Professor","Conservation Research Leader","Biodiversity Consultant","Museum Curator Research","International Researcher"],"tags":["Ph.D. Biology","CU","Biodiversity"],"website_url":"https://www.sc.chula.ac.th"},
  {"id":"cu_sci_data_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์ข้อมูล","title_en":"Master of Science Program in Data Science","degree_level":"ปริญญาโท","degree_name":"วท.ม. (วิทยาศาสตร์ข้อมูล)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Mathematics and Computer Science","department_th":"ภาควิชาคณิตศาสตร์และวิทยาการคอมพิวเตอร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"140,000 บาท","description":"วิจัยวิทยาการข้อมูลเชิงวิทยาศาสตร์ AI และการวิเคราะห์ข้อมูลขนาดใหญ่","curriculum_highlights":["Machine Learning & Deep Learning","Big Data Engineering (Spark)","Statistical Inference & Bayesian","Thesis Data Science","Data Visualization & Communication"],"career_paths":["Data Scientist","ML Engineer","Research Data Scientist","Academic","Consultant"],"tags":["Data Science","CU","Science","Master Degree"],"website_url":"https://www.sc.chula.ac.th"},
  # === FACULTY OF ECONOMICS expansion (5) ===
  {"id":"cu_econ_ba","title_th":"หลักสูตรเศรษฐศาสตรบัณฑิต","title_en":"Bachelor of Economics Program","degree_level":"ปริญญาตรี","degree_name":"ศ.บ. (เศรษฐศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Department of Economics","department_th":"ภาควิชาเศรษฐศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นเศรษฐศาสตร์จุลภาค มหภาค เศรษฐมิติ และการวิเคราะห์นโยบายเศรษฐกิจไทยและอาเซียน","curriculum_highlights":["Micro & Macro Economics","Econometrics & Applied Micro","Development Economics & Thai Economy","International Economics & ASEAN","Policy Analysis Lab"],"career_paths":["Economist","Economic Analyst","Policy Researcher","Financial Analyst","Consultant Economics"],"tags":["Economics","CU","EBE"],"website_url":"https://www.econ.chula.ac.th"},
  {"id":"cu_econ_becon_inter","title_th":"หลักสูตรเศรษฐศาสตรบัณฑิต (หลักสูตรนานาชาติ EBA)","title_en":"Bachelor of Economics Program (EBA International Program)","degree_level":"ปริญญาตรี","degree_name":"ศ.บ. (เศรษฐศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Economics EBA Program","department_th":"หลักสูตร EBA","program_type":"นานาชาติ","duration_years":"4 ปี","total_credits":"133 หน่วยกิต","tuition_per_semester":"85,000 บาท","tuition_total":"680,000 บาท","description":"หลักสูตรนานาชาติ EBA อันดับ 1 ไทย เรียน 100% English มี Double Degree กับมหาวิทยาลัยคู่สัญญา (UK/Australia)","curriculum_highlights":["International Economics (English)","Financial Economics & FinTech","Econometrics with Data Science","Global Internship & Exchange","EBA Senior Project & Case Competition"],"career_paths":["International Economist","Investment Banker","Management Consultant","Global Policy Analyst","Entrepreneur"],"tags":["EBA","Economics","International Program","CU"],"website_url":"https://www.eba.econ.chula.ac.th"},
  {"id":"cu_econ_dev_msc","title_th":"หลักสูตรเศรษฐศาสตรมหาบัณฑิต สาขาวิชาเศรษฐศาสตร์การพัฒนา","title_en":"Master of Economics Program in Development Economics","degree_level":"ปริญญาโท","degree_name":"ศ.ม. (เศรษฐศาสตร์การพัฒนา)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Graduate Studies Economics","department_th":"บัณฑิตศึกษา คณะเศรษฐศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"140,000 บาท","description":"วิจัยเศรษฐกิจการพัฒนา ความยากจนและความเหลื่อมล้ำไทย","curriculum_highlights":["Development Economics & Poverty","Inequality & Labour Economics","Impact Evaluation & RCT","Thesis Development Economics","Fieldwork Thai Economy"],"career_paths":["Development Economist","Policy Evaluator","World Bank/ADB Analyst","Researcher","PhD Candidate"],"tags":["Development Economics","CU","Master Degree"],"website_url":"https://www.econ.chula.ac.th"},
  {"id":"cu_econ_business_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาเศรษฐศาสตร์","title_en":"Doctor of Philosophy Program in Economics","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (เศรษฐศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Doctoral Program in Economics","department_th":"สาขาวิชาเศรษฐศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"240,000 บาท","description":"ผลิตนักเศรษฐศาสตร์วิจัยระดับแนวหน้า เน้นไทย-อาเซียน","curriculum_highlights":["Advanced Micro & Macro Theory","Causal Inference & Machine Learning Economics","Dissertation Economics","Teaching Economics","International Publication"],"career_paths":["Economics Professor","Senior Economist Bank of Thailand","Think Tank Director","International Organization Economist","Consultant"],"tags":["Ph.D. Economics","CU","Research"],"website_url":"https://www.econ.chula.ac.th"},
  {"id":"cu_econ_health_msc","title_th":"หลักสูตรเศรษฐศาสตรมหาบัณฑิต สาขาวิชาเศรษฐศาสตร์สาธารณสุข","title_en":"Master of Science Program in Health Economics","degree_level":"ปริญญาโท","degree_name":"ศศ.ม. (เศรษฐศาสตร์สาธารณสุข)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Centre for Health Economics","department_th":"ศูนย์วิจัยเศรษฐศาสตร์สาธารณสุข","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"32,000 บาท","tuition_total":"128,000 บาท","description":"เน้นเศรษฐศาสตร์สุขภาพ ระบบหลักประกันสุขภาพ และการประเมินเทคโนโลยีสุขภาพ (HTA)","curriculum_highlights":["Health Economics & UHC","Health Technology Assessment (HTA)","Health Econometrics","Thesis Health Economics","Internship Ministry of Public Health"],"career_paths":["Health Economist","HTA Analyst","NHSO Policy Analyst","Health Researcher","Consultant Health"],"tags":["Health Economics","HTA","UHC","CU"],"website_url":"https://www.econ.chula.ac.th"},
  # === FACULTY OF POLITICAL SCIENCE (6) ===
  {"id":"cu_polsci_ba","title_th":"หลักสูตรรัฐศาสตรบัณฑิต สาขาวิชาการปกครอง","title_en":"Bachelor of Arts Program in Government","degree_level":"ปริญญาตรี","degree_name":"ร.บ. (การปกครอง)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Political Science","faculty_th":"คณะรัฐศาสตร์","department":"Department of Government","department_th":"ภาควิชาการปกครอง","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นรัฐศาสตร์ การเมืองไทยเปรียบเทียบ รัฐธรรมนูญ และนโยบายสาธารณะเพื่อผู้นำรุ่นใหม่","curriculum_highlights":["Thai Politics & Constitution","Comparative Politics ASEAN","Public Policy & Governance","International Relations & Diplomacy","Political Research & Debate"],"career_paths":["Political Scientist","Policy Analyst","Diplomat Assistant","Government Officer","Political Journalist"],"tags":["Political Science","Government","CU","Public Policy"],"website_url":"https://www.polsci.chula.ac.th"},
  {"id":"cu_polsci_ir_ba","title_th":"หลักสูตรรัฐศาสตรบัณฑิต สาขาวิชาความสัมพันธ์ระหว่างประเทศ","title_en":"Bachelor of Arts Program in International Relations","degree_level":"ปริญญาตรี","degree_name":"ร.บ. (ความสัมพันธ์ระหว่างประเทศ)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Political Science","faculty_th":"คณะรัฐศาสตร์","department":"Department of International Relations","department_th":"ภาควิชาความสัมพันธ์ระหว่างประเทศ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นความสัมพันธ์ระหว่างประเทศ ทฤษฎี IR กฎหมายระหว่างประเทศ และ ASEAN Studies","curriculum_highlights":["IR Theory & ASEAN","International Law & Organizations","Diplomacy & Negotiation","Global Political Economy","Model UN & Diplomatic Simulation"],"career_paths":["Diplomat","International Organization Officer","Foreign Affairs Analyst","International Journalist","IR Researcher"],"tags":["International Relations","ASEAN","CU","Diplomacy"],"website_url":"https://www.polsci.chula.ac.th"},
  {"id":"cu_polsci_socio_ba","title_th":"หลักสูตรรัฐศาสตรบัณฑิต สาขาวิชาสังคมวิทยาและมานุษยวิทยา","title_en":"Bachelor of Arts Program in Sociology and Anthropology","degree_level":"ปริญญาตรี","degree_name":"ร.บ. (สังคมวิทยาและมานุษยวิทยา)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Political Science","faculty_th":"คณะรัฐศาสตร์","department":"Department of Sociology and Anthropology","department_th":"ภาควิชาสังคมวิทยาและมานุษยวิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นสังคมไทยร่วมสมัย ความเหลื่อมล้ำ เพศสภาพ และการวิจัยชาติพันธุ์","curriculum_highlights":["Contemporary Thai Society & Inequality","Gender & Cultural Anthropology","Qualitative Research & Fieldwork Bangkok","Urban Sociology","Thesis Sociology"],"career_paths":["Sociologist","Anthropologist","NGO Researcher","Social Policy Analyst","Academic"],"tags":["Sociology","Anthropology","CU"],"website_url":"https://www.polsci.chula.ac.th"},
  {"id":"cu_polsci_pubadmin_ba","title_th":"หลักสูตรรัฐศาสตรบัณฑิต สาขาวิชารัฐประศาสนศาสตร์","title_en":"Bachelor of Arts Program in Public Administration","degree_level":"ปริญญาตรี","degree_name":"ร.บ. (รัฐประศาสนศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Political Science","faculty_th":"คณะรัฐศาสตร์","department":"Department of Public Administration","department_th":"ภาควิชารัฐประศาสนศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นบริหารรัฐกิจ นโยบายสาธารณะ และรัฐบาลดิจิทัล","curriculum_highlights":["Public Administration & Bureaucracy Thai","Public Policy Analysis","Digital Government & Innovation","Local Governance & Decentralization","Internship Government Agencies"],"career_paths":["Government Officer (Palad)","Policy Analyst","Local Government Officer","Public Sector Consultant","Academic"],"tags":["Public Administration","CU","Digital Government"],"website_url":"https://www.polsci.chula.ac.th"},
  {"id":"cu_polsci_ma","title_th":"หลักสูตรรัฐศาสตรมหาบัณฑิต","title_en":"Master of Arts Program in Political Science","degree_level":"ปริญญาโท","degree_name":"ร.ม. (รัฐศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Political Science","faculty_th":"คณะรัฐศาสตร์","department":"Graduate Studies Polsci","department_th":"บัณฑิตศึกษา คณะรัฐศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"วิจัยการเมืองไทยเปรียบเทียบและนโยบายสาธารณะ","curriculum_highlights":["Comparative Politics Thailand-ASEAN","Policy Process & Evaluation","Research Methods Political Science","Thesis Political Science","Political Theory Seminar"],"career_paths":["Political Researcher","Policy Consultant","Academic","Think Tank Analyst","Government Advisor"],"tags":["Political Science","Master Degree","CU"],"website_url":"https://www.polsci.chula.ac.th"},
  {"id":"cu_polsci_phd","title_th":"หลักสูตรรัฐศาสตรดุษฎีบัณฑิต","title_en":"Doctor of Philosophy Program in Political Science","degree_level":"ปริญญาเอก","degree_name":"ร.ด. (รัฐศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Political Science","faculty_th":"คณะรัฐศาสตร์","department":"Doctoral Program Polsci","department_th":"สาขาวิชารัฐศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"240,000 บาท","description":"ผลิตนักรัฐศาสตร์วิจัยระดับแนวหน้า","curriculum_highlights":["Advanced Political Theory","Democracy & Authoritarianism Research","Dissertation Polsci","International Collaboration","Publication & Teaching"],"career_paths":["Professor Polsci","Political Research Director","Policy Maker","International Consultant","Think Tank Leader"],"tags":["Ph.D. Political Science","CU"],"website_url":"https://www.polsci.chula.ac.th"},
  # === FACULTY OF PSYCHOLOGY (5) ===
  {"id":"cu_psy_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาจิตวิทยา","title_en":"Bachelor of Arts Program in Psychology","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (จิตวิทยา)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Psychology","faculty_th":"คณะจิตวิทยา","department":"Department of Psychology","department_th":"ภาควิชาจิตวิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นจิตวิทยาทั่วไป พัฒนาการ สังคม คลินิกเบื้องต้น และการวิจัยจิตวิทยาไทย","curriculum_highlights":["General & Developmental Psychology","Social & Organizational Psychology","Psychological Testing & Assessment","Research Methods Psychology","Psychology Lab & Practicum"],"career_paths":["Psychologist Assistant","HR Officer","UX Researcher","Counseling Support","Research Assistant"],"tags":["Psychology","CU","Counseling"],"website_url":"https://www.psy.chula.ac.th"},
  {"id":"cu_psy_clin_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาจิตวิทยาคลินิก","title_en":"Master of Science Program in Clinical Psychology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (จิตวิทยาคลินิก)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Psychology","faculty_th":"คณะจิตวิทยา","department":"Clinical Psychology","department_th":"สาขาวิชาจิตวิทยาคลินิก","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"32,000 บาท","tuition_total":"128,000 บาท","description":"ผลิตนักจิตวิทยาคลินิกที่เชี่ยวชาญการประเมิน วินิจฉัย และบำบัดขั้นต้น","curriculum_highlights":["Psychopathology & Diagnosis DSM-5","Psychotherapy & CBT Basics","Psychological Assessment & Report","Clinical Practicum CU Hospital","Thesis Clinical Psychology"],"career_paths":["Clinical Psychologist (supervised)","Therapist","Mental Health Specialist","Hospital Psychologist","Academic Clinical"],"tags":["Clinical Psychology","CU","CBT"],"website_url":"https://www.psy.chula.ac.th"},
  {"id":"cu_psy_org_msc","title_th":"หลักสูตรศิลปศาสตรมหาบัณฑิต สาขาวิชาจิตวิทยาอุตสาหกรรมและองค์การ","title_en":"Master of Arts Program in Industrial and Organizational Psychology","degree_level":"ปริญญาโท","degree_name":"ศศ.ม. (จิตวิทยาอุตสาหกรรมและองค์การ)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Psychology","faculty_th":"คณะจิตวิทยา","department":"I/O Psychology","department_th":"สาขาวิชาจิตวิทยาอุตสาหกรรมและองค์การ","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"32,000 บาท","tuition_total":"128,000 บาท","description":"เน้นจิตวิทยาองค์การ การคัดเลือกบุคลากร และการพัฒนาองค์การยุคใหม่","curriculum_highlights":["Personnel Selection & Assessment Center","Organization Development & Change","Talent Management & Coaching","Research I/O Psychology","Practicum Corporate"],"career_paths":["I/O Psychologist","Talent Management Specialist","HR Consultant","Organization Development Consultant","People Analytics Specialist"],"tags":["I/O Psychology","HR","CU"],"website_url":"https://www.psy.chula.ac.th"},
  {"id":"cu_psy_social_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาจิตวิทยาสังคม","title_en":"Master of Science Program in Social Psychology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (จิตวิทยาสังคม)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Psychology","faculty_th":"คณะจิตวิทยา","department":"Social Psychology","department_th":"สาขาวิชาจิตวิทยาสังคม","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"วิจัยจิตวิทยาสังคมไทย อคติ การเมือง และสื่อสังคม","curriculum_highlights":["Social Cognition & Attitudes","Political Psychology Thailand","Social Media & Behavior","Thesis Social Psychology","Community Psychology Fieldwork"],"career_paths":["Social Psychology Researcher","Behavioral Analyst","Media Researcher","NGO Program Designer","Academic"],"tags":["Social Psychology","CU"],"website_url":"https://www.psy.chula.ac.th"},
  {"id":"cu_psy_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาจิตวิทยา","title_en":"Doctor of Philosophy Program in Psychology","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (จิตวิทยา)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Psychology","faculty_th":"คณะจิตวิทยา","department":"Doctoral Program Psychology","department_th":"สาขาวิชาจิตวิทยา","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"240,000 บาท","description":"วิจัยจิตวิทยาขั้นสูงเพื่อสร้างองค์ความรู้จิตวิทยาไทย","curriculum_highlights":["Advanced Research Methods Psychology","Cultural Psychology Thailand","Dissertation Psychology","International Lab & Publication","Teaching Psychology"],"career_paths":["Psychology Professor","Research Director","Policy Behavioral Scientist","Consultant","Clinical Leader"],"tags":["Ph.D. Psychology","CU"],"website_url":"https://www.psy.chula.ac.th"},
  # === FACULTY OF PHARMACEUTICAL SCIENCES (5) ===
  {"id":"cu_pharm_bsc","title_th":"หลักสูตรเภสัชศาสตรบัณฑิต","title_en":"Bachelor of Pharmacy Program","degree_level":"ปริญญาตรี","degree_name":"ภ.บ. (เภสัชศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Pharmaceutical Sciences","faculty_th":"คณะเภสัชศาสตร์","department":"Faculty of Pharmaceutical Sciences","department_th":"คณะเภสัชศาสตร์","program_type":"ภาคปกติ","duration_years":"6 ปี","total_credits":"210 หน่วยกิต","tuition_per_semester":"25,000 บาท","tuition_total":"300,000 บาท","description":"ผลิตเภสัชกรที่เชี่ยวชาญการบริบาลทางเภสัชกรรม อุตสาหกรรมยา และเภสัชกรรมปฐมภูมิ","curriculum_highlights":["Pharmaceutical Care & Clinical Pharmacy","Industrial Pharmacy & GMP","Pharmacology & Toxicology","Herbal & Natural Products","Hospital Pharmacy Clerkship"],"career_paths":["Pharmacist","Clinical Pharmacist","Industrial Pharmacist","Community Pharmacist","Pharma R&D"],"tags":["Pharmacy","CU","Pharmaceutical Care"],"website_url":"https://www.pharm.chula.ac.th"},
  {"id":"cu_pharm_pharmcare_msc","title_th":"หลักสูตรเภสัชศาสตรมหาบัณฑิต สาขาวิชาเภสัชกรรมคลินิก","title_en":"Master of Science in Pharmacy Program in Clinical Pharmacy","degree_level":"ปริญญาโท","degree_name":"ภ.ม. (เภสัชกรรมคลินิก)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Pharmaceutical Sciences","faculty_th":"คณะเภสัชศาสตร์","department":"Clinical Pharmacy","department_th":"ภาควิชาเภสัชกรรมคลินิก","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"วิจัยเภสัชกรรมคลินิก เภสัชพันธุศาสตร์ และการใช้ยาอย่างสมเหตุผล","curriculum_highlights":["Clinical Pharmacokinetics & Pharmacogenomics","Rational Drug Use & Pharmacovigilance","Thesis Clinical Pharmacy","Hospital Rotation CU","Pharmacy Research Methods"],"career_paths":["Clinical Pharmacist Specialist","Pharmacovigilance Officer","Hospital Pharmacy Leader","Academic Pharmacist","Researcher"],"tags":["Clinical Pharmacy","CU","Master Degree"],"website_url":"https://www.pharm.chula.ac.th"},
  {"id":"cu_pharm_indus_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเภสัชอุตสาหกรรม","title_en":"Master of Science Program in Industrial Pharmacy","degree_level":"ปริญญาโท","degree_name":"วท.ม. (เภสัชอุตสาหกรรม)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Pharmaceutical Sciences","faculty_th":"คณะเภสัชศาสตร์","department":"Industrial Pharmacy","department_th":"ภาควิชาเภสัชอุตสาหกรรม","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"วิจัยการตั้งตำรับยา นาโนเภสัชภัณฑ์ และการควบคุมคุณภาพยาตาม GMP/PIC/S","curriculum_highlights":["Pharmaceutical Formulation & Nanotech","GMP & Quality by Design (QbD)","Drug Delivery Systems","Thesis Industrial Pharmacy","Industrial Internship Pharma Plant"],"career_paths":["Industrial Pharmacist","Formulation Scientist","QA/QC Manager Pharma","Regulatory Affairs Specialist","Pharma Entrepreneur"],"tags":["Industrial Pharmacy","CU","GMP"],"website_url":"https://www.pharm.chula.ac.th"},
  {"id":"cu_pharm_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาเภสัชศาสตร์","title_en":"Doctor of Philosophy Program in Pharmaceutical Sciences","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (เภสัชศาสตร์)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Pharmaceutical Sciences","faculty_th":"คณะเภสัชศาสตร์","department":"Doctoral Program","department_th":"สาขาวิชาเภสัชศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"210,000 บาท","description":"วิจัยเภสัชศาสตร์ขั้นสูงระดับนานาชาติ","curriculum_highlights":["Advanced Drug Discovery & Design","Pharmacogenomics & Precision Medicine","Dissertation Pharmaceutical Sciences","International Collaboration & Publication","Teaching Pharmacy"],"career_paths":["Pharmacy Professor","Pharma R&D Director","Drug Discovery Scientist","Regulatory Leader","Academic"],"tags":["Ph.D. Pharmacy","CU","Drug Discovery"],"website_url":"https://www.pharm.chula.ac.th"},
  {"id":"cu_pharm_cosmetic_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์เครื่องสำอาง","title_en":"Master of Science Program in Cosmetic Science","degree_level":"ปริญญาโท","degree_name":"วท.ม. (วิทยาศาสตร์เครื่องสำอาง)","university":"Chulalongkorn University","university_th":"จุฬาลงกรณ์มหาวิทยาลัย","faculty":"Faculty of Pharmaceutical Sciences","faculty_th":"คณะเภสัชศาสตร์","department":"Cosmetic Science","department_th":"สาขาวิชาวิทยาศาสตร์เครื่องสำอาง","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"32,000 บาท","tuition_total":"128,000 บาท","description":"วิจัยเครื่องสำอาง สมุนไพรไทย และนวัตกรรมความงามยั่งยืน","curriculum_highlights":["Cosmetic Formulation & Stability","Thai Herbal Cosmetics & Natural Products","Cosmetic Safety & Regulation (FDA)","Thesis Cosmetic Science","Internship Cosmetic Industry"],"career_paths":["Cosmetic Scientist","R&D Cosmetics","Product Development Manager","Regulatory Cosmetics","Beauty Entrepreneur"],"tags":["Cosmetic Science","CU","Herbal"],"website_url":"https://www.pharm.chula.ac.th"},
]
print(f"Prepared {len(CU_COURSES)} CU courses")
out=pathlib.Path("backend/data/courses_new/courses_cu_expansion1.json")
with open(out,'w',encoding='utf-8') as f:
    json.dump(CU_COURSES,f,ensure_ascii=False,indent=2)
print(f"Saved to {out}")
Base.metadata.create_all(bind=engine)
session=SessionLocal()
ins=upd=0
for c in CU_COURSES:
    et=emb_text(c)
    try:
        vec=embedding_service.get_embedding(et)
        if vec and len(vec)!=768:
            vec=None
    except Exception as e:
        print(f"emb fail {c['id']}: {e}")
        vec=None
    ex=session.query(CourseDB).filter_by(id=c["id"]).first()
    if ex:
        for k,v in c.items():
            setattr(ex,k,v)
        ex.embedding_text=et
        if vec:
            ex.embedding=vec
        upd+=1
        print(f"Updated {c['id']}")
    else:
        db=CourseDB(id=c["id"], title_th=c["title_th"], title_en=c.get("title_en"), degree_level=c["degree_level"], degree_name=c.get("degree_name"), university=c["university"], university_th=c["university_th"], faculty=c["faculty"], faculty_th=c["faculty_th"], department=c.get("department"), department_th=c.get("department_th"), program_type=c.get("program_type","ภาคปกติ"), duration_years=c.get("duration_years"), total_credits=c.get("total_credits"), tuition_per_semester=c.get("tuition_per_semester"), tuition_total=c.get("tuition_total"), description=c.get("description"), curriculum_highlights=c.get("curriculum_highlights",[]), career_paths=c.get("career_paths",[]), tags=c.get("tags",[]), website_url=c.get("website_url"), embedding_text=et, embedding=vec if vec else None)
        session.add(db)
        ins+=1
        print(f"Inserted {c['id']} emb={'OK' if vec else 'NULL'}")
    if (ins+upd)%20==0:
        session.commit()
session.commit()
print(f"Done CU ins={ins} upd={upd}")
from sqlalchemy import text as t
with engine.connect() as conn:
    total=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Chulalongkorn University'")).scalar()
    print(f"CU total now: {total}")
    tot_all=conn.execute(t("SELECT COUNT(*) FROM courses")).scalar()
    print(f"DB total: {tot_all}")
session.close()
