# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')
import os, json, pathlib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.core.database import SessionLocal, engine, Base
from app.models.db_models import CourseDB
from app.core.embedding_service import embedding_service
def emb_text(c):
    hl=", ".join(c.get("curriculum_highlights",[]))
    cp=", ".join(c.get("career_paths",[]))
    tags=", ".join(c.get("tags",[]))
    return f"{c['title_th']} {c.get('title_en','')}. University: {c['university']} {c['university_th']}. Faculty: {c['faculty']} {c['faculty_th']}. Department: {c.get('department','')} {c.get('department_th','')}. Degree: {c['degree_level']} {c.get('degree_name','')}. Description: {c.get('description','')}. Highlights: {hl}. Careers: {cp}. Tags: {tags}."
NEW3 = [
  # === MEDICINE expansion (4) ===
  {"id":"kku_med_nurse_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเวชกิจฉุกเฉิน","title_en":"Bachelor of Science Program in Emergency Medical Operation","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เวชกิจฉุกเฉิน)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Medicine","faculty_th":"คณะแพทยศาสตร์","department":"Department of Emergency Medicine","department_th":"ภาควิชาเวชศาสตร์ฉุกเฉิน","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"176,000 บาท","description":"ผลิตนักปฏิบัติการฉุกเฉินการแพทย์ (Paramedic) ที่เชี่ยวชาญการกู้ชีพขั้นสูง การจัดการภัยพิบัติ และการแพทย์ฉุกเฉินชุมชนอีสาน","curriculum_highlights":["Advanced Paramedic & ACLS","Disaster Medicine & Triage Isan","Emergency Medical System (EMS)","Trauma & Critical Care Transport","Clinical Practicum at Srinagarind ER"],"career_paths":["Paramedic","Emergency Medical Officer","Disaster Response Coordinator","EMS Manager","Emergency Medical Instructor"],"tags":["Emergency Medicine","Paramedic","KKU","Medicine"],"website_url":"https://md.kku.ac.th"},
  {"id":"kku_med_physician_assist_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาผู้ช่วยแพทย์","title_en":"Bachelor of Science Program in Physician Assistant","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ผู้ช่วยแพทย์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Medicine","faculty_th":"คณะแพทยศาสตร์","department":"Department of Physician Assistant","department_th":"สาขาวิชาผู้ช่วยแพทย์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"24,000 บาท","tuition_total":"192,000 บาท","description":"ผลิตผู้ช่วยแพทย์ที่ช่วยแพทย์ตรวจวินิจฉัย รักษาเบื้องต้น และดูแลผู้ป่วยในโรงพยาบาลชุมชนที่ขาดแคลนแพทย์อีสาน","curriculum_highlights":["Clinical Diagnosis & Treatment","Family Medicine & Primary Care","Pharmacology for PA","Community Hospital Rotation Isan","PA Clinical Clerkship"],"career_paths":["Physician Assistant","Primary Care PA","Hospital PA","Community Health PA","Clinical Coordinator"],"tags":["Physician Assistant","KKU","Primary Care"],"website_url":"https://md.kku.ac.th"},
  {"id":"kku_med_medsci_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาวิทยาศาสตร์การแพทย์","title_en":"Doctor of Philosophy Program in Medical Sciences","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (วิทยาศาสตร์การแพทย์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Medicine","faculty_th":"คณะแพทยศาสตร์","department":"Graduate Studies Medicine","department_th":"บัณฑิตศึกษา คณะแพทยศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"38,000 บาท","tuition_total":"228,000 บาท","description":"วิจัยขั้นสูงด้านมะเร็งท่อน้ำดี พยาธิใบไม้ตับ และโรคเขตร้อนลุ่มน้ำโขงอันเป็นจุดเด่น มข.","curriculum_highlights":["Cholangiocarcinoma & Liver Fluke Research Mekong","Tropical Disease Genomics","Precision Medicine & Translational Research","Dissertation in Medical Sciences","International Publication"],"career_paths":["Medical Scientist","Research Professor","Biomedical Research Leader","Pharma R&D Director","International Research Collaborator"],"tags":["Ph.D. Medical Sciences","Cholangiocarcinoma","KKU"],"website_url":"https://md.kku.ac.th"},
  {"id":"kku_med_family_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาเวชศาสตร์ครอบครัว","title_en":"Doctor of Philosophy Program in Family Medicine","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (เวชศาสตร์ครอบครัว)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Medicine","faculty_th":"คณะแพทยศาสตร์","department":"Department of Family Medicine","department_th":"ภาควิชาเวชศาสตร์ครอบครัว","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"38,000 บาท","tuition_total":"228,000 บาท","description":"วิจัยระบบสุขภาพปฐมภูมิอีสาน เวชศาสตร์ครอบครัว และสุขภาวะชุมชน","curriculum_highlights":["Family Medicine Systems Research Isan","Primary Care Implementation Science","Community Health Equity","Dissertation Family Medicine","Leadership in Primary Care"],"career_paths":["Family Medicine Professor","Primary Care Research Director","Health Systems Leader","Policy Maker","Academic Family Doctor"],"tags":["Ph.D. Family Medicine","Primary Care","KKU"],"website_url":"https://md.kku.ac.th"},
  # === ENGINEERING expansion (8) ===
  {"id":"kku_eng_civil_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมโยธา","title_en":"Bachelor of Engineering Program in Civil Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมโยธา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Civil Engineering","department_th":"ภาควิชาวิศวกรรมโยธา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"142 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นโครงสร้าง คอนกรีตเสริมเหล็ก ปฐพีกลศาสตร์ และการจัดการน้ำลุ่มน้ำโขง-ชี-มูล","curriculum_highlights":["Structural Analysis & Concrete Design","Geotechnical & Foundation Engineering","Water Resources & Hydrology Mekong","Construction Management & BIM","Civil Lab & Field Practice"],"career_paths":["Civil Engineer","Structural Engineer","Geotechnical Engineer","Construction Manager","Water Resources Engineer"],"tags":["Civil Engineering","KKU","Mekong"],"website_url":"https://www.en.kku.ac.th"},
  {"id":"kku_eng_env_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมสิ่งแวดล้อม","title_en":"Bachelor of Engineering Program in Environmental Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมสิ่งแวดล้อม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Environmental Engineering","department_th":"ภาควิชาวิศวกรรมสิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นการจัดการน้ำเสีย อากาศเสีย ขยะ และ EIA สำหรับอุตสาหกรรมอีสาน","curriculum_highlights":["Water & Wastewater Treatment Design","Air Pollution Control & PM2.5","Solid Waste & Hazardous Waste","EIA & Environmental Law","Environmental Lab Isan"],"career_paths":["Environmental Engineer","EIA Consultant","Pollution Control Engineer","Waste Management Specialist","Sustainability Consultant"],"tags":["Environmental Engineering","EIA","KKU"],"website_url":"https://www.en.kku.ac.th"},
  {"id":"kku_eng_ie_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมอุตสาหการ","title_en":"Bachelor of Engineering Program in Industrial Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมอุตสาหการ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Industrial Engineering","department_th":"ภาควิชาวิศวกรรมอุตสาหการ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้น Lean, Six Sigma, โลจิสติกส์ และ Smart Factory สำหรับอุตสาหกรรมอีสาน","curriculum_highlights":["Lean & Six Sigma Quality","Supply Chain & Logistics Isan","Operations Research & Simulation","Smart Factory & Automation","Industrial Plant Design"],"career_paths":["Industrial Engineer","Quality Engineer","Supply Chain Manager","Lean Consultant","Factory Manager"],"tags":["Industrial Engineering","Lean","KKU"],"website_url":"https://www.en.kku.ac.th"},
  {"id":"kku_eng_agri_beng2","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเกษตร (เพิ่มเติม)","title_en":"Bachelor of Engineering Program in Agricultural Engineering (2nd program)","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมเกษตร)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Agricultural Engineering","department_th":"ภาควิชาวิศวกรรมเกษตร","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นเครื่องจักรกลเกษตร ระบบชลประทานอัจฉริยะ และเกษตรแม่นยำสูงอีสาน","curriculum_highlights":["Farm Machinery & Precision Ag Drones","Smart Irrigation Systems Isan","Post-Harvest Engineering","Renewable Energy for Agriculture","Agricultural Automation Lab"],"career_paths":["Agricultural Engineer","Precision Ag Specialist","Irrigation Engineer","Farm Machinery Designer","Smart Farm Engineer"],"tags":["Agricultural Engineering","Precision Agriculture","KKU"],"website_url":"https://www.en.kku.ac.th"},
  {"id":"kku_eng_bio_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมชีวการแพทย์","title_en":"Bachelor of Engineering Program in Biomedical Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมชีวการแพทย์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Biomedical Engineering","department_th":"ภาควิชา​วิศวกรรมชีวการแพทย์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"176,000 บาท","description":"บูรณาการวิศวกรรมและการแพทย์ อุปกรณ์การแพทย์ ภาพทางการแพทย์ และหุ่นยนต์ผ่าตัด","curriculum_highlights":["Medical Device Design & FDA","Biomedical Imaging (CT/MRI)","Biomechanics & Biomaterials","Rehabilitation Robotics","Clinical Internship Srinagarind"],"career_paths":["Biomedical Engineer","Medical Device Designer","Clinical Engineer","Rehab Tech Specialist","MedTech Entrepreneur"],"tags":["Biomedical Engineering","KKU","MedTech"],"website_url":"https://www.en.kku.ac.th"},
  {"id":"kku_eng_com_inter_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์ (หลักสูตรนานาชาติ)","title_en":"Bachelor of Engineering Program in Computer Engineering (International Program)","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมคอมพิวเตอร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Computer Engineering","department_th":"ภาควิชาวิศวกรรมคอมพิวเตอร์","program_type":"นานาชาติ","duration_years":"4 ปี","total_credits":"135 หน่วยกิต","tuition_per_semester":"45,000 บาท","tuition_total":"360,000 บาท","description":"หลักสูตรนานาชาติ 100% English เน้น AI, Cloud, Cybersecurity และสหกิจศึกษานานาชาติ","curriculum_highlights":["International AI & Cloud Systems","Cybersecurity & Blockchain (English)","Global Software Engineering","International Co-op Abroad","Capstone International Project"],"career_paths":["International Software Engineer","Cloud Architect","Cybersecurity Specialist","Global IT Consultant","International Graduate Studies"],"tags":["Computer Engineering","International Program","KKU"],"website_url":"https://www.en.kku.ac.th"},
  {"id":"kku_eng_electrical_meng","title_th":"หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมไฟฟ้า","title_en":"Master of Engineering Program in Electrical Engineering","degree_level":"ปริญญาโท","degree_name":"วศ.ม. (วิศวกรรมไฟฟ้า)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Electrical Engineering","department_th":"ภาควิชาวิศวกรรมไฟฟ้า","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"26,000 บาท","tuition_total":"104,000 บาท","description":"วิจัยระบบไฟฟ้ากำลังอัจฉริยะ Smart Grid และพลังงานทดแทนอีสาน","curriculum_highlights":["Smart Grid & Renewable Integration Isan","Power Electronics & Microgrid","High Voltage & Protection Systems","Thesis Electrical Engineering","Smart Energy Lab"],"career_paths":["Electrical Research Engineer","Smart Grid Specialist","Power Systems Consultant","Academic Researcher","Energy Policy Analyst"],"tags":["Electrical Engineering","Smart Grid","KKU","Master Degree"],"website_url":"https://www.en.kku.ac.th"},
  {"id":"kku_eng_mech_meng","title_th":"หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมเครื่องกล","title_en":"Master of Engineering Program in Mechanical Engineering","degree_level":"ปริญญาโท","degree_name":"วศ.ม. (วิศวกรรมเครื่องกล)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Mechanical Engineering","department_th":"ภาควิชาวิศวกรรมเครื่องกล","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"26,000 บาท","tuition_total":"104,000 บาท","description":"วิจัยยานยนต์ไฟฟ้า EV, พลังงาน และหุ่นยนต์อุตสาหกรรมอีสาน","curriculum_highlights":["EV Powertrain & Battery Systems Isan","Thermal & Fluid Advanced","Robotics & Mechatronics","Thesis Mechanical Engineering","EV Lab KKU"],"career_paths":["Mechanical Research Engineer","EV Systems Engineer","Robotics Specialist","Academic Mechanical","R&D Manager"],"tags":["Mechanical Engineering","EV","KKU","Master Degree"],"website_url":"https://www.en.kku.ac.th"},
  # === SCIENCE grad expansion (4) ===
  {"id":"kku_sci_bio_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาชีววิทยา","title_en":"Master of Science Program in Biology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (ชีววิทยา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Biology","department_th":"ภาควิชาชีววิทยา","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"80,000 บาท","description":"วิจัยความหลากหลายทางชีวภาพลุ่มน้ำโขงและชีววิทยาโมเลกุล","curriculum_highlights":["Mekong Biodiversity Research","Molecular Ecology","Conservation Genetics","Thesis Biology","Field Research Mekong"],"career_paths":["Biology Researcher","Conservation Biologist","Ecologist","Academic","Lab Scientist"],"tags":["Biology","Master Degree","KKU","Mekong"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_chem_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเคมี","title_en":"Master of Science Program in Chemistry","degree_level":"ปริญญาโท","degree_name":"วท.ม. (เคมี)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Chemistry","department_th":"ภาควิชาเคมี","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"88,000 บาท","description":"วิจัยเคมีวัสดุ นาโน และเคมีวิเคราะห์เพื่ออุตสาหกรรมอีสาน","curriculum_highlights":["Materials & Nanochemistry","Analytical Chemistry Advanced","Thesis Chemistry","Polymer Research Isan","Nanotech Lab"],"career_paths":["Chemist Researcher","Materials Scientist","Analytical Lab Manager","Academic Chemist","R&D Specialist"],"tags":["Chemistry","Master Degree","KKU"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_physics_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาฟิสิกส์","title_en":"Master of Science Program in Physics","degree_level":"ปริญญาโท","degree_name":"วท.ม. (ฟิสิกส์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Physics","department_th":"ภาควิชาฟิสิกส์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"80,000 บาท","description":"วิจัยฟิสิกส์วัสดุ พลังงาน และฟิสิกส์ประยุกต์อีสาน","curriculum_highlights":["Condensed Matter Physics Isan","Renewable Energy Physics Lab","Computational Physics Advanced","Thesis Physics","Materials Characterization"],"career_paths":["Physics Researcher","Energy Physicist","Materials Analyst","Academic","Data Scientist Physics"],"tags":["Physics","Master Degree","KKU"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_env_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์สิ่งแวดล้อม","title_en":"Master of Science Program in Environmental Science","degree_level":"ปริญญาโท","degree_name":"วท.ม. (วิทยาศาสตร์สิ่งแวดล้อม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Environmental Science","department_th":"ภาควิชาวิทยาศาสตร์สิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"80,000 บาท","description":"วิจัยมลพิษ PM2.5 และคุณภาพน้ำโขง","curriculum_highlights":["PM2.5 & Mekong Water Quality Research","EIA Advanced & HIA","Climate Change Isan","Thesis Environmental Science","GIS Environmental Lab"],"career_paths":["Environmental Researcher","EIA Specialist Senior","Climate Analyst","Academic Environmental","Consultant"],"tags":["Environmental Science","Master Degree","KKU"],"website_url":"https://sc.kku.ac.th"},
  # === INTERDISCIPLINARY Nong Khai expansion (5) ===
  {"id":"kku_is_tourism_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาการท่องเที่ยวและการโรงแรม","title_en":"Bachelor of Arts Program in Tourism and Hospitality","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (การท่องเที่ยวและการโรงแรม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Interdisciplinary Studies","faculty_th":"คณะสหวิทยาการ","department":"Department of Tourism","department_th":"สาขาวิชาการท่องเที่ยวและการโรงแรม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการท่องเที่ยวลุ่มน้ำโขง การท่องเที่ยวเชิงวัฒนธรรมอีสาน และการโรงแรมข้ามพรมแดน ไทย-ลาว","curriculum_highlights":["Mekong Tourism & Cross-Border Hospitality","Isan Cultural Tourism Management","Hotel Operations & Service Design","Tourism Digital Marketing GMS","Internship in Mekong Hotels"],"career_paths":["Tourism Manager GMS","Hotel Manager","Cultural Tourism Entrepreneur","Tour Operator Mekong","Hospitality Consultant"],"tags":["Tourism","Hospitality","Mekong","KKU","Nong Khai"],"website_url":"https://is.kku.ac.th"},
  {"id":"kku_is_law_ba","title_th":"หลักสูตรนิติศาสตรบัณฑิต สาขาวิชานิติศาสตร์ (วิทยาเขตหนองคาย)","title_en":"Bachelor of Laws Program (Nong Khai Campus)","degree_level":"ปริญญาตรี","degree_name":"น.บ. (นิติศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Interdisciplinary Studies","faculty_th":"คณะสหวิทยาการ","department":"Department of Law Nong Khai","department_th":"สาขาวิชานิติศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"135 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นกฎหมายปกครองท้องถิ่น กฎหมายชายแดน และกฎหมายการค้าระหว่างประเทศลุ่มน้ำโขง","curriculum_highlights":["Local Administrative Law Nong Khai","Cross-Border Trade Law Mekong","Community Law Clinic","Moot Court Nong Khai","Internship Border Legal Aid"],"career_paths":["Border Lawyer","Local Government Legal Officer","Cross-Border Trade Counsel","Community Lawyer","Graduate Law"],"tags":["Law","Nong Khai","Border Law","KKU"],"website_url":"https://is.kku.ac.th"},
  {"id":"kku_is_logistics_bba","title_th":"หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาโลจิสติกส์และการค้าระหว่างประเทศ","title_en":"Bachelor of Business Administration Program in Logistics and International Trade","degree_level":"ปริญญาตรี","degree_name":"บธ.บ. (โลจิสติกส์และการค้าระหว่างประเทศ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Interdisciplinary Studies","faculty_th":"คณะสหวิทยาการ","department":"Department of Business","department_th":"สาขาวิชาบริหารธุรกิจ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นโลจิสติกส์ข้ามพรมแดน ไทย-ลาว-เวียดนาม ระเบียงเศรษฐกิจตะวันออก-ตะวันตก (EWEC)","curriculum_highlights":["Cross-Border Logistics EWEC (Thailand-Laos-Vietnam)","Customs & Border Trade Procedures","Warehouse & Cold Chain for Mekong","Supply Chain Analytics","Internship Cross-Border Logistics"],"career_paths":["Cross-Border Logistics Manager","Customs Officer","Supply Chain Coordinator","Freight Forwarder GMS","Trade Analyst"],"tags":["Logistics","Cross-Border","EWEC","KKU","Nong Khai"],"website_url":"https://is.kku.ac.th"},
  {"id":"kku_is_fisheries_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาประมง (วิทยาเขตหนองคาย)","title_en":"Bachelor of Science Program in Fisheries (Nong Khai Campus)","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ประมง)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Interdisciplinary Studies","faculty_th":"คณะสหวิทยาการ","department":"Department of Fisheries Nong Khai","department_th":"สาขาวิชาประมง","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นประมงน้ำจืดโขง การเพาะเลี้ยงสัตว์น้ำโขง และการจัดการทรัพยากรประมงลุ่มน้ำโขง","curriculum_highlights":["Mekong Freshwater Aquaculture","Mekong Fisheries Resource Management","Fish Breeding & Genetics Mekong","Fish Processing Mekong","Fieldwork Mekong Fisheries"],"career_paths":["Mekong Fisheries Officer","Aquaculture Manager","Fisheries Researcher","Fish Processing Entrepreneur","Extension Officer Fisheries"],"tags":["Fisheries","Mekong","KKU","Nong Khai"],"website_url":"https://is.kku.ac.th"},
  {"id":"kku_is_account_bba","title_th":"หลักสูตรบัญชีบัณฑิต (วิทยาเขตหนองคาย)","title_en":"Bachelor of Accountancy Program (Nong Khai Campus)","degree_level":"ปริญญาตรี","degree_name":"บช.บ. (การบัญชี)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Interdisciplinary Studies","faculty_th":"คณะสหวิทยาการ","department":"Department of Accountancy Nong Khai","department_th":"สาขาวิชาการบัญชี","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นบัญชีธุรกิจชายแดน การบัญชีโลจิสติกส์ และการสอบบัญชีอีสาน","curriculum_highlights":["Border Trade Accounting","Logistics Accounting & Costing","Auditing & Taxation Isan","Accounting Software & ERP","Internship Cross-Border Firms"],"career_paths":["Accountant","Auditor","Tax Officer","Logistics Accountant","Entrepreneur"],"tags":["Accountancy","Nong Khai","KKU"],"website_url":"https://is.kku.ac.th"},
  # === DENTISTRY/MED expansion (2) ===
  {"id":"kku_dent_ortho_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาทันตกรรมจัดฟัน","title_en":"Master of Science Program in Orthodontics","degree_level":"ปริญญาโท","degree_name":"วท.ม. (ทันตกรรมจัดฟัน)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Dentistry","faculty_th":"คณะทันตแพทยศาสตร์","department":"Department of Orthodontics","department_th":"ภาควิชาทันตกรรมจัดฟัน","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"60,000 บาท","tuition_total":"360,000 บาท","description":"ผลิตทันตแพทย์จัดฟันเชี่ยวชาญ เทคนิคจัดฟันใส และทันตกรรมดิจิทัล","curriculum_highlights":["Advanced Orthodontic Mechanics","Clear Aligner Technology & Digital Ortho","Craniofacial Growth & Development","Orthodontic Research Thesis","Clinical Ortho Residency"],"career_paths":["Orthodontist","Clear Aligner Specialist","Private Ortho Clinic Owner","Dental Specialist Hospital","Academic Ortho"],"tags":["Orthodontics","Dentistry","KKU","Clear Aligner"],"website_url":"https://dentistry.kku.ac.th"},
  {"id":"kku_dent_implant_dip","title_th":"หลักสูตรประกาศนียบัตรบัณฑิตชั้นสูง สาขาวิชาทันตกรรมรากเทียม","title_en":"Higher Graduate Diploma Program in Implant Dentistry","degree_level":"ประกาศนียบัตรบัณฑิต (ชั้นสูง)","degree_name":"ป.บัณฑิตชั้นสูง (ทันตกรรมรากเทียม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Dentistry","faculty_th":"คณะทันตแพทยศาสตร์","department":"Department of Implant Dentistry","department_th":"ภาควิชาทันตกรรมรากเทียม","program_type":"ภาคปกติ","duration_years":"1 ปี","total_credits":"24 หน่วยกิต","tuition_per_semester":"90,000 บาท","tuition_total":"180,000 บาท","description":"เน้นทันตกรรมรากเทียมดิจิทัล การวางแผนด้วย CT และการผ่าตัดรากเทียม","curriculum_highlights":["Digital Implant Planning (CT-Guided)","Implant Surgery & Prosthodontics","Bone Grafting & Tissue Engineering","Implant Complications Management","Clinical Implant Residency"],"career_paths":["Implant Dentist","Private Implant Clinic","Hospital Implant Specialist","Implant Educator","Dental Entrepreneur"],"tags":["Implant Dentistry","KKU","Diploma"],"website_url":"https://dentistry.kku.ac.th"},
]

print(f"Prepared {len(NEW3)} courses wave3")
import pathlib, json
out = pathlib.Path("backend/data/courses_new/courses_kku_full_expansion3.json")
with open(out, 'w', encoding='utf-8') as f:
    json.dump(NEW3, f, ensure_ascii=False, indent=2)
print(f"Saved to {out}")
Base.metadata.create_all(bind=engine)
session = SessionLocal()
ins=upd=0
for c in NEW3:
    et=emb_text(c)
    try:
        vec=embedding_service.get_embedding(et)
        if vec and len(vec)!=768:
            vec=None
    except Exception as e:
        print(f"emb fail {c['id']}: {e}")
        vec=None
    ex=session.query(CourseDB).filter_by(id=c["id"]).first()
    if ex:
        for k,v in c.items():
            setattr(ex,k,v)
        ex.embedding_text=et
        if vec:
            ex.embedding=vec
        upd+=1
        print(f"Updated {c['id']}")
    else:
        db=CourseDB(id=c["id"], title_th=c["title_th"], title_en=c.get("title_en"), degree_level=c["degree_level"], degree_name=c.get("degree_name"), university=c["university"], university_th=c["university_th"], faculty=c["faculty"], faculty_th=c["faculty_th"], department=c.get("department"), department_th=c.get("department_th"), program_type=c.get("program_type","ภาคปกติ"), duration_years=c.get("duration_years"), total_credits=c.get("total_credits"), tuition_per_semester=c.get("tuition_per_semester"), tuition_total=c.get("tuition_total"), description=c.get("description"), curriculum_highlights=c.get("curriculum_highlights",[]), career_paths=c.get("career_paths",[]), tags=c.get("tags",[]), website_url=c.get("website_url"), embedding_text=et, embedding=vec if vec else None)
        session.add(db)
        ins+=1
        print(f"Inserted {c['id']} emb={'OK' if vec else 'NULL'}")
    if (ins+upd)%20==0:
        session.commit()
session.commit()
print(f"Done ins={ins} upd={upd}")
from sqlalchemy import text
with engine.connect() as conn:
    tot=conn.execute(text("SELECT COUNT(*) FROM courses WHERE university='Khon Kaen University'")).scalar()
    print(f"KKU total now: {tot}")
    tot_all=conn.execute(text("SELECT COUNT(*) FROM courses")).scalar()
    print(f"DB total all: {tot_all}")
session.close()
