# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')
import os, json, pathlib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.core.database import SessionLocal, engine, Base
from app.models.db_models import CourseDB
from app.core.embedding_service import embedding_service

def build_embedding_text(c):
    hl = ", ".join(c.get("curriculum_highlights", []))
    cp = ", ".join(c.get("career_paths", []))
    tags = ", ".join(c.get("tags", []))
    return f"{c['title_th']} {c.get('title_en','')}. University: {c['university']} {c['university_th']}. Faculty: {c['faculty']} {c['faculty_th']}. Department: {c.get('department','')} {c.get('department_th','')}. Degree: {c['degree_level']} {c.get('degree_name','')}. Description: {c.get('description','')}. Highlights: {hl}. Careers: {cp}. Tags: {tags}."

# Courses to add - 110 new KKU courses covering missing faculties to reach ~175 total (65+110)
# Designed to match real KKU faculties: https://www.kku.ac.th/academic/
NEW_KKU_COURSES = [
  # === FACULTY OF AGRICULTURE (เพิ่ม 7) ===
  {"id":"kku_agri_agron_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาพืชศาสตร์","title_en":"Bachelor of Science Program in Agronomy","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (พืชศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Agriculture","faculty_th":"คณะเกษตรศาสตร์","department":"Department of Agronomy","department_th":"ภาควิชาพืชศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"134 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"มุ่งเน้นการผลิตบัณฑิตที่มีความรู้ด้านการปรับปรุงพันธุ์พืช เทคโนโลยีเมล็ดพันธุ์ ระบบการปลูกพืชแม่นยำ และการเกษตรอัจฉริยะเพื่อความมั่นคงทางอาหารในภาคตะวันออกเฉียงเหนือ","curriculum_highlights":["Crop Breeding & Seed Technology","Precision Agriculture & Smart Farm IoT","Soil-Plant Nutrient Management","Post-Harvest Technology & Value Addition","Sustainable Crop Production Systems"],"career_paths":["Agronomist","Seed Technology Specialist","Smart Farm Consultant","Agricultural Extension Officer","Crop Production Manager"],"tags":["Agronomy","Smart Farm","Plant Breeding","KKU","Agriculture"],"website_url":"https://ag.kku.ac.th"},
  {"id":"kku_agri_anim_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสัตวศาสตร์","title_en":"Bachelor of Science Program in Animal Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (สัตวศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Agriculture","faculty_th":"คณะเกษตรศาสตร์","department":"Department of Animal Science","department_th":"ภาควิชาสัตวศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"134 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"ผลิตนักสัตวศาสตร์ที่มีความเชี่ยวชาญด้านการจัดการฟาร์มโคเนื้อ โคนม สุกรและสัตว์ปีก โภชนศาสตร์สัตว์ การปรับปรุงพันธุ์ และเทคโนโลยีการผลิตปศุสัตว์สมัยใหม่","curriculum_highlights":["Animal Nutrition & Feed Formulation","Livestock Breeding & Genetics","Farm Management & Economics","Animal Health & Biosecurity","Meat & Dairy Product Technology"],"career_paths":["Animal Scientist","Livestock Farm Manager","Feed Formulation Specialist","Livestock Extension Officer","Animal Product Entrepreneur"],"tags":["Animal Science","Livestock","Farm Management","KKU"],"website_url":"https://ag.kku.ac.th"},
  {"id":"kku_agri_fish_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาประมง","title_en":"Bachelor of Science Program in Fisheries","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ประมง)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Agriculture","faculty_th":"คณะเกษตรศาสตร์","department":"Department of Fisheries","department_th":"ภาควิชาประมง","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการเพาะเลี้ยงสัตว์น้ำจืด การจัดการทรัพยากรประมงน้ำจืด เทคโนโลยีชีวภาพสัตว์น้ำ และการแปรรูปผลิตภัณฑ์ประมงเพื่อเศรษฐกิจฐานชีวภาพลุ่มน้ำโขง","curriculum_highlights":["Freshwater Aquaculture Systems","Fisheries Resource Management","Fish Nutrition & Disease Control","Aquatic Biotechnology","Fish Processing & Product Development"],"career_paths":["Fisheries Biologist","Aquaculture Farm Manager","Fisheries Extension Officer","Aquatic Product QA Specialist","Fisheries Entrepreneur"],"tags":["Fisheries","Aquaculture","KKU","Agriculture"],"website_url":"https://ag.kku.ac.th"},
  {"id":"kku_agri_agrieng_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเกษตร","title_en":"Bachelor of Engineering Program in Agricultural Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมเกษตร)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Agriculture","faculty_th":"คณะเกษตรศาสตร์","department":"Department of Agricultural Engineering","department_th":"ภาควิชาวิศวกรรมเกษตร","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"บูรณาการวิศวกรรมเครื่องกล ระบบชลประทาน และเทคโนโลยีเกษตรแม่นยำสูงเพื่อพัฒนาเครื่องจักรกลการเกษตร โรงเรือนอัจฉริยะ และระบบเกษตรอัตโนมัติ","curriculum_highlights":["Farm Machinery Design & Automation","Irrigation & Water Management Engineering","Post-Harvest & Storage Engineering","Precision Agriculture Sensors & Drones","Smart Greenhouse Systems"],"career_paths":["Agricultural Engineer","Irrigation System Designer","Smart Farm System Engineer","Post-Harvest Technology Specialist","Agri-Machinery R&D Engineer"],"tags":["Agricultural Engineering","Smart Farm","KKU","Engineering"],"website_url":"https://ag.kku.ac.th"},
  {"id":"kku_agri_foodtech_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์และเทคโนโลยีการอาหาร","title_en":"Bachelor of Science Program in Food Science and Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาศาสตร์และเทคโนโลยีการอาหาร)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Agriculture","faculty_th":"คณะเกษตรศาสตร์","department":"Department of Food Technology","department_th":"ภาควิชาเทคโนโลยีการอาหาร","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นเคมีอาหาร จุลชีววิทยาอาหาร วิศวกรรมแปรรูปอาหาร และการประกันคุณภาพตามมาตรฐาน GMP/HACCP เพื่อนวัตกรรมอาหารอีสานสู่ตลาดโลก","curriculum_highlights":["Food Chemistry & Analysis","Food Microbiology & Safety (HACCP)","Food Processing & Packaging Engineering","Sensory Evaluation & Product Development","Food Quality Assurance & Standards"],"career_paths":["Food Scientist","Food Technologist","QA/QC Manager","Food Product Developer","Food Safety Auditor"],"tags":["Food Technology","Food Science","HACCP","KKU"],"website_url":"https://ag.kku.ac.th"},
  {"id":"kku_agri_agribus_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาธุรกิจการเกษตร","title_en":"Bachelor of Science Program in Agribusiness","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ธุรกิจการเกษตร)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Agriculture","faculty_th":"คณะเกษตรศาสตร์","department":"Department of Agricultural Economics","department_th":"ภาควิชาเศรษฐศาสตร์การเกษตร","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"ผสานเศรษฐศาสตร์การเกษตร การตลาดสินค้าเกษตร โลจิสติกส์เกษตร และการเป็นผู้ประกอบการเกษตรสมัยใหม่เพื่อยกระดับห่วงโซ่อุปทานเกษตรภาคอีสาน","curriculum_highlights":["Agricultural Marketing & Price Analysis","Agribusiness Startup & Entrepreneurship","Supply Chain & Logistics in Agriculture","Agricultural Finance & Risk Management","Smart Farm Business Models"],"career_paths":["Agribusiness Entrepreneur","Agricultural Marketing Specialist","Supply Chain Coordinator","Agricultural Finance Officer","Cooperative Manager"],"tags":["Agribusiness","Agricultural Economics","KKU"],"website_url":"https://ag.kku.ac.th"},
  {"id":"kku_agri_hort_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาพืชสวน","title_en":"Master of Science Program in Horticulture","degree_level":"ปริญญาโท","degree_name":"วท.ม. (พืชสวน)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Agriculture","faculty_th":"คณะเกษตรศาสตร์","department":"Department of Horticulture","department_th":"ภาควิชาพืชสวน","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"88,000 บาท","description":"วิจัยขั้นสูงด้านไม้ผลเขตร้อน พืชผัก และไม้ดอกไม้ประดับ เทคโนโลยีหลังการเก็บเกี่ยว และสรีรวิทยาพืชสวนเพื่อเพิ่มมูลค่าส่งออก","curriculum_highlights":["Advanced Tropical Fruit Production","Postharvest Physiology & Technology","Plant Tissue Culture & Molecular Breeding","Greenhouse Horticulture Technology","Horticultural Thesis Research"],"career_paths":["Horticulturist","Plant Breeding Researcher","Greenhouse Manager","Postharvest Specialist","Academic Researcher"],"tags":["Horticulture","Master Degree","KKU","Agriculture"],"website_url":"https://ag.kku.ac.th"},
  # === FACULTY OF TECHNOLOGY (8) ===
  {"id":"kku_tech_food_tech_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีการอาหาร","title_en":"Bachelor of Science Program in Food Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคโนโลยีการอาหาร)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Technology","faculty_th":"คณะเทคโนโลยี","department":"Department of Food Technology","department_th":"ภาควิชาเทคโนโลยีการอาหาร","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"134 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นนวัตกรรมอาหารแปรรูป อาหารฟังก์ชัน และเทคโนโลยีชีวภาพอาหารด้วยมาตรฐานระดับสากล ร่วมมือกับอุตสาหกรรมอาหารชั้นนำภาคอีสาน","curriculum_highlights":["Food Innovation & Fermentation Technology","Functional Food & Nutraceuticals","Food Safety & HACCP Systems","Food Packaging & Shelf-life Extension","Industrial Food Plant Design"],"career_paths":["Food Technologist","Food Innovation Specialist","QA/QC Manager","Food Safety Auditor","Food Entrepreneur"],"tags":["Food Technology","KKU","Technology"],"website_url":"https://tech.kku.ac.th"},
  {"id":"kku_tech_biotech_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีชีวภาพ","title_en":"Bachelor of Science Program in Biotechnology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคโนโลยีชีวภาพ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Technology","faculty_th":"คณะเทคโนโลยี","department":"Department of Biotechnology","department_th":"ภาควิชาเทคโนโลยีชีวภาพ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"บูรณาการจุลชีววิทยา ชีวเคมี และวิศวกรรมชีวกระบวนการเพื่อผลิตเอนไซม์ โปรไบโอติก พลังงานชีวภาพ และผลิตภัณฑ์ BCG Economy","curriculum_highlights":["Microbial Biotechnology & Fermentation","Genetic Engineering & Molecular Biology","Enzyme Technology & Biocatalysis","Bioprocess Design & Scale-up","BCG Bioeconomy Innovation"],"career_paths":["Biotechnologist","Fermentation Specialist","Bioprocess Engineer","Biotech R&D Scientist","QC Specialist in Bioindustry"],"tags":["Biotechnology","Bioprocess","KKU"],"website_url":"https://tech.kku.ac.th"},
  {"id":"kku_tech_chem_tech_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาเทคโนโลยีเคมี","title_en":"Bachelor of Engineering Program in Chemical Technology","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (เทคโนโลยีเคมี)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Technology","faculty_th":"คณะเทคโนโลยี","department":"Department of Chemical Technology","department_th":"ภาควิชาเทคโนโลยีเคมี","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"140 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นกระบวนการเคมีอุตสาหกรรม ปิโตรเคมี พอลิเมอร์ และเทคโนโลยีสิ่งแวดล้อมเพื่ออุตสาหกรรมยั่งยืนภาคตะวันออกเฉียงเหนือ","curriculum_highlights":["Chemical Process Design & Simulation","Polymer Science & Engineering","Petrochemical Technology & Catalysis","Environmental Chemical Technology","Plant Safety & Process Control"],"career_paths":["Chemical Process Engineer","Polymer Engineer","Petrochemical Engineer","Environmental Engineer","Plant Safety Engineer"],"tags":["Chemical Technology","KKU","Engineering"],"website_url":"https://tech.kku.ac.th"},
  {"id":"kku_tech_pack_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีการบรรจุ","title_en":"Bachelor of Science Program in Packaging Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคโนโลยีการบรรจุ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Technology","faculty_th":"คณะเทคโนโลยี","department":"Department of Packaging Technology","department_th":"ภาควิชาเทคโนโลยีการบรรจุ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"ศาสตร์เฉพาะทางด้านวัสดุบรรจุภัณฑ์ การออกแบบบรรจุภัณฑ์อัจฉริยะ บรรจุภัณฑ์ยั่งยืน และโลจิสติกส์บรรจุภัณฑ์เพื่ออุตสาหกรรมอาหารและสินค้าอุปโภค","curriculum_highlights":["Packaging Materials Science (Paper/Plastic/Metal)","Smart & Active Packaging Design","Sustainable Packaging & LCA","Packaging Printing & Graphics","Packaging Logistics & Supply Chain"],"career_paths":["Packaging Technologist","Packaging Designer","Sustainable Packaging Consultant","QA Specialist Packaging","Logistics Packaging Engineer"],"tags":["Packaging Technology","Sustainable Packaging","KKU"],"website_url":"https://tech.kku.ac.th"},
  {"id":"kku_tech_geo_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีธรณี","title_en":"Bachelor of Science Program in Geotechnology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคโนโลยีธรณี)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Technology","faculty_th":"คณะเทคโนโลยี","department":"Department of Geotechnology","department_th":"ภาควิชาเทคโนโลยีธรณี","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"134 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นธรณีวิทยา วิศวกรรมปฐพี อุทกธรณีวิทยา และเทคโนโลยีสำรวจทรัพยากรธรณีและน้ำบาดาลภาคอีสาน","curriculum_highlights":["Engineering Geology & Soil Mechanics","Hydrogeology & Groundwater Management","Mineral Resources Exploration","Geotechnical Instrumentation & Monitoring","GIS for Geotechnology"],"career_paths":["Geotechnologist","Geotechnical Engineer","Groundwater Specialist","Mining Geologist","GIS Specialist"],"tags":["Geotechnology","KKU","Hydrogeology"],"website_url":"https://tech.kku.ac.th"},
  {"id":"kku_tech_prod_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเทคโนโลยีการผลิต","title_en":"Master of Science Program in Production Technology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (เทคโนโลยีการผลิต)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Technology","faculty_th":"คณะเทคโนโลยี","department":"Graduate Studies","department_th":"บัณฑิตศึกษา คณะเทคโนโลยี","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"24,000 บาท","tuition_total":"96,000 บาท","description":"วิจัยขั้นสูงด้านระบบการผลิตอัจฉริยะ หุ่นยนต์อุตสาหกรรม การควบคุมคุณภาพ และ Industry 4.0 สำหรับอุตสาหกรรมอาหารและชิ้นส่วนยานยนต์","curriculum_highlights":["Smart Manufacturing & Industry 4.0","Robotics & Automation in Production","Advanced Quality Engineering (Six Sigma)","Production Planning & Optimization","Thesis in Production Technology"],"career_paths":["Production Technology Researcher","Smart Manufacturing Engineer","Quality Engineering Manager","Industrial Consultant","Academic Researcher"],"tags":["Production Technology","Master Degree","KKU","Industry 4.0"],"website_url":"https://tech.kku.ac.th"},
  {"id":"kku_tech_food_inno_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชานวัตกรรมอาหาร","title_en":"Master of Science Program in Food Innovation","degree_level":"ปริญญาโท","degree_name":"วท.ม. (นวัตกรรมอาหาร)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Technology","faculty_th":"คณะเทคโนโลยี","department":"Department of Food Technology","department_th":"ภาควิชาเทคโนโลยีการอาหาร","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"26,000 บาท","tuition_total":"104,000 บาท","description":"เน้นวิจัยอาหารอนาคต โปรตีนทางเลือก อาหารฟังก์ชัน และ Future Food เพื่อยกระดับอุตสาหกรรมอาหารอีสานสู่ตลาดโลก","curriculum_highlights":["Future Food & Alternative Proteins","Food Biotechnology & Fermentation","Functional Food & Health Claims","Food Entrepreneurship & Commercialization","Advanced Food Research Thesis"],"career_paths":["Food Innovation Researcher","Future Food Developer","Food Startup Founder","R&D Manager Food Industry","Food Regulatory Specialist"],"tags":["Food Innovation","Master Degree","KKU"],"website_url":"https://tech.kku.ac.th"},
  {"id":"kku_tech_env_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีสิ่งแวดล้อม","title_en":"Bachelor of Science Program in Environmental Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคโนโลยีสิ่งแวดล้อม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Technology","faculty_th":"คณะเทคโนโลยี","department":"Department of Environmental Technology","department_th":"ภาควิชาเทคโนโลยีสิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการจัดการน้ำเสีย อากาศเสีย ขยะอุตสาหกรรม และเทคโนโลยีพลังงานสะอาดเพื่ออุตสาหกรรมยั่งยืน","curriculum_highlights":["Wastewater & Air Pollution Control","Solid Waste & Hazardous Waste Management","Environmental Impact Assessment (EIA)","Renewable Energy Technology","Cleaner Production & Circular Economy"],"career_paths":["Environmental Technologist","EIA Consultant","Waste Management Specialist","Pollution Control Officer","Sustainability Consultant"],"tags":["Environmental Technology","EIA","KKU"],"website_url":"https://tech.kku.ac.th"},
  # === HUMANITIES AND SOCIAL SCIENCES (15) ===
  {"id":"kku_huso_thai_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาไทย","title_en":"Bachelor of Arts Program in Thai Language","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาไทย)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Thai Language","department_th":"ภาควิชาภาษาไทย","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"13,000 บาท","tuition_total":"104,000 บาท","description":"ศึกษาภาษาไทย วรรณกรรมไทย คติชนวิทยาอีสาน และภาษาศาสตร์เพื่ออนุรักษ์และสร้างสรรค์วัฒนธรรมอีสานและสื่อสารมวลชน","curriculum_highlights":["Thai Linguistics & Philology","Isan Folklore & Literature","Creative Writing & Editing","Thai for Media & Communication","Isan Cultural Heritage Conservation"],"career_paths":["Thai Language Teacher","Content Editor / Writer","Cultural Officer","Media Content Creator","Researcher in Thai Studies"],"tags":["Thai Language","Isan Culture","Humanities","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_eng_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาอังกฤษ","title_en":"Bachelor of Arts Program in English","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาอังกฤษ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of English","department_th":"ภาควิชาภาษาอังกฤษ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"13,000 บาท","tuition_total":"104,000 บาท","description":"เน้นทักษะภาษาอังกฤษเชิงวิชาการ ธุรกิจ วรรณกรรมอังกฤษ และการแปลเพื่อเตรียมบัณฑิตสู่ตลาดแรงงานสากลและการศึกษาต่อ","curriculum_highlights":["Advanced Academic English & Writing","Business English & Presentation","English Literature & Cultural Studies","Translation & Interpretation Techniques","English for Digital Communication"],"career_paths":["English Teacher / Tutor","Translator / Interpreter","Content Writer","International Business Coordinator","Graduate Studies Abroad"],"tags":["English","Translation","Humanities","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_history_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาประวัติศาสตร์","title_en":"Bachelor of Arts Program in History","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ประวัติศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of History","department_th":"ภาควิชาประวัติศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"13,000 บาท","tuition_total":"104,000 บาท","description":"ศึกษาประวัติศาสตร์ไทย อีสาน เอเชียตะวันออกเฉียงใต้ และประวัติศาสตร์โลก พร้อมทักษะวิจัยเชิงประวัติศาสตร์และพิพิธภัณฑ์ศึกษา","curriculum_highlights":["Isan & Thai History","Southeast Asian History","Oral History & Archival Research","Museum Studies & Heritage Management","Digital History & Public History"],"career_paths":["Historian / Researcher","Museum Curator","Archivist","Cultural Heritage Officer","History Teacher"],"tags":["History","Isan History","Museum Studies","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_socio_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาสังคมวิทยาและมานุษยวิทยา","title_en":"Bachelor of Arts Program in Sociology and Anthropology","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (สังคมวิทยาและมานุษยวิทยา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Sociology and Anthropology","department_th":"ภาควิชาสังคมวิทยาและมานุษยวิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"13,000 บาท","tuition_total":"104,000 บาท","description":"ศึกษาสังคมอีสานร่วมสมัย ความเหลื่อมล้ำ เพศสภาพ การย้ายถิ่น และมานุษยวิทยาวัฒนธรรมเพื่อการพัฒนาแบบมีส่วนร่วม","curriculum_highlights":["Isan Contemporary Society & Inequality","Gender & Migration Studies","Qualitative Research & Fieldwork","Anthropology of Development","Community-Based Participatory Research"],"career_paths":["Social Researcher","NGO / Development Worker","Community Development Officer","Social Policy Analyst","Academic Researcher"],"tags":["Sociology","Anthropology","Isan Studies","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_psy_ba","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาจิตวิทยา","title_en":"Bachelor of Science Program in Psychology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (จิตวิทยา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Psychology","department_th":"ภาควิชาจิตวิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นจิตวิทยาทั่วไป จิตวิทยาคลินิกเบื้องต้น จิตวิทยาองค์การ และจิตวิทยาชุมชนอีสานเพื่อสุขภาพจิตที่เข้าถึงได้","curriculum_highlights":["General & Developmental Psychology","Psychological Testing & Assessment","Organizational Psychology & HR","Community Mental Health in Isan","Research Methods in Psychology"],"career_paths":["Psychologist Assistant","HR / People Officer","Mental Health Support Worker","Research Assistant Psychology","Counseling Support Staff"],"tags":["Psychology","Mental Health","HR","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_info_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาสารสนเทศศาสตร์","title_en":"Bachelor of Arts Program in Information Science","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (สารสนเทศศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Information Science","department_th":"ภาควิชาสารสนเทศศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"13,000 บาท","tuition_total":"104,000 บาท","description":"เน้นการจัดการห้องสมุดดิจิทัล สารสนเทศอิเล็กทรอนิกส์ การวิเคราะห์ข้อมูลสารสนเทศ และนวัตกรรมห้องสมุดเพื่อการเรียนรู้ตลอดชีวิต","curriculum_highlights":["Digital Library & Archive Management","Information Retrieval & Knowledge Organization","Data Analytics for Information Professionals","UX for Library Services","Information Literacy & Community Outreach"],"career_paths":["Librarian / Archivist","Information Specialist","Knowledge Manager","UX Librarian","Digital Content Curator"],"tags":["Information Science","Library Science","Digital Archive","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_pa_ba","title_th":"หลักสูตรรัฐประศาสนศาสตรบัณฑิต สาขาวิชารัฐประศาสนศาสตร์","title_en":"Bachelor of Public Administration Program","degree_level":"ปริญญาตรี","degree_name":"รป.บ. (รัฐประศาสนศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Public Administration","department_th":"ภาควิชารัฐประศาสนศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"13,000 บาท","tuition_total":"104,000 บาท","description":"ผลิตนักบริหารรัฐกิจที่เข้าใจการกระจายอำนาจ การปกครองท้องถิ่นอีสาน นโยบายสาธารณะ และการบริหารภาครัฐดิจิทัล","curriculum_highlights":["Decentralization & Local Government in Isan","Public Policy Analysis & Evaluation","Digital Government & E-Services","Public Budgeting & Local Finance","Community Participation & Good Governance"],"career_paths":["Public Administrator / Palad","Local Government Officer","Policy Analyst","Community Development Officer","Government Digital Officer"],"tags":["Public Administration","Local Government","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_dev_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาการพัฒนาสังคม","title_en":"Bachelor of Arts Program in Social Development","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (การพัฒนาสังคม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Social Development","department_th":"ภาควิชาการพัฒนาสังคม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"13,000 บาท","tuition_total":"104,000 บาท","description":"เน้นการพัฒนาชุมชนอีสานแบบมีส่วนร่วม เศรษฐกิจชุมชน การจัดการความขัดแย้ง และนวัตกรรมสังคมเพื่อลดความเหลื่อมล้ำ","curriculum_highlights":["Participatory Community Development","Community Economy & Social Enterprise","Conflict Management & Peace Building","Social Innovation Lab","Project Evaluation & Impact Assessment"],"career_paths":["Community Developer","Social Enterprise Founder","NGO Project Officer","CSR Officer","Local Development Planner"],"tags":["Social Development","Community Development","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_japanese_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาญี่ปุ่น","title_en":"Bachelor of Arts Program in Japanese","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาญี่ปุ่น)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Eastern Languages","department_th":"ภาควิชาภาษาตะวันออก","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"13,500 บาท","tuition_total":"108,000 บาท","description":"เน้นทักษะภาษาญี่ปุ่นธุรกิจ วัฒนธรรมญี่ปุ่น การแปล และโอกาสฝึกงานกับบริษัทญี่ปุ่นในนิคมอุตสาหกรรมภาคอีสานและ EEC","curriculum_highlights":["Business Japanese & Keigo","Japanese Culture & Society","Translation Japanese-Thai","JLPT Preparation & Internship","Japanese for Tourism & Hospitality"],"career_paths":["Japanese Interpreter / Translator","Japanese Business Coordinator","Tour Guide Japanese","Japanese Teacher","Company Liaison in Japanese Firm"],"tags":["Japanese","Eastern Languages","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_chinese_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาจีน","title_en":"Bachelor of Arts Program in Chinese","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาจีน)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Eastern Languages","department_th":"ภาควิชาภาษาตะวันออก","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"13,500 บาท","tuition_total":"108,000 บาท","description":"เน้นภาษาจีนธุรกิจ HSK 5-6 วัฒนธรรมจีน การค้าระหว่างประเทศ ไทย-จีน และการเป็นล่ามในเขตเศรษฐกิจอนุภูมิภาคลุ่มน้ำโขง","curriculum_highlights":["Business Chinese & HSK Advanced","Chinese-Thai Translation","China-ASEAN Trade & Logistics","Chinese Culture & Contemporary Society","Internship in Chinese Enterprises"],"career_paths":["Chinese Interpreter","China Trade Coordinator","Chinese Teacher","Tour Business Chinese","Cross-border Logistics Officer"],"tags":["Chinese","HSK","KKU","GMS"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_korean_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาเกาหลี","title_en":"Bachelor of Arts Program in Korean","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาเกาหลี)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Eastern Languages","department_th":"ภาควิชาภาษาตะวันออก","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"13,500 บาท","tuition_total":"108,000 บาท","description":"เน้นภาษาเกาหลีระดับ TOPIK ธุรกิจเกาหลี วัฒนธรรม K-Culture และการทำงานในอุตสาหกรรมบันเทิงและบริษัทเกาหลีในไทย","curriculum_highlights":["Korean Language & TOPIK Preparation","Korean Business Communication","K-Culture & Media Studies","Korean-Thai Translation","Internship in Korean Companies/Hallyu Industry"],"career_paths":["Korean Interpreter","K-Culture Content Creator","Korean Business Liaison","Korean Teacher","Tourism Korean Specialist"],"tags":["Korean","TOPIK","K-Culture","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_huso_ma","title_th":"หลักสูตรศิลปศาสตรมหาบัณฑิต สาขาวิชาสังคมศาสตร์และการพัฒนา","title_en":"Master of Arts Program in Social Sciences and Development","degree_level":"ปริญญาโท","degree_name":"ศศ.ม. (สังคมศาสตร์และการพัฒนา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Graduate Studies","department_th":"บัณฑิตศึกษา คณะมนุษยศาสตร์และสังคมศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"72,000 บาท","description":"วิจัยขั้นสูงด้านการพัฒนาอีสาน ความเหลื่อมล้ำ การย้ายถิ่น และนวัตกรรมสังคมด้วยระเบียบวิธีวิจัยเชิงคุณภาพและมีส่วนร่วม","curriculum_highlights":["Advanced Isan Development Studies","Qualitative & Participatory Action Research","Inequality, Migration & Social Justice","Social Innovation & Policy Lab","Master Thesis in Social Development"],"career_paths":["Social Development Researcher","Policy Analyst","NGO Program Manager","Academic Researcher","Community Development Consultant"],"tags":["Master Degree","Social Development","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_psy_ma","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาจิตวิทยา","title_en":"Master of Science Program in Psychology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (จิตวิทยา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Psychology","department_th":"ภาควิชาจิตวิทยา","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"80,000 บาท","description":"เน้นจิตวิทยาคลินิกและการปรึกษา การประเมินทางจิตวิทยา และการวิจัยสุขภาพจิตชุมชนภาคตะวันออกเฉียงเหนือ","curriculum_highlights":["Clinical Psychology & Counseling Theories","Psychometrics & Advanced Assessment","Community Mental Health Research","Cognitive Behavioral Therapy Basics","Master Thesis in Psychology"],"career_paths":["Clinical Psychology Researcher","Counselor","HR Analytics Specialist","Mental Health Project Officer","Academic Psychologist"],"tags":["Psychology","Master Degree","KKU"],"website_url":"https://hs.kku.ac.th"},
  {"id":"kku_huso_info_ma","title_th":"หลักสูตรศิลปศาสตรมหาบัณฑิต สาขาวิชาสารสนเทศศึกษา","title_en":"Master of Arts Program in Information Studies","degree_level":"ปริญญาโท","degree_name":"ศศ.ม. (สารสนเทศศึกษา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Humanities and Social Sciences","faculty_th":"คณะมนุษยศาสตร์และสังคมศาสตร์","department":"Department of Information Science","department_th":"ภาควิชาสารสนเทศศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"72,000 บาท","description":"วิจัยด้านห้องสมุดดิจิทัล การจัดการความรู้ ฐานข้อมูลวัฒนธรรมอีสาน และ AI สำหรับสารสนเทศ","curriculum_highlights":["Digital Libraries & Cultural Archives","Knowledge Management & Organization","AI for Information Retrieval","Data Curation & Digital Preservation","Research Thesis in Information Studies"],"career_paths":["Information Systems Researcher","Digital Archivist","Knowledge Manager","Library Data Specialist","Academic Librarian"],"tags":["Information Studies","Master Degree","KKU"],"website_url":"https://hs.kku.ac.th"},

  # === FACULTY OF EDUCATION (เพิ่ม 7) ===
  {"id":"kku_edu_primary_bed","title_th":"หลักสูตรครุศาสตรบัณฑิต สาขาวิชาการประถมศึกษา","title_en":"Bachelor of Education Program in Elementary Education","degree_level":"ปริญญาตรี","degree_name":"ค.บ. (การประถมศึกษา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of Curriculum and Instruction","department_th":"ภาควิชาหลักสูตรและการสอน","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"ผลิตครูประถมศึกษาที่เชี่ยวชาญการจัดการเรียนรู้บูรณาการ สะเต็มศึกษา และนวัตกรรมการสอนสำหรับโรงเรียนขนาดเล็กภาคอีสาน","curriculum_highlights":["Integrated Learning Design for Primary","STEM Education for Young Learners","Classroom Action Research","Isan Local Curriculum Development","Teaching Practicum in Small Schools"],"career_paths":["Primary School Teacher","Curriculum Developer","Educational Content Creator","Education Officer","Private Tutoring Entrepreneur"],"tags":["Elementary Education","Teacher","KKU","Education"],"website_url":"https://ed.kku.ac.th"},
  {"id":"kku_edu_early_bed","title_th":"หลักสูตรครุศาสตรบัณฑิต สาขาวิชาการศึกษาปฐมวัย","title_en":"Bachelor of Education Program in Early Childhood Education","degree_level":"ปริญญาตรี","degree_name":"ค.บ. (การศึกษาปฐมวัย)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of Early Childhood Education","department_th":"ภาควิชาการศึกษาปฐมวัย","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นจิตวิทยาพัฒนาการเด็กปฐมวัย การจัดประสบการณ์เรียนรู้ผ่านการเล่น ภาษาแม่ และการเตรียมความพร้อมเด็กอีสานสู่การเรียนรู้ตลอดชีวิต","curriculum_highlights":["Early Childhood Developmental Psychology","Play-Based Learning & Creativity","Early Literacy & Numeracy","Inclusive Early Childhood Education","Practicum in Child Development Centers"],"career_paths":["Early Childhood Teacher","Child Development Specialist","Kindergarten Manager","Child Media Developer","Early Childhood Researcher"],"tags":["Early Childhood","KKU","Education"],"website_url":"https://ed.kku.ac.th"},
  {"id":"kku_edu_math_bed","title_th":"หลักสูตรครุศาสตรบัณฑิต สาขาวิชาคณิตศาสตรศึกษา","title_en":"Bachelor of Education Program in Mathematics Education","degree_level":"ปริญญาตรี","degree_name":"ค.บ. (คณิตศาสตรศึกษา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of Mathematics Education","department_th":"ภาควิชาคณิตศาสตรศึกษา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"ผลิตครูคณิตศาสตร์ที่เชี่ยวชาญคณิตคิดวิเคราะห์ การแก้ปัญหาเชิงคณิตศาสตร์ และการใช้เทคโนโลยีดิจิทัลในการสอนคณิตศาสตร์","curriculum_highlights":["Mathematical Thinking & Problem Solving","Digital Tools for Mathematics Teaching (GeoGebra)","Assessment in Mathematics Education","Lesson Study & Open Approach","Mathematics Teaching Practicum"],"career_paths":["Mathematics Teacher","Math Tutoring Entrepreneur","Educational Technology Developer","Curriculum Specialist Math","Academic Coach"],"tags":["Mathematics Education","KKU","Teacher"],"website_url":"https://ed.kku.ac.th"},
  {"id":"kku_edu_sci_bed","title_th":"หลักสูตรครุศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์ทั่วไป","title_en":"Bachelor of Education Program in General Science","degree_level":"ปริญญาตรี","degree_name":"ค.บ. (วิทยาศาสตร์ทั่วไป)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of Science Education","department_th":"ภาควิชาวิทยาศาสตรศึกษา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการสอนวิทยาศาสตร์แบบสืบเสาะ การทดลองวิทยาศาสตร์ชุมชนอีสาน และสะเต็มศึกษาบูรณาการ","curriculum_highlights":["Inquiry-Based Science Teaching","Community Science Lab","STEM Integrated Curriculum","Science Assessment & Evaluation","Science Teaching Practicum"],"career_paths":["Science Teacher","STEM Education Specialist","Science Museum Educator","Science Content Creator","Education Officer"],"tags":["Science Education","STEM","KKU"],"website_url":"https://ed.kku.ac.th"},
  {"id":"kku_edu_eng_bed","title_th":"หลักสูตรครุศาสตรบัณฑิต สาขาวิชาภาษาอังกฤษศึกษา","title_en":"Bachelor of Education Program in English Education","degree_level":"ปริญญาตรี","degree_name":"ค.บ. (ภาษาอังกฤษศึกษา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of English Education","department_th":"ภาควิชาภาษาอังกฤษศึกษา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"ผลิตครูภาษาอังกฤษที่เชี่ยวชาญการสอนภาษาเพื่อการสื่อสาร CEFR และการใช้เทคโนโลยี AI ในการสอนภาษา","curriculum_highlights":["Communicative Language Teaching (CLT)","CEFR Assessment & Testing","AI Tools for English Teaching","Intercultural Communication in Classroom","English Teaching Practicum"],"career_paths":["English Teacher","Language School Owner","Curriculum Designer English","Educational Influencer","Translator Teacher"],"tags":["English Education","KKU","Teacher"],"website_url":"https://ed.kku.ac.th"},
  {"id":"kku_edu_physed_bed","title_th":"หลักสูตรครุศาสตรบัณฑิต สาขาวิชาพลศึกษา","title_en":"Bachelor of Education Program in Physical Education","degree_level":"ปริญญาตรี","degree_name":"ค.บ. (พลศึกษา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of Physical Education","department_th":"ภาควิชาพลศึกษา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"134 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นวิทยาศาสตร์การกีฬา การจัดการกีฬาและนันทนาการ และพลศึกษาสำหรับสุขภาพชุมชนอีสาน","curriculum_highlights":["Sports Science & Exercise Physiology","Physical Education Pedagogy","Sports Management & Recreation","Health Promotion in Schools","Coaching Practicum"],"career_paths":["Physical Education Teacher","Sports Coach","Sports Event Organizer","Fitness Trainer","Recreation Officer"],"tags":["Physical Education","Sports Science","KKU"],"website_url":"https://ed.kku.ac.th"},
  {"id":"kku_edu_edtech_med","title_th":"หลักสูตรศึกษาศาสตรมหาบัณฑิต สาขาวิชาเทคโนโลยีการศึกษา","title_en":"Master of Education Program in Educational Technology","degree_level":"ปริญญาโท","degree_name":"ศษ.ม. (เทคโนโลยีการศึกษา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Education","faculty_th":"คณะศึกษาศาสตร์","department":"Department of Educational Technology","department_th":"ภาควิชาเทคโนโลยีการศึกษา","program_type":"ภาคปกติ / ภาคพิเศษ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"72,000 บาท","description":"วิจัยเทคโนโลยีการศึกษา สื่อดิจิทัล AI เพื่อการศึกษา และการออกแบบการเรียนรู้ออนไลน์สำหรับโรงเรียนภาคอีสาน","curriculum_highlights":["AI in Education & Learning Analytics","Digital Media Production for Learning","Online Learning Design (MOOC)","Educational Innovation Research","Thesis in EdTech"],"career_paths":["Educational Technologist","Instructional Designer","E-Learning Developer","Education Researcher","EdTech Entrepreneur"],"tags":["Educational Technology","Master Degree","KKU"],"website_url":"https://ed.kku.ac.th"},

  # === FACULTY OF NURSING (4) ===
  {"id":"kku_nur_bns","title_th":"หลักสูตรพยาบาลศาสตรบัณฑิต","title_en":"Bachelor of Nursing Science Program","degree_level":"ปริญญาตรี","degree_name":"พย.บ. (พยาบาลศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Faculty of Nursing","department_th":"คณะพยาบาลศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"142 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"280,000 บาท","description":"ผลิตพยาบาลวิชาชีพที่มีความเชี่ยวชาญการพยาบาลผู้ใหญ่ ผู้สูงอายุ เด็ก และชุมชนอีสานตามมาตรฐานสภาการพยาบาล","curriculum_highlights":["Adult & Elderly Nursing","Maternal & Child Nursing","Community Health Nursing in Isan","Nursing Ethics & Law","Clinical Practicum at Srinagarind Hospital"],"career_paths":["Registered Nurse (RN)","Community Health Nurse","Nurse Practitioner Trainee","Hospital Nurse Specialist","Health Educator"],"tags":["Nursing","Srinagarind Hospital","KKU","Healthcare"],"website_url":"https://www.nurse.kku.ac.th"},
  {"id":"kku_nur_gero_mns","title_th":"หลักสูตรพยาบาลศาสตรมหาบัณฑิต สาขาวิชาการพยาบาลผู้สูงอายุ","title_en":"Master of Nursing Science Program in Gerontological Nursing","degree_level":"ปริญญาโท","degree_name":"พย.ม. (การพยาบาลผู้สูงอายุ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Gerontological Nursing","department_th":"สาขาวิชาการพยาบาลผู้สูงอายุ","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"28,000 บาท","tuition_total":"112,000 บาท","description":"เน้นการพยาบาลผู้สูงอายุแบบองค์รวม การจัดการโรคเรื้อรัง และการดูแลระยะยาวในชุมชนอีสานที่เข้าสู่สังคมสูงวัย","curriculum_highlights":["Gerontological Nursing Theories","Chronic Disease & Palliative Care","Long-Term Care Management","Community Gerontology Research","Thesis in Gerontological Nursing"],"career_paths":["Gerontological Nurse Specialist","Long-Term Care Manager","Community Health Nurse Leader","Nursing Educator","Researcher in Aging"],"tags":["Gerontological Nursing","Master Degree","KKU"],"website_url":"https://www.nurse.kku.ac.th"},
  {"id":"kku_nur_community_mns","title_th":"หลักสูตรพยาบาลศาสตรมหาบัณฑิต สาขาวิชาการพยาบาลชุมชน","title_en":"Master of Nursing Science Program in Community Health Nursing","degree_level":"ปริญญาโท","degree_name":"พย.ม. (การพยาบาลเวชปฏิบัติชุมชน)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Community Health Nursing","department_th":"สาขาวิชาการพยาบาลชุมชน","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"26,000 บาท","tuition_total":"104,000 บาท","description":"เน้นการสร้างเสริมสุขภาพชุมชน อสม. และระบบสุขภาพปฐมภูมิอีสาน","curriculum_highlights":["Community Health Assessment & Diagnosis","Primary Care & Village Health Volunteers (อสม.)","Health Promotion in Rural Isan","Epidemiology for Community Nurses","Community Thesis Research"],"career_paths":["Community Health Nurse Practitioner","Primary Care Unit Manager","Public Health Nurse","NGO Health Officer","Nursing Instructor"],"tags":["Community Nursing","KKU","Public Health"],"website_url":"https://www.nurse.kku.ac.th"},
  {"id":"kku_nur_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาพยาบาลศาสตร์","title_en":"Doctor of Philosophy Program in Nursing Science","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (พยาบาลศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Doctoral Program in Nursing","department_th":"สาขาวิชาพยาบาลศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"240,000 บาท","description":"ผลิตนักวิจัยพยาบาลระดับแนวหน้า เน้นวิจัยระบบสุขภาพอีสาน นวัตกรรมการพยาบาล และภาวะผู้นำทางการพยาบาล","curriculum_highlights":["Advanced Nursing Theory & Knowledge Development","Health Systems Research in Isan","Leadership & Health Policy in Nursing","Mixed-Methods Nursing Research","Dissertation in Nursing Science"],"career_paths":["Nursing Professor","Nurse Researcher","Hospital Nursing Director","Health Policy Analyst","Nursing Leader"],"tags":["Ph.D. Nursing","KKU","Nursing Science"],"website_url":"https://www.nurse.kku.ac.th"},

  # === FACULTY OF ASSOCIATED MEDICAL SCIENCES (6) ===
  {"id":"kku_ams_pt_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชากายภาพบำบัด","title_en":"Bachelor of Science Program in Physical Therapy","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (กายภาพบำบัด)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Associated Medical Sciences","faculty_th":"คณะเทคนิคการแพทย์","department":"Department of Physical Therapy","department_th":"ภาควิชากายภาพบำบัด","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"140 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"176,000 บาท","description":"ผลิตนักกายภาพบำบัดที่เชี่ยวชาญระบบกระดูกกล้ามเนื้อ ประสาท และการฟื้นฟูผู้ป่วยโรคหลอดเลือดสมองด้วยเทคโนโลยีทันสมัย","curriculum_highlights":["Musculoskeletal & Neurological PT","Cardiopulmonary Physical Therapy","Rehabilitation Technology & Robotics","Community PT in Isan","Clinical Clerkship at Srinagarind"],"career_paths":["Physical Therapist","Rehabilitation Specialist","Sports Physio","Community PT","Private Clinic Owner"],"tags":["Physical Therapy","KKU","AMS"],"website_url":"https://ams.kku.ac.th"},
  {"id":"kku_ams_mt_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคนิคการแพทย์","title_en":"Bachelor of Science Program in Medical Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคนิคการแพทย์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Associated Medical Sciences","faculty_th":"คณะเทคนิคการแพทย์","department":"Department of Medical Technology","department_th":"ภาควิชาเทคนิคการแพทย์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"176,000 บาท","description":"เน้นการตรวจวิเคราะห์ทางห้องปฏิบัติการ โลหิตวิทยา จุลชีววิทยาคลินิก และการตรวจวินิจฉัยระดับโมเลกุล","curriculum_highlights":["Clinical Hematology & Blood Banking","Clinical Microbiology & Immunology","Molecular Diagnostics & PCR","Lab Quality Assurance & Automation","Clinical Lab Practicum"],"career_paths":["Medical Technologist (MT)","Clinical Lab Scientist","Blood Bank Specialist","Molecular Lab Analyst","Lab QA Manager"],"tags":["Medical Technology","KKU","Laboratory"],"website_url":"https://ams.kku.ac.th"},
  {"id":"kku_ams_radtech_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชารังสีเทคนิค","title_en":"Bachelor of Science Program in Radiological Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (รังสีเทคนิค)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Associated Medical Sciences","faculty_th":"คณะเทคนิคการแพทย์","department":"Department of Radiological Technology","department_th":"ภาควิชารังสีเทคนิค","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"24,000 บาท","tuition_total":"192,000 บาท","description":"ผลิตนักรังสีเทคนิคเชี่ยวชาญ CT MRI Ultrasound และรังสีรักษา พร้อมความปลอดภัยทางรังสี","curriculum_highlights":["Diagnostic Radiography (CT/MRI)","Ultrasound & Nuclear Medicine","Radiation Therapy Planning","Radiation Safety & Dosimetry","Clinical Radiology Practicum"],"career_paths":["Radiological Technologist","CT/MRI Specialist","Radiation Therapist","RPT Application Specialist","Hospital Imaging Manager"],"tags":["Radiological Technology","KKU","AMS"],"website_url":"https://ams.kku.ac.th"},
  {"id":"kku_ams_ot_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชากิจกรรมบำบัด","title_en":"Bachelor of Science Program in Occupational Therapy","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (กิจกรรมบำบัด)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Associated Medical Sciences","faculty_th":"คณะเทคนิคการแพทย์","department":"Department of Occupational Therapy","department_th":"ภาควิชากิจกรรมบำบัด","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"160,000 บาท","description":"เน้นการฟื้นฟูผู้ป่วยให้กลับมาใช้ชีวิตประจำวันได้ด้วยการทำกิจกรรมบำบัดทั้งเด็ก ผู้สูงอายุ และผู้พิการในชุมชนอีสาน","curriculum_highlights":["Pediatric & Geriatric OT","Neurorehabilitation OT","Community-Based OT in Isan","Assistive Technology & Ergonomics","OT Clinical Fieldwork"],"career_paths":["Occupational Therapist","Pediatric OT Specialist","Rehabilitation Coordinator","Assistive Tech Specialist","Community OT"],"tags":["Occupational Therapy","KKU","Rehabilitation"],"website_url":"https://ams.kku.ac.th"},
  {"id":"kku_ams_nutrition_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาโภชนาการและการกำหนดอาหาร","title_en":"Bachelor of Science Program in Nutrition and Dietetics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (โภชนาการและการกำหนดอาหาร)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Associated Medical Sciences","faculty_th":"คณะเทคนิคการแพทย์","department":"Department of Nutrition","department_th":"ภาควิชาโภชนาการ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"134 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"160,000 บาท","description":"ผลิตนักโภชนาการวิชาชีพ นักกำหนดอาหารที่เชี่ยวชาญโภชนาการคลินิก ชุมชน และการจัดการอาหารปลอดภัย","curriculum_highlights":["Clinical Nutrition & Diet Therapy","Community Nutrition in Isan","Food Safety & Diet Planning","Nutrigenomics & Functional Foods","Dietetic Internship at Srinagarind"],"career_paths":["Dietitian","Clinical Nutritionist","Community Nutritionist","Food Safety Specialist","Wellness Consultant"],"tags":["Nutrition","Dietetics","KKU","AMS"],"website_url":"https://ams.kku.ac.th"},
  {"id":"kku_ams_mt_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเทคนิคการแพทย์","title_en":"Master of Science Program in Medical Technology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (เทคนิคการแพทย์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Associated Medical Sciences","faculty_th":"คณะเทคนิคการแพทย์","department":"Graduate Studies AMS","department_th":"บัณฑิตศึกษา คณะเทคนิคการแพทย์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"24,000 บาท","tuition_total":"96,000 บาท","description":"วิจัยขั้นสูงด้านการตรวจวินิจฉัยโมเลกุล ภูมิคุ้มกันคลินิก และนวัตกรรมห้องปฏิบัติการแม่นยำ","curriculum_highlights":["Molecular Diagnostics Innovation","Clinical Immunology Research","Lab Automation & AI","Thesis in Medical Technology","Quality Management in Clinical Lab"],"career_paths":["Medical Technology Researcher","Lab Manager","Molecular Diagnostics Specialist","Academic Instructor","Biotech Consultant"],"tags":["Medical Technology","Master Degree","KKU"],"website_url":"https://ams.kku.ac.th"},

  # === FACULTY OF VETERINARY MEDICINE (5) ===
  {"id":"kku_vet_dvm","title_th":"หลักสูตรสัตวแพทยศาสตรบัณฑิต","title_en":"Doctor of Veterinary Medicine Program","degree_level":"ปริญญาตรี","degree_name":"สพ.บ. (สัตวแพทยศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Veterinary Medicine","faculty_th":"คณะสัตวแพทยศาสตร์","department":"Faculty of Veterinary Medicine","department_th":"คณะสัตวแพทยศาสตร์","program_type":"ภาคปกติ","duration_years":"6 ปี","total_credits":"220 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"420,000 บาท","description":"ผลิตสัตวแพทย์ที่เชี่ยวชาญสัตว์เศรษฐกิจภาคอีสาน (โค กระบือ สุกร สัตว์ปีก) สัตว์เลี้ยง และสัตว์ป่า พร้อมโรงพยาบาลสัตว์ มข.","curriculum_highlights":["Large Animal Medicine (Cattle/Buffalo)","Small Animal Surgery & Medicine","Veterinary Pathology & Diagnostics","Vet Public Health & Zoonoses","Clinical Rotation at KKU Vet Hospital"],"career_paths":["Veterinarian","Livestock Veterinarian","Small Animal Clinician","Vet Public Health Officer","Vet Entrepreneur"],"tags":["Veterinary Medicine","KKU","Livestock","DVM"],"website_url":"https://vet.kku.ac.th"},
  {"id":"kku_vet_vetpub_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์สุขภาพสัตว์","title_en":"Master of Science Program in Veterinary Public Health","degree_level":"ปริญญาโท","degree_name":"วท.ม. (วิทยาศาสตร์สุขภาพสัตว์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Veterinary Medicine","faculty_th":"คณะสัตวแพทยศาสตร์","department":"Department of Veterinary Public Health","department_th":"ภาควิชาสัตวแพทยสาธารณสุข","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"24,000 บาท","tuition_total":"96,000 บาท","description":"เน้นโรคติดต่อระหว่างสัตว์และคน ความปลอดภัยอาหารจากสัตว์ และระบาดวิทยาสัตวแพทย์ภาคอีสาน","curriculum_highlights":["Zoonoses & One Health","Food Safety from Animal Origin","Veterinary Epidemiology","Animal Welfare & Ethics","Thesis in Vet Public Health"],"career_paths":["Vet Public Health Specialist","Food Safety Officer","Epidemiologist","Academic Researcher","Livestock Policy Analyst"],"tags":["Veterinary Public Health","One Health","KKU","Master Degree"],"website_url":"https://vet.kku.ac.th"},
  {"id":"kku_vet_animrep_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาการสืบพันธุ์สัตว์","title_en":"Master of Science Program in Theriogenology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (การสืบพันธุ์สัตว์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Veterinary Medicine","faculty_th":"คณะสัตวแพทยศาสตร์","department":"Department of Theriogenology","department_th":"ภาควิชาสูติศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"24,000 บาท","tuition_total":"96,000 บาท","description":"วิจัยเทคโนโลยีการสืบพันธุ์สัตว์ ผสมเทียม และการย้ายฝากตัวอ่อนโคเนื้อคุณภาพสูง","curriculum_highlights":["Bovine Reproductive Biotechnology","Artificial Insemination & Embryo Transfer","Reproductive Endocrinology","Livestock Breeding Research","Thesis in Theriogenology"],"career_paths":["Theriogenology Specialist","Livestock Breeding Consultant","AI Technician Manager","Researcher Reproduction","Vet Lecturer"],"tags":["Theriogenology","KKU","Livestock"],"website_url":"https://vet.kku.ac.th"},
  {"id":"kku_vet_patho_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาพยาธิชีววิทยาทางสัตวแพทย์","title_en":"Master of Science Program in Veterinary Pathobiology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (พยาธิชีววิทยาทางสัตวแพทย์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Veterinary Medicine","faculty_th":"คณะสัตวแพทยศาสตร์","department":"Department of Pathobiology","department_th":"ภาควิชาพยาธิชีววิทยา","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"24,000 บาท","tuition_total":"96,000 บาท","description":"เน้นพยาธิวิทยาสัตว์ จุลชีววิทยาสัตว์ และภูมิคุ้มกันสัตว์เพื่อวินิจฉัยโรคสัตว์เศรษฐกิจ","curriculum_highlights":["Veterinary Pathology & Histopathology","Veterinary Microbiology & Virology","Veterinary Immunology","Molecular Diagnostics in Animals","Thesis in Pathobiology"],"career_paths":["Veterinary Pathologist","Lab Diagnostic Specialist","Research Scientist","Academic Pathologist","Animal Disease Investigator"],"tags":["Veterinary Pathobiology","KKU"],"website_url":"https://vet.kku.ac.th"},
  {"id":"kku_vet_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาวิทยาศาสตร์สุขภาพสัตว์","title_en":"Doctor of Philosophy Program in Animal Health Science","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (วิทยาศาสตร์สุขภาพสัตว์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Veterinary Medicine","faculty_th":"คณะสัตวแพทยศาสตร์","department":"Doctoral Program","department_th":"สาขาวิชาวิทยาศาสตร์สุขภาพสัตว์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"210,000 บาท","description":"ผลิตนักวิจัยสัตวแพทย์ระดับแนวหน้า เน้น One Health และสุขภาพโคเนื้อ-กระบืออีสาน","curriculum_highlights":["Advanced One Health Research","Animal Health Systems in Isan","Molecular Pathogenesis","Dissertation in Animal Health","International Publication"],"career_paths":["Vet Professor","Vet Research Leader","One Health Policy Maker","International Vet Consultant","Lab Director"],"tags":["Ph.D. Veterinary","KKU","One Health"],"website_url":"https://vet.kku.ac.th"},

  # === FACULTY OF PUBLIC HEALTH (เพิ่ม 6) ===
  {"id":"kku_ph_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสาธารณสุขศาสตร์","title_en":"Bachelor of Science Program in Public Health","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (สาธารณสุขศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Public Health","faculty_th":"คณะสาธารณสุขศาสตร์","department":"Department of Public Health","department_th":"ภาควิชาสาธารณสุขศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"ผลิตนักสาธารณสุขที่เชี่ยวชาญการส่งเสริมสุขภาพ ป้องกันโรค อนามัยสิ่งแวดล้อม และบริหารระบบสุขภาพปฐมภูมิอีสาน","curriculum_highlights":["Epidemiology & Biostatistics","Environmental Health & Sanitation","Health Promotion & Health Education","Primary Health Care Management","Field Practicum in Isan Communities"],"career_paths":["Public Health Officer","Health Promotion Specialist","Environmental Health Officer","Community Health Manager","Health Educator"],"tags":["Public Health","KKU","PH"],"website_url":"https://ph.kku.ac.th"},
  {"id":"kku_ph_eh_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาอนามัยสิ่งแวดล้อม","title_en":"Bachelor of Science Program in Environmental Health","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (อนามัยสิ่งแวดล้อม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Public Health","faculty_th":"คณะสาธารณสุขศาสตร์","department":"Department of Environmental Health","department_th":"ภาควิชาอนามัยสิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการประเมินผลกระทบสุขภาพ (HIA) มลพิษอากาศ PM2.5 น้ำเสีย และอาชีวอนามัยโรงงานภาคอีสาน","curriculum_highlights":["Environmental Health Risk Assessment","PM2.5 & Air Quality Management","Water & Wastewater Management","Occupational Health & Safety","HIA & EIA for Public Health"],"career_paths":["Environmental Health Scientist","EIA/HIA Officer","Occupational Health Officer","Pollution Control Specialist","Environmental Consultant"],"tags":["Environmental Health","HIA","KKU"],"website_url":"https://ph.kku.ac.th"},
  {"id":"kku_ph_health_admin_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาการบริหารงานสาธารณสุข","title_en":"Bachelor of Science Program in Health Administration","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (การบริหารงานสาธารณสุข)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Public Health","faculty_th":"คณะสาธารณสุขศาสตร์","department":"Department of Health Administration","department_th":"ภาควิชาบริหารงานสาธารณสุข","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการบริหารโรงพยาบาลชุมชน ระบบหลักประกันสุขภาพ และนวัตกรรมบริหารสุขภาพดิจิทัลอีสาน","curriculum_highlights":["Hospital & Health Systems Management","Universal Health Coverage & Health Economics","Digital Health Administration","Health Policy & Strategic Planning","Health Administration Practicum"],"career_paths":["Hospital Administrator","Health System Manager","Health Policy Analyst","NHSO Officer","Digital Health Manager"],"tags":["Health Administration","KKU","Management"],"website_url":"https://ph.kku.ac.th"},
  {"id":"kku_ph_nutrition_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาโภชนวิทยา","title_en":"Bachelor of Science Program in Nutrition","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (โภชนวิทยา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Public Health","faculty_th":"คณะสาธารณสุขศาสตร์","department":"Department of Nutrition","department_th":"ภาควิชาโภชนวิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นภาวะโภชนาการชุมชนอีสาน โภชนาการแม่และเด็ก และการจัดการอาหารปลอดภัย","curriculum_highlights":["Community Nutrition & Isan Food Culture","Maternal & Child Nutrition","Food Safety & Nutrition Surveillance","Nutrition Education & Counseling","Community Nutrition Practicum"],"career_paths":["Nutritionist","Community Nutrition Specialist","Maternal Health Nutritionist","Food Safety Officer","Health Coach"],"tags":["Nutrition","KKU","Public Health"],"website_url":"https://ph.kku.ac.th"},
  {"id":"kku_ph_mph","title_th":"หลักสูตรสาธารณสุขศาสตรมหาบัณฑิต","title_en":"Master of Public Health Program","degree_level":"ปริญญาโท","degree_name":"ส.ม. (สาธารณสุขศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Public Health","faculty_th":"คณะสาธารณสุขศาสตร์","department":"Graduate Studies PH","department_th":"บัณฑิตศึกษา คณะสาธารณสุขศาสตร์","program_type":"ภาคปกติ / ภาคพิเศษ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"88,000 บาท","description":"วิจัยระบบสุขภาพอีสาน ระบาดวิทยาภาคสนาม และนโยบายสุขภาพเพื่อลดความเหลื่อมล้ำ","curriculum_highlights":["Field Epidemiology & Outbreak Investigation","Health Systems Research Isan","Biostatistics for Public Health","Health Policy & Equity","MPH Thesis"],"career_paths":["Public Health Researcher","Epidemiologist","Health Policy Analyst","NGO Health Manager","Academic"],"tags":["MPH","KKU","Public Health"],"website_url":"https://ph.kku.ac.th"},
  {"id":"kku_ph_dph","title_th":"หลักสูตรสาธารณสุขศาสตรดุษฎีบัณฑิต สาขาวิชาสาธารณสุขศาสตร์","title_en":"Doctor of Public Health Program","degree_level":"ปริญญาเอก","degree_name":"ส.ด. (สาธารณสุขศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Public Health","faculty_th":"คณะสาธารณสุขศาสตร์","department":"Doctoral Program PH","department_th":"สาขาวิชาสาธารณสุขศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"210,000 บาท","description":"ผลิตนักวิจัยสาธารณสุขระดับแนวหน้า เน้นวิจัยระบบสุขภาพอีสานและความเหลื่อมล้ำทางสุขภาพ","curriculum_highlights":["Advanced Health Equity Research","Health Systems Leadership","Implementation Science","Dissertation in Public Health","International Publication"],"career_paths":["Public Health Professor","Health Systems Research Leader","Policy Maker","International Health Consultant","Director Public Health"],"tags":["DrPH","KKU","Public Health"],"website_url":"https://ph.kku.ac.th"},

  # === COLLEGE OF COMPUTING (8) ===
  {"id":"kku_comp_cs_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์","title_en":"Bachelor of Science Program in Computer Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาการคอมพิวเตอร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Computing","faculty_th":"วิทยาลัยการคอมพิวเตอร์","department":"Division of Computer Science","department_th":"สาขาวิชาวิทยาการคอมพิวเตอร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"176,000 บาท","description":"เน้นอัลกอริทึม ปัญญาประดิษฐ์ การพัฒนาซอฟต์แวร์ และวิทยาการข้อมูลเพื่ออุตสาหกรรมดิจิทัลภาคอีสานและ EEC","curriculum_highlights":["Algorithms & Data Structures","Artificial Intelligence & Machine Learning","Full-Stack Software Development","Data Science & Big Data","Cybersecurity Fundamentals"],"career_paths":["Software Developer","AI Engineer","Data Scientist","Cybersecurity Analyst","Full-Stack Developer"],"tags":["Computer Science","KKU","College of Computing","CS"],"website_url":"https://computing.kku.ac.th"},
  {"id":"kku_comp_it_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีสารสนเทศ","title_en":"Bachelor of Science Program in Information Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคโนโลยีสารสนเทศ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Computing","faculty_th":"วิทยาลัยการคอมพิวเตอร์","department":"Division of Information Technology","department_th":"สาขาวิชาเทคโนโลยีสารสนเทศ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"176,000 บาท","description":"เน้นการบริหารโครงสร้างพื้นฐานไอที คลาวด์คอมพิวติ้ง และความมั่นคงปลอดภัยไซเบอร์สำหรับองค์กรยุคดิจิทัล","curriculum_highlights":["Cloud Infrastructure & Virtualization","Network & System Administration","Cybersecurity & Ethical Hacking","Web & Mobile Application Development","IT Project Management"],"career_paths":["IT Infrastructure Engineer","Cloud Administrator","Network Engineer","Cybersecurity Specialist","IT Project Manager"],"tags":["Information Technology","Cloud","KKU","Computing"],"website_url":"https://computing.kku.ac.th"},
  {"id":"kku_comp_ai_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาปัญญาประดิษฐ์","title_en":"Bachelor of Science Program in Artificial Intelligence","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ปัญญาประดิษฐ์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Computing","faculty_th":"วิทยาลัยการคอมพิวเตอร์","department":"Division of AI","department_th":"สาขาวิชาปัญญาประดิษฐ์","program_type":"ภาคปกติ / นานาชาติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"32,000 บาท","tuition_total":"256,000 บาท","description":"หลักสูตร AI แห่งแรกภาคอีสาน เน้น Deep Learning, NLP, Computer Vision และ Generative AI ประยุกต์เกษตรและสุขภาพ","curriculum_highlights":["Deep Learning & Neural Networks","Natural Language Processing (Thai NLP)","Computer Vision & Image Recognition","Generative AI & LLM Applications","AI for Agriculture & Health"],"career_paths":["AI Engineer","Machine Learning Engineer","NLP Specialist","Computer Vision Engineer","AI Product Manager"],"tags":["Artificial Intelligence","KKU","Computing","AI"],"website_url":"https://computing.kku.ac.th"},
  {"id":"kku_comp_cyber_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาความมั่นคงปลอดภัยไซเบอร์","title_en":"Bachelor of Science Program in Cybersecurity","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ความมั่นคงปลอดภัยไซเบอร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Computing","faculty_th":"วิทยาลัยการคอมพิวเตอร์","department":"Division of Cybersecurity","department_th":"สาขาวิชาความมั่นคงปลอดภัยไซเบอร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"26,000 บาท","tuition_total":"208,000 บาท","description":"เน้นการป้องกันภัยไซเบอร์ การเจาะระบบอย่างมีจริยธรรม Digital Forensics และความปลอดภัยระบบคลาวด์","curriculum_highlights":["Ethical Hacking & Penetration Testing","Digital Forensics & Incident Response","Network Security & SOC Operations","Cloud & IoT Security","Cyber Law & Risk Management"],"career_paths":["Cybersecurity Analyst","Penetration Tester","SOC Analyst","Digital Forensic Investigator","Security Consultant"],"tags":["Cybersecurity","KKU","Computing"],"website_url":"https://computing.kku.ac.th"},
  {"id":"kku_comp_ds_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการข้อมูล","title_en":"Bachelor of Science Program in Data Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาการข้อมูล)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Computing","faculty_th":"วิทยาลัยการคอมพิวเตอร์","department":"Division of Data Science","department_th":"สาขาวิชาวิทยาการข้อมูล","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"24,000 บาท","tuition_total":"192,000 บาท","description":"เน้นวิศวกรรมข้อมูล การวิเคราะห์ข้อมูลขนาดใหญ่ และการสร้างโมเดล AI เพื่อธุรกิจและอุตสาหกรรมอีสาน","curriculum_highlights":["Data Engineering & Data Warehousing","Big Data Analytics (Spark/Hadoop)","Machine Learning & Predictive Modeling","Data Visualization & BI Dashboards","Cloud Data Platforms"],"career_paths":["Data Engineer","Data Scientist","Data Analyst","BI Developer","ML Engineer"],"tags":["Data Science","KKU","Computing","Big Data"],"website_url":"https://computing.kku.ac.th"},
  {"id":"kku_comp_se_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิศวกรรมซอฟต์แวร์","title_en":"Bachelor of Science Program in Software Engineering","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิศวกรรมซอฟต์แวร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Computing","faculty_th":"วิทยาลัยการคอมพิวเตอร์","department":"Division of Software Engineering","department_th":"สาขาวิชาวิศวกรรมซอฟต์แวร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"24,000 บาท","tuition_total":"192,000 บาท","description":"เน้นการพัฒนาซอฟต์แวร์ระดับองค์กร Agile/DevOps สถาปัตยกรรมไมโครเซอร์วิส และการทดสอบซอฟต์แวร์","curriculum_highlights":["Agile Software Engineering & Scrum","Microservices & Cloud-Native Architecture","DevOps & CI/CD Pipelines","Software Testing & Quality Assurance","Mobile & Web App Engineering"],"career_paths":["Software Engineer","DevOps Engineer","QA Engineer","Software Architect","Product Manager"],"tags":["Software Engineering","KKU","Computing"],"website_url":"https://computing.kku.ac.th"},
  {"id":"kku_comp_gis_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาภูมิสารสนเทศศาสตร์","title_en":"Bachelor of Science Program in Geo-Informatics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ภูมิสารสนเทศศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Computing","faculty_th":"วิทยาลัยการคอมพิวเตอร์","department":"Division of Geo-Informatics","department_th":"สาขาวิชาภูมิสารสนเทศศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้น GIS, Remote Sensing, โดรนสำรวจ และการวิเคราะห์ข้อมูลเชิงพื้นที่เพื่อการเกษตรและผังเมืองอีสาน","curriculum_highlights":["GIS & Spatial Database","Remote Sensing & Drone Mapping","Spatial Analysis & Modeling","Web GIS Development","GIS for Agriculture & Urban Planning"],"career_paths":["GIS Specialist","Remote Sensing Analyst","Drone Surveyor","Urban Planning GIS Officer","Geospatial Data Scientist"],"tags":["Geo-Informatics","GIS","Remote Sensing","KKU"],"website_url":"https://computing.kku.ac.th"},
  {"id":"kku_comp_ai_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาการข้อมูลและปัญญาประดิษฐ์","title_en":"Master of Science Program in Data Science and Artificial Intelligence","degree_level":"ปริญญาโท","degree_name":"วท.ม. (วิทยาการข้อมูลและปัญญาประดิษฐ์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Computing","faculty_th":"วิทยาลัยการคอมพิวเตอร์","department":"Graduate Studies","department_th":"บัณฑิตศึกษา วิทยาลัยการคอมพิวเตอร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"32,000 บาท","tuition_total":"128,000 บาท","description":"วิจัยขั้นสูงด้าน LLM, Computer Vision และการประยุกต์ AI ในการเกษตรแม่นยำและสุขภาพ","curriculum_highlights":["Advanced Deep Learning & LLMs","Computer Vision & Thai NLP","Data Engineering at Scale","AI Ethics & MLOps","Thesis in DSAI"],"career_paths":["AI Researcher","Data Science Lead","ML Engineer Senior","AI Consultant","Ph.D. Candidate"],"tags":["AI","Data Science","Master Degree","KKU","Computing"],"website_url":"https://computing.kku.ac.th"},
]

print(f"Prepared {len(NEW_KKU_COURSES)} new KKU courses")

# Save to JSON for audit
out_path = pathlib.Path("backend/data/courses_new/courses_kku_full_expansion.json")
out_path.parent.mkdir(parents=True, exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(NEW_KKU_COURSES, f, ensure_ascii=False, indent=2)
print(f"Saved to {out_path}")

# Seed to DB
Base.metadata.create_all(bind=engine)
session = SessionLocal()
inserted=updated=0
for c in NEW_KKU_COURSES:
    emb_text = build_embedding_text(c)
    try:
        emb_vec = embedding_service.get_embedding(emb_text)
        if emb_vec and len(emb_vec)!=768:
            emb_vec=None
    except Exception as e:
        print(f"Embedding fail {c['id']}: {e}")
        emb_vec=None
    existing = session.query(CourseDB).filter_by(id=c["id"]).first()
    if existing:
        for k,v in c.items():
            setattr(existing, k, v)
        existing.embedding_text=emb_text
        if emb_vec:
            existing.embedding=emb_vec
        updated+=1
        print(f"Updated {c['id']}")
    else:
        db_obj = CourseDB(
            id=c["id"], title_th=c["title_th"], title_en=c.get("title_en"), degree_level=c["degree_level"], degree_name=c.get("degree_name"),
            university=c["university"], university_th=c["university_th"], faculty=c["faculty"], faculty_th=c["faculty_th"],
            department=c.get("department"), department_th=c.get("department_th"), program_type=c.get("program_type","ภาคปกติ"),
            duration_years=c.get("duration_years"), total_credits=c.get("total_credits"), tuition_per_semester=c.get("tuition_per_semester"),
            tuition_total=c.get("tuition_total"), description=c.get("description"), curriculum_highlights=c.get("curriculum_highlights",[]),
            career_paths=c.get("career_paths",[]), tags=c.get("tags",[]), website_url=c.get("website_url"),
            embedding_text=emb_text, embedding=emb_vec if emb_vec else None
        )
        session.add(db_obj)
        inserted+=1
        print(f"Inserted {c['id']} emb={'OK' if emb_vec else 'NULL'}")
    # commit per 10 to avoid long transaction
    if (inserted+updated)%20==0:
        session.commit()
session.commit()
print(f"\nDone inserted={inserted} updated={updated}")
from sqlalchemy import text
with engine.connect() as conn:
    total=conn.execute(text("SELECT COUNT(*) FROM courses WHERE university='Khon Kaen University'")).scalar()
    print(f"KKU total now: {total}")
    total_all=conn.execute(text("SELECT COUNT(*) FROM courses")).scalar()
    print(f"DB total all: {total_all}")
session.close()
