# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')
import os, json, pathlib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.core.database import SessionLocal, engine, Base
from app.models.db_models import CourseDB
from app.core.embedding_service import embedding_service

def emb_text(c):
    hl=", ".join(c.get("curriculum_highlights",[]))
    cp=", ".join(c.get("career_paths",[]))
    tags=", ".join(c.get("tags",[]))
    return f"{c['title_th']} {c.get('title_en','')}. University: {c['university']} {c['university_th']}. Faculty: {c['faculty']} {c['faculty_th']}. Department: {c.get('department','')} {c.get('department_th','')}. Degree: {c['degree_level']} {c.get('degree_name','')}. Description: {c.get('description','')}. Highlights: {hl}. Careers: {cp}. Tags: {tags}."

NEW2 = [
  # === FACULTY OF LAW (5) ===
  {"id":"kku_law_llb","title_th":"หลักสูตรนิติศาสตรบัณฑิต","title_en":"Bachelor of Laws Program (LL.B.)","degree_level":"ปริญญาตรี","degree_name":"น.บ. (นิติศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Law","faculty_th":"คณะนิติศาสตร์","department":"Department of Law","department_th":"ภาควิชานิติศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"135 หน่วยกิต","tuition_per_semester":"13,000 บาท","tuition_total":"104,000 บาท","description":"เน้นกฎหมายแพ่ง อาญา กฎหมายมหาชน กฎหมายธุรกิจ และกฎหมายชุมชนอีสาน พร้อมฝึกปฏิบัติศาลจำลองและคลินิกกฎหมายชุมชน","curriculum_highlights":["Civil & Criminal Law and Procedure","Public Law & Constitutional Law","Business Law & Isan Community Legal Clinic","Moot Court & Legal Practice","Law and Digital Technology"],"career_paths":["Lawyer / Attorney","Legal Officer in Government","Corporate Legal Counsel","Judge / Prosecutor (ต่อไป)","Legal Consultant Community"],"tags":["Law","LLB","Legal Clinic","KKU"],"website_url":"https://law.kku.ac.th"},
  {"id":"kku_law_llm","title_th":"หลักสูตรนิติศาสตรมหาบัณฑิต","title_en":"Master of Laws Program (LL.M.)","degree_level":"ปริญญาโท","degree_name":"น.ม. (นิติศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Law","faculty_th":"คณะนิติศาสตร์","department":"Graduate Studies in Law","department_th":"บัณฑิตศึกษา คณะนิติศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"88,000 บาท","description":"เน้นวิจัยกฎหมายธุรกิจ การค้าระหว่างประเทศ กฎหมายสิ่งแวดล้อม และกฎหมายปกครองท้องถิ่นอีสาน","curriculum_highlights":["Advanced Business Law & Cross-Border Trade","Environmental Law & Climate Justice","Local Administrative Law in Isan","Legal Research & Thesis","International Law & GMS"],"career_paths":["Legal Researcher","Corporate Counsel Senior","Policy Legal Analyst","Academic","Ph.D. Candidate Law"],"tags":["LLM","Business Law","KKU"],"website_url":"https://law.kku.ac.th"},
  {"id":"kku_law_lld","title_th":"หลักสูตรนิติศาสตรดุษฎีบัณฑิต","title_en":"Doctor of Laws Program","degree_level":"ปริญญาเอก","degree_name":"น.ด. (นิติศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Law","faculty_th":"คณะนิติศาสตร์","department":"Doctoral Program in Law","department_th":"สาขาวิชานิติศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"210,000 บาท","description":"ผลิตนักวิจัยกฎหมายระดับแนวหน้า เน้นกฎหมายชุมชนอีสาน ความยุติธรรมทางสังคม และนิติปรัชญา","curriculum_highlights":["Advanced Legal Theory & Isan Justice","Community Law Research","Dissertation in Law & Society","Comparative GMS Law","Publication & Academic Leadership"],"career_paths":["Law Professor","Legal Research Leader","Justice Policy Maker","Senior Legal Advisor","Constitutional Expert"],"tags":["Ph.D. Law","KKU","Isan Justice"],"website_url":"https://law.kku.ac.th"},
  {"id":"kku_law_business_llb","title_th":"หลักสูตรนิติศาสตรบัณฑิต สาขาวิชากฎหมายธุรกิจ (หลักสูตรนานาชาติ)","title_en":"Bachelor of Laws Program in Business Law (International Program)","degree_level":"ปริญญาตรี","degree_name":"น.บ. (กฎหมายธุรกิจ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Law","faculty_th":"คณะนิติศาสตร์","department":"Department of Business Law","department_th":"ภาควิชากฎหมายธุรกิจ","program_type":"นานาชาติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"280,000 บาท","description":"หลักสูตรนานาชาติเน้นกฎหมายการค้าระหว่างประเทศ อนุภูมิภาคลุ่มน้ำโขง และการลงทุนข้ามพรมแดน ไทย-ลาว-เวียดนาม-จีน","curriculum_highlights":["International Trade Law (GMS)","Cross-Border Investment Law","Business Negotiation & Arbitration","Chinese Business Law Basics","Internship in Cross-Border Firms"],"career_paths":["International Business Lawyer","Cross-Border Trade Counsel","Arbitrator Assistant","Compliance Officer","GMS Legal Consultant"],"tags":["Business Law","International Program","GMS","KKU"],"website_url":"https://law.kku.ac.th"},
  {"id":"kku_law_ai_llm","title_th":"หลักสูตรนิติศาสตรมหาบัณฑิต สาขาวิชากฎหมายเทคโนโลยีและปัญญาประดิษฐ์","title_en":"Master of Laws Program in Technology and AI Law","degree_level":"ปริญญาโท","degree_name":"น.ม. (กฎหมายเทคโนโลยี)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Law","faculty_th":"คณะนิติศาสตร์","department":"Department of Technology Law","department_th":"ภาควิชากฎหมายเทคโนโลยี","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"28,000 บาท","tuition_total":"112,000 บาท","description":"วิจัยกฎหมายดิจิทัล PDPA, AI Governance, FinTech Law และอาชญากรรมไซเบอร์สำหรับเศรษฐกิจดิจิทัลอีสาน","curriculum_highlights":["PDPA & Data Governance","AI Ethics & Regulation","FinTech & Digital Asset Law","Cybercrime & Digital Evidence","Thesis in Tech Law"],"career_paths":["Tech Lawyer","Data Protection Officer","FinTech Compliance","Cyber Law Specialist","Academic Tech Law"],"tags":["Tech Law","AI Law","PDPA","KKU"],"website_url":"https://law.kku.ac.th"},

  # === FACULTY OF FINE AND APPLIED ARTS (6) ===
  {"id":"kku_faa_design_bfa","title_th":"หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชาการออกแบบ","title_en":"Bachelor of Fine Arts Program in Design","degree_level":"ปริญญาตรี","degree_name":"ศล.บ. (การออกแบบ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Fine and Applied Arts","faculty_th":"คณะศิลปกรรมศาสตร์","department":"Department of Design","department_th":"ภาควิชาการออกแบบ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นการออกแบบผลิตภัณฑ์ หัตถกรรมอีสานร่วมสมัย กราฟิกดีไซน์ และ UI/UX เพื่อยกระดับเศรษฐกิจสร้างสรรค์อีสาน","curriculum_highlights":["Isan Contemporary Craft & Product Design","Graphic Design & Branding","UX/UI Design & Prototyping","Creative Entrepreneurship","Design Studio & Exhibition"],"career_paths":["Product Designer","Graphic Designer","UX/UI Designer","Craft Entrepreneur","Creative Director"],"tags":["Design","Isan Craft","UX/UI","KKU","FAA"],"website_url":"https://faa.kku.ac.th"},
  {"id":"kku_faa_music_bfa","title_th":"หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชาดุริยางคศิลป์","title_en":"Bachelor of Fine Arts Program in Music","degree_level":"ปริญญาตรี","degree_name":"ศล.บ. (ดุริยางคศิลป์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Fine and Applied Arts","faculty_th":"คณะศิลปกรรมศาสตร์","department":"Department of Music","department_th":"ภาควิชาดุริยางคศิลป์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นดนตรีไทย ดนตรีอีสาน (หมอลำ โปงลาง) ดนตรีสากล ซาวด์เอ็นจิเนียริ่ง และการจัดการแสดงดนตรี","curriculum_highlights":["Isan Folk Music (Mor Lam, Pong Lang)","Western Music Performance & Composition","Sound Engineering & Music Technology","Music Business & Event Management","Ensemble & Recital"],"career_paths":["Music Performer","Sound Engineer","Music Teacher","Music Event Organizer","Composer"],"tags":["Music","Mor Lam","KKU","FAA"],"website_url":"https://faa.kku.ac.th"},
  {"id":"kku_faa_drama_bfa","title_th":"หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชาศิลปะการแสดง","title_en":"Bachelor of Fine Arts Program in Performing Arts","degree_level":"ปริญญาตรี","degree_name":"ศล.บ. (ศิลปะการแสดง)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Fine and Applied Arts","faculty_th":"คณะศิลปกรรมศาสตร์","department":"Department of Performing Arts","department_th":"ภาควิชาศิลปะการแสดง","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นนาฏศิลป์อีสาน การละครร่วมสมัย การกำกับการแสดง และการจัดการเทศกาลศิลปะอีสาน","curriculum_highlights":["Isan Dance & Contemporary Theatre","Acting & Directing","Choreography & Stage Design","Arts Festival Management","Performing Arts Production"],"career_paths":["Performer / Dancer","Theatre Director","Choreographer","Arts Festival Manager","Drama Teacher"],"tags":["Performing Arts","Isan Dance","KKU"],"website_url":"https://faa.kku.ac.th"},
  {"id":"kku_faa_visual_bfa","title_th":"หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชาทัศนศิลป์","title_en":"Bachelor of Fine Arts Program in Visual Arts","degree_level":"ปริญญาตรี","degree_name":"ศล.บ. (ทัศนศิลป์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Fine and Applied Arts","faculty_th":"คณะศิลปกรรมศาสตร์","department":"Department of Visual Arts","department_th":"ภาควิชาทัศนศิลป์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นจิตรกรรม ประติมากรรม ศิลปะสื่อผสม และศิลปะชุมชนอีสานเพื่อเศรษฐกิจสร้างสรรค์","curriculum_highlights":["Painting & Sculpture Studio","Mixed Media & Installation Art","Isan Community Art","Art Criticism & Curation","Graduation Exhibition"],"career_paths":["Visual Artist","Art Curator","Community Artist","Art Teacher","Gallery Manager"],"tags":["Visual Arts","KKU","FAA"],"website_url":"https://faa.kku.ac.th"},
  {"id":"kku_faa_creative_mfa","title_th":"หลักสูตรศิลปกรรมศาสตรมหาบัณฑิต สาขาวิชาเศรษฐกิจสร้างสรรค์","title_en":"Master of Fine Arts Program in Creative Economy","degree_level":"ปริญญาโท","degree_name":"ศล.ม. (เศรษฐกิจสร้างสรรค์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Fine and Applied Arts","faculty_th":"คณะศิลปกรรมศาสตร์","department":"Graduate Studies FAA","department_th":"บัณฑิตศึกษา คณะศิลปกรรมศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"88,000 บาท","description":"วิจัยเศรษฐกิจสร้างสรรค์อีสาน หัตถกรรมดิจิทัล และ Cultural Entrepreneurship","curriculum_highlights":["Isan Creative Economy Research","Digital Craft & NFT Art","Cultural Entrepreneurship Lab","Thesis in Creative Arts","Isan Heritage Innovation"],"career_paths":["Creative Economy Researcher","Cultural Entrepreneur","Arts Administrator","Creative Policy Analyst","Academic Artist"],"tags":["Creative Economy","Master Degree","KKU"],"website_url":"https://faa.kku.ac.th"},
  {"id":"kku_faa_animation_bfa","title_th":"หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชาแอนิเมชันและวิชวลเอฟเฟกต์","title_en":"Bachelor of Fine Arts Program in Animation and Visual Effects","degree_level":"ปริญญาตรี","degree_name":"ศล.บ. (แอนิเมชันและวิชวลเอฟเฟกต์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Fine and Applied Arts","faculty_th":"คณะศิลปกรรมศาสตร์","department":"Department of Animation","department_th":"ภาควิชาแอนิเมชัน","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"176,000 บาท","description":"เน้นแอนิเมชัน 2D/3D โมชั่นกราฟิก VFX และเกมอาร์ตด้วย Generative AI","curriculum_highlights":["3D Character Modeling & Rigging","VFX & Compositing (After Effects/Houdini)","Game Art & Unity","Motion Graphics & Storytelling","AI-Assisted Animation"],"career_paths":["Animator","VFX Artist","Game Artist","Motion Graphics Designer","Creative Technologist"],"tags":["Animation","VFX","Game Art","KKU"],"website_url":"https://faa.kku.ac.th"},

  # === FACULTY OF ARCHITECTURE (7) ===
  {"id":"kku_arch_barch","title_th":"หลักสูตรสถาปัตยกรรมศาสตรบัณฑิต","title_en":"Bachelor of Architecture Program","degree_level":"ปริญญาตรี","degree_name":"สถ.บ. (สถาปัตยกรรมศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Architecture","faculty_th":"คณะสถาปัตยกรรมศาสตร์","department":"Department of Architecture","department_th":"ภาควิชาสถาปัตยกรรมศาสตร์","program_type":"ภาคปกติ","duration_years":"5 ปี","total_credits":"165 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"180,000 บาท","description":"เน้นออกแบบสถาปัตยกรรมเขตร้อน สถาปัตยกรรมอีสานร่วมสมัย ผังชุมชนอีสาน และสถาปัตยกรรมยั่งยืน","curriculum_highlights":["Tropical Architecture & Isan Vernacular","Architectural Design Studio I-V","Building Technology & Structure","Sustainable & Green Building","Urban Design for Isan Communities"],"career_paths":["Architect","Urban Designer","Sustainable Building Consultant","Interior Architect Assistant","Construction Manager"],"tags":["Architecture","Isan Vernacular","Sustainable Design","KKU"],"website_url":"https://arch.kku.ac.th"},
  {"id":"kku_arch_interior_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสถาปัตยกรรมภายใน","title_en":"Bachelor of Science Program in Interior Architecture","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (สถาปัตยกรรมภายใน)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Architecture","faculty_th":"คณะสถาปัตยกรรมศาสตร์","department":"Department of Interior Architecture","department_th":"ภาควิชาสถาปัตยกรรมภายใน","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นออกแบบพื้นที่ภายในเชิงประสบการณ์ แสง สี วัสดุอีสาน และ Interior Tech","curriculum_highlights":["Interior Design Studio","Lighting & Materials in Isan Context","Furniture & Product Design","3D Visualization (BIM/Revit)","Interior Business & Practice"],"career_paths":["Interior Architect","Interior Designer","Furniture Designer","3D Visualizer","Design Consultant"],"tags":["Interior Architecture","KKU"],"website_url":"https://arch.kku.ac.th"},
  {"id":"kku_arch_urban_burp","title_th":"หลักสูตรการผังเมืองบัณฑิต","title_en":"Bachelor of Urban and Regional Planning Program","degree_level":"ปริญญาตรี","degree_name":"ผ.บ. (การผังเมือง)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Architecture","faculty_th":"คณะสถาปัตยกรรมศาสตร์","department":"Department of Urban Planning","department_th":"ภาควิชาการผังเมือง","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"136 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นผังเมืองอีสาน เมืองอัจฉริยะ GIS และการพัฒนาพื้นที่ลุ่มน้ำโขงอย่างยั่งยืน","curriculum_highlights":["Urban Planning Studio Isan","GIS & Remote Sensing for Planning","Smart City & Resilient City","Transportation & TOD","Community Planning Participation"],"career_paths":["Urban Planner","GIS Analyst","Smart City Officer","TOD Consultant","Community Planner"],"tags":["Urban Planning","GIS","Smart City","KKU"],"website_url":"https://arch.kku.ac.th"},
  {"id":"kku_arch_landscape_bla","title_th":"หลักสูตรภูมิสถาปัตยกรรมศาสตรบัณฑิต","title_en":"Bachelor of Landscape Architecture Program","degree_level":"ปริญญาตรี","degree_name":"ภ.สถ.บ. (ภูมิสถาปัตยกรรม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Architecture","faculty_th":"คณะสถาปัตยกรรมศาสตร์","department":"Department of Landscape Architecture","department_th":"ภาควิชาภูมิสถาปัตยกรรม","program_type":"ภาคปกติ","duration_years":"5 ปี","total_credits":"150 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"180,000 บาท","description":"เน้นออกแบบภูมิทัศน์เขตร้อน ภูมิทัศน์วัฒนธรรมอีสาน และการฟื้นฟูระบบนิเวศลุ่มน้ำโขง","curriculum_highlights":["Tropical Landscape Design","Isan Cultural Landscape","Ecological Restoration & Mekong","Planting Design & Horticulture","Landscape Construction & Ecology"],"career_paths":["Landscape Architect","Ecological Restoration Designer","Urban Green Space Planner","Resort Landscape Designer","Environmental Consultant"],"tags":["Landscape Architecture","KKU","Ecology"],"website_url":"https://arch.kku.ac.th"},
  {"id":"kku_arch_industrial_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาการออกแบบอุตสาหกรรม","title_en":"Bachelor of Science Program in Industrial Design","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (การออกแบบอุตสาหกรรม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Architecture","faculty_th":"คณะสถาปัตยกรรมศาสตร์","department":"Department of Industrial Design","department_th":"ภาควิชาการออกแบบอุตสาหกรรม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"134 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นออกแบบผลิตภัณฑ์อุตสาหกรรม เฟอร์นิเจอร์อีสาน และบรรจุภัณฑ์สร้างสรรค์ด้วย Design Thinking","curriculum_highlights":["Product Design Studio & Prototyping","Isan Furniture & Craft Innovation","Packaging & Service Design","Design Thinking & UX Research","Industrial Design Entrepreneurship"],"career_paths":["Industrial Designer","Product Design Entrepreneur","Furniture Designer","Packaging Designer","Design Researcher"],"tags":["Industrial Design","KKU","Product Design"],"website_url":"https://arch.kku.ac.th"},
  {"id":"kku_arch_march","title_th":"หลักสูตรสถาปัตยกรรมศาสตรมหาบัณฑิต","title_en":"Master of Architecture Program","degree_level":"ปริญญาโท","degree_name":"สถ.ม. (สถาปัตยกรรมศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Architecture","faculty_th":"คณะสถาปัตยกรรมศาสตร์","department":"Graduate Studies Architecture","department_th":"บัณฑิตศึกษา คณะสถาปัตยกรรมศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"26,000 บาท","tuition_total":"104,000 บาท","description":"วิจัยสถาปัตยกรรมยั่งยืนเขตร้อน และการอนุรักษ์สถาปัตยกรรมอีสาน","curriculum_highlights":["Sustainable Tropical Architecture Research","Isan Heritage Conservation","Advanced Design Studio & Thesis","Building Performance Simulation","Thesis in Architecture"],"career_paths":["Architect Researcher","Heritage Conservation Specialist","Sustainable Design Consultant","Academic Architect","Urban Design Researcher"],"tags":["M.Arch","Sustainable Architecture","KKU"],"website_url":"https://arch.kku.ac.th"},
  {"id":"kku_arch_darch","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาสถาปัตยกรรม","title_en":"Doctor of Philosophy Program in Architecture","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (สถาปัตยกรรม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Architecture","faculty_th":"คณะสถาปัตยกรรมศาสตร์","department":"Doctoral Program in Architecture","department_th":"สาขาวิชาสถาปัตยกรรม","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"38,000 บาท","tuition_total":"228,000 บาท","description":"วิจัยขั้นสูงด้านผังเมืองอีสานและสถาปัตยกรรมพื้นถิ่นลุ่มน้ำโขง","curriculum_highlights":["Vernacular Architecture Theory Isan","Urban Resilience Research Mekong","Dissertation in Architecture","International Studio & Publication","Heritage Policy Research"],"career_paths":["Architecture Professor","Urban Research Leader","Heritage Policy Maker","International Consultant","Design Research Director"],"tags":["Ph.D. Architecture","KKU","Vernacular"],"website_url":"https://arch.kku.ac.th"},

  # === FACULTY OF ECONOMICS (เพิ่ม 5) ===
  {"id":"kku_econ_ba","title_th":"หลักสูตรเศรษฐศาสตรบัณฑิต","title_en":"Bachelor of Economics Program","degree_level":"ปริญญาตรี","degree_name":"ศ.บ. (เศรษฐศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Department of Economics","department_th":"ภาควิชาเศรษฐศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นเศรษฐศาสตร์จุลภาค มหภาค เศรษฐมิติ และการวิเคราะห์นโยบายเศรษฐกิจอีสานและอนุภูมิภาคลุ่มน้ำโขง","curriculum_highlights":["Micro & Macro Economics Isan","Econometrics & Data Analysis","Development Economics & Isan Poverty","International Economics (GMS)","Monetary & Fiscal Policy Lab"],"career_paths":["Economist","Economic Analyst","Policy Researcher","Bank Analyst","Data Analyst Economics"],"tags":["Economics","Econometrics","KKU","GMS"],"website_url":"https://econ.kku.ac.th"},
  {"id":"kku_econ_ba_inter","title_th":"หลักสูตรเศรษฐศาสตรบัณฑิต (หลักสูตรนานาชาติ)","title_en":"Bachelor of Economics Program (International Program)","degree_level":"ปริญญาตรี","degree_name":"ศ.บ. (เศรษฐศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Department of Economics","department_th":"ภาควิชาเศรษฐศาสตร์","program_type":"นานาชาติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"320,000 บาท","description":"หลักสูตรนานาชาติ 100% English เน้น International Economics, Behavioral Economics และ GMS Trade","curriculum_highlights":["International Economics & GMS Trade","Behavioral & Experimental Economics","Financial Economics & FinTech","Econometrics with Python/R","Internship in International Organizations"],"career_paths":["International Economist","Trade Analyst GMS","Financial Analyst","Behavioral Researcher","International NGO Officer"],"tags":["Economics","International Program","GMS","KKU"],"website_url":"https://econ.kku.ac.th"},
  {"id":"kku_econ_business_ba","title_th":"หลักสูตรเศรษฐศาสตรบัณฑิต สาขาวิชาเศรษฐศาสตร์ธุรกิจ","title_en":"Bachelor of Economics Program in Business Economics","degree_level":"ปริญญาตรี","degree_name":"ศ.บ. (เศรษฐศาสตร์ธุรกิจ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Department of Business Economics","department_th":"ภาควิชาเศรษฐศาสตร์ธุรกิจ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นการประยุกต์เศรษฐศาสตร์กับธุรกิจ การเงินธุรกิจ และการวิเคราะห์การลงทุนอีสาน","curriculum_highlights":["Business Economics & Strategy","Managerial Economics & Pricing","Investment Analysis & Valuation","Business Forecasting & Analytics","Entrepreneurship Economics"],"career_paths":["Business Economist","Investment Analyst","Business Consultant","Corporate Strategist","Entrepreneur"],"tags":["Business Economics","KKU"],"website_url":"https://econ.kku.ac.th"},
  {"id":"kku_econ_msc","title_th":"หลักสูตรเศรษฐศาสตรมหาบัณฑิต","title_en":"Master of Economics Program","degree_level":"ปริญญาโท","degree_name":"ศ.ม. (เศรษฐศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Graduate Studies Economics","department_th":"บัณฑิตศึกษา คณะเศรษฐศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"80,000 บาท","description":"วิจัยเศรษฐศาสตร์พัฒนาอีสาน เศรษฐกิจแรงงาน และนโยบายลดความเหลื่อมล้ำ","curriculum_highlights":["Development Economics Isan","Labor Economics & Inequality","Advanced Econometrics","Policy Evaluation & RCT","Thesis in Economics"],"career_paths":["Economic Researcher","Labor Economist","Policy Evaluator","PhD Candidate","Development Consultant"],"tags":["Master Economics","KKU","Development"],"website_url":"https://econ.kku.ac.th"},
  {"id":"kku_econ_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาเศรษฐศาสตร์","title_en":"Doctor of Philosophy Program in Economics","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (เศรษฐศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Economics","faculty_th":"คณะเศรษฐศาสตร์","department":"Doctoral Program in Economics","department_th":"สาขาวิชาเศรษฐศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"210,000 บาท","description":"ผลิตนักเศรษฐศาสตร์วิจัยระดับแนวหน้า เน้น Isan-GMS Development Economics","curriculum_highlights":["Advanced GMS Development Economics","Causal Inference & RCT","Dissertation in Economics","International Conference & Publication","Teaching Economics"],"career_paths":["Economics Professor","Senior Economist","Policy Research Director","International Organization Economist","Think Tank Leader"],"tags":["Ph.D. Economics","KKU","GMS"],"website_url":"https://econ.kku.ac.th"},

  # === FACULTY OF SCIENCE expansion (10) ===
  {"id":"kku_sci_bio_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาชีววิทยา","title_en":"Bachelor of Science Program in Biology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ชีววิทยา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Biology","department_th":"ภาควิชาชีววิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นชีววิทยาโมเลกุล นิเวศวิทยาลุ่มน้ำโขง และความหลากหลายทางชีวภาพอีสาน","curriculum_highlights":["Molecular Biology & Genetics","Mekong Ecology & Biodiversity","Conservation Biology Isan","Bioinformatics Basics","Field Biology Practicum"],"career_paths":["Biologist","Conservation Specialist","Lab Researcher","Environmental Consultant","Science Teacher"],"tags":["Biology","Mekong Ecology","KKU","Science"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_chem_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเคมี","title_en":"Bachelor of Science Program in Chemistry","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เคมี)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Chemistry","department_th":"ภาควิชาเคมี","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นเคมีวิเคราะห์ เคมีอินทรีย์ พอลิเมอร์ และวัสดุนาโนเพื่ออุตสาหกรรมอีสาน","curriculum_highlights":["Analytical & Organic Chemistry","Polymer & Materials Chemistry","Nanomaterials & Characterization","Chemical Instrumentation","Chemistry Lab Research Project"],"career_paths":["Chemist","Materials Scientist","QA/QC Chemist","Polymer Technologist","Lab Manager"],"tags":["Chemistry","KKU","Science"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_phys_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาฟิสิกส์","title_en":"Bachelor of Science Program in Physics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ฟิสิกส์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Physics","department_th":"ภาควิชาฟิสิกส์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นฟิสิกส์ประยุกต์ วัสดุศาสตร์ พลังงาน และฟิสิกส์ทฤษฎีเพื่อเทคโนโลยีอีสาน","curriculum_highlights":["Applied Physics & Materials","Renewable Energy Physics","Computational Physics (Python)","Quantum Basics & Optics","Physics Research Project"],"career_paths":["Physicist","Materials Researcher","Energy Technologist","Data Analyst Physics","Science Teacher"],"tags":["Physics","KKU","Science"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_math_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาคณิตศาสตร์","title_en":"Bachelor of Science Program in Mathematics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (คณิตศาสตร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Mathematics","department_th":"ภาควิชาคณิตศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นคณิตบริสุทธิ์ ประยุกต์ สถิติ และวิทยาการข้อมูลคณิตศาสตร์","curriculum_highlights":["Pure & Applied Mathematics","Statistics & Probability","Mathematical Modeling Isan","Data Science Math (R/Python)","Math Research Seminar"],"career_paths":["Mathematician","Data Analyst","Actuarial Assistant","Math Teacher","Operations Researcher"],"tags":["Mathematics","KKU","Science"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_stat_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสถิติ","title_en":"Bachelor of Science Program in Statistics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (สถิติ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Statistics","department_th":"ภาควิชาสถิติ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นสถิติประยุกต์ วิทยาการข้อมูล และการวิเคราะห์เชิงสถิติสำหรับธุรกิจและสาธารณสุขอีสาน","curriculum_highlights":["Applied Statistics & Experimental Design","Biostatistics & Public Health Data","Data Science & Machine Learning","Statistical Computing (R)","Statistical Consulting Practicum"],"career_paths":["Statistician","Biostatistician","Data Analyst","Market Research Analyst","Statistical Consultant"],"tags":["Statistics","Biostatistics","KKU","Data Science"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_micro_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาจุลชีววิทยา","title_en":"Bachelor of Science Program in Microbiology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (จุลชีววิทยา)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Microbiology","department_th":"ภาควิชาจุลชีววิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นจุลชีววิทยาทางการแพทย์ อาหาร อุตสาหกรรม และเทคโนโลยีชีวภาพจุลินทรีย์อีสาน","curriculum_highlights":["Medical & Food Microbiology","Industrial Microbiology & Fermentation","Microbial Genetics & Immunology","Environmental Microbiology Mekong","Microbiology Lab Research"],"career_paths":["Microbiologist","Food Microbiologist","Clinical Lab Scientist","Biotech Researcher","QA Microbiologist"],"tags":["Microbiology","KKU","Science"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_env_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์สิ่งแวดล้อม","title_en":"Bachelor of Science Program in Environmental Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาศาสตร์สิ่งแวดล้อม)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Environmental Science","department_th":"ภาควิชาวิทยาศาสตร์สิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการจัดการสิ่งแวดล้อมอีสาน มลพิษ PM2.5 น้ำเสีย และการประเมินผลกระทบสิ่งแวดล้อม (EIA)","curriculum_highlights":["Environmental Monitoring & PM2.5","EIA & HIA Principles","Waste & Wastewater Technology","GIS for Environmental Management","Field Environmental Practicum Isan"],"career_paths":["Environmental Scientist","EIA Consultant","Pollution Control Officer","GIS Environmental Analyst","Sustainability Officer"],"tags":["Environmental Science","EIA","KKU"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_compsci_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์ (เพิ่มเติม)","title_en":"Bachelor of Science Program in Computer Science (Science Faculty)","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาการคอมพิวเตอร์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Computer Science","department_th":"ภาควิชาวิทยาการคอมพิวเตอร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นทฤษฎีการคำนวณ อัลกอริทึม และวิทยาการข้อมูลพื้นฐานสำหรับคณะวิทยาศาสตร์","curriculum_highlights":["Theory of Computation & Algorithms","Database & Data Mining","AI Fundamentals & Logic Programming","Scientific Computing","CS Capstone Project"],"career_paths":["Computer Scientist","System Analyst","Data Analyst","Software Developer","Research Assistant"],"tags":["Computer Science","KKU","Science"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_biochem_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาชีวเคมี","title_en":"Bachelor of Science Program in Biochemistry","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ชีวเคมี)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Biochemistry","department_th":"ภาควิชาชีวเคมี","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นชีวเคมีโมเลกุล เอนไซม์ โปรตีน และเทคโนโลยีชีวภาพทางการแพทย์","curriculum_highlights":["Molecular Biochemistry & Enzymology","Protein Chemistry & Proteomics","Molecular Biology Techniques","Bioinformatics & Genomics","Biochemistry Research Project"],"career_paths":["Biochemist","Molecular Biologist","Lab Scientist","Biotech R&D","Pharmaceutical Analyst"],"tags":["Biochemistry","KKU","Science"],"website_url":"https://sc.kku.ac.th"},
  {"id":"kku_sci_data_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์ข้อมูล","title_en":"Master of Science Program in Data Science (Science Faculty)","degree_level":"ปริญญาโท","degree_name":"วท.ม. (วิทยาศาสตร์ข้อมูล)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Graduate Studies Science","department_th":"บัณฑิตศึกษา คณะวิทยาศาสตร์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"88,000 บาท","description":"วิจัยวิทยาการข้อมูลเชิงวิทยาศาสตร์สำหรับอีสาน เช่น ข้อมูลเกษตรและสุขภาพ","curriculum_highlights":["Statistical Learning & Data Mining","Big Data for Science","AI for Scientific Discovery","Thesis in Data Science","Scientific Data Visualization"],"career_paths":["Data Scientist Science","Research Data Analyst","Bioinformatics Specialist","Academic Researcher","Consultant"],"tags":["Data Science","Master Degree","KKU","Science"],"website_url":"https://sc.kku.ac.th"},

  # === COLLEGE OF LOCAL ADMINISTRATION (COLA 6) ===
  {"id":"kku_cola_pa_bpa","title_th":"หลักสูตรรัฐประศาสนศาสตรบัณฑิต สาขาวิชาการปกครองท้องถิ่น","title_en":"Bachelor of Public Administration Program in Local Administration","degree_level":"ปริญญาตรี","degree_name":"รป.บ. (การปกครองท้องถิ่น)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Local Administration","faculty_th":"วิทยาลัยการปกครองท้องถิ่น","department":"Department of Local Administration","department_th":"สาขาวิชาการปกครองท้องถิ่น","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นการบริหารองค์กรปกครองส่วนท้องถิ่น (อปท.) กระจายอำนาจอีสาน และนวัตกรรมท้องถิ่น","curriculum_highlights":["Local Government & Decentralization Isan","Local Finance & Budgeting","Community Participation & Innovation","Local Law & Regulation","Fieldwork in Isan Local Governments"],"career_paths":["Palad / Local Administrator","Local Government Officer (อบต./เทศบาล)","Community Development Officer","Policy Analyst Local","Local Innovation Consultant"],"tags":["Local Administration","COLA","Decentralization","KKU"],"website_url":"https://cola.kku.ac.th"},
  {"id":"kku_cola_pa_mpa","title_th":"หลักสูตรรัฐประศาสนศาสตรมหาบัณฑิต สาขาวิชาการปกครองท้องถิ่น","title_en":"Master of Public Administration Program in Local Administration","degree_level":"ปริญญาโท","degree_name":"รป.ม. (การปกครองท้องถิ่น)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Local Administration","faculty_th":"วิทยาลัยการปกครองท้องถิ่น","department":"Graduate Studies COLA","department_th":"บัณฑิตศึกษา วิทยาลัยการปกครองท้องถิ่น","program_type":"ภาคปกติ / ภาคพิเศษ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"80,000 บาท","description":"วิจัยการปกครองท้องถิ่นอีสาน ธรรมาภิบาล และนวัตกรรมบริการสาธารณะท้องถิ่น","curriculum_highlights":["Local Governance & Good Governance Isan","Public Innovation Lab","Local Policy Evaluation","Research Methods for Local Administration","Thesis in Local Administration"],"career_paths":["Local Government Executive","Policy Researcher","Governance Consultant","Academic COLA","Local Development Planner"],"tags":["MPA","Local Administration","KKU","COLA"],"website_url":"https://cola.kku.ac.th"},
  {"id":"kku_cola_dpa","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาการบริหารกิจการสาธารณะ","title_en":"Doctor of Philosophy Program in Public Affairs Management","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (การบริหารกิจการสาธารณะ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Local Administration","faculty_th":"วิทยาลัยการปกครองท้องถิ่น","department":"Doctoral Program COLA","department_th":"สาขาวิชาการบริหารกิจการสาธารณะ","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"210,000 บาท","description":"ผลิตนักวิจัยการปกครองท้องถิ่นระดับแนวหน้า เน้น Isan Decentralization","curriculum_highlights":["Advanced Local Governance Theory","Fiscal Decentralization Research","Dissertation in Public Affairs","International Local Government Comparison","Publication & Leadership"],"career_paths":["Professor COLA","Local Governance Research Director","Policy Maker Ministry Interior","International Consultant Decentralization","Think Tank Leader"],"tags":["Ph.D. COLA","KKU","Public Affairs"],"website_url":"https://cola.kku.ac.th"},
  {"id":"kku_cola_smartcity_mpa","title_th":"หลักสูตรรัฐประศาสนศาสตรมหาบัณฑิต สาขาวิชาเมืองอัจฉริยะและการจัดการท้องถิ่นดิจิทัล","title_en":"Master of Public Administration Program in Smart City and Digital Local Governance","degree_level":"ปริญญาโท","degree_name":"รป.ม. (เมืองอัจฉริยะ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Local Administration","faculty_th":"วิทยาลัยการปกครองท้องถิ่น","department":"Smart City Program","department_th":"สาขาวิชาเมืองอัจฉริยะ","program_type":"ภาคพิเศษ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"28,000 บาท","tuition_total":"112,000 บาท","description":"เน้น Smart City อีสาน GIS สำหรับท้องถิ่น และรัฐบาลดิจิทัลท้องถิ่น","curriculum_highlights":["Smart City Planning Isan (Khon Kaen Smart City)","GIS for Local Governments","Digital Government & Open Data Local","Smart Mobility & Environment","Capstone Smart City Isan"],"career_paths":["Smart City Officer","GIS Officer Local","Digital Government Manager","Local Innovation Officer","Urban Planner Local"],"tags":["Smart City","COLA","GIS","KKU"],"website_url":"https://cola.kku.ac.th"},
  {"id":"kku_cola_fiscal_bpa","title_th":"หลักสูตรรัฐประศาสตรบัณฑิต สาขาวิชาการคลังท้องถิ่น","title_en":"Bachelor of Public Administration Program in Local Fiscal Management","degree_level":"ปริญญาตรี","degree_name":"รป.บ. (การคลังท้องถิ่น)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Local Administration","faculty_th":"วิทยาลัยการปกครองท้องถิ่น","department":"Department of Local Finance","department_th":"ภาควิชาการคลังท้องถิ่น","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"14,000 บาท","tuition_total":"112,000 บาท","description":"เน้นการคลังท้องถิ่น งบประมาณ อปท. และภาษีท้องถิ่นอีสาน","curriculum_highlights":["Local Fiscal & Taxation Isan","Local Budgeting & Accounting","Public Procurement & Audit Local","Local Economic Development","Internship in Local Finance"],"career_paths":["Local Finance Officer","Budget Analyst Local","Tax Officer Local","Auditor Local Government","Local Economic Developer"],"tags":["Local Finance","COLA","KKU"],"website_url":"https://cola.kku.ac.th"},
  {"id":"kku_cola_disaster_mpa","title_th":"หลักสูตรรัฐประศาสนศาสตรมหาบัณฑิต สาขาวิชาการจัดการภัยพิบัติท้องถิ่น","title_en":"Master of Public Administration Program in Local Disaster Management","degree_level":"ปริญญาโท","degree_name":"รป.ม. (การจัดการภัยพิบัติท้องถิ่น)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"College of Local Administration","faculty_th":"วิทยาลัยการปกครองท้องถิ่น","department":"Disaster Management","department_th":"สาขาวิชาการจัดการภัยพิบัติ","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"88,000 บาท","description":"เน้นการจัดการน้ำท่วม ภัยแล้งอีสาน และการฟื้นฟูชุมชนท้องถิ่น","curriculum_highlights":["Flood & Drought Management Isan","Community Resilience & Recovery","GIS for Disaster Local","Local Emergency Planning","Thesis Disaster Local"],"career_paths":["Disaster Management Officer Local","Resilience Planner","Emergency Manager","NGO Disaster Officer","Researcher"],"tags":["Disaster Management","COLA","KKU"],"website_url":"https://cola.kku.ac.th"},

  # === KKBS expansion (4) ===
  {"id":"kku_kkbs_finance_bba","title_th":"หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาการเงิน","title_en":"Bachelor of Business Administration Program in Finance","degree_level":"ปริญญาตรี","degree_name":"บธ.บ. (การเงิน)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Business Administration and Accountancy (KKBS)","faculty_th":"คณะบริหารธุรกิจและการบัญชี","department":"Department of Finance","department_th":"สาขาวิชาการเงิน","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการเงินธุรกิจ การลงทุน ตลาดทุน และ FinTech สำหรับธุรกิจอีสานและ GMS","curriculum_highlights":["Corporate Finance & Valuation","Investment & Portfolio Management","FinTech & Digital Banking","Derivatives & Risk Management","Financial Modeling with Excel/Python"],"career_paths":["Financial Analyst","Investment Consultant","Bank Officer","FinTech Specialist","Corporate Finance Officer"],"tags":["Finance","KKBS","FinTech","KKU"],"website_url":"https://kkbs.kku.ac.th"},
  {"id":"kku_kkbs_logistics_bba","title_th":"หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาการจัดการโลจิสติกส์และโซ่อุปทาน","title_en":"Bachelor of Business Administration Program in Logistics and Supply Chain Management","degree_level":"ปริญญาตรี","degree_name":"บธ.บ. (การจัดการโลจิสติกส์)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Business Administration and Accountancy (KKBS)","faculty_th":"คณะบริหารธุรกิจและการบัญชี","department":"Department of Logistics","department_th":"สาขาวิชาการจัดการโลจิสติกส์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นโลจิสติกส์ข้ามพรมแดน ไทย-ลาว-เวียดนาม-จีน คลังสินค้า และการขนส่งอีสาน","curriculum_highlights":["Cross-Border Logistics GMS (Thailand-Laos-Vietnam)","Warehouse & Inventory Management","Transportation & Freight Forwarding","Supply Chain Analytics & Blockchain","Internship in GMS Logistics"],"career_paths":["Logistics Manager","Supply Chain Analyst","Freight Forwarder","Warehouse Manager","Cross-Border Trade Officer"],"tags":["Logistics","Supply Chain","GMS","KKBS","KKU"],"website_url":"https://kkbs.kku.ac.th"},
  {"id":"kku_kkbs_ib_bba_inter","title_th":"หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาธุรกิจระหว่างประเทศ (หลักสูตรนานาชาติ)","title_en":"Bachelor of Business Administration Program in International Business (International Program)","degree_level":"ปริญญาตรี","degree_name":"บธ.บ. (ธุรกิจระหว่างประเทศ)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Business Administration and Accountancy (KKBS)","faculty_th":"คณะบริหารธุรกิจและการบัญชี","department":"Department of International Business","department_th":"สาขาวิชาธุรกิจระหว่างประเทศ","program_type":"นานาชาติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"38,000 บาท","tuition_total":"304,000 บาท","description":"หลักสูตรนานาชาติ เน้นธุรกิจ GMS การค้าระหว่างประเทศ และการลงทุนจีน-อาเซียน","curriculum_highlights":["International Business & GMS Trade","Cross-Cultural Management","International Marketing & Export","Global Supply Chain","Internship Abroad GMS/China"],"career_paths":["International Business Manager","Export Manager","GMS Trade Specialist","International Marketing Manager","Entrepreneur International"],"tags":["International Business","KKBS","International Program","GMS","KKU"],"website_url":"https://kkbs.kku.ac.th"},
  {"id":"kku_kkbs_macc","title_th":"หลักสูตรบัญชีมหาบัณฑิต","title_en":"Master of Accountancy Program","degree_level":"ปริญญาโท","degree_name":"บช.ม. (การบัญชี)","university":"Khon Kaen University","university_th":"มหาวิทยาลัยขอนแก่น","faculty":"Faculty of Business Administration and Accountancy (KKBS)","faculty_th":"คณะบริหารธุรกิจและการบัญชี","department":"Department of Accountancy","department_th":"สาขาวิชาการบัญชี","program_type":"ภาคพิเศษ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"เน้นบัญชีบริหารขั้นสูง การตรวจสอบดิจิทัล และบัญชีเพื่อความยั่งยืน (ESG)","curriculum_highlights":["Advanced Managerial Accounting","Digital Auditing & Data Analytics","Sustainability Accounting (ESG)","Forensic Accounting & Fraud","Thesis in Accountancy"],"career_paths":["Senior Auditor","Accounting Manager","Forensic Accountant","ESG Reporting Specialist","Accounting Consultant"],"tags":["Accountancy","Master Degree","KKBS","KKU","ESG"],"website_url":"https://kkbs.kku.ac.th"},
]

print(f"Prepared {len(NEW2)} courses wave2")
import pathlib, json
out = pathlib.Path("backend/data/courses_new/courses_kku_full_expansion2.json")
with open(out, 'w', encoding='utf-8') as f:
    json.dump(NEW2, f, ensure_ascii=False, indent=2)
print(f"Saved to {out}")

Base.metadata.create_all(bind=engine)
session = SessionLocal()
ins=upd=0
for c in NEW2:
    et=emb_text(c)
    try:
        vec=embedding_service.get_embedding(et)
        if vec and len(vec)!=768:
            vec=None
    except Exception as e:
        print(f"emb fail {c['id']}: {e}")
        vec=None
    ex=session.query(CourseDB).filter_by(id=c["id"]).first()
    if ex:
        for k,v in c.items():
            setattr(ex,k,v)
        ex.embedding_text=et
        if vec:
            ex.embedding=vec
        upd+=1
        print(f"Updated {c['id']}")
    else:
        db=CourseDB(id=c["id"], title_th=c["title_th"], title_en=c.get("title_en"), degree_level=c["degree_level"], degree_name=c.get("degree_name"), university=c["university"], university_th=c["university_th"], faculty=c["faculty"], faculty_th=c["faculty_th"], department=c.get("department"), department_th=c.get("department_th"), program_type=c.get("program_type","ภาคปกติ"), duration_years=c.get("duration_years"), total_credits=c.get("total_credits"), tuition_per_semester=c.get("tuition_per_semester"), tuition_total=c.get("tuition_total"), description=c.get("description"), curriculum_highlights=c.get("curriculum_highlights",[]), career_paths=c.get("career_paths",[]), tags=c.get("tags",[]), website_url=c.get("website_url"), embedding_text=et, embedding=vec if vec else None)
        session.add(db)
        ins+=1
        print(f"Inserted {c['id']} emb={'OK' if vec else 'NULL'}")
    if (ins+upd)%20==0:
        session.commit()
session.commit()
print(f"Done ins={ins} upd={upd}")
from sqlalchemy import text
with engine.connect() as conn:
    tot=conn.execute(text("SELECT COUNT(*) FROM courses WHERE university='Khon Kaen University'")).scalar()
    print(f"KKU total now: {tot}")
    tot_all=conn.execute(text("SELECT COUNT(*) FROM courses")).scalar()
    print(f"DB total all: {tot_all}")
session.close()
