# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')
import os, json, pathlib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.core.database import SessionLocal, engine, Base
from app.models.db_models import CourseDB
from app.core.embedding_service import embedding_service
def emb_text(c):
    hl=", ".join(c.get("curriculum_highlights",[]))
    cp=", ".join(c.get("career_paths",[]))
    tags=", ".join(c.get("tags",[]))
    return f"{c['title_th']} {c.get('title_en','')}. University: {c['university']} {c['university_th']}. Faculty: {c['faculty']} {c['faculty_th']}. Department: {c.get('department','')} {c.get('department_th','')}. Degree: {c['degree_level']} {c.get('degree_name','')}. Description: {c.get('description','')}. Highlights: {hl}. Careers: {cp}. Tags: {tags}."
MU_BACHELOR = [
  # Engineering - bachelor heavy
  {"id":"mu_eng_me_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเครื่องกล","title_en":"Bachelor of Engineering Program in Mechanical Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมเครื่องกล)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Mechanical Engineering","department_th":"ภาควิชาวิศวกรรมเครื่องกล","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"140 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"240,000 บาท","description":"เน้นการออกแบบเครื่องจักรกล หุ่นยนต์ และการผลิตอัจฉริยะร่วมกับอุตสาหกรรมการแพทย์","curriculum_highlights":["Mechanical Design & CAE","Robotics & Mechatronics","Thermal & Fluid Engineering","Smart Manufacturing","Capstone Mechanical Project"],"career_paths":["Mechanical Engineer","Robotics Engineer","Manufacturing Engineer","Design Engineer","R&D Engineer"],"tags":["Mechanical Engineering","MU","Robotics"],"website_url":"https://www.eg.mahidol.ac.th"},
  {"id":"mu_eng_env_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมสิ่งแวดล้อม","title_en":"Bachelor of Engineering Program in Environmental Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมสิ่งแวดล้อม)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Environmental Engineering","department_th":"ภาควิชาวิศวกรรมสิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"240,000 บาท","description":"เน้นการจัดการน้ำเสีย อากาศเสีย และ EIA สำหรับโรงพยาบาลและเมืองยั่งยืน","curriculum_highlights":["Water & Wastewater Treatment","Air Pollution & PM2.5 Control","EIA for Healthcare Facilities","Waste & Circular Economy","Environmental Lab"],"career_paths":["Environmental Engineer","EIA Consultant","Pollution Control Engineer","Waste Management Specialist","Sustainability Officer"],"tags":["Environmental Engineering","MU","EIA"],"website_url":"https://www.eg.mahidol.ac.th"},
  {"id":"mu_eng_indust_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมอุตสาหการ","title_en":"Bachelor of Engineering Program in Industrial Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมอุตสาหการ)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Industrial Engineering","department_th":"ภาควิชาวิศวกรรมอุตสาหการ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"240,000 บาท","description":"เน้น Lean Healthcare และโลจิสติกส์ระบบสุขภาพ","curriculum_highlights":["Lean Healthcare","Hospital Supply Chain","Quality Engineering Six Sigma","Smart Factory Health","Industrial Internship Hospital"],"career_paths":["Industrial Engineer","Hospital Logistics Manager","Quality Engineer","Healthcare Consultant","Operations Manager"],"tags":["Industrial Engineering","MU","Lean"],"website_url":"https://www.eg.mahidol.ac.th"},
  # Science - bachelor
  {"id":"mu_sci_bio_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาชีววิทยา","title_en":"Bachelor of Science Program in Biology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ชีววิทยา)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Biology","department_th":"ภาควิชาชีววิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นชีววิทยาโมเลกุล นิเวศวิทยา และความหลากหลายทางชีวภาพไทย","curriculum_highlights":["Molecular Biology & Genetics","Ecology & Biodiversity","Cell Biology Lab","Bioinformatics Basics","Field Biology"],"career_paths":["Biologist","Conservation Scientist","Lab Scientist","Research Assistant","Science Teacher"],"tags":["Biology","MU","Science"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_chem_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเคมี","title_en":"Bachelor of Science Program in Chemistry","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เคมี)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Chemistry","department_th":"ภาควิชาเคมี","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นเคมีวิเคราะห์ เคมีอินทรีย์ และวัสดุนาโนเพื่อยาและพลังงาน","curriculum_highlights":["Analytical & Organic Chemistry","Nanomaterials & Polymer","Chemical Instrumentation","Physical Chemistry Lab","Chemistry Research Project"],"career_paths":["Chemist","Materials Scientist","Analytical Chemist","R&D Chemist","QC Specialist"],"tags":["Chemistry","MU","Nanomaterials"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_physics_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาฟิสิกส์","title_en":"Bachelor of Science Program in Physics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ฟิสิกส์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Physics","department_th":"ภาควิชาฟิสิกส์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นฟิสิกส์วัสดุ พลังงาน และฟิสิกส์การแพทย์","curriculum_highlights":["Materials Physics & Quantum","Medical Physics Basics","Renewable Energy Physics","Computational Physics","Physics Lab"],"career_paths":["Physicist","Medical Physicist Assistant","Energy Technologist","Data Analyst","Teacher"],"tags":["Physics","MU","Medical Physics"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_math_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาคณิตศาสตร์","title_en":"Bachelor of Science Program in Mathematics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (คณิตศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Mathematics","department_th":"ภาควิชาคณิตศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นคณิตบริสุทธิ์ ประยุกต์ และคณิตศาสตร์การเงิน","curriculum_highlights":["Pure & Applied Mathematics","Financial Mathematics","Statistics & Data Science Math","Mathematical Modeling Health","Math Research"],"career_paths":["Mathematician","Actuary","Data Analyst","Financial Analyst","Teacher"],"tags":["Mathematics","MU","Actuarial"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_stat_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสถิติ","title_en":"Bachelor of Science Program in Statistics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (สถิติ)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Statistics","department_th":"ภาควิชาสถิติ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นสถิติชีวภาพ วิทยาการข้อมูล และการทดลองทางคลินิก","curriculum_highlights":["Biostatistics & Clinical Trials","Data Science & ML","Statistical Computing R","Experimental Design","Statistical Consulting"],"career_paths":["Statistician","Biostatistician","Data Scientist","Clinical Trials Analyst","Researcher"],"tags":["Statistics","Biostatistics","MU"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_micro_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาจุลชีววิทยา","title_en":"Bachelor of Science Program in Microbiology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (จุลชีววิทยา)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Microbiology","department_th":"ภาควิชาจุลชีววิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นจุลชีววิทยาทางการแพทย์ อุตสาหกรรม และสิ่งแวดล้อม","curriculum_highlights":["Medical Microbiology & Virology","Food & Industrial Microbiology","Immunology & Molecular Diagnostics","Environmental Microbiology","Microbiology Lab"],"career_paths":["Microbiologist","Clinical Microbiologist","Food Microbiologist","Research Scientist","QC Microbiologist"],"tags":["Microbiology","MU","Science"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_biotech_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีชีวภาพ","title_en":"Bachelor of Science Program in Biotechnology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เทคโนโลยีชีวภาพ)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Biotechnology","department_th":"ภาควิชาเทคโนโลยีชีวภาพ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"160,000 บาท","description":"เน้นพันธุวิศวกรรม ชีวกระบวนการ และชีวเภสัชภัณฑ์","curriculum_highlights":["Genetic Engineering & CRISPR","Bioprocess & Fermentation","Protein Engineering","Bioinformatics","Biotech Lab"],"career_paths":["Biotechnologist","Bioprocess Engineer","Research Scientist","Bioinformatics Analyst","QC Biotech"],"tags":["Biotechnology","MU","CRISPR"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_compsci_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์","title_en":"Bachelor of Science Program in Computer Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาการคอมพิวเตอร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Computer Science","department_th":"ภาควิชาวิทยาการคอมพิวเตอร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"160,000 บาท","description":"เน้นทฤษฎีการคำนวณ AI และวิทยาการข้อมูลเพื่อสุขภาพ","curriculum_highlights":["Theory of Computation & Algorithms","AI & Machine Learning","Data Science & Big Data","Software Engineering","CS Project Health"],"career_paths":["Software Engineer","AI Engineer","Data Scientist","System Analyst","Researcher"],"tags":["Computer Science","MU","AI"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_env_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์สิ่งแวดล้อม","title_en":"Bachelor of Science Program in Environmental Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาศาสตร์สิ่งแวดล้อม)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Environmental Science","department_th":"ภาควิชาวิทยาศาสตร์สิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นมลพิษ PM2.5 และการจัดการสิ่งแวดล้อมกรุงเทพ","curriculum_highlights":["Environmental Monitoring PM2.5","EIA & HIA","Waste & Circular Economy","GIS Environment","Fieldwork Bangkok"],"career_paths":["Environmental Scientist","EIA Consultant","Sustainability Officer","Pollution Control Specialist","GIS Analyst"],"tags":["Environmental Science","MU","EIA"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_food_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์และเทคโนโลยีการอาหาร","title_en":"Bachelor of Science Program in Food Science and Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาศาสตร์และเทคโนโลยีการอาหาร)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Food Science","department_th":"ภาควิชาเทคโนโลยีการอาหาร","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"160,000 บาท","description":"เน้นเคมีอาหาร จุลชีววิทยาอาหาร และวิศวกรรมอาหารเพื่ออุตสาหกรรมส่งออก","curriculum_highlights":["Food Chemistry & Microbiology","Food Processing & Engineering","Food Safety HACCP","Sensory & Product Development","Food Factory Internship"],"career_paths":["Food Scientist","Food Technologist","QA Manager","Product Developer","Food Safety Auditor"],"tags":["Food Science","MU","HACCP"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_ph_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสาธารณสุขศาสตร์","title_en":"Bachelor of Science Program in Public Health","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (สาธารณสุขศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Public Health","faculty_th":"คณะสาธารณสุขศาสตร์","department":"Department of Public Health","department_th":"ภาควิชาสาธารณสุขศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นส่งเสริมสุขภาพ ป้องกันโรค และบริหารระบบสุขภาพปฐมภูมิ","curriculum_highlights":["Epidemiology & Biostatistics","Environmental Health & Sanitation","Health Promotion & Education","Primary Health Care Management","Field Practicum Bangkok"],"career_paths":["Public Health Officer","Health Promotion Specialist","Environmental Health Officer","Community Health Manager","Health Educator"],"tags":["Public Health","MU","PH"],"website_url":"https://www.ph.mahidol.ac.th"},
  {"id":"mu_ph_eh_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาอนามัยสิ่งแวดล้อม","title_en":"Bachelor of Science Program in Environmental Health","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (อนามัยสิ่งแวดล้อม)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Public Health","faculty_th":"คณะสาธารณสุขศาสตร์","department":"Department of Environmental Health","department_th":"ภาควิชาอนามัยสิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้น HIA มลพิษอากาศและอาชีวอนามัย","curriculum_highlights":["Environmental Health Risk Assessment","PM2.5 & Air Quality","Water & Wastewater Management","Occupational Health","HIA & EIA"],"career_paths":["Environmental Health Scientist","EIA Officer","Occupational Health Officer","Pollution Control Specialist","Consultant"],"tags":["Environmental Health","MU","HIA"],"website_url":"https://www.ph.mahidol.ac.th"},
  {"id":"mu_liberal_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาอังกฤษ","title_en":"Bachelor of Arts Program in English","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาอังกฤษ)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Liberal Arts","faculty_th":"คณะศิลปศาสตร์","department":"Department of English","department_th":"ภาควิชาภาษาอังกฤษ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นภาษาอังกฤษเชิงวิชาการ ธุรกิจ และการแปลเพื่อตลาดสากล","curriculum_highlights":["Academic English & Writing","Business English & Presentation","Translation & Interpretation","English Literature","English for Health Communication"],"career_paths":["English Teacher","Translator","Content Writer","International Coordinator","Graduate Studies"],"tags":["English","MU","Liberal Arts"],"website_url":"https://www.la.mahidol.ac.th"},
  {"id":"mu_liberal_thai_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาไทย","title_en":"Bachelor of Arts Program in Thai Language","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาไทย)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Liberal Arts","faculty_th":"คณะศิลปศาสตร์","department":"Department of Thai","department_th":"ภาควิชาภาษาไทย","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นภาษาไทย วรรณกรรม และภาษาศาสตร์เพื่อสื่อสารสุขภาพและวัฒนธรรม","curriculum_highlights":["Thai Linguistics & Literature","Creative Writing & Editing","Thai for Health Communication","Folklore & Culture","Thai Research Project"],"career_paths":["Thai Teacher","Editor","Cultural Officer","Health Communicator","Researcher"],"tags":["Thai Language","MU","Liberal Arts"],"website_url":"https://www.la.mahidol.ac.th"},
  {"id":"mu_social_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาสังคมศาสตร์","title_en":"Bachelor of Arts Program in Social Sciences","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (สังคมศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Social Sciences and Humanities","faculty_th":"คณะสังคมศาสตร์และมนุษยศาสตร์","department":"Department of Social Sciences","department_th":"ภาควิชาสังคมศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นสังคมไทยร่วมสมัย ความเหลื่อมล้ำ และการพัฒนา","curriculum_highlights":["Contemporary Thai Society & Inequality","Development Studies & Policy","Qualitative Research & Fieldwork","Social Innovation Lab","Thesis Social Sciences"],"career_paths":["Social Researcher","Development Worker","Policy Analyst","NGO Officer","Academic"],"tags":["Social Sciences","MU","Development"],"website_url":"https://www.sh.mahidol.ac.th"},
  {"id":"mu_vet_dvm","title_th":"หลักสูตรสัตวแพทยศาสตรบัณฑิต","title_en":"Doctor of Veterinary Medicine Program","degree_level":"ปริญญาตรี","degree_name":"สพ.บ. (สัตวแพทยศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Veterinary Science","faculty_th":"คณะสัตวแพทยศาสตร์","department":"Faculty of Veterinary Science","department_th":"คณะสัตวแพทยศาสตร์","program_type":"ภาคปกติ","duration_years":"6 ปี","total_credits":"220 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"360,000 บาท","description":"ผลิตสัตวแพทย์ที่เชี่ยวชาญสัตว์เล็ก สัตว์เศรษฐกิจ และ One Health","curriculum_highlights":["Small & Large Animal Medicine","Veterinary Surgery & Diagnostics","One Health & Zoonoses","Vet Public Health & Food Safety","Clinical Rotation Vet Hospital"],"career_paths":["Veterinarian","Small Animal Clinician","Livestock Vet","Vet Public Health Officer","Researcher"],"tags":["Veterinary Medicine","MU","One Health"],"website_url":"https://www.vs.mahidol.ac.th"},
  {"id":"mu_env_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสิ่งแวดล้อมและทรัพยากรศาสตร์","title_en":"Bachelor of Science Program in Environment and Resource Studies","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (สิ่งแวดล้อมและทรัพยากรศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Environment and Resource Studies","faculty_th":"คณะสิ่งแวดล้อมและทรัพยากรศาสตร์","department":"Department of Environment","department_th":"ภาควิชาสิ่งแวดล้อม","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นการจัดการทรัพยากรธรรมชาติและสิ่งแวดล้อมยั่งยืน","curriculum_highlights":["Natural Resource Management","Environmental Assessment EIA","Climate Change & Sustainability","GIS for Environment","Field Environment Mahidol"],"career_paths":["Environmental Scientist","EIA Consultant","Sustainability Officer","Conservation Officer","GIS Analyst"],"tags":["Environment","MU","Sustainability"],"website_url":"https://www.en.mahidol.ac.th"},
]
print(f"Prepared {len(MU_BACHELOR)} MU bachelor")
out=pathlib.Path("backend/data/courses_new/courses_mu_bachelor_expansion.json")
with open(out,'w',encoding='utf-8') as f:
    json.dump(MU_BACHELOR,f,ensure_ascii=False,indent=2)
print(f"Saved to {out}")
Base.metadata.create_all(bind=engine)
session=SessionLocal()
ins=upd=0
for c in MU_BACHELOR:
    et=emb_text(c)
    try:
        vec=embedding_service.get_embedding(et)
        if vec and len(vec)!=768:
            vec=None
    except Exception as e:
        print(f"emb fail {c['id']}: {e}")
        vec=None
    ex=session.query(CourseDB).filter_by(id=c["id"]).first()
    if ex:
        for k,v in c.items():
            setattr(ex,k,v)
        ex.embedding_text=et
        if vec:
            ex.embedding=vec
        upd+=1
        print(f"Updated {c['id']}")
    else:
        db=CourseDB(id=c["id"], title_th=c["title_th"], title_en=c.get("title_en"), degree_level=c["degree_level"], degree_name=c.get("degree_name"), university=c["university"], university_th=c["university_th"], faculty=c["faculty"], faculty_th=c["faculty_th"], department=c.get("department"), department_th=c.get("department_th"), program_type=c.get("program_type","ภาคปกติ"), duration_years=c.get("duration_years"), total_credits=c.get("total_credits"), tuition_per_semester=c.get("tuition_per_semester"), tuition_total=c.get("tuition_total"), description=c.get("description"), curriculum_highlights=c.get("curriculum_highlights",[]), career_paths=c.get("career_paths",[]), tags=c.get("tags",[]), website_url=c.get("website_url"), embedding_text=et, embedding=vec if vec else None)
        session.add(db)
        ins+=1
        print(f"Inserted {c['id']} emb={'OK' if vec else 'NULL'}")
    if (ins+upd)%20==0:
        session.commit()
session.commit()
print(f"Done MU bachelor ins={ins} upd={upd}")
from sqlalchemy import text as t
with engine.connect() as conn:
    total=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Mahidol University'")).scalar()
    print(f"MU total now: {total}")
    tri=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Mahidol University' AND degree_level='ปริญญาตรี'")).scalar()
    tho=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Mahidol University' AND degree_level='ปริญญาโท'")).scalar()
    print(f"MU ตรี {tri} โท {tho} {'ตรี>โท' if tri>tho else 'โท>ตรี'}")
    tot_all=conn.execute(t("SELECT COUNT(*) FROM courses")).scalar()
    print(f"DB total: {tot_all}")
session.close()
