# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')
import os, json, pathlib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.core.database import SessionLocal, engine, Base
from app.models.db_models import CourseDB
from app.core.embedding_service import embedding_service
def emb_text(c):
    hl=", ".join(c.get("curriculum_highlights",[]))
    cp=", ".join(c.get("career_paths",[]))
    tags=", ".join(c.get("tags",[]))
    return f"{c['title_th']} {c.get('title_en','')}. University: {c['university']} {c['university_th']}. Faculty: {c['faculty']} {c['faculty_th']}. Department: {c.get('department','')} {c.get('department_th','')}. Degree: {c['degree_level']} {c.get('degree_name','')}. Description: {c.get('description','')}. Highlights: {hl}. Careers: {cp}. Tags: {tags}."
MU_B2 = [
  {"id":"mu_sci_applied_math_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาคณิตศาสตร์ประยุกต์","title_en":"Bachelor of Science Program in Applied Mathematics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (คณิตศาสตร์ประยุกต์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Mathematics","department_th":"ภาควิชาคณิตศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นคณิตศาสตร์ประยุกต์ คณิตศาสตร์การเงิน และการสร้างแบบจำลอง","curriculum_highlights":["Applied Mathematics & Modeling","Financial Mathematics & Risk","Computational Mathematics Python","Statistics & Data Science","Research Project Applied Math"],"career_paths":["Applied Mathematician","Financial Analyst","Data Analyst","Actuarial Assistant","Researcher"],"tags":["Applied Mathematics","MU","Science"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_actuarial_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาคณิตศาสตร์ประกันภัย","title_en":"Bachelor of Science Program in Actuarial Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (คณิตศาสตร์ประกันภัย)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Mathematics","department_th":"ภาควิชาคณิตศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"22,000 บาท","tuition_total":"176,000 บาท","description":"เน้นคณิตศาสตร์ประกันภัย สถิติ และการบริหารความเสี่ยงสำหรับธุรกิจประกัน","curriculum_highlights":["Actuarial Mathematics & Risk Theory","Insurance & Financial Risk","Statistics for Actuaries","Computing for Actuarial Science","Internship Insurance Company"],"career_paths":["Actuary","Risk Analyst","Insurance Specialist","Financial Consultant","Data Analyst"],"tags":["Actuarial Science","MU","Insurance"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_material_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวัสดุศาสตร์และนาโนเทคโนโลยี","title_en":"Bachelor of Science Program in Materials Science and Nano Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วัสดุศาสตร์และนาโนเทคโนโลยี)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Physics","department_th":"ภาควิชาฟิสิกส์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"160,000 บาท","description":"เน้นวัสดุนาโน พอลิเมอร์ และวัสดุพลังงานเพื่ออุตสาหกรรม EV","curriculum_highlights":["Nanomaterials & Synthesis","Polymer & Composite Materials","Materials Characterization","Energy Materials (Battery)","Materials Lab Project"],"career_paths":["Materials Scientist","Nanotechnologist","Battery Specialist","Polymer Engineer","R&D Specialist"],"tags":["Materials Science","Nano","MU","EV"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_sci_plant_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาพฤกษศาสตร์","title_en":"Bachelor of Science Program in Plant Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (พฤกษศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Science","faculty_th":"คณะวิทยาศาสตร์","department":"Department of Plant Science","department_th":"ภาควิชาพฤกษศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นพฤกษศาสตร์ โครงสร้างพืช และเทคโนโลยีชีวภาพพืช","curriculum_highlights":["Plant Physiology & Diversity","Plant Biotechnology & Tissue Culture","Plant Systematics & Ecology","Economic Botany & Herbal","Field Botany Project"],"career_paths":["Botanist","Plant Biotechnologist","Herbal Researcher","Conservation Scientist","Teacher"],"tags":["Plant Science","MU","Botany"],"website_url":"https://science.mahidol.ac.th"},
  {"id":"mu_ict_design_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาการออกแบบผลิตภัณฑ์ดิจิทัล","title_en":"Bachelor of Science Program in Digital Product Design","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (การออกแบบผลิตภัณฑ์ดิจิทัล)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Information and Communication Technology","faculty_th":"คณะเทคโนโลยีสารสนเทศและการสื่อสาร","department":"Digital Design","department_th":"สาขาวิชาการออกแบบผลิตภัณฑ์ดิจิทัล","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"32,000 บาท","tuition_total":"256,000 บาท","description":"เน้น UX/UI การออกแบบผลิตภัณฑ์สุขภาพดิจิทัล และ Design Thinking","curriculum_highlights":["UX/UI Design for Health Apps","Design Thinking & Prototyping","Digital Product Management","Frontend for Health","Capstone Digital Health Product"],"career_paths":["UX/UI Designer Health","Product Designer","Digital Designer","Product Manager","Startup Founder"],"tags":["Digital Product Design","UX/UI","MU","ICT"],"website_url":"https://www.ict.mahidol.ac.th"},
  {"id":"mu_arts_music_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาดนตรี","title_en":"Bachelor of Arts Program in Music","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ดนตรี)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Liberal Arts","faculty_th":"คณะศิลปศาสตร์","department":"Department of Music","department_th":"ภาควิชาดนตรี","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นดนตรีไทย ดนตรีสากล ซาวด์เอ็นจิเนียริ่ง และธุรกิจดนตรี","curriculum_highlights":["Thai & Western Music Performance","Sound Engineering & Recording","Music Business & Management","Composition & Arranging","Recital & Concert"],"career_paths":["Musician","Sound Engineer","Music Teacher","Composer","Music Event Manager"],"tags":["Music","MU","Liberal Arts"],"website_url":"https://www.la.mahidol.ac.th"},
  {"id":"mu_arts_history_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาประวัติศาสตร์","title_en":"Bachelor of Arts Program in History","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ประวัติศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Social Sciences and Humanities","faculty_th":"คณะสังคมศาสตร์และมนุษยศาสตร์","department":"Department of History","department_th":"ภาควิชาประวัติศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นประวัติศาสตร์ไทย เอเชียตะวันออกเฉียงใต้ และการวิจัยเชิงประวัติศาสตร์","curriculum_highlights":["Thai & Southeast Asian History","Oral History & Archive","Museum Studies & Heritage","Digital History","History Research Project"],"career_paths":["Historian","Museum Curator","Archivist","Cultural Officer","Teacher"],"tags":["History","MU","Humanities"],"website_url":"https://www.sh.mahidol.ac.th"},
  {"id":"mu_arts_psy_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาจิตวิทยา","title_en":"Bachelor of Arts Program in Psychology","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (จิตวิทยา)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Social Sciences and Humanities","faculty_th":"คณะสังคมศาสตร์และมนุษยศาสตร์","department":"Department of Psychology","department_th":"ภาควิชาจิตวิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"16,000 บาท","tuition_total":"128,000 บาท","description":"เน้นจิตวิทยาทั่วไป สังคม คลินิกเบื้องต้น และการวิจัย","curriculum_highlights":["General & Social Psychology","Developmental Psychology","Psychological Testing","Research Methods Psychology","Practicum Psychology"],"career_paths":["Psychologist Assistant","HR Officer","UX Researcher","Counseling Support","Research Assistant"],"tags":["Psychology","MU","Social Sciences"],"website_url":"https://www.sh.mahidol.ac.th"},
  {"id":"mu_tropmed_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเวชศาสตร์เขตร้อน","title_en":"Bachelor of Science Program in Tropical Medicine","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (เวชศาสตร์เขตร้อน)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Tropical Medicine","faculty_th":"คณะเวชศาสตร์เขตร้อน","department":"Department of Tropical Medicine","department_th":"ภาควิชาเวชศาสตร์เขตร้อน","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"20,000 บาท","tuition_total":"160,000 บาท","description":"คณะเวชศาสตร์เขตร้อนอันดับ 1 ไทย เน้นโรคติดเชื้อเขตร้อน ปรสิต และสุขภาพโลก","curriculum_highlights":["Tropical Infectious Diseases (Malaria/Dengue)","Parasitology & Vector Control","Global Health & Epidemiology","One Health Tropical","Field Tropical Medicine"],"career_paths":["Tropical Medicine Specialist","Global Health Officer","Vector Control Specialist","Research Scientist","Public Health Officer"],"tags":["Tropical Medicine","MU","Global Health"],"website_url":"https://www.tm.mahidol.ac.th"},
  {"id":"mu_tropmed_global_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสุขภาพโลก","title_en":"Bachelor of Science Program in Global Health","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (สุขภาพโลก)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Tropical Medicine","faculty_th":"คณะเวชศาสตร์เขตร้อน","department":"Global Health","department_th":"สาขาวิชาสุขภาพโลก","program_type":"นานาชาติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"45,000 บาท","tuition_total":"360,000 บาท","description":"หลักสูตรนานาชาติเน้นสุขภาพโลก ความเหลื่อมล้ำ และการพัฒนาที่ยั่งยืน","curriculum_highlights":["Global Health Governance & WHO","Health Equity & Sustainable Development","Epidemiology Global","Field Global Health ASEAN","Global Health Capstone"],"career_paths":["Global Health Officer","WHO/NGO Officer","Health Policy Analyst","Research Global Health","International Consultant"],"tags":["Global Health","MU","Tropical Medicine","International Program"],"website_url":"https://www.tm.mahidol.ac.th"},
  {"id":"mu_asset_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์การกีฬา","title_en":"Bachelor of Science Program in Sports Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาศาสตร์การกีฬา)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"College of Sports Science and Technology","faculty_th":"วิทยาลัยวิทยาศาสตร์และเทคโนโลยีการกีฬา","department":"Sports Science","department_th":"สาขาวิชาวิทยาศาสตร์การกีฬา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"เน้นวิทยาศาสตร์การกีฬา สรีรวิทยาการออกกำลังกาย และเทคโนโลยีการกีฬา","curriculum_highlights":["Exercise Physiology & Biomechanics","Sports Nutrition & Psychology","Sports Technology & Analytics","Coaching Science","Sports Internship"],"career_paths":["Sports Scientist","Exercise Physiologist","Sports Coach","Fitness Specialist","Sports Technology Specialist"],"tags":["Sports Science","MU","College of Sports"],"website_url":"https://www.ss.mahidol.ac.th"},
  {"id":"mu_religion_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาศาสนศึกษา","title_en":"Bachelor of Arts Program in Religious Studies","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ศาสนศึกษา)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Social Sciences and Humanities","faculty_th":"คณะสังคมศาสตร์และมนุษยศาสตร์","department":"Department of Religious Studies","department_th":"ภาควิชาศาสนศึกษา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นพุทธศาสนา ศาสนาเปรียบเทียบ และปรัชญาเพื่อสันติภาพ","curriculum_highlights":["Buddhist Philosophy & Ethics","Comparative Religion & Philosophy","Peace Studies & Conflict Resolution","Meditation & Mindfulness","Field Religious Studies"],"career_paths":["Religious Studies Teacher","Peace Worker","Cultural Officer","Writer","Researcher Religion"],"tags":["Religious Studies","Buddhism","MU"],"website_url":"https://www.sh.mahidol.ac.th"},
  {"id":"mu_langs_ba","title_th":"หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาศาสตร์","title_en":"Bachelor of Arts Program in Linguistics","degree_level":"ปริญญาตรี","degree_name":"ศศ.บ. (ภาษาศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Research Institute for Languages and Cultures of Asia","faculty_th":"สถาบันวิจัยภาษาและวัฒนธรรมเอเชีย","department":"Linguistics","department_th":"ภาควิชาภาษาศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"126 หน่วยกิต","tuition_per_semester":"15,000 บาท","tuition_total":"120,000 บาท","description":"เน้นภาษาศาสตร์ ภาษาไทย และภาษาอาเซียนเพื่อการสื่อสารและ AI ภาษา","curriculum_highlights":["General Linguistics & Thai Linguistics","ASEAN Languages & Cultures","Computational Linguistics & NLP Thai","Field Linguistics","Linguistics Research Project"],"career_paths":["Linguist","NLP Specialist Thai","Translator","Language Teacher","Researcher"],"tags":["Linguistics","NLP Thai","MU","RILCA"],"website_url":"https://www.lc.mahidol.ac.th"},
  {"id":"mu_nutrition_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาโภชนวิทยา","title_en":"Bachelor of Science Program in Nutrition","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (โภชนวิทยา)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Institute of Nutrition","faculty_th":"สถาบันโภชนาการ","department":"Nutrition","department_th":"สาขาวิชาโภชนวิทยา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"18,000 บาท","tuition_total":"144,000 บาท","description":"สถาบันโภชนาการอันดับ 1 ไทย เน้นโภชนาการคลินิก ชุมชน และอาหารปลอดภัย","curriculum_highlights":["Clinical Nutrition & Diet Therapy","Community Nutrition & Thai Food","Food Safety & Nutrition Surveillance","Nutrigenomics","Nutrition Practicum Siriraj"],"career_paths":["Nutritionist","Dietitian","Community Nutritionist","Food Safety Officer","Researcher Nutrition"],"tags":["Nutrition","MU","Institute of Nutrition"],"website_url":"https://www.inmu.mahidol.ac.th"},
  {"id":"mu_pt_bsc2","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชากายภาพบำบัด (หลักสูตรนานาชาติ)","title_en":"Bachelor of Science Program in Physical Therapy (International Program)","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (กายภาพบำบัด)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Physical Therapy","faculty_th":"คณะกายภาพบำบัด","department":"Physical Therapy","department_th":"ภาควิชากายภาพบำบัด","program_type":"นานาชาติ","duration_years":"4 ปี","total_credits":"140 หน่วยกิต","tuition_per_semester":"50,000 บาท","tuition_total":"400,000 บาท","description":"หลักสูตรนานาชาติ 100% English เน้นกายภาพบำบัดระบบประสาทและกล้ามเนื้อ","curriculum_highlights":["International Musculoskeletal & Neuro PT","Clinical Reasoning PT English","Rehabilitation Technology","Clinical Clerkship International","Research PT International"],"career_paths":["Physical Therapist International","Sports Physio","Rehab Specialist","Private Clinic International","Academic PT"],"tags":["Physical Therapy","International Program","MU"],"website_url":"https://www.pt.mahidol.ac.th"},
]
print(f"Prepared {len(MU_B2)}")
out=pathlib.Path("backend/data/courses_new/courses_mu_bachelor_expansion2.json")
with open(out,'w',encoding='utf-8') as f:
    json.dump(MU_B2,f,ensure_ascii=False,indent=2)
print(f"Saved to {out}")
Base.metadata.create_all(bind=engine)
session=SessionLocal()
ins=upd=0
for c in MU_B2:
    et=emb_text(c)
    try:
        vec=embedding_service.get_embedding(et)
        if vec and len(vec)!=768:
            vec=None
    except Exception as e:
        print(f"emb fail {c['id']}: {e}")
        vec=None
    ex=session.query(CourseDB).filter_by(id=c["id"]).first()
    if ex:
        for k,v in c.items():
            setattr(ex,k,v)
        ex.embedding_text=et
        if vec:
            ex.embedding=vec
        upd+=1
        print(f"Updated {c['id']}")
    else:
        db=CourseDB(id=c["id"], title_th=c["title_th"], title_en=c.get("title_en"), degree_level=c["degree_level"], degree_name=c.get("degree_name"), university=c["university"], university_th=c["university_th"], faculty=c["faculty"], faculty_th=c["faculty_th"], department=c.get("department"), department_th=c.get("department_th"), program_type=c.get("program_type","ภาคปกติ"), duration_years=c.get("duration_years"), total_credits=c.get("total_credits"), tuition_per_semester=c.get("tuition_per_semester"), tuition_total=c.get("tuition_total"), description=c.get("description"), curriculum_highlights=c.get("curriculum_highlights",[]), career_paths=c.get("career_paths",[]), tags=c.get("tags",[]), website_url=c.get("website_url"), embedding_text=et, embedding=vec if vec else None)
        session.add(db)
        ins+=1
        print(f"Inserted {c['id']} emb={'OK' if vec else 'NULL'}")
    if (ins+upd)%20==0:
        session.commit()
session.commit()
print(f"Done MU B2 ins={ins} upd={upd}")
from sqlalchemy import text as t
with engine.connect() as conn:
    total=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Mahidol University'")).scalar()
    tri=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Mahidol University' AND degree_level='ปริญญาตรี'")).scalar()
    tho=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Mahidol University' AND degree_level='ปริญญาโท'")).scalar()
    print(f"MU total {total} ตรี {tri} โท {tho} {'ตรี>โท' if tri>tho else 'โท>ตรี'} need {tho-tri+1} more ตรี to flip")
    tot_all=conn.execute(t("SELECT COUNT(*) FROM courses")).scalar()
    print(f"DB total: {tot_all}")
session.close()
