# -*- coding: utf-8 -*-
import sys
sys.stdout.reconfigure(encoding='utf-8')
import os, json, pathlib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.core.database import SessionLocal, engine, Base
from app.models.db_models import CourseDB
from app.core.embedding_service import embedding_service
def emb_text(c):
    hl=", ".join(c.get("curriculum_highlights",[]))
    cp=", ".join(c.get("career_paths",[]))
    tags=", ".join(c.get("tags",[]))
    return f"{c['title_th']} {c.get('title_en','')}. University: {c['university']} {c['university_th']}. Faculty: {c['faculty']} {c['faculty_th']}. Department: {c.get('department','')} {c.get('department_th','')}. Degree: {c['degree_level']} {c.get('degree_name','')}. Description: {c.get('description','')}. Highlights: {hl}. Careers: {cp}. Tags: {tags}."
MU_COURSES = [
  # === FACULTY OF ENGINEERING expansion (8) - MU only 13 currently ===
  {"id":"mu_eng_bme_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมชีวการแพทย์","title_en":"Bachelor of Engineering Program in Biomedical Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมชีวการแพทย์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Biomedical Engineering","department_th":"ภาควิชาวิศวกรรมชีวการแพทย์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"140 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"280,000 บาท","description":"บูรณาการวิศวกรรมและการแพทย์ อุปกรณ์การแพทย์ ภาพทางการแพทย์ และชีววัสดุ ร่วมกับ รพ.ศิริราชและรามาธิบดี","curriculum_highlights":["Medical Device Design & Regulation","Biomedical Imaging (CT/MRI/US)","Biomaterials & Tissue Engineering","Rehabilitation Engineering & Robotics","Clinical Internship Siriraj/Ramathibodi"],"career_paths":["Biomedical Engineer","Medical Device Designer","Clinical Engineer","Rehab Technology Specialist","MedTech Entrepreneur"],"tags":["Biomedical Engineering","MU","Medical Device"],"website_url":"https://www.eg.mahidol.ac.th"},
  {"id":"mu_eng_che_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเคมี","title_en":"Bachelor of Engineering Program in Chemical Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมเคมี)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Chemical Engineering","department_th":"ภาควิชาวิศวกรรมเคมี","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"142 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"240,000 บาท","description":"เน้นกระบวนการเคมีอุตสาหกรรม เภสัชเคมี พลังงานชีวภาพ และวิศวกรรมยั่งยืนเพื่ออุตสาหกรรมยาและอาหาร","curriculum_highlights":["Chemical Process Design & Simulation","Pharmaceutical Chemical Technology","Biochemical Engineering & Bioreactor","Sustainable Process Engineering","Plant Design & Safety"],"career_paths":["Chemical Engineer","Pharma Process Engineer","Bioprocess Engineer","Environmental Process Specialist","Plant Manager"],"tags":["Chemical Engineering","MU","Bioprocess"],"website_url":"https://www.eg.mahidol.ac.th"},
  {"id":"mu_eng_ce_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมโยธา","title_en":"Bachelor of Engineering Program in Civil Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมโยธา)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Civil Engineering","department_th":"ภาควิชาวิศวกรรมโยธา","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"142 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"240,000 บาท","description":"เน้นโครงสร้าง โรงพยาบาลและอาคารสุขภาพ การจัดการน้ำ และการก่อสร้างยั่งยืนสำหรับระบบสุขภาพ","curriculum_highlights":["Hospital & Healthcare Facility Design","Structural & Geotechnical Engineering","Water Resources & Green Building","Construction Management & BIM for Health","Civil Lab & Site Practice"],"career_paths":["Civil Engineer","Healthcare Facility Designer","Structural Engineer","Construction Project Manager","Water Engineer"],"tags":["Civil Engineering","Healthcare Facility","MU"],"website_url":"https://www.eg.mahidol.ac.th"},
  {"id":"mu_eng_ie_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมอุตสาหการ","title_en":"Bachelor of Engineering Program in Industrial Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมอุตสาหการ)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Industrial Engineering","department_th":"ภาควิชาวิศวกรรมอุตสาหการ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"240,000 บาท","description":"เน้น Lean Healthcare, โลจิสติกส์โรงพยาบาล และ Industry 4.0 สำหรับระบบสุขภาพและอุตสาหกรรมการแพทย์","curriculum_highlights":["Lean Healthcare & Hospital Logistics","Healthcare Supply Chain","Quality Engineering (Six Sigma) for Health","Smart Manufacturing & Automation","Industrial Hospital Internship"],"career_paths":["Industrial Engineer Healthcare","Hospital Logistics Manager","Quality Engineer","Healthcare Consultant","Factory Manager Med Industry"],"tags":["Industrial Engineering","Lean Healthcare","MU"],"website_url":"https://www.eg.mahidol.ac.th"},
  {"id":"mu_eng_cpe_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์","title_en":"Bachelor of Engineering Program in Computer Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมคอมพิวเตอร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Computer Engineering","department_th":"ภาควิชาวิศวกรรมคอมพิวเตอร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"240,000 บาท","description":"เน้นระบบฝังตัวทางการแพทย์ AI ทางการแพทย์ และความมั่นคงปลอดภัยไซเบอร์สุขภาพ","curriculum_highlights":["Embedded Systems for Medical Devices","AI in Medicine & Health Informatics","Cybersecurity for Healthcare","Cloud & IoT for Health","Computer Engineering Project Siriraj"],"career_paths":["Computer Engineer Medical Systems","Health AI Engineer","Cybersecurity Specialist Health","IoT Health Developer","Software Engineer"],"tags":["Computer Engineering","Health AI","MU","Engineering"],"website_url":"https://www.eg.mahidol.ac.th"},
  {"id":"mu_eng_ee_beng","title_th":"หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมไฟฟ้า","title_en":"Bachelor of Engineering Program in Electrical Engineering","degree_level":"ปริญญาตรี","degree_name":"วศ.บ. (วิศวกรรมไฟฟ้า)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Department of Electrical Engineering","department_th":"ภาควิชาวิศวกรรมไฟฟ้า","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"240,000 บาท","description":"เน้นระบบไฟฟ้ากำลังโรงพยาบาล เครื่องมือแพทย์ไฟฟ้า และพลังงานสะอาดสำหรับสุขภาพ","curriculum_highlights":["Hospital Power Systems & Microgrid","Medical Electrical Equipment","Renewable Energy for Healthcare","Control Systems & Automation","Electrical Lab & Hospital Practice"],"career_paths":["Electrical Engineer Hospital","Medical Equipment Engineer","Energy Engineer Healthcare","Control Systems Engineer","Power Systems Specialist"],"tags":["Electrical Engineering","MU","Hospital Power"],"website_url":"https://www.eg.mahidol.ac.th"},
  {"id":"mu_eng_ai_meng","title_th":"หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมปัญญาประดิษฐ์ทางการแพทย์","title_en":"Master of Engineering Program in Medical Artificial Intelligence Engineering","degree_level":"ปริญญาโท","degree_name":"วศ.ม. (วิศวกรรมปัญญาประดิษฐ์ทางการแพทย์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Medical AI Engineering","department_th":"สาขาวิชาวิศวกรรมปัญญาประดิษฐ์ทางการแพทย์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"160,000 บาท","description":"วิจัย AI วินิจฉัยภาพทางการแพทย์ LLM ทางการแพทย์ และหุ่นยนต์ผ่าตัดร่วมกับศิริราช","curriculum_highlights":["Medical Imaging AI (Radiology)","LLM for Clinical Decision Support","Surgical Robotics & Navigation","Thesis Medical AI","Clinical AI Lab Siriraj"],"career_paths":["Medical AI Engineer","Clinical AI Researcher","Health AI Product Manager","Academic Medical AI","Startup Founder MedTech"],"tags":["Medical AI","Master Degree","MU","Engineering"],"website_url":"https://www.eg.mahidol.ac.th"},
  {"id":"mu_eng_robotics_meng","title_th":"หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมหุ่นยนต์และระบบอัตโนมัติทางการแพทย์","title_en":"Master of Engineering Program in Medical Robotics and Automation","degree_level":"ปริญญาโท","degree_name":"วศ.ม. (วิศวกรรมหุ่นยนต์ทางการแพทย์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Engineering","faculty_th":"คณะวิศวกรรมศาสตร์","department":"Medical Robotics","department_th":"สาขาวิชาหุ่นยนต์ทางการแพทย์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"160,000 บาท","description":"วิจัยหุ่นยนต์ผ่าตัด หุ่นยนต์ฟื้นฟู และระบบอัตโนมัติโรงพยาบาล","curriculum_highlights":["Surgical Robotics & Haptics","Rehabilitation Robotics Exoskeleton","Hospital Automation & Logistics Robots","Thesis Medical Robotics","Siriraj Robotics Lab"],"career_paths":["Medical Robotics Engineer","Rehab Robotics Specialist","Hospital Automation Engineer","Researcher","MedTech Entrepreneur"],"tags":["Medical Robotics","MU","Master Degree"],"website_url":"https://www.eg.mahidol.ac.th"},
  # === FACULTY OF ICT expansion (7) - currently only 3 ===
  {"id":"mu_ict_cs_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์","title_en":"Bachelor of Science Program in Computer Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาการคอมพิวเตอร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Information and Communication Technology","faculty_th":"คณะเทคโนโลยีสารสนเทศและการสื่อสาร","department":"Department of Computer Science","department_th":"ภาควิชาวิทยาการคอมพิวเตอร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"280,000 บาท","description":"เน้นทฤษฎีการคำนวณ AI วิทยาการข้อมูล และความมั่นคงปลอดภัยไซเบอร์เพื่ออุตสาหกรรมดิจิทัลสุขภาพ","curriculum_highlights":["Algorithms & Theory of Computation","AI & Machine Learning for Health","Cybersecurity & Privacy","Data Science & Big Data","Software Engineering Project"],"career_paths":["Software Engineer","AI Engineer Health","Cybersecurity Analyst","Data Scientist","System Architect"],"tags":["Computer Science","MU","ICT","AI"],"website_url":"https://www.ict.mahidol.ac.th"},
  {"id":"mu_ict_se_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิศวกรรมซอฟต์แวร์","title_en":"Bachelor of Science Program in Software Engineering","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิศวกรรมซอฟต์แวร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Information and Communication Technology","faculty_th":"คณะเทคโนโลยีสารสนเทศและการสื่อสาร","department":"Department of Software Engineering","department_th":"ภาควิชา​วิศวกรรมซอฟต์แวร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"280,000 บาท","description":"เน้นวิศวกรรมซอฟต์แวร์ระดับองค์กร Agile/DevOps สำหรับระบบโรงพยาบาลและ HealthTech","curriculum_highlights":["Agile & DevOps for Health Systems","Microservices & Cloud-Native Health","Health Informatics Standards (HL7/FHIR)","Software Testing & QA Health","Capstone Health Software Project"],"career_paths":["Software Engineer Health","DevOps Engineer","Health Informatics Specialist","QA Engineer","Product Manager HealthTech"],"tags":["Software Engineering","MU","ICT","HealthTech"],"website_url":"https://www.ict.mahidol.ac.th"},
  {"id":"mu_ict_ds_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการข้อมูล","title_en":"Bachelor of Science Program in Data Science","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (วิทยาการข้อมูล)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Information and Communication Technology","faculty_th":"คณะเทคโนโลยีสารสนเทศและการสื่อสาร","department":"Department of Data Science","department_th":"ภาควิชาวิทยาการข้อมูล","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"38,000 บาท","tuition_total":"304,000 บาท","description":"เน้นวิศวกรรมข้อมูล AI และการวิเคราะห์ข้อมูลสุขภาพขนาดใหญ่ (Big Health Data)","curriculum_highlights":["Data Engineering & Health Data Warehouse","Machine Learning & Health Analytics","Big Data (Spark) for Genomics","Data Visualization & BI Health","Data Science Capstone Health"],"career_paths":["Data Engineer Health","Data Scientist","Health Data Analyst","BI Developer","ML Engineer"],"tags":["Data Science","MU","ICT","Health Data"],"website_url":"https://www.ict.mahidol.ac.th"},
  {"id":"mu_ict_cyber_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาความมั่นคงปลอดภัยไซเบอร์","title_en":"Bachelor of Science Program in Cyber Security","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ความมั่นคงปลอดภัยไซเบอร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Information and Communication Technology","faculty_th":"คณะเทคโนโลยีสารสนเทศและการสื่อสาร","department":"Department of Cyber Security","department_th":"ภาควิชาความมั่นคงปลอดภัยไซเบอร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"38,000 บาท","tuition_total":"304,000 บาท","description":"เน้นการป้องกันภัยไซเบอร์โรงพยาบาล PDPA สุขภาพ และ Digital Forensics ทางการแพทย์","curriculum_highlights":["Healthcare Cybersecurity & PDPA","Ethical Hacking & PenTest Health","Digital Forensics Medical Systems","SOC for Hospital","Cyber Law Health"],"career_paths":["Cybersecurity Analyst Health","Pen Tester Health","SOC Analyst Hospital","DPO Healthcare","Digital Forensics Specialist"],"tags":["Cyber Security","MU","ICT","PDPA"],"website_url":"https://www.ict.mahidol.ac.th"},
  {"id":"mu_ict_ai_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาปัญญาประดิษฐ์","title_en":"Bachelor of Science Program in Artificial Intelligence","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ปัญญาประดิษฐ์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Information and Communication Technology","faculty_th":"คณะเทคโนโลยีสารสนเทศและการสื่อสาร","department":"Department of Artificial Intelligence","department_th":"ภาควิชาปัญญาประดิษฐ์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"130 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"320,000 บาท","description":"เน้น Deep Learning NLP และ Computer Vision เพื่อการแพทย์แม่นยำและสาธารณสุข","curriculum_highlights":["Deep Learning & Medical Imaging","NLP for Thai Clinical Text","Computer Vision Diagnosis","Generative AI for Health","AI Capstone Siriraj"],"career_paths":["AI Engineer Health","Medical Imaging AI Specialist","NLP Health Engineer","Computer Vision Researcher","AI Entrepreneur"],"tags":["Artificial Intelligence","MU","ICT","Medical AI"],"website_url":"https://www.ict.mahidol.ac.th"},
  {"id":"mu_ict_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเทคโนโลยีสารสนเทศ","title_en":"Master of Science Program in Information Technology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (เทคโนโลยีสารสนเทศ)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Information and Communication Technology","faculty_th":"คณะเทคโนโลยีสารสนเทศและการสื่อสาร","department":"Graduate Studies ICT","department_th":"บัณฑิตศึกษา คณะ ICT","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"160,000 บาท","description":"วิจัยเทคโนโลยีสารสนเทศขั้นสูงสำหรับสุขภาพดิจิทัล","curriculum_highlights":["Advanced Health Informatics","AI & Big Data for ICT","Thesis ICT","Health Data Privacy & Blockchain","Cloud for Health Systems"],"career_paths":["IT Researcher Health","Health Informatics Leader","Academic ICT","Consultant","PhD Candidate"],"tags":["Master ICT","MU","Health Informatics"],"website_url":"https://www.ict.mahidol.ac.th"},
  {"id":"mu_ict_gis_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาภูมิสารสนเทศศาสตร์สุขภาพ","title_en":"Bachelor of Science Program in Health Geoinformatics","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (ภูมิสารสนเทศศาสตร์สุขภาพ)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Information and Communication Technology","faculty_th":"คณะเทคโนโลยีสารสนเทศและการสื่อสาร","department":"Health Geoinformatics","department_th":"สาขาวิชาภูมิสารสนเทศศาสตร์สุขภาพ","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"128 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"280,000 บาท","description":"เน้น GIS ระบาดวิทยาเชิงพื้นที่ และการจัดการทรัพยากรสุขภาพ","curriculum_highlights":["GIS for Epidemiology","Spatial Health Data Analysis","Remote Sensing Health","Health Resource Mapping","GIS Health Project"],"career_paths":["Health GIS Specialist","Epidemiologist GIS","Public Health GIS Analyst","Environmental Health GIS","Researcher"],"tags":["Geoinformatics","Health GIS","MU"],"website_url":"https://www.ict.mahidol.ac.th"},
  # === FACULTY OF NURSING expansion (5) - currently only 1 ===
  {"id":"mu_nurs_bns","title_th":"หลักสูตรพยาบาลศาสตรบัณฑิต","title_en":"Bachelor of Nursing Science Program","degree_level":"ปริญญาตรี","degree_name":"พย.บ. (พยาบาลศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Faculty of Nursing","department_th":"คณะพยาบาลศาสตร์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"142 หน่วยกิต","tuition_per_semester":"25,000 บาท","tuition_total":"200,000 บาท","description":"ผลิตพยาบาลวิชาชีพตามมาตรฐานสภาการพยาบาล เน้นการพยาบาลผู้ใหญ่ เด็ก ผู้สูงอายุและชุมชนร่วมกับ รพ.ศิริราช/รามาธิบดี","curriculum_highlights":["Adult & Geriatric Nursing Siriraj","Pediatric & Maternity Nursing","Community Health Nursing Bangkok","Nursing Ethics & Leadership","Clinical Practicum Siriraj/Rama"],"career_paths":["Registered Nurse","Community Health Nurse","Pediatric Nurse","Geriatric Nurse","Nurse Educator Trainee"],"tags":["Nursing","MU","Siriraj","Nurse"],"website_url":"https://www.ns.mahidol.ac.th"},
  {"id":"mu_nurs_gero_msc","title_th":"หลักสูตรพยาบาลศาสตรมหาบัณฑิต สาขาวิชาการพยาบาลผู้สูงอายุ","title_en":"Master of Nursing Science Program in Gerontological Nursing","degree_level":"ปริญญาโท","degree_name":"พย.ม. (การพยาบาลผู้สูงอายุ)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Gerontological Nursing","department_th":"สาขาวิชาการพยาบาลผู้สูงอายุ","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการพยาบาลผู้สูงอายุแบบองค์รวม การจัดการโรคเรื้อรัง และการดูแลระยะยาวในสังคมสูงวัยกรุงเทพ","curriculum_highlights":["Gerontology & Aging Theories","Chronic Disease & Palliative Care Bangkok","Long-Term Care Management","Thesis Gerontological Nursing","Community Gerontology Research"],"career_paths":["Gerontological Nurse Specialist","Long-Term Care Manager","Community Nurse Leader","Nursing Educator","Researcher Aging"],"tags":["Gerontological Nursing","MU","Master Degree"],"website_url":"https://www.ns.mahidol.ac.th"},
  {"id":"mu_nurs_pediatric_msc","title_th":"หลักสูตรพยาบาลศาสตรมหาบัณฑิต สาขาวิชาการพยาบาลเด็ก","title_en":"Master of Nursing Science Program in Pediatric Nursing","degree_level":"ปริญญาโท","degree_name":"พย.ม. (การพยาบาลเด็ก)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Pediatric Nursing","department_th":"สาขาวิชาการพยาบาลเด็ก","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการพยาบาลเด็กวิกฤต ทารกแรกเกิด และครอบครัว","curriculum_highlights":["Pediatric Critical Care Nursing","Neonatal Nursing & Family","Child Development & Health Promotion","Thesis Pediatric Nursing","Clinical Pediatric Siriraj"],"career_paths":["Pediatric Nurse Specialist","Neonatal Nurse","Child Health Nurse","Nursing Instructor","Researcher"],"tags":["Pediatric Nursing","MU","Master Degree"],"website_url":"https://www.ns.mahidol.ac.th"},
  {"id":"mu_nurs_midwife_msc","title_th":"หลักสูตรพยาบาลศาสตรมหาบัณฑิต สาขาวิชาการผดุงครรภ์","title_en":"Master of Nursing Science Program in Midwifery","degree_level":"ปริญญาโท","degree_name":"พย.ม. (การผดุงครรภ์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Midwifery","department_th":"สาขาวิชาการผดุงครรภ์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"เน้นการผดุงครรภ์ขั้นสูง การดูแลมารดาและทารก และการส่งเสริมสุขภาพสตรี","curriculum_highlights":["Advanced Midwifery & Labor Care","Maternal & Newborn Health","Reproductive Health Promotion","Thesis Midwifery","Clinical Midwifery Siriraj"],"career_paths":["Midwife Specialist","Maternal Health Nurse","Women Health Consultant","Nursing Educator","Researcher Midwifery"],"tags":["Midwifery","MU","Nursing"],"website_url":"https://www.ns.mahidol.ac.th"},
  {"id":"mu_nurs_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาพยาบาลศาสตร์","title_en":"Doctor of Philosophy Program in Nursing Science","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (พยาบาลศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Nursing","faculty_th":"คณะพยาบาลศาสตร์","department":"Doctoral Program Nursing","department_th":"สาขาวิชาพยาบาลศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"240,000 บาท","description":"ผลิตนักวิจัยพยาบาลระดับแนวหน้า เน้นระบบสุขภาพไทยและนวัตกรรมการพยาบาล","curriculum_highlights":["Advanced Nursing Theory & Health Systems","Nursing Innovation Research","Leadership & Health Policy Nursing","Dissertation Nursing Science","International Publication"],"career_paths":["Nursing Professor","Nursing Research Director","Hospital Nursing Director","Health Policy Maker","International Consultant"],"tags":["Ph.D. Nursing","MU","Nursing Science"],"website_url":"https://www.ns.mahidol.ac.th"},
  # === FACULTY OF MEDICAL TECHNOLOGY expansion (4) - currently 2 ===
  {"id":"mu_mt_pt_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชากายภาพบำบัด","title_en":"Bachelor of Science Program in Physical Therapy","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (กายภาพบำบัด)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Medical Technology","faculty_th":"คณะเทคนิคการแพทย์","department":"Department of Physical Therapy","department_th":"ภาควิชากายภาพบำบัด","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"140 หน่วยกิต","tuition_per_semester":"25,000 บาท","tuition_total":"200,000 บาท","description":"เน้นกายภาพบำบัดระบบกระดูกกล้ามเนื้อ ประสาท และการฟื้นฟูผู้ป่วยหลอดเลือดสมองด้วยเทคโนโลยีหุ่นยนต์","curriculum_highlights":["Musculoskeletal & Neuro PT","Cardiopulmonary PT & Exercise","Rehabilitation Robotics & Technology","Community PT Bangkok","Clinical PT Siriraj/Rama"],"career_paths":["Physical Therapist","Rehab Specialist","Sports Physio","Community PT","Private Clinic Owner"],"tags":["Physical Therapy","MU","Rehabilitation"],"website_url":"https://www.mt.mahidol.ac.th"},
  {"id":"mu_mt_ot_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชากิจกรรมบำบัด","title_en":"Bachelor of Science Program in Occupational Therapy","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (กิจกรรมบำบัด)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Medical Technology","faculty_th":"คณะเทคนิคการแพทย์","department":"Department of Occupational Therapy","department_th":"ภาควิชากิจกรรมบำบัด","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"138 หน่วยกิต","tuition_per_semester":"25,000 บาท","tuition_total":"200,000 บาท","description":"เน้นการฟื้นฟูผู้ป่วยให้กลับมาใช้ชีวิตประจำวันได้ด้วยกิจกรรมบำบัดทั้งเด็ก ผู้สูงอายุ และผู้พิการ","curriculum_highlights":["Pediatric & Geriatric OT","Neurorehabilitation OT","Community OT Bangkok","Assistive Technology & Ergonomics","OT Clinical Fieldwork"],"career_paths":["Occupational Therapist","Pediatric OT","Rehab Coordinator","Assistive Tech Specialist","Community OT"],"tags":["Occupational Therapy","MU","Rehab"],"website_url":"https://www.mt.mahidol.ac.th"},
  {"id":"mu_mt_rad_bsc","title_th":"หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชารังสีเทคนิค","title_en":"Bachelor of Science Program in Radiological Technology","degree_level":"ปริญญาตรี","degree_name":"วท.บ. (รังสีเทคนิค)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Medical Technology","faculty_th":"คณะเทคนิคการแพทย์","department":"Department of Radiological Technology","department_th":"ภาควิชารังสีเทคนิค","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"140 หน่วยกิต","tuition_per_semester":"28,000 บาท","tuition_total":"224,000 บาท","description":"ผลิตนักรังสีเทคนิคเชี่ยวชาญ CT MRI และรังสีรักษาร่วมกับ รพ.รามาธิบดี","curriculum_highlights":["Diagnostic Radiography CT/MRI","Ultrasound & Nuclear Medicine","Radiation Therapy Planning","Radiation Safety & Dosimetry","Clinical Radiology Rama"],"career_paths":["Radiological Technologist","CT/MRI Specialist","Radiation Therapist","Application Specialist","Imaging Manager"],"tags":["Radiological Technology","MU","CT/MRI"],"website_url":"https://www.mt.mahidol.ac.th"},
  {"id":"mu_mt_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเทคนิคการแพทย์","title_en":"Master of Science Program in Medical Technology","degree_level":"ปริญญาโท","degree_name":"วท.ม. (เทคนิคการแพทย์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Medical Technology","faculty_th":"คณะเทคนิคการแพทย์","department":"Graduate Studies MT","department_th":"บัณฑิตศึกษา คณะเทคนิคการแพทย์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"120,000 บาท","description":"วิจัยการตรวจวินิจฉัยโมเลกุลและนวัตกรรมห้องปฏิบัติการแม่นยำ","curriculum_highlights":["Molecular Diagnostics & PCR","Clinical Immunology Research","Lab Automation & AI","Thesis Medical Technology","Quality Lab Management"],"career_paths":["Medical Technologist Researcher","Lab Manager","Molecular Diagnostics Specialist","Academic","Biotech Consultant"],"tags":["Medical Technology","MU","Master Degree"],"website_url":"https://www.mt.mahidol.ac.th"},
  # === FACULTY OF PHARMACY expansion (5) - currently 7, add more ===
  {"id":"mu_pharm_care_pharmd","title_th":"หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาการบริบาลทางเภสัชกรรม","title_en":"Doctor of Pharmacy Program in Pharmaceutical Care","degree_level":"ปริญญาตรี","degree_name":"ภ.บ. (การบริบาลทางเภสัชกรรม)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Pharmacy","faculty_th":"คณะเภสัชศาสตร์","department":"Department of Pharmacy","department_th":"ภาควิชาเภสัชกรรม","program_type":"ภาคปกติ","duration_years":"6 ปี","total_credits":"220 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"360,000 บาท","description":"เน้นการบริบาลทางเภสัชกรรมคลินิก ร่วมกับ รพ.ศิริราช/รามาธิบดี และการใช้ยาอย่างสมเหตุผล","curriculum_highlights":["Clinical Pharmacy & Pharmacotherapy","Pharmacogenomics & Precision Dosing","Hospital Pharmacy Rotation Siriraj/Rama","Community Pharmacy & Pharmacovigilance","Pharmacy Research Project"],"career_paths":["Clinical Pharmacist","Hospital Pharmacist","Community Pharmacist","Pharmacovigilance Officer","Pharma R&D"],"tags":["Pharmacy","MU","Pharmaceutical Care"],"website_url":"https://www.pharmacy.mahidol.ac.th"},
  {"id":"mu_pharm_indust_pharmd","title_th":"หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาเภสัชกรรมอุตสาหการ","title_en":"Doctor of Pharmacy Program in Industrial Pharmacy","degree_level":"ปริญญาตรี","degree_name":"ภ.บ. (เภสัชกรรมอุตสาหการ)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Pharmacy","faculty_th":"คณะเภสัชศาสตร์","department":"Industrial Pharmacy","department_th":"สาขาวิชาเภสัชกรรมอุตสาหการ","program_type":"ภาคปกติ","duration_years":"6 ปี","total_credits":"220 หน่วยกิต","tuition_per_semester":"30,000 บาท","tuition_total":"360,000 บาท","description":"เน้นการผลิตยา การควบคุมคุณภาพตาม GMP/PIC/S และเภสัชภัณฑ์ชีวภาพ","curriculum_highlights":["Industrial Drug Manufacturing & GMP","Pharmaceutical Quality Assurance","Biopharmaceutical Production","Drug Regulatory Affairs","Industrial Pharmacy Internship"],"career_paths":["Industrial Pharmacist","QA/QC Pharmacist","Regulatory Affairs Specialist","Biopharma Production","Pharma Entrepreneur"],"tags":["Industrial Pharmacy","MU","GMP"],"website_url":"https://www.pharmacy.mahidol.ac.th"},
  {"id":"mu_pharm_cosmetic_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์เครื่องสำอาง","title_en":"Master of Science Program in Cosmetic Science","degree_level":"ปริญญาโท","degree_name":"วท.ม. (วิทยาศาสตร์เครื่องสำอาง)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Pharmacy","faculty_th":"คณะเภสัชศาสตร์","department":"Cosmetic Science","department_th":"สาขาวิชาวิทยาศาสตร์เครื่องสำอาง","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"32,000 บาท","tuition_total":"128,000 บาท","description":"วิจัยเครื่องสำอางจากสมุนไพรไทยและนวัตกรรมความงามยั่งยืนร่วมกับอุตสาหกรรมความงาม","curriculum_highlights":["Cosmetic Formulation & Thai Herbal","Cosmetic Safety & FDA Regulation","Thesis Cosmetic Science","Sensory Evaluation Cosmetics","Internship Beauty Industry"],"career_paths":["Cosmetic Scientist","R&D Cosmetics","Product Development Manager","Regulatory Cosmetics","Beauty Entrepreneur"],"tags":["Cosmetic Science","MU","Herbal"],"website_url":"https://www.pharmacy.mahidol.ac.th"},
  {"id":"mu_pharm_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาเภสัชศาสตร์","title_en":"Doctor of Philosophy Program in Pharmaceutical Sciences","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (เภสัชศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Pharmacy","faculty_th":"คณะเภสัชศาสตร์","department":"Doctoral Program Pharmacy","department_th":"สาขาวิชาเภสัชศาสตร์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"210,000 บาท","description":"วิจัยเภสัชศาสตร์ขั้นสูงระดับนานาชาติ การค้นพบยาใหม่","curriculum_highlights":["Drug Discovery & Design Mahidol","Pharmacogenomics & Precision Medicine","Dissertation Pharmacy","International Publication","Teaching Pharmacy"],"career_paths":["Pharmacy Professor","Pharma R&D Director","Drug Discovery Scientist","Regulatory Leader","Academic"],"tags":["Ph.D. Pharmacy","MU","Drug Discovery"],"website_url":"https://www.pharmacy.mahidol.ac.th"},
  {"id":"mu_pharm_social_phd","title_th":"หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาเภสัชศาสตร์สังคมและการบริหาร","title_en":"Doctor of Philosophy Program in Social and Administrative Pharmacy","degree_level":"ปริญญาเอก","degree_name":"ปร.ด. (เภสัชศาสตร์สังคมและการบริหาร)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Pharmacy","faculty_th":"คณะเภสัชศาสตร์","department":"Social Pharmacy","department_th":"ภาควิชาเภสัชศาสตร์สังคมและการบริหาร","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"210,000 บาท","description":"วิจัยนโยบายยา เภสัชเศรษฐศาสตร์ และการเข้าถึงยาในระบบหลักประกันสุขภาพไทย","curriculum_highlights":["Pharmaceutical Policy & Access","Pharmacoeconomics & HTA","Social Pharmacy Research","Dissertation Social Pharmacy","Policy Advocacy"],"career_paths":["Pharmacy Policy Researcher","HTA Analyst","Access to Medicines Advocate","Academic Social Pharmacy","Consultant"],"tags":["Social Pharmacy","HTA","MU","Ph.D."],"website_url":"https://www.pharmacy.mahidol.ac.th"},
  # === FACULTY OF DENTISTRY expansion (4) - currently 13, add more ===
  {"id":"mu_dent_ortho_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาทันตกรรมจัดฟัน","title_en":"Master of Science Program in Orthodontics","degree_level":"ปริญญาโท","degree_name":"วท.ม. (ทันตกรรมจัดฟัน)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Dentistry","faculty_th":"คณะทันตแพทยศาสตร์","department":"Department of Orthodontics","department_th":"ภาควิชาทันตกรรมจัดฟัน","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"60,000 บาท","tuition_total":"360,000 บาท","description":"ผลิตทันตแพทย์จัดฟันเชี่ยวชาญ เทคนิคจัดฟันใส Clear Aligner และทันตกรรมดิจิทัล","curriculum_highlights":["Advanced Orthodontic Mechanics Bangkok","Clear Aligner & Digital Orthodontics","Craniofacial Development","Thesis Orthodontics","Clinical Ortho Residency Mahidol"],"career_paths":["Orthodontist","Clear Aligner Specialist","Private Ortho Clinic","Hospital Ortho Specialist","Academic Ortho"],"tags":["Orthodontics","MU","Dentistry"],"website_url":"https://www.dt.mahidol.ac.th"},
  {"id":"mu_dent_implant_dip","title_th":"หลักสูตรประกาศนียบัตรบัณฑิตชั้นสูง สาขาวิชาทันตกรรมรากเทียม","title_en":"Higher Graduate Diploma Program in Implant Dentistry","degree_level":"ประกาศนียบัตรบัณฑิต (ชั้นสูง)","degree_name":"ป.บัณฑิตชั้นสูง (ทันตกรรมรากเทียม)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Dentistry","faculty_th":"คณะทันตแพทยศาสตร์","department":"Implant Dentistry","department_th":"สาขาวิชาทันตกรรมรากเทียม","program_type":"ภาคปกติ","duration_years":"1 ปี","total_credits":"24 หน่วยกิต","tuition_per_semester":"90,000 บาท","tuition_total":"180,000 บาท","description":"เน้นทันตกรรมรากเทียมดิจิทัล CT-guided และการฟื้นฟูรากเทียม","curriculum_highlights":["Digital Implant Planning CT","Implant Surgery & Prosthodontics","Bone Augmentation & Tissue Engineering","Implant Complications","Clinical Implant Residency"],"career_paths":["Implant Dentist","Private Implant Clinic","Hospital Implant Specialist","Implant Educator","Entrepreneur"],"tags":["Implant Dentistry","MU","Diploma"],"website_url":"https://www.dt.mahidol.ac.th"},
  {"id":"mu_dent_pedo_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาทันตกรรมสำหรับเด็ก","title_en":"Master of Science Program in Pediatric Dentistry","degree_level":"ปริญญาโท","degree_name":"วท.ม. (ทันตกรรมสำหรับเด็ก)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Dentistry","faculty_th":"คณะทันตแพทยศาสตร์","department":"Pediatric Dentistry","department_th":"ภาควิชาทันตกรรมสำหรับเด็ก","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"55,000 บาท","tuition_total":"330,000 บาท","description":"เน้นทันตกรรมเด็กเชิงป้องกันและพฤติกรรมเด็ก","curriculum_highlights":["Pediatric Dentistry Prevention","Child Behavior Management","Thesis Pediatric Dentistry","Clinical Pediatric Residency","Community Pediatric Outreach"],"career_paths":["Pediatric Dentist","Children Dental Specialist","Hospital Pediatric Dentist","Academic Pediatric","Private Practice"],"tags":["Pediatric Dentistry","MU"],"website_url":"https://www.dt.mahidol.ac.th"},
  {"id":"mu_dent_endo_msc","title_th":"หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเอ็นโดดอนต์","title_en":"Master of Science Program in Endodontics","degree_level":"ปริญญาโท","degree_name":"วท.ม. (เอ็นโดดอนต์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"Faculty of Dentistry","faculty_th":"คณะทันตแพทยศาสตร์","department":"Endodontics","department_th":"ภาควิชาเอ็นโดดอนต์","program_type":"ภาคปกติ","duration_years":"3 ปี","total_credits":"48 หน่วยกิต","tuition_per_semester":"55,000 บาท","tuition_total":"330,000 บาท","description":"เน้นรักษารากฟันด้วยกล้องจุลทรรศน์และเทคนิคหมุนดิจิทัล","curriculum_highlights":["Microscopic Endodontics","Rotary Endodontic Techniques","Thesis Endodontics","Clinical Endo Residency","Pain Management Endo"],"career_paths":["Endodontist","Root Canal Specialist","Hospital Endo Specialist","Academic Endo","Private Practice"],"tags":["Endodontics","MU","Dentistry"],"website_url":"https://www.dt.mahidol.ac.th"},
  # === COLLEGE OF MUSIC (2) ===
  {"id":"mu_music_bmus","title_th":"หลักสูตรดุริยางคศาสตรบัณฑิต","title_en":"Bachelor of Music Program","degree_level":"ปริญญาตรี","degree_name":"ดศ.บ. (ดุริยางคศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"College of Music","faculty_th":"วิทยาลัยดุริยางคศิลป์","department":"College of Music","department_th":"วิทยาลัยดุริยางคศิลป์","program_type":"ภาคปกติ","duration_years":"4 ปี","total_credits":"132 หน่วยกิต","tuition_per_semester":"35,000 บาท","tuition_total":"280,000 บาท","description":"วิทยาลัยดุริยางคศิลป์อันดับ 1 ไทย เน้นการแสดงดนตรีคลาสสิก แจ๊ส ดนตรีไทย และเทคโนโลยีดนตรี","curriculum_highlights":["Classical & Jazz Performance","Thai Music & Ensemble","Music Technology & Sound Engineering","Composition & Arranging","Recital & Concert Management"],"career_paths":["Professional Musician","Music Teacher","Sound Engineer","Composer","Music Event Manager"],"tags":["Music","MU","College of Music","Performance"],"website_url":"https://www.music.mahidol.ac.th"},
  {"id":"mu_music_mmus","title_th":"หลักสูตรดุริยางคศาสตรมหาบัณฑิต","title_en":"Master of Music Program","degree_level":"ปริญญาโท","degree_name":"ดศ.ม. (ดุริยางคศาสตร์)","university":"Mahidol University","university_th":"มหาวิทยาลัยมหิดล","faculty":"College of Music","faculty_th":"วิทยาลัยดุริยางคศิลป์","department":"Graduate Music","department_th":"บัณฑิตศึกษา ดุริยางคศิลป์","program_type":"ภาคปกติ","duration_years":"2 ปี","total_credits":"36 หน่วยกิต","tuition_per_semester":"40,000 บาท","tuition_total":"160,000 บาท","description":"วิจัยการแสดงดนตรีระดับสูงและการประพันธ์ดนตรีร่วมสมัย","curriculum_highlights":["Advanced Performance & Pedagogy","Composition & Music Research","Thesis Music Performance","International Masterclass","Concert & Recording Project"],"career_paths":["Professional Performer","Music Professor","Composer","Music Director","Recording Artist"],"tags":["Master Music","MU","Performance"],"website_url":"https://www.music.mahidol.ac.th"},
]
print(f"Prepared {len(MU_COURSES)} MU courses")
out=pathlib.Path("backend/data/courses_new/courses_mu_expansion1.json")
with open(out,'w',encoding='utf-8') as f:
    json.dump(MU_COURSES,f,ensure_ascii=False,indent=2)
print(f"Saved to {out}")
Base.metadata.create_all(bind=engine)
session=SessionLocal()
ins=upd=0
for c in MU_COURSES:
    et=emb_text(c)
    try:
        vec=embedding_service.get_embedding(et)
        if vec and len(vec)!=768:
            vec=None
    except Exception as e:
        print(f"emb fail {c['id']}: {e}")
        vec=None
    ex=session.query(CourseDB).filter_by(id=c["id"]).first()
    if ex:
        for k,v in c.items():
            setattr(ex,k,v)
        ex.embedding_text=et
        if vec:
            ex.embedding=vec
        upd+=1
        print(f"Updated {c['id']}")
    else:
        db=CourseDB(id=c["id"], title_th=c["title_th"], title_en=c.get("title_en"), degree_level=c["degree_level"], degree_name=c.get("degree_name"), university=c["university"], university_th=c["university_th"], faculty=c["faculty"], faculty_th=c["faculty_th"], department=c.get("department"), department_th=c.get("department_th"), program_type=c.get("program_type","ภาคปกติ"), duration_years=c.get("duration_years"), total_credits=c.get("total_credits"), tuition_per_semester=c.get("tuition_per_semester"), tuition_total=c.get("tuition_total"), description=c.get("description"), curriculum_highlights=c.get("curriculum_highlights",[]), career_paths=c.get("career_paths",[]), tags=c.get("tags",[]), website_url=c.get("website_url"), embedding_text=et, embedding=vec if vec else None)
        session.add(db)
        ins+=1
        print(f"Inserted {c['id']} emb={'OK' if vec else 'NULL'}")
    if (ins+upd)%20==0:
        session.commit()
session.commit()
print(f"Done MU ins={ins} upd={upd}")
from sqlalchemy import text as t
with engine.connect() as conn:
    total=conn.execute(t("SELECT COUNT(*) FROM courses WHERE university='Mahidol University'")).scalar()
    print(f"MU total now: {total}")
    tot_all=conn.execute(t("SELECT COUNT(*) FROM courses")).scalar()
    print(f"DB total: {tot_all}")
session.close()
