# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789880130_78468b)
EXTRACTED_FACULTIES = [
    {
        "id": "kingmongku_facultyofe_visitsattapongs_001",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Sarinporn",
        "last_name": "Visitsattapongse",
        "full_name": "Sarinporn Visitsattapongse",
        "full_name_th": "รศ.ดร. สารินพร วิเยี่ยมสัตตپงศ์",
        "role": "อาจารย์ประจำ",
        "email": "sarinporn.vi@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Medical Technology, Mahidol University, Thailand (2014)"
        ],
        "research_interests": [
            "genetic engineering",
            "molecular biology/biochemistry"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_tungjitkusolmun_002",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Supan",
        "last_name": "Tungjitkusolmun",
        "full_name": "Supan Tungjitkusolmun",
        "full_name_th": "รศ.ดร. สุพันธ์ ทั่งจิตต์กุศลมนต์",
        "role": "อาจารย์ประจำ",
        "email": "supan.tu@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Electrical Engineering, University of Wisconsin-Madison, USA (2000)"
        ],
        "research_interests": [
            "signal processing",
            "medical devices",
            "tissue ablation"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_piyawattanameth_003",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Wibool",
        "last_name": "Piyawattanametha",
        "full_name": "Wibool Piyawattanametha",
        "full_name_th": "รศ.ดร. วิบูลย์ ปิยะวัฒนเมธา",
        "role": "อาจารย์ประจำ",
        "email": "wibool.pi@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Electrical Engineering, University of California, Los Angeles, USA (2004)"
        ],
        "research_interests": [
            "biophotonics",
            "imaging",
            "medical devices"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_paing_004",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "May Phu",
        "last_name": "Paing",
        "full_name": "May Phu Paing",
        "full_name_th": "ผศ.ดร. เมย์ ภู เป่ง",
        "role": "อาจารย์ประจำ",
        "email": "may.pa@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Electrical Engineering, King Mongkut's Institute of Technology Ladkrabang, Thailand (2020)"
        ],
        "research_interests": [
            "Image processing",
            "Artificial intelligence"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_nampeng_005",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Jindapa",
        "last_name": "Nampeng",
        "full_name": "Jindapa Nampeng",
        "full_name_th": "อ. จินดาภา นำเพ็ง",
        "role": "อาจารย์ประจำ",
        "email": "jindapa.na@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "MSc Drug Chemistry, Newcastle University, UK (2022)"
        ],
        "research_interests": [
            "Biosensors",
            "Medical device",
            "Deep learning",
            "Biochemistry"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_wisitponchai_006",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Tanchanok",
        "last_name": "Wisitponchai",
        "full_name": "Tanchanok Wisitponchai",
        "full_name_th": "ดร. ธัญชนก วิสิฐพงศ์ชัย",
        "role": "อาจารย์ประจำ",
        "email": "tanchanok.wi@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Biomedical Engineering, University of Strathclyde, UK (2026)"
        ],
        "research_interests": [
            "Computational fluid dynamics"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_srirussamee_007",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Kasama",
        "last_name": "Srirussamee",
        "full_name": "Kasama Srirussamee",
        "full_name_th": "ผศ.ดร. ภาสกร ศรีรัสมี",
        "role": "อาจารย์ประจำ",
        "email": "kasama.sr@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Biomedical Materials, The University of Manchester, UK (2019)"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_pintavirooj_008",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Chuchart",
        "last_name": "Pintavirooj",
        "full_name": "Chuchart Pintavirooj",
        "full_name_th": "ศ.ดร. ชูชาติ ปินตาวิโรจน์",
        "role": "อาจารย์ประจำ",
        "email": "chuchart.pi@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Biomedical Engineering, Drexel University, USA (2000)"
        ],
        "research_interests": [
            "image processing",
            "medical devices",
            "X-rays"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_gleeson_009",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Matthew Paul",
        "last_name": "Gleeson",
        "full_name": "Matthew Paul Gleeson",
        "full_name_th": "ศ.ดร. แมทธิว พอล กลีสัน",
        "role": "อาจารย์ประจำ",
        "email": "paul.gl@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Chemistry, University of Manchester, UK (2003)"
        ],
        "research_interests": [
            "medicinal chemistry",
            "pharmaceutical engineering",
            "molecular simulations"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_treebupachatsak_010",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Treesukon",
        "last_name": "Treebupachatsakul",
        "full_name": "Treesukon Treebupachatsakul",
        "full_name_th": "ผศ.ดร. เปรมสุดา ตรีบุพชาติสกุล",
        "role": "อาจารย์ประจำ",
        "email": "treesukon.tr@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Integrated Bioscience and Technology, Nagaoka University of Technology, Japan (2015)"
        ],
        "research_interests": [
            "cellular engineering",
            "biomass"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_hannantaanan_011",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Pimkhuan",
        "last_name": "Hannanta-anan",
        "full_name": "Pimkhuan Hannanta-anan",
        "full_name_th": "ผศ.ดร. พิมพ์ขวัญ หนันทานันท์",
        "role": "อาจารย์ประจำ",
        "email": "pimkhuan.ha@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Bioengineering, University of Pennsylvania (2018)"
        ],
        "research_interests": [
            "Synthetic Biology",
            "Optogenetics",
            "Microfluidics",
            "Diagnostics",
            "Bioinformatics",
            "Functional Food"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_thanarak_012",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Jeerawan",
        "last_name": "Thanarak",
        "full_name": "Jeerawan Thanarak",
        "full_name_th": "ดร. จีรวรรณ ธนารักษ์",
        "role": "อาจารย์ประจำ",
        "email": "jeerawan.th@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Biomaterials and Tissue Engineering, The University of Sheffield, UK (2023)"
        ],
        "research_interests": [
            "Soft Tissue Engineering",
            "Polymer Biomaterials",
            "Bioreactors"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_facultyofe_leewiwatwong_013",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Suphachart",
        "last_name": "Leewiwatwong",
        "full_name": "Suphachart Leewiwatwong",
        "full_name_th": "ดร. ศุภชาติ ลีิววัฒน์วงศ์",
        "role": "อาจารย์ประจำ",
        "email": "suphachart.le@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Biomedical Engineering, Duke University, USA (2026)"
        ],
        "research_interests": [
            "Medical Imaging",
            "Hyperpolarized xenon",
            "MRI"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
