# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789880204_b81b7a)
EXTRACTED_FACULTIES = [
    {
        "id": "kingmongku_internatio_yooyen_001",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "International Academy of Aviation Industry",
        "faculty_th": "วิทยาลัยอุตสาหกรรมการบินนานาชาติ (IAAI)",
        "department": "International Academy of Aviation Industry",
        "department_th": "International Academy of Aviation Industry",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Soemsak",
        "last_name": "Yooyen",
        "full_name": "Soemsak Yooyen",
        "full_name_th": "ผศ.ดร. เสริมศักดิ์ อยู่เย็น",
        "role": "อาจารย์ประจำ",
        "email": "soemsak.yo@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Philosophy (Materials Science), Mie University, Japan",
            "Master of Science (Materials Science), Mie University, Japan",
            "Master of Engineering (Mechanical Engineering), Khon Kaen University, Thailand",
            "Bachelor of Engineering (Mechanical Engineering), Khon Kaen University, Thailand"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_internatio_tipmontian_002",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "International Academy of Aviation Industry",
        "faculty_th": "วิทยาลัยอุตสาหกรรมการบินนานาชาติ (IAAI)",
        "department": "International Academy of Aviation Industry",
        "department_th": "International Academy of Aviation Industry",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Jedsada",
        "last_name": "Tipmontian",
        "full_name": "Jedsada Tipmontian",
        "full_name_th": "ดร. เจษฎา ทิพย์มณเฑียร",
        "role": "อาจารย์ประจำ",
        "email": "jedsada.ti@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Philosophy (Industrial Engineering, Logistics & Supply Chain Management), Anna University, Chennai, India",
            "Master of Engineering (Industrial Engineering), King Mongkut's University of Technology North Bangkok, Thailand",
            "Bachelor of Science (Agro-Industry), Prince of Songkla University, Thailand"
        ],
        "research_interests": [
            "Industrial Engineering",
            "Logistics & Supply Chain Management"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_internatio_itsariyapinyo_003",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "International Academy of Aviation Industry",
        "faculty_th": "วิทยาลัยอุตสาหกรรมการบินนานาชาติ (IAAI)",
        "department": "International Academy of Aviation Industry",
        "department_th": "International Academy of Aviation Industry",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Pititat",
        "last_name": "Itsariyapinyo",
        "full_name": "Pititat Itsariyapinyo",
        "full_name_th": "ผศ.ดร. ภิติพัฒน์ อิสริยภิญโญ",
        "role": "อาจารย์ประจำ",
        "email": "pititat.it@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Philosophy (Mechanical Engineering), University of Auckland, New Zealand",
            "Bachelor of Engineering (Aerospace Engineering), University of New South Wales, Australia"
        ],
        "research_interests": [
            "Mechanical Engineering",
            "Aerospace Engineering"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_internatio_thatchatham_004",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "International Academy of Aviation Industry",
        "faculty_th": "วิทยาลัยอุตสาหกรรมการบินนานาชาติ (IAAI)",
        "department": "International Academy of Aviation Industry",
        "department_th": "International Academy of Aviation Industry",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Chanikarn",
        "last_name": "Thatchatham",
        "full_name": "Chanikarn Thatchatham",
        "full_name_th": "ดร. ชนิกานต์ ธัชธรรม",
        "role": "อาจารย์ประจำ",
        "email": "chanikarn.nu@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Philosophy (English as an International Language), Chulalongkorn University, Thailand",
            "Master of Science (TESOL), The University of Edinburgh, United Kingdom",
            "Bachelor of Arts (English) (2nd Class Honors), Chulalongkorn University, Thailand"
        ],
        "research_interests": [
            "English as an International Language",
            "TESOL"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_internatio_suksangpanya_005",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "International Academy of Aviation Industry",
        "faculty_th": "วิทยาลัยอุตสาหกรรมการบินนานาชาติ (IAAI)",
        "department": "International Academy of Aviation Industry",
        "department_th": "International Academy of Aviation Industry",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Nobphadon",
        "last_name": "Suksangpanya",
        "full_name": "Nobphadon Suksangpanya",
        "full_name_th": "ผศ.ดร. นพดล สุขแสงปัญญา",
        "role": "อาจารย์ประจำ",
        "email": "nobphadon.su@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Philosophy (Civil Engineering), Purdue University, United States",
            "Master of Science & Engineering (Civil Engineering), Purdue University, United States",
            "Bachelor of Engineering (Mechanical Engineering), King Mongkut's Institute of Technology Ladkrabang, Thailand"
        ],
        "research_interests": [
            "Civil Engineering",
            "Mechanical Engineering"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_internatio_rattanakijsunto_006",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "International Academy of Aviation Industry",
        "faculty_th": "วิทยาลัยอุตสาหกรรมการบินนานาชาติ (IAAI)",
        "department": "International Academy of Aviation Industry",
        "department_th": "International Academy of Aviation Industry",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Komsan",
        "last_name": "Rattanakijsuntorn",
        "full_name": "Komsan Rattanakijsuntorn",
        "full_name_th": "ดร. คมสันต์ รัตนกิจสุนทร",
        "role": "อาจารย์ประจำ",
        "email": "komsan.ra@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Philosophy (Mechanical Engineering), University of Southern California, United States",
            "Master of Engineering (Mechanical Engineering), University of Southern California, United States",
            "Bachelor of Engineering (Mechanical Engineering), Chulalongkorn University, Thailand"
        ],
        "research_interests": [
            "Mechanical Engineering"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_internatio_yodpram_007",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "International Academy of Aviation Industry",
        "faculty_th": "วิทยาลัยอุตสาหกรรมการบินนานาชาติ (IAAI)",
        "department": "International Academy of Aviation Industry",
        "department_th": "International Academy of Aviation Industry",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Somcanae",
        "last_name": "Yodpram",
        "full_name": "Somcanae Yodpram",
        "full_name_th": "ผศ.ดร. สมคเณ ยอดพรม",
        "role": "อาจารย์ประจำ",
        "email": "somcanae.yo@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Philosophy (International Business), Silpakorn University International College, Thailand",
            "Master of Arts (Economics), University of Southern California, USA",
            "Bachelor of Arts (Economics), Thammasat University, Thailand"
        ],
        "research_interests": [
            "International Business",
            "Economics"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_internatio_munikanond_008",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "International Academy of Aviation Industry",
        "faculty_th": "วิทยาลัยอุตสาหกรรมการบินนานาชาติ (IAAI)",
        "department": "Asia Aviation Technology",
        "department_th": "Asia Aviation Technology",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Charnvit",
        "last_name": "Munikanond",
        "full_name": "Charnvit Munikanond",
        "full_name_th": "อ. นาย ชาญวิทย์ มุนิกานนท์",
        "role": "อาจารย์ประจำ",
        "email": "paulcharnvit@gmail.com",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Master of Business Administration (Industrial Management), Pacific States University, United States",
            "Bachelor of Arts (History), Srinakharinwirot University, Thailand"
        ],
        "research_interests": [
            "Industrial Management",
            "Space Technology and Research"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kingmongku_internatio_imsri_009",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "International Academy of Aviation Industry",
        "faculty_th": "วิทยาลัยอุตสาหกรรมการบินนานาชาติ (IAAI)",
        "department": "International Academy of Aviation Industry",
        "department_th": "International Academy of Aviation Industry",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Kantima",
        "last_name": "Imsri",
        "full_name": "Kantima Imsri",
        "full_name_th": "อ. ว่าที่ร้อยตรีหญิง กันติมา อิ่มศรี",
        "role": "อาจารย์ประจำ",
        "email": "kantima.im@kmitl.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Master of Business Administration, Maejo University, Thailand",
            "Bachelor of Accounting, Maejo University, Thailand"
        ],
        "research_interests": [
            "Business Administration",
            "Accounting"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
