# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1790398025_8fd8b7)
EXTRACTED_FACULTIES = [
    {
        "id": "thammasatu_pridibanom_bruce_001",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Thai Studies Program",
        "department_th": "Thai Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Thomas",
        "last_name": "Bruce",
        "full_name": "Thomas Bruce",
        "full_name_th": "ดร. Thomas Bruce",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Thai History, the School of Oriental and African Studies (SOAS), University of London"
        ],
        "research_interests": [
            "Thai and Southeast Asian History"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_copeland_002",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Matthew",
        "last_name": "Copeland",
        "full_name": "Matthew Copeland",
        "full_name_th": "ดร. Matthew Copeland",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Asian History, Australian National University"
        ],
        "research_interests": [
            "Asian History"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_duangkong_003",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "",
        "department_th": "",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Thitipong",
        "last_name": "Duangkong",
        "full_name": "Thitipong Duangkong",
        "full_name_th": "อ. Thitipong Duangkong",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "M.A. in Translation and Interpretation, Instituto Universitario de Lenguas Modernas y Traductores, The University of La Complutense, Spain"
        ],
        "research_interests": [
            "Translation and Interpretation"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_duangratana_004",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Thai Studies Program",
        "department_th": "Thai Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Ornthicha",
        "last_name": "Duangratana",
        "full_name": "Ornthicha Duangratana",
        "full_name_th": "ดร. Ornthicha Duangratana",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Political Science (International Relations), Chulalongkorn University"
        ],
        "research_interests": [
            "Political Science",
            "International Relations"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_faheem_005",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Thai Studies Program",
        "department_th": "Thai Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Mohd",
        "last_name": "Faheem",
        "full_name": "Mohd Faheem",
        "full_name_th": "ดร. Mohd Faheem",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Geography, Aligarh Muslim University"
        ],
        "research_interests": [
            "Indian Studies",
            "Geography"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_fongprechakun_006",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Chinese Studies Program",
        "department_th": "Chinese Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Kiattisak",
        "last_name": "Fongprechakun",
        "full_name": "Kiattisak Fongprechakun",
        "full_name_th": "ดร. Kiattisak Fongprechakun",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Linguistics and Applied Linguistics, Minzu University of China"
        ],
        "research_interests": [
            "Chinese Language",
            "Linguistics",
            "Applied Linguistics"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_khamkhun_007",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Thai Studies Program",
        "department_th": "Thai Studies Program",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Akkharaphong",
        "last_name": "Khamkhun",
        "full_name": "Akkharaphong Khamkhun",
        "full_name_th": "อ. Akkharaphong Khamkhun",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "M.A. in Southeast Asian Studies, Graduate School, Chulalongkorn University"
        ],
        "research_interests": [
            "Southeast Asian Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_lertrattananon_008",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Chinese Studies Program",
        "department_th": "Chinese Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Usanee",
        "last_name": "Lertrattananon",
        "full_name": "Usanee Lertrattananon",
        "full_name_th": "ดร. Usanee Lertrattananon",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Diplomacy, Peking University"
        ],
        "research_interests": [
            "Diplomacy",
            "Chinese Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_li_009",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "",
        "department_th": "",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Hongfei",
        "last_name": "Li",
        "full_name": "Hongfei Li",
        "full_name_th": "อ. Hongfei Li",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Candidate in Integrated Science, Thammasat University"
        ],
        "research_interests": [
            "Integrated Science"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_liaotianchai_010",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Thai Studies Program",
        "department_th": "Thai Studies Program",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Warachaya",
        "last_name": "Liaotianchai",
        "full_name": "Warachaya Liaotianchai",
        "full_name_th": "อ. Warachaya Liaotianchai",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "M.A. in Thai (Scholarship), Faculty of Arts, Chulalongkorn University"
        ],
        "research_interests": [
            "Thai Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_yi_011",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Chinese Studies Program",
        "department_th": "Chinese Studies Program",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Lin",
        "last_name": "Yi",
        "full_name": "Lin Yi",
        "full_name_th": "รศ.ดร. Lin Yi",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Sociology, Peking University"
        ],
        "research_interests": [
            "Sociology",
            "Chinese Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_mcbain_012",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Thai Studies Program",
        "department_th": "Thai Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Paul",
        "last_name": "McBain",
        "full_name": "Paul McBain",
        "full_name_th": "ดร. Paul McBain",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Religious Studies, University of Pennsylvania, USA"
        ],
        "research_interests": [
            "Religious Studies",
            "Thai Literature"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_ni_013",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "",
        "department_th": "",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Yating",
        "last_name": "Ni",
        "full_name": "Yating Ni",
        "full_name_th": "อ. Yating Ni",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "M.A. in Teaching Chinese as a Foreign Language, Yunnan Normal University, China"
        ],
        "research_interests": [
            "Teaching Chinese as a Foreign Language"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_phayakhrut_014",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Chinese Studies Program",
        "department_th": "Chinese Studies Program",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Chaiyaporn",
        "last_name": "Phayakhrut",
        "full_name": "Chaiyaporn Phayakhrut",
        "full_name_th": "อ. Chaiyaporn Phayakhrut",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Candidate in Chinese Studies, National University of Singapore, Singapore"
        ],
        "research_interests": [
            "International Relations",
            "Chinese Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_pipatchukiat_015",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Thai Studies Program",
        "department_th": "Thai Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Prididome",
        "last_name": "Pipatchukiat",
        "full_name": "Prididome Pipatchukiat",
        "full_name_th": "ดร. Prididome Pipatchukiat",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Geography, Aberystwyth University, Wales"
        ],
        "research_interests": [
            "Sociology",
            "Geography"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_piyasirikul_016",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Chinese Studies Program",
        "department_th": "Chinese Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Kampol",
        "last_name": "Piyasirikul",
        "full_name": "Kampol Piyasirikul",
        "full_name_th": "ดร. Kampol Piyasirikul",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Comparative Political Systems, Peking University"
        ],
        "research_interests": [
            "Comparative Politics"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_rattanaprichave_017",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Chinese Studies Program",
        "department_th": "Chinese Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Monthinee",
        "last_name": "Rattanaprichavej",
        "full_name": "Monthinee Rattanaprichavej",
        "full_name_th": "ดร. Monthinee Rattanaprichavej",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Economics, Peking University"
        ],
        "research_interests": [
            "Economics"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_sinha_018",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Thai Studies Program",
        "department_th": "Thai Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Shweta",
        "last_name": "Sinha",
        "full_name": "Shweta Sinha",
        "full_name_th": "ดร. Shweta Sinha",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Remote Sensing and GIS, Asian Institute of Technology"
        ],
        "research_interests": [
            "Environmental Technology",
            "Remote Sensing",
            "GIS"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_teanmahasatid_019",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Chinese Studies Program",
        "department_th": "Chinese Studies Program",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Jaruwan",
        "last_name": "Teanmahasatid",
        "full_name": "Jaruwan Teanmahasatid",
        "full_name_th": "อ. Jaruwan Teanmahasatid",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Candidate in History, the School of Oriental and African Studies (SOAS), University of London"
        ],
        "research_interests": [
            "History",
            "Chinese Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_wang_020",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Chinese Studies Program",
        "department_th": "Chinese Studies Program",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Chunyu",
        "last_name": "Wang",
        "full_name": "Chunyu Wang",
        "full_name_th": "อ. Chunyu Wang",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "M.A. in Education Science, China Light Industry College"
        ],
        "research_interests": [
            "Education",
            "Education Science"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_winichakul_021",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Department of History, University of Wisconsin, Madison",
        "department_th": "Department of History, University of Wisconsin, Madison",
        "academic_title": "ศ.",
        "academic_title_th": "ศ.",
        "first_name": "Thongchai",
        "last_name": "Winichakul",
        "full_name": "Thongchai Winichakul",
        "full_name_th": "ศ. Thongchai Winichakul",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "History"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_withoonchart_022",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Thai Studies Program",
        "department_th": "Thai Studies Program",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Ken",
        "last_name": "Withoonchart",
        "full_name": "Ken Withoonchart",
        "full_name_th": "ดร. Ken Withoonchart",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in History, University of Edinburgh"
        ],
        "research_interests": [
            "History",
            "Thai Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_wongratanapitak_023",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Paphutsorn",
        "last_name": "Wongratanapitak",
        "full_name": "Paphutsorn Wongratanapitak",
        "full_name_th": "ดร. Paphutsorn Wongratanapitak",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Ethnomusicology, the School of Oriental and African Studies (SOAS), University of London"
        ],
        "research_interests": [
            "Ethnomusicology"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_xizhen_024",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "Chinese Studies Program",
        "department_th": "Chinese Studies Program",
        "academic_title": "ศ.",
        "academic_title_th": "ศ.",
        "first_name": "Zhang",
        "last_name": "Xizhen",
        "full_name": "Zhang Xizhen",
        "full_name_th": "ศ. Zhang Xizhen",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "International Politics"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_sinha_025",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Ta",
        "last_name": "Sinha",
        "full_name": "Ta Sinha",
        "full_name_th": "ผศ.ดร. ตา สินหา",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Remote Sensing and GIS, Asian Institute of Technology"
        ],
        "research_interests": [
            "Environmental Technology",
            "Thai Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_teanmahasatid_026",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Jaruwan",
        "last_name": "Teanmahasatid",
        "full_name": "Jaruwan Teanmahasatid",
        "full_name_th": "อ. จารุวรรณ เตียมา하สถิต",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Candidate in History, the School of Oriental and African Studies (SOAS), University of London"
        ],
        "research_interests": [
            "Chinese Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_wang_027",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Chunyu",
        "last_name": "Wang",
        "full_name": "Chunyu Wang",
        "full_name_th": "ผศ. ชุนหยู หวัง",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "M.A. in Education Science, China Light Industry College"
        ],
        "research_interests": [
            "Education",
            "Chinese Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_withoonchart_028",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Ken",
        "last_name": "Withoonchart",
        "full_name": "Ken Withoonchart",
        "full_name_th": "ดร. เคน วิฑูรชาติ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in History, University of Edinburgh"
        ],
        "research_interests": [
            "Thai Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_xizhen_029",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "ศ.",
        "academic_title_th": "ศ.",
        "first_name": "Zhang",
        "last_name": "Xizhen",
        "full_name": "Zhang Xizhen",
        "full_name_th": "ศ. จาง ซีเจิ้น",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "School of International Relations, Peking University (1997-2010)"
        ],
        "research_interests": [
            "International Politics",
            "Chinese Studies"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_copeland_030",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Matthew",
        "last_name": "Copeland",
        "full_name": "Matthew Copeland",
        "full_name_th": "ดร. แมทธิว โคปแลนด์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Asian History, Australian National University"
        ],
        "research_interests": [
            "Asian History"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_duangkong_031",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Thitipong",
        "last_name": "Duangkong",
        "full_name": "Thitipong Duangkong",
        "full_name_th": "อ. ฐิติพงศ์ ดวงคง",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "MA in Translation and Interpretation, Instituto Universitario de Lenguas Modernas y Traductores, The University of La Complutense"
        ],
        "research_interests": [
            "Translation and Interpretation"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_li_032",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Hongfei",
        "last_name": "Li",
        "full_name": "Hongfei Li",
        "full_name_th": "อ. ฮองเฟย หลี่",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. Candidate in Integrated Science, Thammasat University"
        ],
        "research_interests": [
            "Integrated Science"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_ni_033",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Yating",
        "last_name": "Ni",
        "full_name": "Yating Ni",
        "full_name_th": "อ. ยาติง นิ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "M.A. in Teaching Chinese as a Foreign Language, Yunnan Normal University, China"
        ],
        "research_interests": [
            "Teaching Chinese as a Foreign Language"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_winichakul_034",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Thongchai",
        "last_name": "Winichakul",
        "full_name": "Thongchai Winichakul",
        "full_name_th": "ศ.ดร. ธงชัย วินิจกุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Department of History, University of Wisconsin, Madison"
        ],
        "research_interests": [
            "History"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_pridibanom_wongratanapitak_035",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Pridi Banomyong International College",
        "faculty_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "department_th": "วิทยาลัยนานาชาติ ปรีดี พนมยงค์",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Paphutsorn",
        "last_name": "Wongratanapitak",
        "full_name": "Paphutsorn Wongratanapitak",
        "full_name_th": "ดร. ภาผุศร วงศ์รัตนพิทักษ์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Ethnomusicology, the School of Oriental and African Studies (SOAS), University of London"
        ],
        "research_interests": [
            "Ethnomusicology"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
