# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1790398064_549256)
EXTRACTED_FACULTIES = [
    {
        "id": "princeofso_facultyofm_tepayakul_001",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "",
        "department_th": "",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Ruechuta",
        "last_name": "Tepayakul",
        "full_name": "Ruechuta Tepayakul",
        "full_name_th": "ผศ.ดร. ฤๅชุตา เทพยากุล",
        "role": "อาจารย์ประจำ",
        "email": "ruechuta.t@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Management, Prince of Songkla University, 2558"
        ],
        "research_interests": [
            "การบริหารทรัพยากรมนุษย์",
            "การบริหารคนเก่ง",
            "การบริหารทุนมนุษย์",
            "องค์การและการจัดการ",
            "พฤติกรรมองค์การ"
        ],
        "featured_publications": [
            "Tepayakul, R., & Rintahaisong, I. (2018). Job Satisfaction and Employee Engagement among Human Resources Staff of Thai Private Higher Education Institutions. The Journal of Behavioral Science, 13(2), 68–81.",
            "Tepayakul, R., & Rintahaisong, I. (2016). Finding Components of Talent Management System. Silpakorn University Journal of Social Sciences, Humanities, and Arts, 16(3), 77–90."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_taveekan_002",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Thunradee",
        "last_name": "Taveekan",
        "full_name": "Thunradee Taveekan",
        "full_name_th": "ดร. ธัญรดี ทวีกาญจน์",
        "role": "อาจารย์ประจำ",
        "email": "thunradee.t@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. (Social Science), School of Global, Urban and Social Studies, RMIT University, Australia, 2014"
        ],
        "research_interests": [
            "การบริหารการปกครอง",
            "นโยบายสาธารณะ",
            "การพัฒนา"
        ],
        "featured_publications": [
            "Battersby P, Taveekan T, and Nimbtik G. Models of Governance: Governance, Power and Participation” In Battersby P and Roy R, eds. International Development: A Global Perspective on Theory and Practice. London, UK: SAGE; 2017: 50 – 67."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_isro_003",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Siriwit",
        "last_name": "Isro",
        "full_name": "Siriwit Isro",
        "full_name_th": "ดร. สิริวิท อิสโร",
        "role": "อาจารย์ประจำ",
        "email": "siriwit.i@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. รัฐศาสตรดุษฎีบัณฑิต (รัฐศาสตร์), จุฬาลงกรณ์มหาวิทยาลัย, 2558"
        ],
        "research_interests": [
            "การบริหารคุณภาพ",
            "การบริหารยุทธศาสตร์",
            "การประเมินผลโครงการ",
            "รัฐประศาสนศาสตร์"
        ],
        "featured_publications": [
            "ศิรภัสสรศ์ วงศ์ทองดี, สิริวิท อิสโร และคณะ. 2559. ยุทธศาสตร์การนำคุณค่าของผู้สูงอายุมาสู่สังคมอย่างสร้างสรรค์บนพื้นฐานการสร้างหลักประกันคุณภาพชีวิตที่ดีให้กับประชากรทุกวัย. วารสารวิทยาลัยพยาบาลพระปกเกล้า จันทบุรี, ปีที่ 27 ฉบับที่ 2 (มีนาคม – สิงหาคม).",
            "สิริวิท อิสโร. 2558. ประสิทธิผลของการบริหารคุณภาพในองค์การภาครัฐของไทย (Effectiveness of Quality Management in Thai Public Organizations). วารสารการเมือง การบริหาร และกฎหมาย,7(1)."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_pulsawasd_004",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Sorawit",
        "last_name": "Pulsawasd",
        "full_name": "Sorawit Pulsawasd",
        "full_name_th": "ดร. สรวิศ ลิ้มโอภาส พูลสวัสดิ์",
        "role": "อาจารย์ประจำ",
        "email": "sorawit.pu@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "PhD in Social Sciences (NGO and Development Management), University of East London, United Kingdom, 2024",
            "Ph.D. in Public Management, University of East London, United Kingdom, 2024"
        ],
        "research_interests": [
            "การบริหารองค์การไม่แสวงหาผลกำไร",
            "การทำงานร่วมข้ามภาคส่วนระหว่างรัฐบาล ภาคธุรกิจ และภาคประชาสังคม",
            "การร่วมลงทุนระหว่างภาครัฐและภาคเอกชนในกิจการของรัฐ",
            "การบริหารการพัฒนาและความยั่งยืน"
        ],
        "featured_publications": [
            "Pulsawasd, S (April, 2018) “Social Partners or Social Contractors?: SDNGO-NTNC Collaborations and Development as Service Delivery in Thailand”, University of East London",
            "Pulsawasd, S (April, 2018) “Social Partners or Social Contractors?: SDNGO-NTNC Collaborations and Development as Service Delivery in Thailand”, University of East London, Department of Social Sciences, Symposium Research in Progress",
            "Pulsawasd S & Paul G, (August, 2016): Identification and removal of the collaboration barriers between Multinational Corporations and Local Non-Governmental Organisations in the Asia Pacific: A Case Study of Thailand, 9th International Society for Third-Sector Research (ISTR) Asia Pacific Regional conference in Japan"
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_ekarisakul_005",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Kittipan",
        "last_name": "Ekarisakul",
        "full_name": "Kittipan Ekarisakul",
        "full_name_th": "ดร. กิตติพันธ์ เอกอารีสกุล",
        "role": "อาจารย์ประจำ",
        "email": "kittipan.e@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. in Public Management, Universiti Utara Malaysia, 2025"
        ],
        "research_interests": [
            "นโยบายสาธารณะและการจัดการ"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_amsuk_006",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Ratchaphon",
        "last_name": "Amsuk",
        "full_name": "Ratchaphon Amsuk",
        "full_name_th": "ดร. รัชพล อ่ำสุข",
        "role": "อาจารย์ประจำ",
        "email": "ratchaphon.a@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "D.P.A. (Public and Private Management), National Institute of Development Administration, THAILAND, 2023"
        ],
        "research_interests": [
            "Elderly and Aging Society",
            "Organization Theory and Organization Management",
            "Public/Private Management",
            "Public Policy",
            "Participation"
        ],
        "featured_publications": [
            "Amsuk, R. (2026). Cultural heritage management in Thailand: The perspective from regulation, implementation, and impediment under public-private partnership and civil society participation. Asia-Pacific Social Science Review, 26(2).",
            "Amsuk, R., Tupmongkol, P., Marnarath, P., & Promma, S. (2025). Isomorphism and network governance: A reflection of the Thai elderly quality of life development and career promotion centers. Asia-Pacific Social Science Review, 25(4), 88-102.",
            "Amsuk, R. (2025). Thai elderly’s working needs during 2007–2021: Empirical findings on aging health status and impact from Thai elderly financial support policy. Asia-Pacific Social Science Review, 25(2), 12-23.",
            "Amsuk, R., & Lorsuwannarat, T. (2023). The management of the elderly quality of life development and career promotion centers. Thai Interdisciplinary and Sustainability Review, 12(2), 121-130.",
            "Phramaha Arun Panyaruno, Wijitwatchararak, K., Amsuk, R., & Charoenjai, N. (2020). Aging empowerment guideline by using the temple based aging self care in Thailand. Journal of Social Science and Buddhistic Anthropology, 5(1), 102-121."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
