# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1790398081_c5ed17)
EXTRACTED_FACULTIES = [
    {
        "id": "princeofso_facultyofm_saengkassanee_001",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "คณะวิทยาการจัดการ",
        "department_th": "คณะวิทยาการจัดการ",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Thanawut",
        "last_name": "Saengkassanee",
        "full_name": "Thanawut Saengkassanee",
        "full_name_th": "ดร. ธนาวุธ แสงกาศนีย์",
        "role": "อาจารย์ประจำ",
        "email": "thanawut.sa@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D (Management Sciences), Universite Montpellier ll france, 2551"
        ],
        "research_interests": [
            "การเงิน",
            "การลงทุน",
            "บริหารธุรกิจ"
        ],
        "featured_publications": [
            "Poonsuk Sirikururat, Klangjai Sangwichitr, Panern Intara, and Poom Cheecharoen. (2017). The Feasibility Study of Serviced Apartment Project on the Basis of Universal Design in Hatyai, Songkhla.",
            "Nattapol Khoothiratrakarn, Klangjai Sangwichitr, Thanawut Saengkassanee, and Noppawan Mann. (2018). Analysis of Investors’ Behavior and Asset Allocation Strategies in Hat Yai, Songkhla.",
            "Warat Limphanudom, Klangjai Sangwichitr, Thanawut Saengkassanee, and Panern Intara. (2019). Investors Behavior Towards High Dividend Stock in Stock Exchange Thailand.",
            "กลางใจ แสงวิจิตร, ธนาวุธ แสงกาศนีย์, พรทิพย์ จิระธำรง, พเนิน อินมะระ, ศรรสนีย์ สังข์สุวรรณ และ ภูมิ ชี้เจริญ (2562). การเปรียบเทียบความรู้และพฤติกรรมการจัดการการเงินส่วนบุคคลก่อนและหลังเรียนรายวิชาการเงินส่วนบุคคลของนักศึกษา มหาวิทยาลัยสงขลานครินทร์. วารสารหาดใหญ่วิชาการ 17(2). 127-141"
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_cheecharoen_002",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "คณะวิทยาการจัดการ",
        "department_th": "คณะวิทยาการจัดการ",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Poom",
        "last_name": "Cheecharoen",
        "full_name": "Poom Cheecharoen",
        "full_name_th": "อ. ภูมิ ชี้เจริญ",
        "role": "อาจารย์ประจำ",
        "email": "poom.c@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "MSc Finance, University of Portsmouth, UK, 2016"
        ],
        "research_interests": [
            "การลงทุน",
            "การบริหารสินเชื่อ",
            "การเงินส่วนบุคคล",
            "การประเมินมูลค่า"
        ],
        "featured_publications": [
            "กลางใจ แสงวิจิตร, ธนาวุธ แสงกาศนีย์, พรทิพย์ จิระธำรง, พเนิน อินทะระ, ศรรสนีย์ สังข์สุวรรณ, และภูมิ ชี้เจริญ. (2562). การเปรียบเทียบความรู้และพฤติกรรมการจัดการการเงินส่วนบุคคลก่อนและหลังเรียนรายวิชาการเงินส่วนบุคคลของนักศึกษา มหาวิทยาลัยสงขลานครินทร์. วารสารหาดใหญ่วิชาการ, 17(2), 127-141."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_sangsuwan_003",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "คณะวิทยาการจัดการ",
        "department_th": "คณะวิทยาการจัดการ",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Sansanee",
        "last_name": "Sangsuwan",
        "full_name": "Sansanee Sangsuwan",
        "full_name_th": "อ. ศรรสนีย์ ทีปรักษพันธ์",
        "role": "อาจารย์ประจำ",
        "email": "sansanee.sa@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "วท.ม. สาขาการกำกับดูแลกิจการ จุฬาลงกรณ์มหาวิทยาลัย"
        ],
        "research_interests": [
            "กำกับดูแลกิจการ"
        ],
        "featured_publications": [
            "Klangjai Sangwichitr, Thanawut Saengkassanee, Porntip Jirathumrong, Panern Intara, Sansanee Sangsuwan and Poom Cheechareon. (2019). A Comparison of Knowledge and Behaviors of Prince of Songkla University Students in Personal Financial Planning Before and After Attending Personal Finance Course. Hatyai Academic Journal 17(2). (pp. 127-141)."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_uthumrat_004",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "คณะวิทยาการจัดการ",
        "department_th": "คณะวิทยาการจัดการ",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Wongtawan",
        "last_name": "Uthumrat",
        "full_name": "Wongtawan Uthumrat",
        "full_name_th": "อ. วงศ์ตะวัน อุทุมรัตน์",
        "role": "อาจารย์ประจำ",
        "email": "wongtawan.u@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "เศรษฐศาสตรมหาบัณฑิต สาขาวิชาเศรษฐศาสตร์การเงิน สถาบันบัณฑิตพัฒนบริหารศาสตร์, 2563"
        ],
        "research_interests": [
            "การเงิน",
            "การลงทุน"
        ],
        "featured_publications": [
            "Wongtawan Uthumrat. (2019). The Relationship between Stock Return, Economic Value Added and Earning Per Share: Evidence from Corporate Governance Report of Thai Listed Companies (Excellent). The 11th National Graduate Research Conference (pp.680-689)."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
