# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1790398239_73c750)
EXTRACTED_FACULTIES = [
    {
        "id": "thammasatu_schoolofgl_vichitvadakan_001",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Nuntavarn",
        "last_name": "Vichit-Vadakan",
        "full_name": "Nuntavarn Vichit-Vadakan",
        "full_name_th": "ศ.ดร. นันทวัน วิจิตรกุลศการ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-ph-nuntavarn-vichit-vadakan/",
        "education": [
            "PH.D., UNIVERSITY OF CALIFORNIA AT LOS ANGELES"
        ],
        "research_interests": [
            "Public health",
            "tobacco control",
            "air pollution"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_pangsapa_002",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Piyasuda",
        "last_name": "Pangsapa",
        "full_name": "Piyasuda Pangsapa",
        "full_name_th": "ดร. ปิยสุดา ปังสะปา",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-piyasuda-pangsapa-2/",
        "education": [
            "University at Buffalo SUNY (Faculty at Global Gender Studies department)"
        ],
        "research_interests": [
            "Gender and development studies",
            "women and work",
            "comparative social and economic development",
            "qualitative and ethnographic research methods",
            "migration",
            "gender and sustainability",
            "social movements",
            "labor standards",
            "human rights",
            "metaverse technology in education"
        ],
        "featured_publications": [
            "Pangsapa, P. (2007). Textures of Struggle: The Emergence of Resistance among Garment Workers in Thailand. Cornell University Press.",
            "Liu, S., & Pangsapa, P. (2025). Island community-based tourism and gendered power: How respectability and paperwork organize women’s everyday authority in Phuket, Thailand. Tourism and Hospitality, 6(5), 281.",
            "Pangsapa, P. (2022). Vaccine policy failure: Explaining Thailand’s unsuccessful containment of COVID-19 in the third wave. Asian Journal of Law and Society, 1–17."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_klangboonkrong_003",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Yiarayong",
        "last_name": "Klangboonkrong",
        "full_name": "Yiarayong Klangboonkrong",
        "full_name_th": "ดร. เตีย ไกรบุญครอง",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-yiarayong-te-klangboonkrong/",
        "education": [
            "PgCert in Learning and Teaching in Higher Education, De Montfort University (UK), 2018",
            "PhD in Management, Cranfield University (UK), 2016",
            "MRes in Management Research, Cranfield University (UK), 2012",
            "MBA in Management of Technology, Asian Institute of Technology (Thailand), 2008",
            "BS in General Science (specialization in molecular biology), Kasetsart University (Thailand), 2005"
        ],
        "research_interests": [
            "Business strategy",
            "Academic entrepreneurship",
            "Inclusive entrepreneurship",
            "Disability entrepreneurship"
        ],
        "featured_publications": [
            "Lucas, G.J.M., Klangboonkrong, T. (2023) ‘A cautionary tale: Lessons from the strategic use of financial reporting’, in: Measuring Sustainability and CSR: From Reporting to Decision-Making, pp. 133-140.",
            "Baines, N., Klangboonkrong, T. & Smith, H.L. (2023) ‘Exploring product/service innovation process in UK: university spin-offs from practice-based lens’, Journal of Technology Transfer.",
            "Klangboonkrong, T. and Baines, N. (2022) ‘Disability entrepreneurship research: Critical reflection through the lens of individual-opportunity nexus’, Strategic Change, 31(4), pp. 427-445.",
            "Obara, L., Klangboonkrong, T., Chapman, G. and Frank, R. (2021) ‘From personal to professional: A reflective account of academics engaging with sustainability’, Personal Sustainability Practices, pp. 206-217."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_lucas_004",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Gerardus (Gertjan)",
        "last_name": "Lucas",
        "full_name": "Gerardus (Gertjan) Lucas",
        "full_name_th": "ดร. เกรดจัน ลูคัส",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-gerardus-lucas/",
        "education": [
            "Ph.D. in Strategy and Innovation, Tilburg University"
        ],
        "research_interests": [
            "Behavioral strategy",
            "Performance Feedback Theory",
            "Strategic decision making",
            "Sustainability"
        ],
        "featured_publications": [
            "Islam, S., Lucas, G. J. M., Paton, D. (2026). Adoption of digital strategy: the role of the top management team. Journal of Technology Transfer.",
            "Li, H., & Lucas, G. J. M. (2026). Interactive effects of multiple types of exogenous uncertainty and prior experience on strategic investment decisions: A real options perspective. Journal of Business Research, 208, 116081.",
            "Lucas, G. J. M. (2025). Performance Feedback Theory (Revised entry). In: Griffin, R. (ed.) Oxford Bibliographies in Management. Oxford University Press.",
            "Lucas, G. J. M., Knoben, j. & Meeus, M. T. H. (2018). Contradictory yet coherent? Inconsistency in performance feedback and R&D investment change. Journal of Management, 44(2), 658-681."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_virangkabutra_005",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Pisate",
        "last_name": "Virangkabutra",
        "full_name": "Pisate Virangkabutra",
        "full_name_th": "อ. พิศาล ไวรางกูร",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/pisate-virangkabutra/",
        "education": [
            "Ph.D. candidate, Doctor of Philosophy in Governance and Development, National Institute of Development Administration, Bangkok, Thailand, 2018 - present",
            "Master of Science in Human Centered Design (by thesis), King Mongkut University of Technology Thonburi, Bangkok, Thailand, 2008",
            "Bachelor of Design in Industrial Design, Royal Melbourne Institute of Technology, Melbourne, Australia, 1996"
        ],
        "research_interests": [
            "Service Design",
            "Design Thinking",
            "Toy and Play Design",
            "Sustainability",
            "Product Development",
            "Human Centered Design",
            "Social Innovation",
            "Toy and Play design",
            "Design for government"
        ],
        "featured_publications": [
            "Virangkabutra, P. Innovation shifts: Moving towards a sustainable system of design adoption in the Thai government. 2025, Springer, NY, USA",
            "Virangkabutra, P. (2018, April 25-26) Design thinking for the Thai public service excellence, Proceedings of the State Capacity for Public Sector reform and National Development in Southeast Asia and Korea, KRI-OPDC Reform Policy Symposium & Regional Workshop 2018, Hanoi, Vietnam. (pp.159-183)",
            "Virangkabutra, P. (2009, August 9-17) The Design of a Portaging Tool for Transporting Bicycles [Paper presentation]. The 17th Congress of the International Ergonomics Association Conference, Beijing, China"
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_jintamanaskoon_006",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Santi",
        "last_name": "Jintamanaskoon",
        "full_name": "Santi Jintamanaskoon",
        "full_name_th": "ดร. สันติ จินตมานัสกุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/santi-jintamanaskoon/",
        "education": [
            "Ph.D. (Management of Projects), University of Manchester, UK, 2016",
            "M.Sc. (International Construction Mg & Engineering), University of Leeds, UK, 2009",
            "B.A. (Civil), Thammasat University, 2005"
        ],
        "research_interests": [
            "Institutional and organizational change issues",
            "Energy transitions",
            "Case study and archival research"
        ],
        "featured_publications": [
            "Boundaries making of public-private partnerships: A historical account of British railways industry. Association of Researchers in Construction Management 2014 conference.",
            "Public-private partnerships, as a consequence, not a condition of reform: Unfolding historical events of British railways. Engineering Project Organization Conference 2014.",
            "Reform as remembering: exploring the continuities of the industry reform in the case of British railways. CIBWBC 2013 conference.",
            "Bridging over the troubled times: Re-assessing the routine reforming of the British railways industry. European Group of Organization Studies 2013 conference."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_gains_007",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Neil",
        "last_name": "Gains",
        "full_name": "Neil Gains",
        "full_name_th": "ดร. นิล เกนส์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-neil-gains/",
        "education": [
            "Ph.D., Dept of Food Science & Technology, University of Reading, UK, 1989",
            "B.A. (Hons) in Art"
        ],
        "research_interests": [
            "Psychology of sustainable consumption",
            "cross-cultural differences",
            "behavioural economics",
            "social psychology",
            "semiotics and visual communication"
        ],
        "featured_publications": [
            "Francisco, R. G., & Gains, N. (2026). Beyond persuasion: Influencers as facilitators of network-mediated diffusion of meat alternatives in Philippine social commerce. International Review on Public and Nonprofit Marketing.",
            "Doell, K. C., Todorova, B., Vlasceanu, M., Gains, N., et al. (2024). The International Climate Psychology Collaboration: Climate change-related data collected from 63 countries. Scientific Data, 11, 1066.",
            "Vlasceanu, M., Doell, K. C., Bak-Coleman, J. B., Gains, N., et al. (2024). Addressing climate change with behavioral science: A global intervention tournament in 63 countries. Science Advances, 10, eadj5778.",
            "Gains, N., & Ho, X.-N. T. (2023). Do plant-based food products communicate sustainability? A case study of brand meanings in Thailand. NIDA Case Research Journal, 15(1).",
            "Gains, N. (2013). Brand esSense: Using Sense, Symbol and Story to Design Brand Identity. London: Kogan Page."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_rousseau_008",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Stéphane P.",
        "last_name": "Rousseau",
        "full_name": "Stéphane P. Rousseau",
        "full_name_th": "อ.ดร. Stéphane P. Rousseau",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/stephane-p-rousseau/",
        "education": [
            "Master in Humanitarian, Development & International Cooperation, University of Paris 1 – La Sorbonne, France",
            "BA-equivalent in Humanitarian operations, Bioforce Institute, Lyon, France"
        ],
        "research_interests": [
            "Humanitarian assistance and operations",
            "development and international cooperation",
            "post-conflict reconstruction",
            "global health/health systems",
            "program and project management"
        ],
        "featured_publications": [
            "Tranches de vie d’un expat’ de l’humanitaire: Petits extraits de trente ans de missions et de vie en Asie du Sud-Est, Editions L’Harmattan, 2020",
            "Advertisement of antibiotics for upper respiratory infections and equity in access to treatment: a cross-sectional study in Nepal, Journal of Pharmaceutical Policy and Practice, 2020"
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_thisaphak_009",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Phithaksak",
        "last_name": "Thisaphak",
        "full_name": "Phithaksak Thisaphak",
        "full_name_th": "ดร. พิทักษ์ศักดิ์ ทิสภาคย์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-phitaksak-thisaphak/",
        "education": [
            "PH.D. (MEDIA STUDIES) - SOAS UNIVERSITY OF LONDON, UK (2015)",
            "M.A. (NEW MEDIA AND SOCIETY) - UNIVERSITY OF LEICESTER, UK (2010)",
            "B.A. (RADIO AND TELEVISION) - THAMMASAT UNIVERSITY (2000)"
        ],
        "research_interests": [
            "Digital cultures",
            "mediated participation",
            "communication for empowerment",
            "communications and media-related subjects"
        ],
        "featured_publications": [
            "Thisaphak, P. (2023). A Handbook for Detecting Disinformation. Bangkok: Broadcasting and Telecommunications Research and Development Fund for Public Interest.",
            "Phithaksak Thisaphak. (2021). Chapter 14: Innovation of Communication in the Digital Age. Nonthaburi: Sukothai Thammathirat Open University Press.",
            "Thisaphak, P. (2020). Thai Media Roles in Nostalgic Situation of Thailand’s Migrant Workers. Journal of Management Science Chiangrai Rajabhat University, 15(2), 67-91."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_vichitvadakan_010",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Viria",
        "last_name": "Vichit-Vadakan",
        "full_name": "Viria Vichit-Vadakan",
        "full_name_th": "อ. Viria Vichit-Vadakan",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/viria-vichit-vadakan/",
        "education": [
            "Master's of Business Administration, Harvard Business School",
            "Bachelor's degree, Stanford University",
            "Executive Coaching Certificate, Berkeley Executive Coaching Institute, UC Berkeley"
        ],
        "research_interests": [
            "Global Studies",
            "Social Entrepreneurship",
            "Leadership",
            "Education Technology",
            "AI in Education"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_tivayanondmongk_011",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Prapaporn",
        "last_name": "Tivayanond Mongkhonvanit",
        "full_name": "Prapaporn Tivayanond Mongkhonvanit",
        "full_name_th": "ผศ.ดร. ประภาภรณ์ ติวยานนท์ มงคลวนิช",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/prapaporn-tivayanond-mongkhonvanit/",
        "education": [
            "Doctor of Philosophy in Social Policy, UNIVERSITY OF OXFORD, UK (2012)",
            "Master of Arts"
        ],
        "research_interests": [
            "Welfare & Informal Sector",
            "Shared Values",
            "Asian Fair Trade",
            "Social Policy Innovation",
            "Sustainable Development Goals (SDGs) & Education"
        ],
        "featured_publications": [
            "Mongkhonvanit Tivayanond, P. An Alternative Narrative of Thailand’s Sustainable Development, Ministry of Higher Education, Research, Science and Innovation (MHESI)",
            "Mongkhonvanit Tivayanond, P. Mapping of Social Protection of Impact of Climate Change in Thailand in the book Understanding Human Security and Climate Change",
            "Mongkhonvanit, P. T. Managing Disaster Risk and Enabling Social Protection in Thailand: Some Lessons from the COVID-19 Pandemic, From the book Populations and Precarity during the COVID-19 Pandemic, ISEAS Yusof Ishak Publication",
            "Mongkhonvanit, P. T. การศึกษาเรื่อง Gig Economy และกิจการเจ้าของคนเดียว (Sole Proprietorship) กับนโยบายการส่งเสริมของรัฐบาล, ทุนจาก สานักงานส่งเสริมวิสาหกิจขนาดกลางและขนาดย่อม (The Office of SMEs Promotion: OSMEP",
            "ประภาภรณ์ ติวยานนท์ มงคลวนิช และคณะ (2018) การวิจัยประเมินผลกระบวนการได้มาซึ่งสมาชิกวุฒิสภา พศ 2561",
            "Mongkhonvanit Tivayanond, P. and Hanvoravongchai, The Impact of Universalization: A Case Study on Thailand’s Social Protection and Universal Health Coverage (Chapter 5) in Yi, I. (Ed.) Towards Universal Health Care in Emerging Economies,” Palgrave."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_rahman_012",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Shekh Mohammad Altafur",
        "last_name": "Rahman",
        "full_name": "Shekh Mohammad Altafur Rahman",
        "full_name_th": "ดร. เชค โมฮัมหมัด อัลตาฟูร์ ราห์มาน",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-shekh-mohammad-altafur-rahman/",
        "education": [
            "Doctoral degree in Human Rights and Peace Studies",
            "Master’s degree in Law",
            "Master’s degree in Human Rights and Social Development"
        ],
        "research_interests": [
            "Globalisation",
            "Human security",
            "Human rights"
        ],
        "featured_publications": [
            "Rahman, S. M. (2023). Thailand's SMARTS visa policy: Its compatibility with migrant entrepreneurship. In Proceedings of the Academy of International Business Southeast USA (AIB-SE) Annual Conference.",
            "Rahman, S.M. & Aree, S. (2022). Islamist Extremism after the Taliban Takeover: Development Trends in selected ASEAN-Countries, Country Study: Thailand. The Konrad-Adenauer-Stiftung.",
            "Rado, I. & Rahman, S.M. (2020). Exploring the Variety of Social Innovation Strategies: Case Studies from Thailand and Taiwan. In Asian Review, Vol. 33, No.1."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_kantaratanakul_013",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Sirasa",
        "last_name": "Kantaratanakul",
        "full_name": "Sirasa Kantaratanakul",
        "full_name_th": "ดร. สิริรสา กันตารัตนกุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-sirasa-kantaratanakul/",
        "education": [
            "Ph.D. (Environment, Development and Sustainability), Chulalongkorn University, Thailand, 2019",
            "M.B.A. (International Businesses), American College of Switzerland, Switzerland, 2007",
            "B.B.A. (Hotel Management), Schiller International University, UK & American College of Switzerland, Switzerland, 2006"
        ],
        "research_interests": [
            "Sustainability",
            "stakeholder management",
            "sustainable production and consumption",
            "sustainable lifestyles",
            "sustainable food systems"
        ],
        "featured_publications": [
            "Kantaratanakul, S., & Jarayabhand, P. (2019). Thailand’s Counter-IUU Fishing Policy: An Analysis of Stakeholder Perceptions. International Journal of Crime, Law and Social Issues, 6(2), 118–129."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_olemmon_014",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Matthew Eric",
        "last_name": "O’Lemmon",
        "full_name": "Matthew Eric O’Lemmon",
        "full_name_th": "ดร. แมทธิว เอริค โอเลมมอน",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-matthew-eric-olemmon/",
        "education": [
            "PH.D. (SOCIAL ANTHROPOLOGY), UNIVERSITY OF EDINBURGH, UK, 2010",
            "M.A. (ANTHROPOLOGY), CALIFORNIA STATE UNIVERSITY, USA, 2000",
            "B.A. (HISTORY), THE UNIVERSITY OF OKLAHOMA, USA, 1996"
        ],
        "research_interests": [
            "Post-war conflict",
            "Religious nationalism",
            "Role of technology in cultural change",
            "Consequences of digital innovation",
            "Lessons from pandemic experiences",
            "Buddhist practices and influence",
            "Natural disaster analysis",
            "Cultural and historical aspects of Southeast Asia"
        ],
        "featured_publications": [
            "O’Lemmon, Matthew. (2022). The Worst Mistake 2.0? The Digital Revolution and the Consequences of Innovation. In, AI & Society.",
            "O’Lemmon, Matthew. (2022). A Crude and Simple Calculus: Lessons for the CCP from Covid-19. In, Journal of Globalization Studies, vol. 13, no. 2.",
            "O’Lemmon, Matthew. (2022). Disease-Trap Diplomacy: China’s BRI and Southeast Asia. In, The Security Impacts of the COVID-19 Pandemic, pp. 57-67.",
            "O’Lemmon, Matthew. (2017). Analysis of the Legacy of Conflict among International Tourists in Vietnam. In, International Journal of Tourism Anthropology, vol. 6, no. 1, pp. 1-17.",
            "O’Lemmon, Matthew (2014). Merit-Making, Political Influence, and the Latent Ideal of the Buddhist Wat in Southwestern Cambodia. In, Journal of Current Southeast Asian Affairs, vol. 33, no. 2, pp. 27-57.",
            "O’Lemmon, Matthew. (2013). Spirit Cults and Practices in Kep Province, Cambodia. In, Journal of Southeast Asian Studies, vol. 45, no. 1, pp. 25-49.",
            "O’Lemmon, Matthew. (2012). Buddhist Identity and the 1973 Cambodian Buddhist Holy War. In, Asian Anthropology, vol. 11, pp. 121-138."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_dahiya_015",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Bharat",
        "last_name": "Dahiya",
        "full_name": "Bharat Dahiya",
        "full_name_th": "ดร. ภารัต ดาหิยะ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-bharat-dahiya/",
        "education": [],
        "research_interests": [
            "Sustainable urban development",
            "Sustainable urbanization",
            "Climate change",
            "Urban innovation",
            "Cultural landscapes",
            "Urban planning",
            "Community-led development",
            "Urban governance",
            "Planning and environment"
        ],
        "featured_publications": [
            "Dahiya, B., De Pascale, F., De Pietro, O., Farabollini, P., Lugeri, F.R., and Mercatanti, L. (Eds.) (2023) Disaster Resilience and Human Settlements: Emerging Perspectives in the Anthropocene, Springer Nature, Singapore",
            "Singh, R.S., Dahiya, B., Singh, A.K., and Poudel, P.C. (Eds.) (2022) Practising Cultural Geographies: Essays in Honour of Rana P. B. Singh, Springer Nature, Singapore",
            "Dahiya, Bharat and Das, Ashok (Eds.) (2020) New Urban Agenda in Asia-Pacific: Governance for Sustainable and Inclusive Cities, Springer Nature, Singapore",
            "Dahiya, B. and Okitasari, M. (2022) Accessing the Loss and Damage climate fund, Science, Vol. 378, No. 6626, p.1285"
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_phaovisaid_016",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Pearl",
        "last_name": "Phaovisaid",
        "full_name": "Pearl Phaovisaid",
        "full_name_th": "อ. Pearl Phaovisaid",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/pearl-phaovisaid/",
        "education": [
            "MBA (National Institute of Development Administration)",
            "MPhil, University of Cambridge",
            "BSc (US Military Academy)",
            "EdM, Harvard University",
            "Doctoral studies in management, Cambridge Judge Business School"
        ],
        "research_interests": [
            "Organizations",
            "Emotions and institutions",
            "Embodiment",
            "Extreme contexts",
            "Management studies",
            "Organizational theory"
        ],
        "featured_publications": [
            "Phaovisaid, P., de Rond, M. and Lok, J. (2022) “Organizational silence in total institutions: the enactment of emotional competence at war.” In: International Symposium on Process Organization Studies (PROS), Theme: Organizing on the Precipice: Process Studies in Extreme Contexts, 25-28 June 2022, Rhodes, Greece."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_mongkolnchaiara_017",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Jitti",
        "last_name": "Mongkolnchai-Aranya",
        "full_name": "Jitti Mongkolnchai-Aranya",
        "full_name_th": "ดร. จิติ มงคลชัยอรัญญา",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-jitti-mongkolnchai-aranya/",
        "education": [
            "Ph.D. in Urban environmental management",
            "M.Sc. in Rural Regional Planning",
            "Diploma in Social Rural Leadership Development",
            "B.SW. in Social Work"
        ],
        "research_interests": [
            "Community empowerment",
            "civil society organization development & networking",
            "promotion of social innovation and appropriate technology",
            "agricultural extension",
            "project planning & management"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_vanberkel_018",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Rene",
        "last_name": "Van Berkel",
        "full_name": "Rene Van Berkel",
        "full_name_th": "ดร. เรอเน แวน เบอร์เคล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/dr-rene-van-berkel/",
        "education": [
            "PhD (Environmental Science), University of Amsterdam (The Netherlands), 1996",
            "MAgrSci (Environmental Hygiene), Wageningen Agricultural University (The Netherlands), 1988",
            "BAgriSci (Environmental Hygiene), Wageningen Agricultural University (The Netherlands), 1985"
        ],
        "research_interests": [
            "Circular economy and resource efficiency",
            "Sustainable development and sustainability science",
            "Responsible business and sustainability management",
            "Cleantech innovation",
            "Responsible entrepreneurship"
        ],
        "featured_publications": [
            "Van Berkel, R, (2023), Circular Manufacturing Transformation: manufacturing perspectives, examples and experiences from implementation of Circular Economy in Asia, in Ghosh, S.K and S.K. Ghosh (eds), Advancing Circular Economy: catalysing decarbonisation through policy instruments, pg 269-299, Springer Publishers, Singapore",
            "Fadeeva, Z & Van Berkel, R (2023), Towards Circular Economy of Food Systems: An Explorative Appraisal of Opportunities in Fish, Seafood Value Chains. In: Narula, S.A., Raj, S.P. (eds) Sustainable Food Value Chain Development. Pg 61-86, Springer Nature, Singapore",
            "Fadeeva, Z, and Van Berkel, R, (2021), Unlocking circular economy for prevention of marine plastic pollution: An exploration of G20 policy and initiatives, Journal of Environmental Management, Volume 227"
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "thammasatu_schoolofgl_rerkbunche_019",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "School of Global Studies",
        "faculty_th": "วิทยาลัยโลกคดีศึกษา",
        "department": "วิทยาลัยโลกคดีศึกษา",
        "department_th": "วิทยาลัยโลกคดีศึกษา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "RAYNU",
        "last_name": "RERKBUNCHE",
        "full_name": "RAYNU RERKBUNCHE",
        "full_name_th": "อ. RAYNU RERKBUNCHE",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://sgs.tu.ac.th/faculty_members/raynu-rerkbunche/",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
