# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1790398091_ea0bfc)
EXTRACTED_FACULTIES = [
    {
        "id": "princeofso_facultyofm_jindabot_001",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "วิชาเอกการตลาดและการสื่อสาร",
        "department_th": "วิชาเอกการตลาดและการสื่อสาร",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Teerasak",
        "last_name": "Jindabot",
        "full_name": "Teerasak Jindabot",
        "full_name_th": "ผศ.ดร. ธีรศักดิ์ จินดาบถ",
        "role": "อาจารย์ประจำ",
        "email": "teerasak.j@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "กต.ด. (การตลาด), มหาวิทยาลัยธรรมศาสตร์, 2550"
        ],
        "research_interests": [
            "การตลาดดิจิทัล",
            "จิตวิทยาการตลาดและผู้บริโภค",
            "การพัฒนามาตรทางการตลาด"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_sukhaphol_002",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "วิชาเอกการตลาดและการสื่อสาร",
        "department_th": "วิชาเอกการตลาดและการสื่อสาร",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Sasiwemon",
        "last_name": "Sukhaphol",
        "full_name": "Sasiwemon Sukhaphol",
        "full_name_th": "รศ.ดร. ศศิวิมล สุขบท",
        "role": "อาจารย์ประจำ",
        "email": "sasiwemon.s@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. การจัดการ Universiti Utara Malaysia, Malaysia, 2558"
        ],
        "research_interests": [
            "การตลาดสินค้าเกษตรกรรม",
            "การตลาดผลิตภัณฑ์ชุมชน",
            "การสร้างตราสินค้า"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_supphonkunnanan_003",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "วิชาเอกการตลาดและการสื่อสาร",
        "department_th": "วิชาเอกการตลาดและการสื่อสาร",
        "academic_title": "รศ.",
        "academic_title_th": "รศ.",
        "first_name": "Laphassawat",
        "last_name": "Supphonkunnanan",
        "full_name": "Laphassawat Supphonkunnanan",
        "full_name_th": "รศ. ลภัสวัฒน์ ศุภผลกุลนันทร์",
        "role": "อาจารย์ประจำ",
        "email": "laphassawat.s@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "บธ.ม. (การตลาด), ม.รังสิต, 2549"
        ],
        "research_interests": [
            "ที่ปรึกษาและการพัฒนาตลาด",
            "การวางแผนการตลาด",
            "การจัดและบริหารงานโครงสร้างองค์กร",
            "การตลาดอสังหาริมทรัพย์"
        ],
        "featured_publications": [
            "วีระวรรณ ศิริพงษ์.(2560). การใช้บัญชีบริหารของวิสาหกิจขนาดกลางและขนาดย่อม จังหวัดสงขลา.วารสารหาดใหญ่วิชาการ, 15(1), 59-72.",
            "วีระวรรณ ศิริพงษ์,กมลรัตน์ สฤษฎีพีรพันธุ์ และมัทนชัย สุทธิพันธุ์.(2561).อิทธิพลของกระแสเงินสด ต่อความสามารถในการทำกำไร และมูลค่าหลักทรัพย์ตามราคาตลาด กรณีศึกษา ตลาดหลักทรัพย์ เอ็ม เอ ไอ (MAI). วารสารมหาวิทยาลัยนราธิวาสราชนครินทร์, 5(2), 111-120.",
            "วีระวรรณ ศิริพงษ์ ,ณัฏฐณิชา คล้ายแก้ว,ตติยา แซ่เจีย,ปิยรัตน์ ไชยถาวร ,สุดารัตน์ บุตรจริยะและมัทนชัย สุทธิพันธุ์,(2562). ความสัมพันธ์ระหว่างความรับผิดชอบต่อสังคมกับคุณภาพกำไรของธุรกิจโรงแรมในจังหวัดสงขลา. วารสารเทคโนโลยีภาคใต้, 12(1), 129-137.",
            "Muttanachai Suttipun, Weerawan Siripong, On-anong Sattayarak, Jittima Wichianrak, and Sutira Limroscharoen, (2018). The Influence of Enterprise Risk Management on Firm Performance Measured by the Balanced Scorecard: Evidence from SMEs in Southern Thailand. ASR: CMU Journal of Social Sciences and Humanities (2018), 5(1), 33-53.",
            "วีระวรรณ ศิริพงษ์, นิตินันท์ พราหมหันต์, ปนัดฐา พิมพกาญจน์, จิราภรณ์ ปัญญายิ่ง, สุชาวดี แสงศรี, อิศรา มาลาวัยจันทร์, และมัทนชัย สุทธิพันธุ์, (2562). ความสัมพันธ์ระหว่างการเปิดเผยข้อมูลการวิจัยและพัฒนา และผลการดำเนินงานทางการเงินของบริษัทจดทะเบียนในตลาดหลักทรัพย์แห่งประเทศไทย. วารสารบริหารธุรกิจเทคโนโลยีมหานคร, 16(2), 173-190.",
            "วีระวรรณ ศิริพงษ์, มัทนชัย สุทธิพันธุ์, ปทุมพร หิรัญสาลี, และลักขณา ดำชู, (2563). ความสัมพันธ์ระหว่างการปฏิบัติตามหลักปรัชญาเศรษฐกิจพอเพียง และผลการดำเนินงานของธุรกิจด้วยการวัดผลเชิงดุลยภาพ : กรณีศึกษาธุรกิจขนาดกลางและย่อมในจังหวัดสงขลา. วารสารวิทยาการจัดการ มหาวิทยาลัยราชภัฏ เชียงราย, 15(1), 134-153."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_laparojkit_004",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "วิชาเอกการตลาดและการสื่อสาร",
        "department_th": "วิชาเอกการตลาดและการสื่อสาร",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Sumana",
        "last_name": "Laparojkit",
        "full_name": "Sumana Laparojkit",
        "full_name_th": "ผศ.ดร. สุมนา ลาภาโรจน์กิจ",
        "role": "อาจารย์ประจำ",
        "email": "sumana.l@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. (Marketing and Strategy) Cardiff University U.K., 2554"
        ],
        "research_interests": [
            "Marketing & Strategy",
            "Consumer Behavior",
            "Brand Community",
            "Branding"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "princeofso_facultyofm_chanchaichujit_005",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "วิชาเอกการตลาดและการสื่อสาร",
        "department_th": "วิชาเอกการตลาดและการสื่อสาร",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Kanruthai",
        "last_name": "Chanchaichujit",
        "full_name": "Kanruthai Chanchaichujit",
        "full_name_th": "อ. กันต์ฤทัย ชาญชัยชูจิต",
        "role": "อาจารย์ประจำ",
        "email": "kanruthai.c@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "M.A. (Marketing), University of Hertfordshire, U.K., 2552"
        ],
        "research_interests": [
            "Tourism Marketing",
            "Sustainable Marketing"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
