# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789641426_ff2b37)
EXTRACTED_FACULTIES = [
    {
        "id": "chulalongk_facultyofs_fac_001_001",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Sports Science",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬา",
        "department": "คณะวิทยาศาสตร์การกีฬา",
        "department_th": "คณะวิทยาศาสตร์การกีฬา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Kanang",
        "last_name": "",
        "full_name": "Kanang",
        "full_name_th": "ผศ.ดร. คนางค์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
