# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789639225_30e740)
EXTRACTED_FACULTIES = [
    {
        "id": "silpakornu_facultyofi_eiamsaard_001",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Information and Communication Technology",
        "faculty_th": "คณะเทคโนโลยีสารสนเทศและการสื่อสาร",
        "department": "คณะเทคโนโลยีสารสนเทศและการสื่อสาร",
        "department_th": "คณะเทคโนโลยีสารสนเทศและการสื่อสาร",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Manop",
        "last_name": "Eiamsa-ard",
        "full_name": "Manop Eiamsa-ard",
        "full_name_th": "ผศ. มานพ เอี่ยมสะอาด",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://ict.su.ac.th/?page_id=58",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
