# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789647214_b66b64)
EXTRACTED_FACULTIES = [
    {
        "id": "kasetsartu_kapi_suphamitmongkol_001",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "KAPI",
        "faculty_th": "สถาบัน KAPI",
        "department": "",
        "department_th": "",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Varawut",
        "last_name": "Suphamitmongkol",
        "full_name": "Varawut Suphamitmongkol",
        "full_name_th": "ดร. วราวุฒิ ศุภมิตรมงคล",
        "role": "อาจารย์ประจำ",
        "email": "aapwws@ku.ac.th",
        "image_url": "",
        "profile_url": "https://kapi.ku.ac.th/topics/personnel/aapwws",
        "education": [
            "2541 ปริญญาตรี วิทยาศาสตรบัณฑิต สาขาพัฒนาผลิตภัณฑ์อุตสาหกรรมเกษตร มหาวิทยาลัยเกษตรศาสตร์",
            "2545 ปริญญาโท วิทยาศาสตรมหาบัณฑิต สาขาอินเตอร์เน็ตเทคโนโลยีและพาณิชย์อิเล็กทรอนิกส์ มหาวิทยาลัยอัสสัมชัญ",
            "2556 ปริญญาเอก Ph.D. in Management Science and Engineering (Data Mining) University of Chinese Academy of Sciences, Beijing China"
        ],
        "research_interests": [
            "Data mining และการจัดการฐานข้อมูล",
            "ออกแบบและพัฒนาเว็บไซต์",
            "วิเคราะห์ระบบและบริหารจัดการระบบสารสนเทศ",
            "การประเมินวัฏจักรผลิตภัณฑ์และคาบอร์นฟุตพริ้นต์ (LCA,CFP)",
            "การตลาด และการพัฒนาผลิตภัณฑ์อุตสาหกรรมเกษตร"
        ],
        "featured_publications": [
            "N.Assavasirijinda, P.Vaithanomsat, S.Liengprayoon, M.Haruthaithanasan, S.Witayakran, W.Wannarat, W.Thanapase, W.Suphamitmongkol. Bioeconomy Policies in the G7, the EU, Asia-Pacific and Thailand. The Proceeding of ASEAN Bioenergy and Bioeconomy Conference. 2017. 1,1:p.43-48.",
            "T.Chowwanonthapunya, S.Piriyawat, W.Suphamitmongkol. An Economic Consideration Guideline for the Selection of Corrosion – Control Strategies. Srinakharinwirot Engineering Journal.2016.11,2:p.133-139.",
            "ธีร์ เชาวนนทปัญญา, ชัยวัฒน์ พีระทัตสุวรรณ, วราวุฒิ ศุภมิตรมงคล. 2558. การกัดกร่อนของเหล็กกล้าภายใต้สภาวะบรรยากาศก๊าซคาร์บอนไดอ็อกไซด์ของอุตสาหกรรมผลิตน้ำมันและก๊าซ: กลไกและการทำนายการกัดกร่อน. วารสารวิชาการปทุมวัน ปีที่ 5 ,14: น.31-41",
            "W. Suphamitmongkol, G. Nie, R. Liu, and Y. Shi, Classification for Orange Varieties Using Near Infrared Spectroscopy. in Data Mining Workshops (ICDMW), 2011 IEEE 11th International Conference on Data Mining. 2011. Canada: IEEE.",
            "P. Yomwan, C. Cao, J. Zhao, R. Tian, and W. Suphamitmongkol, Epidemic risk assessment of acute watery diarrhea for the 2011 Ayutthaya flood disaster using remote sensing and water quality, in The 33rd Asian Conference On Remote Sensing. 2012: Chonburi, Thailand.",
            "W. Suphamitmongkol, G. Nie, R. Liu, S. Kasemsumran, and Y. Shi, An alternative approach for the classification of orange varieties based on near infrared spectroscopy. Computers and Electronics in Agriculture, 2013. 91: p. 87-93.",
            "F. Wang, W. Suphamitmongkol, and B. Wang, Advertisements click-through rate prediction using multiple criteria linear programming regression model, Procedia Computer Science, 2013. 17:p. 803-811.",
            "V.J.Bruckman, M.Haruthaithanasan, F.Kraxner, R.Miller, A.Darabant, G.Choumnit, S.Thongmanivong, Memh Ko Ko Gyi, W.Suphamitmongkol. ACMECS BIOENERGY 2015: Three Years of Efforts Towards a Regional Bioenergy Network. IUFRO Occasional Paper No. 31. 2016. 31:p.1-29."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_kapi_rerksamran_002",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "KAPI",
        "faculty_th": "สถาบัน KAPI",
        "department": "สถาบัน KAPI",
        "department_th": "สถาบัน KAPI",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Tucksin",
        "last_name": "Rerksamran",
        "full_name": "Tucksin Rerksamran",
        "full_name_th": "อ. นายทักษิณ ฤกษ์สำราญ",
        "role": "อาจารย์ประจำ",
        "email": "tucksin.l@ku.ac.th",
        "image_url": "",
        "profile_url": "https://kapi.ku.ac.th/topics/personnel/aaptsl",
        "education": [
            "2546 ปริญญาตรี",
            "2553 ปริญญาโท"
        ],
        "research_interests": [
            "เคมี"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_kapi_banjong_003",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "KAPI",
        "faculty_th": "สถาบัน KAPI",
        "department": "",
        "department_th": "",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Yutthana",
        "last_name": "Banjong",
        "full_name": "Yutthana Banjong",
        "full_name_th": "อ. นายยุทธนา บรรจง",
        "role": "อาจารย์ประจำ",
        "email": "aapynb@ku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "2546 ปริญญาตรี สาขาพฤกษศาสตร์, มหาวิทยาลัยเกษตรศาสตร์",
            "2553 ปริญญาโท สาขาพัฒนาผลิตภัณฑ์อุตสาหกรรมเกษตร, มหาวิทยาลัยเกษตรศาสตร์"
        ],
        "research_interests": [
            "พืชพลังงาน",
            "ชีวมวล",
            "การใช้ประโยชน์จากพืช"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_kapi_thanawat_004",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "KAPI",
        "faculty_th": "สถาบัน KAPI",
        "department": "สถาบัน KAPI",
        "department_th": "สถาบัน KAPI",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Ekapong",
        "last_name": "Thanawat",
        "full_name": "Ekapong Thanawat",
        "full_name_th": "อ. นายเอกพงษ์ ธนะวัติ",
        "role": "อาจารย์ประจำ",
        "email": "appept@ku.ac.th",
        "image_url": "",
        "profile_url": "https://kapi.ku.ac.th/topics/personnel/aapept",
        "education": [
            "2550 ปริญญาตรี สาขาวนศาสตร์, มหาวิทยาลัยเกษตรศาสตร์",
            "2556 ปริญญาโท สาขาวนศาสตร์ (เทคโนโลยีวรวัฒน์), มหาวิทยาลัยเกษตรศาสตร์"
        ],
        "research_interests": [
            "Biomass bioenergy and forest plantation"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_kapi_umamanit_005",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "KAPI",
        "faculty_th": "สถาบัน KAPI",
        "department": "",
        "department_th": "",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Thotsaphon",
        "last_name": "Umamanit",
        "full_name": "Thotsaphon Umamanit",
        "full_name_th": "อ. นายทศพล อุมะมานิต",
        "role": "อาจารย์ประจำ",
        "email": "aapthu@ku.ac.th",
        "image_url": "",
        "profile_url": "https://kapi.ku.ac.th/topics/personnel/aapthu",
        "education": [
            "2555 ปริญญาตรี วท.บ. (สาขาวิชาพืชสวน) สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหาร ลาดกระบัง",
            "2560 ปริญญาโท วท.ม. (ส่งเสริมการเกษตร) มหาวิทยาลัยเกษตรศาสตร์"
        ],
        "research_interests": [
            "เทคโนโลยีการเพาะเลี้ยงเนื้อเยื่อพืช",
            "เทคโนโลยีเนียร์อินฟราเรด",
            "การจัดการความรู้",
            "การถ่ายทอดเทคโนโลยี",
            "การส่งเสริมการเกษตร",
            "การสื่อสารและการประชาสัมพันธ์"
        ],
        "featured_publications": [
            "Punlapa Vutdhipapornkul , Siriorn Anootthato , Weerasin Sonjaroon , Pattama Tongkok and Thotsaphon Umamanit . Development of soap bar from water chestnut peel in Suphan Buri province for sustainable income and quality of life improvement for the community. ASEAN Bioenergy and Bioeconomy Conference 2023. No.1 Vol. 6.",
            "Punlapa Vutdhipapornkul, Siriorn Anootthato, Weerasin Sonjaroon, Patcharavadee Sriboonruang, Tanin Kongsila, Pattama Tongkok, Gadewara Matmarurat and Thotsaphon Umamanit , Enhancing skin care efficacy: Innovating rock salt scrub infused with Thai herbals for optimal benefits. ASEAN Bioenergy and Bioeconomy Conference 2024. No.1 Vol. 7.",
            "ทศพล อุมะมานิต , ณัฐภรณ์ สุทธิวิจิตรภักดี, ศุมาพร เกษมสำราญ, สุธีรา วิทยากาญจน์, มะลิวัลย์ หฤทัยธนาสันติ์, “การวิเคราะห์ปริมาณโฮโลเซลลูโลสในไผ่หวานอ่างขางโดยวิธีอินฟราเรดย่านใกล้”,เกษตรพระจอมเกล้า, ปีที่ 33, ฉบับพิเศษ 1, พฤศจิกายน 2015, หน้า 858-863."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_kapi_harutaitanasan_006",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "KAPI",
        "faculty_th": "สถาบัน KAPI",
        "department": "",
        "department_th": "",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Kasem",
        "last_name": "Harutaitanasan",
        "full_name": "Kasem Harutaitanasan",
        "full_name_th": "อ. นายเกษม หฤทัยธนาสันติ์",
        "role": "อาจารย์ประจำ",
        "email": "aapksh@ku.ac.th",
        "image_url": "",
        "profile_url": "https://kapi.ku.ac.th/topics/personnel/aapksh",
        "education": [
            "2539 ปริญญาตรี วศ.บ.( วิศวกรรมเคมี) มหาวิทยาลัยเกษตรศาสตร์",
            "2544 ปริญญาโท วศ.ม.( วิศวกรรมเคมี) จุฬาลงกรณ์มหาวิทยาลัย"
        ],
        "research_interests": [
            "การใช้ประโยชน์จากชีวมวลเพื่อพลังงาน"
        ],
        "featured_publications": [
            "มะลิวัลย์ หฤทัยธนาสันติ์ , เกษม หฤทัยธนาสันติ์ , เอกพงษ์ ธนะวัติ , ศักดา พรมเลิศ, เอกชัย บ่ายแสงจันทร์. 2553. ศักยภาพของกระถินยักษ์ ยูคาลิปตัส กระถินเทพา และกระถินเทพณรงค์ในการปลูกเป็นสวนป่าพืชพลังงาน. น.579-586. ใน เอกสารประกอบการประชุมทางวิชาการของมหาวิทยาลัยเกษตรศาสตร์ ครั้งที่ 48 วันที่ 3-5 กุมภาพันธ์ 2553. มหาวิทยาลัยเกษตรศาสตร์, กรุงเทพ ฯ",
            "ยุทธนา บรรจง, มะลิวัลย์ หฤทัยธนาสันติ์, เกษม หฤทัยธนาสันติ์ , วิชัย หฤทัยธนาสันติ์ . 2553. สมรรถภาพการเจริญเติบโตและผลผลิตของฟักข้าวแหล่งพันธุ์ไทยและเวียดนามในการเก็บเกี่ยวปีแรก. น.1-4. ใน เอกสารประกอบการประชุมวิชาการประชุมวิชาการและเสนอผลงานวิจัยพืชเขตร้อนและกึ่งร้อน ครั้งที่ 4 วันที่ 22-23 กรกฎาคม 2553. กรุงเทพ."
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
