# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789647388_8e210b)
EXTRACTED_FACULTIES = [
    {
        "id": "kingmongku_facultyofi_thong_001",
        "university": "King Mongkut's University of Technology North Bangkok",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ",
        "faculty": "Faculty of Industrial Technology",
        "faculty_th": "คณะเทคโนโลยีอุตสาหกรรม",
        "department": "สำนักพัฒนาเทคโนโลยีเพื่ออุตสาหกรรม",
        "department_th": "สำนักพัฒนาเทคโนโลยีเพื่ออุตสาหกรรม",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Chatrchan",
        "last_name": "Thong",
        "full_name": "Chatrchan Thong",
        "full_name_th": "รศ.ดร. ฉัตรชาญ ทองจับ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "ESG"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
