"""Wave26 Batch C checkpoint-only export (wu_allied) — 2026-09-17.
sitemap_locs=2570 p_or_pageid=601; samples: https://sah.wu.ac.th/?page_id=17274 -> title='Page not found - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์' len=126586 dens=12 snip=' Page not found - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์ {"@context":"https:\/\/schema.org","@gr'; https://sah.wu.ac.th/?page_id=17219 -> title='สโมสรนักศึกษาสำนักวิชาสหเวชศาสตร์ - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์' len=149776 dens=12 snip=' สโมสรนักศึกษาสำนักวิชาสหเวชศาสตร์ - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์ {"@context":"https:\'; https://sah.wu.ac.th/?page_id=17200 -> title='สรุปมติที่ประชุมบริหาร มวล. - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์' len=139698 dens=12 snip=' สรุปมติที่ประชุมบริหาร มวล. - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์ {"@context":"https:\/\/sch'; https://sah.wu.ac.th/?page_id=17174 -> title='ศูนย์ความเป็นเลิศ (Center of Excellence) - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์' len=141184 dens=12 snip=' ศูนย์ความเป็นเลิศ (Center of Excellence) - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์ {"@context":"'; https://sah.wu.ac.th/?p=17133 -> title='นางสาวณิชาภัทร พันธ์โภชน์ นักศึกษาสาขาวิชาเทคนิคการแพทย์ เข้ารับเข็มเกียรติยศ และประกาศนียบัตรเชิดชูเกียรติ ผู้มีผลการศึ' len=152359 dens=21 snip=' นางสาวณิชาภัทร พันธ์โภชน์ นักศึกษาสาขาวิชาเทคนิคการแพทย์ เข้ารับเข็มเกียรติยศ และประกาศนียบัตรเชิดช'; https://sah.wu.ac.th/?p=17121 -> title='Page not found - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์' len=126574 dens=12 snip=' Page not found - สำนักวิชาสหเวชศาสตร์ มหาวิทยาลัยวลัยลักษณ์ {"@context":"https:\/\/sc
Verified count in body: 2 (no invented names, NO DB commit).

PROVENANCE NOTE: 2 profiles (Asst Prof Salinee Chaikool / Suphattra Chaiban, physiotherapy) derive from a single official news article https://sah.wu.ac.th/?p=16991 (school lecturers serving as physios at university games); titles match article text. No roster page, no emails/profiles - downstream ingestion should treat as weak/news-derived.
"""
# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789654089_f2db69)
EXTRACTED_FACULTIES = [
  {
    "id": "walailakun_schoolofal_chaikool_001",
    "university": "Walailak University",
    "university_th": "มหาวิทยาลัยวลัยลักษณ์",
    "faculty": "School of Allied Health Sciences",
    "faculty_th": "สำนักวิชาสหเวชศาสตร์",
    "department": "สาขาวิชากายภาพบำบัด สำนักวิชาสหเวชศาสตร์",
    "department_th": "สาขาวิชากายภาพบำบัด สำนักวิชาสหเวชศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Salinee",
    "last_name": "Chaikool",
    "full_name": "Salinee Chaikool",
    "full_name_th": "ผศ.ดร. สาลินี ไชยกูล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "กายภาพบำบัด",
      "การรักษาอาการบาดเจ็บจากการกีฬา"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "walailakun_schoolofal_chaiban_002",
    "university": "Walailak University",
    "university_th": "มหาวิทยาลัยวลัยลักษณ์",
    "faculty": "School of Allied Health Sciences",
    "faculty_th": "สำนักวิชาสหเวชศาสตร์",
    "department": "สาขาวิชากายภาพบำบัด สำนักวิชาสหเวชศาสตร์",
    "department_th": "สาขาวิชากายภาพบำบัด สำนักวิชาสหเวชศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Suphattra",
    "last_name": "Chaiban",
    "full_name": "Suphattra Chaiban",
    "full_name_th": "ผศ. สุพัตรา ไชยบาล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "กายภาพบำบัด",
      "การรักษาอาการบาดเจ็บจากการกีฬา"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
