# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789697332_ad457c)
EXTRACTED_FACULTIES = [
    {
        "id": "kingmongku_schoolofen_karcharnubarn_001",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "School of Engineering",
        "faculty_th": "วิทยาลัยประชากรศาสตร์",
        "department": "วิทยาลัยประชากรศาสตร์",
        "department_th": "วิทยาลัยประชากรศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Rukchanok",
        "last_name": "Karcharnubarn",
        "full_name": "Rukchanok Karcharnubarn",
        "full_name_th": "ผศ.ดร. รัชนก คชารุ바นทร์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "Demographic Research",
            "Population Data Survey Methods"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
