"""Wave27 Batch C checkpoint-only export (mfu_law). static_verified=1 (2 agent rows, 1 corrupt dup dropped by hygiene filter, survivor deep-merged). en_links=19 browser_rendered=0. Official *.ac.th only, NO DB commit."""
# Auto-generated by SKILL.state FacultyExtractionAgent (Session: wave27_mfu_law)
EXTRACTED_FACULTIES = [
    {
        "id": "maefahluan_schoolofla_noichim_001",
        "university": "Mae Fah Luang University",
        "university_th": "มหาวิทยาลัยแม่ฟ้าหลวง",
        "faculty": "School of Law",
        "faculty_th": "สำนักวิชานิติศาสตร์",
        "department": "สำนักวิชานิติศาสตร์",
        "department_th": "สำนักวิชานิติศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Chukiat",
        "last_name": "Noichim",
        "full_name": "Chukiat Noichim",
        "full_name_th": "รศ.ดร. ชูเกียรติ น้อยฉิม",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "https://law.mfu.ac.th/en/",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
