# Auto-generated by SKILL.state FacultyExtractionAgent (Session: wave33_mu_ss)
# Hygiene pass: script-contamination_drop=0; scoped_to_sport_school_only (other-faculty deans excluded)
EXTRACTED_FACULTIES = [
    {
        "id": "mahidoluni_collegeofs_udomphorn_007",
        "university": "Mahidol University",
        "university_th": "มหาวิทยาลัยมหิดล",
        "faculty": "College of Sports Science and Technology",
        "faculty_th": "วิทยาลัยวิทยาศาสตร์และเทคโนโลยีการกีฬา",
        "department": "College of Sports Science and Technology",
        "department_th": "College of Sports Science and Technology",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Yuthana",
        "last_name": "Udomphorn",
        "full_name": "Yuthana Udomphorn",
        "full_name_th": "ผศ. Yuthana Udomphorn",
        "role": "อาจารย์ประจำ",
        "email": "deanss@mahidol.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
