"""Wave25 Batch A checkpoint-only export (wu_allied) — 2026-09-17.
Sitemap: sitemap.xml ok:2570 locs (flat ?page_id=/?p=/?iwp_log=, 0 strict staff-keyword hits), wp-sitemap malformed, robots.txt 404.
Seeds (official *.ac.th only): ['https://sah.wu.ac.th/', 'https://www.wu.ac.th/'].
Verified count in body: 0 (no OCR, no invented names, NO DB commit).
Source: spa_wu_allied_export.py.
"""
# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789647200_bb65d2)
EXTRACTED_FACULTIES = []
