# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789733119_14fee8)
# Wave37 NU SGtech CV enrichment: 15 CV links followed, 0 NEW (15/15 already-known by email+EN fuzzy>=90).
# Enrichment deltas (education/research/publications) retained in extract_1789733119_14fee8.json checkpoint. NO DB commit.
EXTRACTED_FACULTIES = []
