"""Wave27 Batch C checkpoint-only export (ubu_sci). static_verified=1 roster_links=1 browser_rendered=0. Official *.ac.th only, NO DB commit."""
# Auto-generated by SKILL.state FacultyExtractionAgent (Session: wave27_ubu_sci)
EXTRACTED_FACULTIES = [
    {
        "id": "ubonratcha_facultyofs_jarujarus_001",
        "university": "Ubon Ratchathani University",
        "university_th": "มหาวิทยาลัยอุบลราชธานี",
        "faculty": "Faculty of Science",
        "faculty_th": "คณะวิทยาศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Purim",
        "last_name": "Jarujarus",
        "full_name": "Purim Jarujarus",
        "full_name_th": "ศ.ดร. ปุริม จารุจำรัส",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
