"""Wave25 Batch A checkpoint-only export (nu_sci) — 2026-09-17.
Sitemap: all sitemaps 404/DNS-fail (sci/math/chemistry/compsci...), robots.txt 404, sitemap_index.xml 404.
Seeds (official *.ac.th only): ['https://www.sci.nu.ac.th/', 'https://chemistry.sci.nu.ac.th/', 'https://www.nu.ac.th/'].
Verified count in body: 0 (no OCR, no invented names, NO DB commit).
Source: spa_nu_sci_export.py.
"""
# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789647251_f2fb70)
EXTRACTED_FACULTIES = []
