# Auto-generated by SKILL.state FacultyExtractionAgent (Session: extract_1789709755_d7f314)
EXTRACTED_FACULTIES = [
    {
        "id": "khonkaenun_facultyofh_songpan_001",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Humanities and Social Sciences",
        "faculty_th": "คณะมนุษยศาสตร์และสังคมศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Wararat",
        "last_name": "Songpan",
        "full_name": "Wararat Songpan",
        "full_name_th": "รศ.ดร. วรารัตน์ สงฆ์แป้น",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "AI",
            "Quantum"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
