# Auto-generated by SKILL.state FacultyExtractionAgent (Session: wave27_su_ict)
EXTRACTED_FACULTIES = [
    {
        "id": "silpakornu_facultyofi_iamsat_001",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Information and Communication Technology",
        "faculty_th": "คณะเทคโนโลยีสารสนเทศและการสื่อสาร",
        "department": "",
        "department_th": "",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Manop",
        "last_name": "Iamsat",
        "full_name": "Manop Iamsat",
        "full_name_th": "ผศ. มานพ เอี่ยมสะอาด",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
