# Auto-generated by SKILL.state FacultyExtractionAgent (Session: wave27_nida_env)
EXTRACTED_FACULTIES = [
    {
        "id": "nationalin_graduatesc_pongpiachan_001",
        "university": "National Institute of Development Administration",
        "university_th": "สถาบันบัณฑิตพัฒนบริหารศาสตร์",
        "faculty": "Graduate School of Environmental Development Administration",
        "faculty_th": "คณะบริหารการพัฒนาสิ่งแวดล้อม",
        "department": "",
        "department_th": "",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Siwatt",
        "last_name": "Pongpiachan",
        "full_name": "Siwatt Pongpiachan",
        "full_name_th": "ศ.ดร. สิวัฒน์ พงษ์เพียจันทร์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "PM 2.5",
            "Environmental Science"
        ],
        "featured_publications": [
            "Conversation with Prof. Dr. Siwatt Pongpiachan about Thailand’s PM 2.5 situation"
        ],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "nationalin_graduatesc_siriborvornrata_002",
        "university": "National Institute of Development Administration",
        "university_th": "สถาบันบัณฑิตพัฒนบริหารศาสตร์",
        "faculty": "Graduate School of Environmental Development Administration",
        "faculty_th": "คณะบริหารการพัฒนาสิ่งแวดล้อม",
        "department": "Graduate School of Applied Statistics",
        "department_th": "Graduate School of Applied Statistics",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Thitirat",
        "last_name": "Siriborvornratanakul",
        "full_name": "Thitirat Siriborvornratanakul",
        "full_name_th": "รศ.ดร. ฐิติรัตน์ สิริบวรรัตนกุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "Artificial Intelligence",
            "Image Processing"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
