"""Wave36 retry2 selenium checkpoint-only export (wave36_su_ict).
Univ=มหาวิทยาลัยศิลปากร Faculty=คณะเทคโนโลยีสารสนเทศและการสื่อสาร.
Method: headless selenium webdriver direct; SU=JS arguments[0].click()+ENTER fallback on nav+elementor widgets; KKU=2nd-hop profile links (cap 15); every page_source fed to FacultyExtractionAgent.step_with_html (step_calls=6).
Verified count in body: 1. Official *.ac.th only, NO DB commit.
Interaction: https://ict.su.ac.th/?page_id=58 clicks=5 [nav_candidates=13 base_chars=228412 dens=102 patch=1 err=-; js_clicked:<a cls='elementor-item elementor-i' text='สำหรับบุคลากร'>:chars=228608:patch=1:err=-; js_clicked:<a cls='elementor-item' text='ITA'>:chars=228611:patch=1:err=-; js_clicked:<a cls='elementor-item has-submenu' text='สำหรับนักศึกษา'>:chars=228792:patch=1:err=-]
"""
# Auto-generated by SKILL.state FacultyExtractionAgent (Session: wave36_su_ict)
EXTRACTED_FACULTIES = [
    {
        "id": "silpakornu_facultyofi_iamsat_001",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Information and Communication Technology",
        "faculty_th": "คณะเทคโนโลยีสารสนเทศและการสื่อสาร",
        "department": "คณะเทคโนโลยีสารสนเทศและการสื่อสาร",
        "department_th": "คณะเทคโนโลยีสารสนเทศและการสื่อสาร",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Manop",
        "last_name": "Iamsat",
        "full_name": "Manop Iamsat",
        "full_name_th": "ผศ. มานพ เอี่ยมสะอาด",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
