# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/allied_health_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "chulalongk_facultyofa_fac_001_001",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "ภาควิชาจุลทรรศน์ศาสตร์คลินิก",
    "department_th": "ภาควิชาจุลทรรศน์ศาสตร์คลินิก",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Khemaporn",
    "last_name": "",
    "full_name": "Khemaporn",
    "full_name_th": "ผศ.ดร. ทนพญ.เขมาภรณ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_mingphakdee_002",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "ภาควิชาเวชศาสตร์การธนาคารเลือดและจุลชีววิทยาคลินิก",
    "department_th": "ภาควิชาเวชศาสตร์การธนาคารเลือดและจุลชีววิทยาคลินิก",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Raweenan",
    "last_name": "Mingphakdee",
    "full_name": "Raweenan Mingphakdee",
    "full_name_th": "ผศ.ดร. ทนพญ.ระวีนันท์ มิ่งภัคนีย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_saelee_003",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "ภาควิชาเคมีคลินิก",
    "department_th": "ภาควิชาเคมีคลินิก",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Chanachai",
    "last_name": "Saelee",
    "full_name": "Chanachai Saelee",
    "full_name_th": "อ.ดร. ทนพ.ชนะชัย แซ่ลี้",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_chanmee_004",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "ภาควิชาเคมีคลินิก",
    "department_th": "ภาควิชาเคมีคลินิก",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Theerawut",
    "last_name": "Chanmee",
    "full_name": "Theerawut Chanmee",
    "full_name_th": "ผศ.ดร. ธีระวุฒิ จันทร์มี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_janmaimool_005",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Piyapong",
    "last_name": "Janmaimool",
    "full_name": "Piyapong Janmaimool",
    "full_name_th": "รศ.ดร. ปิยะพงษ์ จันทร์ใหม่มูล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_prach_006",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "ภาควิชารังสีเทคนิค",
    "department_th": "ภาควิชารังสีเทคนิค",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Weerapong",
    "last_name": "Prach",
    "full_name": "Weerapong Prach",
    "full_name_th": "ศ. เกียรติคุณ ดร.วีระพงศ์ ปรัช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_liangpibul_007",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะเทคนิคการแพทย์",
    "department_th": "คณะเทคนิคการแพทย์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Pimphan",
    "last_name": "Liangpibul",
    "full_name": "Pimphan Liangpibul",
    "full_name_th": "รศ. พญ.พิมพ์พันธุ์ เลียงพิบูลย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_fac_008_008",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะสหเวชศาสตร์",
    "department_th": "คณะสหเวชศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Anong",
    "last_name": "",
    "full_name": "Anong",
    "full_name_th": "รศ.ดร. กภ.อนงค์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_chatathikun_009",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "สำนักวิชาสหเวชศาสตร์",
    "department_th": "สำนักวิชาสหเวชศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Morakot",
    "last_name": "Chatathikun",
    "full_name": "Morakot Chatathikun",
    "full_name_th": "รศ.ดร. ทนพญ.มรกต ชาตาธิคุณ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_bunyarataphan_010",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะสหเวชศาสตร์",
    "department_th": "คณะสหเวชศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Viroj",
    "last_name": "Bunyarataphan",
    "full_name": "Viroj Bunyarataphan",
    "full_name_th": "รศ.ดร. ทนพ.วิโรจน์ บุญรัตนกรกิจ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "มะเร็งและการอักเสบ"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_amranont_012",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะสหเวชศาสตร์",
    "department_th": "คณะสหเวชศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Palanee",
    "last_name": "Amranont",
    "full_name": "Palanee Amranont",
    "full_name_th": "รศ.ดร. ปาลนี อัมรานนท์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_worasinchai_013",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "ภาควิชาเวชศาสตร์การธนาคารเลือด",
    "department_th": "ภาควิชาเวชศาสตร์การธนาคารเลือด",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Navaporn",
    "last_name": "Worasinchai",
    "full_name": "Navaporn Worasinchai",
    "full_name_th": "ผศ.ดร. ทนพญ.นวพร วรศิลป์ชัย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_leecharoenkiat_014",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "ภาควิชาจุลทรรศน์ศาสตร์คลินิก",
    "department_th": "ภาควิชาจุลทรรศน์ศาสตร์คลินิก",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Kamonlak",
    "last_name": "Leecharoenkiat",
    "full_name": "Kamonlak Leecharoenkiat",
    "full_name_th": "รศ.ดร. ทนพญ.กมลลักษณ์ ลีเจริญเกียรติ",
    "role": "อาจารย์ประจำ",
    "email": "kamonlak.l@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_prachniwat_015",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "ภาควิชาจุลทรรศน์ศาสตร์คลินิก",
    "department_th": "ภาควิชาจุลทรรศน์ศาสตร์คลินิก",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Paweena",
    "last_name": "Prachniwat",
    "full_name": "Paweena Prachniwat",
    "full_name_th": "ผศ.ดร. ทนพญ.ปวีณา ปราชญ์นิวัฒน์",
    "role": "อาจารย์ประจำ",
    "email": "paweena.p@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_rakvongthai_016",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Yothin",
    "last_name": "Rakvongthai",
    "full_name": "Yothin Rakvongthai",
    "full_name_th": "รศ.ดร. โยธิน รักวงษ์ไทย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_udee_017",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Nuntawat",
    "last_name": "Udee",
    "full_name": "Nuntawat Udee",
    "full_name_th": "รศ.ดร. นันทวัฒน์ อู่ดี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_kaewlek_018",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Titipong",
    "last_name": "Kaewlek",
    "full_name": "Titipong Kaewlek",
    "full_name_th": "ผศ.ดร. ฐิติพงศ์ แก้วเหล็ก",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_damrongkitudom_019",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Nuanpen",
    "last_name": "Damrongkitudom",
    "full_name": "Nuanpen Damrongkitudom",
    "full_name_th": "ดร. นวลเพ็ญ ดำรงกิจอุดม",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_wangsaturak_020",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Danai",
    "last_name": "Wangsaturak",
    "full_name": "Danai Wangsaturak",
    "full_name_th": "ผศ.ดร. นพ.ดนัย วังสตุรค",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_techavichit_021",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Piti",
    "last_name": "Techavichit",
    "full_name": "Piti Techavichit",
    "full_name_th": "รศ. นพ.ปิติ เตชะวิจิตร์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_plabplueng_022",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะเทคนิคการแพทย์",
    "department_th": "คณะเทคนิคการแพทย์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Chotiros",
    "last_name": "Plabplueng",
    "full_name": "Chotiros Plabplueng",
    "full_name_th": "ผศ.ดร. โชติรส พลับพลึง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_panyapinyoplul_023",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะเทคนิคการแพทย์",
    "department_th": "คณะเทคนิคการแพทย์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Boonyarit",
    "last_name": "Panyapinyoplul",
    "full_name": "Boonyarit Panyapinyoplul",
    "full_name_th": "ผศ.ดร. บุณยฤทธิ์ ปัญญาภิญโญผล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_sri_024",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะเทคนิคการแพทย์",
    "department_th": "คณะเทคนิคการแพทย์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sorachai",
    "last_name": "Sri...",
    "full_name": "Sorachai Sri...",
    "full_name_th": "ผศ.ดร. นพ.สรชัย ศรี...",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_phuthong_025",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะสหเวชศาสตร์ มหาวิทยาลัยธรรมศาสตร์",
    "department_th": "คณะสหเวชศาสตร์ มหาวิทยาลัยธรรมศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Anek",
    "last_name": "Phuthong",
    "full_name": "Anek Phuthong",
    "full_name_th": "ผศ.ดร. เอนก ภู่ทอง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_siriprikphong_026",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะสหเวชศาสตร์ มหาวิทยาลัยธรรมศาสตร์",
    "department_th": "คณะสหเวชศาสตร์ มหาวิทยาลัยธรรมศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Philaiwan",
    "last_name": "Siriprikphong",
    "full_name": "Philaiwan Siriprikphong",
    "full_name_th": "รศ.ดร. พิไลวรรณ ศิริพฤกษ์พงษ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_tangwongsan_027",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Suphachai",
    "last_name": "Tangwongsan",
    "full_name": "Suphachai Tangwongsan",
    "full_name_th": "รศ.ดร. ศุภชัย ตั้งวงศ์ศานต์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_tantimongcolwat_028",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะเทคนิคการแพทย์",
    "department_th": "คณะเทคนิคการแพทย์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Thanawut",
    "last_name": "Tantimongcolwat",
    "full_name": "Thanawut Tantimongcolwat",
    "full_name_th": "รศ.ดร. ธนาวุฒิ ตันติมงคลวัฒน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_nantasenamat_029",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะเทคนิคการแพทย์ มหาวิทยาลัยมหิดล",
    "department_th": "คณะเทคนิคการแพทย์ มหาวิทยาลัยมหิดล",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Chanin",
    "last_name": "Nantasenamat",
    "full_name": "Chanin Nantasenamat",
    "full_name_th": "รศ.ดร. ชนินทร์ นันทเสนามาตร์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "ปริญญาตรี สาขาวิทยาศาสตร์ชีวภาพ"
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_asipat_030",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะเทคนิคการแพทย์ มหาวิทยาลัยมหิดล",
    "department_th": "คณะเทคนิคการแพทย์ มหาวิทยาลัยมหิดล",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Kulmawadee",
    "last_name": "Asipat",
    "full_name": "Kulmawadee Asipat",
    "full_name_th": "ศ.ดร. ทพญ.กุลมาวดี อาศิพัทธ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_pongnapang_031",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะสหเวชศาสตร์",
    "department_th": "คณะสหเวชศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Napapong",
    "last_name": "Pongnapang",
    "full_name": "Napapong Pongnapang",
    "full_name_th": "ผศ.ดร. นภาพงษ์ พงษ์นภางค์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "Radiologic Technology"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofa_chitphat_032",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Allied Health Sciences & Faculty of Medical Technology",
    "faculty_th": "คณะสหเวชศาสตร์ และ คณะเทคนิคการแพทย์",
    "department": "คณะเทคนิคการแพทย์",
    "department_th": "คณะเทคนิคการแพทย์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Nittaya",
    "last_name": "Chitphat",
    "full_name": "Nittaya Chitphat",
    "full_name_th": "อ. พญ.นิตยา จิตรภาษย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
