# -*- coding: utf-8 -*-
"""
Cleaned & Disambiguated Academic Faculty Dataset (backend/scripts/data_sources/architecture_arts_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "silpakornu_facultyofa_panhiphak_001",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "คณะสถาปัตยกรรมศาสตร์",
    "department_th": "คณะสถาปัตยกรรมศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Kuntontip",
    "last_name": "Panhiphak",
    "full_name": "Kuntontip Panhiphak",
    "full_name_th": "รศ.ดร. กุณฑลทิพย พานิชภักดิ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_sapsuk_002",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาสถาปัตยกรรมศาสตร์",
    "department_th": "ภาควิชาสถาปัตยกรรมศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Sarayut",
    "last_name": "Sapsuk",
    "full_name": "Sarayut Sapsuk",
    "full_name_th": "ผศ. สรายุทธ ทรัพย์สุข",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_sangsayan_003",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "สาขาวิชาสถาปัตยกรรมไทย",
    "department_th": "สาขาวิชาสถาปัตยกรรมไทย",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Pracha",
    "last_name": "Sangsayan",
    "full_name": "Pracha Sangsayan",
    "full_name_th": "รศ. ประชา แสงสายัณห์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "สถาปัตยกรรมไทย"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_wongphayat_004",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาสถาปัตยกรรมศาสตร์",
    "department_th": "ภาควิชาสถาปัตยกรรมศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Waricha",
    "last_name": "Wongphayat",
    "full_name": "Waricha Wongphayat",
    "full_name_th": "รศ.ดร. วาริชา วงศ์พยัต",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_sirithanawat_005",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "คณะสถาปัตยกรรมศาสตร์",
    "department_th": "คณะสถาปัตยกรรมศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Chaiboon",
    "last_name": "Sirithanawat",
    "full_name": "Chaiboon Sirithanawat",
    "full_name_th": "อ. ชัยบูรณ์ ศิริธนะวัฒน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_kasornsawan_006",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "คณะจิตรกรรมประติมากรรมและภาพพิมพ์",
    "department_th": "คณะจิตรกรรมประติมากรรมและภาพพิมพ์",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Tinnakorn",
    "last_name": "Kasornsawan",
    "full_name": "Tinnakorn Kasornsawan",
    "full_name_th": "ศ. ทินกร กาษรสุวรรณ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_charoenwong_007",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "คณะจิตรกรรมประติมากรรมและภาพพิมพ์",
    "department_th": "คณะจิตรกรรมประติมากรรมและภาพพิมพ์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Surasak",
    "last_name": "Charoenwong",
    "full_name": "Surasak Charoenwong",
    "full_name_th": "รศ. สุรศักดิ์ เจริญวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_pongdam_008",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "คณะจิตรกรรมประติมากรรมและภาพพิมพ์",
    "department_th": "คณะจิตรกรรมประติมากรรมและภาพพิมพ์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Prayad",
    "last_name": "Pongdam",
    "full_name": "Prayad Pongdam",
    "full_name_th": "รศ. ประหยัด พงษ์ดำ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_likhitmanon_009",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์ คณะวิจิตรศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์ คณะวิจิตรศิลป์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Wannuchat",
    "last_name": "Likhitmanon",
    "full_name": "Wannuchat Likhitmanon",
    "full_name_th": "ผศ.ดร. วรรณุฉัตร ลิขิตมานนท์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ทัศนศิลป์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_janthakhaisorn_010",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Prakornpatara",
    "last_name": "Janthakhaisorn",
    "full_name": "Prakornpatara Janthakhaisorn",
    "full_name_th": "รศ. ปกรณ์ภัทร์ จันทะไข่สร",
    "role": "อาจารย์ประจำ",
    "email": "prakornpatara.j@cmu.ac.th",
    "image_url": "",
    "profile_url": "https://service.finearts.cmu.ac.th/PersonFAV1/ViewDetailPersonal.php?&IDDataStaff=40",
    "education": [],
    "research_interests": [
      "ศิลปะภาพพิมพ์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_suwanhem_011",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Soontorn",
    "last_name": "Suwanhem",
    "full_name": "Soontorn Suwanhem",
    "full_name_th": "รศ. สุนทร สุวรรณเหม",
    "role": "อาจารย์ประจำ",
    "email": "soontorn.s@cmu.ac.th",
    "image_url": "",
    "profile_url": "https://service.finearts.cmu.ac.th/PersonFAV1/ViewDetailPersonal.php?&IDDataStaff=35",
    "education": [],
    "research_interests": [
      "ประติมากรรม"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_sudhom_012",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Songkran",
    "last_name": "Sudhom",
    "full_name": "Songkran Sudhom",
    "full_name_th": "ผศ. สงกรานต์ สุดหอม",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ทัศนศิลป์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_panjinda_013",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Wipavee",
    "last_name": "Panjinda",
    "full_name": "Wipavee Panjinda",
    "full_name_th": "อ.ดร. วิภาวี ปานจินดา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ทัศนศิลป์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_maleepan_014",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Kitti",
    "last_name": "Maleepan",
    "full_name": "Kitti Maleepan",
    "full_name_th": "รศ. กิตติ มาลีพันธุ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "จิตรกรรม"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_chainakut_015",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาภาพพิมพ์ จิตรกรรม และประติมากรรม คณะวิจิตรศิลป์",
    "department_th": "ภาควิชาภาพพิมพ์ จิตรกรรม และประติมากรรม คณะวิจิตรศิลป์",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Phongdet",
    "last_name": "Chainakut",
    "full_name": "Phongdet Chainakut",
    "full_name_th": "ศ. (เกียรติคุณ)พงศ์เดช ไชยคุตร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://service.finearts.cmu.ac.th/PersonFAV1/ViewDetailPersonal.php?&IDDataStaff=48",
    "education": [],
    "research_interests": [
      "ภาพพิมพ์",
      "จิตรกรรม",
      "ประติมากรรม"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_gasorngatsara_016",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "คณะวิจิตรศิลป์",
    "department_th": "คณะวิจิตรศิลป์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Sugree",
    "last_name": "Gasorngatsara",
    "full_name": "Sugree Gasorngatsara",
    "full_name_th": "รศ.ดร. สุกรี เกษรเกศรา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_anantacha_017",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "คณะสถาปัตยกรรมและการออกแบบ",
    "department_th": "คณะสถาปัตยกรรมและการออกแบบ",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Thana",
    "last_name": "Anantacha",
    "full_name": "Thana Anantacha",
    "full_name_th": "รศ.ดร. ธนา อนันต์อาชา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://archd.kmutnb.ac.th/about/profile?c=8ac87937bbc5c9b604a141d83e7599c172d114df&type=board",
    "education": [],
    "research_interests": [
      "สถาปัตยกรรม"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_kunawan_018",
    "university": "King Mongkut's University of Technology North Bangkok",
    "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "สาขาสถาปัตยกรรม",
    "department_th": "สาขาสถาปัตยกรรม",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Panida",
    "last_name": "Kunawan",
    "full_name": "Panida Kunawan",
    "full_name_th": "อ.ดร. ปณิดา คุณาวรรณ",
    "role": "อาจารย์ประจำ",
    "email": "panida.k@archd.kmutnb.ac.th",
    "image_url": "",
    "profile_url": "https://archd.kmutnb.ac.th/about/profile?c=9bb23f08ac6d381eb574ccde73edcc8d9da63942&type=advisor-architecture",
    "education": [],
    "research_interests": [
      "สถาปัตยกรรม"
    ],
    "featured_publications": [
      "ผลงาน 1 ปณิดา คุณาวรรณ"
    ],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_piriyasurawong_019",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "คณะสถาปัตยกรรมและการออกแบบ",
    "department_th": "คณะสถาปัตยกรรมและการออกแบบ",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Sawit",
    "last_name": "Piriyasurawong",
    "full_name": "Sawit Piriyasurawong",
    "full_name_th": "ดร. ศวิษฐ์ พิริยะสุรวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyofa_chintanawat_020",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Architecture",
    "faculty_th": "คณะสถาปัตยกรรมศาสตร์",
    "department": "ภาควิชาสถาปัตยกรรม คณะสถาปัตยกรรมและการออกแบบ",
    "department_th": "ภาควิชาสถาปัตยกรรม คณะสถาปัตยกรรมและการออกแบบ",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Amarat",
    "last_name": "Chintanawat",
    "full_name": "Amarat Chintanawat",
    "full_name_th": "อ. อมรรัตน์ ชินธนวัฒน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://archd.kmutnb.ac.th/about/profile?c=f9ff3d3157e5e4a3f652bd428628f9186fa7c368&type=advisor-architecture",
    "education": [],
    "research_interests": [
      "ออกแบบภายใน"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
