# Batch 2: Advanced Engineering, Medical, Creative Arts, Business & Regional Curricula

BATCH2_COURSES = [
    # =========================================================================
    # KMITL (School of Information Technology, Engineering & Food Industry)
    # =========================================================================
    {
        "id": "kmitl_it_bsc_datascience",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการข้อมูลและการวิเคราะห์เชิงธุรกิจ",
        "title_en": "Bachelor of Science Program in Data Science and Business Analytics",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาการข้อมูลและการวิเคราะห์เชิงธุรกิจ)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Information Technology",
        "faculty_th": "คณะเทคโนโลยีสารสนเทศ",
        "department": "Department of Data Science",
        "department_th": "สาขาวิชาวิทยาการข้อมูล",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "224,000 บาท",
        "description": "มุ่งเน้นการวิเคราะห์ Big Data, Machine Learning, Deep Learning, Data Visualization และการนำข้อมูลไปขับเคลื่อนกลยุทธ์ทางธุรกิจ",
        "curriculum_highlights": ["การใช้เครื่องมือ Data Science ระดับแนวหน้า (Python, SQL, Spark, Tableau)", "การสร้างแบบจำลอง AI สำหรับ FinTech และ E-Commerce", "การทำโครงงาน Data Analytics กับองค์กรธุรกิจจริง"],
        "career_paths": ["Data Scientist", "Data Analyst", "Data Engineer", "Business Intelligence Developer"],
        "tags": ["Data Science", "Business Analytics", "Machine Learning", "Big Data", "KMITL"],
        "website_url": "https://it.kmitl.ac.th"
    },
    {
        "id": "kmitl_it_bsc_cybersecurity",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาความมั่นคงปลอดภัยไซเบอร์",
        "title_en": "Bachelor of Science Program in Cybersecurity",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (ความมั่นคงปลอดภัยไซเบอร์)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Information Technology",
        "faculty_th": "คณะเทคโนโลยีสารสนเทศ",
        "department": "Department of Cybersecurity",
        "department_th": "สาขาวิชาความมั่นคงปลอดภัยไซเบอร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "224,000 บาท",
        "description": "เน้นการป้องกันภัยคุกคามทางไซเบอร์ การทดสอบเจาะระบบ (Penetration Testing) นิติวิทยาศาสตร์ดิจิทัล และการปฏิบัติตาม พ.ร.บ. ไซเบอร์/PDPA",
        "curriculum_highlights": ["ห้องปฏิบัติการ Cyber Range สำหรับจำลองการโจมตีและป้องกันแบบเรียลไทม์", "การเตรียมพร้อมสอบใบเซอร์สากล (CompTIA Security+, CEH, CISSP)", "ความร่วมมือกับสำนักงานคณะกรรมการการรักษาความมั่นคงปลอดภัยไซเบอร์แห่งชาติ (สกมช.)"],
        "career_paths": ["Cybersecurity Analyst", "Penetration Tester / Ethical Hacker", "SOC Analyst", "Information Security Officer"],
        "tags": ["Cybersecurity", "Information Security", "Ethical Hacking", "Cloud Security", "KMITL"],
        "website_url": "https://it.kmitl.ac.th"
    },
    {
        "id": "kmitl_eng_beng_chemical",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเคมี",
        "title_en": "Bachelor of Engineering Program in Chemical Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมเคมี)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Chemical Engineering",
        "department_th": "ภาควิชาวิศวกรรมเคมี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "140 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "ศึกษาการออกแบบและควบคุมกระบวนการทางเคมี ปิโตรเคมี โรงกลั่นน้ำมัน พลังงานไฮโดรเจน และการผลิตสารเคมีมูลค่าสูงที่เป็นมิตรต่อสิ่งแวดล้อม",
        "curriculum_highlights": ["การจำลองกระบวนการผลิตด้วยซอฟต์แวร์ Aspen Plus และ HYSYS", "เทคโนโลยีพลังงานไฮโดรเจนและการดักจับคาร์บอน (CCUS)", "การฝึกงานในกลุ่มอุตสาหกรรมปิโตรเคมีและพลังงานชั้นนำ (PTT, SCG, GC)"],
        "career_paths": ["Process Engineer", "Petrochemical & Refinery Engineer", "Safety & Environmental Engineer"],
        "tags": ["Chemical Engineering", "Process Engineering", "Petrochemical", "Energy", "KMITL"],
        "website_url": "https://chemeng.kmitl.ac.th"
    },
    {
        "id": "kmitl_eng_beng_industrial",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมอุตสาหการและการจัดการโลจิสติกส์",
        "title_en": "Bachelor of Engineering Program in Industrial Engineering and Logistics Management",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมอุตสาหการ)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Industrial Engineering",
        "department_th": "ภาควิชาวิศวกรรมอุตสาหการ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "เน้นการเพิ่มประสิทธิภาพกระบวนการผลิต การจัดการโซ่อุปทาน การควบคุมคุณภาพแบบ Lean Six Sigma และการใช้ AI ในโรงงานอุตสาหกรรม 4.0",
        "curriculum_highlights": ["การประยุกต์ใช้ Lean Manufacturing และ Six Sigma", "การจำลองระบบโลจิสติกส์ด้วย Digital Simulation Tools (Arena, FlexSim)", "ระบบบริหารงานคุณภาพ ISO และการบริหารความเสี่ยง"],
        "career_paths": ["Industrial Engineer", "Supply Chain & Logistics Specialist", "Quality Assurance Engineer (QA/QC)", "Production Planning Manager"],
        "tags": ["Industrial Engineering", "Logistics", "Supply Chain", "Six Sigma", "Industry 4.0"],
        "website_url": "https://ie.kmitl.ac.th"
    },

    # =========================================================================
    # KMUTT (School of Bioresources, Liberal Arts & Architecture)
    # =========================================================================
    {
        "id": "kmutt_soad_barch_intl",
        "title_th": "หลักสูตรสถาปัตยกรรมศาสตรบัณฑิต (หลักสูตรนานาชาติ - SoA+D)",
        "title_en": "Bachelor of Architecture Program (International Program - SoA+D)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "สถ.บ. (สถาปัตยกรรม)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "School of Architecture and Design (SoA+D)",
        "faculty_th": "คณะสถาปัตยกรรมศาสตร์และการออกแบบ (SoA+D)",
        "department": "Department of Architecture",
        "department_th": "สาขาวิชาสถาปัตยกรรม",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "5 ปี",
        "total_credits": "165 หน่วยกิต",
        "tuition_per_semester": "80,000 บาท",
        "tuition_total": "800,000 บาท",
        "description": "หลักสูตรสถาปัตยกรรมนานาชาติชั้นนำในย่านบางขุนเทียน เน้นการออกแบบเชิงนวัตกรรม สถาปัตยกรรมยั่งยืน และการใช้เทคโนโลยีดิจิทัลระดับสากล",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษ 100% กับอาจารย์ชาวต่างชาติ", "สตูดิโอออกแบบที่เน้นความยั่งยืนและการตอบโจทย์ปัญหาสังคม", "เครือข่ายแลกเปลี่ยนนักศึกษากับสถาบันสถาปัตยกรรมระดับโลกในยุโรปและเอเชีย"],
        "career_paths": ["International Architect", "Sustainable Building Designer", "Urban Design Consultant", "Creative Design Director"],
        "tags": ["Architecture", "SoA+D", "Design", "Sustainable Architecture", "KMUTT"],
        "website_url": "https://soad.kmutt.ac.th"
    },
    {
        "id": "kmutt_bio_msc_biotech",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเทคโนโลยีชีวภาพ (หลักสูตรนานาชาติ)",
        "title_en": "Master of Science Program in Biotechnology (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (เทคโนโลยีชีวภาพ)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "School of Bioresources and Technology",
        "faculty_th": "คณะทรัพยากรชีวภาพและเทคโนโลยี",
        "department": "Division of Biotechnology",
        "department_th": "สายวิชาเทคโนโลยีชีวภาพ",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "180,000 บาท",
        "description": "ศูนย์กลางการวิจัยเทคโนโลยีชีวภาพของ มจธ. บางขุนเทียน เน้นเทคโนโลยีการหมักขั้นสูง ชีววิทยาระบบ สาหร่ายพลังงาน และสารชีวภาพมูลค่าสูง",
        "curriculum_highlights": ["การวิจัยสาหร่ายขนาดเล็ก (Spirulina / Microalgae) และชีวมวลระดับแนวหน้า", "โรงงานต้นแบบชีววิศวกรรมและเทคโนโลยีการหมักระดับอุตสาหกรรม", "การสร้างสารออกฤทธิ์ทางชีวภาพและโปรตีนทางเลือก"],
        "career_paths": ["นักวิจัยอาวุโสด้านเทคโนโลยีชีวภาพ", "ผู้เชี่ยวชาญการผลิตชีวภาพในภาคอุตสาหกรรม", "อาจารย์มหาวิทยาลัย"],
        "tags": ["Biotechnology", "Bioresources", "Fermentation", "Microalgae", "KMUTT"],
        "website_url": "https://sbt.kmutt.ac.th"
    },

    # =========================================================================
    # SWU (Faculty of Humanities, Science & Social Sciences)
    # =========================================================================
    {
        "id": "swu_sci_bsc_computer_science",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์",
        "title_en": "Bachelor of Science Program in Computer Science",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาการคอมพิวเตอร์)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Science",
        "faculty_th": "คณะวิทยาศาสตร์",
        "department": "Department of Computer Science",
        "department_th": "ภาควิชาวิทยาการคอมพิวเตอร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "เน้นการพัฒนาซอฟต์แวร์ อัลกอริทึม ปัญญาประดิษฐ์ วิทยาการข้อมูล และความมั่นคงปลอดภัยบนคลาวด์ ตั้งอยู่ใจกลางย่านธุรกิจอโศก-ประสานมิตร",
        "curriculum_highlights": ["การเรียนรู้ Full-Stack Web, Mobile และ Cloud Native Architecture", "การฝึกงานและสหกิจศึกษากับบริษัท Tech ชั้นนำในย่าน CBD อโศก", "การพัฒนาโครงงานโครงสร้างพื้นฐาน AI และ Data Analytics"],
        "career_paths": ["Software Developer / Engineer", "Data Scientist / Data Analyst", "Cloud Solutions Developer", "System Analyst"],
        "tags": ["Computer Science", "Software Engineering", "AI", "Cloud", "SWU"],
        "website_url": "https://cs.science.swu.ac.th"
    },
    {
        "id": "swu_hum_ba_language_for_career",
        "title_th": "หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาษาเพื่ออาชีพ (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Arts Program in Language for Careers (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ. (ภาษาเพื่ออาชีพ)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Humanities",
        "faculty_th": "คณะมนุษยศาสตร์",
        "department": "Department of Western Languages",
        "department_th": "ภาควิชาภาษาตะวันตก",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "42,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "พัฒนาทักษะภาษาอังกฤษและภาษาที่สามระดับมืออาชีพสำหรับธุรกิจระหว่างประเทศ การทูต สื่อสารมวลชน และการท่องเที่ยว",
        "curriculum_highlights": ["การสื่อสารธุรกิจข้ามวัฒนธรรมและการเจรจาต่อรองระดับสากล", "การแปลและการล่ามสำหรับการประชุมระดับนานาชาติ", "การฝึกงานกับสถานเอกอัครราชทูตและองค์กรข้ามชาติ"],
        "career_paths": ["เจ้าหน้าที่การทูตและวิเทศสัมพันธ์", "นักแปลและล่ามมืออาชีพ", "ผู้จัดการฝ่ายสื่อสารองค์กรระหว่างประเทศ", "พนักงานต้อนรับบนเครื่องบิน"],
        "tags": ["Humanities", "Languages", "International Relations", "Business English", "SWU"],
        "website_url": "https://hu.swu.ac.th"
    },

    # =========================================================================
    # SU (Faculty of Painting, Music & ICT)
    # =========================================================================
    {
        "id": "su_art_bfa_painting",
        "title_th": "หลักสูตรศิลปบัณฑิต สาขาวิชาจิตรกรรม",
        "title_en": "Bachelor of Fine Arts Program in Painting",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศ.บ. (จิตรกรรม)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Painting, Sculpture and Graphic Arts",
        "faculty_th": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
        "department": "Department of Painting",
        "department_th": "ภาควิชาจิตรกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "5 ปี",
        "total_credits": "165 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "180,000 บาท",
        "description": "คณะศิลปะอันดับ 1 และเก่าแก่ที่สุดของไทย ก่อตั้งโดยศาสตราจารย์ศิลป์ พีระศรี สร้างศิลปินเอก ศิลปินแห่งชาติ และผู้เชี่ยวชาญด้านทัศนศิลป์",
        "curriculum_highlights": ["การฝึกทักษะจิตรกรรม วาดเส้น และทัศนศิลป์อย่างเข้มข้นทุกเทอม", "การจัดแสดงนิทรรศการผลงานศิลปะระดับชาติและนานาชาติ", "อาจารย์และศิลปินผู้ทรงคุณวุฒิระดับศิลปินแห่งชาติ"],
        "career_paths": ["ศิลปินอาชีพ (Professional Artist)", "ภัณฑารักษ์และนักบริหารจัดการศิลปะ (Curator)", "อาจารย์และนักวิชาการศิลปะ"],
        "tags": ["Fine Arts", "Painting", "Sculpture", "Silpa Bhirasri", "Silpakorn"],
        "website_url": "https://psg.su.ac.th"
    },
    {
        "id": "su_music_bfa_commercial_music",
        "title_th": "หลักสูตรดุริยางคศาสตรบัณฑิต สาขาวิชาดนตรีเชิงพาณิชย์",
        "title_en": "Bachelor of Music Program in Commercial Music",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ดย.บ. (ดนตรีเชิงพาณิชย์)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Music",
        "faculty_th": "คณะดุริยางคศาสตร์",
        "department": "Department of Commercial Music",
        "department_th": "สาขาวิชาดนตรีเชิงพาณิชย์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "360,000 บาท",
        "description": "ผลิตนักแต่งเพลง โปรดิวเซอร์ ซาวด์เอ็นจิเนียร์ และศิลปินในอุตสาหกรรมเพลงและสื่อบันเทิงยุคดิจิทัล",
        "curriculum_highlights": ["ห้องสตูดิโอบันทึกเสียงและโปรดักชันดนตรีมาตรฐานระดับโลก", "การแต่งเพลง การเรียบเรียงเสียงประสาน และการโปรดิวซ์เพลง", "การบริหารจัดการค่ายเพลงและลิขสิทธิ์ดนตรีสากล"],
        "career_paths": ["Music Producer", "Songwriter / Composer", "Sound Engineer / Mix & Mastering Engineer", "Artist"],
        "tags": ["Music", "Commercial Music", "Music Production", "Sound Engineering", "Silpakorn"],
        "website_url": "https://music.su.ac.th"
    },
    {
        "id": "su_ict_bsc_game_interactive",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีสารสนเทศเพื่อการออกแบบ (การออกแบบเกมและแอนิเมชัน)",
        "title_en": "Bachelor of Science Program in Information and Communication Technology for Design (Game and Animation)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคโนโลยีสารสนเทศเพื่อการออกแบบ)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Information and Communication Technology (ICT Silpakorn)",
        "faculty_th": "คณะเทคโนโลยีสารสนเทศและการสื่อสาร (ICT ศิลปากร)",
        "department": "Department of Interactive Design",
        "department_th": "สาขาวิชาการออกแบบเกมและแอนิเมชัน",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "38,000 บาท",
        "tuition_total": "304,000 บาท",
        "description": "ผสานศิลปะเข้ากับเทคโนโลยีไอทีเพื่อผลิตเกมเมอร์ดีไซเนอร์ นักพัฒนาเกม 3D แอนิเมเตอร์ และวิศวกรซอฟต์แวร์อินเตอร์แอคทีฟ",
        "curriculum_highlights": ["การพัฒนาเกมด้วย Unreal Engine และ Unity", "การปั้นโมเดล 3D การสร้างตัวละคร (Character Design) และ Rigging", "การสร้างผลงานเกมเพื่อจัดจำหน่ายจริงบน Steam และ Mobile Platforms"],
        "career_paths": ["Game Designer & Developer", "3D Animator & Modeler", "Technical Artist", "Interactive Media Producer"],
        "tags": ["Game Design", "Animation", "Unity", "Unreal Engine", "ICT Silpakorn"],
        "website_url": "https://ict.su.ac.th"
    },

    # =========================================================================
    # BUU (Allied Health, Nursing & Pharmacy)
    # =========================================================================
    {
        "id": "buu_pharm_bpharm_care",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาการบริบาลทางเภสัชกรรม",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Care",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (การบริบาลทางเภสัชกรรม)",
        "university": "Burapha University",
        "university_th": "มหาวิทยาลัยบูรพา",
        "faculty": "Faculty of Pharmaceutical Sciences",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Clinical Pharmacy",
        "department_th": "สาขาวิชาเภสัชกรรมคลินิก",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "224 หน่วยกิต",
        "tuition_per_semester": "26,000 บาท",
        "tuition_total": "312,000 บาท",
        "description": "เน้นการบริบาลทางเภสัชกรรมในโรงพยาบาลและการส่งเสริมการใช้ยาอย่างสมเหตุผลในเขตระเบียงเศรษฐกิจพิเศษภาคตะวันออก",
        "curriculum_highlights": ["การฝึกปฏิบัติงานคลินิกในโรงพยาบาลมหาวิทยาลัยบูรพาและโรงพยาบาลศูนย์ภาคตะวันออก", "การคุ้มครองความปลอดภัยด้านยาและผลิตภัณฑ์สุขภาพชุมชน", "เภสัชพันธุศาสตร์และการบริบาลผู้ป่วยเฉพาะราย"],
        "career_paths": ["เภสัชกรประจำโรงพยาบาล", "เภสัชกรคลินิก", "เภสัชกรชุมชน (เจ้าของร้านยา)"],
        "tags": ["Pharmacy", "Pharmaceutical Care", "Health Science", "Burapha Pharmacy"],
        "website_url": "https://pharm.buu.ac.th"
    },
    {
        "id": "buu_ah_bsc_med_tech",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคนิคการแพทย์",
        "title_en": "Bachelor of Science Program in Medical Technology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคนิคการแพทย์)",
        "university": "Burapha University",
        "university_th": "มหาวิทยาลัยบูรพา",
        "faculty": "Faculty of Allied Health Sciences",
        "faculty_th": "คณะสหเวชศาสตร์",
        "department": "Department of Medical Technology",
        "department_th": "ภาควิชาเทคนิคการแพทย์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "176,000 บาท",
        "description": "ผลิตนักเทคนิคการแพทย์ผู้เชี่ยวชาญการตรวจวิเคราะห์ทางห้องปฏิบัติการทางการแพทย์ โลหิตวิทยา ภูมิคุ้มกันวิทยา และอณูชีวโมเลกุล",
        "curriculum_highlights": ["ห้องปฏิบัติการชันสูตรทางการแพทย์ที่ได้มาตรฐานสากล ISO 15189", "การตรวจวินิจฉัยโรคติดเชื้อและโรคทางพันธุกรรมด้วยเทคนิค PCR / NGS", "การฝึกงานในห้องปฏิบัติการโรงพยาบาลศูนย์ชั้นนำ"],
        "career_paths": ["นักเทคนิคการแพทย์ประจำโรงพยาบาลรัฐและเอกชน", "นักวิทยาศาสตร์การแพทย์ในห้องแล็บเฉพาะทาง", "ผู้เชี่ยวชาญผลิตภัณฑ์ตรวจวินิจฉัยทางการแพทย์"],
        "tags": ["Medical Technology", "Allied Health", "Clinical Chemistry", "Laboratory", "Burapha"],
        "website_url": "https://allied.buu.ac.th"
    },

    # =========================================================================
    # NIDA (Graduate School of Language & Communication, Law)
    # =========================================================================
    {
        "id": "nida_lc_ma_language_communication",
        "title_th": "หลักสูตรศิลปศาสตรมหาบัณฑิต สาขาวิชาภาษาและการสื่อสารระหว่างวัฒนธรรม",
        "title_en": "Master of Arts Program in Language and Intercultural Communication",
        "degree_level": "ปริญญาโท",
        "degree_name": "ศศ.ม. (ภาษาและการสื่อสาร)",
        "university": "National Institute of Development Administration",
        "university_th": "สถาบันบัณฑิตพัฒนบริหารศาสตร์ (นิด้า)",
        "faculty": "Graduate School of Language and Communication",
        "faculty_th": "คณะภาษาและการสื่อสาร",
        "department": "Department of Communication Studies",
        "department_th": "สาขาวิชาภาษาและการสื่อสาร",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "42,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "พัฒนาผู้นำการสื่อสารเชิงกลยุทธ์ การสื่อสารข้ามวัฒนธรรม การประชาสัมพันธ์ระดับโลก และการเจรจาต่อรองทางธุรกิจ",
        "curriculum_highlights": ["การวิเคราะห์วาทกรรมและการสื่อสารในองค์กรระหว่างประเทศ", "การบริหารชื่อเสียงและภาวะวิกฤตของแบรนด์ (Crisis Communication)", "การสื่อสารดิจิทัลสำหรับผู้นำยุคใหม่"],
        "career_paths": ["ผู้อำนวยการฝ่ายสื่อสารองค์กร (Corporate Communications Director)", "ที่ปรึกษาด้านการสื่อสารและการประชาสัมพันธ์ระดับสากล", "นักวิชาการด้านภาษาและการสื่อสาร"],
        "tags": ["Communication Arts", "Intercultural Communication", "Strategic Communication", "NIDA"],
        "website_url": "https://lc.nida.ac.th"
    },
    {
        "id": "nida_law_llm_business",
        "title_th": "หลักสูตรนิติศาสตรมหาบัณฑิต สาขากฎหมายธุรกิจและภาษีอากร (LL.M.)",
        "title_en": "Master of Laws Program in Business and Tax Law (LL.M.)",
        "degree_level": "ปริญญาโท",
        "degree_name": "น.ม. (กฎหมายธุรกิจและภาษีอากร)",
        "university": "National Institute of Development Administration",
        "university_th": "สถาบันบัณฑิตพัฒนบริหารศาสตร์ (นิด้า)",
        "faculty": "Graduate School of Law",
        "faculty_th": "คณะนิติศาสตร์",
        "department": "Department of Law",
        "department_th": "สาขาวิชานิติศาสตร์",
        "program_type": "ภาคปกติ / ภาคพิเศษ (วันเสาร์-อาทิตย์)",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "180,000 บาท",
        "description": "เน้นกฎหมายภาษีอากรเชิงลึก การควบรวมกิจการ (M&A) กฎหมายการค้าระหว่างประเทศ และกฎหมายตลาดทุนสำหรับผู้บริหารและทนายความ",
        "curriculum_highlights": ["การวางแผนภาษีอากรธุรกิจและภาษีระหว่างประเทศ (International Tax Planning)", "กฎหมายการเงิน ตราสารหนี้ และสินทรัพย์ดิจิทัล", "อาจารย์ผู้ทรงคุณวุฒิจากศาลฎีกา กรมสรรพากร และสำนักงานกฎหมายชั้นนำ"],
        "career_paths": ["ที่ปรึกษากฎหมายภาษีและธุรกิจ (Tax & Legal Counsel)", "ทนายความประจำสำนักงานกฎหมายชั้นนำ (International Law Firm)", "ผู้บริหารฝ่ายกฎหมายองค์กร"],
        "tags": ["Law", "LL.M.", "Business Law", "Tax Law", "Corporate Law", "NIDA"],
        "website_url": "https://law.nida.ac.th"
    },
]
