# Batch 3: Private Leaders, Tech & Specialized Institutes
# (RSU, BU, UTCC, KMUTNB, RMUTT, KU Specialised, NIDA)

BATCH3_COURSES = [
    # =========================================================================
    # RSU (Rangsit University - มหาวิทยาลัยรังสิต)
    # =========================================================================
    {
        "id": "rsu_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "Rangsit University",
        "university_th": "มหาวิทยาลัยรังสิต",
        "faculty": "College of Medicine",
        "faculty_th": "วิทยาลัยแพทยศาสตร์",
        "department": "Department of Medicine",
        "department_th": "สาขาวิชาแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "252 หน่วยกิต",
        "tuition_per_semester": "180,000 บาท",
        "tuition_total": "2,160,000 บาท",
        "description": "วิทยาลัยแพทยศาสตร์เอกชนแห่งแรกของไทย ร่วมมือกับโรงพยาบาลราชวิถี โรงพยาบาลเลิดสิน และสถาบันสุขภาพเด็กแห่งชาติมหาราชินี",
        "curriculum_highlights": ["การฝึกปฏิบัติการทางคลินิกในโรงพยาบาลศูนย์ชั้นนำระดับประเทศ (รพ.ราชวิถี, รพ.เลิดสิน)", "ศูนย์ฝึกทักษะการแพทย์เสมือนจริง (Medical Simulation Center)", "มาตรฐานการประเมินวิชาชีพเวชกรรมตามเกณฑ์แพทยสภาสากล (WFME)"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไป", "แพทย์เฉพาะทางทุกสาขา", "แพทย์ประจำโรงพยาบาลรัฐและเอกชนชั้นนำ"],
        "tags": ["Medicine", "Doctor", "Health Science", "Rangsit Medicine", "WFME"],
        "website_url": "https://med.rsu.ac.th"
    },
    {
        "id": "rsu_dent_dds",
        "title_th": "หลักสูตรทันตแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Dental Surgery Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ท.บ. (ทันตแพทยศาสตรบัณฑิต)",
        "university": "Rangsit University",
        "university_th": "มหาวิทยาลัยรังสิต",
        "faculty": "College of Dental Medicine",
        "faculty_th": "วิทยาลัยทันตแพทยศาสตร์",
        "department": "Department of Dental Medicine",
        "department_th": "สาขาวิชาทันตแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "234 หน่วยกิต",
        "tuition_per_semester": "195,000 บาท",
        "tuition_total": "2,340,000 บาท",
        "description": "วิทยาลัยทันตแพทยศาสตร์เอกชนชั้นนำของไทย พร้อมโรงพยาบาลทันตกรรมขนาดใหญ่และเทคโนโลยี Digital Dentistry ครบวงจร",
        "curriculum_highlights": ["โรงพยาบาลทันตกรรม มหาวิทยาลัยรังสิต ที่มีเก้าอี้ทันตกรรมกว่า 200 ยูนิต", "การประยุกต์ใช้ CAD/CAM, 3D Cone Beam CT และเลเซอร์ทางทันตกรรม", "การฝึกทักษะคลินิกเฉพาะทางภายใต้การดูแลของทันตแพทย์ผู้เชี่ยวชาญ"],
        "career_paths": ["ทันตแพทย์ในโรงพยาบาลและคลินิกทันตกรรม", "ทันตแพทย์เฉพาะทาง", "เจ้าของคลินิกทันตกรรม"],
        "tags": ["Dentistry", "Dental", "Doctor of Dental Surgery", "Digital Dentistry", "Rangsit"],
        "website_url": "https://dentistry.rsu.ac.th"
    },
    {
        "id": "rsu_aviation_bsc_pilot",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาการบิน (นักบินพาณิชย์ตรี)",
        "title_en": "Bachelor of Science Program in Aviation (Commercial Pilot)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (การบิน)",
        "university": "Rangsit University",
        "university_th": "มหาวิทยาลัยรังสิต",
        "faculty": "International South East Asia College of Aviation (CAD)",
        "faculty_th": "สถาบันการบิน มหาวิทยาลัยรังสิต",
        "department": "Department of Commercial Pilot Training",
        "department_th": "สาขาวิชานักบินพาณิชย์",
        "program_type": "ภาคปกติ / นานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "95,000 บาท (ไม่รวมค่าชั่วโมงบิน)",
        "tuition_total": "760,000 บาท",
        "description": "ฝึกอบรมนักบินพาณิชย์ตรี (CPL) ร่วมกับโรงเรียนการบินมาตรฐานสากล พร้อมเครื่องฝึกบินจำลอง (Flight Simulator) ระดับสูง",
        "curriculum_highlights": ["การฝึกบินจริงเพื่อรับใบอนุญาตนักบินพาณิชย์ตรี (CPL) และการบินด้วยเครื่องวัดประกอบการบิน (IR)", "เครื่องฝึกบินจำลองมาตรฐาน Boeing 737 / Airbus A320 และ Multi-Engine", "ความร่วมมือกับสายการบินชั้นนำ (Thai Airways, Bangkok Airways, AirAsia)"],
        "career_paths": ["นักบินพาณิชย์ประจำสายการบิน (Commercial Airline Pilot)", "นักบินส่วนบุคคล / องค์กร (Corporate Pilot)", "ครูฝึกการบิน (Flight Instructor)"],
        "tags": ["Aviation", "Commercial Pilot", "Flight Training", "CPL", "Airlines"],
        "website_url": "https://aviation.rsu.ac.th"
    },

    # =========================================================================
    # BU (Bangkok University - มหาวิทยาลัยกรุงเทพ)
    # =========================================================================
    {
        "id": "bu_film_ba_digital_film",
        "title_th": "หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาพยนตร์และสื่อดิจิทัล",
        "title_en": "Bachelor of Arts Program in Digital Film and Media",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ. (ภาพยนตร์และสื่อดิจิทัล)",
        "university": "Bangkok University",
        "university_th": "มหาวิทยาลัยกรุงเทพ",
        "faculty": "School of Digital Media and Cinematic Arts",
        "faculty_th": "คณะดิจิทัลมีเดียและศิลปะภาพยนตร์",
        "department": "Department of Film",
        "department_th": "สาขาวิชาภาพยนตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "48,000 บาท",
        "tuition_total": "384,000 บาท",
        "description": "อันดับ 1 ด้านภาพยนตร์และสื่อบันเทิงของสถาบันเอกชน เพียบพร้อมด้วยสตูดิโอถ่ายทำมาตรฐานฮอลลีวูด อุปกรณ์ ARRI / RED และ Virtual Production",
        "curriculum_highlights": ["BU Virtual Production Studio สตูดิโอจอ LED ขนาดยักษ์สำหรับการถ่ายทำระดับฮอลลีวูด", "กล้องและอุปกรณ์โปรดักชันระดับอุตสาหกรรมภาพยนตร์มาตรฐานโลก", "เครือข่ายผู้กำกับและโปรดิวเซอร์ชั้นนำของไทยและระดับนานาชาติ"],
        "career_paths": ["ผู้กำกับภาพยนตร์ / ซีรีส์สตรีมมิ่ง (Netflix, Prime, Disney+)", "ผู้กำกับภาพ (Director of Photography)", "โปรดิวเซอร์และนักเขียนบทภาพยนตร์"],
        "tags": ["Film Production", "Cinematic Arts", "Virtual Production", "Digital Media", "Bangkok University"],
        "website_url": "https://film.bu.ac.th"
    },
    {
        "id": "bu_busem_bba_entrepreneurship",
        "title_th": "หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาการเป็นเจ้าของธุรกิจและการบริหารกิจการ (BU-SEED / BUSEM)",
        "title_en": "Bachelor of Business Administration Program in Entrepreneurship (BUSEM)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ. (การเป็นเจ้าของธุรกิจ)",
        "university": "Bangkok University",
        "university_th": "มหาวิทยาลัยกรุงเทพ",
        "faculty": "School of Entrepreneurship and Management (BUSEM)",
        "faculty_th": "คณะการสร้างเจ้าของธุรกิจและการบริหารกิจการ (BUSEM)",
        "department": "Department of Entrepreneurship",
        "department_th": "สาขาวิชาการเป็นเจ้าของธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "360,000 บาท",
        "description": "สถาบันสร้างผู้ประกอบการแห่งแรกของไทย ร่วมมือกับ Babson College (สถาบันด้าน Entrepreneurship อันดับ 1 ของโลกในสหรัฐฯ)",
        "curriculum_highlights": ["หลักสูตรร่วมพัฒนากับ Babson College (No.1 Entrepreneurship USA)", "การทำธุรกิจจริงระหว่างเรียน พร้อมทุนสนับสนุนจากกองทุนตั้งต้น ม.กรุงเทพ", "Mentorship ตัวต่อตัวกับนักธุรกิจและผู้บริหารระดับประเทศ"],
        "career_paths": ["ผู้ประกอบการและเจ้าของธุรกิจใหม่ (Startup Founder)", "ทายาทธุรกิจและผู้สืบทอดกิจการครอบครัว", "Business Development Executive"],
        "tags": ["Entrepreneurship", "BUSEM", "Babson College", "Startup", "Business Administration"],
        "website_url": "https://busem.bu.ac.th"
    },

    # =========================================================================
    # KMUTNB (King Mongkut's University of Technology North Bangkok - มจพ.)
    # =========================================================================
    {
        "id": "kmutnb_eng_beng_rail_transport",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมระบบรางและการขนส่งสมัยใหม่",
        "title_en": "Bachelor of Engineering Program in Railway Systems and Modern Transportation Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมระบบราง)",
        "university": "King Mongkut's University of Technology North Bangkok",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ",
        "faculty": "TGGS / Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Railway Engineering",
        "department_th": "ภาควิชาวิศวกรรมระบบราง",
        "program_type": "ภาคปกติ / นานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "25,000 บาท",
        "tuition_total": "200,000 บาท",
        "description": "ศูนย์ความเป็นเลิศด้านวิศวกรรมระบบราง รถไฟความเร็วสูง รถไฟฟ้าใต้ดิน และการถ่ายทอดเทคโนโลยีตามมาตรฐานระบบรางเยอรมัน (RWTH Aachen)",
        "curriculum_highlights": ["การถ่ายทอดเทคโนโลยีระบบรางมาตรฐานเยอรมนี (TGGS / RWTH Aachen)", "การฝึกปฏิบัติงานจริงกับการรถไฟแห่งประเทศไทย (รฟท.), รฟม. และ BTS/BEM", "การออกแบบระบบขับเคลื่อน ขบวนรถไฟ และระบบอาณัติสัญญาณ"],
        "career_paths": ["วิศวกรระบบรางและรถไฟความเร็วสูง", "วิศวกรอาณัติสัญญาณและระบบควบคุมรถไฟฟ้า", "วิศวกรซ่อมบำรุงระบบขนส่งมวลชน"],
        "tags": ["Railway Engineering", "High-Speed Train", "Transportation", "German Engineering", "KMUTNB"],
        "website_url": "https://eng.kmutnb.ac.th"
    },
    {
        "id": "kmutnb_tggs_msc_automotive",
        "title_th": "หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมยานยนต์และระบบขับเคลื่อนไฟฟ้า (TGGS นานาชาติ)",
        "title_en": "Master of Engineering Program in Automotive and Electric Propulsion Systems (TGGS International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วศ.ม. (วิศวกรรมยานยนต์และระบบขับเคลื่อน)",
        "university": "King Mongkut's University of Technology North Bangkok",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ",
        "faculty": "The Sirindhorn International Thai-German Graduate School of Engineering (TGGS)",
        "faculty_th": "บัณฑิตวิทยาลัยวิศวกรรมศาสตร์นานาชาติสิรินธร ไทย-เยอรมัน (TGGS)",
        "department": "Department of Automotive Engineering",
        "department_th": "ภาควิชาวิศวกรรมยานยนต์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "60,000 บาท",
        "tuition_total": "240,000 บาท",
        "description": "หลักสูตรวิศวกรรมศาสตร์ชั้นนำร่วมกับ RWTH Aachen University ประเทศเยอรมนี เน้นเทคโนโลยียานยนต์ไฟฟ้า (EV) แบตเตอรี่ และยานยนต์ขับขี่อัตโนมัติ",
        "curriculum_highlights": ["มาตรฐานการศึกษาและคณาจารย์จาก RWTH Aachen University เยอรมนี", "การวิจัยระบบขับเคลื่อนไฟฟ้า มอเตอร์ และการจัดการแบตเตอรี่ (BMS)", "โอกาสฝึกงานและทำวิทยานิพนธ์ ณ ประเทศเยอรมนี"],
        "career_paths": ["Automotive EV Research Engineer", "Battery Systems Engineer", "Autonomous Vehicle Specialist", "อาจารย์มหาวิทยาลัย"],
        "tags": ["Automotive Engineering", "Electric Vehicle", "EV", "TGGS", "Germany", "KMUTNB"],
        "website_url": "https://tggs.kmutnb.ac.th"
    },

    # =========================================================================
    # RMUTT (Rajamangala University of Technology Thanyaburi - มทร.ธัญบุรี)
    # =========================================================================
    {
        "id": "rmutt_eng_beng_ev_robotics",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมยานยนต์ไฟฟ้าและหุ่นยนต์อุตสาหกรรม",
        "title_en": "Bachelor of Engineering Program in Electric Vehicle and Industrial Robotics Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมยานยนต์ไฟฟ้าและหุ่นยนต์)",
        "university": "Rajamangala University of Technology Thanyaburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลธัญบุรี",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Mechanical and Industrial Engineering",
        "department_th": "ภาควิชาวิศวกรรมเครื่องกลและอุตสาหการ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "140 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "เน้นการผลิตวิศวกรนักปฏิบัติ (Hands-on Engineer) ที่เชี่ยวชาญการดัดแปลงและผลิตยานยนต์ไฟฟ้า การควบคุมหุ่นยนต์แขนกล และระบบอัตโนมัติ",
        "curriculum_highlights": ["การลงมือปฏิบัติจริงในโรงงานต้นแบบยานยนต์ไฟฟ้าและแขนกลหุ่นยนต์", "การออกแบบชุดแบตเตอรี่และการควบคุมมอเตอร์ไฟฟ้ากระแสสลับ", "ความร่วมมือกับสมาคมยานยนต์ไฟฟ้าไทย (EVAT)"],
        "career_paths": ["วิศวกรยานยนต์ไฟฟ้า (EV Engineer)", "วิศวกรควบคุมระบบหุ่นยนต์และระบบอัตโนมัติ", "วิศวกรบริการและพัฒนาเทคนิค EV"],
        "tags": ["Electric Vehicle", "EV", "Robotics", "Hands-on Engineering", "RMUTT"],
        "website_url": "https://eng.rmutt.ac.th"
    },

    # =========================================================================
    # KU Specialised (Faculty of Forestry & Faculty of Fisheries)
    # =========================================================================
    {
        "id": "ku_forest_bsc_forestry",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวนศาสตร์และการจัดการป่าไม้คาร์บอนต่ำ",
        "title_en": "Bachelor of Science Program in Forestry and Carbon Forestry Management",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วนศาสตร์)",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Forestry",
        "faculty_th": "คณะวนศาสตร์",
        "department": "Department of Forest Management",
        "department_th": "ภาควิชาการจัดการป่าไม้",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "คณะวนศาสตร์แห่งเดียวในประเทศไทย เน้นการจัดการป่าไม้ การกักเก็บคาร์บอนในป่าไม้ (Forest Carbon Credit) การอนุรักษ์สัตว์ป่า และระบบนิเวศป่าเขตร้อน",
        "curriculum_highlights": ["การประเมินการกักเก็บคาร์บอนและคาร์บอนเครดิตภาคป่าไม้ (T-VER / Verra)", "การฝึกภาคสนามในป่าสงวนและอุทยานแห่งชาติทั่วประเทศ", "การใช้โดรนและภาพถ่ายดาวเทียมในการสำรวจและติดตามไฟป่า"],
        "career_paths": ["นักวิชาการป่าไม้ (กรมป่าไม้, กรมอุทยานแห่งชาติฯ)", "ผู้ประเมินและพัฒนาโครงการคาร์บอนเครดิตป่าไม้ (Carbon Credit Consultant)", "นักวิจัยนิเวศวิทยาป่าไม้"],
        "tags": ["Forestry", "Carbon Credit", "Ecology", "Wildlife", "Kasetsart Forestry"],
        "website_url": "https://forest.ku.ac.th"
    },
    {
        "id": "ku_fish_bsc_fisheries",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาการประมงและวิทยาศาสตร์ทางน้ำ",
        "title_en": "Bachelor of Science Program in Fisheries and Aquatic Science",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (การประมง)",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Fisheries",
        "faculty_th": "คณะประมง",
        "department": "Department of Aquaculture",
        "department_th": "ภาควิชาเพาะเลี้ยงสัตว์น้ำ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "คณะประมงชั้นนำของประเทศ ศึกษาชีววิทยาสัตว์น้ำ การเพาะเลี้ยงสัตว์น้ำเศรษฐกิจ เทคโนโลยีชีวภาพทางทะเล และการจัดการสิ่งแวดล้อมทางน้ำ",
        "curriculum_highlights": ["สถานีวิจัยประมงคลองวาฬ ศรีราชา และสมุทรสงคราม", "การปรับปรุงพันธุ์สัตว์น้ำเศรษฐกิจ (กุ้งขาว, ปลากะพง, ปลานิลจิตรลดา)", "นวัตกรรมการเลี้ยงสัตว์น้ำแบบปลอดภัยและยั่งยืน"],
        "career_paths": ["นักวิชาการประมง (กรมประมง)", "ผู้จัดการฟาร์มสัตว์น้ำและโรงเพาะฟัก", "ผู้เชี่ยวชาญด้านอาหารและเวชภัณฑ์สัตว์น้ำในบริษัทเอกชน (CP, Thai Union)"],
        "tags": ["Fisheries", "Aquatic Science", "Aquaculture", "Marine Biology", "Kasetsart"],
        "website_url": "https://fish.ku.ac.th"
    },
]
