# BUU, NIDA & MSU Official Curricula Dataset

BUU_MSU_NIDA_COURSES = [
    # =========================================================================
    # BUU (Burapha University - มหาวิทยาลัยบูรพา บางแสน / EEC)
    # =========================================================================
    # --- คณะแพทยศาสตร์ (Faculty of Medicine - BUU) ---
    {
        "id": "buu_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "Burapha University",
        "university_th": "มหาวิทยาลัยบูรพา",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Clinical Medicine",
        "department_th": "ภาควิชาแพทยศาสตร์คลินิก",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "250 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "ผลิตแพทย์ที่มีความเชี่ยวชาญด้านเวชศาสตร์บูรณาการ เวชศาสตร์ทางทะเล และการดูแลสุขภาพประชากรในพื้นที่เขตพัฒนาพิเศษภาคตะวันออก (EEC)",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิก ณ โรงพยาบาลมหาวิทยาลัยบูรพา และโรงพยาบาลศูนย์สมเด็จพระบรมราชเทวี ณ ศรีราชา", "ความเชี่ยวชาญเฉพาะทางด้านเวชศาสตร์ทางทะเลและเวชศาสตร์ใต้น้ำ", "การวิจัยด้านโรคอุบัติใหม่และสุขภาวะเขตอุตสาหกรรม"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไป", "แพทย์เฉพาะทาง", "แพทย์เวชศาสตร์ทางทะเลและอาชีวเวชศาสตร์"],
        "tags": ["Medicine", "Doctor", "Health Science", "EEC", "Burapha Medicine"],
        "website_url": "https://med.buu.ac.th"
    },
    # --- คณะวิทยาการสารสนเทศ (Faculty of Informatics - BUU) ---
    {
        "id": "buu_infor_bsc_ai_ds",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาปัญญาประดิษฐ์และวิทยาการข้อมูล",
        "title_en": "Bachelor of Science Program in Artificial Intelligence and Data Science",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (ปัญญาประดิษฐ์และวิทยาการข้อมูล)",
        "university": "Burapha University",
        "university_th": "มหาวิทยาลัยบูรพา",
        "faculty": "Faculty of Informatics",
        "faculty_th": "คณะวิทยาการสารสนเทศ",
        "department": "Department of Computer Science",
        "department_th": "ภาควิชาวิทยาการคอมพิวเตอร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "ศูนย์กลางการศึกษาด้าน AI และ Data ในพื้นที่ EEC เน้นการสร้างระบบ AI สำหรับโรงงานอัจฉริยะ โลจิสติกส์ท่าเรือ และการวิเคราะห์ข้อมูลธุรกิจ",
        "curriculum_highlights": ["การประยุกต์ใช้ AI ในภาคอุตสาหกรรมยานยนต์และโลจิสติกส์ท่าเรือแหลมฉบัง", "การเรียนรู้ Machine Learning, Deep Learning และ Big Data Analytics", "ความร่วมมือและฝึกสหกิจศึกษากับบริษัทเทคโนโลยีใน EEC"],
        "career_paths": ["AI Engineer", "Data Scientist", "Data Engineer", "Business Intelligence Specialist"],
        "tags": ["Artificial Intelligence", "AI", "Data Science", "Informatics", "EEC", "Burapha"],
        "website_url": "https://informatics.buu.ac.th"
    },
    # --- คณะโลจิสติกส์ (Faculty of Logistics - BUU) ---
    {
        "id": "buu_log_bba_maritime",
        "title_th": "หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาการจัดการพาณิชยนาวีและการขนส่งทางทะเล",
        "title_en": "Bachelor of Business Administration Program in Maritime Commerce and Shipping Management",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ. (การจัดการพาณิชยนาวี)",
        "university": "Burapha University",
        "university_th": "มหาวิทยาลัยบูรพา",
        "faculty": "Faculty of Logistics",
        "faculty_th": "คณะโลจิสติกส์",
        "department": "Department of Maritime Logistics",
        "department_th": "ภาควิชาการจัดการพาณิชยนาวี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "176,000 บาท",
        "description": "คณะโลจิสติกส์แห่งแรกของประเทศไทย ตั้งอยู่ใจกลางฮับโลจิสติกส์ทางทะเล EEC เน้นการบริหารท่าเรือ สายการเดินเรือ และพิธีการศุลกากรระหว่างประเทศ",
        "curriculum_highlights": ["การบริหารจัดการท่าเทียบเรือตู้สินค้าและเรือบรรทุกสินค้าเทกอง (Port Operations)", "กฎหมายพาณิชยนาวี ประกันภัยทางทะเล และสัญญาระหว่างประเทศ (Incoterms)", "การฝึกงานกับท่าเรือแหลมฉบัง ท่าเรือกรุงเทพ และสายการเดินเรือระดับโลก"],
        "career_paths": ["ผู้บริหารและปฏิบัติการประจำท่าเรือและสายการเดินเรือ", "ตัวแทนออกของและผู้วางแผนการขนส่งระหว่างประเทศ (Freight Forwarder)", "ผู้จัดการโลจิสติกส์และซัพพลายเชน"],
        "tags": ["Logistics", "Maritime", "Shipping", "Port Management", "EEC", "Supply Chain"],
        "website_url": "https://logistics.buu.ac.th"
    },
    # --- คณะวิทยาศาสตร์ทางทะเล / สถาบันวิทยาศาสตร์ทางทะเล (BUU Marine Science) ---
    {
        "id": "buu_sci_bsc_aquatic_science",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์การประมงและทรัพยากรทางน้ำ",
        "title_en": "Bachelor of Science Program in Aquatic Science and Fisheries Resources",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาศาสตร์การประมงและทรัพยากรทางน้ำ)",
        "university": "Burapha University",
        "university_th": "มหาวิทยาลัยบูรพา",
        "faculty": "Faculty of Science",
        "faculty_th": "คณะวิทยาศาสตร์",
        "department": "Department of Aquatic Science",
        "department_th": "ภาควิชาวาริชศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "ศึกษาชีววิทยาทางทะเล การเพาะเลี้ยงสัตว์น้ำเศรษฐกิจ การจัดการคุณภาพน้ำชายฝั่ง และการอนุรักษ์ทรัพยากรทางน้ำอ่าวไทย",
        "curriculum_highlights": ["การเรียนรู้ร่วมกับสถาบันวิทยาศาสตร์ทางทะเล มหาวิทยาลัยบูรพา (พิพิธภัณฑ์สัตว์น้ำบางแสน)", "เทคโนโลยีการเพาะเลี้ยงสัตว์น้ำความหนาแน่นสูงและระบบปิด (RAS)", "การตรวจวิเคราะห์คุณภาพน้ำและสิ่งแวดล้อมทางน้ำชายฝั่ง"],
        "career_paths": ["นักวิชาการประมงและสิ่งแวดล้อมทางน้ำ", "ผู้จัดการฟาร์มเพาะเลี้ยงสัตว์น้ำเศรษฐกิจ", "นักวิจัยชีววิทยาทางทะเล"],
        "tags": ["Aquatic Science", "Marine Biology", "Fisheries", "Aquaculture", "Burapha"],
        "website_url": "https://sci.buu.ac.th"
    },

    # =========================================================================
    # NIDA (National Institute of Development Administration - สถาบันบัณฑิตพัฒนบริหารศาสตร์ นิด้า)
    # =========================================================================
    # --- Graduate School of Business Administration (GSBA - NIDA) ---
    {
        "id": "nida_gsba_mba_flexible",
        "title_th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต (Flexible MBA / Young Executive MBA)",
        "title_en": "Master of Business Administration Program (NIDA MBA)",
        "degree_level": "ปริญญาโท",
        "degree_name": "บธ.ม. (บริหารธุรกิจ)",
        "university": "National Institute of Development Administration",
        "university_th": "สถาบันบัณฑิตพัฒนบริหารศาสตร์ (นิด้า)",
        "faculty": "NIDA Business School (GSBA)",
        "faculty_th": "คณะบริหารธุรกิจ (GSBA)",
        "department": "Department of Business Administration",
        "department_th": "สาขาวิชาบริหารธุรกิจ",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "39 หน่วยกิต",
        "tuition_per_semester": "55,000 บาท",
        "tuition_total": "220,000 บาท",
        "description": "สถาบันบริหารธุรกิจแห่งแรกของประเทศไทยที่ได้รับการรับรองมาตรฐานระดับโลก AACSB ผลิตผู้นำธุรกิจ ผู้บริหาร และผู้ประกอบการชั้นนำ",
        "curriculum_highlights": ["ได้รับการรับรองมาตรฐานการศึกษาธุรกิจระดับโลก AACSB International", "การเรียนรู้ผ่านกรณีศึกษาธุรกิจระดับโลก (Harvard Case Studies)", "เครือข่ายศิษย์เก่าระดับผู้บริหารระดับสูง (C-Level) ทั่วประเทศ"],
        "career_paths": ["ผู้บริหารระดับสูงในองค์กรชั้นนำ (CEO, CFO, CMO)", "ผู้ประกอบการและนักลงทุน", "ที่ปรึกษาด้านกลยุทธ์ธุรกิจและการจัดการ"],
        "tags": ["MBA", "Business Administration", "NIDA", "AACSB", "Leadership"],
        "website_url": "https://mba.nida.ac.th"
    },
    {
        "id": "nida_as_msc_datascience",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาการข้อมูลและการวิเคราะห์ (Data Science and Analytics)",
        "title_en": "Master of Science Program in Data Science and Analytics",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (วิทยาการข้อมูลและการวิเคราะห์)",
        "university": "National Institute of Development Administration",
        "university_th": "สถาบันบัณฑิตพัฒนบริหารศาสตร์ (นิด้า)",
        "faculty": "Graduate School of Applied Statistics",
        "faculty_th": "คณะสถิติประยุกต์",
        "department": "Department of Data Science",
        "department_th": "สาขาวิชาวิทยาการข้อมูล",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "180,000 บาท",
        "description": "หลักสูตรชั้นนำด้าน Data Science และ AI สำหรับการตัดสินใจเชิงกลยุทธ์ การวิเคราะห์ Big Data, Deep Learning และ Business Analytics",
        "curriculum_highlights": ["การสร้างแบบจำลอง AI, Machine Learning และ Deep Learning เชิงประยุกต์", "การบริหารจัดการแพลตฟอร์ม Big Data และ Cloud Analytics", "การประยุกต์ใช้ Data Science ในธุรกิจ การเงิน และนโยบายภาครัฐ"],
        "career_paths": ["Chief Data Officer (CDO)", "Lead Data Scientist", "Machine Learning Engineer", "Business Analytics Manager"],
        "tags": ["Data Science", "Analytics", "Machine Learning", "Big Data", "NIDA"],
        "website_url": "https://as.nida.ac.th"
    },
    {
        "id": "nida_gspa_mpa",
        "title_th": "หลักสูตรรัฐประศาสนศาสตรมหาบัณฑิต (MPA)",
        "title_en": "Master of Public Administration Program (MPA)",
        "degree_level": "ปริญญาโท",
        "degree_name": "รป.ม. (รัฐประศาสนศาสตร์)",
        "university": "National Institute of Development Administration",
        "university_th": "สถาบันบัณฑิตพัฒนบริหารศาสตร์ (นิด้า)",
        "faculty": "Graduate School of Public Administration",
        "faculty_th": "คณะรัฐประศาสนศาสตร์",
        "department": "Department of Public Administration",
        "department_th": "สาขาวิชารัฐประศาสนศาสตร์",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "42,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "สถาบันรัฐประศาสนศาสตร์อันดับ 1 ของไทย เน้นการบริหารภาครัฐเชิงยุทธศาสตร์ การจัดการนโยบายสาธารณะ และการนำองค์กรสู่ดิจิทัล",
        "curriculum_highlights": ["การวิเคราะห์และประเมินนโยบายสาธารณะเชิงลึก", "การบริหารราชการแผ่นดินและธรรมาภิบาลดิจิทัล (Digital Governance)", "เครือข่ายผู้นำภาครัฐและข้าราชการระดับสูงทั่วประเทศ"],
        "career_paths": ["ข้าราชการและผู้บริหารระดับสูงในหน่วยงานภาครัฐ (ปลัดกระทรวง, อธิบดี)", "นักวิเคราะห์นโยบายและแผน", "ผู้บริหารรัฐวิสาหกิจและองค์กรไม่แสวงหากำไร"],
        "tags": ["Public Administration", "MPA", "Public Policy", "Governance", "NIDA"],
        "website_url": "https://gspa.nida.ac.th"
    },
    {
        "id": "nida_econ_phd_economics",
        "title_th": "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาเศรษฐศาสตร์เพื่อการพัฒนา (หลักสูตรนานาชาติ)",
        "title_en": "Doctor of Philosophy Program in Development Economics (International Program)",
        "degree_level": "ปริญญาเอก",
        "degree_name": "ปร.ด. (เศรษฐศาสตร์เพื่อการพัฒนา)",
        "university": "National Institute of Development Administration",
        "university_th": "สถาบันบัณฑิตพัฒนบริหารศาสตร์ (นิด้า)",
        "faculty": "Graduate School of Development Economics",
        "faculty_th": "คณะพัฒนาการเศรษฐกิจ",
        "department": "Department of Economics",
        "department_th": "สาขาวิชาเศรษฐศาสตร์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "3 ปี",
        "total_credits": "48 หน่วยกิต",
        "tuition_per_semester": "60,000 บาท",
        "tuition_total": "360,000 บาท",
        "description": "ผลิตนักเศรษฐศาสตร์และนักวิจัยระดับปริญญาเอกที่เชี่ยวชาญเศรษฐมิติเชิงลึก เศรษฐศาสตร์การคลัง และการออกแบบนโยบายพัฒนาเศรษฐกิจมหภาค",
        "curriculum_highlights": ["เศรษฐมิติขั้นสูง (Advanced Econometrics) และการวิเคราะห์เชิงปริมาณ", "การวิจัยนโยบายเศรษฐกิจเพื่อการพัฒนาที่ยั่งยืน", "คณาจารย์ผู้ทรงคุณวุฒิระดับแนวหน้าของประเทศและระดับสากล"],
        "career_paths": ["นักเศรษฐศาสตร์อาวุโสประจำธนาคารแห่งประเทศไทยและกระทรวงการคลัง", "นักวิจัยสถาบันวิจัยเศรษฐกิจ (TDRI, ธนาคารโลก, ADB)", "อาจารย์ประจำมหาวิทยาลัย"],
        "tags": ["Economics", "Development Economics", "Econometrics", "Ph.D.", "NIDA"],
        "website_url": "https://econ.nida.ac.th"
    },

    # =========================================================================
    # MSU (Mahasarakham University - มหาวิทยาลัยมหาสารคาม มมส)
    # =========================================================================
    # --- คณะเภสัชศาสตร์ (Faculty of Pharmacy - MSU) ---
    {
        "id": "msu_pharm_bpharm_care",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาการบริบาลทางเภสัชกรรม",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Care",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (การบริบาลทางเภสัชกรรม)",
        "university": "Mahasarakham University",
        "university_th": "มหาวิทยาลัยมหาสารคาม",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Clinical Pharmacy",
        "department_th": "สาขาวิชาเภสัชกรรมคลินิก",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "224 หน่วยกิต",
        "tuition_per_semester": "24,000 บาท",
        "tuition_total": "288,000 บาท",
        "description": "คณะเภสัชศาสตร์ชั้นนำแห่งภาคอีสาน เน้นการบริบาลทางเภสัชกรรม การใช้ยาสมเหตุผลในชุมชน และการคุ้มครองผู้บริโภคด้านสุขภาพ",
        "curriculum_highlights": ["การฝึกปฏิบัติงานบริบาลทางเภสัชกรรมในโรงพยาบาลศูนย์และโรงพยาบาลชุมชนภาคอีสาน", "ศูนย์วิจัยและพัฒนาผลิตภัณฑ์สมุนไพรและยาแผนโบราณ", "การบูรณาการระบบบริการปฐมภูมิและเภสัชกรรมครอบครัว"],
        "career_paths": ["เภสัชกรประจำโรงพยาบาล", "เภสัชกรคลินิก", "เภสัชกรชุมชน (เจ้าของร้านยา)", "เภสัชกรคุ้มครองผู้บริโภค"],
        "tags": ["Pharmacy", "Pharmaceutical Care", "Health Science", "MSU Pharmacy"],
        "website_url": "https://pharmacy.msu.ac.th"
    },
    # --- คณะแพทยศาสตร์ (Faculty of Medicine - MSU) ---
    {
        "id": "msu_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "Mahasarakham University",
        "university_th": "มหาวิทยาลัยมหาสารคาม",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Medicine",
        "department_th": "สาขาวิชาแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "252 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "ผลิตแพทย์ผู้เชี่ยวชาญการดูแลสุขภาพระดับปฐมภูมิและเวชศาสตร์ครอบครัว มุ่งเน้นการแก้ปัญหาสาธารณสุขและโรคประจำถิ่นในภาคตะวันออกเฉียงเหนือ",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิก ณ โรงพยาบาลสุทธาเวช คณะแพทยศาสตร์ มมส และโรงพยาบาลเครือข่าย", "การบูรณาการเวชศาสตร์ครอบครัวและชุมชนชนบทอย่างเข้มข้น", "การวิจัยการแพทย์ปฐมภูมิและโรคเขตร้อนในภาคอีสาน"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไป", "แพทย์เฉพาะทาง", "แพทย์เวชศาสตร์ครอบครัวประจำโรงพยาบาลชุมชน"],
        "tags": ["Medicine", "Doctor", "Health Science", "Family Medicine", "MSU"],
        "website_url": "https://med.msu.ac.th"
    },
    # --- คณะวิทยาการสารสนเทศ (Faculty of Informatics - MSU) ---
    {
        "id": "msu_infor_bsc_it",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีสารสนเทศ",
        "title_en": "Bachelor of Science Program in Information Technology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคโนโลยีสารสนเทศ)",
        "university": "Mahasarakham University",
        "university_th": "มหาวิทยาลัยมหาสารคาม",
        "faculty": "Faculty of Informatics",
        "faculty_th": "คณะวิทยาการสารสนเทศ",
        "department": "Department of Information Technology",
        "department_th": "สาขาวิชาเทคโนโลยีสารสนเทศ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "มุ่งเน้นการพัฒนานักเทคโนโลยีสารสนเทศที่มีทักษะการพัฒนาซอฟต์แวร์ คลาวด์คอมพิวติง ระบบเครือข่าย และการดูแลความปลอดภัยของข้อมูล",
        "curriculum_highlights": ["การพัฒนาเว็บแอปพลิเคชันและโมบายล์แอปพลิเคชันเชิงปฏิบัติ", "การบริหารจัดการเครือข่ายและระบบคลาวด์", "โครงการโครงงานเทคโนโลยีสารสนเทศร่วมกับชุมชนและธุรกิจท้องถิ่น"],
        "career_paths": ["Software Developer", "IT Support / Network Administrator", "Web & Mobile Developer", "Database Administrator"],
        "tags": ["Information Technology", "Software Development", "Cloud", "Informatics", "MSU"],
        "website_url": "https://it.msu.ac.th"
    },
]
