# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/chula_vrc_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "chulalongk_centerofex_patarakul_002",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Center of Excellence in Vaccine Research and Development (Chula VRC)",
    "faculty_th": "ศูนย์วิจัยวัคซีน คณะแพทยศาสตร์",
    "department": "ภาควิชาจุลชีววิทยา",
    "department_th": "ภาควิชาจุลชีววิทยา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kanitha",
    "last_name": "Patarakul",
    "full_name": "Kanitha Patarakul",
    "full_name_th": "ผศ.ดร. คณิตา ภัทรกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.chulavrc.org/staff/kanitha-patarakul/",
    "education": [
      "M.D., Faculty of Medicine Chulalongkorn University",
      "Ph.D., Georgetown University"
    ],
    "research_interests": [
      "Pathogenesis of Leptospirosis",
      "Leptospirosis vaccine",
      "Outer membrane proteins",
      "DNA and Subunit vaccine"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_centerofex_palaga_003",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Center of Excellence in Vaccine Research and Development (Chula VRC)",
    "faculty_th": "ศูนย์วิจัยวัคซีน คณะแพทยศาสตร์",
    "department": "ภาควิชาจุลชีววิทยา คณะวิทยาศาสตร์",
    "department_th": "ภาควิชาจุลชีววิทยา คณะวิทยาศาสตร์",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Tanapat",
    "last_name": "Palaga",
    "full_name": "Tanapat Palaga",
    "full_name_th": "ดร. ธนภัทร ปาลกะวงศ์ ณ อยุธยา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.chulavrc.org/staff/tanapat-palaga/",
    "education": [
      "Ph.D."
    ],
    "research_interests": [
      "Vaccine development for tuberculosis (TB)",
      "Cancer vaccine",
      "mRNA-based vaccine",
      "Novel vaccine delivery systems"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_centerofex_sirivichayakul_004",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Center of Excellence in Vaccine Research and Development (Chula VRC)",
    "faculty_th": "ศูนย์วิจัยวัคซีน คณะแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Sunee",
    "last_name": "Sirivichayakul",
    "full_name": "Sunee Sirivichayakul",
    "full_name_th": "ดร. สุนีย์ สิริวิชยากุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.chulavrc.org/staff/sunee-sirivichayakul/",
    "education": [
      "Bachelor degree, Chulalongkorn University",
      "Master degree, Chulalongkorn University",
      "Ph.D. in Immunology and Microbiology, Chulalongkorn University"
    ],
    "research_interests": [
      "HIV virology",
      "HIV immunology",
      "HIV molecular biology",
      "HIV DNA vaccine"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_centerofex_ketloy_005",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Center of Excellence in Vaccine Research and Development (Chula VRC)",
    "faculty_th": "ศูนย์วิจัยวัคซีน คณะแพทยศาสตร์",
    "department": "ภาควิชาห้องปฏิบัติการทางการแพทย์",
    "department_th": "ภาควิชาห้องปฏิบัติการทางการแพทย์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Chutitorn",
    "last_name": "Ketloy",
    "full_name": "Chutitorn Ketloy",
    "full_name_th": "ผศ.ดร. ชุติธร เกตุลอย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.chulavrc.org/staff/chutitorn-ketloy/",
    "education": [
      "Ph.D. in Biomedical Sciences, Chulalongkorn University"
    ],
    "research_interests": [
      "DNA-based dengue vaccine"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_centerofex_prompetchara_006",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Center of Excellence in Vaccine Research and Development (Chula VRC)",
    "faculty_th": "ศูนย์วิจัยวัคซีน คณะแพทยศาสตร์",
    "department": "ภาควิชาชีวเคมีและจุลชีววิทยา คณะเภสัชศาสตร์",
    "department_th": "ภาควิชาชีวเคมีและจุลชีววิทยา คณะเภสัชศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Eakachai",
    "last_name": "Prompetchara",
    "full_name": "Eakachai Prompetchara",
    "full_name_th": "อ.ดร. เอกชัย พรเพชราภรณ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.chulavrc.org/staff/eakachai-prompetchara/",
    "education": [
      "Ph.D. in Biomedical Sciences, Chulalongkorn University, 2014"
    ],
    "research_interests": [
      "Immunology",
      "Virology",
      "Molecular Biology",
      "Dengue DNA vaccine",
      "Viral vaccine development",
      "Nucleic acid-based vaccine (DNA, mRNA)",
      "Virus-like particles",
      "Recombinant proteins",
      "Humanized mice model for vaccine immunogenicity testing"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_centerofex_boonyasuppayako_007",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Center of Excellence in Vaccine Research and Development (Chula VRC)",
    "faculty_th": "ศูนย์วิจัยวัคซีน คณะแพทยศาสตร์",
    "department": "ภาควิชาจุลชีววิทยา คณะแพทยศาสตร์",
    "department_th": "ภาควิชาจุลชีววิทยา คณะแพทยศาสตร์",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Siwaporn",
    "last_name": "Boonyasuppayakorn",
    "full_name": "Siwaporn Boonyasuppayakorn",
    "full_name_th": "ดร. สิริพร บุญสุพยากร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.chulavrc.org/staff/siwaporn-boonyasuppayakorn/",
    "education": [
      "M.D., 2007",
      "Ph.D. in Georgetown University Medical Center, Washington, DC, USA, 2013"
    ],
    "research_interests": [
      "Virology",
      "Respiratory syncytial virus infection",
      "Anti-dengue drug discovery",
      "Functional analysis of flaviviral enzymes",
      "Academic drug discovery",
      "Zika viruses"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_centerofex_buranapraditkun_008",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Center of Excellence in Vaccine Research and Development (Chula VRC)",
    "faculty_th": "ศูนย์วิจัยวัคซีน คณะแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Supranee",
    "last_name": "Buranapraditkun",
    "full_name": "Supranee Buranapraditkun",
    "full_name_th": "ดร. สุปราณี บูรณประดิษฐ์กุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.chulavrc.org/staff/supranee-buranapraditkun/",
    "education": [
      "Ph.D. in Molecular Biology and Immunology, Chulalongkorn University, 2012"
    ],
    "research_interests": [
      "Acute HIV infection cohort (RV254)",
      "Immune response",
      "T and B cells",
      "HIV-1 infection",
      "Vaccine design and development",
      "Broadly neutralizing antibodies"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_centerofex_pitakpolrat_009",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Center of Excellence in Vaccine Research and Development (Chula VRC)",
    "faculty_th": "ศูนย์วิจัยวัคซีน คณะแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Patrawadee",
    "last_name": "Pitakpolrat",
    "full_name": "Patrawadee Pitakpolrat",
    "full_name_th": "อ. ภัทรวดี พิทักษ์פולรัตน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.chulavrc.org/staff/patrawadee-pitakpolrat/",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_centerofex_tharakhet_010",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Center of Excellence in Vaccine Research and Development (Chula VRC)",
    "faculty_th": "ศูนย์วิจัยวัคซีน คณะแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Kittipan",
    "last_name": "Tharakhet",
    "full_name": "Kittipan Tharakhet",
    "full_name_th": "อ. กิตติพันธ์ ธาระเขตต์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.chulavrc.org/staff/kittipan-tharakhet/",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
