# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/chula_law_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "chulalongk_facultyofl_chantharathom_002",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Kanaphon",
    "last_name": "Chantharathom",
    "full_name": "Kanaphon Chantharathom",
    "full_name_th": "ศ.ดร. คณพล จันทน์หอม",
    "role": "อาจารย์ประจำ",
    "email": "kanaphon.c@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_allanrosen_003",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Daniel",
    "last_name": "Allan Rosen",
    "full_name": "Daniel Allan Rosen",
    "full_name_th": "ศ.ดร. แดเนียล อัลลัน โรเซน",
    "role": "อาจารย์ประจำ",
    "email": "daniel@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_sothipan_004",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Sanankorn",
    "last_name": "Sothipan",
    "full_name": "Sanankorn Sothipan",
    "full_name_th": "ศ.ดร. ศนันท์กรณ์ โสตถิพันธุ์",
    "role": "อาจารย์ประจำ",
    "email": "ajarnkorn@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_thanitcul_005",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Sakda",
    "last_name": "Thanitcul",
    "full_name": "Sakda Thanitcul",
    "full_name_th": "ศ.ดร. ศักดา ธนิตกุล",
    "role": "อาจารย์ประจำ",
    "email": "sakda.t@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_rerkasut_006",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Tachmai",
    "last_name": "Rerkasut",
    "full_name": "Tachmai Rerkasut",
    "full_name_th": "ศ. ทัชมัย ฤกษะสุต",
    "role": "อาจารย์ประจำ",
    "email": "tashmai.r@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_komalarjun_007",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Kanpirom",
    "last_name": "Komalarjun",
    "full_name": "Kanpirom Komalarjun",
    "full_name_th": "รศ.ดร. กรรภิรมย์ โกมลารชุน",
    "role": "อาจารย์ประจำ",
    "email": "kanpirom@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_sribuaiam_008",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Khaneungnit",
    "last_name": "Sribua-iam",
    "full_name": "Khaneungnit Sribua-iam",
    "full_name_th": "รศ.ดร. คนึงนิจ ศรีบัวเอี่ยม",
    "role": "อาจารย์ประจำ",
    "email": "ajarnnoi@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_ngamapichon_009",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Chanisa",
    "last_name": "Ngamapichon",
    "full_name": "Chanisa Ngamapichon",
    "full_name_th": "รศ.ดร. ชนิสา งามอภิชน",
    "role": "อาจารย์ประจำ",
    "email": "chanisa.n@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_pruksacholavit_011",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Panthip",
    "last_name": "Pruksacholavit",
    "full_name": "Panthip Pruksacholavit",
    "full_name_th": "รศ.ดร. ปานทิพย์ พฤกษาชลวิทย์",
    "role": "อาจารย์ประจำ",
    "email": "panthip.p@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_eiamchamroonlar_012",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Piti",
    "last_name": "Eiamchamroonlarp",
    "full_name": "Piti Eiamchamroonlarp",
    "full_name_th": "รศ.ดร. ปิติ เอี่ยมจำรูญลาภ",
    "role": "อาจารย์ประจำ",
    "email": "piti.e@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_boonaramrueng_013",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Piyabutr",
    "last_name": "Boonaramrueng",
    "full_name": "Piyabutr Boonaramrueng",
    "full_name_th": "รศ.ดร. ปิยะบุตร บุญอร่ามเรือง",
    "role": "อาจารย์ประจำ",
    "email": "piyabutr.b@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_liangboonprakon_014",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pornson",
    "last_name": "Liangboonprakong",
    "full_name": "Pornson Liangboonprakong",
    "full_name_th": "รศ.ดร. พรสันต์ เลี้ยงบุญเลิศชัย",
    "role": "อาจารย์ประจำ",
    "email": "pornson.l@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_kowpatanakit_015",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Patanaporn",
    "last_name": "Kowpatanakit",
    "full_name": "Patanaporn Kowpatanakit",
    "full_name_th": "รศ.ดร. พัฒนาพร โกวพัฒนกิจ",
    "role": "อาจารย์ประจำ",
    "email": "patanaporn.k@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_satayanurak_016",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pawat",
    "last_name": "Satayanurak",
    "full_name": "Pawat Satayanurak",
    "full_name_th": "รศ.ดร. ภาวัฒน์ สัตยานุรักษ์",
    "role": "อาจารย์ประจำ",
    "email": "pawat.s@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_jumpa_017",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Manit",
    "last_name": "Jumpa",
    "full_name": "Manit Jumpa",
    "full_name_th": "รศ.ดร. มานิตย์ จุมปา",
    "role": "อาจารย์ประจำ",
    "email": "manit_j@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_rachapradit_018",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Wimpat",
    "last_name": "Rachapradit",
    "full_name": "Wimpat Rachapradit",
    "full_name_th": "รศ.ดร. วิมพัทธ์ ราชประดิษฐ์",
    "role": "อาจารย์ประจำ",
    "email": "wimpat.r@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_thaweejamsap_019",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Suphasit",
    "last_name": "Thaweejamsap",
    "full_name": "Suphasit Thaweejamsap",
    "full_name_th": "รศ.ดร. ศุภศิษฏ์ ทวีแจ่มทรัพย์",
    "role": "อาจารย์ประจำ",
    "email": "suphasit.t@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_reekie_020",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Surutchada",
    "last_name": "Reekie",
    "full_name": "Surutchada Reekie",
    "full_name_th": "รศ.ดร. สุรัชดา รีคี",
    "role": "อาจารย์ประจำ",
    "email": "surutchada.r@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_pinkaew_021",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Angkanawadee",
    "last_name": "Pinkaew",
    "full_name": "Angkanawadee Pinkaew",
    "full_name_th": "รศ.ดร. อังคณาวดี ปิ่นแก้ว",
    "role": "อาจารย์ประจำ",
    "email": "angkanawadee@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_engchanil_022",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Aua-aree",
    "last_name": "Engchanil",
    "full_name": "Aua-aree Engchanil",
    "full_name_th": "รศ.ดร. เอื้ออารีย์ อิ้งจะนิล",
    "role": "อาจารย์ประจำ",
    "email": "aua-aree.e@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_phetranond_023",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kansak",
    "last_name": "Phetranond",
    "full_name": "Kansak Phetranond",
    "full_name_th": "ผศ.ดร. กัญจน์ศักดิ์ เพชรานนท์",
    "role": "อาจารย์ประจำ",
    "email": "kansak.b@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_khaosaeng_024",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Khanuengnit",
    "last_name": "Khaosaeng",
    "full_name": "Khanuengnit Khaosaeng",
    "full_name_th": "ผศ.ดร. คนึงนิจ ขาวแสง",
    "role": "อาจารย์ประจำ",
    "email": "khanuengnit@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_vidyavarakul_025",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Chotika",
    "last_name": "Vidyavarakul",
    "full_name": "Chotika Vidyavarakul",
    "full_name_th": "ผศ.ดร. โชติกา วิทยาวรากุล",
    "role": "อาจารย์ประจำ",
    "email": "chotika.w@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_jittirat_026",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Natchapol",
    "last_name": "Jittirat",
    "full_name": "Natchapol Jittirat",
    "full_name_th": "ผศ.ดร. ณัชพล จิตติรัตน์",
    "role": "อาจารย์ประจำ",
    "email": "natchapol.j@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_silppiromsuk_027",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Thidarat",
    "last_name": "Silppiromsuk",
    "full_name": "Thidarat Silppiromsuk",
    "full_name_th": "ผศ.ดร. ธิดารัตน์ ศิลปภิรมย์สุข",
    "role": "อาจารย์ประจำ",
    "email": "tidarat.s@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_thanodomdet_028",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Papawadee",
    "last_name": "Thanodomdet",
    "full_name": "Papawadee Thanodomdet",
    "full_name_th": "ผศ.ดร. ปภาวดี ธโนดมเดช",
    "role": "อาจารย์ประจำ",
    "email": "papawadee@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_sermsiltham_029",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Pramote",
    "last_name": "Sermsiltham",
    "full_name": "Pramote Sermsiltham",
    "full_name_th": "ผศ.ดร. ปราโมทย์ เสริมศีลธรรม",
    "role": "อาจารย์ประจำ",
    "email": "pramote.s@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_niyom_030",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Patch",
    "last_name": "Niyomศิลป์",
    "full_name": "Patch Niyomศิลป์",
    "full_name_th": "ผศ.ดร. พัชร์ นิยมศิลป",
    "role": "อาจารย์ประจำ",
    "email": "pat.n@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_choksuwattanasa_031",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Peerapat",
    "last_name": "Choksuwattanasakul",
    "full_name": "Peerapat Choksuwattanasakul",
    "full_name_th": "ผศ.ดร. พีรพัฒ โชคสุวัฒนสกุล",
    "role": "อาจารย์ประจำ",
    "email": "peerapat@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_damrongvudh_032",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Poomsiri",
    "last_name": "Damrongvudh",
    "full_name": "Poomsiri Damrongvudh",
    "full_name_th": "ผศ.ดร. ภูมิศิริ ดำรงวุฒิ",
    "role": "อาจารย์ประจำ",
    "email": "poomsiri@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_malsukhum_033",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Worapol",
    "last_name": "Malsukhum",
    "full_name": "Worapol Malsukhum",
    "full_name_th": "ผศ.ดร. วรพล มาลสุขุม",
    "role": "อาจารย์ประจำ",
    "email": "v.malsukhum@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_wathinpongphan_034",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Wirote",
    "last_name": "Wathinpongphan",
    "full_name": "Wirote Wathinpongphan",
    "full_name_th": "ผศ.ดร. วิโรจน์ วาทินพงศ์พันธ์",
    "role": "อาจารย์ประจำ",
    "email": "wirote.w@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_wiwattanawattan_035",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sipim",
    "last_name": "Wiwattanawattana",
    "full_name": "Sipim Wiwattanawattana",
    "full_name_th": "ผศ.ดร. สิพิม วิวัฒนวัฒนา",
    "role": "อาจารย์ประจำ",
    "email": "sipim@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_khowilaikul_036",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sirikanya",
    "last_name": "Khowilaikul",
    "full_name": "Sirikanya Khowilaikul",
    "full_name_th": "ผศ.ดร. สิริกัญญา โฆวิไลกูล",
    "role": "อาจารย์ประจำ",
    "email": "ksirikanya@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_tangnirundorn_037",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Arm",
    "last_name": "Tangnirundorn",
    "full_name": "Arm Tangnirundorn",
    "full_name_th": "ผศ.ดร. อาร์ม ตั้งนิรันดร",
    "role": "อาจารย์ประจำ",
    "email": "armtung@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_phiromphanit_038",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Chattames",
    "last_name": "Phiromphanit",
    "full_name": "Chattames Phiromphanit",
    "full_name_th": "ผศ. ฉัฏฐเมษ ภิรมย์พานิช",
    "role": "อาจารย์ประจำ",
    "email": "chattames@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_sirithaporn_039",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Thidaporn",
    "last_name": "Sirithaporn",
    "full_name": "Thidaporn Sirithaporn",
    "full_name_th": "ผศ. ธิดาพร ศิริถาพร",
    "role": "อาจารย์ประจำ",
    "email": "thidaporn.s@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_prasertsak_040",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Kornkamon",
    "last_name": "Prasertsak",
    "full_name": "Kornkamon Prasertsak",
    "full_name_th": "อ.ดร. กรณ์กมล ประเสริฐศักดิ์",
    "role": "อาจารย์ประจำ",
    "email": "kornkamon@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_chaidehsuriya_041",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Jutaporn",
    "last_name": "Chaidehsuriya",
    "full_name": "Jutaporn Chaidehsuriya",
    "full_name_th": "อ.ดร. จุฑาพร ชัยเดชสุริยะ",
    "role": "อาจารย์ประจำ",
    "email": "jutaporn.c@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_tengamnuay_042",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Thitinant",
    "last_name": "Tengamnuay",
    "full_name": "Thitinant Tengamnuay",
    "full_name_th": "อ.ดร. ฐิตินันท์ เต็งอำนวย",
    "role": "อาจารย์ประจำ",
    "email": "thitinant.t@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_saensawat_043",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Thossaporn",
    "last_name": "Saensawat",
    "full_name": "Thossaporn Saensawat",
    "full_name_th": "อ.ดร. ทศพร แสนสวัสดิ์",
    "role": "อาจารย์ประจำ",
    "email": "thossaporn@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_songsujaritkul_044",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Warut",
    "last_name": "Songsujaritkul",
    "full_name": "Warut Songsujaritkul",
    "full_name_th": "อ.ดร. วรุตม์ ทรงสุจริตกุล",
    "role": "อาจารย์ประจำ",
    "email": "warut@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_petcharatana_045",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Sriprapha",
    "last_name": "Petcharatana",
    "full_name": "Sriprapha Petcharatana",
    "full_name_th": "อ.ดร. ศรีประภา เพชรมีศรี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_boonyawan_046",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Chunya",
    "last_name": "Boonyawan",
    "full_name": "Chunya Boonyawan",
    "full_name_th": "อ. ชัญญา บุญญวรรณ",
    "role": "อาจารย์ประจำ",
    "email": "chunya.b@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_piyarattanayoth_047",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Puttipong",
    "last_name": "Piyarattanayothin",
    "full_name": "Puttipong Piyarattanayothin",
    "full_name_th": "อ. พุฒิพงศ์ ปิยะรัตนโยธิน",
    "role": "อาจารย์ประจำ",
    "email": "puttipong@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_termoriyabut_048",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Warinthorn",
    "last_name": "Termoriyabut",
    "full_name": "Warinthorn Termoriyabut",
    "full_name_th": "อ. วรินทร เติมอริยบุตร",
    "role": "อาจารย์ประจำ",
    "email": "warinthorn.t@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_siriwanporn_049",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Harit",
    "last_name": "Siriwanporn",
    "full_name": "Harit Siriwanporn",
    "full_name_th": "อ. หฤษฎ ศิริวรรณพร",
    "role": "อาจารย์ประจำ",
    "email": "harit@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_pimngam_050",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Sarun",
    "last_name": "Pimngam",
    "full_name": "Sarun Pimngam",
    "full_name_th": "อ. ศรัณย์ พิมพ์งาม",
    "role": "อาจารย์ประจำ",
    "email": "sarun.pi@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_sirichumsang_051",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Siratach",
    "last_name": "Sirichumsang",
    "full_name": "Siratach Sirichumsang",
    "full_name_th": "อ. ศิรธัช ศิริชุมแสง",
    "role": "อาจารย์ประจำ",
    "email": "siratach@law.chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_rodcharoen_052",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Natthaporn",
    "last_name": "Rodcharoen",
    "full_name": "Natthaporn Rodcharoen",
    "full_name_th": "อ. ณัฏฐพร รอดเจริญ",
    "role": "อาจารย์ประจำ",
    "email": "natthaporn.rodcharoen@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofl_sirirallop_053",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Intach",
    "last_name": "Sirirallop",
    "full_name": "Intach Sirirallop",
    "full_name_th": "อ. อินทัช ศิริวัลลภ",
    "role": "อาจารย์ประจำ",
    "email": "intouch.s@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
