# Chulalongkorn University 100% Full Completion Dataset
# Covers Dentistry, Allied Health, Nursing, Veterinary, Fine Arts, Education, Arts, Agricultural Resources & Interdisciplinary

CHULA_COMPLETION_COURSES = [
    # =========================================================================
    # 1. คณะทันตแพทยศาสตร์ (Faculty of Dentistry - Chulalongkorn University)
    # =========================================================================
    {
        "id": "cu_dent_dds",
        "title_th": "หลักสูตรทันตแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Dental Surgery Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ท.บ. (ทันตแพทยศาสตรบัณฑิต)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Dentistry",
        "department_th": "สาขาวิชาทันตแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "238 หน่วยกิต",
        "tuition_per_semester": "34,000 บาท",
        "tuition_total": "408,000 บาท",
        "description": "คณะทันตแพทยศาสตร์แห่งแรกของประเทศไทย อันดับ 1 ด้านทันตกรรม ผลิตทันตแพทย์ผู้เชี่ยวชาญการดูแลสุขภาพช่องปาก เทคโนโลยี Digital Dentistry และหัตถการคลินิกระดับมาตรฐานโลก",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิกในโรงพยาบาลทันตกรรม คณะทันตแพทยศาสตร์ จุฬาฯ", "ศูนย์ความเป็นเลิศด้านทันตกรรมดิจิทัล CAD/CAM และ 3D Bioprinting", "การวิจัยด้านเซลล์ต้นกำเนิดและวิศวกรรมเนื้อเยื่อในช่องปาก (Stem Cell & Tissue Engineering)"],
        "career_paths": ["ทันตแพทย์ในโรงพยาบาลชั้นนำของรัฐและเอกชน", "ทันตแพทย์เฉพาะทางทุกสาขา", "อาจารย์ทันตแพทย์และนักวิจัยระดับนานาชาติ", "เจ้าของคลินิกทันตกรรม"],
        "tags": ["Dentistry", "Dental", "Doctor of Dental Surgery", "Digital Dentistry", "Chula Dentistry"],
        "website_url": "https://dent.chula.ac.th"
    },
    {
        "id": "cu_dent_msc_orthodontics",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาทันตกรรมจัดฟัน (หลักสูตรนานาชาติ)",
        "title_en": "Master of Science Program in Orthodontics (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (ทันตกรรมจัดฟัน)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Orthodontics",
        "department_th": "ภาควิชาทันตกรรมจัดฟัน",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "3 ปี",
        "total_credits": "52 หน่วยกิต",
        "tuition_per_semester": "120,000 บาท",
        "tuition_total": "720,000 บาท",
        "description": "หลักสูตรทันตกรรมจัดฟันระดับปริญญาโทชั้นนำของเอเชีย เน้นการวินิจฉัยและวางแผนการรักษาการสบฟันผิดปกติขั้นซับซ้อน การจัดฟันร่วมกับการผ่าตัดขากรรไกร และ Clear Aligner Technology",
        "curriculum_highlights": ["การดูแลรักษาผู้ป่วยจัดฟันที่มีความซับซ้อนสูงและผู้ป่วยปากแหว่งเพดานโหว่", "เทคโนโลยีการจัดฟันแบบดิจิทัล 3 มิติ และแบบจำลองเสมือนจริง", "การตีพิมพ์ผลงานวิจัยในวารสารทันตกรรมจัดฟันระดับโลก (AJODO, Angle Orthodontist)"],
        "career_paths": ["ทันตแพทย์เฉพาะทางสาขาทันตกรรมจัดฟัน (Orthodontist)", "อาจารย์ประจำคณะทันตแพทยศาสตร์", "นักวิจัยทันตกรรมจัดฟันระดับสากล"],
        "tags": ["Orthodontics", "Dentistry", "Digital Orthodontics", "Master of Science", "Chula"],
        "website_url": "https://ortho.dent.chula.ac.th"
    },
    {
        "id": "cu_dent_msc_periodontics",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาปริทันตวิทยา",
        "title_en": "Master of Science Program in Periodontics",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (ปริทันตวิทยา)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Periodontology",
        "department_th": "ภาควิชาปริทันตวิทยา",
        "program_type": "ภาคปกติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "65,000 บาท",
        "tuition_total": "260,000 บาท",
        "description": "เน้นการรักษาโรคเหงือกและเนื้อเยื่อรอบฟันขั้นสูง การผ่าตัดปริทันต์ การปลูกกระดูกและรากฟันเทียม (Dental Implants) และการฟื้นฟูเนื้อเยื่อปริทันต์",
        "curriculum_highlights": ["การผ่าตัดฝังรากฟันเทียมขั้นสูง (Advanced Dental Implantology)", "การใช้เลเซอร์ทางทันตกรรมและชีววัสดุปลูกกระดูก", "การฝึกปฏิบัติการคลินิกเฉพาะทางภายใต้คณาจารย์ผู้ทรงคุณวุฒิระดับประเทศ"],
        "career_paths": ["ทันตแพทย์เฉพาะทางปริทันตวิทยาและรากเทียม", "อาจารย์ทันตแพทย์", "นักวิจัยชีววัสดุทางทันตกรรม"],
        "tags": ["Periodontics", "Dental Implants", "Dentistry", "Master", "Chula"],
        "website_url": "https://perio.dent.chula.ac.th"
    },

    # =========================================================================
    # 2. คณะสหเวชศาสตร์ (Faculty of Allied Health Sciences - Chulalongkorn)
    # =========================================================================
    {
        "id": "cu_ah_bsc_med_tech",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคนิคการแพทย์",
        "title_en": "Bachelor of Science Program in Medical Technology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคนิคการแพทย์)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Allied Health Sciences",
        "faculty_th": "คณะสหเวชศาสตร์",
        "department": "Department of Medical Technology",
        "department_th": "ภาควิชาเทคนิคการแพทย์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "21,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "ผลิตนักเทคนิคการแพทย์ชั้นนำ เชี่ยวชาญการตรวจวิเคราะห์สิ่งส่งตรวจทางห้องปฏิบัติการ โลหิตวิทยา เคมีคลินิก อณูชีววิทยาทางการแพทย์ และการตรวจคัดกรองพันธุกรรม",
        "curriculum_highlights": ["การฝึกปฏิบัติงานในห้องปฏิบัติการโรงพยาบาลจุฬาลงกรณ์ สภากาชาดไทย", "การตรวจวินิจฉัยระดับโมเลกุล (Next-Generation Sequencing & PCR)", "การควบคุมคุณภาพห้องปฏิบัติการมาตรฐานสากล ISO 15189"],
        "career_paths": ["นักเทคนิคการแพทย์ประจำโรงพยาบาลรัฐและเอกชนชั้นนำ", "นักวิทยาศาสตร์การแพทย์และนักวิจัยทางการแพทย์", "ผู้เชี่ยวชาญเครื่องมือตรวจวินิจฉัยทางการแพทย์"],
        "tags": ["Medical Technology", "Allied Health", "Clinical Chemistry", "Molecular Diagnostics", "Chula"],
        "website_url": "https://ahsc.chula.ac.th"
    },
    {
        "id": "cu_ah_bsc_physical_therapy",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชากายภาพบำบัด",
        "title_en": "Bachelor of Science Program in Physical Therapy",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (กายภาพบำบัด)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Allied Health Sciences",
        "faculty_th": "คณะสหเวชศาสตร์",
        "department": "Department of Physical Therapy",
        "department_th": "ภาควิชากายภาพบำบัด",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "140 หน่วยกิต",
        "tuition_per_semester": "21,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "มุ่งเน้นการตรวจประเมิน รักษา และฟื้นฟูสมรรถภาพทางกายในผู้ป่วยระบบกระดูก กล้ามเนื้อ ระบบประสาท ระบบหัวใจหลอดเลือด และกายภาพบำบัดทางการกีฬา",
        "curriculum_highlights": ["คลินิกกายภาพบำบัด คณะสหเวชศาสตร์ จุฬาฯ และโรงพยาบาลจุฬาลงกรณ์", "กายภาพบำบัดทางการกีฬาและการฟื้นฟูนักกีฬาทีมชาติ", "การใช้นวัตกรรมหุ่นยนต์ช่วยฝึกเดิน (Robotic Gait Trainer) และเครื่องมือกายภาพสมัยใหม่"],
        "career_paths": ["นักกายภาพบำบัดประจำโรงพยาบาลชั้นนำ", "นักกายภาพบำบัดประจำสโมสรกีฬาและทีมนักกีฬา", "เจ้าของคลินิกกายภาพบำบัด"],
        "tags": ["Physical Therapy", "Rehabilitation", "Sports Medicine", "Physiotherapy", "Chula"],
        "website_url": "https://ahsc.chula.ac.th"
    },
    {
        "id": "cu_ah_bsc_radiological_tech",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชารังสีเทคนิค",
        "title_en": "Bachelor of Science Program in Radiological Technology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (รังสีเทคนิค)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Allied Health Sciences",
        "faculty_th": "คณะสหเวชศาสตร์",
        "department": "Department of Radiological Technology",
        "department_th": "ภาควิชารังสีเทคนิค",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "21,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "เชี่ยวชาญการใช้รังสีและคลื่นสะท้อนในสนามแม่เหล็กเพื่อการตรวจวินิจฉัยและรักษาโรค (X-ray, CT Scan, MRI, เวชศาสตร์นิวเคลียร์ และรังสีรักษา)",
        "curriculum_highlights": ["การฝึกปฏิบัติการกับเครื่องมือรังสีวินิจฉัยขั้นสูง (MRI 3.0T, Dual-Source CT, PET-CT) ณ รพ.จุฬาลงกรณ์", "การวางแผนรังสีรักษาโรคมะเร็งและเวชศาสตร์นิวเคลียร์", "ความปลอดภัยทางรังสีและการประกันคุณภาพภาพถ่ายทางการแพทย์"],
        "career_paths": ["นักรังสีการแพทย์ (Radiological Technologist)", "ผู้เชี่ยวชาญรังสีรักษาและเวชศาสตร์นิวเคลียร์", "ผู้เชี่ยวชาญเครื่องมือแพทย์ด้านรังสีวินิจฉัย (MRI / CT Specialist)"],
        "tags": ["Radiological Technology", "MRI", "CT Scan", "Medical Imaging", "Nuclear Medicine", "Chula"],
        "website_url": "https://ahsc.chula.ac.th"
    },
    {
        "id": "cu_ah_bsc_nutrition_dietetics",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาโภชนาการและการกำหนดอาหาร",
        "title_en": "Bachelor of Science Program in Nutrition and Dietetics",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (โภชนาการและการกำหนดอาหาร)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Allied Health Sciences",
        "faculty_th": "คณะสหเวชศาสตร์",
        "department": "Department of Nutrition and Dietetics",
        "department_th": "ภาควิชาโภชนาการและการกำหนดอาหาร",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "21,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "ผลิตนักกำหนดอาหารวิชาชีพ (Dietitian) ผู้เชี่ยวชาญการวางแผนโภชนบำบัดรักษาโรค (เบาหวาน, ไต, มะเร็ง) โภชนาการทางการกีฬา และการส่งเสริมสุขภาพเชิงรุก",
        "curriculum_highlights": ["การฝึกปฏิบัติงานโภชนบำบัดทางคลินิก ณ โรงพยาบาลจุฬาลงกรณ์ สภากาชาดไทย", "การออกแบบอาหารเฉพาะโรคและการบริหารจัดการบริการอาหารโรงพยาบาล", "โภชนพันธุศาสตร์และการกำหนดอาหารเฉพาะบุคคล (Personalized Nutrition)"],
        "career_paths": ["นักกำหนดอาหารวิชาชีพ (Certified Dietitian / Nutritionist)", "นักโภชนาการคลินิกประจำโรงพยาบาล", "ผู้เชี่ยวชาญโภชนาการทางการกีฬาและผลิตภัณฑ์อาหารสุขภาพ"],
        "tags": ["Nutrition", "Dietetics", "Clinical Nutrition", "Dietitian", "Health Science", "Chula"],
        "website_url": "https://ahsc.chula.ac.th"
    },

    # =========================================================================
    # 3. คณะพยาบาลศาสตร์ (Faculty of Nursing - Chulalongkorn University)
    # =========================================================================
    {
        "id": "cu_nurs_bns",
        "title_th": "หลักสูตรพยาบาลศาสตรบัณฑิต",
        "title_en": "Bachelor of Nursing Science Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พย.บ. (พยาบาลศาสตรบัณฑิต)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Nursing",
        "faculty_th": "คณะพยาบาลศาสตร์",
        "department": "Department of Nursing",
        "department_th": "สาขาวิชาพยาบาลศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "21,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "สถาบันการพยาบาลชั้นนำของประเทศ มุ่งเน้นการผลิตพยาบาลวิชาชีพที่มีภาวะผู้นำ ความเชี่ยวชาญการดูแลผู้ป่วยวิกฤต และการวิจัยนวัตกรรมทางการพยาบาล",
        "curriculum_highlights": ["การฝึกปฏิบัติการพยาบาล ณ โรงพยาบาลจุฬาลงกรณ์ สภากาชาดไทย", "ศูนย์จำลองสถานการณ์เพื่อการเรียนรู้ทางการพยาบาล (Nursing Simulation Center)", "การแลกเปลี่ยนทางวิชาการและการฝึกงานกับสถาบันพยาบาลชั้นนำระดับโลก"],
        "career_paths": ["พยาบาลวิชาชีพในโรงพยาบาลชั้นนำของรัฐและเอกชน", "พยาบาลเฉพาะทาง (ผู้ป่วยวิกฤต, หัวใจ, เด็ก, ผู้สูงอายุ)", "อาจารย์และนักวิจัยพยาบาลศาสตร์"],
        "tags": ["Nursing", "Nurse", "Healthcare", "Patient Care", "Chula Nursing"],
        "website_url": "https://nurse.chula.ac.th"
    },
    {
        "id": "cu_nurs_mns_adult_gero",
        "title_th": "หลักสูตรพยาบาลศาสตรมหาบัณฑิต สาขาวิชาการพยาบาลผู้ใหญ่และผู้สูงอายุ",
        "title_en": "Master of Nursing Science Program in Adult and Gerontological Nursing",
        "degree_level": "ปริญญาโท",
        "degree_name": "พย.ม. (การพยาบาลผู้ใหญ่และผู้สูงอายุ)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Nursing",
        "faculty_th": "คณะพยาบาลศาสตร์",
        "department": "Department of Adult and Gerontological Nursing",
        "department_th": "สาขาวิชาการพยาบาลผู้ใหญ่และผู้สูงอายุ",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "38,000 บาท",
        "tuition_total": "152,000 บาท",
        "description": "พัฒนาพยาบาลผู้ปฏิบัติการพยาบาลขั้นสูง (Advanced Practice Nurse) ในการดูแลผู้ป่วยผู้ใหญ่และผู้สูงอายุที่มีภาวะโรคซับซ้อนและการสร้างงานวิจัยคลินิก",
        "curriculum_highlights": ["การบริหารจัดการการดูแลผู้ป่วยวิกฤตและโรคเรื้อรังซับซ้อน", "การพัฒนานวัตกรรมและแนวปฏิบัติทางการพยาบาลตามหลักฐานเชิงประจักษ์ (EBP)", "การประยุกต์ใช้เทคโนโลยีสุขภาพเพื่อการดูแลผู้สูงอายุระยะยาว"],
        "career_paths": ["พยาบาลผู้ปฏิบัติการขั้นสูง (APN)", "ผู้บริหารและหัวหน้าฝ่ายการพยาบาล", "อาจารย์และนักวิจัยพยาบาลศาสตร์"],
        "tags": ["Nursing", "Advanced Practice Nursing", "Gerontology", "Master of Nursing", "Chula"],
        "website_url": "https://nurse.chula.ac.th"
    },

    # =========================================================================
    # 4. คณะสัตวแพทยศาสตร์ (Faculty of Veterinary Science - Chulalongkorn)
    # =========================================================================
    {
        "id": "cu_vet_dvm",
        "title_th": "หลักสูตรสัตวแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Veterinary Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "สพ.บ. (สัตวแพทยศาสตรบัณฑิต)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Veterinary Science",
        "faculty_th": "คณะสัตวแพทยศาสตร์",
        "department": "Department of Veterinary Medicine",
        "department_th": "สาขาวิชาสัตวแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "242 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "คณะสัตวแพทยศาสตร์แห่งแรกของไทย ผลิตสัตวแพทย์ผู้เชี่ยวชาญการดูแลรักษาสัตว์เลี้ยง สัตว์เศรษฐกิจ สัตว์ป่า สัตว์น้ำ และการควบคุมโรคติดต่อระหว่างสัตว์และคน (One Health)",
        "curriculum_highlights": ["โรงพยาบาลสัตว์เล็ก จุฬาฯ และโรงพยาบาลปศุสัตว์นครปฐม ขนาดใหญ่และทันสมัย", "ศูนย์วิจัยโรคสัตว์น้ำและสัตว์ป่าระดับสากล", "การวิจัยด้านสุขภาพหนึ่งเดียว (One Health) และความปลอดภัยทางอาหารระดับโลก"],
        "career_paths": ["สัตวแพทย์คลินิกสัตว์เลี้ยงและสัตว์ป่า", "สัตวแพทย์ควบคุมฟาร์มปศุสัตว์และสัตว์น้ำ", "นักวิจัยชีววิทยาการแพทย์และวัคซีนสัตว์", "นายสัตวแพทย์ประจำกรมปศุสัตว์"],
        "tags": ["Veterinary Medicine", "DVM", "Animal Health", "One Health", "Chula Vet"],
        "website_url": "https://vet.chula.ac.th"
    },

    # =========================================================================
    # 5. คณะศิลปกรรมศาสตร์ (Faculty of Fine and Applied Arts - Chulalongkorn)
    # =========================================================================
    {
        "id": "cu_faa_bfa_creative_arts",
        "title_th": "หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชานฤมิตศิลป์ (Creative Arts)",
        "title_en": "Bachelor of Fine and Applied Arts Program in Creative Arts",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศล.บ. (นฤมิตศิลป์)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Fine and Applied Arts",
        "faculty_th": "คณะศิลปกรรมศาสตร์",
        "department": "Department of Creative Arts",
        "department_th": "ภาควิชานฤมิตศิลป์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "21,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "ครอบคลุมการออกแบบกราฟิก (Graphic Design), การออกแบบแฟชั่นและสิ่งทอ (Fashion), การออกแบบเซรามิกส์ (Ceramics) และการออกแบบนิทรรศการ (Exhibition Design)",
        "curriculum_highlights": ["สตูดิโอการออกแบบสร้างสรรค์และเวิร์กช็อปแฟชั่นมาตรฐานสากล", "การนำผลงานเข้าร่วมแสดงในงานสัปดาห์การออกแบบ (Bangkok Design Week)", "ศิษย์เก่าดำรงตำแหน่งดีไซเนอร์และผู้ก่อตั้งแบรนด์แฟชั่นระดับแนวหน้า"],
        "career_paths": ["Fashion Designer / Creative Director", "Graphic & Brand Identity Designer", "Exhibition & Event Designer", "Ceramic & Product Designer"],
        "tags": ["Creative Arts", "Fashion Design", "Graphic Design", "Fine Arts", "Chula"],
        "website_url": "https://faa.chula.ac.th"
    },
    {
        "id": "cu_faa_bfa_music",
        "title_th": "หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชาดุริยางคศิลป์",
        "title_en": "Bachelor of Fine and Applied Arts Program in Music",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศล.บ. (ดุริยางคศิลป์)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Fine and Applied Arts",
        "faculty_th": "คณะศิลปกรรมศาสตร์",
        "department": "Department of Music",
        "department_th": "ภาควิชาดุริยางคศิลป์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "23,000 บาท",
        "tuition_total": "184,000 บาท",
        "description": "เน้นความเป็นเลิศด้านการปฏิบัติการดนตรีไทยและดนตรีสากล การประพันธ์เพลง การอำนวยเพลง (Conducting) และดุริยางควิทยา",
        "curriculum_highlights": ["CU Symphony Orchestra วงดุริยางค์ซิมโฟนีชั้นนำของมหาวิทยาลัย", "การแสดงเดี่ยว (Solo Recital) และการแสดงร่วมวงออร์เคสตราทุกภาคการศึกษา", "คณาจารย์และศิลปินดนตรีระดับปรมาจารย์ของประเทศ"],
        "career_paths": ["นักดนตรีอาชีพและสมาชิกวงออร์เคสตรา", "นักประพันธ์เพลงและผู้เรียบเรียงเสียงประสาน (Composer / Arranger)", "ครูสอนดนตรีและนักวิชาการดนตรี"],
        "tags": ["Music", "Symphony Orchestra", "Music Performance", "Composition", "Chula"],
        "website_url": "https://faa.chula.ac.th"
    },

    # =========================================================================
    # 6. คณะครุศาสตร์ (Faculty of Education - Chulalongkorn University)
    # =========================================================================
    {
        "id": "cu_edu_bed_secondary",
        "title_th": "หลักสูตรครุศาสตรบัณฑิต สาขาวิชามัธยมศึกษา",
        "title_en": "Bachelor of Education Program in Secondary Education",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ค.บ. (มัธยมศึกษา)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "Department of Curriculum and Instruction",
        "department_th": "ภาควิชาหลักสูตรและการสอน",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "ผลิตครูมัธยมศึกษาชั้นนำในวิชาเอกวิทยาศาสตร์ คณิตศาสตร์ ภาษาอังกฤษ ภาษาไทย และสังคมศึกษา ที่มีสมรรถนะการสอนสมัยใหม่และการใช้ EdTech AI",
        "curriculum_highlights": ["การฝึกปฏิบัติการสอนในโรงเรียนสาธิตจุฬาลงกรณ์มหาวิทยาลัย (ฝ่ายมัธยม)", "การออกแบบการจัดการเรียนรู้แบบ Active Learning และ STEM Education", "การประยุกต์ใช้นวัตกรรมดิจิทัลและ AI เพื่อการศึกษา"],
        "career_paths": ["ครูผู้สอนระดับมัธยมศึกษาในโรงเรียนรัฐและเอกชนชั้นนำ", "นักวิชาการศึกษาและนักพัฒนาหลักสูตร", "ผู้เชี่ยวชาญด้านสื่อนวัตกรรมการศึกษา"],
        "tags": ["Education", "Teacher", "Secondary Education", "Curriculum", "Chula Education"],
        "website_url": "https://edu.chula.ac.th"
    },
    {
        "id": "cu_edu_bed_early_childhood",
        "title_th": "หลักสูตรครุศาสตรบัณฑิต สาขาวิชาการศึกษาปฐมวัย",
        "title_en": "Bachelor of Education Program in Early Childhood Education",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ค.บ. (การศึกษาปฐมวัย)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "Department of Curriculum and Instruction",
        "department_th": "ภาควิชาหลักสูตรและการสอน",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "เน้นการพัฒนาเด็กปฐมวัยแบบองค์รวม พัฒนาการทางสมอง (Executive Functions - EF) จิตวิทยาเด็ก และการออกแบบสภาพแวดล้อมการเรียนรู้เชิงสร้างสรรค์",
        "curriculum_highlights": ["การฝึกปฏิบัติการสอนในโรงเรียนสาธิตจุฬาลงกรณ์มหาวิทยาลัย (ฝ่ายประถม/ปฐมวัย)", "การบูรณาการแนวคิดมอนเตสซอรี (Montessori) และเรจจิโอ เอมิเลีย (Reggio Emilia)", "การส่งเสริมพัฒนาการทางสมองและการเรียนรู้ผ่านการเล่น (Play-Based Learning)"],
        "career_paths": ["ครูปฐมวัยในโรงเรียนอนุบาลชั้นนำและโรงเรียนนานาชาติ", "ผู้เชี่ยวชาญด้านการพัฒนาเด็กปฐมวัย", "ผู้บริหารสถานรับเลี้ยงเด็กและโรงเรียนอนุบาล"],
        "tags": ["Early Childhood Education", "Teacher", "Child Development", "Chula"],
        "website_url": "https://edu.chula.ac.th"
    },

    # =========================================================================
    # 7. คณะอักษรศาสตร์ (Faculty of Arts - Chulalongkorn University)
    # =========================================================================
    {
        "id": "cu_arts_ba_balac",
        "title_th": "หลักสูตรอักษรศาสตรบัณฑิต สาขาวิชาภาษาและวัฒนธรรม (หลักสูตรนานาชาติ - BALAC)",
        "title_en": "Bachelor of Arts in Language and Culture (International Program - BALAC)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "อ.บ. (ภาษาและวัฒนธรรม)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Arts",
        "faculty_th": "คณะอักษรศาสตร์",
        "department": "BALAC Program",
        "department_th": "สาขาวิชาภาษาและวัฒนธรรมนานาชาติ",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "128 หน่วยกิต",
        "tuition_per_semester": "92,000 บาท",
        "tuition_total": "736,000 บาท",
        "description": "หลักสูตรนานาชาติชั้นนำของคณะอักษรศาสตร์ จุฬาฯ ศึกษาลึกซึ้งด้านวรรณกรรม วัฒนธรรมโลก สื่อศึกษา ปรัชญา และภาษาต่างประเทศที่สาม",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษ 100% กับคณาจารย์ระดับสากล", "โอกาสแลกเปลี่ยนกับมหาวิทยาลัยชั้นนำในยุโรป สหรัฐอเมริกา และญี่ปุ่น", "การคิดเชิงวิพากษ์ (Critical Thinking) และการวิเคราะห์วัฒนธรรมร่วมสมัย"],
        "career_paths": ["นักการทูตและเจ้าหน้าที่องค์การระหว่างประเทศ (UN, UNESCO)", "บรรณาธิการและนักเขียนระดับสากล", "ผู้เชี่ยวชาญด้านสื่อข้ามวัฒนธรรมและการประชาสัมพันธ์"],
        "tags": ["BALAC", "Arts", "Language and Culture", "International Program", "Chula Arts"],
        "website_url": "https://balac.arts.chula.ac.th"
    },
    {
        "id": "cu_arts_ba_thai_major",
        "title_th": "หลักสูตรอักษรศาสตรบัณฑิต สาขาวิชาภาษาและวรรณคดีไทย",
        "title_en": "Bachelor of Arts Program in Thai Language and Literature",
        "degree_level": "ปริญญาตรี",
        "degree_name": "อ.บ. (ภาษาและวรรณคดีไทย)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Arts",
        "faculty_th": "คณะอักษรศาสตร์",
        "department": "Department of Thai",
        "department_th": "ภาควิชาภาษาไทย",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "ศูนย์กลางการศึกษาภาษาไทย วรรณคดีไทย ภาษาศาสตร์ และการใช้ภาษาไทยระดับสูงระดับประเทศ",
        "curriculum_highlights": ["การวิเคราะห์วรรณคดีคลาสสิกและวรรณกรรมร่วมสมัย", "ภาษาศาสตร์ภาษาไทยและการประมวลผลภาษาธรรมชาติภาษาไทย (Thai NLP)", "การเขียนเชิงสร้างสรรค์และการสื่อสารมวลชนระดับมืออาชีพ"],
        "career_paths": ["นักเขียน บรรณาธิการ และนักวิจารณ์วรรณกรรม", "นักภาษาศาสตร์และนักภาษาศาสตร์คอมพิวเตอร์ (AI Linguist)", "อาจารย์และนักวิชาการภาษาไทย"],
        "tags": ["Thai Language", "Literature", "Linguistics", "Chula Arts", "Writing"],
        "website_url": "https://thai.arts.chula.ac.th"
    },
    {
        "id": "cu_arts_ba_eastern_languages",
        "title_th": "หลักสูตรอักษรศาสตรบัณฑิต สาขาวิชาภาษาตะวันออก (ภาษาจีน, ภาษาญี่ปุ่น, ภาษาเกาหลี)",
        "title_en": "Bachelor of Arts Program in Eastern Languages (Chinese, Japanese, Korean)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "อ.บ. (ภาษาตะวันออก)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Arts",
        "faculty_th": "คณะอักษรศาสตร์",
        "department": "Department of Eastern Languages",
        "department_th": "ภาควิชาภาษาตะวันออก",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "ความเชี่ยวชาญระดับสูงด้านภาษา วรรณกรรม ประวัติศาสตร์ และวัฒนธรรมเอเชียตะวันออก (จีน, ญี่ปุ่น, เกาหลี) สำหรับการทูตและธุรกิจสากล",
        "curriculum_highlights": ["การเรียนภาษาระดับสูงกับเจ้าของภาษาและการฝึกแปล/ล่ามขั้นสูง", "ทุนการศึกษาและการแลกเปลี่ยนกับมหาวิทยาลัยชั้นนำในจีน ญี่ปุ่น และเกาหลี (Peking, Tokyo, Seoul National)", "การศึกษาวัฒนธรรมและเศรษฐกิจการเมืองเอเชียร่วมสมัย"],
        "career_paths": ["นักแปลและล่ามระดับสูง", "เจ้าหน้าที่การทูตและองค์กรระหว่างประเทศ", "ผู้บริหารในบรรษัทข้ามชาติเอเชีย (ญี่ปุ่น, จีน, เกาหลี)"],
        "tags": ["Chinese", "Japanese", "Korean", "Eastern Languages", "Chula Arts"],
        "website_url": "https://eastern.arts.chula.ac.th"
    },

    # =========================================================================
    # 8. สำนักวิชาทรัพยากรการเกษตร (School of Agricultural Resources - SAR Chula)
    # =========================================================================
    {
        "id": "cu_sar_ba_agri_resources",
        "title_th": "หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาการบริหารจัดการทรัพยากรการเกษตร",
        "title_en": "Bachelor of Arts Program in Agricultural Resources Management",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ. (การบริหารจัดการทรัพยากรการเกษตร)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "School of Agricultural Resources (SAR Chula)",
        "faculty_th": "สำนักวิชาทรัพยากรการเกษตร",
        "department": "Department of Agricultural Resources Management",
        "department_th": "สาขาวิชาการบริหารจัดการทรัพยากรการเกษตร",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "บูรณาการศาสตร์เกษตร เทคโนโลยีชีวภาพ การจัดการธุรกิจเกษตร และการพัฒนาความยั่งยืน ณ ศูนย์การเรียนรู้จุฬาฯ สระบุรีและน่าน",
        "curriculum_highlights": ["การเรียนรู้เชิงปฏิบัติการ ณ ศูนย์เครือข่ายการเรียนรู้เพื่อภูมิภาค จุฬาฯ จ.สระบุรี และ จ.น่าน", "การจัดการห่วงโซ่คุณค่าเกษตรปลอดภัยและเกษตรอินทรีย์", "การพัฒนาผลิตภัณฑ์เกษตรนวัตกรรมและการสร้างผู้ประกอบการเกษตรรุ่นใหม่"],
        "career_paths": ["ผู้จัดการธุรกิจเกษตรและอาหารแปรรูป", "นักวิชาการพัฒนาการเกษตรและสิ่งแวดล้อม", "ผู้ประกอบการฟาร์มเกษตรอัจฉริยะ"],
        "tags": ["Agricultural Resources", "Agribusiness", "Sustainability", "Smart Farming", "SAR Chula"],
        "website_url": "https://sar.chula.ac.th"
    },

    # =========================================================================
    # 9. บัณฑิตวิทยาลัย สหสาขาวิชา (Chulalongkorn Interdisciplinary Graduate Programs)
    # =========================================================================
    {
        "id": "cu_grad_msc_nano",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชานาโนวิทยาและเทคโนโลยี (หลักสูตรนานาชาติ)",
        "title_en": "Master of Science Program in Nanoscience and Technology (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (นาโนวิทยาและเทคโนโลยี)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Graduate School (Interdisciplinary)",
        "faculty_th": "บัณฑิตวิทยาลัย (สหสาขาวิชา)",
        "department": "Program in Nanoscience and Technology",
        "department_th": "สหสาขาวิชานาโนวิทยาและเทคโนโลยี",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "50,000 บาท",
        "tuition_total": "200,000 บาท",
        "description": "การวิจัยขั้นสูงด้านวัสดุระดับนาโน นาโนอิเล็กทรอนิกส์ นาโนการแพทย์ และระบบนำส่งยาระดับนาโน ร่วมกับศูนย์นาโนเทคโนโลยีแห่งชาติ (NANOTEC)",
        "curriculum_highlights": ["การใช้ห้องคลีนรูมและกล้องจุลทรรศน์อิเล็กตรอนขั้นสูง (TEM / SEM / AFM)", "การวิจัยวัสดุนาโนสำหรับกักเก็บพลังงานและเซนเซอร์ทางการแพทย์", "ทุนวิจัยและการตีพิมพ์ในวารสารระดับ Q1"],
        "career_paths": ["นักวิจัยนาโนเทคโนโลยีระดับแนวหน้า", "ผู้เชี่ยวชาญ R&D ในอุตสาหกรรมเซมิคอนดักเตอร์และยา", "อาจารย์มหาวิทยาลัย"],
        "tags": ["Nanoscience", "Nanotechnology", "Nanomedicine", "Interdisciplinary", "Chula"],
        "website_url": "https://grad.chula.ac.th"
    },
    {
        "id": "cu_grad_msc_env_management",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาการจัดการสิ่งแวดล้อม (หลักสูตรนานาชาติ)",
        "title_en": "Master of Science Program in Environmental Management (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (การจัดการสิ่งแวดล้อม)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Graduate School (Interdisciplinary)",
        "faculty_th": "บัณฑิตวิทยาลัย (สหสาขาวิชา)",
        "department": "Program in Environmental Management",
        "department_th": "สหสาขาวิชาการจัดการสิ่งแวดล้อม",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "55,000 บาท",
        "tuition_total": "220,000 บาท",
        "description": "สถาบันการจัดการสิ่งแวดล้อมชั้นนำ เน้นนโยบายการเปลี่ยนแปลงสภาพภูมิอากาศ การจัดการมลพิษ เศรษฐกิจหมุนเวียน (Circular Economy) และกลยุทธ์ ESG องค์กร",
        "curriculum_highlights": ["การประเมินคาร์บอนฟุตพริ้นท์และการวางแผนสู่ Net Zero", "การประเมินผลกระทบสิ่งแวดล้อมและสุขภาพ (EIA / EHIA)", "ความร่วมมือกับสถาบันสิ่งแวดล้อมระดับนานาชาติ"],
        "career_paths": ["ผู้เชี่ยวชาญด้าน ESG และ Net Zero ในองค์กรชั้นนำ", "ที่ปรึกษาด้านการจัดการสิ่งแวดล้อมและพลังงานสะอาด", "นักวิจัยนโยบายสิ่งแวดล้อมระดับสากล"],
        "tags": ["Environmental Management", "ESG", "Net Zero", "Circular Economy", "Chula"],
        "website_url": "https://grad.chula.ac.th"
    },
    {
        "id": "cu_grad_msc_logistics",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาการจัดการโลจิสติกส์และโซ่อุปทาน (หลักสูตรนานาชาติ)",
        "title_en": "Master of Science Program in Logistics and Supply Chain Management (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (การจัดการโลจิสติกส์และโซ่อุปทาน)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Graduate School (Interdisciplinary)",
        "faculty_th": "บัณฑิตวิทยาลัย (สหสาขาวิชา)",
        "department": "Program in Logistics and Supply Chain",
        "department_th": "สหสาขาวิชาการจัดการโลจิสติกส์และโซ่อุปทาน",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "55,000 บาท",
        "tuition_total": "220,000 บาท",
        "description": "บูรณาการศาสตร์วิศวกรรมศาสตร์และพาณิชยศาสตร์ เน้นการเพิ่มประสิทธิภาพโซ่อุปทานระดับโลก การจำลองคลังสินค้าดิจิทัล และการวิเคราะห์ข้อมูลโลจิสติกส์",
        "curriculum_highlights": ["การออกแบบและเพิ่มประสิทธิภาพเครือข่ายซัพพลายเชนระดับโลกด้วย Data Analytics", "การประยุกต์ใช้ AI และ Automation ในคลังสินค้าและการขนส่ง", "ความร่วมมือกับสมาคมไทยโลจิสติกส์และการผลิต (TLA) และบรรษัทข้ามชาติ"],
        "career_paths": ["Supply Chain & Logistics Director", "Global Procurement Specialist", "ที่ปรึกษาระบบโลจิสติกส์และซัพพลายเชน"],
        "tags": ["Logistics", "Supply Chain", "Data Analytics", "Interdisciplinary", "Chula"],
        "website_url": "https://grad.chula.ac.th"
    },

    # =========================================================================
    # 10. คณะเภสัชศาสตร์ (Faculty of Pharmaceutical Sciences - Chula)
    # =========================================================================
    {
        "id": "cu_pharm_bpharm_care",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาการบริบาลทางเภสัชกรรม",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Care",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (การบริบาลทางเภสัชกรรม)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmaceutical Sciences",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Clinical Pharmacy",
        "department_th": "ภาควิชาเภสัชกรรมคลินิก",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "228 หน่วยกิต",
        "tuition_per_semester": "24,000 บาท",
        "tuition_total": "288,000 บาท",
        "description": "คณะเภสัชศาสตร์แห่งแรกของไทย มุ่งเน้นการบริบาลทางเภสัชกรรมแก่ผู้ป่วยในโรงพยาบาลระดับตติยภูมิ เภสัชพันธุศาสตร์ และการส่งเสริมการใช้ยาอย่างปลอดภัย",
        "curriculum_highlights": ["การฝึกปฏิบัติงานบริบาลทางเภสัชกรรม ณ โรงพยาบาลจุฬาลงกรณ์ สภากาชาดไทย", "เภสัชพันธุศาสตร์เพื่อการรักษาแบบแม่นยำ (Precision Pharmacotherapy)", "ศูนย์ข้อมูลยาและพิษวิทยามาตรฐานสากล"],
        "career_paths": ["เภสัชกรคลินิกประจำโรงพยาบาลชั้นนำ", "เภสัชกรผู้เชี่ยวชาญด้านยาและสารพิษ", "เภสัชกรชุมชนและเจ้าของร้านยาคุณภาพ"],
        "tags": ["Pharmacy", "Pharmaceutical Care", "Clinical Pharmacy", "Chula Pharmacy"],
        "website_url": "https://pharm.chula.ac.th"
    },
    {
        "id": "cu_pharm_bpharm_sci",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์เภสัชกรรม",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Sciences",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (วิทยาศาสตร์เภสัชกรรม)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmaceutical Sciences",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Pharmaceutics and Industrial Pharmacy",
        "department_th": "ภาควิชาเภสัชกรรมอุตสาหการ",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "228 หน่วยกิต",
        "tuition_per_semester": "24,000 บาท",
        "tuition_total": "288,000 บาท",
        "description": "เน้นการวิจัยพัฒนาสูตรตำรับยา ยาชีววัตถุ เครื่องสำอาง และการควบคุมคุณภาพในอุตสาหกรรมยาตามมาตรฐานสากล PIC/S",
        "curriculum_highlights": ["ศูนย์วิจัยและพัฒนาผลิตภัณฑ์ยาและชีวเภสัชภัณฑ์ (Chula Drug R&D Center)", "การสังเคราะห์ตัวยาใหม่และการนำส่งยาระดับนาโน (Nanomedicine)", "การฝึกงานในโรงงานผลิตยาชั้นนำและสำนักงานคณะกรรมการอาหารและยา (อย.)"],
        "career_paths": ["เภสัชกรนักวิจัยและพัฒนาสูตรยา (Drug R&D)", "เภสัชกรฝ่ายผลิตและประกันคุณภาพโรงงานยา (QA/QC)", "เภสัชกรฝ่ายขึ้นทะเบียนยาและคุ้มครองผู้บริโภค"],
        "tags": ["Pharmaceutical Sciences", "Industrial Pharmacy", "Drug Formulation", "Chula Pharmacy"],
        "website_url": "https://pharm.chula.ac.th"
    },
]
