# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/chula_polsci_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "chulalongk_facultyofp_nogsuansawasdee_023",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Siripan",
    "last_name": "Nogsuan Sawasdee",
    "full_name": "Siripan Nogsuan Sawasdee",
    "full_name_th": "ศ.ดร. สิริพรรณ นกสวน สวัสดี",
    "role": "อาจารย์ประจำ",
    "email": "nogsuan@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_tangsathapornpa_024",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Ake",
    "last_name": "Tangsathapornpan",
    "full_name": "Ake Tangsathapornpan",
    "full_name_th": "ศ.ดร. เอก ตั้งทรัพย์วัฒนา",
    "role": "อาจารย์ประจำ",
    "email": "ake.t@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_sangiampongsa_025",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pisanu",
    "last_name": "Sangiampongsa",
    "full_name": "Pisanu Sangiampongsa",
    "full_name_th": "รศ.ดร. พิษณุ เสงี่ยมพงษ์",
    "role": "อาจารย์ประจำ",
    "email": "pisanu.sangiampongsa@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_kraisoraphong_026",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Keokam",
    "last_name": "Kraisoraphong",
    "full_name": "Keokam Kraisoraphong",
    "full_name_th": "รศ.ดร. แก้วคำ ไกรสรพงษ์",
    "role": "อาจารย์ประจำ",
    "email": "keokamk@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_netipoh_028",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Viengrat",
    "last_name": "Netipoh",
    "full_name": "Viengrat Netipoh",
    "full_name_th": "รศ.ดร. เวียงรัฐ เนติโพธิ์",
    "role": "อาจารย์ประจำ",
    "email": "viengrat@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_pongsawat_029",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pitch",
    "last_name": "Pongsawat",
    "full_name": "Pitch Pongsawat",
    "full_name_th": "รศ.ดร. พิชญ์ พงษ์สวัสดิ์",
    "role": "อาจารย์ประจำ",
    "email": "madpitch@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_chanrojkit_030",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Bandit",
    "last_name": "Chanrojkit",
    "full_name": "Bandit Chanrojkit",
    "full_name_th": "รศ.ดร. บัณฑิต จันทร์โรจนกิจ",
    "role": "อาจารย์ประจำ",
    "email": "panditc@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_lertchoosakul_031",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Kanokrat",
    "last_name": "Lertchoosakul",
    "full_name": "Kanokrat Lertchoosakul",
    "full_name_th": "รศ.ดร. กนกรัตน์ เลิศชูสกุล",
    "role": "อาจารย์ประจำ",
    "email": "kanokrat.l@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_laiprakobsup_032",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Thanapan",
    "last_name": "Laiprakobsup",
    "full_name": "Thanapan Laiprakobsup",
    "full_name_th": "รศ.ดร. ธนพันธ์ ไล่ประกอบทรัพย์",
    "role": "อาจารย์ประจำ",
    "email": "thanapon.l@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_tonsakulrungrua_033",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Khemthong",
    "last_name": "Tonsakulrungruang",
    "full_name": "Khemthong Tonsakulrungruang",
    "full_name_th": "ผศ.ดร. เข็มทอง ต้นสกุลรุ่งเรือง",
    "role": "อาจารย์ประจำ",
    "email": "khemthong.t@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_thananithichot_034",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Stithorn",
    "last_name": "Thananithichot",
    "full_name": "Stithorn Thananithichot",
    "full_name_th": "อ.ดร. สติธร ธนานิธิโชติ",
    "role": "อาจารย์ประจำ",
    "email": "stithorn.t@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_manakul_035",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาการปกครอง",
    "department_th": "ภาควิชาการปกครอง",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Tawan",
    "last_name": "Manakul",
    "full_name": "Tawan Manakul",
    "full_name_th": "อ.ดร. ตะวัน มานะกุล",
    "role": "อาจารย์ประจำ",
    "email": "tawan.m@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_pawakapan_036",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Puangthong",
    "last_name": "Pawakapan",
    "full_name": "Puangthong Pawakapan",
    "full_name_th": "ศ.ดร. พวงทอง ภวัครพันธุ์",
    "role": "อาจารย์ประจำ",
    "email": "p.pawakapan@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_chainam_038",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Soravis",
    "last_name": "Chainam",
    "full_name": "Soravis Chainam",
    "full_name_th": "ศ. สรวิศ ชัยนาม",
    "role": "อาจารย์ประจำ",
    "email": "soravis@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_pitisant_039",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Suphamit",
    "last_name": "Pitisant",
    "full_name": "Suphamit Pitisant",
    "full_name_th": "รศ.ดร. ศุภมิตร ปิติพัฒน์",
    "role": "อาจารย์ประจำ",
    "email": "spitipat@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_kunmas_040",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Nuttanont",
    "last_name": "Kunmas",
    "full_name": "Nuttanont Kunmas",
    "full_name_th": "รศ.ดร. ณัฐนันท์ คุณมาศ",
    "role": "อาจารย์ประจำ",
    "email": "kunnamas@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_cheepeutrakul_041",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Kasira",
    "last_name": "Cheepeutrakul",
    "full_name": "Kasira Cheepeutrakul",
    "full_name_th": "รศ.ดร. กษิร ชีพเป็นสุข",
    "role": "อาจารย์ประจำ",
    "email": "kasira.c@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_horachaikul_042",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Surat",
    "last_name": "Horachaikul",
    "full_name": "Surat Horachaikul",
    "full_name_th": "รศ. สุรัตน์ โหราชัยกุล",
    "role": "อาจารย์ประจำ",
    "email": "surat.h@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_charoenying_043",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kalaya",
    "last_name": "Charoenying",
    "full_name": "Kalaya Charoenying",
    "full_name_th": "ผศ.ดร. กัลยา เจริญยิ่ง",
    "role": "อาจารย์ประจำ",
    "email": "kalaya.ch@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_busbarat_044",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Pongphisoot",
    "last_name": "Busbarat",
    "full_name": "Pongphisoot Busbarat",
    "full_name_th": "ผศ.ดร. พงศ์พิสุทธิ์ บุษบารัตน์",
    "role": "อาจารย์ประจำ",
    "email": "pongphisoot.b@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_suputtikul_045",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Teewin",
    "last_name": "Suputtikul",
    "full_name": "Teewin Suputtikul",
    "full_name_th": "ผศ.ดร. ธีวินท์ สุพุทธิกุล",
    "role": "อาจารย์ประจำ",
    "email": "teewino@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_phuapansawat_046",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Khorapin",
    "last_name": "Phuapansawat",
    "full_name": "Khorapin Phuapansawat",
    "full_name_th": "ผศ.ดร. กรพินธุ์ พัวพันสวัสดิ์",
    "role": "อาจารย์ประจำ",
    "email": "phuak238@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_jittiang_047",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Bhanubhatra",
    "last_name": "Jittiang",
    "full_name": "Bhanubhatra Jittiang",
    "full_name_th": "ผศ.ดร. ภาณุภัทร จิตเที่ยง",
    "role": "อาจารย์ประจำ",
    "email": "bhanubhatra.j@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_mangkang_048",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Hassachai",
    "last_name": "Mangkang",
    "full_name": "Hassachai Mangkang",
    "full_name_th": "อ.ดร. นาวาเอก อ.ดร.หัสไชยญ์ มั่งคั่ง",
    "role": "อาจารย์ประจำ",
    "email": "hassachai.m@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_sawangsilp_049",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "department_th": "ภาควิชาความสัมพันธ์ระหว่างประเทศ",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Sorasich",
    "last_name": "Sawangsilp",
    "full_name": "Sorasich Sawangsilp",
    "full_name_th": "อ.ดร. สรสิช สว่างศิลป์",
    "role": "อาจารย์ประจำ",
    "email": "sorasich.s@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_rukumnuaykit_050",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Pungpond",
    "last_name": "Rukumnuaykit",
    "full_name": "Pungpond Rukumnuaykit",
    "full_name_th": "ศ.ดร. ปังปอนด์ รักอํานวยกิจ",
    "role": "อาจารย์ประจำ",
    "email": "pungpond_r@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_sirikod_051",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pakorn",
    "last_name": "Sirikod",
    "full_name": "Pakorn Sirikod",
    "full_name_th": "รศ.ดร. ปกรณ์ ศิริประกอบ",
    "role": "อาจารย์ประจำ",
    "email": "popsiri@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_kruatep_052",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Weerasak",
    "last_name": "Kruatep",
    "full_name": "Weerasak Kruatep",
    "full_name_th": "รศ.ดร. วีระศักดิ์ เครือเทพ",
    "role": "อาจารย์ประจำ",
    "email": "weerasak.k@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_chaiperm_053",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Ackadej",
    "last_name": "Chaiperm",
    "full_name": "Ackadej Chaiperm",
    "full_name_th": "ผศ.ดร. อัครเดช ไชยเพิ่ม",
    "role": "อาจารย์ประจำ",
    "email": "ackadej.chaiperm@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_rojananon_054",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Chadin",
    "last_name": "Rojananon",
    "full_name": "Chadin Rojananon",
    "full_name_th": "ผศ.ดร. ชฎิล โรจนานนท์",
    "role": "อาจารย์ประจำ",
    "email": "chadinroch@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_siriprapanukul_055",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Pawin",
    "last_name": "Siriprapanukul",
    "full_name": "Pawin Siriprapanukul",
    "full_name_th": "ผศ.ดร. ภาวิน ศิริประภานุกูล",
    "role": "อาจารย์ประจำ",
    "email": "s.pawin@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_pariponueasakul_056",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Suthamma",
    "last_name": "Paripon-Ueasakul",
    "full_name": "Suthamma Paripon-Ueasakul",
    "full_name_th": "ผศ.ดร. สุธรรมา ปริพนธ์เอื้อสกุล",
    "role": "อาจารย์ประจำ",
    "email": "suthamma.n@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_aroonsri_057",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Pimsiri",
    "last_name": "Aroonsri",
    "full_name": "Pimsiri Aroonsri",
    "full_name_th": "ผศ.ดร. พิมพ์สิริ อรุณศรี",
    "role": "อาจารย์ประจำ",
    "email": "pimsiri.a@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_jaturachinda_058",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Chayanuch",
    "last_name": "Jaturachinda",
    "full_name": "Chayanuch Jaturachinda",
    "full_name_th": "ผศ. ชญานุช จาตุรจินดา",
    "role": "อาจารย์ประจำ",
    "email": "salicupt@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_srijamroen_059",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Wimonmat",
    "last_name": "Srijamroen",
    "full_name": "Wimonmat Srijamroen",
    "full_name_th": "อ.ดร. วิมลมาศ ศรีจำเริญ",
    "role": "อาจารย์ประจำ",
    "email": "wimonmat.s@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_phanpakdee_060",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Waewpailin",
    "last_name": "Phanpakdee",
    "full_name": "Waewpailin Phanpakdee",
    "full_name_th": "อ.ดร. แววไพลิน พันธุ์ภักดี",
    "role": "อาจารย์ประจำ",
    "email": "waewpailin.p@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_burapadecha_061",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Vasa",
    "last_name": "Burapadecha",
    "full_name": "Vasa Burapadecha",
    "full_name_th": "อ.ดร. วสะ บูรพาเดชะ",
    "role": "อาจารย์ประจำ",
    "email": "vasa.b@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_potipiroon_062",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชารัฐประศาสนศาสตร์",
    "department_th": "ภาควิชารัฐประศาสนศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Wisanupong",
    "last_name": "Potipiroon",
    "full_name": "Wisanupong Potipiroon",
    "full_name_th": "อ.ดร. วิษณุพงษ์ โพธิพิรุฬห์",
    "role": "อาจารย์ประจำ",
    "email": "wisanupong.p@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_jitsawang_063",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Sumonthip",
    "last_name": "Jitsawang",
    "full_name": "Sumonthip Jitsawang",
    "full_name_th": "รศ.ดร. สุมนทิพย์ จิตสว่าง",
    "role": "อาจารย์ประจำ",
    "email": "sumonthip99@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_lerttomornsakul_064",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Unisa",
    "last_name": "Lerttomornsakul",
    "full_name": "Unisa Lerttomornsakul",
    "full_name_th": "รศ.ดร. อุนิษา เลิศโตมรสกุล",
    "role": "อาจารย์ประจำ",
    "email": "unisa@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_srirattanaball_065",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pavika",
    "last_name": "Srirattanaball",
    "full_name": "Pavika Srirattanaball",
    "full_name_th": "รศ.ดร. ภาวิกา ศรีรัตนบัลล์",
    "role": "อาจารย์ประจำ",
    "email": "pavika.s@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_thianthai_066",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Chulanee",
    "last_name": "Thianthai",
    "full_name": "Chulanee Thianthai",
    "full_name_th": "รศ.ดร. จุลนี เทียนไทย",
    "role": "อาจารย์ประจำ",
    "email": "chulanee00@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_palakawongnaayu_068",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Siripong",
    "last_name": "Palakawong Na Ayuthaya",
    "full_name": "Siripong Palakawong Na Ayuthaya",
    "full_name_th": "รศ.ดร. ศิริพงศ์ ปาลกะวงศ์ ณ อยุธยา",
    "role": "อาจารย์ประจำ",
    "email": "siripong.spa@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_thongsawang_069",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Sirima",
    "last_name": "Thongsawang",
    "full_name": "Sirima Thongsawang",
    "full_name_th": "รศ.ดร. ศิริมา ทองสว่าง",
    "role": "อาจารย์ประจำ",
    "email": "sirima.th@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_phetmunee_070",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Thitiya",
    "last_name": "Phetmunee",
    "full_name": "Thitiya Phetmunee",
    "full_name_th": "ผศ.ดร. ฐิติยา เพชรมุนี",
    "role": "อาจารย์ประจำ",
    "email": "thitiya.p@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_chuenpitayatorn_071",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Keerati",
    "last_name": "Chuenpitayatorn",
    "full_name": "Keerati Chuenpitayatorn",
    "full_name_th": "ผศ.ดร. กีรติ ชื่นพิทยาธร",
    "role": "อาจารย์ประจำ",
    "email": "keerati.chenp@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_laocharoenwong_072",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Jiraporn",
    "last_name": "Laocharoenwong",
    "full_name": "Jiraporn Laocharoenwong",
    "full_name_th": "ผศ.ดร. จิราพร เหล่าเจริญวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "jiraporn.la@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_sakwit_073",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kulpathu",
    "last_name": "Sakwit",
    "full_name": "Kulpathu Sakwit",
    "full_name_th": "ผศ.ดร. กุลพธู ศักดิ์วิทย์",
    "role": "อาจารย์ประจำ",
    "email": "platuna42@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_wanichwiwatana_074",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Amorn",
    "last_name": "Wanichwiwatana",
    "full_name": "Amorn Wanichwiwatana",
    "full_name_th": "อ.ดร. อมร วาณิชวิวัฒน์",
    "role": "อาจารย์ประจำ",
    "email": "a.wanichwiwatana@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_boonwanno_075",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Thanida",
    "last_name": "Boonwanno",
    "full_name": "Thanida Boonwanno",
    "full_name_th": "อ.ดร. ฐานิดา บุญวรรโณ",
    "role": "อาจารย์ประจำ",
    "email": "thanida.b@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_liemdee_076",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Kathaleeya",
    "last_name": "Liemdee",
    "full_name": "Kathaleeya Liemdee",
    "full_name_th": "อ.ดร. คัทลียา เหลี่ยมดี",
    "role": "อาจารย์ประจำ",
    "email": "khathaleeya.l@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_thongmuang_077",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Chaturawit",
    "last_name": "Thongmuang",
    "full_name": "Chaturawit Thongmuang",
    "full_name_th": "อ.ดร. จตุรวิทย์ ทองเมือง",
    "role": "อาจารย์ประจำ",
    "email": "chaturawit.t@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_middleton_078",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์ชาวต่างชาติ",
    "department_th": "คณาจารย์ชาวต่างชาติ",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Carl",
    "last_name": "Middleton",
    "full_name": "Carl Middleton",
    "full_name_th": "อ. Associate Professor Dr.Carl Middleton",
    "role": "อาจารย์ประจำ",
    "email": "carl.chulalongkorn@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_horstmann_079",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์ชาวต่างชาติ",
    "department_th": "คณาจารย์ชาวต่างชาติ",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Alexander",
    "last_name": "Horstmann",
    "full_name": "Alexander Horstmann",
    "full_name_th": "อ. Dr. Alexander Horstmann",
    "role": "อาจารย์ประจำ",
    "email": "alexander.horstmann@posteo.net",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_yavaprapas_080",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Supachai",
    "last_name": "Yavaprapas",
    "full_name": "Supachai Yavaprapas",
    "full_name_th": "ศ. กิตติคุณ ดร.ศุภชัย ยาวะประภาษ",
    "role": "อาจารย์ประจำ",
    "email": "supachai.yava1@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_bumrungsuk_081",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Surachart",
    "last_name": "Bumrungsuk",
    "full_name": "Surachart Bumrungsuk",
    "full_name_th": "ศ. กิตติคุณ ดร.สุรชาติ บำรุงสุข",
    "role": "อาจารย์ประจำ",
    "email": "newsecproject@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_chaiporn_082",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Chaiyan",
    "last_name": "Chaiporn",
    "full_name": "Chaiyan Chaiporn",
    "full_name_th": "ศ.ดร. ไชยันต์ ไชยพร",
    "role": "อาจารย์ประจำ",
    "email": "cchaiyan@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_uaamnoy_083",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Jutharat",
    "last_name": "Ua-amnoy",
    "full_name": "Jutharat Ua-amnoy",
    "full_name_th": "รศ.ดร. จุฑารัตน์ เอื้ออำนวย",
    "role": "อาจารย์ประจำ",
    "email": "jutharat.u@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_pintobtapong_084",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Prapart",
    "last_name": "Pintobtapong",
    "full_name": "Prapart Pintobtapong",
    "full_name_th": "รศ.ดร. ประภาส ปิ่นตบแต่ง",
    "role": "อาจารย์ประจำ",
    "email": "prapart.p@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_aedsakul_085",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Sirirat",
    "last_name": "Aedsakul",
    "full_name": "Sirirat Aedsakul",
    "full_name_th": "รศ.ดร. ศิริรัตน์ แอดสกุล",
    "role": "อาจารย์ประจำ",
    "email": "sirirath.a@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_panaspornprasit_086",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Chookiat",
    "last_name": "Panaspornprasit",
    "full_name": "Chookiat Panaspornprasit",
    "full_name_th": "รศ.ดร. ชูเกียรติ พนัสพรประสิทธิ์",
    "role": "อาจารย์ประจำ",
    "email": "anuwales@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_mahatthanobol_087",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Worasak",
    "last_name": "Mahatthanobol",
    "full_name": "Worasak Mahatthanobol",
    "full_name_th": "รศ. วรศักดิ์ มหัทธโนบล",
    "role": "อาจารย์ประจำ",
    "email": "vmahatdhanobol@yahoo.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_meechart_088",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Wanchai",
    "last_name": "Meechart",
    "full_name": "Wanchai Meechart",
    "full_name_th": "รศ. วันชัย มีชาติ",
    "role": "อาจารย์ประจำ",
    "email": "wanchaimeechart@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_tiprat_089",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Pranee",
    "last_name": "Tiprat",
    "full_name": "Pranee Tiprat",
    "full_name_th": "ผศ.ดร. ปราณี ทิพย์รัตน์",
    "role": "อาจารย์ประจำ",
    "email": "pranee.th@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofp_malakulnaayudhy_090",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Political Science",
    "faculty_th": "คณะรัฐศาสตร์",
    "department": "คณาจารย์พิเศษ",
    "department_th": "คณาจารย์พิเศษ",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Panaros",
    "last_name": "Malakul Na Ayudhya",
    "full_name": "Panaros Malakul Na Ayudhya",
    "full_name_th": "ผศ. ปัณรส มาลากุล ณ อยุธยา",
    "role": "อาจารย์ประจำ",
    "email": "panaros44@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
