# Chulalongkorn University Exhaustive Mastery Dataset
# Covers all 20 Faculties, 5 Colleges/Institutes, Sasin, Sports Science, JIPP, PPC, CPHS, CPS, PGS, EBA, BBA, BCM, LL.B.

CHULA_EXHAUSTIVE_COURSES = [
    # =========================================================================
    # 1. คณะวิทยาศาสตร์การกีฬา (Faculty of Sports Science - Chulalongkorn)
    # =========================================================================
    {
        "id": "cu_sports_bsc_exercise_science",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์การกีฬาและการออกกำลังกาย",
        "title_en": "Bachelor of Science Program in Sports and Exercise Science",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาศาสตร์การกีฬาและการออกกำลังกาย)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Sports Science",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬา",
        "department": "Department of Sports and Exercise Science",
        "department_th": "สาขาวิชาวิทยาศาสตร์การกีฬาและการออกกำลังกาย",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "คณะวิทยาศาสตร์การกีฬาอันดับ 1 ของประเทศ ศึกษาชีวกลศาสตร์การกีฬา สรีรวิทยาการออกกำลังกาย โภชนาการนักกีฬา และการฝึกสอนสมรรถภาพระดับสูง",
        "curriculum_highlights": ["ห้องปฏิบัติการวิเคราะห์การเคลื่อนไหว 3 มิติ (3D Motion Analysis Lab)", "ศูนย์ทดสอบสมรรถภาพทางกายมาตรฐานระดับสากลและฟิตเนสเซ็นเตอร์จุฬาฯ", "การดูแลและพัฒนานักกีฬาทีมชาติไทยและสโมสรกีฬาอาชีพ"],
        "career_paths": ["นักวิทยาศาสตร์การกีฬาและผู้เชี่ยวชาญด้านสมรรถภาพทางกาย (Strength & Conditioning Coach)", "ผู้ฝึกสอนกีฬาอาชีพ (Professional Coach)", "ที่ปรึกษาด้านการออกกำลังกายและสุขภาพในโรงพยาบาลและศูนย์สุขภาพ"],
        "tags": ["Sports Science", "Exercise Science", "Athletic Training", "Biomechanics", "Chula Sports"],
        "website_url": "https://spsc.chula.ac.th"
    },
    {
        "id": "cu_sports_msc_sports_science",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์การกีฬาและการออกกำลังกาย",
        "title_en": "Master of Science Program in Sports and Exercise Science",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (วิทยาศาสตร์การกีฬาและการออกกำลังกาย)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Sports Science",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬา",
        "department": "Department of Sports and Exercise Science",
        "department_th": "สาขาวิชาวิทยาศาสตร์การกีฬาและการออกกำลังกาย",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "38,000 บาท",
        "tuition_total": "152,000 บาท",
        "description": "วิจัยขั้นสูงด้านสรีรวิทยาการออกกำลังกายระดับโมเลกุล เทคโนโลยีชีวกลศาสตร์สำหรับการกีฬา และการฟื้นฟูสมรรถภาพนักกีฬาขั้นสูง",
        "curriculum_highlights": ["การวิจัยกลไกการล้าและการฟื้นฟูกล้ามเนื้อของนักกีฬาระดับสูง", "การประยุกต์ใช้เทคโนโลยี AI และเซนเซอร์สวมใส่ (Wearable Sensors) ในการกีฬา", "การตีพิมพ์ในวารสารวิทยาศาสตร์การกีฬาระดับนานาชาติ (Q1/Q2)"],
        "career_paths": ["นักวิจัยวิทยาศาสตร์การกีฬาและสุขภาพ", "หัวหน้าทีมวิทยาศาสตร์การกีฬาประจำทีมชาติ / สโมสรชั้นนำ", "อาจารย์ประจำมหาวิทยาลัย"],
        "tags": ["Sports Science", "Exercise Physiology", "Biomechanics", "Master of Science", "Chula"],
        "website_url": "https://spsc.chula.ac.th"
    },

    # =========================================================================
    # 2. สถาบันบัณฑิตบริหารธุรกิจ ศศินทร์ (Sasin School of Management)
    # =========================================================================
    {
        "id": "cu_sasin_flexible_mba",
        "title_th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต (Sasin Flexible MBA - หลักสูตรนานาชาติ)",
        "title_en": "Master of Business Administration Program (Sasin Flexible MBA - International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "บธ.ม. (บริหารธุรกิจ)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Sasin School of Management",
        "faculty_th": "สถาบันบัณฑิตบริหารธุรกิจ ศศินทร์แห่งจุฬาลงกรณ์มหาวิทยาลัย",
        "department": "Department of Business Administration",
        "department_th": "สาขาวิชาบริหารธุรกิจ",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "48 หน่วยกิต",
        "tuition_per_semester": "265,000 บาท",
        "tuition_total": "1,590,000 บาท",
        "description": "สถาบันบริหารธุรกิจระดับโลกแห่งแรกของไทย ก่อตั้งร่วมกับ Kellogg School of Management (Northwestern) และ The Wharton School (UPenn) ได้รับการรับรอง AACSB และ EQUIS",
        "curriculum_highlights": ["ความร่วมมือกับ Kellogg School of Management และ The Wharton School", "การรับรองมาตรฐานสากลระดับโลก AACSB และ EQUIS (Double Crown Accreditation)", "เครือข่ายศิษย์เก่าระดับผู้นำธุรกิจชั้นสูงสุด (C-Level Executives & Unicorn Founders)"],
        "career_paths": ["Chief Executive Officer (CEO) / Managing Director", "Management Consultant (McKinsey, BCG, Bain)", "Venture Capitalist / Private Equity Partner", "Global Entrepreneur"],
        "tags": ["Sasin", "MBA", "Kellogg", "Wharton", "AACSB", "EQUIS", "Leadership", "Chula Sasin"],
        "website_url": "https://sasin.edu"
    },
    {
        "id": "cu_sasin_executive_mba",
        "title_th": "หลักสูตรบริหารธุรกิจมหาบัณฑิตสำหรับผู้บริหาร (Sasin Executive MBA - EMBA)",
        "title_en": "Executive Master of Business Administration Program (Sasin Executive MBA - EMBA)",
        "degree_level": "ปริญญาโท",
        "degree_name": "บธ.ม. (บริหารธุรกิจสำหรับผู้บริหาร)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Sasin School of Management",
        "faculty_th": "สถาบันบัณฑิตบริหารธุรกิจ ศศินทร์แห่งจุฬาลงกรณ์มหาวิทยาลัย",
        "department": "Executive Education",
        "department_th": "สาขาวิชาบริหารธุรกิจผู้บริหาร",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "45 หน่วยกิต",
        "tuition_per_semester": "340,000 บาท",
        "tuition_total": "2,040,000 บาท",
        "description": "หลักสูตรสำหรับผู้บริหารระดับสูงและเจ้าของธุรกิจที่มีประสบการณ์ทำงานกว่า 8 ปี มุ่งเน้นการวางกลยุทธ์ระดับโลก การนำองค์กรสู่ความยั่งยืน และการทรานส์ฟอร์มธุรกิจ",
        "curriculum_highlights": ["International Residential Trips ณ สถาบันพันธมิตรในสหรัฐอเมริกาและยุโรป", "การเรียนการสอนเชิงกลยุทธ์และการแลกเปลี่ยนวิสัยทัศน์กับผู้บริหารระดับสูง", "คณาจารย์ผู้ทรงคุณวุฒิและ Visiting Professors จาก Kellogg และ Wharton"],
        "career_paths": ["C-Suite Executives (CEO, COO, CFO)", "Business Owners / Board of Directors", "Senior Vice President ในบรรษัทข้ามชาติ"],
        "tags": ["Sasin", "EMBA", "Executive MBA", "Wharton", "Kellogg", "Chula Sasin"],
        "website_url": "https://sasin.edu"
    },
    {
        "id": "cu_sasin_phd_business",
        "title_th": "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาบริหารธุรกิจ (Sasin Ph.D. - หลักสูตรนานาชาติ)",
        "title_en": "Doctor of Philosophy Program in Business Administration (Sasin Ph.D. - International Program)",
        "degree_level": "ปริญญาเอก",
        "degree_name": "ปร.ด. (บริหารธุรกิจ)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Sasin School of Management",
        "faculty_th": "สถาบันบัณฑิตบริหารธุรกิจ ศศินทร์แห่งจุฬาลงกรณ์มหาวิทยาลัย",
        "department": "Doctoral Program in Business Administration",
        "department_th": "สาขาวิชาบริหารธุรกิจดุษฎีบัณฑิต",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "60 หน่วยกิต",
        "tuition_per_semester": "200,000 บาท",
        "tuition_total": "1,600,000 บาท",
        "description": "ผลิตนักวิชาการและนักวิจัยระดับปริญญาเอกชั้นนำในสาขาการเงินและการตลาด โดยเน้นการวิจัยเชิงประจักษ์ที่มีผลกระทบระดับโลก",
        "curriculum_highlights": ["การทำงานวิจัยร่วมกับคณาจารย์ระดับโลกจาก Kellogg และ Wharton", "การเตรียมความพร้อมเพื่อตีพิมพ์ในวารสารระดับท็อป (UT Dallas / FT50 Journals)", "การนำเสนอผลงานในที่ประชุมวิชาการระดับโลก (AFA, AMA, AOM)"],
        "career_paths": ["อาจารย์ประจำคณะบริหารธุรกิจในมหาวิทยาลัยระดับโลก", "นักวิจัยเศรษฐศาสตร์และธุรกิจอาวุโส", "Chief Economist / Chief Strategy Officer"],
        "tags": ["Sasin", "Ph.D.", "Business Administration", "Finance", "Marketing", "Doctoral"],
        "website_url": "https://sasin.edu"
    },

    # =========================================================================
    # 3. คณะจิตวิทยา - JIPP (Joint International Psychology Program)
    # =========================================================================
    {
        "id": "cu_psych_bsc_jipp",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์จิตวิทยา (หลักสูตรร่วมสองปริญญา จุฬาฯ - U. of Queensland - JIPP)",
        "title_en": "Bachelor of Science Program in Psychological Science (Joint International Program - JIPP)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาศาสตร์จิตวิทยา)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Psychology",
        "faculty_th": "คณะจิตวิทยา",
        "department": "Joint International Psychology Program (JIPP)",
        "department_th": "สาขาวิชาจิตวิทยานานาชาติ",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "95,000 บาท (จุฬาฯ) / ตามอัตรา UQ ออสเตรเลีย",
        "tuition_total": "980,000 บาท",
        "description": "หลักสูตรสองปริญญาตรีระดับนานาชาติชั้นนำ เรียน 2 ปีที่จุฬาฯ และ 2 ปีที่ University of Queensland (Top 50 ของโลกในออสเตรเลีย) ได้รับปริญญาจากทั้ง 2 สถาบัน",
        "curriculum_highlights": ["ได้รับปริญญาตรี 2 ใบจากจุฬาลงกรณ์มหาวิทยาลัย และ The University of Queensland (Australia)", "การเรียนรู้จิตวิทยาคลินิก จิตวิทยาความรู้ความเข้าใจ (Cognitive) และประสาทวิทยาศาสตร์", "ได้รับการรับรองจาก Australian Psychology Accreditation Council (APAC)"],
        "career_paths": ["นักจิตวิทยาคลินิก / นักจิตวิทยาองค์กรระดับสากล", "นักวิจัยด้านพฤติกรรมศาสตร์และประสาทวิทยาศาสตร์", "ผู้เชี่ยวชาญด้าน Human Factors และ User Experience (UX Researcher)"],
        "tags": ["JIPP", "Psychology", "University of Queensland", "Double Degree", "International", "Chula"],
        "website_url": "https://jipp.psy.chula.ac.th"
    },

    # =========================================================================
    # 4. วิทยาลัยปิโตรเลียมและปิโตรเคมี (The Petroleum and Petrochemical College - PPC)
    # =========================================================================
    {
        "id": "cu_ppc_msc_polymer_science",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์พอลิเมอร์ (หลักสูตรนานาชาติ - PPC)",
        "title_en": "Master of Science Program in Polymer Science (International Program - PPC)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (วิทยาศาสตร์พอลิเมอร์)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "The Petroleum and Petrochemical College (PPC)",
        "faculty_th": "วิทยาลัยปิโตรเลียมและปิโตรเคมี",
        "department": "Department of Polymer Science",
        "department_th": "สาขาวิชาวิทยาศาสตร์พอลิเมอร์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "60,000 บาท",
        "tuition_total": "240,000 บาท",
        "description": "วิทยาลัยเฉพาะทางระดับบัณฑิตศึกษาร่วมกับ University of Michigan และ University of Akron (USA) เชี่ยวชาญพอลิเมอร์ชีวภาพ พลาสติกรีไซเคิล และพอลิเมอร์นำไฟฟ้า",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษ 100% ร่วมกับคณาจารย์จาก University of Michigan (USA)", "ห้องปฏิบัติการสังเคราะห์พอลิเมอร์และวิเคราะห์โครงสร้างขั้นสูงระดับสากล", "ทุนการศึกษาและโครงงานวิจัยที่สนับสนุนโดยกลุ่มอุตสาหกรรมปิโตรเคมี (SCG, PTTGC)"],
        "career_paths": ["นักวิจัยและพัฒนาพอลิเมอร์และพลาสติกชีวภาพ (Polymer R&D Scientist)", "วิศวกรและผู้เชี่ยวชาญด้านวัสดุพอลิเมอร์ในภาคอุตสาหกรรม", "อาจารย์และนักวิจัยมหาวิทยาลัย"],
        "tags": ["Polymer Science", "PPC Chula", "Petrochemical", "University of Michigan", "International Program"],
        "website_url": "https://ppc.chula.ac.th"
    },
    {
        "id": "cu_ppc_msc_petroleum_tech",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาเทคโนโลยีปิโตรเลียมและพลังงาน (หลักสูตรนานาชาติ - PPC)",
        "title_en": "Master of Science Program in Petroleum and Energy Technology (International Program - PPC)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (เทคโนโลยีปิโตรเลียมและพลังงาน)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "The Petroleum and Petrochemical College (PPC)",
        "faculty_th": "วิทยาลัยปิโตรเลียมและปิโตรเคมี",
        "department": "Department of Petroleum Technology",
        "department_th": "สาขาวิชาเทคโนโลยีปิโตรเลียม",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "60,000 บาท",
        "tuition_total": "240,000 บาท",
        "description": "หลักสูตรร่วมกับ University of Oklahoma (USA) ศึกษาการขุดเจาะและสำรวจปิโตรเลียมขั้นสูง พลังงานไฮโดรเจน และการดักจับกักเก็บคาร์บอน (CCUS)",
        "curriculum_highlights": ["ความร่วมมือทางวิชาการกับ University of Oklahoma (USA)", "การวิจัยการเปลี่ยนผ่านสู่พลังงานสะอาด (Energy Transition) และพลังงานไฮโดรเจน", "โอกาสทำวิทยานิพนธ์ร่วมกับบริษัทสำรวจและผลิตปิโตรเลียมชั้นนำ (PTTEP, Chevron)"],
        "career_paths": ["Petroleum & Energy Reservoir Engineer", "CCUS & Clean Energy Specialist", "นักวิจัยเทคโนโลยีพลังงานขั้นสูง"],
        "tags": ["Petroleum Technology", "Energy", "PPC Chula", "University of Oklahoma", "CCUS"],
        "website_url": "https://ppc.chula.ac.th"
    },

    # =========================================================================
    # 5. วิทยาลัยประชากรศาสตร์ (College of Population Studies - CPS Chula)
    # =========================================================================
    {
        "id": "cu_cps_ma_demography",
        "title_th": "หลักสูตรศิลปศาสตรมหาบัณฑิต สาขาวิชาประชากรศาสตร์ (หลักสูตรนานาชาติ)",
        "title_en": "Master of Arts Program in Demography (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "ศศ.ม. (ประชากรศาสตร์)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "College of Population Studies (CPS)",
        "faculty_th": "วิทยาลัยประชากรศาสตร์",
        "department": "Department of Population Studies",
        "department_th": "สาขาวิชาประชากรศาสตร์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "50,000 บาท",
        "tuition_total": "200,000 บาท",
        "description": "ศูนย์กลางการวิจัยด้านประชากรศาสตร์ชั้นนำของเอเชีย เน้นการวิเคราะห์โครงสร้างประชากร สังคมสูงวัยสมบูรณ์ (Super-Aged Society) การย้ายถิ่นฐาน และนโยบายประชากร",
        "curriculum_highlights": ["การวิเคราะห์ข้อมูลประชากรเชิงลึก (Demographic Modeling & Big Data)", "การศึกษาวิจัยผลกระทบของสังคมผู้สูงอายุและการวางแผนระบบบำนาญ", "ความร่วมมือกับองค์การสหประชาชาติ (UNFPA, WHO)"],
        "career_paths": ["นักประชากรศาสตร์และนักวิเคราะห์นโยบายประชากร (Demographer)", "นักวิจัยในองค์กรระหว่างประเทศ (UN, World Bank)", "ที่ปรึกษาวางแผนยุทธศาสตร์เศรษฐกิจและสังคม"],
        "tags": ["Demography", "Population Studies", "Aging Society", "UNFPA", "CPS Chula"],
        "website_url": "https://cps.chula.ac.th"
    },

    # =========================================================================
    # 6. วิทยาลัยวิทยาศาสตร์สาธารณสุข (College of Public Health Sciences - CPHS)
    # =========================================================================
    {
        "id": "cu_cphs_mph_public_health",
        "title_th": "หลักสูตรสาธารณสุขศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์สาธารณสุข (หลักสูตรนานาชาติ)",
        "title_en": "Master of Public Health Program in Public Health Sciences (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "ส.ม. (วิทยาศาสตร์สาธารณสุข)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "College of Public Health Sciences (CPHS)",
        "faculty_th": "วิทยาลัยวิทยาศาสตร์สาธารณสุข",
        "department": "Department of Public Health Sciences",
        "department_th": "สาขาวิชาวิทยาศาสตร์สาธารณสุข",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "60,000 บาท",
        "tuition_total": "240,000 บาท",
        "description": "เน้นการวิจัยสุขภาวะระดับสากล ระบาดวิทยาข้ามพรมแดน การควบคุมสารเสพติดและยาสูบ สุขภาพสิ่งแวดล้อม และระบบสารสนเทศสาธารณสุข",
        "curriculum_highlights": ["ศูนย์ความร่วมมือขององค์การอนามัยโลก (WHO Collaborating Centre)", "การศึกษาวิจัยสุขภาพประชากรระดับภูมิภาคเอเชียและแปซิฟิก", "นักศึกษาและคณาจารย์หลากหลายสัญชาติจากกว่า 20 ประเทศทั่วโลก"],
        "career_paths": ["นักวิชาการสาธารณสุขระหว่างประเทศ (WHO, ASEAN, CDC)", "ผู้เชี่ยวชาญการประเมินความเสี่ยงสุขภาพและสิ่งแวดล้อม", "ผู้บริหารนโยบายสุขภาพและสาธารณสุขโลก"],
        "tags": ["Public Health", "Global Health", "Epidemiology", "WHO", "CPHS Chula"],
        "website_url": "https://cphs.chula.ac.th"
    },

    # =========================================================================
    # 7. คณะรัฐศาสตร์ - PGS (Politics and Global Studies - International)
    # =========================================================================
    {
        "id": "cu_polsci_ba_pgs_intl",
        "title_th": "หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาการเมืองและโลกสัมพันธ์ศึกษา (หลักสูตรนานาชาติ - PGS)",
        "title_en": "Bachelor of Arts in Politics and Global Studies (International Program - PGS)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ. (การเมืองและโลกสัมพันธ์ศึกษา)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Political Science",
        "faculty_th": "คณะรัฐศาสตร์",
        "department": "PGS Program",
        "department_th": "สาขาวิชาการเมืองและโลกสัมพันธ์ศึกษานานาชาติ",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "92,000 บาท",
        "tuition_total": "736,000 บาท",
        "description": "หลักสูตรรัฐศาสตร์นานาชาติชั้นนำของจุฬาฯ ผสานทฤษฎีความสัมพันธ์ระหว่างประเทศ (IR) ภูมิรัฐศาสตร์โลก นโยบายสาธารณะเปรียบเทียบ และการทูตยุคใหม่",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษ 100% กับผู้เชี่ยวชาญความสัมพันธ์ระหว่างประเทศระดับโลก", "โอกาสแลกเปลี่ยนกับมหาวิทยาลัยชั้นนำในสหราชอาณาจักร ออสเตรเลีย และยุโรป", "การจำลองการประชุมสหประชาชาติ (Model United Nations - MUN) และการทูตเชิงปฏิบัติ"],
        "career_paths": ["นักการทูตและเจ้าหน้าที่กระทรวงการต่างประเทศ", "เจ้าหน้าที่ประจำองค์การระหว่างประเทศ (UN, ASEAN, World Bank)", "นักวิเคราะห์ความเสี่ยงทางการเมืองระหว่างประเทศ (Political Risk Analyst)"],
        "tags": ["PGS", "Political Science", "International Relations", "Diplomacy", "Chula PolSci"],
        "website_url": "https://pgs.polsci.chula.ac.th"
    },

    # =========================================================================
    # 8. คณะนิเทศศาสตร์ - BCM (Communication Management - International)
    # =========================================================================
    {
        "id": "cu_commarts_ba_bcm_intl",
        "title_th": "หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาการจัดการการสื่อสาร (หลักสูตรนานาชาติ - BCM CommArts)",
        "title_en": "Bachelor of Arts in Communication Management (International Program - BCM CommArts)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ. (การจัดการการสื่อสาร)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Communication Arts",
        "faculty_th": "คณะนิเทศศาสตร์",
        "department": "International Program in Communication Management",
        "department_th": "สาขาวิชาการจัดการการสื่อสารนานาชาติ",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "88,000 บาท",
        "tuition_total": "704,000 บาท",
        "description": "หลักสูตรนิเทศศาสตร์นานาชาติอันดับ 1 ของไทย เน้นการบริหารจัดการแบรนด์ระดับโลก การตลาดดิจิทัล การสื่อสารองค์กรเชิงกลยุทธ์ และการผลิตสื่อสร้างสรรค์",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษ 100% โดยผู้เชี่ยวชาญและคณาจารย์ระดับสากล", "โครงงานการสร้างแคมเปญสื่อสารการตลาดจริงกับแบรนด์ระดับโลก", "เครือข่ายศิษย์เก่าระดับผู้บริหารในวงการเอเจนซี่โฆษณา สื่อ และการตลาดข้ามชาติ"],
        "career_paths": ["Global Brand Manager / Marketing Communications Manager", "Strategic Planner ในเอเจนซี่โฆษณาระดับโลก", "Corporate Communications & Public Relations Specialist"],
        "tags": ["BCM", "Communication Arts", "Brand Management", "Digital Marketing", "Chula CommArts"],
        "website_url": "https://inter.commarts.chula.ac.th"
    },
]
