# -*- coding: utf-8 -*-
EXTRACTED_FACULTIES = [
    {
        "id": "chulalongk_facultyofc_boonnimit_001",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Communication Arts",
        "faculty_th": "คณะนิเทศศาสตร์",
        "department": "คณะนิเทศศาสตร์",
        "department_th": "คณะนิเทศศาสตร์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Sopawan",
        "last_name": "Boonnimit",
        "full_name": "Sopawan Boonnimit",
        "full_name_th": "อ. โสภาวรรณ บุญนิมิตร",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofc_thianthaworn_002",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Faculty of Journalism and Mass Communication",
        "faculty_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "department": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "department_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Ekapon",
        "last_name": "Thianthaworn",
        "full_name": "Ekapon Thianthaworn",
        "full_name_th": "ผศ.ดร. เอกพล เธียรถาวร",
        "role": "อาจารย์ประจำ",
        "email": "ekapon.t@tu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "วารสารศาสตร์"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofc_saengsingkeo_003",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Journalism and Mass Communication",
        "faculty_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "department": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "department_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Nitida",
        "last_name": "Saengsingkeo",
        "full_name": "Nitida Saengsingkeo",
        "full_name_th": "รศ.ดร. นิธิดา แสงสิงแก้ว",
        "role": "อาจารย์ประจำ",
        "email": "niitiidaa@gmail.com",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofc_pandaranuwong_004",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Faculty of Journalism and Mass Communication",
        "faculty_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "department": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "department_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Atchara",
        "last_name": "Pandaranuwong",
        "full_name": "Atchara Pandaranuwong",
        "full_name_th": "ผศ.ดร. อัจฉรา ปัณฑรานุวงศ์",
        "role": "อาจารย์ประจำ",
        "email": "padchara@tu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofc_ronawech_005",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Journalism and Mass Communication",
        "faculty_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "department": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "department_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Monaiphol",
        "last_name": "Ronawech",
        "full_name": "Monaiphol Ronawech",
        "full_name_th": "ผศ.ดร. โมไนยพล รณเวช",
        "role": "อาจารย์ประจำ",
        "email": "monaiphol2026@gmail.com",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
