# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/dentistry_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "chulalongk_facultyofd_kamonkhantikul_001",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "ภาควิชาทันตกรรมประดิษฐ์",
    "department_th": "ภาควิชาทันตกรรมประดิษฐ์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Krit",
    "last_name": "Kamonkhantikul",
    "full_name": "Krit Kamonkhantikul",
    "full_name_th": "ผศ. ทพ.ดร.กฤช กมลขันติกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_phijitbundarn_002",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Sitapa",
    "last_name": "Phijitbundarn",
    "full_name": "Sitapa Phijitbundarn",
    "full_name_th": "อ.ดร. Sitapa Phijitbundarn",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "D.D.S",
      "Diplomate, Thai Board of Dental"
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_kosalanunt_003",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "ภาควิชาพยาธิวิทยาช่องปากและแม็กซิลโลเฟเชียล",
    "department_th": "ภาควิชาพยาธิวิทยาช่องปากและแม็กซิลโลเฟเชียล",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Theerachai",
    "last_name": "Kosalanunt",
    "full_name": "Theerachai Kosalanunt",
    "full_name_th": "ผศ. ทพ.ธีรชัย โกศัลวัฒน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_assoratkul_004",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "It",
    "last_name": "Assoratkul",
    "full_name": "It Assoratkul",
    "full_name_th": "ดร. อิษฏ์ อัสโสรัตน์กุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_porntaveetus_005",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Thantrira",
    "last_name": "Porntaveetus",
    "full_name": "Thantrira Porntaveetus",
    "full_name_th": "ศ. ทพญ.ดร.ฑัณฑริรา พรทวีทัศน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_trachu_006",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Vorapat",
    "last_name": "Trachu",
    "full_name": "Vorapat Trachu",
    "full_name_th": "ผศ. ทพ.นพ.วรภัทร ตราชู",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_amatyakul_007",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "ภาควิชาสรีรวิทยา",
    "department_th": "ภาควิชาสรีรวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Suphatra",
    "last_name": "Amatyakul",
    "full_name": "Suphatra Amatyakul",
    "full_name_th": "รศ.ดร. สุภัทรา อมาตยกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_suporn_008",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "ภาควิชาสรีรวิทยา",
    "department_th": "ภาควิชาสรีรวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Weera",
    "last_name": "Suporn",
    "full_name": "Weera Suporn",
    "full_name_th": "รศ.ดร. วีระ สุพร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_jansisith_009",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Pornchai",
    "last_name": "Jansisith",
    "full_name": "Pornchai Jansisith",
    "full_name_th": "ศ. ทพ.ดร. พรชัย จันศิษ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_charoenrat_010",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Thanit",
    "last_name": "Charoenrat",
    "full_name": "Thanit Charoenrat",
    "full_name_th": "ผศ. ทพ.ธนิต เจริญรัตน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_chokchanachaisa_011",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Uraiwan",
    "last_name": "Chokchanachaisakul",
    "full_name": "Uraiwan Chokchanachaisakul",
    "full_name_th": "ผศ. ทพญ.ดร.อุไรวรรณ โชคชนะชัยสกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_kangsadanpipop_012",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Khajorn",
    "last_name": "Kangsadanpipop",
    "full_name": "Khajorn Kangsadanpipop",
    "full_name_th": "รศ. ทพ.ขจร กังสดาลพิภพ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_osathanon_013",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Thanaphum",
    "last_name": "Osathanon",
    "full_name": "Thanaphum Osathanon",
    "full_name_th": "ศ. ทพ.ดร.ธนภูมิ โอสถานนท์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_srethunyarat_014",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Suprida",
    "last_name": "Srethunyarat",
    "full_name": "Suprida Srethunyarat",
    "full_name_th": "ผศ. ทพญ.ดร.สุปรีดา ศรีธัญรัตน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_khabut_015",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Butsana",
    "last_name": "Khabut",
    "full_name": "Butsana Khabut",
    "full_name_th": "ผศ. ทพญ.ดร.บุศนา คะบุศ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_jansisiyont_016",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Pornchai",
    "last_name": "Jansisiyont",
    "full_name": "Pornchai Jansisiyont",
    "full_name_th": "ศ. ทพ.ดร. พรชัย จันศิษย์ยานนท์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_kridakorn_017",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "ภาควิชาชีวเคมี",
    "department_th": "ภาควิชาชีวเคมี",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Ood",
    "last_name": "Kridakorn",
    "full_name": "Ood Kridakorn",
    "full_name_th": "ศ. ทพ.ดร.ม.ร.ว. อ๊อด กฤดากร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_phantumvanit_018",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "ภาควิชาชีวเคมี",
    "department_th": "ภาควิชาชีวเคมี",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Prateep",
    "last_name": "Phantumvanit",
    "full_name": "Prateep Phantumvanit",
    "full_name_th": "รศ. ทพ. ประทีป พันธุมวนิช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_patinanu_019",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "ภาควิชาชีวเคมี",
    "department_th": "ภาควิชาชีวเคมี",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Pornsri",
    "last_name": "Patinanu",
    "full_name": "Pornsri Patinanu",
    "full_name_th": "รศ. พรศรี ปฏิมานุ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_fac_020_020",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Suntra",
    "last_name": "",
    "full_name": "Suntra",
    "full_name_th": "รศ.ดร. ทพ. สุนทรา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_kiattavorncharo_021",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "ภาควิชาศัลยศาสตร์ช่องปากและแม็กซิลโลเฟเชียล",
    "department_th": "ภาควิชาศัลยศาสตร์ช่องปากและแม็กซิลโลเฟเชียล",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Sirichai",
    "last_name": "Kiattavorncharoen",
    "full_name": "Sirichai Kiattavorncharoen",
    "full_name_th": "ศ. คลินิก ดร.นพ.ทพ. ศิริชัย เกียรติถาวรเจริญ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ศัลยศาสตร์ช่องปากและแม็กซิลโลเฟเชียล"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_teeradilok_022",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "ภาควิชาทันตกรรมทั่วไปขั้นสูง",
    "department_th": "ภาควิชาทันตกรรมทั่วไปขั้นสูง",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sasipa",
    "last_name": "Teeradilok",
    "full_name": "Sasipa Teeradilok",
    "full_name_th": "ผศ.ดร. ทพญ. ศศิภา ธีรดิลก",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_lapaut_023",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Khomsan",
    "last_name": "Lapaut",
    "full_name": "Khomsan Lapaut",
    "full_name_th": "ผศ. ทพ. คมสัน ลาภาอุตย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_arayasantiparb_024",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Raweewan",
    "last_name": "Arayasantiparb",
    "full_name": "Raweewan Arayasantiparb",
    "full_name_th": "รศ.ดร. ทพญ. ระวีวรรณ อารยะสันติภาพ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "รังสีวิทยาช่องปาก"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_sipiyarak_025",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kawin",
    "last_name": "Sipiyarak",
    "full_name": "Kawin Sipiyarak",
    "full_name_th": "ผศ.ดร. ทพ. กวิน สิปิยารักษ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_maitratanakul_026",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Somsak",
    "last_name": "Maitratanakul",
    "full_name": "Somsak Maitratanakul",
    "full_name_th": "รศ.ดร. ทพ. สมศักดิ์ ไมตรีรัตนะกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_raocharoenporn_027",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Somchat",
    "last_name": "Raocharoenporn",
    "full_name": "Somchat Raocharoenporn",
    "full_name_th": "ผศ. ทพ. สมชาติ เราเจริญพร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_fac_028_028",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Chaipol",
    "last_name": "",
    "full_name": "Chaipol",
    "full_name_th": "อ. ทพ. ชัยพล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_srimaneekarn_029",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Natchalee",
    "last_name": "Srimaneekarn",
    "full_name": "Natchalee Srimaneekarn",
    "full_name_th": "รศ.ดร. ทพญ. นัจชลี ศรีมณีกาญจน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofd_suddhasthiyasri_030",
    "university": "Chulalongkorn University & Mahidol University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย และ มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Dentistry",
    "faculty_th": "คณะทันตแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Srisurang",
    "last_name": "Suddhasthiyasri",
    "full_name": "Srisurang Suddhasthiyasri",
    "full_name_th": "รศ.ดร. ทพญ. ศรีสุรางค์ สุทธปรียาศรี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
