# -*- coding: utf-8 -*-
EXTRACTED_FACULTIES = [
    {
        "id": "chulalongk_facultyofe_tippayalai_001",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Katika",
        "last_name": "Tippayalai",
        "full_name": "Katika Tippayalai",
        "full_name_th": "ผศ.ดร. กติกา ทิพยาลัย",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_tournememe_002",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Frederic Jean Marie",
        "last_name": "Tournememe",
        "full_name": "Frederic Jean Marie Tournememe",
        "full_name_th": "ศ.ดร. เฟรเดริค ฌ็อง มารี ตูร์เนอเมน",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_thanapanich_004",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Nat",
        "last_name": "Thanapanich",
        "full_name": "Nat Thanapanich",
        "full_name_th": "อ.ดร. ณัฐ ธารพานิช",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_theingsri_005",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Khemrut",
        "last_name": "Theルingsri",
        "full_name": "Khemrut Theルingsri",
        "full_name_th": "รศ.ดร. เขมรัฐ เถลิงศรี",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_phanishsarn_006",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.",
        "academic_title_th": "รศ.",
        "first_name": "Aksornsri",
        "last_name": "Phanishsarn",
        "full_name": "Aksornsri Phanishsarn",
        "full_name_th": "รศ. อักษรศรี พานิชสาส์น",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_tanasritunyakul_007",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Alongkorn",
        "last_name": "Tanasritunyakul",
        "full_name": "Alongkorn Tanasritunyakul",
        "full_name_th": "ผศ. อลงกรณ์ ธนศรีตระกูล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_pawasutipaisit_008",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Anan",
        "last_name": "Pawasutipaisit",
        "full_name": "Anan Pawasutipaisit",
        "full_name_th": "อ. อานันท์ ภาวสุทธิไพสิฐ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_phankitnirundor_009",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Krit",
        "last_name": "Phankitnirundorn",
        "full_name": "Krit Phankitnirundorn",
        "full_name_th": "อ.ดร. กฤษฏิ์ ภัณฑ์กิจนิรันดร",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_saelee_010",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Kittichai",
        "last_name": "Saelee",
        "full_name": "Kittichai Saelee",
        "full_name_th": "ผศ.ดร. กิตติชัย แซ่ลี้",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_kulkantrakorn_011",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Kiriya",
        "last_name": "Kulkantrakorn",
        "full_name": "Kiriya Kulkantrakorn",
        "full_name_th": "รศ.ดร. กิริยา กุลกลการ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_liewskul_012",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Kusal",
        "last_name": "Liewskul",
        "full_name": "Kusal Liewskul",
        "full_name_th": "อ.ดร. กุศล เลี้ยวสกุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_techakanont_013",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Kriangkrai",
        "last_name": "Techakanont",
        "full_name": "Kriangkrai Techakanont",
        "full_name_th": "รศ.ดร. เกรียงไกร เตชกานนท์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_phankitnirundor_014",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Krit",
        "last_name": "Phankitnirundorn",
        "full_name": "Krit Phankitnirundorn",
        "full_name_th": "อ.ดร. กฤต ภัทรกิจนิรันดร์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_fakthong_015",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Tiraphap",
        "last_name": "Fakthong",
        "full_name": "Tiraphap Fakthong",
        "full_name_th": "ผศ.ดร. ถิรภาพ ฟักทอง",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. of Philosophy (Economics) University of Aberdeen, UK"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_pitidol_016",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Thorn",
        "last_name": "Pitidol",
        "full_name": "Thorn Pitidol",
        "full_name_th": "ผศ.ดร. ธร ปีติดล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D."
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_kanokpermpoon_017",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Monthon",
        "last_name": "Kanokpermpoon",
        "full_name": "Monthon Kanokpermpoon",
        "full_name_th": "ดร. มณฑล กนกเพ็ญพูน",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_tangkiengsirisi_018",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Supong",
        "last_name": "Tangkiengsirisin",
        "full_name": "Supong Tangkiengsirisin",
        "full_name_th": "ดร. สุพงศ์ ตั้งเคียงศิริสิน",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_jantori_019",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Parichat",
        "last_name": "Jantori",
        "full_name": "Parichat Jantori",
        "full_name_th": "ดร. ปาริฉัตร จันทรI",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_zhao_021",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Bin",
        "last_name": "Zhao",
        "full_name": "Bin Zhao",
        "full_name_th": "ดร. บิน จ้าว",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_chancharoenchai_022",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "ภาควิชาเศรษฐศาสตร์",
        "department_th": "ภาควิชาเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Kanokwan",
        "last_name": "Chancharoenchai",
        "full_name": "Kanokwan Chancharoenchai",
        "full_name_th": "รศ.ดร. กนกวรรณ จันทร์เจริญชัย",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D. (International Economics and Economics of Development), Southern"
        ],
        "research_interests": [
            "International Economics",
            "Economics of Development"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_toraninnitiyan_023",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "ภาควิชาสหกรณ์",
        "department_th": "ภาควิชาสหกรณ์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Nakhun",
        "last_name": "Toraninnitiyan",
        "full_name": "Nakhun Toraninnitiyan",
        "full_name_th": "รศ.ดร. ณคุณ ธรณีนิติญาณ",
        "role": "อาจารย์ประจำ",
        "email": "feconht@ku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_theeraphattana_024",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "ภาควิชาเศรษฐศาสตร์",
        "department_th": "ภาควิชาเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Siwapong",
        "last_name": "Theeraphattana",
        "full_name": "Siwapong Theeraphattana",
        "full_name_th": "รศ.ดร. ศิวพงศ์ ธีรภัทรวาณิชย์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_chai_025",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "ภาควิชาเศรษฐศาสตร์",
        "department_th": "ภาควิชาเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Natchanicha",
        "last_name": "Chai",
        "full_name": "Natchanicha Chai",
        "full_name_th": "ผศ.ดร. ณัฏฐณิชา ฉาย",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_suebpongsakorn_026",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "ภาควิชาสหกรณ์",
        "department_th": "ภาควิชาสหกรณ์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Attapol",
        "last_name": "Suebpongsakorn",
        "full_name": "Attapol Suebpongsakorn",
        "full_name_th": "รศ.ดร. อรรถพล สืบพงศกร",
        "role": "อาจารย์ประจำ",
        "email": "fecoapsu@ku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_luangaram_028",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Pongsak",
        "last_name": "Luangaram",
        "full_name": "Pongsak Luangaram",
        "full_name_th": "รศ.ดร. พงศ์ศักดิ์ เหลืองอร่าม",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_subhanij_030",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Tientip",
        "last_name": "Subhanij",
        "full_name": "Tientip Subhanij",
        "full_name_th": "ผศ.ดร. เทียนทิพ สุพานิช",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_srisangnam_031",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Piti",
        "last_name": "Srisangnam",
        "full_name": "Piti Srisangnam",
        "full_name_th": "รศ.ดร. ปิติ ศรีแสงนาม",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_nakavachara_032",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Woraprapa",
        "last_name": "Nakavachara",
        "full_name": "Woraprapa Nakavachara",
        "full_name_th": "ผศ.ดร. วรประภา นาควัชระ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_komolpaisarn_033",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Touchanun",
        "last_name": "Komolpaisarn",
        "full_name": "Touchanun Komolpaisarn",
        "full_name_th": "รศ.ดร. ธัชนันท์ โกมลไพศาล",
        "role": "อาจารย์ประจำ",
        "email": "touchanun.k@chula.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_damrongrittikul_034",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Taya",
        "last_name": "Damrongrittikul",
        "full_name": "Taya Damrongrittikul",
        "full_name_th": "ผศ.ดร. ทยา ดำรงฤทธิกุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_thongrak_035",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Suthanya",
        "last_name": "Thongrak",
        "full_name": "Suthanya Thongrak",
        "full_name_th": "รศ.ดร. สุธัญญา ทองรักษ์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_osathanunkul_036",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Rossarin",
        "last_name": "Osathanunkul",
        "full_name": "Rossarin Osathanunkul",
        "full_name_th": "ผศ.ดร. รสริน โอสถานันต์กุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_koedruang_037",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Pattha",
        "last_name": "Koedruang",
        "full_name": "Pattha Koedruang",
        "full_name_th": "ผศ.ดร. ภัททา เกิดเรือง",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_jithitikulchai_038",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Teepakorn",
        "last_name": "Jithitikulchai",
        "full_name": "Teepakorn Jithitikulchai",
        "full_name_th": "รศ.ดร. ทีปกร จิร์ฐิติกุลชัย",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_charoenporn_039",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Peera",
        "last_name": "Charoenporn",
        "full_name": "Peera Charoenporn",
        "full_name_th": "รศ.ดร. พีระ เจริญพร",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_thanasomboonyag_040",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Alongkorn",
        "last_name": "Thanasomboonyagul",
        "full_name": "Alongkorn Thanasomboonyagul",
        "full_name_th": "ผศ.ดร. อลงกรณ์ ธนศรีธัญญากุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_poapongsakorn_041",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Nipon",
        "last_name": "Poapongsakorn",
        "full_name": "Nipon Poapongsakorn",
        "full_name_th": "รศ.ดร. นิพนธ์ พัวพงศกร",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปริญญาเอกด้านเศรษฐศาสตร์ University of Hawaii",
            "ปริญญาโท"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_vidyarkornruang_042",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Sarut",
        "last_name": "Vidyarkornruangsri",
        "full_name": "Sarut Vidyarkornruangsri",
        "full_name_th": "ดร. ศรุต วิทยารุ่งเรืองศรี",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_ruangnarrab_043",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Chutisor",
        "last_name": "Ruangnarrab",
        "full_name": "Chutisor Ruangnarrab",
        "full_name_th": "ผศ.ดร. ชุติสร เรืองนาราบ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_wongcharoen_044",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Phetcharin",
        "last_name": "Wongcharoen",
        "full_name": "Phetcharin Wongcharoen",
        "full_name_th": "ผศ. เพ็ชรธรินทร์ วงศ์เจริญ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofe_stimanont_045",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Economics",
        "faculty_th": "คณะเศรษฐศาสตร์",
        "department": "คณะเศรษฐศาสตร์",
        "department_th": "คณะเศรษฐศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Montian",
        "last_name": "Stimanont",
        "full_name": "Montian Stimanont",
        "full_name_th": "ผศ.ดร. มณเฑียร สติมานนท์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
