# -*- coding: utf-8 -*-
"""
Academic Dataset (backend/scripts/data_sources/finearts_humanities_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "silpakornu_facultyoff_chandhanaphalin_001",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty of Painting, Sculpture and Graphic Arts",
    "faculty_th": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
    "department": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
    "department_th": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Nontivathn",
    "last_name": "Chandhanaphalin",
    "full_name": "Nontivathn Chandhanaphalin",
    "full_name_th": "อ. นนทิวรรธน์ จันทนะผะลิน",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_charoenwong_002",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty of Painting, Sculpture and Graphic Arts",
    "faculty_th": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
    "department": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
    "department_th": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Surasak",
    "last_name": "Charoenwong",
    "full_name": "Surasak Charoenwong",
    "full_name_th": "รศ. สุรศักดิ์ เจริญวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_pongdum_003",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty of Painting, Sculpture and Graphic Arts",
    "faculty_th": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
    "department": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
    "department_th": "คณะจิตรกรรม ประติมากรรมและภาพพิมพ์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Prayad",
    "last_name": "Pongdum",
    "full_name": "Prayad Pongdum",
    "full_name_th": "รศ. ประหยัด พงษ์ดำ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_sinsuppan_004",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts",
    "faculty_th": "คณะวิจิตรศิลป์",
    "department": "คณะวิจิตรศิลป์",
    "department_th": "คณะวิจิตรศิลป์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Thatchatham",
    "last_name": "Sinsuppan",
    "full_name": "Thatchatham Sinsuppan",
    "full_name_th": "ผศ.ดร. ธัชธรรม ศิลป์สุพรรณ",
    "role": "อาจารย์ประจำ",
    "email": "thatchatham.s@cmu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_rupin_005",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts",
    "faculty_th": "คณะวิจิตรศิลป์",
    "department": "คณะวิจิตรศิลป์",
    "department_th": "คณะวิจิตรศิลป์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Sarawut",
    "last_name": "Rupin",
    "full_name": "Sarawut Rupin",
    "full_name_th": "อ.ดร. สราวุธ รูปิน",
    "role": "อาจารย์ประจำ",
    "email": "sarawut.r@cmu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_likhitmanont_006",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts",
    "faculty_th": "คณะวิจิตรศิลป์",
    "department": "คณะวิจิตรศิลป์",
    "department_th": "คณะวิจิตรศิลป์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Wannuchat",
    "last_name": "Likhitmanont",
    "full_name": "Wannuchat Likhitmanont",
    "full_name_th": "ผศ.ดร. วรรณุฉัตร ลิขิตมานนท์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ทัศนศิลป์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_suwanhem_007",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Sunthorn",
    "last_name": "Suwanhem",
    "full_name": "Sunthorn Suwanhem",
    "full_name_th": "รศ. สุนทร สุวรรณเหม",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ทัศนศิลป์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_sudhom_008",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Songkran",
    "last_name": "Sudhom",
    "full_name": "Songkran Sudhom",
    "full_name_th": "ผศ. สงกรานต์ สุดหอม",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ทัศนศิลป์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_panjinda_009",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Wipavee",
    "last_name": "Panjinda",
    "full_name": "Wipavee Panjinda",
    "full_name_th": "อ.ดร. วิภาวี ปานจินดา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ทัศนศิลป์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_saenyakiatkun_010",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาศิลปะไทย",
    "department_th": "ภาควิชาศิลปะไทย",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Suebsak",
    "last_name": "Saenyakiatkun",
    "full_name": "Suebsak Saenyakiatkun",
    "full_name_th": "รศ.ดร. สืบศักดิ์ แสนยาเกียรติคุณ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_wanjring_011",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Social Sciences",
    "faculty_th": "คณะสังคมศาสตร์",
    "department": "ภาควิชาศิลปะไทย",
    "department_th": "ภาควิชาศิลปะไทย",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Asawinee",
    "last_name": "Wanjring",
    "full_name": "Asawinee Wanjring",
    "full_name_th": "รศ. อัศวิณีย์ หวานจริง",
    "role": "อาจารย์ประจำ",
    "email": "asawinee.w@cmu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_kesonkesara_012",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts",
    "faculty_th": "คณะวิจิตรศิลป์",
    "department": "คณะวิจิตรศิลป์",
    "department_th": "คณะวิจิตรศิลป์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Sukree",
    "last_name": "Kesonkesara",
    "full_name": "Sukree Kesonkesara",
    "full_name_th": "รศ. สุกรี เกษรเกศรา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_chanthakhaisorn_013",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Social Sciences",
    "faculty_th": "คณะสังคมศาสตร์",
    "department": "ภาควิชาทัศนศิลป์",
    "department_th": "ภาควิชาทัศนศิลป์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Prakornpatara",
    "last_name": "Chanthakhaisorn",
    "full_name": "Prakornpatara Chanthakhaisorn",
    "full_name_th": "รศ. ปกรณ์ภัทร์ จันทะไข่สร",
    "role": "อาจารย์ประจำ",
    "email": "prakornpatara.j@cmu.ac.th",
    "image_url": "",
    "profile_url": "https://service.finearts.cmu.ac.th/PersonFAV1/ViewDetailPersonal.php?&IDDataStaff=40",
    "education": [],
    "research_interests": [
      "ศิลปะภาพพิมพ์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_chanlun_014",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty of Arts",
    "faculty_th": "คณะอักษรศาสตร์",
    "department": "คณะอักษรศาสตร์",
    "department_th": "คณะอักษรศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Chutathip",
    "last_name": "Chanlun",
    "full_name": "Chutathip Chanlun",
    "full_name_th": "รศ.ดร. จุฑาทิพย์ จันทร์ลุน",
    "role": "อาจารย์ประจำ",
    "email": "chanlun_j@su.ac.th",
    "image_url": "",
    "profile_url": "https://arts.su.ac.th/?page_id=33",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_chiravate_015",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty of Arts",
    "faculty_th": "คณะอักษรศาสตร์",
    "department": "คณะอักษรศาสตร์",
    "department_th": "คณะอักษรศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Boonjira",
    "last_name": "Chiravate",
    "full_name": "Boonjira Chiravate",
    "full_name_th": "รศ.ดร. บูลย์จีรา ชิรเวทย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_ruenpirom_016",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty of Arts",
    "faculty_th": "คณะอักษรศาสตร์",
    "department": "คณะอักษรศาสตร์",
    "department_th": "คณะอักษรศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kanapat",
    "last_name": "Ruenpirom",
    "full_name": "Kanapat Ruenpirom",
    "full_name_th": "ผศ.ดร. กณภัทร รื่นภิรมย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_sawasdee_017",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาภาษาอังกฤษ",
    "department_th": "ภาควิชาภาษาอังกฤษ",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Nithiwadee",
    "last_name": "Sawasdee",
    "full_name": "Nithiwadee Sawasdee",
    "full_name_th": "ผศ. นิธิวดี สวัสดี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_kerdkham_018",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาภาษาอังกฤษ",
    "department_th": "ภาควิชาภาษาอังกฤษ",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Chantira",
    "last_name": "Kerdkham",
    "full_name": "Chantira Kerdkham",
    "full_name_th": "อ. จันทิรา เกิดคำ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_hutanuwatr_019",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาภาษาอังกฤษ",
    "department_th": "ภาควิชาภาษาอังกฤษ",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Nachanok",
    "last_name": "Hutanuwatr",
    "full_name": "Nachanok Hutanuwatr",
    "full_name_th": "อ.ดร. ณชนก หุตนันท์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_rampanphet_020",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาภาษาอังกฤษ",
    "department_th": "ภาควิชาภาษาอังกฤษ",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Theerach",
    "last_name": "Rampanphet",
    "full_name": "Theerach Rampanphet",
    "full_name_th": "อ.ดร. ธีรัช รำแพนเพชร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_khiewvichai_021",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาภาษาอังกฤษ",
    "department_th": "ภาควิชาภาษาอังกฤษ",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Baramee",
    "last_name": "Khiewvichai",
    "full_name": "Baramee Khiewvichai",
    "full_name_th": "ผศ.ดร. บารมี เขียววิชัย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_phongphiw_022",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Humanities",
    "faculty_th": "คณะมนุษยศาสตร์",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Thanyaporn",
    "last_name": "Phongphiw",
    "full_name": "Thanyaporn Phongphiw",
    "full_name_th": "ผศ.ดร. ธัญญาภรณ์ ผ่องผิว",
    "role": "อาจารย์ประจำ",
    "email": "tanyapon.p@cmu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_rattanawong_023",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Humanities",
    "faculty_th": "คณะมนุษยศาสตร์",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Pongsak",
    "last_name": "Rattanawong",
    "full_name": "Pongsak Rattanawong",
    "full_name_th": "ผศ. พงษ์ศักดิ์ รัตนวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_tainta_024",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "สาขาวิชาภาษาญี่ปุ่น ภาควิชาภาษาตะวันออก",
    "department_th": "สาขาวิชาภาษาญี่ปุ่น ภาควิชาภาษาตะวันออก",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Phuwat",
    "last_name": "Tainta",
    "full_name": "Phuwat Tainta",
    "full_name_th": "อ.ดร. ภูวัตร ทาอินต๊ะ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_techacharoenrun_025",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Humanities",
    "faculty_th": "คณะมนุษยศาสตร์",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Suparak",
    "last_name": "Techacharoenrungrueang",
    "full_name": "Suparak Techacharoenrungrueang",
    "full_name_th": "ผศ.ดร. ศุภรักษ์ เตชะเจริญรุ่งเรือง",
    "role": "อาจารย์ประจำ",
    "email": "suparak.t@cmu.ac.th",
    "image_url": "",
    "profile_url": "https://www.cmu.ac.th/th/faculty/humanities/teacher/db5d90f4-2c56-4af1-9237-cb57411131ca",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_chansong_026",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Humanities",
    "faculty_th": "คณะมนุษยศาสตร์",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Rawee",
    "last_name": "Chansong",
    "full_name": "Rawee Chansong",
    "full_name_th": "ผศ.ดร. ระวี จันทร์ส่อง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_chumsai_027",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Humanities",
    "faculty_th": "คณะมนุษยศาสตร์",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Tui",
    "last_name": "Chumsai",
    "full_name": "Tui Chumsai",
    "full_name_th": "ศ.ดร. หม่อมหลวงตุ้ย ชุมสาย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_rattakanok_028",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Humanities",
    "faculty_th": "คณะมนุษยศาสตร์",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Thin",
    "last_name": "Rattakanok",
    "full_name": "Thin Rattakanok",
    "full_name_th": "อ. ถิ่น รัติกนก",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_pattiya_029",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Humanities",
    "faculty_th": "คณะมนุษยศาสตร์",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Arkom",
    "last_name": "Pattiya",
    "full_name": "Arkom Pattiya",
    "full_name_th": "ศ. พันตรีอาคม พัฒิยะ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_channgam_030",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Humanities",
    "faculty_th": "คณะมนุษยศาสตร์",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Saeng",
    "last_name": "Channgam",
    "full_name": "Saeng Channgam",
    "full_name_th": "ศ. แสง จันทร์งาม",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_santasombat_031",
    "university": "Silpakorn University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยศิลปากร และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Fine Arts, Humanities & Social Sciences",
    "faculty_th": "คณะจิตรกรรม, คณะวิจิตรศิลป์, คณะอักษรศาสตร์, คณะมนุษยศาสตร์ และ คณะสังคมศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Yos",
    "last_name": "Santasombat",
    "full_name": "Yos Santasombat",
    "full_name_th": "ศ. เกียรติคุณ ดร.ยศ สันตสมบัติ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ความหลากหลายทางชีวภาพ",
      "ป่าชุมชน",
      "ภูมิปัญญาท้องถิ่นกับการพัฒนาอย่างยั่งยืน",
      "การบริหารจัดการทรัพยากรธรรมชาติ"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_kongthweesak_032",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Social Sciences",
    "faculty_th": "คณะสังคมศาสตร์",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา คณะสังคมศาสตร์",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา คณะสังคมศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pairote",
    "last_name": "Kongthweesak",
    "full_name": "Pairote Kongthweesak",
    "full_name_th": "รศ.ดร. ไพโรจน์ คงทวีศักดิ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_panyagaew_033",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Social Sciences",
    "faculty_th": "คณะสังคมศาสตร์",
    "department": "คณะสังคมศาสตร์",
    "department_th": "คณะสังคมศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Wasan",
    "last_name": "Panyagaew",
    "full_name": "Wasan Panyagaew",
    "full_name_th": "รศ.ดร. วสันต์ ปัญญาแก้ว",
    "role": "อาจารย์ประจำ",
    "email": "wasan.p@cmu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_katumanee_034",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Social Sciences",
    "faculty_th": "คณะสังคมศาสตร์",
    "department": "คณะสังคมศาสตร์",
    "department_th": "คณะสังคมศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Teerapong",
    "last_name": "Katumanee",
    "full_name": "Teerapong Katumanee",
    "full_name_th": "อ.ดร. ธีรพงศ์ เกตุมณี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "Ph.D. (Sociology and Anthropology), Chiang Mai University, Thailand, 2023"
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "silpakornu_facultyoff_ivanova_035",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Social Sciences",
    "faculty_th": "คณะสังคมศาสตร์",
    "department": "ภาควิชาสังคมศาสตร์กับการพัฒนา",
    "department_th": "ภาควิชาสังคมศาสตร์กับการพัฒนา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Maranatha",
    "last_name": "Ivanova",
    "full_name": "Maranatha Ivanova",
    "full_name_th": "อ.ดร. Maranatha Ivanova",
    "role": "อาจารย์ประจำ",
    "email": "maranatha.v@cmu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
