# -*- coding: utf-8 -*-
"""
Cleaned & Disambiguated Academic Faculty Dataset (backend/scripts/data_sources/humanities_social_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "chulalongk_facultyofc_phisitsankhatka_001",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะจิตวิทยา",
    "department_th": "คณะจิตวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Kullaya",
    "last_name": "Phisitsankhatkan",
    "full_name": "Kullaya Phisitsankhatkan",
    "full_name_th": "รศ.ดร. กุลยา พิสิษฐ์สังฆการ",
    "role": "อาจารย์ประจำ",
    "email": "kullaya.d@chula.ac.th",
    "image_url": "",
    "profile_url": "https://www.psy.chula.ac.th/th/our-people/?category=50",
    "education": [],
    "research_interests": [
      "จิตวิทยาคลินิก",
      "จิตวิทยาการปรึกษา"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_pornprasertmani_002",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะจิตวิทยา",
    "department_th": "คณะจิตวิทยา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Santhad",
    "last_name": "Pornprasertmanit",
    "full_name": "Santhad Pornprasertmanit",
    "full_name_th": "อ.ดร. สันทัด พรประเสริฐมานิต",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "จิตวิทยาปริชาน"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_kruahiran_003",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะจิตวิทยา",
    "department_th": "คณะจิตวิทยา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Piyakrita",
    "last_name": "Kruahiran",
    "full_name": "Piyakrita Kruahiran",
    "full_name_th": "อ.ดร. ปิยกฤตา เครือหิรัญ",
    "role": "อาจารย์ประจำ",
    "email": "piyakrita.k@chula.ac.th",
    "image_url": "",
    "profile_url": "https://www.psy.chula.ac.th/th/people/piyakrita-kruahiran/",
    "education": [],
    "research_interests": [
      "จิตวิทยาสังคม"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_tepphan_004",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะจิตวิทยา",
    "department_th": "คณะจิตวิทยา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Nattasuda",
    "last_name": "Tepphan",
    "full_name": "Nattasuda Tepphan",
    "full_name_th": "ผศ.ดร. ณัฐสุดา เต้พันธ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_chawowanich_005",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะจิตวิทยา",
    "department_th": "คณะจิตวิทยา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Jennifer",
    "last_name": "Chawowanich",
    "full_name": "Jennifer Chawowanich",
    "full_name_th": "อ.ดร. เจนนิเฟอร์ ชวโนวานิช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_jantawarint_006",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะจิตวิทยา",
    "department_th": "คณะจิตวิทยา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Supasiree",
    "last_name": "Jantawarint",
    "full_name": "Supasiree Jantawarint",
    "full_name_th": "อ.ดร. สุภสิรี จันทวรินทร์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_nimmapirat_007",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะจิตวิทยา",
    "department_th": "คณะจิตวิทยา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Pimjutha",
    "last_name": "Nimmapirat",
    "full_name": "Pimjutha Nimmapirat",
    "full_name_th": "อ.ดร. พิมพ์จุฑา นิมมาภิรัตน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_pekanandsiriwan_008",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะจิตวิทยา",
    "department_th": "คณะจิตวิทยา",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Panthip",
    "last_name": "Pekanand Siriwanaboon",
    "full_name": "Panthip Pekanand Siriwanaboon",
    "full_name_th": "รศ.ดร. พรรณทิพย์ เภกะนันทน์ ศิริวรรณบุศย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_santasombat_009",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา คณะสังคมศาสตร์",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา คณะสังคมศาสตร์",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Yos",
    "last_name": "Santasombat",
    "full_name": "Yos Santasombat",
    "full_name_th": "ศ. เกียรติคุณ ดร.ยศ สันตสมบัติ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ความหลากหลายทางชีวภาพ",
      "ป่าชุมชน",
      "ภูมิปัญญาท้องถิ่นกับการพัฒนาอย่างยั่งยืน",
      "การบริหารจัดการทรัพยากรธรรมชาติ"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_panyakaew_010",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะสังคมศาสตร์",
    "department_th": "คณะสังคมศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Wasan",
    "last_name": "Panyakaew",
    "full_name": "Wasan Panyakaew",
    "full_name_th": "รศ.ดร. วสันต์ ปัญญาแก้ว",
    "role": "อาจารย์ประจำ",
    "email": "wasan.p@cmu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_kongthweesak_011",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "ภาควิชาสังคมวิทยาและมานุษยวิทยา คณะสังคมศาสตร์",
    "department_th": "ภาควิชาสังคมวิทยาและมานุษยวิทยา คณะสังคมศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pairote",
    "last_name": "Kongthweesak",
    "full_name": "Pairote Kongthweesak",
    "full_name_th": "รศ.ดร. ไพโรจน์ คงทวีศักดิ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_ivanova_012",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "ภาควิชาสังคมศาสตร์กับการพัฒนา",
    "department_th": "ภาควิชาสังคมศาสตร์กับการพัฒนา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Maranatha",
    "last_name": "Ivanova",
    "full_name": "Maranatha Ivanova",
    "full_name_th": "อ.ดร. Maranatha Ivanova",
    "role": "อาจารย์ประจำ",
    "email": "maranatha.v@cmu.ac.th",
    "image_url": "",
    "profile_url": "https://mayakovskaya.academia.edu/",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_ketmanee_013",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะสังคมศาสตร์",
    "department_th": "คณะสังคมศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Teerapong",
    "last_name": "Ketmanee",
    "full_name": "Teerapong Ketmanee",
    "full_name_th": "อ.ดร. ธีรพงศ์ เกตุมณี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "Ph.D. (Sociology and Anthropology), Chiang Mai University, Thailand, 2023"
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_ongkrutaraksa_014",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "ภาควิชาการประชาสัมพันธ์",
    "department_th": "ภาควิชาการประชาสัมพันธ์",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Worawan",
    "last_name": "Ongkrutaraksa",
    "full_name": "Worawan Ongkrutaraksa",
    "full_name_th": "ศ.ดร. วรวรรณ องค์ครุฑรักษา",
    "role": "อาจารย์ประจำ",
    "email": "worawan.o@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "การโฆษณา"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_chansatitporn_015",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "ภาควิชาวาทวิทยาและสื่อสารการแสดง",
    "department_th": "ภาควิชาวาทวิทยาและสื่อสารการแสดง",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Praputsorn",
    "last_name": "Chansatitporn",
    "full_name": "Praputsorn Chansatitporn",
    "full_name_th": "ผศ.ดร. ประภัสสร จันทร์สถิตย์พร",
    "role": "อาจารย์ประจำ",
    "email": "praputsorn.c@chula.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_akrachantachote_016",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะนิเทศศาสตร์",
    "department_th": "คณะนิเทศศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Preeda",
    "last_name": "Akrachantachote",
    "full_name": "Preeda Akrachantachote",
    "full_name_th": "รศ.ดร. ปรีดา อัครจันทโชติ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_chongvilaikasem_017",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะวารสารศาสตร์และสื่อสารมวลชน",
    "department_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Wilaiwan",
    "last_name": "Chongvilaikasem",
    "full_name": "Wilaiwan Chongvilaikasem",
    "full_name_th": "รศ.ดร. วิไลวรรณ จงวิไลเกษม",
    "role": "อาจารย์ประจำ",
    "email": "boomda68@tu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "วิทยุโทรทัศน์และสื่อดิจิทัล"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_hinwiman_018",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะวารสารศาสตร์และสื่อสารมวลชน",
    "department_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Somsuk",
    "last_name": "Hinwiman",
    "full_name": "Somsuk Hinwiman",
    "full_name_th": "รศ.ดร. สมสุข หินวิมาน",
    "role": "อาจารย์ประจำ",
    "email": "acfb2@hotmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_panahiranuwong_019",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะวารสารศาสตร์และสื่อสารมวลชน",
    "department_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Atchara",
    "last_name": "Panahiranuwong",
    "full_name": "Atchara Panahiranuwong",
    "full_name_th": "ผศ.ดร. อัจฉรา ปัณฑรานุวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "padchara@tu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_ronnavech_020",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะวารสารศาสตร์และสื่อสารมวลชน",
    "department_th": "คณะวารสารศาสตร์และสื่อสารมวลชน",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Monaiphol",
    "last_name": "Ronnavech",
    "full_name": "Monaiphol Ronnavech",
    "full_name_th": "ผศ.ดร. โมไนยพล รณเวช",
    "role": "อาจารย์ประจำ",
    "email": "monaiphol2026@gmail.com",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_phongphiw_021",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Tanyapon",
    "last_name": "Phongphiw",
    "full_name": "Tanyapon Phongphiw",
    "full_name_th": "ผศ.ดร. ธัญญาภรณ์ ผ่องผิว",
    "role": "อาจารย์ประจำ",
    "email": "tanyapon.p@cmu.ac.th",
    "image_url": "",
    "profile_url": "https://www.cmu.ac.th/th/faculty/humanities/teacher",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_rattanawong_022",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Pongsak",
    "last_name": "Rattanawong",
    "full_name": "Pongsak Rattanawong",
    "full_name_th": "ผศ. พงษ์ศักดิ์ รัตนวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.cmu.ac.th/th/faculty/humanities/teacher",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_techacharoenrun_023",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Suparak",
    "last_name": "Techacharoenrungrueang",
    "full_name": "Suparak Techacharoenrungrueang",
    "full_name_th": "ผศ.ดร. ศุภรักษ์ เตชะเจริญรุ่งเรือง",
    "role": "อาจารย์ประจำ",
    "email": "suparak.t@cmu.ac.th",
    "image_url": "",
    "profile_url": "https://www.cmu.ac.th/th/faculty/humanities/teacher/db5d90f4-2c56-4af1-9237-cb57411131ca",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_thainta_024",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "ภาควิชาภาษาตะวันออก สาขาวิชาภาษาญี่ปุ่น คณะมนุษยศาสตร์",
    "department_th": "ภาควิชาภาษาตะวันออก สาขาวิชาภาษาญี่ปุ่น คณะมนุษยศาสตร์",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Phuwat",
    "last_name": "Thainta",
    "full_name": "Phuwat Thainta",
    "full_name_th": "อ.ดร. ภูวัตร ทาอินต๊ะ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ภาษาญี่ปุ่น"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_nanthasri_025",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Chaiwat",
    "last_name": "Nanthasri",
    "full_name": "Chaiwat Nanthasri",
    "full_name_th": "ผศ.ดร. ชัยวัฒน์ นันทศรี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.human.cmu.ac.th/",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_promyiam_026",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Korawan",
    "last_name": "Promyiam",
    "full_name": "Korawan Promyiam",
    "full_name_th": "ผศ.ดร. กรวรรณ พรหมแย้ม",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.human.cmu.ac.th/",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_chansong_027",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Rawee",
    "last_name": "Chansong",
    "full_name": "Rawee Chansong",
    "full_name_th": "ผศ.ดร. ระวี จันทร์ส่อง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_chumsai_028",
    "university": "Chulalongkorn University",
    "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "M.L. Tui",
    "last_name": "Chumsai",
    "full_name": "M.L. Tui Chumsai",
    "full_name_th": "ศ.ดร. หม่อมหลวงตุ้ย ชุมสาย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.human.cmu.ac.th/history",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "chulalongk_facultyofc_suwannarat_029",
    "university": "Chiang Mai University",
    "university_th": "มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Psychology",
    "faculty_th": "คณะจิตวิทยา",
    "department": "คณะมนุษยศาสตร์",
    "department_th": "คณะมนุษยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Junyawan",
    "last_name": "Suwannarat",
    "full_name": "Junyawan Suwannarat",
    "full_name_th": "ผศ.ดร. จรรยวรรณ สุวรรณรัตน์",
    "role": "อาจารย์ประจำ",
    "email": "junyawan.suwannarat@cmu.ac.th",
    "image_url": "",
    "profile_url": "https://so03.tci-thaijo.org/index.php/JHUMANS/about/contact",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
