# KMITL & KMUTT Official Curricula Dataset

KMITL_KMUTT_COURSES = [
    # =========================================================================
    # KMITL (King Mongkut's Institute of Technology Ladkrabang - สจล.)
    # =========================================================================
    # --- School of Engineering (KMITL) ---
    {
        "id": "kmitl_eng_beng_robotics_ai",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมหุ่นยนต์และปัญญาประดิษฐ์ (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Engineering Program in Robotics and Artificial Intelligence Engineering (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมหุ่นยนต์และปัญญาประดิษฐ์)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Robotics and AI",
        "department_th": "ภาควิชาวิศวกรรมหุ่นยนต์และปัญญาประดิษฐ์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "135 หน่วยกิต",
        "tuition_per_semester": "75,000 บาท",
        "tuition_total": "600,000 บาท",
        "description": "หลักสูตรวิศวกรรมหุ่นยนต์และ AI นานาชาติชั้นนำ เน้นการออกแบบหุ่นยนต์อัจฉริยะ การควบคุมอัตโนมัติ คอมพิวเตอร์วิทัศน์ และระบบอัตโนมัติในอุตสาหกรรมยุค 4.0",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษ 100% กับผู้เชี่ยวชาญระดับโลก", "ห้องปฏิบัติการหุ่นยนต์และ AI ที่ทันสมัยระดับสากล (KMITL Robotics Lab)", "โอกาสทำ Dual Degree ร่วมกับมหาวิทยาลัยชั้นนำในสหรัฐฯ และยุโรป"],
        "career_paths": ["Robotics and Automation Engineer", "AI & Computer Vision Engineer", "Embedded Systems Developer", "R&D Robotics Specialist"],
        "tags": ["Robotics", "Artificial Intelligence", "AI", "Engineering", "International Program"],
        "website_url": "https://curriculum.kmitl.ac.th/engineering"
    },
    {
        "id": "kmitl_eng_beng_software",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมซอฟต์แวร์ (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Engineering Program in Software Engineering (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมซอฟต์แวร์)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Computer Engineering",
        "department_th": "ภาควิชาวิศวกรรมคอมพิวเตอร์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "75,000 บาท",
        "tuition_total": "600,000 บาท",
        "description": "เน้นการพัฒนาซอฟต์แวร์ขนาดใหญ่ สถาปัตยกรรมคลาวด์เนทีฟ ความมั่นคงปลอดภัยไซเบอร์ และ DevOps ด้วยมาตรฐานวิศวกรรมระดับโลก",
        "curriculum_highlights": ["สถาปัตยกรรม Microservices, Cloud Computing และ CI/CD", "การฝึกงานและสหกิจศึกษากับบริษัทยักษ์ใหญ่ด้าน Tech ทั้งในและต่างประเทศ", "หลักสูตรที่ได้รับการรับรองมาตรฐานสากล ABET"],
        "career_paths": ["Software Engineer / Full-Stack Architect", "DevOps / Cloud Engineer", "Mobile & Web Architect", "Tech Entrepreneur"],
        "tags": ["Software Engineering", "Cloud", "DevOps", "International Program", "KMITL"],
        "website_url": "https://curriculum.kmitl.ac.th/engineering"
    },
    {
        "id": "kmitl_eng_beng_biomedical",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมชีวการแพทย์ (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Engineering Program in Biomedical Engineering (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมชีวการแพทย์)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Biomedical Engineering",
        "department_th": "ภาควิชาวิศวกรรมชีวการแพทย์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "135 หน่วยกิต",
        "tuition_per_semester": "75,000 บาท",
        "tuition_total": "600,000 บาท",
        "description": "ผสานวิศวกรรมศาสตร์เข้ากับการแพทย์ ออกแบบเครื่องมือแพทย์ อุปกรณ์ฝังในร่างกาย อวัยวะเทียม และการประมวลผลสัญญาณชีวการแพทย์",
        "curriculum_highlights": ["การออกแบบและพัฒนาอุปกรณ์การแพทย์อัจฉริยะ (Smart Medical Devices)", "การประมวลผลภาพถ่ายทางการแพทย์ด้วย AI (Medical Image Processing)", "การฝึกปฏิบัติงานจริงในโรงพยาบาลและโรงงานผลิตเครื่องมือแพทย์"],
        "career_paths": ["วิศวกรชีวการแพทย์และผู้เชี่ยวชาญเครื่องมือแพทย์", "นักวิจัยและพัฒนาอุปกรณ์การแพทย์ R&D", "วิศวกรคลินิกประจำโรงพยาบาล"],
        "tags": ["Biomedical Engineering", "Medical Devices", "AI in Medicine", "Healthcare Tech"],
        "website_url": "https://bme.kmitl.ac.th"
    },
    {
        "id": "kmitl_eng_beng_civil",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมโยธา",
        "title_en": "Bachelor of Engineering Program in Civil Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมโยธา)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Civil Engineering",
        "department_th": "ภาควิชาวิศวกรรมโยธา",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "เน้นการออกแบบและควบคุมงานก่อสร้างโครงสร้างพื้นฐานขนาดใหญ่ ทางด่วน รถไฟฟ้า สะพาน และการประยุกต์ใช้เทคโนโลยีการก่อสร้างสมัยใหม่",
        "curriculum_highlights": ["การออกแบบโครงสร้างอาคารสูงและสะพานขนาดใหญ่", "เทคโนโลยี BIM และการจำลองดิจิทัลในการก่อสร้าง", "การทดสอบวัสดุและปฐพีกลศาสตร์ขั้นสูง"],
        "career_paths": ["วิศวกรโยธาและวิศวกรโครงสร้าง", "ผู้จัดการโครงการก่อสร้าง (Project Manager)", "วิศวกรที่ปรึกษาโครงสร้างพื้นฐาน"],
        "tags": ["Civil Engineering", "Structural Engineering", "Construction", "BIM"],
        "website_url": "https://civil.kmitl.ac.th"
    },
    {
        "id": "kmitl_eng_msc_electrical",
        "title_th": "หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมไฟฟ้า (หลักสูตรนานาชาติ)",
        "title_en": "Master of Engineering Program in Electrical Engineering (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วศ.ม. (วิศวกรรมไฟฟ้า)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Electrical Engineering",
        "department_th": "ภาควิชาวิศวกรรมไฟฟ้า",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "180,000 บาท",
        "description": "วิจัยขั้นสูงด้านระบบโครงข่ายไฟฟ้าอัจฉริยะ (Smart Grid) อิเล็กทรอนิกส์กำลัง ยานยนต์ไฟฟ้า (EV) และพลังงานหมุนเวียน",
        "curriculum_highlights": ["ระบบโครงข่ายไฟฟ้าอัจฉริยะและการบูรณาการพลังงานแสงอาทิตย์/ลม", "ระบบขับเคลื่อนยานยนต์ไฟฟ้าและสถานีชาร์จพลังงานสูง", "การควบคุมระบบไฟฟ้ากำลังด้วย AI"],
        "career_paths": ["วิศวกรไฟฟ้าอาวุโสและที่ปรึกษาพลังงาน", "นักวิจัยด้าน Smart Grid และ EV", "อาจารย์มหาวิทยาลัย"],
        "tags": ["Electrical Engineering", "Smart Grid", "Power Electronics", "Renewable Energy"],
        "website_url": "https://ee.kmitl.ac.th"
    },
    {
        "id": "kmitl_eng_phd_computer",
        "title_th": "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์ (หลักสูตรนานาชาติ)",
        "title_en": "Doctor of Philosophy Program in Computer Engineering (International Program)",
        "degree_level": "ปริญญาเอก",
        "degree_name": "ปร.ด. (วิศวกรรมคอมพิวเตอร์)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Computer Engineering",
        "department_th": "ภาควิชาวิศวกรรมคอมพิวเตอร์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "3 ปี",
        "total_credits": "48 หน่วยกิต",
        "tuition_per_semester": "50,000 บาท",
        "tuition_total": "300,000 บาท",
        "description": "สร้างดุษฎีบัณฑิตนักวิจัยระดับโลกด้าน AI, Deep Learning, Quantum Computing, Cyber-Physical Systems และสถาปัตยกรรมคอมพิวเตอร์ขั้นสูง",
        "curriculum_highlights": ["การวิจัย AI ขั้นสูงและการคำนวณสมรรถนะสูง (High-Performance Computing)", "ความปลอดภัยทางไซเบอร์และการเข้ารหัสลับยุคควอนตัม", "การตีพิมพ์ในวารสารชั้นนำ IEEE/ACM Transactions"],
        "career_paths": ["นักวิจัยคอมพิวเตอร์ระดับสากล", "หัวหน้านักวิทยาศาสตร์ AI (Chief AI Scientist)", "อาจารย์ประจำมหาวิทยาลัย"],
        "tags": ["Computer Engineering", "Artificial Intelligence", "Quantum Computing", "Ph.D."],
        "website_url": "https://ce.kmitl.ac.th"
    },
    # --- School of Architecture, Art, and Design (KMITL) ---
    {
        "id": "kmitl_arch_barch",
        "title_th": "หลักสูตรสถาปัตยกรรมศาสตรบัณฑิต สาขาวิชาสถาปัตยกรรมหลัก",
        "title_en": "Bachelor of Architecture Program in Architecture",
        "degree_level": "ปริญญาตรี",
        "degree_name": "สถ.บ. (สถาปัตยกรรม)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Architecture, Art, and Design",
        "faculty_th": "คณะสถาปัตยกรรม ศิลปะและการออกแบบ",
        "department": "Department of Architecture",
        "department_th": "ภาควิชาสถาปัตยกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "5 ปี",
        "total_credits": "165 หน่วยกิต",
        "tuition_per_semester": "25,000 บาท",
        "tuition_total": "250,000 บาท",
        "description": "สร้างสถาปนิกที่มีความคิดสร้างสรรค์ ทักษะการออกแบบสถาปัตยกรรมที่ยั่งยืน การใช้เทคโนโลยีดิจิทัล และการบริหารงานก่อสร้าง",
        "curriculum_highlights": ["สตูดิโอการออกแบบสถาปัตยกรรมที่เข้มข้นทุกภาคการศึกษา", "การออกแบบอาคารประหยัดพลังงานและอาคารเขียว (Green Building)", "การประยุกต์ใช้ Computational Design และ Generative Architecture"],
        "career_paths": ["สถาปนิกวิชาชีพ (ใบประกอบวิชาชีพสถาปัตยกรรมควบคุม)", "สถาปนิกออกแบบอาคารเขียวและยั่งยืน", "ผู้บริหารงานออกแบบและพัฒนาอสังหาริมทรัพย์"],
        "tags": ["Architecture", "Design", "Green Building", "Sustainable Architecture"],
        "website_url": "https://aad.kmitl.ac.th"
    },
    # --- School of Science (KMITL) ---
    {
        "id": "kmitl_sci_bsc_applied_stat",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาสถิติประยุกต์และการวิเคราะห์ข้อมูล",
        "title_en": "Bachelor of Science Program in Applied Statistics and Data Analytics",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (สถิติประยุกต์)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Science",
        "faculty_th": "คณะวิทยาศาสตร์",
        "department": "Department of Mathematics and Computer Science",
        "department_th": "ภาควิชาคณิตศาสตร์และสถิติ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "19,000 บาท",
        "tuition_total": "152,000 บาท",
        "description": "เน้นการวิเคราะห์ข้อมูลขั้นสูง สถิติประกันภัย การทำเหมืองข้อมูล และการประยุกต์ใช้ Machine Learning สำหรับธุรกิจและการเงิน",
        "curriculum_highlights": ["สถิติศาสตร์สำหรับการเงินและประกันภัย (Actuarial Science)", "การเขียนโปรแกรม Python/R สำหรับวิเคราะห์ข้อมูลขนาดใหญ่", "โครงงานวิทยาศาสตร์ข้อมูลร่วมกับองค์กรธุรกิจจริง"],
        "career_paths": ["Data Analyst", "Data Scientist", "นักสถิติประกันภัย (Actuary)", "Risk Analyst"],
        "tags": ["Statistics", "Data Analytics", "Actuarial Science", "Machine Learning"],
        "website_url": "https://sci.kmitl.ac.th"
    },
    # --- School of Food Industry (KMITL) ---
    {
        "id": "kmitl_food_bsc_culinary_sci",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์การประกอบอาหารและการจัดการนวัตกรรมอาหาร",
        "title_en": "Bachelor of Science Program in Culinary Science and Food Innovation Management",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาศาสตร์การประกอบอาหาร)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Food Industry",
        "faculty_th": "คณะอุตสาหกรรมอาหาร",
        "department": "Department of Culinary Science",
        "department_th": "สาขาวิชาวิทยาศาสตร์การประกอบอาหาร",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "224,000 บาท",
        "description": "ผสานศิลปะการประกอบอาหาร (Culinary Arts) เข้ากับวิทยาศาสตร์อาหารและเทคโนโลยีแปรรูปเพื่อสร้างสรรค์นวัตกรรมอาหารแห่งอนาคต",
        "curriculum_highlights": ["ห้องปฏิบัติการครัวมาตรฐานระดับสากลและ Food Lab ขั้นสูง", "การออกแบบเมนูและการวิจัยอาหารฟังก์ชัน (Functional Food)", "การเป็นผู้ประกอบการธุรกิจอาหารและภัตตาคาร"],
        "career_paths": ["เชฟวิจัยและพัฒนาอาหาร (Research Chef)", "นักพัฒนาผลิตภัณฑ์อาหารนวัตกรรม", "ผู้ประกอบการร้านอาหารและแฟรนไชส์"],
        "tags": ["Culinary Science", "Food Innovation", "Chef", "Food Industry"],
        "website_url": "https://food.kmitl.ac.th"
    },

    # =========================================================================
    # KMUTT (King Mongkut's University of Technology Thonburi - มจธ. บางมด)
    # =========================================================================
    # --- Institute of Field Robotics (FIBO - KMUTT) ---
    {
        "id": "kmutt_fibo_beng_robotics",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมหุ่นยนต์และระบบอัตโนมัติ (FIBO)",
        "title_en": "Bachelor of Engineering Program in Robotics and Automation Systems (FIBO)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมหุ่นยนต์และระบบอัตโนมัติ)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "Institute of Field Robotics (FIBO)",
        "faculty_th": "สถาบันวิทยาการหุ่นยนต์ภาคสนาม (ฟีโบ้)",
        "department": "Department of Robotics Engineering",
        "department_th": "สาขาวิชาวิศวกรรมหุ่นยนต์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "32,000 บาท",
        "tuition_total": "256,000 บาท",
        "description": "สถาบันหุ่นยนต์แห่งแรกของประเทศไทย เน้นการเรียนรู้แบบ Project-Based Learning สร้างหุ่นยนต์บริการ หุ่นยนต์การแพทย์ และระบบอัตโนมัติในโรงงาน",
        "curriculum_highlights": ["การสร้างหุ่นยนต์จริงตั้งแต่ปี 1 (Learning by Doing)", "การออกแบบกลไก การควบคุม วงจรอิเล็กทรอนิกส์ และ AI ครบวงจร", "ความร่วมมือกับภาคอุตสาหกรรมหุ่นยนต์ระดับแนวหน้า"],
        "career_paths": ["Robotics Engineer", "Automation and Control Engineer", "AI/System Integrator", "R&D Robotics Specialist"],
        "tags": ["Robotics", "FIBO", "Automation", "AI", "KMUTT"],
        "website_url": "https://fibo.kmutt.ac.th"
    },
    {
        "id": "kmutt_fibo_msc_robotics",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาการหุ่นยนต์และระบบอัตโนมัติ (หลักสูตรนานาชาติ)",
        "title_en": "Master of Science Program in Robotics and Automation (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (วิทยาการหุ่นยนต์และระบบอัตโนมัติ)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "Institute of Field Robotics (FIBO)",
        "faculty_th": "สถาบันวิทยาการหุ่นยนต์ภาคสนาม (ฟีโบ้)",
        "department": "Department of Robotics Engineering",
        "department_th": "สาขาวิชาวิทยาการหุ่นยนต์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "50,000 บาท",
        "tuition_total": "200,000 บาท",
        "description": "การวิจัยขั้นสูงด้านหุ่นยนต์ฮิวมานอยด์ หุ่นยนต์ผ่าตัด ระบบการมองเห็นสามมิติ และอัลกอริทึมการเคลื่อนที่แบบอัตโนมัติ (SLAM / Navigation)",
        "curriculum_highlights": ["การวิจัยหุ่นยนต์ทางการแพทย์และบริการระดับลึก", "การพัฒนาระบบนำทางและแผนที่อัตโนมัติ (Autonomous Navigation)", "ผลงานวิจัยและสิทธิบัตรทางหุ่นยนต์ร่วมกับภาคอุตสาหกรรม"],
        "career_paths": ["Senior Robotics Researcher", "Autonomous Systems Architect", "อาจารย์และนักวิจัยหุ่นยนต์"],
        "tags": ["Robotics", "FIBO", "Autonomous Systems", "Medical Robotics", "Master"],
        "website_url": "https://fibo.kmutt.ac.th"
    },
    # --- School of Information Technology (SIT - KMUTT) ---
    {
        "id": "kmutt_sit_bsc_it",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีสารสนเทศ (SIT)",
        "title_en": "Bachelor of Science Program in Information Technology (SIT)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคโนโลยีสารสนเทศ)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "School of Information Technology (SIT)",
        "faculty_th": "คณะเทคโนโลยีสารสนเทศ (SIT)",
        "department": "Department of Information Technology",
        "department_th": "สาขาวิชาเทคโนโลยีสารสนเทศ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "34,000 บาท",
        "tuition_total": "272,000 บาท",
        "description": "คณะไอทีชั้นนำของประเทศ มุ่งเน้นการพัฒนา Full-Stack Software, Data Analytics, Cybersecurity และ Cloud Computing สำหรับองค์กรยุคใหม่",
        "curriculum_highlights": ["หลักสูตรเข้มข้นตรงตามความต้องการของตลาด Tech", "โครงการประกวดนวัตกรรมซอฟต์แวร์และการฝึกงานสหกิจศึกษาชั้นนำ", "ศิษย์เก่าดำรงตำแหน่งผู้นำในบริษัท Tech ชั้นนำทั่วโลก"],
        "career_paths": ["Full-Stack Software Developer", "Systems Analyst / Solutions Architect", "Cybersecurity Specialist", "IT Consultant"],
        "tags": ["Information Technology", "SIT", "Software Development", "Cloud", "KMUTT"],
        "website_url": "https://sit.kmutt.ac.th"
    },
    {
        "id": "kmutt_sit_bsc_dsba",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการข้อมูลและการวิเคราะห์ธุรกิจ (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Science Program in Data Science and Business Analytics (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาการข้อมูลและการวิเคราะห์ธุรกิจ)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "School of Information Technology (SIT)",
        "faculty_th": "คณะเทคโนโลยีสารสนเทศ (SIT)",
        "department": "Department of Data Science",
        "department_th": "สาขาวิชาวิทยาการข้อมูล",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "60,000 บาท",
        "tuition_total": "480,000 บาท",
        "description": "ผสาน Data Science, AI, Business Intelligence และกลยุทธ์ธุรกิจ เพื่อสร้างนักวิทยาศาสตร์ข้อมูลที่เข้าใจโมเดลธุรกิจและแก้ปัญหาจริงได้",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษและการใช้ Data Platform ระดับ Enterprise", "การวิเคราะห์ Big Data และการสร้างโมเดล Machine Learning เชิงพาณิชย์", "ความร่วมมือกับพันธมิตรระดับโลก เช่น AWS, Microsoft, Google"],
        "career_paths": ["Data Scientist", "Business Intelligence Specialist", "Data Engineer", "Machine Learning Specialist"],
        "tags": ["Data Science", "Business Analytics", "Big Data", "Machine Learning", "SIT"],
        "website_url": "https://sit.kmutt.ac.th"
    },
    {
        "id": "kmutt_sit_msc_ai",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาปัญญาประดิษฐ์ประยุกต์และวิทยาการข้อมูล",
        "title_en": "Master of Science Program in Applied Artificial Intelligence and Data Science",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (ปัญญาประดิษฐ์ประยุกต์และวิทยาการข้อมูล)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "School of Information Technology (SIT)",
        "faculty_th": "คณะเทคโนโลยีสารสนเทศ (SIT)",
        "department": "Department of Artificial Intelligence",
        "department_th": "สาขาวิชาปัญญาประดิษฐ์",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "180,000 บาท",
        "description": "เน้นการวิจัยและพัฒนา AI ขั้นสูง Deep Learning, Generative AI, Large Language Models (LLMs) และการประยุกต์ใช้ในอุตสาหกรรม",
        "curriculum_highlights": ["การพัฒนาและการปรับจูนแบบจำลองภาษาขนาดใหญ่ (LLMs) และ AI Generative", "การวิเคราะห์ภาพทางการแพทย์และวิดีโอสตรีมมิ่งด้วย Computer Vision", "โครงงานวิจัยที่ได้รับการสนับสนุนจากภาคอุตสาหกรรม Tech"],
        "career_paths": ["Lead AI Engineer / Scientist", "Machine Learning Architect", "อาจารย์และนักวิจัยด้าน AI"],
        "tags": ["Artificial Intelligence", "AI", "LLM", "Deep Learning", "Data Science", "SIT"],
        "website_url": "https://sit.kmutt.ac.th"
    },
    # --- Faculty of Engineering (KMUTT) ---
    {
        "id": "kmutt_eng_beng_environmental",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมสิ่งแวดล้อม",
        "title_en": "Bachelor of Engineering Program in Environmental Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมสิ่งแวดล้อม)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Environmental Engineering",
        "department_th": "ภาควิชาวิศวกรรมสิ่งแวดล้อม",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "140 หน่วยกิต",
        "tuition_per_semester": "24,000 บาท",
        "tuition_total": "192,000 บาท",
        "description": "มุ่งเน้นการจัดการสิ่งแวดล้อมอย่างยั่งยืน การบำบัดน้ำเสียขั้นสูง การจัดการมลพิษทางอากาศ พลังงานสะอาด และ Net Zero Carbon",
        "curriculum_highlights": ["ความเป็นเลิศด้านเทคโนโลยีการจัดการของเสียและพลังงานชีวภาพ", "การประเมินวัฏจักรชีวิต (LCA) และคาร์บอนฟุตพริ้นท์", "การออกแบบโรงบำบัดน้ำเสียและระบบรีไซเคิลน้ำอุตสาหกรรม"],
        "career_paths": ["วิศวกรสิ่งแวดล้อม", "ผู้เชี่ยวชาญด้าน Net Zero และ Carbon Credit", "ที่ปรึกษาด้านการจัดการสิ่งแวดล้อมและ ESG"],
        "tags": ["Environmental Engineering", "Net Zero", "Water Treatment", "Sustainability", "KMUTT"],
        "website_url": "https://env.eng.kmutt.ac.th"
    },
    {
        "id": "kmutt_eng_phd_energy_tech",
        "title_th": "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาเทคโนโลยีพลังงาน (หลักสูตรนานาชาติ)",
        "title_en": "Doctor of Philosophy Program in Energy Technology (International Program)",
        "degree_level": "ปริญญาเอก",
        "degree_name": "ปร.ด. (เทคโนโลยีพลังงาน)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "School of Energy, Environment and Materials (JGSEE / SEEM)",
        "faculty_th": "บัณฑิตวิทยาลัยร่วมด้านพลังงานและสิ่งแวดล้อม (JGSEE)",
        "department": "Division of Energy Technology",
        "department_th": "สายวิชาเทคโนโลยีพลังงาน",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "3 ปี",
        "total_credits": "48 หน่วยกิต",
        "tuition_per_semester": "55,000 บาท",
        "tuition_total": "330,000 บาท",
        "description": "สถาบันวิจัยด้านพลังงานชั้นนำของภูมิภาคเอเชีย วิจัยเซลล์แสงอาทิตย์ พลังงานไฮโดรเจน ชีวมวล และนโยบายพลังงานและการเปลี่ยนแปลงสภาพภูมิอากาศ",
        "curriculum_highlights": ["การวิจัยร่วมกับเครือข่ายมหาวิทยาลัยระดับโลกและองค์กรพลังงานระหว่างประเทศ", "การพัฒนาเทคโนโลยีไฮโดรเจนและเซลล์เชื้อเพลิง (Fuel Cell)", "การสร้างแบบจำลองนโยบายพลังงานและการลดก๊าซเรือนกระจก"],
        "career_paths": ["นักวิจัยอาวุโสด้านพลังงานทดแทน", "ผู้เชี่ยวชาญนโยบายพลังงานระดับนานาชาติ (IEA, IRENA)", "อาจารย์มหาวิทยาลัย"],
        "tags": ["Energy Technology", "JGSEE", "Hydrogen Energy", "Solar Cell", "Ph.D."],
        "website_url": "https://jgsee.kmutt.ac.th"
    },
]
