# Complete Engineering, Science, Architecture & Tech Curricula for KMITL & KMUTT

KMITL_KMUTT_FULL_COURSES = [
    # =========================================================================
    # KMITL (สจล. ลาดกระบัง)
    # =========================================================================
    {
        "id": "kmitl_eng_beng_civil",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมโยธา",
        "title_en": "Bachelor of Engineering Program in Civil Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมโยธา)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Civil Engineering",
        "department_th": "ภาควิชาวิศวกรรมโยธา",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "เน้นวิศวกรรมโครงสร้างขนาดใหญ่ วิศวกรรมปฐพี ฐานรากสนามบินและอุโมงค์ การจัดการงานก่อสร้าง และเทคโนโลยี BIM สากล",
        "curriculum_highlights": ["ห้องปฏิบัติการทดสอบคอนกรีตและปฐพีกลศาสตร์ขนาดใหญ่", "การออกแบบโครงสร้างอาคารสูงและสะพานขึง", "การประยุกต์ใช้ BIM และโดรนสำรวจงานก่อสร้าง"],
        "career_paths": ["วิศวกรโยธาและวิศวกรโครงสร้าง", "วิศวกรควบคุมงานก่อสร้างโครงการเมกะโปรเจกต์", "วิศวกรที่ปรึกษาด้านปฐพีและโครงสร้าง"],
        "tags": ["Civil Engineering", "Structural", "Geotechnical", "BIM", "KMITL"],
        "website_url": "https://civil.kmitl.ac.th"
    },
    {
        "id": "kmitl_eng_beng_electrical",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมไฟฟ้า (ระบบไฟฟ้ากำลังและควบคุม)",
        "title_en": "Bachelor of Engineering Program in Electrical Engineering (Power and Control Systems)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมไฟฟ้า)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Electrical Engineering",
        "department_th": "ภาควิชาวิศวกรรมไฟฟ้า",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "ภาควิชาวิศวกรรมไฟฟ้าอันดับ 1 ของพระจอมเกล้าลาดกระบัง เชี่ยวชาญระบบไฟฟ้ากำลังแรงสูง สมาร์ตกริด หม้อแปลงไฟฟ้า และระบบควบคุมอัตโนมัติ",
        "curriculum_highlights": ["ห้องปฏิบัติการไฟฟ้าแรงสูง (High Voltage Lab) ชั้นนำของอาเซียน", "การจำลองระบบไฟฟ้ากำลังด้วยซอฟต์แวร์ DIgSILENT PowerFactory", "ความร่วมมือกับการไฟฟ้าฝ่ายผลิตแห่งประเทศไทย (กฟผ.), กฟภ. และ กฟน."],
        "career_paths": ["วิศวกรระบบไฟฟ้ากำลังและโรงไฟฟ้า", "วิศวกรออกแบบระบบไฟฟ้าอาคารและโรงงาน", "วิศวกรระบบพลังงานแสงอาทิตย์และ Smart Grid"],
        "tags": ["Electrical Engineering", "High Voltage", "Power Systems", "Smart Grid", "KMITL"],
        "website_url": "https://ee.kmitl.ac.th"
    },
    {
        "id": "kmitl_eng_beng_biomedical",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมชีวการแพทย์ (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Engineering Program in Biomedical Engineering (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมชีวการแพทย์)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Biomedical Engineering",
        "department_th": "ภาควิชาวิศวกรรมชีวการแพทย์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "75,000 บาท",
        "tuition_total": "600,000 บาท",
        "description": "ออกแบบและพัฒนาเครื่องมือแพทย์ อวัยวะเทียม เซนเซอร์สวมใส่ทางการแพทย์ และระบบ AI วินิจฉัยโรคเพื่อโรงพยาบาลอัจฉริยะ",
        "curriculum_highlights": ["การพัฒนาเครื่องมือแพทย์ร่วมกับคณะแพทยศาสตร์ สจล. และโรงพยาบาลชั้นนำ", "การออกแบบอุปกรณ์ฝังในร่างกาย (Implants) และอวัยวะเทียม 3D Printing", "การปฏิบัติตามมาตรฐานสากลเครื่องมือแพทย์ ISO 13485 และ FDA"],
        "career_paths": ["วิศวกรชีวการแพทย์ประจำโรงพยาบาล", "นักวิจัยและพัฒนาอุปกรณ์การแพทย์ (Medical Device R&D)", "ผู้เชี่ยวชาญผลิตภัณฑ์เครื่องมือแพทย์ระดับสากล"],
        "tags": ["Biomedical Engineering", "Medical Devices", "AI Healthcare", "KMITL"],
        "website_url": "https://bme.kmitl.ac.th"
    },
    {
        "id": "kmitl_sci_bsc_applied_physics",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาฟิสิกส์ประยุกต์และเทคโนโลยีเซมิคอนดักเตอร์",
        "title_en": "Bachelor of Science Program in Applied Physics and Semiconductor Technology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (ฟิสิกส์ประยุกต์)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Science",
        "faculty_th": "คณะวิทยาศาสตร์",
        "department": "Department of Physics",
        "department_th": "ภาควิชาฟิสิกส์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "เน้นฟิสิกส์เซมิคอนดักเตอร์ การผลิตและตรวจสอบไมโครชิป ออปโตอิเล็กทรอนิกส์ และเทคโนโลยีสุญญากาศสำหรับอุตสาหกรรมไฮเทค",
        "curriculum_highlights": ["ห้องปฏิบัติการคลีนรูมและการเคลือบฟิล์มบาง (Thin Film Deposition)", "การผลิตและวิเคราะห์คุณลักษณะของโซลาร์เซลล์และเซนเซอร์", "ความร่วมมือกับอุตสาหกรรมผลิตชิป ฮาร์ดดิสก์ และอิเล็กทรอนิกส์ (WD, Hana, Sony)"],
        "career_paths": ["Process & Semiconductor Engineer", "Thin Film & Vacuum Specialist", "Failure Analysis Engineer"],
        "tags": ["Applied Physics", "Semiconductor", "Microchip", "Cleanroom", "KMITL"],
        "website_url": "https://physics.kmitl.ac.th"
    },
    {
        "id": "kmitl_arch_barch_interior",
        "title_th": "หลักสูตรสถาปัตยกรรมศาสตรบัณฑิต สาขาวิชาสถาปัตยกรรมภายใน",
        "title_en": "Bachelor of Architecture Program in Interior Architecture",
        "degree_level": "ปริญญาตรี",
        "degree_name": "สถ.บ. (สถาปัตยกรรมภายใน)",
        "university": "King Mongkut's Institute of Technology Ladkrabang",
        "university_th": "สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
        "faculty": "School of Architecture, Art, and Design",
        "faculty_th": "คณะสถาปัตยกรรม ศิลปะและการออกแบบ",
        "department": "Department of Interior Architecture",
        "department_th": "ภาควิชาสถาปัตยกรรมภายใน",
        "program_type": "ภาคปกติ",
        "duration_years": "5 ปี",
        "total_credits": "165 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "220,000 บาท",
        "description": "เน้นการออกแบบพื้นที่ภายในอาคาร โรงแรม คอนโดมิเนียม และพื้นที่เชิงพาณิชย์ ผสานประโยชน์ใช้สอย แสงสว่าง และวัสดุก่อสร้างที่ยั่งยืน",
        "curriculum_highlights": ["สตูดิโอการออกแบบภายในเข้มข้นทุกภาคการศึกษา", "การออกแบบแสงสว่าง (Lighting Design) และการเลือกใช้วัสดุตกแต่งยุคใหม่", "การฝึกงานกับบริษัทออกแบบสถาปัตยกรรมภายในระดับแถวหน้าของประเทศ"],
        "career_paths": ["สถาปนิกภายในวิชาชีพ (Licensed Interior Architect)", "นักออกแบบพื้นที่เชิงพาณิชย์และโรงแรม (Commercial & Hospitality Designer)", "Lighting & Material Consultant"],
        "tags": ["Interior Architecture", "Interior Design", "Architecture", "KMITL"],
        "website_url": "https://arch.kmitl.ac.th"
    },

    # =========================================================================
    # KMUTT (มจธ. บางมด)
    # =========================================================================
    {
        "id": "kmutt_eng_beng_civil",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมโยธา",
        "title_en": "Bachelor of Engineering Program in Civil Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมโยธา)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Civil Engineering",
        "department_th": "ภาควิชาวิศวกรรมโยธา",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "21,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "เน้นการวิเคราะห์โครงสร้างต้านทานแรงสั่นสะเทือน คอนกรีตคาร์บอนต่ำ การจัดการระบบน้ำท่วมเมือง และวิศวกรรมขนส่งอัจฉริยะ",
        "curriculum_highlights": ["ห้องปฏิบัติการทดสอบแผ่นดินไหวและโครงสร้างขนาดใหญ่ (Shaking Table)", "การวิจัยคอนกรีตสีเขียวและวัสดุก่อสร้างคาร์บอนต่ำ", "การฝึกอบรมการบริหารโครงการด้วยโมเดลแบบจำลองสารสนเทศอาคาร (BIM)"],
        "career_paths": ["วิศวกรโยธาและวิศวกรโครงสร้าง", "วิศวกรวิเคราะห์แรงต้านแผ่นดินไหว", "ผู้จัดการโครงการก่อสร้าง (Project Manager)"],
        "tags": ["Civil Engineering", "Earthquake Engineering", "Green Concrete", "KMUTT"],
        "website_url": "https://civil.kmutt.ac.th"
    },
    {
        "id": "kmutt_eng_beng_production",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมอุตสาหการและการผลิต (Production Engineering)",
        "title_en": "Bachelor of Engineering Program in Production and Industrial Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมการผลิต)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Production Engineering",
        "department_th": "ภาควิชาวิศวกรรมการผลิต",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "21,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "เน้นการผลิตขั้นสูง (Advanced Manufacturing) แม่พิมพ์โลหะและพลาสติก ระบบอัตโนมัติในโรงงาน และการควบคุมคุณภาพเชิงสถิติ",
        "curriculum_highlights": ["โรงงานอุตสาหกรรมจำลอง (Smart Learning Factory) ภายใน มจธ.", "การใช้เครื่องจักร CNC 5 แกน เลเซอร์ตัดโลหะ และการพิมพ์ 3D โลหะ", "การฝึกงานและสหกิจศึกษากับอุตสาหกรรมยานยนต์และชิ้นส่วนอิเล็กทรอนิกส์"],
        "career_paths": ["วิศวกรการผลิต (Production Engineer)", "วิศวกรออกแบบแม่พิมพ์และกระบวนการ (Tooling & Process Engineer)", "ผู้จัดการโรงงานอัจฉริยะ"],
        "tags": ["Production Engineering", "Manufacturing", "Industry 4.0", "CNC", "KMUTT"],
        "website_url": "https://pe.kmutt.ac.th"
    },
    {
        "id": "kmutt_eng_beng_environmental",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมสิ่งแวดล้อม",
        "title_en": "Bachelor of Engineering Program in Environmental Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมสิ่งแวดล้อม)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Environmental Engineering",
        "department_th": "ภาควิชาวิศวกรรมสิ่งแวดล้อม",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "140 หน่วยกิต",
        "tuition_per_semester": "21,000 บาท",
        "tuition_total": "168,000 บาท",
        "description": "เชี่ยวชาญการบำบัดน้ำเสียอุตสาหกรรม การควบคุมมลพิษทางอากาศ การจัดการขยะมูลฝอยและของเสียอันตราย และการประเมินคาร์บอนเครดิต",
        "curriculum_highlights": ["ระบบบำบัดน้ำเสียขั้นสูงและการหมุนเวียนน้ำกลับมาใช้ใหม่ (Water Reclamation)", "การตรวจวัดมลพิษอากาศ PM2.5 และก๊าซเรือนกระจก", "การวางแผนกลยุทธ์ Decarbonization และ Circular Economy ภาคอุตสาหกรรม"],
        "career_paths": ["วิศวกรสิ่งแวดล้อม", "ที่ปรึกษาด้านการจัดการมลพิษและสิ่งแวดล้อม", "ผู้ประเมินคาร์บอนฟุตพริ้นท์และ ESG Auditor"],
        "tags": ["Environmental Engineering", "Wastewater Treatment", "Carbon Footprint", "ESG", "KMUTT"],
        "website_url": "https://env.kmutt.ac.th"
    },
    {
        "id": "kmutt_sci_bsc_microbiology",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาจุลชีววิทยาอุตสาหกรรม",
        "title_en": "Bachelor of Science Program in Industrial Microbiology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (จุลชีววิทยา)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "Faculty of Science",
        "faculty_th": "คณะวิทยาศาสตร์",
        "department": "Department of Microbiology",
        "department_th": "ภาควิชาจุลชีววิทยา",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "ประยุกต์ใช้จุลินทรีย์ในกระบวนการหมักทางอุตสาหกรรม การผลิตเอนไซม์ ยาชีวภาพ และการตรวจสอบความปลอดภัยทางจุลชีววิทยาในอาหารและยา",
        "curriculum_highlights": ["ห้องปฏิบัติการวิจัยชีววิทยาโมเลกุลและการหมักระดับถังปฏิกรณ์ชีวภาพ (Bioreactor)", "การตัดแต่งพันธุกรรมจุลินทรีย์เพื่อผลิตโปรตีนมูลค่าสูง", "การฝึกงานกับห้องแล็บตรวจวิเคราะห์เชื้อมาตรฐานสากล"],
        "career_paths": ["นักจุลชีววิทยาในอุตสาหกรรมอาหาร ยา และเครื่องสำอาง", "นักวิจัยเทคโนโลยีชีวภาพและกระบวนการหมัก", "ผู้เชี่ยวชาญควบคุมการปนเปื้อนในคลีนรูม"],
        "tags": ["Microbiology", "Fermentation", "Biotechnology", "Science", "KMUTT"],
        "website_url": "https://micro.kmutt.ac.th"
    },
    {
        "id": "kmutt_fiet_bsc_media_tech",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีมีเดีย (มีเดียทางการแพทย์และเกม)",
        "title_en": "Bachelor of Science Program in Media Technology (Medical Media and Games)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคโนโลยีมีเดีย)",
        "university": "King Mongkut's University of Technology Thonburi",
        "university_th": "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        "faculty": "School of Industrial Education and Technology (FIET)",
        "faculty_th": "คณะครุศาสตร์อุตสาหกรรมและเทคโนโลยี (FIET)",
        "department": "Department of Media Technology",
        "department_th": "สาขาวิชาเทคโนโลยีมีเดีย",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "224,000 บาท",
        "description": "ผสานเทคโนโลยีดิจิทัลเข้ากับการแพทย์และสื่อบันเทิง เชี่ยวชาญการจำลองการผ่าตัดเสมือนจริง VR/AR การพัฒนาเกม และแอนิเมชัน 3 มิติ",
        "curriculum_highlights": ["ห้องปฏิบัติการ Virtual Reality และ Motion Capture Studio มาตรฐานสากล", "การพัฒนาสื่อจำลองทางการแพทย์ 3 มิติสำหรับบุคลากรสาธารณสุข", "การพัฒนาเกมและอินเตอร์แอคทีฟมีเดียด้วย Unity และ Unreal Engine 5"],
        "career_paths": ["Medical Media & Simulation Specialist", "Game Developer & Unity/Unreal Engine Programmer", "AR/VR Interactive Designer"],
        "tags": ["Media Technology", "Medical Media", "VR/AR", "Game Development", "KMUTT FIET"],
        "website_url": "https://media.kmutt.ac.th"
    },
]
