# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/ku_agro_vet_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "kasetsartu_facultyofa_chinsirikul_001",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะอุตสาหกรรมเกษตร",
    "department_th": "คณะอุตสาหกรรมเกษตร",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Wannee",
    "last_name": "Chinsirikul",
    "full_name": "Wannee Chinsirikul",
    "full_name_th": "รศ.ดร. วรรณี จิรภาคย์กุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_chavisuk_002",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะอุตสาหกรรมเกษตร",
    "department_th": "คณะอุตสาหกรรมเกษตร",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Rawipim",
    "last_name": "Chavisuk",
    "full_name": "Rawipim Chavisuk",
    "full_name_th": "รศ.ดร. รวิพิม ฉวีสุข",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_tongkhao_003",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "ภาควิชาวิทยาศาสตร์และเทคโนโลยีการอาหาร",
    "department_th": "ภาควิชาวิทยาศาสตร์และเทคโนโลยีการอาหาร",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kullanart",
    "last_name": "Tongkhao",
    "full_name": "Kullanart Tongkhao",
    "full_name_th": "ผศ.ดร. กุลนาถ ทองขาว",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_rimkeeree_004",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "ภาควิชาพัฒนาผลิตภัณฑ์",
    "department_th": "ภาควิชาพัฒนาผลิตภัณฑ์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Hathairat",
    "last_name": "Rimkeeree",
    "full_name": "Hathairat Rimkeeree",
    "full_name_th": "รศ.ดร. หทัยรัตน์ ริมคีรี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_pharakulsuksati_005",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะอุตสาหกรรมเกษตร",
    "department_th": "คณะอุตสาหกรรมเกษตร",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Pramuk",
    "last_name": "Pharakulsuksatit",
    "full_name": "Pramuk Pharakulsuksatit",
    "full_name_th": "ผศ.ดร. ประมุข ภระกูลสุขสถิตย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_nakphaichit_006",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "ภาควิชาเทคโนโลยีชีวภาพ",
    "department_th": "ภาควิชาเทคโนโลยีชีวภาพ",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Masalin",
    "last_name": "Nakphaichit",
    "full_name": "Masalin Nakphaichit",
    "full_name_th": "รศ.ดร. มัสลิน นาคไพจิตร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_nitikornwarakul_007",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "ภาควิชาวิทยาศาสตร์และเทคโนโลยีการอาหาร",
    "department_th": "ภาควิชาวิทยาศาสตร์และเทคโนโลยีการอาหาร",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Chavachوان",
    "last_name": "Nitikornwarakul",
    "full_name": "Chavachوان Nitikornwarakul",
    "full_name_th": "ผศ.ดร. ชวขวัญ นิติกรวรากุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_tansakul_008",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Paiboon",
    "last_name": "Tansakul",
    "full_name": "Paiboon Tansakul",
    "full_name_th": "ดร. ไพบูลย์ ตั่นสกูล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_vityakiat_009",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Ulaiwan",
    "last_name": "Vityakiat",
    "full_name": "Ulaiwan Vityakiat",
    "full_name_th": "ผศ.ดร. อุลัยวรรณ์ วิทยเกียรติ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_prukudom_010",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Sukumal",
    "last_name": "Prukudom",
    "full_name": "Sukumal Prukudom",
    "full_name_th": "อ. สพ.ญ.ดร.สุขุมาล พฤกษ์อุดม",
    "role": "อาจารย์ประจำ",
    "email": "sukumal.pru@ku.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_011_011",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "รศ. สพ.ญ.ดร.ศิรินทร์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_012_012",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "ผศ.ดร. เกษริน ขำยิ่งเกิด",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "Ph.D. (Tropical Medicine)"
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_013_013",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "ผศ.ดร. กาญจนา อิ่มศิลป์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_014_014",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "รศ.ดร. ปารียา อุดมกุศลศรี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_015_015",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "ศ.ดร. อำนาจ พัวพลเทพ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "ปรัชญาดุษฎีบัณฑิต (เภสัชวิทยาและพิษวิทยาทางสัตวแพทย์)"
    ],
    "research_interests": [
      "พิษวิทยา",
      "เภสัชวิทยาเชิงประยุกต์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_016_016",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "ผศ.ดร. จันทิมา พฤกษากร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "ปรัชญาดุษฎีบัณฑิต (จุลชีววิทยาทางสัตวแพทย์)"
    ],
    "research_interests": [
      "ไวรัสวิทยา",
      "ชีววิทยา",
      "จุลชีว",
      "พยาธิสัตวแพทย์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_017_017",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "รศ.ดร. จำนงจิต ผาสุข",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "ปรัชญาดุษฎีบัณฑิต (กีฏวิทยา)"
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_018_018",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "รศ.ดร. ศรัญญา พัวพลเทพ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_019_019",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "รศ.ดร. น.สพ.ณัฐสิทธิ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_fac_020_020",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "คณะสัตวแพทยศาสตร์",
    "department_th": "คณะสัตวแพทยศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "ผศ.ดร. สันติ แก้วโมกุล",
    "role": "อาจารย์ประจำ",
    "email": "fvetstk@ku.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [
      "ปรัชญาดุษฎีบัณฑิต (สรีรวิทยา)"
    ],
    "research_interests": [
      "สรีรวิทยาทางสัตวแพทย์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_vijarnsorn_021",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "cacs",
    "department_th": "cacs",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Monchanok",
    "last_name": "Vijarnsorn",
    "full_name": "Monchanok Vijarnsorn",
    "full_name_th": "ผศ. สพ.ญ.ดร. มนชนก วิจารสรณ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "สัตวแพทย์ตัวอย่าง"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "kasetsartu_facultyofa_pichai_022",
    "university": "Kasetsart University",
    "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
    "faculty": "Faculty of Agro-Industry & Faculty of Veterinary Medicine",
    "faculty_th": "คณะอุตสาหกรรมเกษตร และ คณะสัตวแพทยศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Jak",
    "last_name": "Pichai",
    "full_name": "Jak Pichai",
    "full_name_th": "ศ.ดร. น.สพ. จักร พิชัย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "สัตวแพทย์ศาสตร์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
