# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/mahidol_bartlab_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "mahidoluni_department_pillai_002",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Department of Biomedical Engineering & Center for Biomedical and Robotics Technology (BART LAB)",
    "faculty_th": "คณะวิศวกรรมศาสตร์ ภาควิชาวิศวกรรมชีวการแพทย์ (BART LAB)",
    "department": "ภาควิชาวิศวกรรมชีวการแพทย์",
    "department_th": "ภาควิชาวิศวกรรมชีวการแพทย์",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Branesh",
    "last_name": "Pillai",
    "full_name": "Branesh Pillai",
    "full_name_th": "ดร. Branesh M. Pillai",
    "role": "อาจารย์ประจำ",
    "email": "branesh.mad@mahidol.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_department_ritthipravat_003",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Department of Biomedical Engineering & Center for Biomedical and Robotics Technology (BART LAB)",
    "faculty_th": "คณะวิศวกรรมศาสตร์ ภาควิชาวิศวกรรมชีวการแพทย์ (BART LAB)",
    "department": "ภาควิชาวิศวกรรมชีวการแพทย์",
    "department_th": "ภาควิชาวิศวกรรมชีวการแพทย์",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Panrasee",
    "last_name": "Ritthipravat",
    "full_name": "Panrasee Ritthipravat",
    "full_name_th": "ดร. Panrasee Ritthipravat",
    "role": "อาจารย์ประจำ",
    "email": "egprp@mahidol.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_department_charoensuk_004",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Department of Biomedical Engineering & Center for Biomedical and Robotics Technology (BART LAB)",
    "faculty_th": "คณะวิศวกรรมศาสตร์ ภาควิชาวิศวกรรมชีวการแพทย์ (BART LAB)",
    "department": "ภาควิชาวิศวกรรมชีวการแพทย์",
    "department_th": "ภาควิชาวิศวกรรมชีวการแพทย์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Warakorn",
    "last_name": "Charoensuk",
    "full_name": "Warakorn Charoensuk",
    "full_name_th": "รศ.ดร. วรากร เจริญสุข",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
