# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/mahidol_medicine_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "mahidoluni_facultyofm_songsivilai_001",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาวิทยาภูมิคุ้มกัน",
    "department_th": "ภาควิชาวิทยาภูมิคุ้มกัน",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Sirirurg",
    "last_name": "Songsivilai",
    "full_name": "Sirirurg Songsivilai",
    "full_name_th": "ศ. นพ.สิริฤกษ์ ทรงศิวิไล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "วิทยาภูมิคุ้มกัน"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_luangwechakan_002",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาวิทยาภูมิคุ้มกัน",
    "department_th": "ภาควิชาวิทยาภูมิคุ้มกัน",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Voravit",
    "last_name": "Luangwechakan",
    "full_name": "Voravit Luangwechakan",
    "full_name_th": "อ. นพ.วรวิชญ์ เหลืองเวชการ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "วิทยาภูมิคุ้มกัน"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_thuvasethakul_003",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาวิทยาภูมิคุ้มกัน",
    "department_th": "ภาควิชาวิทยาภูมิคุ้มกัน",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Piti",
    "last_name": "Thuvasethakul",
    "full_name": "Piti Thuvasethakul",
    "full_name_th": "รศ.ดร. นพ.ปีติ ธุว",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "วิทยาภูมิคุ้มกัน"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_kamtorntip_004",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาเวชศาสตร์ฟื้นฟู",
    "department_th": "ภาควิชาเวชศาสตร์ฟื้นฟู",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Visanu",
    "last_name": "Kamtorntip",
    "full_name": "Visanu Kamtorntip",
    "full_name_th": "ผศ. นพ.วิษณุ กัมทรทิพย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "เวชศาสตร์ฟื้นฟู"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_jiarakul_005",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาอายุรศาสตร์",
    "department_th": "ภาควิชาอายุรศาสตร์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Nitipat",
    "last_name": "Jiarakul",
    "full_name": "Nitipat Jiarakul",
    "full_name_th": "รศ. นพ.นิธิพัฒน์ เจียรกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "อายุรศาสตร์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_chotireungnapa_006",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาอายุรศาสตร์",
    "department_th": "ภาควิชาอายุรศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Chavalit",
    "last_name": "Chotireungnapa",
    "full_name": "Chavalit Chotireungnapa",
    "full_name_th": "ผศ. นพ.ชวลิต โชติเรืองนภา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "อายุรศาสตร์",
      "ความดันโลหิตสูง"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_akaraviputh_007",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Thawatchai",
    "last_name": " Akaraviputh",
    "full_name": "Thawatchai  Akaraviputh",
    "full_name_th": "ศ. นพ.ธวัชชัย อัครวิพุธ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_ruangtrakool_008",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Rawis",
    "last_name": "Ruangtrakool",
    "full_name": "Rawis Ruangtrakool",
    "full_name_th": "รศ. นพ.รวิศ เรืองตระกูล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_pookriyakamee_009",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาจิตเวชศาสตร์",
    "department_th": "ภาควิชาจิตเวชศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Panate",
    "last_name": "Pookriyakamee",
    "full_name": "Panate Pookriyakamee",
    "full_name_th": "ผศ. นพ.ปเนต ผู้กฤตยาคามี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "จิตเวชศาสตร์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_prateepavanich_010",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาเวชศาสตร์ฟื้นฟู",
    "department_th": "ภาควิชาเวชศาสตร์ฟื้นฟู",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Pradit",
    "last_name": "Prateepavanich",
    "full_name": "Pradit Prateepavanich",
    "full_name_th": "รศ. นพ.ประดิษฐ์ ประทีปะวณิช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "เวชศาสตร์ฟื้นฟู"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_vasuvattakul_011",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "หน่วยโรคไต",
    "department_th": "หน่วยโรคไต",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Somkiat",
    "last_name": "Vasuvattakul",
    "full_name": "Somkiat Vasuvattakul",
    "full_name_th": "อ. นพ.สมเกียรติ วสุวัฎฎกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "โรคไต"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_pajareya_012",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาเวชศาสตร์ฟื้นฟู",
    "department_th": "ภาควิชาเวชศาสตร์ฟื้นฟู",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Kingkaew",
    "last_name": "Pajareya",
    "full_name": "Kingkaew Pajareya",
    "full_name_th": "รศ. พญ.กิ่งแก้ว ปาจรีย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "เวชศาสตร์ฟื้นฟู",
      "พัฒนาการเด็กออทิสติก"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_kitiyakara_013",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Chakree",
    "last_name": "Kitiyakara",
    "full_name": "Chakree Kitiyakara",
    "full_name_th": "ศ. นพ.ม.ล.ชาครีย์ กิติยากร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_dankulchai_014",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Pittaya",
    "last_name": "Dankulchai",
    "full_name": "Pittaya Dankulchai",
    "full_name_th": "รศ. นพ.พิทยา ด่านกุลชัย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_fac_015_015",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Teerawut",
    "last_name": "",
    "full_name": "Teerawut",
    "full_name_th": "ผศ. นพ.ธีรวุฒิ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_duangthongpol_016",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "คณะแพทยศาสตร์ศิริราชพยาบาล",
    "department_th": "คณะแพทยศาสตร์ศิริราชพยาบาล",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Phichayen",
    "last_name": "Duangthongpol",
    "full_name": "Phichayen Duangthongpol",
    "full_name_th": "รศ. นพ.พิชเยนทร์ ดวงทองพล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "Microvascular lab for neurosurgeon"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_sampattavanich_017",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาเภสัชวิทยา",
    "department_th": "ภาควิชาเภสัชวิทยา",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Somponnat",
    "last_name": "Sampattavanich",
    "full_name": "Somponnat Sampattavanich",
    "full_name_th": "ดร. สมพรณัฐ สัมปัตตะวนิช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "Pharmacology"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_pisitkun_018",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Trairak",
    "last_name": "Pisitkun",
    "full_name": "Trairak Pisitkun",
    "full_name_th": "รศ.ดร. ไตรรักษ์ พิศุทธ์สะกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "M.D."
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_leerapan_019",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Borwornsom",
    "last_name": "Leerapan",
    "full_name": "Borwornsom Leerapan",
    "full_name_th": "อ. บวรศม Leerapan",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "Doctor of Medicine (M.D.)"
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_wannakrairot_020",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Surasak",
    "last_name": "Wannakrairot",
    "full_name": "Surasak Wannakrairot",
    "full_name_th": "ผศ. สุรศักดิ์ วรรณไกรโรจน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "M.D."
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_sungkaworn_021",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Titiwat",
    "last_name": "Sungkaworn",
    "full_name": "Titiwat Sungkaworn",
    "full_name_th": "ดร. ติติวัฒน์ สังขวร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "Ph.D."
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_dangprapai_022",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชากุมารเวชศาสตร์",
    "department_th": "ภาควิชากุมารเวชศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Yodying",
    "last_name": "Dangprapai",
    "full_name": "Yodying Dangprapai",
    "full_name_th": "ผศ.ดร. ยิ่งยศ ด่านประไพ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "M.D.",
      "Ph.D.",
      "M.H.P.E."
    ],
    "research_interests": [
      "Pediatrics"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_sukhato_023",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Kanokporn",
    "last_name": "Sukhato",
    "full_name": "Kanokporn Sukhato",
    "full_name_th": "อ. กนกพร สุขโข",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "M.D.",
      "Diploma in Medical Education"
    ],
    "research_interests": [
      "Medical Education"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_sutharatanapong_024",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "ภาควิชาอายุรศาสตร์",
    "department_th": "ภาควิชาอายุรศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Napun",
    "last_name": "Sutharatanapong",
    "full_name": "Napun Sutharatanapong",
    "full_name_th": "อ. นปุณ สุธารทานพงศ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "M.D."
    ],
    "research_interests": [
      "Medicine",
      "Kidney Transplantations"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_nainetr_025",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Pornnop",
    "last_name": "Nainetr",
    "full_name": "Pornnop Nainetr",
    "full_name_th": "อ.ดร. นพ.พรนพ นัยเนตร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofm_homsanit_026",
    "university": "Mahidol University",
    "university_th": "มหาวิทยาลัยมหิดล",
    "faculty": "Faculty of Medicine Siriraj Hospital & Ramathibodi Hospital",
    "faculty_th": "คณะแพทยศาสตร์ศิริราชพยาบาล และ คณะแพทยศาสตร์โรงพยาบาลรามาธิบดี",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Mayuree",
    "last_name": "Homsanit",
    "full_name": "Mayuree Homsanit",
    "full_name_th": "ผศ.ดร. พญ.มยุรี หอมสนิท",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
