# Complete Curricula Dataset for Naresuan University (NU) & Kasetsart University Graduate Expansion (Master's & Ph.D.)

NU_KU_GRAD_FULL_COURSES = [
    # =========================================================================
    # NARESUAN UNIVERSITY (NU - มหาวิทยาลัยนเรศวร พิษณุโลก)
    # =========================================================================
    {
        "id": "nu_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "Naresuan University",
        "university_th": "มหาวิทยาลัยนเรศวร",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Medicine",
        "department_th": "สาขาวิชาแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "254 หน่วยกิต",
        "tuition_per_semester": "25,000 บาท",
        "tuition_total": "300,000 บาท",
        "description": "ศูนย์การแพทย์ระดับตติยภูมิชั้นสูงและโรงเรียนแพทย์ชั้นนำของภาคเหนือตอนล่าง พร้อมโรงพยาบาลมหาวิทยาลัยนเรศวรและศูนย์ปลูกถ่ายอวัยวะ",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิกในโรงพยาบาลมหาวิทยาลัยนเรศวร ขนาดกว่า 800 เตียง", "ศูนย์ความเป็นเลิศด้านการผ่าตัดผ่านกล้องและโรคหัวใจ", "การผลิตแพทย์เพื่อชุมชนและบริการสุขภาพในเขตภาคเหนือตอนล่าง"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไปและแพทย์เฉพาะทาง", "แพทย์ประจำโรงพยาบาลศูนย์และโรงพยาบาลทั่วไป", "อาจารย์แพทย์และนักวิจัยคลินิก"],
        "tags": ["Medicine", "Doctor", "Health Science", "Naresuan Medicine", "Phitsanulok"],
        "website_url": "https://med.nu.ac.th"
    },
    {
        "id": "nu_dent_dds",
        "title_th": "หลักสูตรทันตแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Dental Surgery Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ท.บ. (ทันตแพทยศาสตรบัณฑิต)",
        "university": "Naresuan University",
        "university_th": "มหาวิทยาลัยนเรศวร",
        "faculty": "Faculty of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Dentistry",
        "department_th": "สาขาวิชาทันตแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "234 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "โรงเรียนทันตแพทย์หลักของภาคเหนือตอนล่าง เพียบพร้อมด้วยโรงพยาบาลทันตกรรมและเทคโนโลยีทันตกรรมเฉพาะทาง",
        "curriculum_highlights": ["โรงพยาบาลทันตกรรม คณะทันตแพทยศาสตร์ มหาวิทยาลัยนเรศวร", "การใช้ระบบดิจิทัลทันตกรรม 3D Cone Beam CT และห้องปฏิบัติการจำลองเสมือนจริง", "การออกหน่วยทันตกรรมพระราชทานและทันตกรรมชุมชน"],
        "career_paths": ["ทันตแพทย์ในโรงพยาบาลรัฐและเอกชน", "ทันตแพทย์เฉพาะทาง", "เจ้าของคลินิกทันตกรรม"],
        "tags": ["Dentistry", "Dental", "Doctor of Dental Surgery", "Naresuan Dentistry"],
        "website_url": "https://dent.nu.ac.th"
    },
    {
        "id": "nu_pharm_bpharm_care",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาการบริบาลทางเภสัชกรรม",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Care",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (การบริบาลทางเภสัชกรรม)",
        "university": "Naresuan University",
        "university_th": "มหาวิทยาลัยนเรศวร",
        "faculty": "Faculty of Pharmaceutical Sciences",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Pharmacy Practice",
        "department_th": "ภาควิชาเภสัชกรรมปฏิบัติ",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "226 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "264,000 บาท",
        "description": "สถาบันผลิตเภสัชกรอันดับ 1 ของภาคเหนือตอนล่าง เชี่ยวชาญการบริบาลทางเภสัชกรรมในโรงพยาบาลและการวิจัยสมุนไพรและเครื่องสำอาง",
        "curriculum_highlights": ["สถานปฏิบัติการเภสัชกรรมชุมชน (ร้านยาคณะเภสัชศาสตร์ ม.นเรศวร)", "ศูนย์วิจัยเครื่องสำอางและผลิตภัณฑ์ธรรมชาติ (Cosmetics Natural Products Center)", "การฝึกปฏิบัติงานคลินิกในโรงพยาบาลศูนย์ชั้นนำ"],
        "career_paths": ["เภสัชกรประจำโรงพยาบาลและเภสัชกรคลินิก", "เภสัชกรชุมชน (เจ้าของร้านยา)", "นักวิจัยพัฒนาสูตรตำรับเครื่องสำอางและสมุนไพร"],
        "tags": ["Pharmacy", "Pharmaceutical Care", "Cosmetics", "Naresuan Pharmacy"],
        "website_url": "https://pha.nu.ac.th"
    },
    {
        "id": "nu_ah_bsc_med_tech",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคนิคการแพทย์",
        "title_en": "Bachelor of Science Program in Medical Technology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคนิคการแพทย์)",
        "university": "Naresuan University",
        "university_th": "มหาวิทยาลัยนเรศวร",
        "faculty": "Faculty of Allied Health Sciences",
        "faculty_th": "คณะสหเวชศาสตร์",
        "department": "Department of Medical Technology",
        "department_th": "ภาควิชาเทคนิคการแพทย์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "ผลิตนักเทคนิคการแพทย์ตรวจวิเคราะห์เลือดและสารคัดหลั่ง การตรวจวินิจฉัยพันธุกรรม และการตรวจชันสูตรโรคติดเชื้อ",
        "curriculum_highlights": ["ห้องปฏิบัติการตรวจวิเคราะห์ทางการแพทย์มาตรฐาน ISO 15189", "การตรวจวินิจฉัยระดับชีวโมเลกุล (Real-Time PCR & Flow Cytometry)", "การฝึกปฏิบัติการจริงในห้องแล็บโรงพยาบาลมหาวิทยาลัยนเรศวร"],
        "career_paths": ["นักเทคนิคการแพทย์ประจำโรงพยาบาล", "นักวิทยาศาสตร์การแพทย์ในศูนย์แล็บเฉพาะทาง", "ผู้เชี่ยวชาญผลิตภัณฑ์น้ำยาตรวจวินิจฉัย"],
        "tags": ["Medical Technology", "Allied Health", "Laboratory Diagnostics", "Naresuan"],
        "website_url": "https://ahs.nu.ac.th"
    },
    {
        "id": "nu_eng_beng_computer",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์และปัญญาประดิษฐ์",
        "title_en": "Bachelor of Engineering Program in Computer Engineering and Artificial Intelligence",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมคอมพิวเตอร์)",
        "university": "Naresuan University",
        "university_th": "มหาวิทยาลัยนเรศวร",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Electrical and Computer Engineering",
        "department_th": "ภาควิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "140 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "เน้นการพัฒนาสถาปัตยกรรมซอฟต์แวร์ อัลกอริทึมปัญญาประดิษฐ์ ระบบสมองกลฝังตัว และระบบคลาวด์",
        "curriculum_highlights": ["การพัฒนาแบบจำลอง AI สำหรับการเกษตรอัจฉริยะและการแพทย์", "ห้องปฏิบัติการ IoT และสมองกลฝังตัว (Embedded System Lab)", "การฝึกงานและสหกิจศึกษากับบริษัทไอทีและซอฟต์แวร์ชั้นนำ"],
        "career_paths": ["Computer Engineer / Software Engineer", "AI & Machine Learning Developer", "Cloud Solutions Architect"],
        "tags": ["Computer Engineering", "AI", "Embedded Systems", "Naresuan Engineering"],
        "website_url": "https://eng.nu.ac.th"
    },

    # =========================================================================
    # KASETSART UNIVERSITY GRADUATE EXPANSION (KU ป.โท และ ป.เอก)
    # =========================================================================
    {
        "id": "ku_grad_msc_computer_ai",
        "title_th": "หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์และปัญญาประดิษฐ์",
        "title_en": "Master of Engineering Program in Computer Engineering and Artificial Intelligence",
        "degree_level": "ปริญญาโท",
        "degree_name": "วศ.ม. (วิศวกรรมคอมพิวเตอร์)",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Computer Engineering",
        "department_th": "ภาควิชาวิศวกรรมคอมพิวเตอร์",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "35,000 บาท",
        "tuition_total": "140,000 บาท",
        "description": "วิจัยขั้นสูงด้าน Large Language Models (LLM), Computer Vision, Big Data Architecture, และระบบอัตโนมัติอัจฉริยะ",
        "curriculum_highlights": ["การประมวลผลภาษาธรรมชาติภาษาไทย (Thai NLP) และโมเดลภาษาขนาดใหญ่", "High-Performance Computing Cluster พร้อม GPU ประสิทธิภาพสูงสำหรับการเทรน AI", "การทำวิทยานิพนธ์ร่วมกับสวทช. (NECTEC) และองค์กรเทคโนโลยีระดับโลก"],
        "career_paths": ["Senior AI & Deep Learning Engineer", "Data Architecture Specialist", "อาจารย์และนักวิจัยวิศวกรรมคอมพิวเตอร์"],
        "tags": ["Computer Engineering", "AI", "NLP", "Machine Learning", "Master of Engineering", "Kasetsart"],
        "website_url": "https://cpe.ku.ac.th"
    },
    {
        "id": "ku_grad_phd_computer",
        "title_th": "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์",
        "title_en": "Doctor of Philosophy Program in Computer Engineering",
        "degree_level": "ปริญญาเอก",
        "degree_name": "ปร.ด. (วิศวกรรมคอมพิวเตอร์)",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Computer Engineering",
        "department_th": "ภาควิชาวิศวกรรมคอมพิวเตอร์",
        "program_type": "ภาคปกติ / นานาชาติ",
        "duration_years": "3 ปี",
        "total_credits": "48 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "270,000 บาท",
        "description": "ผลิตนักวิจัยระดับปริญญาเอกผู้สร้างสรรค์องค์ความรู้ใหม่ด้าน AI, Quantum Computing, Distributed Systems และ Cybersecurity",
        "curriculum_highlights": ["การตีพิมพ์ในวารสารวิชาการชั้นนำระดับ Q1 (IEEE Transactions, ACM)", "โอกาสทำงานวิจัยร่วมกับมหาวิทยาลัยพันธมิตรในญี่ปุ่นและสหรัฐอเมริกา", "ทุนการศึกษาและผู้ช่วยวิจัยเต็มเวลา (Research Assistantship)"],
        "career_paths": ["Principal AI Scientist / Chief Technology Officer", "อาจารย์ประจำมหาวิทยาลัยชั้นนำ", "นักวิจัยอาวุโสในสถาบันวิจัยระดับนานาชาติ"],
        "tags": ["Computer Engineering", "Ph.D.", "AI", "Quantum Computing", "Kasetsart"],
        "website_url": "https://cpe.ku.ac.th"
    },
    {
        "id": "ku_grad_msc_forest_carbon",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวนศาสตร์และการจัดการคาร์บอนป่าไม้",
        "title_en": "Master of Science Program in Forestry and Forest Carbon Management",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (วนศาสตร์)",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Forestry",
        "faculty_th": "คณะวนศาสตร์",
        "department": "Department of Forest Management",
        "department_th": "ภาควิชาการจัดการป่าไม้",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "30,000 บาท",
        "tuition_total": "120,000 บาท",
        "description": "ศูนย์กลางการวิจัยคาร์บอนเครดิตภาคป่าไม้แห่งเดียวในไทย การประเมินการกักเก็บคาร์บอนในป่าเขตร้อน (T-VER/Verra/VCS) และวนเกษตรยั่งยืน",
        "curriculum_highlights": ["การใช้โดรน LiDAR และภาพถ่ายดาวเทียมสำรวจมวลชีวภาพและการกักเก็บคาร์บอน", "การพัฒนาโครงการ Forest Carbon Offset และการซื้อขายคาร์บอนเครดิตสากล", "ความร่วมมือกับองค์การบริหารจัดการก๊าซเรือนกระจก (TGO) และกรมป่าไม้"],
        "career_paths": ["ผู้เชี่ยวชาญการประเมินคาร์บอนเครดิตป่าไม้ (Forest Carbon Credit Specialist)", "ที่ปรึกษาด้านความยั่งยืนและ Net Zero ป่าไม้", "นักวิจัยนิเวศวิทยาป่าไม้"],
        "tags": ["Forestry", "Carbon Credit", "Net Zero", "Remote Sensing", "Master", "Kasetsart"],
        "website_url": "https://forest.ku.ac.th"
    },
    {
        "id": "ku_grad_msc_fisheries_aquaculture",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาการเพาะเลี้ยงสัตว์น้ำและเทคโนโลยีชีวภาพทางน้ำ",
        "title_en": "Master of Science Program in Aquaculture and Aquatic Biotechnology",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (การประมง)",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Fisheries",
        "faculty_th": "คณะประมง",
        "department": "Department of Aquaculture",
        "department_th": "ภาควิชาเพาะเลี้ยงสัตว์น้ำ",
        "program_type": "ภาคปกติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "30,000 บาท",
        "tuition_total": "120,000 บาท",
        "description": "วิจัยขั้นสูงด้านพันธุวิศวกรรมสัตว์น้ำ โภชนาการและอาหารสัตว์น้ำคุณภาพสูง และระบบการเพาะเลี้ยงสัตว์น้ำความหนาแน่นสูงและเป็นมิตรต่อสิ่งแวดล้อม",
        "curriculum_highlights": ["สถานีวิจัยประมงคลองวาฬและศรีราชา", "การพัฒนาวัคซีนและสารเสริมภูมิคุ้มกันสำหรับกุ้งและปลาเศรษฐกิจ", "ความร่วมมือกับบริษัทผู้นำธุรกิจเกษตรและอาหารแปรรูปสัตว์น้ำระดับโลก (CP, Thai Union)"],
        "career_paths": ["นักวิจัยและพัฒนาอาหารและสุขภาพสัตว์น้ำ (Aquaculture R&D)", "ผู้จัดการเทคนิคฟาร์มสัตว์น้ำระดับสากล", "อาจารย์และนักวิชาการประมง"],
        "tags": ["Fisheries", "Aquaculture", "Aquatic Biotechnology", "Master", "Kasetsart"],
        "website_url": "https://fish.ku.ac.th"
    },
]
