# -*- coding: utf-8 -*-
EXTRACTED_FACULTIES = [
    {
        "id": "chulalongk_facultyofp_dilokpatanamong_001",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาเภสัชกรรม",
        "department_th": "ภาควิชาเภสัชกรรม",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Pitchaya",
        "last_name": "Dilokpatanamongkol",
        "full_name": "Pitchaya Dilokpatanamongkol",
        "full_name_th": "ผศ. ภญ. พิชญา ดิลกพัฒนมงคล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_chantjaruporn_002",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาเภสัชกรรม",
        "department_th": "ภาควิชาเภสัชกรรม",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Fahsai",
        "last_name": "Chantjaruporn",
        "full_name": "Fahsai Chantjaruporn",
        "full_name_th": "ผศ.ดร. ภญ. ฟ้าใส จันท์จารุภรณ์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_wongrakpanich_003",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาเภสัชกรรม",
        "department_th": "ภาควิชาเภสัชกรรม",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Amaraporn",
        "last_name": "Wongrakpanich",
        "full_name": "Amaraporn Wongrakpanich",
        "full_name_th": "รศ.ดร. ภญ. อมราพร วงศ์รักษ์พานิช",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_wongkrajang_004",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาสรีรวิทยา",
        "department_th": "ภาควิชาสรีรวิทยา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Yuwadee",
        "last_name": "Wongkrajang",
        "full_name": "Yuwadee Wongkrajang",
        "full_name_th": "อ. ยุวดี วงษ์กระจ่าง",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_temsiririrkkul_005",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาเภสัชพฤกษศาสตร์",
        "department_th": "ภาควิชาเภสัชพฤกษศาสตร์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Rungrawee",
        "last_name": "Temsiririrkkul",
        "full_name": "Rungrawee Temsiririrkkul",
        "full_name_th": "อ. รุ่งระวี เต็มศิริฤกษ์กุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_nakornchai_006",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาเภสัชวิทยา",
        "department_th": "ภาควิชาเภสัชวิทยา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Somjai",
        "last_name": "Nakornchai",
        "full_name": "Somjai Nakornchai",
        "full_name_th": "อ. สมใจ นครชัย",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_udomsinprasert_007",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาชีวเคมี",
        "department_th": "ภาควิชาชีวเคมี",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Wanwisa",
        "last_name": "Udomsinprasert",
        "full_name": "Wanwisa Udomsinprasert",
        "full_name_th": "รศ.ดร. ทนพญ. วันวิสาข์ อุดมสินประเสริฐ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "ชีวบ่งชี้",
            "อีพีจีเจเนติกส์เพื่อการรักษาแบบมุ่งเป้า"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_suphratanasit_008",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาสรีรวิทยา",
        "department_th": "ภาควิชาสรีรวิทยา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Wasu",
        "last_name": "Suphratanasit",
        "full_name": "Wasu Suphratanasit",
        "full_name_th": "ผศ.ดร. ภก. วสุ ศุภรัตนสิทธิ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_tonnum_009",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาสรีรวิทยา",
        "department_th": "ภาควิชาสรีรวิทยา",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Kalayanee",
        "last_name": "Tonnum",
        "full_name": "Kalayanee Tonnum",
        "full_name_th": "อ.ดร. ภญ. กัลยาณี โตนุ่ม",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_fac_010_010",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาวิทยาศาสตร์เภสัชกรรม",
        "department_th": "ภาควิชาวิทยาศาสตร์เภสัชกรรม",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Noppadon",
        "last_name": "",
        "full_name": "Noppadon",
        "full_name_th": "ผศ.ดร. ภก. นพดล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_kiatisin_011",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาวิทยาศาสตร์เภสัชกรรม",
        "department_th": "ภาควิชาวิทยาศาสตร์เภสัชกรรม",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Kanokwan",
        "last_name": "Kiatisin",
        "full_name": "Kanokwan Kiatisin",
        "full_name_th": "ผศ.ดร. ภญ. กนกวรรณ เกียรติสิน",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_mingphan_012",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Warunee",
        "last_name": "Mingphan",
        "full_name": "Warunee Mingphan",
        "full_name_th": "อ. ภญ.วารุณี มิ่งพันธ์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_saenjum_013",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาวิทยาศาสตร์เภสัชกรรม",
        "department_th": "ภาควิชาวิทยาศาสตร์เภสัชกรรม",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Chalermpong",
        "last_name": "Saenjum",
        "full_name": "Chalermpong Saenjum",
        "full_name_th": "รศ.ดร. ภก.เฉลิมพงษ์ แสนจุ้ม",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_vongsutilers_014",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Vorasit",
        "last_name": "Vongsutilers",
        "full_name": "Vorasit Vongsutilers",
        "full_name_th": "รศ.ดร. ภก.วรสิทธิ์ วงศ์สุทธิเลิศ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_sakulbumrungsil_015",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Rungpetch",
        "last_name": "Sakulbumrungsil",
        "full_name": "Rungpetch Sakulbumrungsil",
        "full_name_th": "ผศ.ดร. รุ่งเพ็ชร สกุลบำรุงศิลป์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_kulsomboon_016",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Vithaya",
        "last_name": "Kulsomboon",
        "full_name": "Vithaya Kulsomboon",
        "full_name_th": "รศ.ดร. วิทยา กุลสมบูรณ์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_avihingsanon_017",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Rattanaporn",
        "last_name": "Avihingsanon",
        "full_name": "Rattanaporn Avihingsanon",
        "full_name_th": "ผศ.ดร. รัตนาภรณ์ อาวิพันธ์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_theeramankong_018",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Sriwan",
        "last_name": "Theeramankong",
        "full_name": "Sriwan Theeramankong",
        "full_name_th": "รศ.ดร. ภญ.ศรีวรรณ ธีระมั่นคง",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_suknuntha_019",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Krit",
        "last_name": "Suknuntha",
        "full_name": "Krit Suknuntha",
        "full_name_th": "ผศ.ดร. ภก.กฤษณ์ สุขนันทร์ธะ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_thitaphiwatnaku_020",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Warin",
        "last_name": "Thitaphiwatnakul",
        "full_name": "Warin Thitaphiwatnakul",
        "full_name_th": "รศ.ดร. ภญ.วฤณ ฐิตาภิวัฒนกุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_petchmongkol_021",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาเทคโนโลยีเภสัชกรรม คณะเภสัชศาสตร์",
        "department_th": "ภาควิชาเทคโนโลยีเภสัชกรรม คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Thawatchai",
        "last_name": "Petchmongkol",
        "full_name": "Thawatchai Petchmongkol",
        "full_name_th": "รศ.ดร. ภก.ธวัชชัย แพชมัด",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ประกาศนียบัตร (หลักสูตรการ...) คณะเภสัชศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย พ.ศ. ๒๕๖๒"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_sirisinsuk_022",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Yupadee",
        "last_name": "Sirisinsuk",
        "full_name": "Yupadee Sirisinsuk",
        "full_name_th": "ผศ.ดร. ภญ.ยุพดี ศิริสินสุข",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_limpananont_023",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "มูลนิธิเภสัชศาสตร์เพื่อสังคม",
        "department_th": "มูลนิธิเภสัชศาสตร์เพื่อสังคม",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Jiraporn",
        "last_name": "Limpananont",
        "full_name": "Jiraporn Limpananont",
        "full_name_th": "รศ.ดร. ภญ.จิราพร ลิ้มปานานนท์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_thongroj_024",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Phawich",
        "last_name": "Thongroj",
        "full_name": "Phawich Thongroj",
        "full_name_th": "ผศ.ดร. ภญ. ภาวิช ทองโรจน์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "เภสัชบำบัด"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_thong_025",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Chuanee",
        "last_name": "Thong",
        "full_name": "Chuanee Thong",
        "full_name_th": "รศ.ดร. ภญ. ชวนี ทอง",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_thavorncharoens_026",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "ภาควิชาเภสัชกรรม คณะเภสัชศาสตร์",
        "department_th": "ภาควิชาเภสัชกรรม คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Montrat",
        "last_name": "Thavorncharoensap",
        "full_name": "Montrat Thavorncharoensap",
        "full_name_th": "รศ.ดร. ภญ. มนทรัตม์ ถาวรเจริญทรัพย์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_jintapattanakit_027",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Anchalee",
        "last_name": "Jintapattanakit",
        "full_name": "Anchalee Jintapattanakit",
        "full_name_th": "ผศ.ดร. ภญ. อัญชลี จินตพัฒนากิจ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_suksiriworapong_028",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Jiraphong",
        "last_name": "Suksiriworapong",
        "full_name": "Jiraphong Suksiriworapong",
        "full_name_th": "รศ.ดร. ภก. จิรพงศ์ สุขสิริวรพงศ์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_nadhisuwan_029",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.",
        "academic_title_th": "รศ.",
        "first_name": "Surakit",
        "last_name": "Nadhisuwan",
        "full_name": "Surakit Nadhisuwan",
        "full_name_th": "รศ. ภก. สุรกิจ นาฑีสุวรรณ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_santivarangkna_030",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Chalat",
        "last_name": "Santivarangkna",
        "full_name": "Chalat Santivarangkna",
        "full_name_th": "รศ.ดร. ชลัท ศานติวรางคณา",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_prathanturarux_031",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Sompop",
        "last_name": "Prathanturarux",
        "full_name": "Sompop Prathanturarux",
        "full_name_th": "รศ.ดร. ภก. สมภพ ประธานธุรารักษ์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_kongsaksakul_032",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Boontiam",
        "last_name": "Kongsaksakul",
        "full_name": "Boontiam Kongsaksakul",
        "full_name_th": "รศ.ดร. บุญเทียม คงศักดิ์ตระกูล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_suthisisang_033",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Juthamas",
        "last_name": "Suthisisang",
        "full_name": "Juthamas Suthisisang",
        "full_name_th": "รศ.ดร. จุฑามณี สุทธิสีสังข์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_chaikledkaew_034",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Usa",
        "last_name": "Chaikledkaew",
        "full_name": "Usa Chaikledkaew",
        "full_name_th": "รศ.ดร. อุษา ฉายเกล็ดแก้ว",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_kulkanjanasehed_035",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Pisamai",
        "last_name": "Kulkanjanasehed",
        "full_name": "Pisamai Kulkanjanasehed",
        "full_name_th": "รศ.ดร. พิสมัย กุลกาญจนาธร",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_fac_036_036",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Jenni",
        "last_name": "",
        "full_name": "Jenni",
        "full_name_th": "ผศ. ภญ. เจนนิ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "chulalongk_facultyofp_pattanarungsee_037",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "คณะเภสัชศาสตร์",
        "department_th": "คณะเภสัชศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Siripan",
        "last_name": "Pattanarungsee",
        "full_name": "Siripan Pattanarungsee",
        "full_name_th": "ผศ.ดร. ภญ. สิริพรรณ พัฒนาฤดี",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
