# PSU Complete 5-Campus Curriculum Dataset (Hat Yai, Phuket, Pattani, Surat Thani, Trang)

PSU_FULL_CAMPUSES_COURSES = [
    # =========================================================================
    # HAT YAI CAMPUS (วิทยาเขตหาดใหญ่)
    # =========================================================================
    {
        "id": "psu_hy_dent_dds",
        "title_th": "หลักสูตรทันตแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Dental Surgery Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ท.บ. (ทันตแพทยศาสตรบัณฑิต)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Dentistry",
        "department_th": "สาขาวิชาทันตแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "236 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "ศูนย์กลางทันตแพทยศาสตร์อันดับ 1 ของภาคใต้ พร้อมโรงพยาบาลทันตกรรมและศูนย์วิจัยทันตกรรมดิจิทัลครบวงจร",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิกในโรงพยาบาลทันตกรรม มหาวิทยาลัยสงขลานครินทร์", "เทคโนโลยีทันตกรรมดิจิทัล 3D CAD/CAM และการผ่าตัดขากรรไกร", "การบริการทันตกรรมชุมชนในพื้นที่ 14 จังหวัดภาคใต้"],
        "career_paths": ["ทันตแพทย์ประจำโรงพยาบาลรัฐและเอกชน", "ทันตแพทย์เฉพาะทางทุกสาขา", "อาจารย์ทันตแพทย์และนักวิจัยทันตกรรม"],
        "tags": ["Dentistry", "Dental", "Doctor of Dental Surgery", "PSU Dentistry", "Hat Yai"],
        "website_url": "https://dent.psu.ac.th"
    },
    {
        "id": "psu_hy_nurs_bns",
        "title_th": "หลักสูตรพยาบาลศาสตรบัณฑิต",
        "title_en": "Bachelor of Nursing Science Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พย.บ. (พยาบาลศาสตรบัณฑิต)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Nursing",
        "faculty_th": "คณะพยาบาลศาสตร์",
        "department": "Department of Nursing",
        "department_th": "สาขาวิชาพยาบาลศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "คณะพยาบาลศาสตร์ชั้นนำของภาคใต้ มุ่งเน้นการพยาบาลผู้ป่วยวิกฤต การดูแลสุขภาพชุมชนพหุวัฒนธรรม และนวัตกรรมทางการพยาบาล",
        "curriculum_highlights": ["การฝึกปฏิบัติงาน ณ โรงพยาบาลสงขลานครินทร์ (โรงพยาบาลระดับตติยภูมิชั้นสูง)", "ศูนย์จำลองสถานการณ์เพื่อการเรียนรู้ทางการพยาบาล (Nursing Simulation Lab)", "การดูแลสุขภาพในบริบทสังคมพหุวัฒนธรรม"],
        "career_paths": ["พยาบาลวิชาชีพในโรงพยาบาลรัฐและเอกชนชั้นนำ", "พยาบาลเฉพาะทาง (ไอซียู, หัวใจ, เด็ก)", "พยาบาลประจำสถานเอกอัครราชทูตและองค์กรระหว่างประเทศ"],
        "tags": ["Nursing", "Nurse", "Healthcare", "PSU Nursing", "Hat Yai"],
        "website_url": "https://nur.psu.ac.th"
    },
    {
        "id": "psu_hy_eng_civil",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมโยธา",
        "title_en": "Bachelor of Engineering Program in Civil Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมโยธา)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Civil Engineering",
        "department_th": "ภาควิชาวิศวกรรมโยธา",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "เน้นการออกแบบโครงสร้างอาคาร สะพาน วิศวกรรมปฐพี วิศวกรรมทรัพยากรน้ำ และการก่อสร้างโครงสร้างพื้นฐานชายฝั่งทะเลภาคใต้",
        "curriculum_highlights": ["การออกแบบโครงสร้างต้านทานแผ่นดินไหวและโครงสร้างชายฝั่งทะเล", "การใช้ซอฟต์แวร์ BIM และการสร้างแบบจำลอง 3 มิติ", "การฝึกงานกับบริษัทรับเหมาก่อสร้างและที่ปรึกษาวิศวกรรมชั้นนำ"],
        "career_paths": ["วิศวกรโยธาและวิศวกรโครงสร้าง", "วิศวกรควบคุมงานก่อสร้าง (Site Engineer)", "วิศวกรสำรวจและปฐพีกลศาสตร์"],
        "tags": ["Civil Engineering", "Structural Engineering", "Infrastructure", "PSU Engineering"],
        "website_url": "https://civil.eng.psu.ac.th"
    },
    {
        "id": "psu_hy_eng_mech",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเครื่องกล",
        "title_en": "Bachelor of Engineering Program in Mechanical Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมเครื่องกล)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Mechanical Engineering",
        "department_th": "ภาควิชาวิศวกรรมเครื่องกล",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "ศึกษาด้านพลังงานความร้อน กลศาสตร์ของไหล หุ่นยนต์อุตสาหกรรม และการแปรรูปพลังงานชีวมวลและน้ำมันปาล์ม",
        "curriculum_highlights": ["การจำลองทางอุณหพลศาสตร์และกลศาสตร์ของไหล (CFD)", "การออกแบบระบบปรับอากาศ พลังงานหมุนเวียน และยานยนต์", "การทำโครงงานวิจัยร่วมกับโรงงานแปรรูปยางพาราและน้ำมันปาล์ม"],
        "career_paths": ["วิศวกรเครื่องกล", "วิศวกรพลังงานและโรงไฟฟ้า", "วิศวกรระบบปรับอากาศและทำความเย็น (HVAC)"],
        "tags": ["Mechanical Engineering", "Thermal Energy", "CFD", "PSU Engineering"],
        "website_url": "https://me.eng.psu.ac.th"
    },
    {
        "id": "psu_hy_agro_food",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์และเทคโนโลยีอาหาร",
        "title_en": "Bachelor of Science Program in Food Science and Technology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาศาสตร์และเทคโนโลยีอาหาร)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Agro-Industry",
        "faculty_th": "คณะอุตสาหกรรมเกษตร",
        "department": "Department of Food Science and Nutrition",
        "department_th": "ภาควิชาวิทยาศาสตร์อาหารและโภชนาการ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "เน้นการแปรรูปอาหารทะเล อาหารฮาลาลมาตรฐานสากล นวัตกรรมอาหารฟังก์ชัน และการควบคุมคุณภาพตามมาตรฐาน GMP/HACCP/ISO 22000",
        "curriculum_highlights": ["โรงงานต้นแบบแปรรูปอาหารมาตรฐานและศูนย์วิจัยอาหารฮาลาล", "การพัฒนาผลิตภัณฑ์อาหารทะเลมูลค่าสูงและโปรตีนทางเลือก", "ความร่วมมือกับอุตสาหกรรมแปรรูปอาหารส่งออกชั้นนำของภาคใต้"],
        "career_paths": ["นักวิจัยและพัฒนาผลิตภัณฑ์อาหาร (Food R&D)", "นักควบคุมคุณภาพและประกันคุณภาพอาหาร (QA/QC)", "ผู้เชี่ยวชาญมาตรฐานอาหารฮาลาล"],
        "tags": ["Food Science", "Agro-Industry", "Halal Food", "Seafood Processing", "PSU"],
        "website_url": "https://agro.psu.ac.th"
    },
    {
        "id": "psu_hy_fms_bba_marketing",
        "title_th": "หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาการตลาดดิจิทัลและการสร้างแบรนด์",
        "title_en": "Bachelor of Business Administration Program in Digital Marketing and Branding",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ. (การตลาด)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "Department of Marketing",
        "department_th": "สาขาวิชาการตลาด",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "พัฒนาทักษะการตลาดดิจิทัล การวิเคราะห์พฤติกรรมผู้บริโภคออนไลน์ การบริหารสื่อโซเชียลมีเดีย และการค้าระหว่างประเทศในภูมิภาคอาเซียนตอนล่าง",
        "curriculum_highlights": ["การยิงโฆษณาและการวิเคราะห์ Data Analytics บน Meta / Google Ads / TikTok", "การทำแคมเปญการตลาดจริงกับผู้ประกอบการ SME ภาคใต้", "การค้าข้ามพรมแดนไทย-มาเลเซีย-สิงคโปร์"],
        "career_paths": ["Digital Marketing Specialist", "Brand Manager / Content Creator", "E-Commerce Manager"],
        "tags": ["Marketing", "Digital Marketing", "Management Sciences", "PSU FMS"],
        "website_url": "https://fms.psu.ac.th"
    },

    # =========================================================================
    # PHUKET CAMPUS (วิทยาเขตภูเก็ต)
    # =========================================================================
    {
        "id": "psu_phuket_fis_intl_business",
        "title_th": "หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาการต่างประเทศและการสื่อสารข้ามวัฒนธรรม (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Arts Program in International Studies and Intercultural Communication (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ. (การต่างประเทศ)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of International Studies (Phuket)",
        "faculty_th": "คณะวิเทศศึกษา (วิทยาเขตภูเก็ต)",
        "department": "Department of International Studies",
        "department_th": "สาขาวิชาการต่างประเทศ",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "38,000 บาท",
        "tuition_total": "304,000 บาท",
        "description": "เน้นความสัมพันธ์ระหว่างประเทศ ธุรกิจและการทูตในเอเชียตะวันออกเฉียงใต้และจีน การสื่อสารพหุวัฒนธรรม และภาษาต่างประเทศระดับสูง",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษ 100% กับคณาจารย์และนักศึกษาต่างชาติ", "ทางเลือกเรียนภาษาจีน ญี่ปุ่น หรือเกาหลีแบบเข้มข้น", "โอกาสแลกเปลี่ยนและฝึกงานกับองค์กรระดับโลกในศูนย์กลางการท่องเที่ยวภูเก็ต"],
        "career_paths": ["เจ้าหน้าที่การทูตและวิเทศสัมพันธ์", "ผู้จัดการฝ่ายธุรกิจและการตลาดระหว่างประเทศ", "พนักงานต้อนรับบนเครื่องบินและฝ่ายบริการลูกค้าพรีเมียม"],
        "tags": ["International Studies", "Phuket", "Intercultural", "PSU Phuket"],
        "website_url": "https://fis.phuket.psu.ac.th"
    },
    {
        "id": "psu_phuket_fht_tourism",
        "title_th": "หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาการจัดการบริการและการท่องเที่ยวพรีเมียม (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Business Administration in Premium Hospitality and Tourism Management (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ. (การจัดการบริการและการท่องเที่ยว)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Hospitality and Tourism (Phuket)",
        "faculty_th": "คณะการบริการและการท่องเที่ยว (วิทยาเขตภูเก็ต)",
        "department": "Department of Tourism Management",
        "department_th": "สาขาวิชาการท่องเที่ยว",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "42,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "คณะการท่องเที่ยวและการบริการอันดับ 1 ของภูเก็ต ศูนย์กลางการท่องเที่ยวระดับโลกของเอเชีย ได้รับการรับรอง UNWTO.TedQual",
        "curriculum_highlights": ["การรับรองมาตรฐานการศึกษาระดับโลก UNWTO.TedQual จากองค์การการท่องเที่ยวโลก", "การฝึกงานกับเครือโรงแรมและรีสอร์ทหรูระดับ 5-6 ดาว (Marriott, Accor, Hyatt)", "การบริหารจัดการการท่องเที่ยวอย่างยั่งยืนและการจัดการอีเวนต์ระดับนานาชาติ (MICE)"],
        "career_paths": ["Hotel & Resort General Manager", "Luxury Travel Consultant / Airline Station Manager", "MICE & Event Director"],
        "tags": ["Hospitality", "Tourism", "Phuket", "UNWTO", "PSU Phuket"],
        "website_url": "https://fht.phuket.psu.ac.th"
    },

    # =========================================================================
    # PATTANI CAMPUS (วิทยาเขตปัตตานี)
    # =========================================================================
    {
        "id": "psu_pn_edu_bed",
        "title_th": "หลักสูตรครุศาสตรบัณฑิต สาขาวิชาการศึกษา (มัธยมศึกษาและประถมศึกษา)",
        "title_en": "Bachelor of Education Program in Secondary and Primary Education",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ค.บ. (การศึกษา)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Education (Pattani)",
        "faculty_th": "คณะศึกษาศาสตร์ (วิทยาเขตปัตตานี)",
        "department": "Department of Curriculum and Instruction",
        "department_th": "ภาควิชาหลักสูตรและการสอน",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "14,000 บาท",
        "tuition_total": "112,000 บาท",
        "description": "คณะก่อตั้งแห่งแรกของ ม.อ. ปัตตานี ผลิตครูและบุคลากรทางการศึกษาชั้นนำของภาคใต้ที่มีความเชี่ยวชาญการสอนพหุวัฒนธรรม",
        "curriculum_highlights": ["การฝึกปฏิบัติการสอนในโรงเรียนสาธิตมหาวิทยาลัยสงขลานครินทร์", "การจัดการศึกษาในสังคมพหุวัฒนธรรมและสันติศึกษา", "การออกแบบสื่อนวัตกรรมการเรียนรู้ดิจิทัลและ Active Learning"],
        "career_paths": ["ครูผู้สอนในโรงเรียนรัฐและเอกชน", "นักวิชาการศึกษาและนักพัฒนาหลักสูตร", "ผู้บริหารสถานศึกษา"],
        "tags": ["Education", "Teacher", "Pattani", "Curriculum", "PSU Pattani"],
        "website_url": "https://edupsu.pn.psu.ac.th"
    },
    {
        "id": "psu_pn_cis_islamic_studies",
        "title_th": "หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาอิสลามศึกษาและกฎหมายอิสลาม",
        "title_en": "Bachelor of Arts Program in Islamic Studies and Islamic Law",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ. (อิสลามศึกษา)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "College of Islamic Studies (Pattani)",
        "faculty_th": "วิทยาลัยอิสลามศึกษา (วิทยาเขตปัตตานี)",
        "department": "Department of Islamic Studies",
        "department_th": "สาขาวิชาอิสลามศึกษา",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "14,000 บาท",
        "tuition_total": "112,000 บาท",
        "description": "ศูนย์กลางการศึกษาอิสลามศึกษา การเงินอิสลาม และกฎหมายอิสลามระดับแนวหน้าของเอเชียตะวันออกเฉียงใต้",
        "curriculum_highlights": ["การเงินและเศรษฐศาสตร์อิสลาม (Islamic Finance & Banking)", "กฎหมายอิสลามเปรียบเทียบและการระงับข้อพิพาททางเลือก", "ความร่วมมือกับมหาวิทยาลัยอิสลามชั้นนำในตะวันออกกลางและมาเลเซีย"],
        "career_paths": ["ที่ปรึกษาการเงินและธนาคารอิสลาม (Shariah Advisor)", "นักวิชาการอิสลามศึกษาและล่ามภาษาอาหรับ", "ผู้ประเมินมาตรฐานผลิตภัณฑ์ฮาลาล"],
        "tags": ["Islamic Studies", "Islamic Finance", "Shariah", "Pattani", "PSU"],
        "website_url": "https://cis.pn.psu.ac.th"
    },

    # =========================================================================
    # SURAT THANI & TRANG CAMPUSES (วิทยาเขตสุราษฎร์ธานี และ ตรัง)
    # =========================================================================
    {
        "id": "psu_surat_sci_rubber_tech",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยียางและพอลิเมอร์ชีวภาพ",
        "title_en": "Bachelor of Science Program in Rubber Technology and Biopolymers",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคโนโลยียางและพอลิเมอร์)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Science and Industrial Technology (Surat Thani)",
        "faculty_th": "คณะวิทยาศาสตร์และเทคโนโลยีอุตสาหกรรม (วิทยาเขตสุราษฎร์ธานี)",
        "department": "Department of Rubber Technology",
        "department_th": "สาขาวิชาเทคโนโลยียางและพอลิเมอร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "ศูนย์ความเป็นเลิศด้านเทคโนโลยียางพาราชั้นนำของประเทศ ศึกษาการแปรรูปน้ำยางธรรมชาติ ยางสังเคราะห์ และพอลิเมอร์ชีวภาพมูลค่าสูง",
        "curriculum_highlights": ["การออกแบบสูตรยางคอมพาวด์และผลิตภัณฑ์ยางทางการแพทย์ (ถุงมือ, ท่อยาง)", "โรงงานต้นแบบแปรรูปยางและห้องทดสอบสมบัติทางกลของยางมาตรฐานสากล", "ความร่วมมือกับสถาบันวิจัยยางและการยางแห่งประเทศไทย (กยท.)"],
        "career_paths": ["นักเทคโนโลยียางและวิศวกรแปรรูปพอลิเมอร์ (Rubber Technologist)", "นักวิจัยและพัฒนาผลิตภัณฑ์ยางและพลาสติกชีวภาพ (R&D)", "ผู้จัดการฝ่ายควบคุมคุณภาพในอุตสาหกรรมยางล้อและถุงมือแพทย์"],
        "tags": ["Rubber Technology", "Polymer", "Natural Rubber", "Surat Thani", "PSU"],
        "website_url": "https://scit.surat.psu.ac.th"
    },
    {
        "id": "psu_trang_arch_barch",
        "title_th": "หลักสูตรสถาปัตยกรรมศาสตรบัณฑิต สาขาวิชาสถาปัตยกรรมเขตร้อนและการออกแบบชุมชน",
        "title_en": "Bachelor of Architecture Program in Tropical Architecture and Community Design",
        "degree_level": "ปริญญาตรี",
        "degree_name": "สถ.บ. (สถาปัตยกรรม)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Architecture (Trang)",
        "faculty_th": "คณะสถาปัตยกรรมศาสตร์ (วิทยาเขตตรัง)",
        "department": "Department of Architecture",
        "department_th": "สาขาวิชาสถาปัตยกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "5 ปี",
        "total_credits": "162 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "220,000 บาท",
        "description": "เชี่ยวชาญการออกแบบสถาปัตยกรรมในเขตภูมิอากาศร้อนชื้น (Tropical Architecture) การอนุรักษ์สถาปัตยกรรมชิโนโปรตุกีส และการออกแบบรีสอร์ทชายฝั่งทะเลอันดามัน",
        "curriculum_highlights": ["การออกแบบอาคารประหยัดพลังงานและการระบายอากาศธรรมชาติในเขตร้อนชื้น", "สตูดิโอออกแบบสถาปัตยกรรมชุมชนและมรดกวัฒนธรรมภาคใต้", "การประยุกต์ใช้ BIM และการสร้างแบบจำลองสถาปัตยกรรม 3 มิติ"],
        "career_paths": ["สถาปนิกวิชาชีพ (Licensed Architect)", "นักออกแบบรีสอร์ทและสถาปัตยกรรมเขตร้อน", "นักผังเมืองและผู้อนุรักษ์มรดกสถาปัตยกรรม"],
        "tags": ["Architecture", "Tropical Architecture", "Trang", "Resort Design", "PSU Trang"],
        "website_url": "https://arch.trang.psu.ac.th"
    },
]
