# PSU (Prince of Songkla University) Official Curricula Dataset

PSU_COURSES = [
    # --- คณะแพทยศาสตร์ (Faculty of Medicine - Hat Yai) ---
    {
        "id": "psu_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Clinical Medicine",
        "department_th": "ภาควิชาแพทยศาสตร์คลินิก",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "254 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "มุ่งผลิตแพทย์ที่มีความรู้ความสามารถทางคลินิกระดับมาตรฐานสากล มีทักษะการดูแลสุขภาพแบบองค์รวมและการวิจัยเพื่อตอบสนองปัญหาสาธารณสุขภาคใต้และระดับประเทศ",
        "curriculum_highlights": ["การเรียนรู้ทางคลินิก ณ โรงพยาบาลสงขลานครินทร์ โรงพยาบาลศูนย์ระดับตติยภูมิขั้นสูง", "การบูรณาการเวชศาสตร์ครอบครัวและชุมชนภาคใต้", "ทักษะการทำวิจัยทางการแพทย์เพื่อพัฒนาคุณภาพชีวิต"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไป", "แพทย์เฉพาะทางทุกสาขา", "อาจารย์แพทย์และนักวิจัย", "ผู้บริหารระบบบริการสุขภาพ"],
        "tags": ["Medicine", "Doctor", "Health Sciences", "PSU Medicine"],
        "website_url": "https://medinfo.psu.ac.th"
    },
    {
        "id": "psu_med_msc_biomedical",
        "title_th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชาวิทยาศาสตร์ชีวการแพทย์ (หลักสูตรนานาชาติ)",
        "title_en": "Master of Science Program in Biomedical Sciences (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "วท.ม. (วิทยาศาสตร์ชีวการแพทย์)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Biomedical Sciences",
        "department_th": "สาขาวิชาวิทยาศาสตร์ชีวการแพทย์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "40,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "เน้นการวิจัยเชิงลึกระดับเซลล์และชีววิทยาโมเลกุล พันธุศาสตร์การแพทย์ พยาธิสรีรวิทยา และการพัฒนานวัตกรรมการตรวจวินิจฉัยและรักษาโรค",
        "curriculum_highlights": ["การวิจัยกลไกการเกิดโรคเขตร้อนและโรคไม่ติดต่อเรื้อรัง", "เทคนิคชีววิทยาโมเลกุลขั้นสูงและการเพาะเลี้ยงเซลล์", "การทำวิจัยร่วมกับศูนย์วิจัยชีวการแพทย์ระดับนานาชาติ"],
        "career_paths": ["นักวิทยาศาสตร์การแพทย์และนักวิจัยชีวการแพทย์", "นักวิจัยในบริษัทยาและชีวเภสัชภัณฑ์", "อาจารย์มหาวิทยาลัย"],
        "tags": ["Biomedical Sciences", "Molecular Medicine", "Genetics", "Health Research"],
        "website_url": "https://medinfo.psu.ac.th"
    },
    {
        "id": "psu_med_phd_biomedical",
        "title_th": "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาวิทยาศาสตร์ชีวการแพทย์ (หลักสูตรนานาชาติ)",
        "title_en": "Doctor of Philosophy Program in Biomedical Sciences (International Program)",
        "degree_level": "ปริญญาเอก",
        "degree_name": "ปร.ด. (วิทยาศาสตร์ชีวการแพทย์)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Biomedical Sciences",
        "department_th": "สาขาวิชาวิทยาศาสตร์ชีวการแพทย์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "3 ปี",
        "total_credits": "48 หน่วยกิต",
        "tuition_per_semester": "50,000 บาท",
        "tuition_total": "300,000 บาท",
        "description": "สร้างนักวิจัยระดับปริญญาเอกเพื่อผลิตงานวิจัยขั้นแนวหน้าด้านชีวการแพทย์ การค้นพบตัวยา การบำบัดด้วยยีนและเซลล์ต้นกำเนิด",
        "curriculum_highlights": ["การค้นพบและทดสอบฤทธิ์ยาต้านมะเร็งและโรคติดเชื้อ", "การใช้เทคโนโลยี Genomic และ Proteomic ในการแพทย์แม่นยำ (Precision Medicine)", "การเผยแพร่ผลงานในวารสารวิชาการชั้นนำระดับ Q1/Q2"],
        "career_paths": ["นักวิจัยหลังปริญญาเอกและหัวหน้าโครงการวิจัย", "อาจารย์แพทย์และนักวิชาการระดับสากล", "ผู้เชี่ยวชาญด้าน R&D ชีวเภสัชภัณฑ์"],
        "tags": ["Biomedical Sciences", "Precision Medicine", "Cancer Research", "Ph.D."],
        "website_url": "https://medinfo.psu.ac.th"
    },
    {
        "id": "psu_med_mph_epidemiology",
        "title_th": "หลักสูตรสาธารณสุขศาสตรมหาบัณฑิต สาขาวิชาวิทยาการระบาด (หลักสูตรนานาชาติ)",
        "title_en": "Master of Public Health Program in Epidemiology (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "ส.ม. (วิทยาการระบาด)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Epidemiology Unit",
        "department_th": "หน่วยระบาดวิทยาคลินิก",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "180,000 บาท",
        "description": "ศูนย์กลางการเรียนการสอนด้านระบาดวิทยาชั้นนำของเอเชียตะวันออกเฉียงใต้ เน้นการวิเคราะห์ข้อมูลสุขภาพประชากร การออกแบบการวิจัยทางคลินิก และการประเมินนโยบายสุขภาพ",
        "curriculum_highlights": ["การวิเคราะห์ข้อมูลระบาดวิทยาขั้นสูงด้วยภาษา R และ Stata", "การวิจัยควบคุมโรคระบาดและโรคติดต่อข้ามพรมแดน", "การเรียนร่วมกับนักศึกษาและผู้เชี่ยวชาญจากนานาชาติ"],
        "career_paths": ["นักระบาดวิทยาประจำกระทรวงสาธารณสุขหรือองค์กรระหว่างประเทศ (WHO, CDC)", "นักสถิติชีวภาพและนักวิจัยคลินิก", "ผู้บริหารนโยบายสุขภาพ"],
        "tags": ["Epidemiology", "Public Health", "Biostatistics", "Clinical Research"],
        "website_url": "https://mediinfo.psu.ac.th/epidemiology"
    },
    # --- คณะทันตแพทยศาสตร์ (Faculty of Dentistry) ---
    {
        "id": "psu_dent_dds",
        "title_th": "หลักสูตรทันตแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Dental Surgery Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ท.บ. (ทันตแพทยศาสตรบัณฑิต)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Dentistry",
        "department_th": "สาขาวิชาทันตแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "236 หน่วยกิต",
        "tuition_per_semester": "30,000 บาท",
        "tuition_total": "360,000 บาท",
        "description": "ผลิตทันตแพทย์ที่มีความเป็นเลิศทางวิชาการ มีทักษะคลินิกทันตกรรมครบวงจร และมุ่งเน้นการส่งเสริมสุขภาพช่องปากของประชาชนในภูมิภาค",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิกทันตกรรม ณ โรงพยาบาลทันตกรรม ม.อ.", "การใช้เทคโนโลยี Digital Dentistry และ CAD/CAM ในการรักษา", "ทันตกรรมชุมชนและการดูแลผู้ป่วยกลุ่มเปราะบาง"],
        "career_paths": ["ทันตแพทย์ในโรงพยาบาลรัฐและเอกชน", "ทันตแพทย์เฉพาะทาง", "เจ้าของคลินิกทันตกรรม", "อาจารย์ทันตแพทย์"],
        "tags": ["Dentistry", "Dental", "Doctor of Dental Surgery", "PSU Dentistry"],
        "website_url": "https://dent.psu.ac.th"
    },
    # --- คณะเภสัชศาสตร์ (Faculty of Pharmaceutical Sciences) ---
    {
        "id": "psu_pharm_bpharm_care",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาการบริบาลทางเภสัชกรรม",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Care",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (การบริบาลทางเภสัชกรรม)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Pharmaceutical Sciences",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Clinical Pharmacy",
        "department_th": "ภาควิชาเภสัชกรรมคลินิก",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "225 หน่วยกิต",
        "tuition_per_semester": "25,000 บาท",
        "tuition_total": "300,000 บาท",
        "description": "เน้นการผลิตเภสัชกรคลินิกผู้เชี่ยวชาญการใช้ยาในผู้ป่วย การติดตามความปลอดภัยของยา และการให้คำปรึกษาด้านการใช้ยาอย่างสมเหตุผล",
        "curriculum_highlights": ["การฝึกปฏิบัติงานบริบาลทางเภสัชกรรมในหอผู้ป่วยโรงพยาบาลสงขลานครินทร์", "การประเมินการใช้ยาและเภสัชวิทยาคลินิกขั้นสูง", "เภสัชพันธุศาสตร์เพื่อการรักษาเฉพาะบุคคล"],
        "career_paths": ["เภสัชกรประจำโรงพยาบาล", "เภสัชกรคลินิกเฉพาะทาง", "เภสัชกรชุมชน (ร้านยา)", "เภสัชกรวิชาการและวิจัย"],
        "tags": ["Pharmacy", "Pharmaceutical Care", "Clinical Pharmacy", "Health"],
        "website_url": "https://pharmacy.psu.ac.th"
    },
    {
        "id": "psu_pharm_bpharm_sci",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์เภสัชกรรม",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Sciences",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (วิทยาศาสตร์เภสัชกรรม)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Pharmaceutical Sciences",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Pharmaceutical Technology",
        "department_th": "ภาควิชาเทคโนโลยีเภสัชกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "225 หน่วยกิต",
        "tuition_per_semester": "25,000 บาท",
        "tuition_total": "300,000 บาท",
        "description": "มุ่งเน้นการวิจัย พัฒนา และผลิตยา เครื่องสำอาง และผลิตภัณฑ์ธรรมชาติ การควบคุมคุณภาพตามมาตรฐาน GMP และการขึ้นทะเบียนยา",
        "curriculum_highlights": ["การออกแบบและพัฒนาสูตรตำรับยาและเครื่องสำอาง", "การวิเคราะห์และควบคุมคุณภาพยาขั้นสูง (HPLC, LC-MS)", "การสกัดสารออกฤทธิ์ทางชีวภาพจากสมุนไพรและทรัพยากรทางทะเล"],
        "career_paths": ["เภสัชกร R&D ในโรงงานผลิตยาและเครื่องสำอาง", "เภสัชกรฝ่ายผลิตและควบคุมคุณภาพ (QA/QC)", "เภสัชกรฝ่ายขึ้นทะเบียนยา (Regulatory Affairs)"],
        "tags": ["Pharmaceutical Sciences", "Drug Development", "Cosmetics", "GMP"],
        "website_url": "https://pharmacy.psu.ac.th"
    },
    # --- คณะวิศวกรรมศาสตร์ (Faculty of Engineering - Hat Yai) ---
    {
        "id": "psu_eng_beng_ai_computer",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมปัญญาประดิษฐ์และคอมพิวเตอร์",
        "title_en": "Bachelor of Engineering Program in Artificial Intelligence and Computer Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมปัญญาประดิษฐ์และคอมพิวเตอร์)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Computer Engineering",
        "department_th": "ภาควิชาวิศวกรรมคอมพิวเตอร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "135 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "176,000 บาท",
        "description": "ผลิตวิศวกรผู้เชี่ยวชาญด้านปัญญาประดิษฐ์ การเรียนรู้ของเครื่อง (Machine Learning), Data Engineering, IoT และการพัฒนาระบบซอฟต์แวร์อัจฉริยะ",
        "curriculum_highlights": ["การประยุกต์ใช้ Generative AI, Computer Vision และ NLP", "การออกแบบสถาปัตยกรรมคลาวด์และระบบประมวลผลประสิทธิภาพสูง", "การทำโครงงานวิศวกรรมร่วมกับองค์กรเทคโนโลยีชั้นนำ"],
        "career_paths": ["AI / Machine Learning Engineer", "Software Engineer", "Data Engineer", "Cloud Solutions Architect"],
        "tags": ["Artificial Intelligence", "AI", "Computer Engineering", "Machine Learning", "Software"],
        "website_url": "https://eng.psu.ac.th"
    },
    {
        "id": "psu_eng_beng_civil",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมโยธา",
        "title_en": "Bachelor of Engineering Program in Civil Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมโยธา)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Civil Engineering",
        "department_th": "ภาควิชาวิศวกรรมโยธา",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "ครอบคลุมการออกแบบโครงสร้าง วิศวกรรมปฐพี วิศวกรรมแหล่งน้ำ วิศวกรรมขนส่ง และการบริหารงานก่อสร้างอาคารและโครงสร้างพื้นฐานขนาดใหญ่",
        "curriculum_highlights": ["การจำลองสารสนเทศอาคาร (BIM) และการจัดการโครงการดิจิทัล", "การวิเคราะห์โครงสร้างต้านทานแผ่นดินไหวและแรงลม", "การฝึกภาคสนามและการสำรวจภูมิประเทศจริง"],
        "career_paths": ["วิศวกรโยธาและวิศวกรโครงสร้าง", "วิศวกรควบคุมงานและบริหารโครงการก่อสร้าง", "วิศวกรสำรวจและวิศวกรธรณีเทคนิค"],
        "tags": ["Civil Engineering", "Structural Engineering", "BIM", "Construction"],
        "website_url": "https://civil.eng.psu.ac.th"
    },
    {
        "id": "psu_eng_beng_mechanical",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเครื่องกล",
        "title_en": "Bachelor of Engineering Program in Mechanical Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมเครื่องกล)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Mechanical Engineering",
        "department_th": "ภาควิชาวิศวกรรมเครื่องกล",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "142 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "เน้นกลศาสตร์ของแข็ง อุณหพลศาสตร์ กลศาสตร์ของไหล ระบบทำความเย็น ยานยนต์ไฟฟ้า (EV) และระบบอัตโนมัติ",
        "curriculum_highlights": ["การวิเคราะห์และออกแบบด้วย CAD/CAM/CAE และ CFD", "เทคโนโลยียานยนต์ไฟฟ้าและระบบกักเก็บพลังงาน", "การอนุรักษ์พลังงานในภาคอุตสาหกรรมและอาคาร"],
        "career_paths": ["วิศวกรเครื่องกลและวิศวกรออกแบบระบบ", "วิศวกรยานยนต์และยานยนต์ไฟฟ้า", "วิศวกรพลังงานและระบบปรับอากาศ"],
        "tags": ["Mechanical Engineering", "EV", "Thermodynamics", "Energy"],
        "website_url": "https://me.eng.psu.ac.th"
    },
    {
        "id": "psu_eng_beng_chemical",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเคมี",
        "title_en": "Bachelor of Engineering Program in Chemical Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมเคมี)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Chemical Engineering",
        "department_th": "ภาควิชาวิศวกรรมเคมี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "140 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "มุ่งเน้นการออกแบบและควบคุมกระบวนการผลิตทางเคมี ปิโตรเคมี พลังงานชีวภาพ ปาล์มน้ำมัน ยางพารา และกระบวนการคาร์บอนต่ำ",
        "curriculum_highlights": ["การออกแบบโรงงานและกระบวนการผลิตด้วย Aspen Plus", "เทคโนโลยีการแปรรูปยางพาราและปาล์มน้ำมันมูลค่าสูง", "ความปลอดภัยในโรงงานอุตสาหกรรมเคมีและสิ่งแวดล้อม"],
        "career_paths": ["วิศวกรกระบวนการผลิต (Process Engineer)", "วิศวกรปิโตรเคมีและพลังงาน", "วิศวกรความปลอดภัยและสิ่งแวดล้อม"],
        "tags": ["Chemical Engineering", "Process Engineering", "Petrochemical", "Biomass"],
        "website_url": "https://chemeng.eng.psu.ac.th"
    },
    {
        "id": "psu_eng_beng_mechatronics",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเมคาทรอนิกส์และหุ่นยนต์",
        "title_en": "Bachelor of Engineering Program in Mechatronics and Robotics Engineering",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมเมคาทรอนิกส์และหุ่นยนต์)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Mechatronics Engineering",
        "department_th": "สาขาวิชาวิศวกรรมเมคาทรอนิกส์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "176,000 บาท",
        "description": "บูรณาการศาสตร์เครื่องกล ไฟฟ้า อิเล็กทรอนิกส์ และวิทยาการคอมพิวเตอร์ เพื่อพัฒนาระบบอัตโนมัติ หุ่นยนต์อุตสาหกรรม และสมาร์ทแฟคทอรี",
        "curriculum_highlights": ["การโปรแกรม PLC, SCADA และแขนกลหุ่นยนต์อุตสาหกรรม", "การพัฒนาระบบสมองกลฝังตัวและเซนเซอร์อัจฉริยะ", "ระบบอัตโนมัติในกระบวนการผลิตอัจฉริยะ (Smart Manufacturing)"],
        "career_paths": ["วิศวกรระบบอัตโนมัติและหุ่นยนต์ (Automation Engineer)", "วิศวกรเมคาทรอนิกส์", "System Integrator"],
        "tags": ["Mechatronics", "Robotics", "Automation", "PLC", "Smart Factory"],
        "website_url": "https://eng.psu.ac.th"
    },
    {
        "id": "psu_eng_msc_ai",
        "title_th": "หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมปัญญาประดิษฐ์และระบบอัตโนมัติ",
        "title_en": "Master of Engineering Program in Artificial Intelligence and Automation Engineering",
        "degree_level": "ปริญญาโท",
        "degree_name": "วศ.ม. (วิศวกรรมปัญญาประดิษฐ์และระบบอัตโนมัติ)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Computer Engineering",
        "department_th": "ภาควิชาวิศวกรรมคอมพิวเตอร์",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "32,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "การศึกษาวิจัยขั้นสูงด้านการประยุกต์ใช้ AI ในภาคอุตสาหกรรม การแพทย์ เกษตรแม่นยำ และระบบอัตโนมัติขั้นสูง",
        "curriculum_highlights": ["การวิจัย Deep Learning, Computer Vision และ NLP เชิงประยุกต์", "การพัฒนาระบบ AI บนอุปกรณ์ Edge และ IoT", "การทำวิจัยร่วมกับเครือข่ายอุตสาหกรรมและโรงพยาบาล ม.อ."],
        "career_paths": ["AI Researcher & Lead Engineer", "Data Science Architect", "อาจารย์และนักวิจัยวิศวกรรมศาสตร์"],
        "tags": ["Artificial Intelligence", "AI", "Master of Engineering", "Automation"],
        "website_url": "https://eng.psu.ac.th"
    },
    {
        "id": "psu_eng_phd_civil",
        "title_th": "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาวิศวกรรมโยธา (หลักสูตรนานาชาติ)",
        "title_en": "Doctor of Philosophy Program in Civil Engineering (International Program)",
        "degree_level": "ปริญญาเอก",
        "degree_name": "ปร.ด. (วิศวกรรมโยธา)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Civil Engineering",
        "department_th": "ภาควิชาวิศวกรรมโยธา",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "3 ปี",
        "total_credits": "48 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "270,000 บาท",
        "description": "สร้างนักวิจัยระดับปริญญาเอกในการแก้ปัญหาทางวิศวกรรมโยธาขั้นสูง วัสดุก่อสร้างคาร์บอนต่ำ การกัดเซาะชายฝั่ง และภัยพิบัติทางธรรมชาติ",
        "curriculum_highlights": ["การวิจัยวิศวกรรมชายฝั่งและโครงสร้างต้านทานภัยธรรมชาติ", "การพัฒนาคอนกรีตสีเขียวและวัสดุจีโอโพลิเมอร์", "การตีพิมพ์ในวารสารวิศวกรรมโยธาระดับนานาชาติ"],
        "career_paths": ["ผู้เชี่ยวชาญวิศวกรรมโยธาระดับสูง", "อาจารย์และนักวิจัยมหาวิทยาลัย", "ที่ปรึกษาโครงสร้างพื้นฐานระดับชาติ"],
        "tags": ["Civil Engineering", "Coastal Engineering", "Ph.D.", "Structures"],
        "website_url": "https://civil.eng.psu.ac.th"
    },
    # --- คณะวิทยาศาสตร์ (Faculty of Science - Hat Yai) ---
    {
        "id": "psu_sci_bsc_marine_science",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์ทางทะเลและสิ่งแวดล้อมชายฝั่ง",
        "title_en": "Bachelor of Science Program in Marine and Coastal Sciences",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาศาสตร์ทางทะเลและสิ่งแวดล้อมชายฝั่ง)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Science",
        "faculty_th": "คณะวิทยาศาสตร์",
        "department": "Department of Biology",
        "department_th": "สาขาวิทยาศาสตร์ทางทะเล",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "ศูนย์กลางการศึกษาชีววิทยาทางทะเลชั้นนำของประเทศ ศึกษานิเวศวิทยาแนวปะการัง ทรัพยากรประมง สมุทรศาสตร์ และการอนุรักษ์ทะเลทั้งฝั่งอ่าวไทยและอันดามัน",
        "curriculum_highlights": ["การฝึกภาคสนามทางทะเล ณ สถานีวิจัยและเรือสำรวจทางทะเล ม.อ.", "การศึกษานิเวศวิทยาแนวปะการังและหญ้าทะเล", "การดำน้ำทางวิทยาศาสตร์ (Scientific Diving) และการอนุรักษ์สัตว์ทะเลหายาก"],
        "career_paths": ["นักวิทยาศาสตร์ทางทะเลประจำกรมทรัพยากรทางทะเลและชายฝั่ง", "นักวิจัยสิ่งแวดล้อมทางทะเล", "ผู้เชี่ยวชาญด้านการเพาะเลี้ยงสัตว์น้ำและการอนุรักษ์"],
        "tags": ["Marine Science", "Oceanography", "Coral Reef", "Marine Biology"],
        "website_url": "https://sci.psu.ac.th"
    },
    {
        "id": "psu_sci_bsc_data_science",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการข้อมูลและการวิเคราะห์",
        "title_en": "Bachelor of Science Program in Data Science and Analytics",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาการข้อมูลและการวิเคราะห์)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Science",
        "faculty_th": "คณะวิทยาศาสตร์",
        "department": "Department of Mathematics and Statistics",
        "department_th": "ภาควิชาคณิตศาสตร์และสถิติ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "ผสานสถิติศาสตร์ คณิตศาสตร์เชิงคำนวณ และวิทยาการคอมพิวเตอร์ เพื่อการสกัดอินไซต์จากข้อมูลขนาดใหญ่ การทำ Data Visualization และ Machine Learning",
        "curriculum_highlights": ["การเขียนโปรแกรม Python/R สำหรับการวิเคราะห์ Big Data", "การสร้างแบบจำลองสถิติเชิงคาดการณ์และ Machine Learning", "โครงงาน Data Analytics ร่วมกับภาคธุรกิจและการเงิน"],
        "career_paths": ["Data Scientist", "Data Analyst", "Business Intelligence Developer", "Machine Learning Specialist"],
        "tags": ["Data Science", "Analytics", "Statistics", "Machine Learning", "Big Data"],
        "website_url": "https://sci.psu.ac.th"
    },
    {
        "id": "psu_sci_phd_marine",
        "title_th": "หลักสูตรปรัชญาดุษฎีบัณฑิต สาขาวิชาวิทยาศาสตร์ทางทะเล (หลักสูตรนานาชาติ)",
        "title_en": "Doctor of Philosophy Program in Marine Science (International Program)",
        "degree_level": "ปริญญาเอก",
        "degree_name": "ปร.ด. (วิทยาศาสตร์ทางทะเล)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Science",
        "faculty_th": "คณะวิทยาศาสตร์",
        "department": "Department of Marine Science",
        "department_th": "สาขาวิทยาศาสตร์ทางทะเล",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "3 ปี",
        "total_credits": "48 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "270,000 บาท",
        "description": "การวิจัยขั้นสูงด้านสมุทรศาสตร์เคมี กายภาพ และชีววิทยา การเปลี่ยนแปลงสภาพภูมิอากาศต่อมหาสมุทร และการฟื้นฟูระบบนิเวศทางทะเล",
        "curriculum_highlights": ["การวิจัยนิเวศวิทยาทางทะเลระดับสากล", "การวิเคราะห์ผลกระทบของไมโครพลาสติกและสารมลพิษในทะเล", "การร่วมมือกับเครือข่ายวิจัยทางทะเลระดับโลก"],
        "career_paths": ["นักวิจัยสมุทรศาสตร์และวิทยาศาสตร์ทางทะเลระดับสากล", "อาจารย์มหาวิทยาลัย", "ที่ปรึกษาองค์กรสิ่งแวดล้อมสากล (IUCN, WWF, UNEP)"],
        "tags": ["Marine Science", "Oceanography", "Ph.D.", "Marine Ecology"],
        "website_url": "https://sci.psu.ac.th"
    },
    # --- คณะอุตสาหกรรมเกษตร (Faculty of Agro-Industry) ---
    {
        "id": "psu_agro_bsc_food_science",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์และเทคโนโลยีอาหาร",
        "title_en": "Bachelor of Science Program in Food Science and Technology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (วิทยาศาสตร์และเทคโนโลยีอาหาร)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Agro-Industry",
        "faculty_th": "คณะอุตสาหกรรมเกษตร",
        "department": "Department of Food Technology",
        "department_th": "ภาควิชาเทคโนโลยีอาหาร",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "เน้นการแปรรูปสัตว์น้ำ อาหารทะเล อาหารฮาลาล และผลิตภัณฑ์เกษตรภาคใต้ การพัฒนาผลิตภัณฑ์อาหารแห่งอนาคต และความปลอดภัยทางอาหารระดับสากล",
        "curriculum_highlights": ["ความเป็นเลิศด้านการแปรรูปอาหารทะเลและผลิตภัณฑ์สัตว์น้ำ", "มาตรฐานอาหารฮาลาล (Halal Food Standards) และการรับรองสากล", "การฝึกปฏิบัติการในโรงงานต้นแบบแปรรูปอาหาร (Pilot Plant)"],
        "career_paths": ["นักวิทยาศาสตร์อาหารและพัฒนาผลิตภัณฑ์ (Food R&D)", "ผู้ควบคุมคุณภาพและความปลอดภัยอาหาร (QA/QC)", "ผู้ตรวจประเมินมาตรฐานอาหารและฮาลาล"],
        "tags": ["Food Science", "Food Technology", "Halal Food", "Seafood Processing"],
        "website_url": "https://agro.psu.ac.th"
    },
    # --- วิทยาเขตภูเก็ต (Phuket Campus - Computing & Hospitality) ---
    {
        "id": "psu_coc_bsc_digital_engineering",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมดิจิทัล (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Engineering Program in Digital Engineering (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมดิจิทัล)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "College of Computing, Phuket Campus",
        "faculty_th": "วิทยาลัยการคอมพิวเตอร์ วิทยาเขตภูเก็ต",
        "department": "Department of Digital Engineering",
        "department_th": "สาขาวิชาวิศวกรรมดิจิทัล",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "360,000 บาท",
        "description": "เรียนรู้การพัฒนาซอฟต์แวร์ระดับสากล IoT, Smart City, ปัญญาประดิษฐ์ และระบบความปลอดภัยไซเบอร์ บนเกาะภูเก็ตเมืองศูนย์กลางนวัตกรรมดิจิทัล",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษ 100% กับคณาจารย์และนักศึกษานานาชาติ", "การพัฒนาโซลูชัน Smart Tourism และ Smart Island Phuket", "การฝึกสหกิจศึกษากับบริษัทเทคโนโลยีข้ามชาติ"],
        "career_paths": ["International Software Engineer", "IoT & Embedded Developer", "Cybersecurity Specialist", "Digital Solutions Consultant"],
        "tags": ["Digital Engineering", "Computing", "Phuket", "Smart City", "International"],
        "website_url": "https://computing.psu.ac.th"
    },
    {
        "id": "psu_fht_bba_intl_hospitality",
        "title_th": "หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาการจัดการการบริการและการท่องเที่ยว (หลักสูตรนานาชาติ)",
        "title_en": "Bachelor of Business Administration Program in Hospitality and Tourism Management (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ. (การจัดการการบริการและการท่องเที่ยว)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Hospitality and Tourism, Phuket Campus",
        "faculty_th": "คณะการบริการและการท่องเที่ยว วิทยาเขตภูเก็ต",
        "department": "Department of Hospitality",
        "department_th": "สาขาวิชาการบริการและการท่องเที่ยว",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "42,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "หลักสูตรการโรงแรมและการท่องเที่ยวชั้นนำในภูเก็ต ศูนย์กลางการท่องเที่ยวระดับโลก เน้นการบริหารโรงแรมหรู การจัดอีเวนต์ระดับโลก และการบริหารสายการบิน",
        "curriculum_highlights": ["การฝึกงานกับเครือโรงแรม 5 ดาวระดับโลกในภูเก็ตและต่างประเทศ (Marriott, Accor, Hilton)", "การเรียนรู้มาตรฐานสากล UNWTO.TedQual", "ภาษาอังกฤษและภาษาที่สาม (จีน, รัสเซีย, ญี่ปุ่น)"],
        "career_paths": ["ผู้บริหารในเครือโรงแรมและรีสอร์ตระดับ 5 ดาว", "ผู้จัดการฝ่ายอีเวนต์และการท่องเที่ยวไมซ์ (MICE)", "ผู้บริหารสายการบินและธุรกิจบริการระดับพรีเมียม"],
        "tags": ["Hospitality", "Tourism Management", "Phuket", "Hotel Management", "International"],
        "website_url": "https://fht.psu.ac.th"
    },
    # --- คณะพยาบาลศาสตร์ (Faculty of Nursing) ---
    {
        "id": "psu_nurs_bns",
        "title_th": "หลักสูตรพยาบาลศาสตรบัณฑิต",
        "title_en": "Bachelor of Nursing Science Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พย.บ. (พยาบาลศาสตรบัณฑิต)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Nursing",
        "faculty_th": "คณะพยาบาลศาสตร์",
        "department": "Department of Nursing",
        "department_th": "สาขาวิชาพยาบาลศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "ผลิตพยาบาลวิชาชีพชั้นนำที่มีสมรรถนะสูง มีทักษะการพยาบาลแบบพหุวัฒนธรรม และการดูแลผู้ป่วยวิกฤตและผู้ป่วยเรื้อรัง",
        "curriculum_highlights": ["การฝึกปฏิบัติการพยาบาลในโรงพยาบาลสงขลานครินทร์และเครือข่ายโรงพยาบาลภาคใต้", "การพยาบาลในบริบทพหุวัฒนธรรมภาคใต้", "ห้องปฏิบัติการพยาบาลเสมือนจริงมาตรฐานสากล"],
        "career_paths": ["พยาบาลวิชาชีพในโรงพยาบาลชั้นนำ", "พยาบาลเฉพาะทาง", "พยาบาลประจำองค์กรต่างประเทศ"],
        "tags": ["Nursing", "Nurse", "Health Care", "Multicultural Care"],
        "website_url": "https://nurse.psu.ac.th"
    },
    {
        "id": "psu_nurs_mns_advanced",
        "title_th": "หลักสูตรพยาบาลศาสตรมหาบัณฑิต สาขาวิชาการพยาบาลผู้ใหญ่และผู้สูงอายุ (หลักสูตรนานาชาติ)",
        "title_en": "Master of Nursing Science Program in Adult and Gerontological Nursing (International Program)",
        "degree_level": "ปริญญาโท",
        "degree_name": "พย.ม. (การพยาบาลผู้ใหญ่และผู้สูงอายุ)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Nursing",
        "faculty_th": "คณะพยาบาลศาสตร์",
        "department": "Department of Nursing",
        "department_th": "สาขาวิชาพยาบาลศาสตร์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "180,000 บาท",
        "description": "พัฒนาพยาบาลผู้เชี่ยวชาญระดับสูง (APN) ในการดูแลผู้ป่วยผู้ใหญ่และผู้สูงอายุที่มีภาวะโรคซับซ้อนและการวิจัยเพื่อพัฒนาคุณภาพการบริบาลพยาบาล",
        "curriculum_highlights": ["การพยาบาลขั้นสูงในภาวะวิกฤตและโรคเรื้อรังซับซ้อน", "การวิจัยทางคลินิกเพื่อพัฒนานวัตกรรมการพยาบาล", "การแลกเปลี่ยนทางวิชาการกับสถาบันพยาบาลชั้นนำระดับโลก"],
        "career_paths": ["พยาบาลผู้ปฏิบัติการพยาบาลขั้นสูง (APN)", "ผู้บริหารการพยาบาล", "อาจารย์และนักวิจัยพยาบาล"],
        "tags": ["Nursing", "Advanced Practice Nursing", "Gerontology", "Master of Nursing"],
        "website_url": "https://nurse.psu.ac.th"
    },
    # --- คณะวิทยาการจัดการ (Faculty of Management Sciences - Hat Yai) ---
    {
        "id": "psu_fms_bba_logistics",
        "title_th": "หลักสูตรบริหารธุรกิจบัณฑิต สาขาวิชาการจัดการโลจิสติกส์และโซ่อุปทาน",
        "title_en": "Bachelor of Business Administration Program in Logistics and Supply Chain Management",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ. (การจัดการโลจิสติกส์และโซ่อุปทาน)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "Department of Business Administration",
        "department_th": "สาขาวิชาบริหารธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "เน้นการบริหารจัดการโลจิสติกส์การค้าข้ามพรมแดน (ไทย-มาเลเซีย-สิงคโปร์) การจัดการคลังสินค้าอัจฉริยะ และการขนส่งต่อเนื่องหลายรูปแบบ",
        "curriculum_highlights": ["ยุทธศาสตร์โลจิสติกส์เชื่อมโยงระเบียงเศรษฐกิจภาคใต้ (SEC) และอาเซียน", "การใช้ซอฟต์แวร์ ERP และระบบบริหารจัดการคลังสินค้า (WMS)", "การฝึกงานกับบริษัทโลจิสติกส์และสายการเดินเรือระหว่างประเทศ"],
        "career_paths": ["ผู้จัดการฝ่ายโลจิสติกส์และซัพพลายเชน", "นักวิเคราะห์การขนส่งและจัดซื้อระหว่างประเทศ", "ผู้ประกอบการธุรกิจโลจิสติกส์และคลังสินค้า"],
        "tags": ["Logistics", "Supply Chain", "Cross-Border Trade", "Business"],
        "website_url": "https://fms.psu.ac.th"
    },
    {
        "id": "psu_fms_mba",
        "title_th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต (MBA)",
        "title_en": "Master of Business Administration Program (MBA)",
        "degree_level": "ปริญญาโท",
        "degree_name": "บธ.ม. (บริหารธุรกิจ)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Management Sciences",
        "faculty_th": "คณะวิทยาการจัดการ",
        "department": "Department of Business Administration",
        "department_th": "สาขาวิชาบริหารธุรกิจ",
        "program_type": "ภาคปกติ / ภาคพิเศษ (วันเสาร์-อาทิตย์)",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "35,000 บาท",
        "tuition_total": "140,000 บาท",
        "description": "พัฒนาผู้นำองค์กรและผู้ประกอบการยุคใหม่ที่มีทักษะการตัดสินใจเชิงกลยุทธ์ การตลาดดิจิทัล การเงินธุรกิจ และการขับเคลื่อนธุรกิจด้วยนวัตกรรม",
        "curriculum_highlights": ["การวิเคราะห์กรณีศึกษาธุรกิจจริง (Business Case Studies)", "กลยุทธ์การปรับเปลี่ยนธุรกิจสู่ดิจิทัล (Digital Transformation)", "เครือข่ายผู้บริหารและศิษย์เก่าผู้นำธุรกิจภาคใต้"],
        "career_paths": ["ผู้บริหารระดับสูงในองค์กรธุรกิจ", "ผู้ประกอบการและผู้ก่อตั้งสตาร์ทอัพ", "ที่ปรึกษาการจัดการและกลยุทธ์ธุรกิจ"],
        "tags": ["MBA", "Business Administration", "Leadership", "Management"],
        "website_url": "https://fms.psu.ac.th"
    },
    # --- คณะนิติศาสตร์ (Faculty of Law) ---
    {
        "id": "psu_law_llb",
        "title_th": "หลักสูตรนิติศาสตรบัณฑิต",
        "title_en": "Bachelor of Laws Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "น.บ. (นิติศาสตรบัณฑิต)",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Law",
        "faculty_th": "คณะนิติศาสตร์",
        "department": "Department of Law",
        "department_th": "สาขาวิชานิติศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "ผลิตนักกฎหมายที่มีความแม่นยำในตัวบทกฎหมายและหลักนิติธรรม มีความรู้เฉพาะทางด้านกฎหมายการค้าชายแดน กฎหมายทะเล และกฎหมายอิสลาม",
        "curriculum_highlights": ["การฝึกปฏิบัติศาลจำลอง (Moot Court) และคลินิกกฎหมายชุมชน", "ความเชี่ยวชาญด้านกฎหมายการค้าชายแดนและกฎหมายทรัพย์สินทางปัญญา", "กฎหมายอิสลามและกฎหมายครอบครัวมรดกอิสลามในจังหวัดชายแดนภาคใต้"],
        "career_paths": ["ผู้พิพากษาและพนักงานอัยการ", "ทนายความและที่ปรึกษากฎหมายธุรกิจ", "นิติกรประจำหน่วยงานรัฐและเอกชน"],
        "tags": ["Law", "LLB", "Legal Studies", "Border Trade Law"],
        "website_url": "https://law.psu.ac.th"
    },
]
