# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/public_health_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "mahidoluni_facultyofp_lahaudomchok_001",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "department_th": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Visanti",
    "last_name": "Lahaudomchok",
    "full_name": "Visanti Lahaudomchok",
    "full_name_th": "ดร. วิสันติ เลาหอุดมโชค",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "อาชีวอนามัยและความปลอดภัย"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_phungrassamee_002",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "department_th": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Wantanee",
    "last_name": "Phungrassamee",
    "full_name": "Wantanee Phungrassamee",
    "full_name_th": "รศ.ดร. วันทนี พันธุ์ประสิทธิ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "อาชีวอนามัยและความปลอดภัย"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_arporn_003",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "department_th": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Sara",
    "last_name": "Arporn",
    "full_name": "Sara Arporn",
    "full_name_th": "รศ.ดร. สรา อาภรณ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "อาชีวอนามัยและความปลอดภัย"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_thangthong_004",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "department_th": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Chainan",
    "last_name": "Thangthong",
    "full_name": "Chainan Thangthong",
    "full_name_th": "ผศ.ดร. ไชยนันต์ แท่งทอง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "อาชีวอนามัยและความปลอดภัย"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_nankong_005",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "department_th": "ภาควิชาอาชีวอนามัยและความปลอดภัย",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Nopanan",
    "last_name": "Nankong",
    "full_name": "Nopanan Nankong",
    "full_name_th": "ผศ.ดร. นพนันท์ นานคง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "อาชีวอนามัยและความปลอดภัย"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_siri_006",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาระบาดวิทยา",
    "department_th": "ภาควิชาระบาดวิทยา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sukontha",
    "last_name": "Siri",
    "full_name": "Sukontha Siri",
    "full_name_th": "ผศ.ดร. สุคนธา ศิริ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ระบาดวิทยา"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_chanchorn_007",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Jiraphan",
    "last_name": "Chanchorn",
    "full_name": "Jiraphan Chanchorn",
    "full_name_th": "ผศ.ดร. จิรพันธุ์ จันทร์จร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_pattanaissaranu_008",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาวิทยาศาสตร์อนามัยสิ่งแวดล้อม",
    "department_th": "ภาควิชาวิทยาศาสตร์อนามัยสิ่งแวดล้อม",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Withida",
    "last_name": "Pattanaissaranukul",
    "full_name": "Withida Pattanaissaranukul",
    "full_name_th": "รศ.ดร. วิธิดา พัฒนอิสรานุกูล",
    "role": "อาจารย์ประจำ",
    "email": "withida.pat@mahidol.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "วิทยาศาสตร์อนามัยสิ่งแวดล้อม"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_panyapinyopol_009",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาวิศวกรรมสุขาภิบาล",
    "department_th": "ภาควิชาวิศวกรรมสุขาภิบาล",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Boonyarith",
    "last_name": "Panyapinyopol",
    "full_name": "Boonyarith Panyapinyopol",
    "full_name_th": "รศ.ดร. บุณยฤทธิ์ ปัญญาภิญโญผล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "วิศวกรรมสุขาภิบาล"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_nontarak_010",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาระบาดวิทยา",
    "department_th": "ภาควิชาระบาดวิทยา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Jiraluck",
    "last_name": "Nontarak",
    "full_name": "Jiraluck Nontarak",
    "full_name_th": "ผศ.ดร. จิราลักษณ์ นนทารักษ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ระบาดวิทยา"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_singweratham_011",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชากายภาพบำบัด",
    "department_th": "ภาควิชากายภาพบำบัด",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Napacha",
    "last_name": "Singweratham",
    "full_name": "Napacha Singweratham",
    "full_name_th": "อ. นภชา สิงห์วีรธรรม",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_naksen_012",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "คณะสาธารณสุขศาสตร์",
    "department_th": "คณะสาธารณสุขศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Varangkana",
    "last_name": "Naksen",
    "full_name": "Varangkana Naksen",
    "full_name_th": "ผศ.ดร. วรางคณา นาคเสน",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "การแก้ไขปัญหาสารโลหะหนักปนเปื้อน"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_utrarachkij_013",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "คณะสาธารณสุขศาสตร์ มหาวิทยาลัยมหิดล",
    "department_th": "คณะสาธารณสุขศาสตร์ มหาวิทยาลัยมหิดล",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Fuangfa",
    "last_name": "Utrarachkij",
    "full_name": "Fuangfa Utrarachkij",
    "full_name_th": "รศ.ดร. เฟื่องฟ้า อุตรารัชต์กิจ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_mahikul_014",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "วิทยาลัยแพทยศาสตร์ศรีสวางควัฒน ราชวิทยาลัย",
    "department_th": "วิทยาลัยแพทยศาสตร์ศรีสวางควัฒน ราชวิทยาลัย",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Viriya",
    "last_name": "Mahikul",
    "full_name": "Viriya Mahikul",
    "full_name_th": "รศ.ดร. วิริยะ มหิกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_manowan_016",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "ภาควิชาบริหารงานสาธารณสุข",
    "department_th": "ภาควิชาบริหารงานสาธารณสุข",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Duangsamorn",
    "last_name": "Manowan",
    "full_name": "Duangsamorn Manowan",
    "full_name_th": "ผศ.ดร. ดวงสมร มะโนวรรณ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_singhalaseng_017",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Attawit",
    "last_name": "Singhalaseng",
    "full_name": "Attawit Singhalaseng",
    "full_name_th": "รศ.ดร. อรรถวิทย์ สิงห์ศาลาแสง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_eksanti_018",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Thawatchai",
    "last_name": "Eksanti",
    "full_name": "Thawatchai Eksanti",
    "full_name_th": "ผศ.ดร. ธวัชชัย เอกสันติ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_kanjanasura_019",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Suwimol",
    "last_name": "Kanjanasura",
    "full_name": "Suwimol Kanjanasura",
    "full_name_th": "รศ.ดร. สุวิมล กาญจนสุรา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_wattanaburanon_020",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Emochcha",
    "last_name": "Wattanaburanon",
    "full_name": "Emochcha Wattanaburanon",
    "full_name_th": "รศ.ดร. เอมอัชฌา วัฒนบุรานนท์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_termsirikulchai_021",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Lakkana",
    "last_name": "Termsirikulchai",
    "full_name": "Lakkana Termsirikulchai",
    "full_name_th": "ผศ.ดร. ลักขณา เติมศิริกุลชัย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_thanasukan_022",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Chanawanthon",
    "last_name": "Thanasukan",
    "full_name": "Chanawanthon Thanasukan",
    "full_name_th": "ผศ.ดร. ชะนวนทอง ธนสุกาญจน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_saichai_023",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Thawee",
    "last_name": "Saichai",
    "full_name": "Thawee Saichai",
    "full_name_th": "ผศ.ดร. ทวี สายวิชัย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_boonchieng_024",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Waraporn",
    "last_name": "Boonchieng",
    "full_name": "Waraporn Boonchieng",
    "full_name_th": "รศ.ดร. วราภรณ์ บุญเชียง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_surat_025",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Suntharee",
    "last_name": "Surat",
    "full_name": "Suntharee Surat",
    "full_name_th": "ผศ.ดร. สุนทรี สุรัตน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_narin_027",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Rangsiya",
    "last_name": "Narin",
    "full_name": "Rangsiya Narin",
    "full_name_th": "ผศ.ดร. รังสิยา นารินทร์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_chaowatakul_028",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sineenart",
    "last_name": "Chaowatakul",
    "full_name": "Sineenart Chaowatakul",
    "full_name_th": "ผศ.ดร. สินีนาฏ ชาวตระการ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_thongprachum_029",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "คณะสาธารณสุขศาสตร์",
    "department_th": "คณะสาธารณสุขศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Aksara",
    "last_name": "Thongprachum",
    "full_name": "Aksara Thongprachum",
    "full_name_th": "ผศ.ดร. อักษรา ทองประชุม",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_kongsawat_030",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Siripan",
    "last_name": "Kongsawat",
    "full_name": "Siripan Kongsawat",
    "full_name_th": "ผศ.ดร. ศิริพันธุ์ คงสวัสดิ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "mahidoluni_facultyofp_kham_031",
    "university": "Mahidol University & Chiang Mai University",
    "university_th": "มหาวิทยาลัยมหิดล และ มหาวิทยาลัยเชียงใหม่",
    "faculty": "Faculty of Public Health",
    "faculty_th": "คณะสาธารณสุขศาสตร์",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Wuttichai",
    "last_name": "Kham",
    "full_name": "Wuttichai Kham",
    "full_name_th": "ผศ.ดร. วุฒิชัย คำ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
