# -*- coding: utf-8 -*-
EXTRACTED_FACULTIES = [
    {
        "id": "khonkaenun_facultyofm_fac_001_001",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Anatomy",
        "department_th": "Anatomy",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "รศ.ดร. วนัสนันท์ แป้นนางรอง",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_002_002",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Anatomy",
        "department_th": "Anatomy",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "ศ.ดร. สิทธิชัย เอี่ยมสะอาด",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_003_003",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Anatomy",
        "department_th": "Anatomy",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "รศ.ดร. ปาริฉัตร ประจะเนย์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_004_004",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชากุมารเวชศาสตร์",
        "department_th": "ภาควิชากุมารเวชศาสตร์",
        "academic_title": "นพ.",
        "academic_title_th": "นพ.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "นพ. นพ.ยุทธพงศ์ วงศ์สวัสดิวัฒน์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_005_005",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชากุมารเวชศาสตร์",
        "department_th": "ภาควิชากุมารเวชศาสตร์",
        "academic_title": "นพ.",
        "academic_title_th": "นพ.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "นพ. นพ.รัฐพล อุปลา",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_006_006",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชากุมารเวชศาสตร์",
        "department_th": "ภาควิชากุมารเวชศาสตร์",
        "academic_title": "นพ.",
        "academic_title_th": "นพ.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "นพ. นพ.สิรภูมิ เนียมสนิท",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_nithichanon_007",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Micro",
        "department_th": "Micro",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Arnone",
        "last_name": "Nithichanon",
        "full_name": "Arnone Nithichanon",
        "full_name_th": "ผศ.ดร. อานันต์",
        "role": "อาจารย์ประจำ",
        "email": "arnoni@kku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D."
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_sirichoat_008",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Micro",
        "department_th": "Micro",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Auttawit",
        "last_name": "Sirichoat",
        "full_name": "Auttawit Sirichoat",
        "full_name_th": "ผศ.ดร. อรรถวิทย์ ศิริโชติ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Ph.D."
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_009_009",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะแพทยศาสตร์",
        "department_th": "คณะแพทยศาสตร์",
        "academic_title": "ศ.",
        "academic_title_th": "ศ.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "ศ. นพ.อภิชาติ อัศวมงคลกุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_010_010",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะแพทยศาสตร์",
        "department_th": "คณะแพทยศาสตร์",
        "academic_title": "ศ.",
        "academic_title_th": "ศ.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "ศ. นพ.ธาดา ยิบอินซอย",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_011_011",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะแพทยศาสตร์",
        "department_th": "คณะแพทยศาสตร์",
        "academic_title": "รศ.",
        "academic_title_th": "รศ.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "รศ. พญ.",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_012_012",
        "university": "Chiang Mai University",
        "university_th": "มหาวิทยาลัยเชียงใหม่",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะแพทยศาสตร์",
        "department_th": "คณะแพทยศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "รศ.ดร. นายแพทย์ ณัฐ คูณรังษีสมบูรณ์",
        "role": "อาจารย์ประจำ",
        "email": "kitti.th@cmu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_chatkul_013",
        "university": "Chiang Mai University",
        "university_th": "มหาวิทยาลัยเชียงใหม่",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาอายุรศาสตร์",
        "department_th": "ภาควิชาอายุรศาสตร์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Nawapol",
        "last_name": "Chatkul",
        "full_name": "Nawapol Chatkul",
        "full_name_th": "อ. นพ.นวพล ชาติกุล",
        "role": "อาจารย์ประจำ",
        "email": "nawapol.chatkul@cmu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "MD"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_kunlayawutipong_014",
        "university": "Chiang Mai University",
        "university_th": "มหาวิทยาลัยเชียงใหม่",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาอายุรศาสตร์",
        "department_th": "ภาควิชาอายุรศาสตร์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Thanaput",
        "last_name": "Kunlayawutipong",
        "full_name": "Thanaput Kunlayawutipong",
        "full_name_th": "อ. นพ.ธนภัทร กัลยาวุฒิพงศ์",
        "role": "อาจารย์ประจำ",
        "email": "thanaput.kunlaya@cmu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "MD"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_015_015",
        "university": "Chiang Mai University",
        "university_th": "มหาวิทยาลัยเชียงใหม่",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะแพทยศาสตร์",
        "department_th": "คณะแพทยศาสตร์",
        "academic_title": "รศ.",
        "academic_title_th": "รศ.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "รศ. นายแพทย์ เฉลิม ลิ่วศรีสกุล",
        "role": "อาจารย์ประจำ",
        "email": "chalerm.liw@cmu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_j_016",
        "university": "Chiang Mai University",
        "university_th": "มหาวิทยาลัยเชียงใหม่",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาเวชศาสตร์ครอบครัว",
        "department_th": "ภาควิชาเวชศาสตร์ครอบครัว",
        "academic_title": "รศ.",
        "academic_title_th": "รศ.",
        "first_name": "Wichuda",
        "last_name": "J.",
        "full_name": "Wichuda J.",
        "full_name_th": "รศ. พญ.วิชุดา จิรพรเจริญ",
        "role": "อาจารย์ประจำ",
        "email": "ruaphant@med.cmu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_sagarik_017",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "สาขาวิชาเคมี สำนักวิชาวิทยาศาสตร์",
        "department_th": "สาขาวิชาเคมี สำนักวิชาวิทยาศาสตร์",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Kritsana",
        "last_name": "Sagarik",
        "full_name": "Kritsana Sagarik",
        "full_name_th": "ศ.ดร. กฤษณะ สาคริก",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "เคมี"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_tantanuch_018",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "สาขาวิชาคณิตศาสตร์ สำนักวิชาวิทยาศาสตร์",
        "department_th": "สาขาวิชาคณิตศาสตร์ สำนักวิชาวิทยาศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Jetsada",
        "last_name": "Tantanuch",
        "full_name": "Jetsada Tantanuch",
        "full_name_th": "ผศ.ดร. เจษฎา ตัณฑนุช",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "คณิตศาสตร์"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_siritanont_019",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "สำนักวิชาวิทยาศาสตร์",
        "department_th": "สำนักวิชาวิทยาศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Teeranun",
        "last_name": "Siritanont",
        "full_name": "Teeranun Siritanont",
        "full_name_th": "รศ.ดร. ธีรนันท์ ศิริตานนท์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_kaewkao_020",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิทยาศาสตร์",
        "department_th": "คณะวิทยาศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Naragorn",
        "last_name": "Kaewkao",
        "full_name": "Naragorn Kaewkao",
        "full_name_th": "ผศ.ดร. นรากรณ์ แก้วขาว",
        "role": "อาจารย์ประจำ",
        "email": "naragorn.k@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_sothhiphan_021",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิทยาศาสตร์",
        "department_th": "คณะวิทยาศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Sunthorn",
        "last_name": "Sothhiphan",
        "full_name": "Sunthorn Sothhiphan",
        "full_name_th": "รศ.ดร. สุนทร โสตถิพันธุ์",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_wongwatcharanan_022",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิทยาศาสตร์",
        "department_th": "คณะวิทยาศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Uraporn",
        "last_name": "Wongwatcharanan",
        "full_name": "Uraporn Wongwatcharanan",
        "full_name_th": "ผศ.ดร. อุราพร วงศ์วัชรานนท์",
        "role": "อาจารย์ประจำ",
        "email": "uraporn.v@psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_panichayakul_023",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิทยาศาสตร์",
        "department_th": "คณะวิทยาศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Thammarat",
        "last_name": "Panichayakul",
        "full_name": "Thammarat Panichayakul",
        "full_name_th": "รศ.ดร. ธรรมรัตน์ พนิชยากุล",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_prateep_024",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิทยาศาสตร์",
        "department_th": "คณะวิทยาศาสตร์",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Anchana",
        "last_name": "Prateep",
        "full_name": "Anchana Prateep",
        "full_name_th": "ศ.ดร. อัญชนา ประเทพ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_guayjarernpanis_025",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาคณิตศาสตร์",
        "department_th": "ภาควิชาคณิตศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Pannarat",
        "last_name": "Guayjarernpanishk",
        "full_name": "Pannarat Guayjarernpanishk",
        "full_name_th": "ผศ.ดร. พรรณรัตน์ ก้วยเจริญพานิชก์",
        "role": "อาจารย์ประจำ",
        "email": "panngu@kku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_luangchaisri_026",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาคณิตศาสตร์",
        "department_th": "ภาควิชาคณิตศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Panuwat",
        "last_name": "Luangchaisri",
        "full_name": "Panuwat Luangchaisri",
        "full_name_th": "ผศ.ดร. ภาณุวัตร เหลืองชัยศรี",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_ngeontae_027",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาเคมี",
        "department_th": "ภาควิชาเคมี",
        "academic_title": "ศ.ดร.",
        "academic_title_th": "ศ.ดร.",
        "first_name": "Wittaya",
        "last_name": "Ngeontae",
        "full_name": "Wittaya Ngeontae",
        "full_name_th": "ศ.ดร. วิทยา เงินแท้",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "เคมีวิเคราะห์ (Analytical Chemistry)",
            "Analytical Chemistry",
            "เคมีวิเคราะห์"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_burakham_028",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาเคมี",
        "department_th": "ภาควิชาเคมี",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Rojana",
        "last_name": "Burakham",
        "full_name": "Rojana Burakham",
        "full_name_th": "รศ.ดร. รจนา บุระคำ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [
            "Analytical Chemistry"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_tummuangpak_029",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาฟิสิกส์",
        "department_th": "ภาควิชาฟิสิกส์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Pimpunyawat",
        "last_name": "Tummuangpak",
        "full_name": "Pimpunyawat Tummuangpak",
        "full_name_th": "ผศ.ดร. พิมปุณยวัจน์ ทุมเมืองปัก",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_ruangchai_030",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาฟิสิกส์",
        "department_th": "ภาควิชาฟิสิกส์",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Sukhum",
        "last_name": "Ruangchai",
        "full_name": "Sukhum Ruangchai",
        "full_name_th": "อ.ดร. สุขุม เรืองไชย",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_031_031",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาฟิสิกส์",
        "department_th": "ภาควิชาฟิสิกส์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Daris",
        "last_name": "",
        "full_name": "Daris",
        "full_name_th": "รศ.ดร. ดริศ สามารถ",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_032_032",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "",
        "department_th": "",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "ผศ.ดร. พูนสุข ภูสิมมา",
        "role": "อาจารย์ประจำ",
        "email": "thacha@kku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_033_033",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิทยาศาสตร์",
        "department_th": "คณะวิทยาศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "ผศ.ดร. อังคณา บุญยืด",
        "role": "อาจารย์ประจำ",
        "email": "sangka@kku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_034_034",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิทยาศาสตร์",
        "department_th": "คณะวิทยาศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "รศ.ดร. คัชรินทร์ ศิริวงศ์",
        "role": "อาจารย์ประจำ",
        "email": "skhatcha@kku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_035_035",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิศวกรรมศาสตร์",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Parinya",
        "last_name": "",
        "full_name": "Parinya",
        "full_name_th": "ผศ.ดร. ปริญญา คงพรม",
        "role": "อาจารย์ประจำ",
        "email": "kparinya@eng.psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_fac_036_036",
        "university": "Prince of Songkla University",
        "university_th": "มหาวิทยาลัยสงขลานครินทร์",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิศวกรรมศาสตร์",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Passagorn",
        "last_name": "",
        "full_name": "Passagorn",
        "full_name_th": "ผศ.ดร. ภาสกร ชัยวิริยะวงศ์",
        "role": "อาจารย์ประจำ",
        "email": "cpassagorn@eng.psu.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_santiworakul_037",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิศวกรรมศาสตร์",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Ratchaphon",
        "last_name": "Santiworakul",
        "full_name": "Ratchaphon Santiworakul",
        "full_name_th": "รศ.ดร. รัชพล สันติวรากร",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_wanchantuk_038",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "ภาควิชาวิศวกรรมคอมพิวเตอร์",
        "department_th": "ภาควิชาวิศวกรรมคอมพิวเตอร์",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Panupong",
        "last_name": "Wanchantuk",
        "full_name": "Panupong Wanchantuk",
        "full_name_th": "ผศ. ภาณุพงษ์ วันจันทึก",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [
            "วศ.บ. มหาวิทยาลัยขอนแก่น",
            "M.Phil. University of Manchester"
        ],
        "research_interests": [
            "การประมวลผลประสิทธิภาพสูง",
            "เดต้าไมน์นิ่ง"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_phongraktham_039",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "สาขาวิชาวิศวกรรมเครื่องกล",
        "department_th": "สาขาวิชาวิศวกรรมเครื่องกล",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Kritsakorn",
        "last_name": "Phongraktham",
        "full_name": "Kritsakorn Phongraktham",
        "full_name_th": "ดร. กฤษกร พงศ์รักธรรม",
        "role": "อาจารย์ประจำ",
        "email": "kritpon@kku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_tangjaijit_040",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "สาขาวิชาวิศวกรรมเครื่องกล",
        "department_th": "สาขาวิชาวิศวกรรมเครื่องกล",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Kiatfa",
        "last_name": "Tangjaijit",
        "full_name": "Kiatfa Tangjaijit",
        "full_name_th": "รศ.ดร. เกียรติฟ้า ตั้งใจจิต",
        "role": "อาจารย์ประจำ",
        "email": "kiatfa@kku.ac.th",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "khonkaenun_facultyofm_sureephat_041",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "คณะวิศวกรรมศาสตร์",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Panithat",
        "last_name": "Sureephat",
        "full_name": "Panithat Sureephat",
        "full_name_th": "รศ.ดร. ปนิทัศน์ สุรียธนาภาส",
        "role": "อาจารย์ประจำ",
        "email": "",
        "image_url": "",
        "profile_url": "",
        "education": [],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
