# -*- coding: utf-8 -*-
"""
Regional Deep Academic Dataset (backend/scripts/data_sources/regional_deep_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "regionalun_facultymem_phuttawong_001",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Panu",
    "last_name": "Phuttawong",
    "full_name": "Panu Phuttawong",
    "full_name_th": "ผศ.ดร. ภาณุ พุทธวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "panup@nu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_swangmek_002",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาการศึกษา",
    "department_th": "ภาควิชาการศึกษา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sureeporn",
    "last_name": "Swangmek",
    "full_name": "Sureeporn Swangmek",
    "full_name_th": "ผศ.ดร. สุรีย์พร สว่างเมฆ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_chapu_003",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาการศึกษา",
    "department_th": "ภาควิชาการศึกษา",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Suriya",
    "last_name": "Chapu",
    "full_name": "Suriya Chapu",
    "full_name_th": "ดร. สุริยา ชาปู่",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_khunmathuros_004",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะศึกษาศาสตร์",
    "department_th": "คณะศึกษาศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Songphop",
    "last_name": "Khunmathuros",
    "full_name": "Songphop Khunmathuros",
    "full_name_th": "ผศ.ดร. ทรงภพ ขุนมธุรส",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_longue_005",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาภาษาตะวันตก",
    "department_th": "ภาควิชาภาษาตะวันตก",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Charly Richard Alexandre",
    "last_name": "Longue",
    "full_name": "Charly Richard Alexandre Longue",
    "full_name_th": "อ. Charly Richard Alexandre Longue",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_cailliau_006",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาภาษาตะวันตก",
    "department_th": "ภาควิชาภาษาตะวันตก",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Elodie",
    "last_name": "CAILLIAU",
    "full_name": "Elodie CAILLIAU",
    "full_name_th": "อ. Elodie CAILLIAU",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_eakapont_007",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาภาษาไทย",
    "department_th": "ภาควิชาภาษาไทย",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Thanapon",
    "last_name": "Eakapont",
    "full_name": "Thanapon Eakapont",
    "full_name_th": "ดร. ธนพล เอกพจน์",
    "role": "อาจารย์ประจำ",
    "email": "thanapone@nu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_mahamontri_008",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาภาษาไทย",
    "department_th": "ภาควิชาภาษาไทย",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Wararat",
    "last_name": "Mahamontri",
    "full_name": "Wararat Mahamontri",
    "full_name_th": "รศ. วรารัชต์ มหามนตรี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_phudphandan_009",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชากายวิภาคศาสตร์",
    "department_th": "ภาควิชากายวิภาคศาสตร์",
    "academic_title": "รศ.",
    "academic_title_th": "รศ.",
    "first_name": "Chanasorn",
    "last_name": "Phudphandan",
    "full_name": "Chanasorn Phudphandan",
    "full_name_th": "รศ. ชนสรณ์ ภูเด่นแดน",
    "role": "อาจารย์ประจำ",
    "email": "chanasornp@nu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_attapanyawanich_010",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชากายวิภาคศาสตร์",
    "department_th": "ภาควิชากายวิภาคศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kannikar",
    "last_name": "Attapanyawanich",
    "full_name": "Kannikar Attapanyawanich",
    "full_name_th": "ผศ.ดร. กรรณิการ์ อรรถปัณยวนิช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_amornratanaphan_011",
    "university": "Burapha University",
    "university_th": "มหาวิทยาลัยบูรพา",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Patcharanan",
    "last_name": "Amornratanaphan",
    "full_name": "Patcharanan Amornratanaphan",
    "full_name_th": "อ.ดร. พัชรนันท์ อมรรัตนพันธ์",
    "role": "อาจารย์ประจำ",
    "email": "patcharanan@buu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_khammanee_012",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Nisara",
    "last_name": "Khammanee",
    "full_name": "Nisara Khammanee",
    "full_name_th": "ดร. นิสรา คำมณี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_naksiang_013",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Bongkoch",
    "last_name": "Naksiang",
    "full_name": "Bongkoch Naksiang",
    "full_name_th": "ผศ.ดร. บงกช นักเสียง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_wongupparaj_014",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Rangsirat",
    "last_name": "Wongupparaj",
    "full_name": "Rangsirat Wongupparaj",
    "full_name_th": "ดร. รังสิรัศม์ วงศ์อุปราช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_soithong_015",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Chananya",
    "last_name": "Soithong",
    "full_name": "Chananya Soithong",
    "full_name_th": "ดร. ชนัญญา สร้อยทอง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_laoorattapong_016",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Pattra",
    "last_name": "La-oorattapong",
    "full_name": "Pattra La-oorattapong",
    "full_name_th": "อ. ภัทรา ลอออรรถพงศ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_charitkuan_017",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Somthawin",
    "last_name": "Charitkuan",
    "full_name": "Somthawin Charitkuan",
    "full_name_th": "รศ.ดร. สมถวิล จริตควร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_suwandacha_018",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะวิทยาศาสตร์และศิลปศาสตร์",
    "department_th": "คณะวิทยาศาสตร์และศิลปศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Suthirak",
    "last_name": "Suwandacha",
    "full_name": "Suthirak Suwandacha",
    "full_name_th": "อ. สุทธิรักษ์ สุวรรณเดชา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_naktang_019",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะวิทยาศาสตร์และศิลปศาสตร์",
    "department_th": "คณะวิทยาศาสตร์และศิลปศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Thanontrat",
    "last_name": "Naktang",
    "full_name": "Thanontrat Naktang",
    "full_name_th": "ผศ. ธนนท์รัฐ นาคทั่ง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_boonchairoj_020",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะวิทยาศาสตร์และศิลปศาสตร์",
    "department_th": "คณะวิทยาศาสตร์และศิลปศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Teerawat",
    "last_name": "Boonchairoj",
    "full_name": "Teerawat Boonchairoj",
    "full_name_th": "อ. ธีระวรรธน์ บุญไชยโรจน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_anusasananan_021",
    "university": "Burapha University",
    "university_th": "มหาวิทยาลัยบูรพา",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาวิจัยและจิตวิทยาประยุกต์",
    "department_th": "ภาควิชาวิจัยและจิตวิทยาประยุกต์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sureeporn",
    "last_name": "Anusasananan",
    "full_name": "Sureeporn Anusasananan",
    "full_name_th": "ผศ.ดร. สุรีพร อนุศาสนนันท์",
    "role": "อาจารย์ประจำ",
    "email": "sirimal@go.buu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_wongtheerathon_022",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาวิจัยและจิตวิทยาประยุกต์",
    "department_th": "ภาควิชาวิจัยและจิตวิทยาประยุกต์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Daldao",
    "last_name": "Wongtheerathon",
    "full_name": "Daldao Wongtheerathon",
    "full_name_th": "ผศ.ดร. ดลดาว วงศ์ธีระธรณ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_chantanavaranon_023",
    "university": "Burapha University",
    "university_th": "มหาวิทยาลัยบูรพา",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาการบริหารการศึกษา",
    "department_th": "ภาควิชาการบริหารการศึกษา",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Pakkanat",
    "last_name": "Chantanavaranon Sompongtham",
    "full_name": "Pakkanat Chantanavaranon Sompongtham",
    "full_name_th": "ผศ.ดร. ภัคณัฏฐ์ จันทนวรานนท์ สมพงษ์ธรรม",
    "role": "อาจารย์ประจำ",
    "email": "pakkanat.so@go.buu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_inthamaso_024",
    "university": "Burapha University",
    "university_th": "มหาวิทยาลัยบูรพา",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "Faculty of Allied Health Sciences",
    "department_th": "Faculty of Allied Health Sciences",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Uraiwan",
    "last_name": "Inthamaso",
    "full_name": "Uraiwan Inthamaso",
    "full_name_th": "รศ.ดร. อุไรวรรณ อินทมาโส",
    "role": "อาจารย์ประจำ",
    "email": "uraiwani@go.buu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_chanlun_025",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Chutathip",
    "last_name": "Chanlun",
    "full_name": "Chutathip Chanlun",
    "full_name_th": "รศ.ดร. จุฑาทิพย์ จันทร์ลุน",
    "role": "อาจารย์ประจำ",
    "email": "chanlun_j@su.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_soonklang_026",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาคอมพิวเตอร์",
    "department_th": "ภาควิชาคอมพิวเตอร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Tassanawan",
    "last_name": "Soonklang",
    "full_name": "Tassanawan Soonklang",
    "full_name_th": "ผศ.ดร. ทัศนวรรณ ศูนย์กลาง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_onpong_027",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาคอมพิวเตอร์",
    "department_th": "ภาควิชาคอมพิวเตอร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Punyanut",
    "last_name": "Onpong",
    "full_name": "Punyanut Onpong",
    "full_name_th": "ผศ.ดร. ปัญญนัท อ้นพงษ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_kanawong_028",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาคอมพิวเตอร์",
    "department_th": "ภาควิชาคอมพิวเตอร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Ratchadaporn",
    "last_name": "Kanawong",
    "full_name": "Ratchadaporn Kanawong",
    "full_name_th": "ผศ.ดร. รัชดาพร คณาวงษ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_ampawat_029",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะวิทยาการจัดการ",
    "department_th": "คณะวิทยาการจัดการ",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kerkrit",
    "last_name": "Ampawat",
    "full_name": "Kerkrit Ampawat",
    "full_name_th": "ผศ.ดร. เกริกฤทธิ์ อัมพะวัต",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_nilmoj_030",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะวิทยาการจัดการ",
    "department_th": "คณะวิทยาการจัดการ",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Chinawat",
    "last_name": "Nilmoj",
    "full_name": "Chinawat Nilmoj",
    "full_name_th": "อ. ชินวัฒน์ นิลโมจน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_patanathabutr_031",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Pajera",
    "last_name": "Patanathabutr",
    "full_name": "Pajera Patanathabutr",
    "full_name_th": "ผศ.ดร. ปาเจรา พัฒนถาบุตร",
    "role": "อาจารย์ประจำ",
    "email": "patanathabutr_p@su.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_kaewwangchai_032",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Somchai",
    "last_name": "Kaewwangchai",
    "full_name": "Somchai Kaewwangchai",
    "full_name_th": "รศ.ดร. สมชาย แก้ววังชัย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_chaison_033",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Noppol",
    "last_name": "Chaison",
    "full_name": "Noppol Chaison",
    "full_name_th": "อ.ดร. นพพล ไชยสน",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_srithep_034",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Yosatha",
    "last_name": "Srithep",
    "full_name": "Yosatha Srithep",
    "full_name_th": "รศ.ดร. ยศฐา ศรีเทพ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_thammavinyu_035",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะการบัญชีและการจัดการ",
    "department_th": "คณะการบัญชีและการจัดการ",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Chonthicha",
    "last_name": "Thammavinyu",
    "full_name": "Chonthicha Thammavinyu",
    "full_name_th": "อ.ดร. ชลธิชา ธรรมวิญญู",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_pramual_036",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Pairot",
    "last_name": "Pramual",
    "full_name": "Pairot Pramual",
    "full_name_th": "ศ.ดร. ไพโรจน์ ประมวล",
    "role": "อาจารย์ประจำ",
    "email": "pairot.p@msu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_sanghamanee_037",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะสาธารณสุขศาสตร์",
    "department_th": "คณะสาธารณสุขศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Suwimon",
    "last_name": "Sanghamanee",
    "full_name": "Suwimon Sanghamanee",
    "full_name_th": "ผศ. สุวิมล สังฆะมณี",
    "role": "อาจารย์ประจำ",
    "email": "suwimon.s@msu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_wongkhongdech_038",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะสาธารณสุขศาสตร์",
    "department_th": "คณะสาธารณสุขศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Adisorn",
    "last_name": "Wongkhongdech",
    "full_name": "Adisorn Wongkhongdech",
    "full_name_th": "ผศ.ดร. อดิศร วงศ์คงเดช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_praphan_039",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะมนุษยศาสตร์และสังคมศาสตร์",
    "department_th": "คณะมนุษยศาสตร์และสังคมศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Kittiphong",
    "last_name": "Praphan",
    "full_name": "Kittiphong Praphan",
    "full_name_th": "รศ.ดร. กิตติพงษ์ ประพันธ์",
    "role": "อาจารย์ประจำ",
    "email": "kittiphong.p@msu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_ketuwong_040",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Thom",
    "last_name": "Ketuwong",
    "full_name": "Thom Ketuwong",
    "full_name_th": "อ. ทม เกตุวงศ",
    "role": "อาจารย์ประจำ",
    "email": "thom.g@msu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_thamrongrat_041",
    "university": "Walailak University",
    "university_th": "มหาวิทยาลัยวลัยลักษณ์",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Nopporn",
    "last_name": "Thamrongrat",
    "full_name": "Nopporn Thamrongrat",
    "full_name_th": "ผศ.ดร. นพพร ธรรมรงค์รัตน์",
    "role": "อาจารย์ประจำ",
    "email": "nopporn.th@wu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_kaewprasertrakk_042",
    "university": "Walailak University",
    "university_th": "มหาวิทยาลัยวลัยลักษณ์",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ศูนย์บริการการศึกษา",
    "department_th": "ศูนย์บริการการศึกษา",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Neeranart",
    "last_name": "Kaewprasert Rakkangthong",
    "full_name": "Neeranart Kaewprasert Rakkangthong",
    "full_name_th": "อ.ดร. นีรนาท แก้วประเสริฐ ระฆังทอง",
    "role": "อาจารย์ประจำ",
    "email": "ces@mail.wu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_kongpran_043",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Jira",
    "last_name": "Kongpran",
    "full_name": "Jira Kongpran",
    "full_name_th": "รศ.ดร. จิรา คงปราณ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_makkaew_044",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Prasert",
    "last_name": "Makkaew",
    "full_name": "Prasert Makkaew",
    "full_name_th": "ผศ.ดร. ประเสริฐ มากแก้ว",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_thongkhao_045",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Patthida",
    "last_name": "Thongkhao",
    "full_name": "Patthida Thongkhao",
    "full_name_th": "ผศ.ดร. พัฒน์ธิดา ทองขาว",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_preecha_046",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Noppadon",
    "last_name": "Preecha",
    "full_name": "Noppadon Preecha",
    "full_name_th": "ผศ.ดร. นพดล ปรีชา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_srimok_047",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Varangkana",
    "last_name": "Srimok",
    "full_name": "Varangkana Srimok",
    "full_name_th": "ผศ.ดร. วรางคณา ศรีหมอก",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_klamsangsai_048",
    "university": "Walailak University",
    "university_th": "มหาวิทยาลัยวลัยลักษณ์",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "สำนักวิชาการจัดการ",
    "department_th": "สำนักวิชาการจัดการ",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Sukumal",
    "last_name": "Klamsangsai",
    "full_name": "Sukumal Klamsangsai",
    "full_name_th": "อ.ดร. สุขุมาล กล่ำแสงใส",
    "role": "อาจารย์ประจำ",
    "email": "ksukhuma@wu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "การจัดนำเที่ยว"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_klinmanee_049",
    "university": "Walailak University",
    "university_th": "มหาวิทยาลัยวลัยลักษณ์",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "สำนักวิชาศิลปศาสตร์ หลักสูตรภาษาอังกฤษ",
    "department_th": "สำนักวิชาศิลปศาสตร์ หลักสูตรภาษาอังกฤษ",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Nattamon",
    "last_name": "Klinmanee",
    "full_name": "Nattamon Klinmanee",
    "full_name_th": "อ. นทมน กลิ่นมณี",
    "role": "อาจารย์ประจำ",
    "email": "wwararat@wu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [
      "ภาษาศาสตร์ประยุกต์"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_fac_050_050",
    "university": "Walailak University",
    "university_th": "มหาวิทยาลัยวลัยลักษณ์",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "สำนักวิชานิติศาสตร์",
    "department_th": "สำนักวิชานิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Wachiraporn",
    "last_name": "",
    "full_name": "Wachiraporn",
    "full_name_th": "ผศ.ดร. วชิราภรณ์",
    "role": "อาจารย์ประจำ",
    "email": "wachiraporn.po@wu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_maneechot_051",
    "university": "Walailak University",
    "university_th": "มหาวิทยาลัยวลัยลักษณ์",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "สำนักวิชานิติศาสตร์",
    "department_th": "สำนักวิชานิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Kwanmanee",
    "last_name": "Maneechot",
    "full_name": "Kwanmanee Maneechot",
    "full_name_th": "อ. ขวัญมณี มณีโชติ",
    "role": "อาจารย์ประจำ",
    "email": "kwanmanee.ma@wu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_theerawattanasu_052",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Piman",
    "last_name": "Theerawattanasunthorn",
    "full_name": "Piman Theerawattanasunthorn",
    "full_name_th": "ผศ.ดร. พิมาน ธีระรัตนสุนทร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_somporn_053",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Rattawan",
    "last_name": "Somporn",
    "full_name": "Rattawan Somporn",
    "full_name_th": "อ. รัฐวรรณ สมพร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_chutipattana_054",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Nirachorn",
    "last_name": "Chutipattana",
    "full_name": "Nirachorn Chutipattana",
    "full_name_th": "รศ.ดร. นิรชร ชูติพัฒนะ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_wongrit_055",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Palirat",
    "last_name": "Wongrit",
    "full_name": "Palirat Wongrit",
    "full_name_th": "ผศ. ปาลีรัตน์ วงศ์ฤทธิ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_nuengmek_056",
    "university": "University of Phayao",
    "university_th": "มหาวิทยาลัยพะเยา",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะเกษตรศาสตร์และทรัพยากรธรรมชาติ",
    "department_th": "คณะเกษตรศาสตร์และทรัพยากรธรรมชาติ",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Wipornpan",
    "last_name": "Nuengmek",
    "full_name": "Wipornpan Nuengmek",
    "full_name_th": "ผศ.ดร. วิพรพรรณ์ เนื่องเม็ก",
    "role": "อาจารย์ประจำ",
    "email": "wipornpan.nu@up.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_srisilapanan_057",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ศ.",
    "academic_title_th": "ศ.",
    "first_name": "Patcharawan",
    "last_name": "Srisilapanan",
    "full_name": "Patcharawan Srisilapanan",
    "full_name_th": "ศ. ทพญ.ดร.พัชราวรรณ ศรีศิลปนันทน์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_sunanta_058",
    "university": "University of Phayao",
    "university_th": "มหาวิทยาลัยพะเยา",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "หลักสูตรการแพทย์แผนจีนบัณฑิต",
    "department_th": "หลักสูตรการแพทย์แผนจีนบัณฑิต",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Raweephun",
    "last_name": "Sunanta",
    "full_name": "Raweephun Sunanta",
    "full_name_th": "อ. ระวีพรรณ สุนันต๊ะ",
    "role": "อาจารย์ประจำ",
    "email": "raweephun.su@up.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_inkam_059",
    "university": "University of Phayao",
    "university_th": "มหาวิทยาลัยพะเยา",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะศิลปศาสตร์ สาขาวิชาภาษาไทย",
    "department_th": "คณะศิลปศาสตร์ สาขาวิชาภาษาไทย",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Phailin",
    "last_name": "Inkam",
    "full_name": "Phailin Inkam",
    "full_name_th": "อ. น.ส.ไพลิน อินคำ",
    "role": "อาจารย์ประจำ",
    "email": "phailin.in@up.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_woraurai_060",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ส่วนกิจการนิสิต",
    "department_th": "ส่วนกิจการนิสิต",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Suttipong",
    "last_name": "Woraurai",
    "full_name": "Suttipong Woraurai",
    "full_name_th": "อ.ดร. สุทธิพงศ์ วรอุไร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_tulawattanakul_061",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Prapaporn",
    "last_name": "Tulawattanakul",
    "full_name": "Prapaporn Tulawattanakul",
    "full_name_th": "อ. ประภาพร ตุลวัฒนกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.ph.up.ac.th/Personnel.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_sirilak_062",
    "university": "University of Phayao",
    "university_th": "มหาวิทยาลัยพะเยา",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Wipawee",
    "last_name": "Sirilak",
    "full_name": "Wipawee Sirilak",
    "full_name_th": "ผศ.ดร. วิภาวี ศิริลักษณ์",
    "role": "อาจารย์ประจำ",
    "email": "wipawee.si@up.ac.th",
    "image_url": "",
    "profile_url": "https://www.se.up.ac.th/se/Personnel.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_maneewan_063",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Buariam",
    "last_name": "Maneewan",
    "full_name": "Buariam Maneewan",
    "full_name_th": "ผศ.ดร. บัวเรียม มณีวรรณ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/person_search.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_lailert_064",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Narisara",
    "last_name": "Lailert",
    "full_name": "Narisara Lailert",
    "full_name_th": "รศ.ดร. นริศรา ไล้เลิศ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/person_search.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_srivorakul_065",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Saralee",
    "last_name": "Srivorakul",
    "full_name": "Saralee Srivorakul",
    "full_name_th": "อ. สัตวแพทย์หญิง ดร.สราลี ศรีวรกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/person_search.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_dechaphatumwan_066",
    "university": "Maejo University",
    "university_th": "มหาวิทยาลัยแม่โจ้",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Parada",
    "last_name": "Dechaphatumwan",
    "full_name": "Parada Dechaphatumwan",
    "full_name_th": "ผศ.ดร. ปารดา เดชะประทุมวัน",
    "role": "อาจารย์ประจำ",
    "email": "parada_d@mju.ac.th",
    "image_url": "",
    "profile_url": "https://liberalarts.mju.ac.th/wtms_person.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_suksamran_067",
    "university": "Maejo University",
    "university_th": "มหาวิทยาลัยแม่โจ้",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Apalai",
    "last_name": "Suksamran",
    "full_name": "Apalai Suksamran",
    "full_name_th": "อ. อาภาลัย สุขสำราญ",
    "role": "อาจารย์ประจำ",
    "email": "apalai@mju.ac.th",
    "image_url": "",
    "profile_url": "https://liberalarts.mju.ac.th/wtms_person.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_sreenorchan_068",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Surachai",
    "last_name": "Sreenorchan",
    "full_name": "Surachai Sreenorchan",
    "full_name_th": "ผศ. สุรชัย ศรีนรจันทร์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://liberalarts.mju.ac.th/wtms_person.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_boontham_069",
    "university": "Maejo University",
    "university_th": "มหาวิทยาลัยแม่โจ้",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Wilasinee",
    "last_name": "Boontham",
    "full_name": "Wilasinee Boontham",
    "full_name_th": "อ.ดร. วิลาสินี บุญธรรม",
    "role": "อาจารย์ประจำ",
    "email": "maejo@mju.ac.th",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/personAllReport.aspx?gid=292",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_tirawong_070",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Ketsaraporn",
    "last_name": "Tirawong",
    "full_name": "Ketsaraporn Tirawong",
    "full_name_th": "อ.ดร. เกศราพร ทิราวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://dashboard.mju.ac.th/personNameList?",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_lertkanjanaporn_071",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Narupon",
    "last_name": "Lertkanjanaporn",
    "full_name": "Narupon Lertkanjanaporn",
    "full_name_th": "อ.ดร. นฤพนธ์ เลิศกาญจนาพร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://dashboard.mju.ac.th/personNameList?",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_rakprayoon_072",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Namfon",
    "last_name": "Rakprayoon",
    "full_name": "Namfon Rakprayoon",
    "full_name_th": "ผศ.ดร. น้ำฝน รักประยูร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://dashboard.mju.ac.th/personNameList?",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_pokkaew_073",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Ratthapong",
    "last_name": "Pokkaew",
    "full_name": "Ratthapong Pokkaew",
    "full_name_th": "ผศ.ดร. รัฐพงศ์ ปกแก้ว",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://dashboard.mju.ac.th/personNameList?",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_phansaensri_074",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Lakkhana",
    "last_name": "Phansaensri",
    "full_name": "Lakkhana Phansaensri",
    "full_name_th": "ผศ.ดร. ลักขณา พันธุ์แสนศรี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://dashboard.mju.ac.th/personNameList?",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_lianghiranthawo_075",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Suwan",
    "last_name": "Lianghiranthaworn",
    "full_name": "Suwan Lianghiranthaworn",
    "full_name_th": "อ. สุวรรณ เลียงหิรัญถาวร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/teacherInProgram.aspx?year=2564&fac=14",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_khammoon_076",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Chayutphat",
    "last_name": "Khammoon",
    "full_name": "Chayutphat Khammoon",
    "full_name_th": "ผศ. ชยุตภัฎ คำมูล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/teacherInProgram.aspx?year=2564&fac=14",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_maneechookate_077",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Siriporn",
    "last_name": "Maneechookate",
    "full_name": "Siriporn Maneechookate",
    "full_name_th": "ผศ. ศิริพร มณีชูเกตุ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/teacherInProgram.aspx?year=2564&fac=14",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_damrongkiatsak_078",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Phakawit",
    "last_name": "Damrongkiatsak",
    "full_name": "Phakawit Damrongkiatsak",
    "full_name_th": "อ.ดร. ภควิชญ์ ดำรงเกียรติศักดิ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/person_search.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_pisitsakul_079",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Thippapha",
    "last_name": "Pisitsakul",
    "full_name": "Thippapha Pisitsakul",
    "full_name_th": "ผศ.ดร. ทิพปภา พิสิษฐ์กุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/person_search.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_uphoyo_080",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Thipphaphorn",
    "last_name": "Uphoyo",
    "full_name": "Thipphaphorn Uphoyo",
    "full_name_th": "อ. สัตวแพทย์หญิง ดร.ทิพย์ภาภรณ์ อุปโย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/person_search.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_phositthiphan_081",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Thipwadee",
    "last_name": "Phositthiphan",
    "full_name": "Thipwadee Phositthiphan",
    "full_name_th": "อ.ดร. ทิพย์วดี โพธิ์สิทธิพรรณ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://erp.mju.ac.th/person_search.aspx",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_khattiyaman_082",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะศึกษาศาสตร์",
    "department_th": "คณะศึกษาศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Vittawat",
    "last_name": "Khattiyaman",
    "full_name": "Vittawat Khattiyaman",
    "full_name_th": "ผศ.ดร. วิทวัฒน์ ขัตติยะมาน",
    "role": "อาจารย์ประจำ",
    "email": "edu@tsu.ac.th",
    "image_url": "",
    "profile_url": "https://edu.tsu.ac.th/cperson.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_chanprasit_083",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Saowalak",
    "last_name": "Chanprasit",
    "full_name": "Saowalak Chanprasit",
    "full_name_th": "อ. เสาวลักษณ์ จันทร์ประสิทธิ์",
    "role": "อาจารย์ประจำ",
    "email": "thanawit.b@tsu.ac.th",
    "image_url": "",
    "profile_url": "https://ecba.tsu.ac.th/cperson.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_tanisro_084",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Narumol",
    "last_name": "Tanisro",
    "full_name": "Narumol Tanisro",
    "full_name_th": "อ. นฤมล ฐานิสโร",
    "role": "อาจารย์ประจำ",
    "email": "tnarumol@tsu.ac.th",
    "image_url": "",
    "profile_url": "https://law.tsu.ac.th/cperson.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_yamacharoen_085",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Sanan",
    "last_name": "Yamacharoen",
    "full_name": "Sanan Yamacharoen",
    "full_name_th": "ผศ. สนัน ยามาเจริญ",
    "role": "อาจารย์ประจำ",
    "email": "sanan.y@tsu.ac.th",
    "image_url": "",
    "profile_url": "https://www.tsu.ac.th/home/administrator.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_klaivitphat_086",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "Phonkrit",
    "last_name": "Klaivitphat",
    "full_name": "Phonkrit Klaivitphat",
    "full_name_th": "อ.ดร. พลกฤษณ์ คล้ายวิตภัทร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.tsu.ac.th/home/administrator.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_charoenkitkankh_087",
    "university": "Silpakorn University",
    "university_th": "มหาวิทยาลัยศิลปากร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Waleewan",
    "last_name": "Charoenkitkankha",
    "full_name": "Waleewan Charoenkitkankha",
    "full_name_th": "อ. กภ.วลีวรรณ เจริญกิจการค้า",
    "role": "อาจารย์ประจำ",
    "email": "waleewan.c@tsu.ac.th",
    "image_url": "",
    "profile_url": "https://ahs.tsu.ac.th/cperson.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_fac_088_088",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "รศ.ดร. รุ่งรวี",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://muse.tsu.ac.th/cperson.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_fac_089_089",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.ดร.",
    "academic_title_th": "อ.ดร.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "อ.ดร. ศันสนีย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://muse.tsu.ac.th/cperson.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_fac_090_090",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "อ. เทียนทิพย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://muse.tsu.ac.th/cperson.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_fac_091_091",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "อ. วันพระ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://muse.tsu.ac.th/cperson.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_fac_092_092",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "อ. วันวิสา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://muse.tsu.ac.th/cperson.php",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_witool_093",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "ภาควิชาศาสตร์การสอนเฉพาะสาขา",
    "department_th": "ภาควิชาศาสตร์การสอนเฉพาะสาขา",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Surasak",
    "last_name": "Witool",
    "full_name": "Surasak Witool",
    "full_name_th": "อ. สุรศักดิ์ วิฑูรย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.ubu.ac.th/web/edu/content/%E0%B8%AD%E0%B8%B2%E0%B8%88%E0%B8%B2%E0%B8%A3%E0%B8%A2%E0%B9%8C%20%E0%B8%AA%E0%B8%B8%E0%B8%A8%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B4%E0%B9%8C%20%E0%B8%A7%E0%B8%B4%E0%B8%91%E0%B8%B9%E0%B8%A3%E0%B8%A2%E0%B9%8C/",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_kumput_094",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Chansit",
    "last_name": "Kumput",
    "full_name": "Chansit Kumput",
    "full_name_th": "อ. ชาญสิทธิ์ คำพุฒ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.ubu.ac.th/web/edu/content/%E0%B8%AD%E0%B8%B2%E0%B8%88%E0%B8%B2%E0%B8%A3%E0%B8%A2%E0%B9%8C%20%E0%B8%84%E0%B8%B2%E0%B8%A2%E0%B8%AA%E0%B8%B4%E0%B8%97%E0%B8%98%E0%B8%B4%E0%B9%8C%20%20%E0%B8%84%E0%B8%B3%E0%B8%9E%E0%B8%B8%E0%B8%92/",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_bunthichak_095",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Arunya",
    "last_name": "Bunthichak",
    "full_name": "Arunya Bunthichak",
    "full_name_th": "ผศ.ดร. อรัญญา บุทธิจักร์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.ubu.ac.th/web/edu/content/%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B8%8A%E0%B9%88%E0%B8%A2%E0%B8%A8%E0%B8%B2%E0%B8%AA%E0%B8%95%E0%B8%A3%E0%B8%B2%E0%B8%88%E0%B8%B2%E0%B8%A3%E0%B8%A2%E0%B9%8C%20%E0%B8%94%E0%B8%A3.%E0%B8%AD%E0%B8%A3%E0%B8%8D%E0%B8%8D%E0%B8%B2%20%E0%B8%9A%E0%B8%B8%E0%B8%97%E0%B8%98%E0%B8%B4%E0%B8%88%E0%B8%B1%E0%B8%81%E0%B8%A3%E0%B9%8C/",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "regionalun_facultymem_fac_096_096",
    "university": "Naresuan University",
    "university_th": "มหาวิทยาลัยนเรศวร",
    "faculty": "Faculty Members and Researchers",
    "faculty_th": "คณาจารย์และนักวิจัย",
    "department": "หลักสูตรศึกษาศาสตรบัณฑิต วิชาเอกดนตรีศึกษา",
    "department_th": "หลักสูตรศึกษาศาสตรบัณฑิต วิชาเอกดนตรีศึกษา",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "full_name_th": "อ. มิตต ทรัพย์ผุด",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "https://www.ubu.ac.th/news.php?id=24578",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
