# AI-Extracted Courses for มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร (Rajamangala University of Technology Phra Nakhon)
# Extracted using SKILL.state Architecture

EXTRACTED_COURSES = [
    {
        "id": "rajamang_acad__001",
        "title_th": "ครุศาสตร์อุตสาหกรรมบัณฑิต สาขาวิชาเครื่องกล",
        "title_en": "ครุศาสตร์อุตสาหกรรมบัณฑิต สาขาวิชาเครื่องกล",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ค.อ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Industrial Education",
        "department_th": "คณะครุศาสตร์อุตสาหกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรได้รับการรับรองจากคุรุสภา",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "เครื่องกล",
            "ครุศาสตร์อุตสาหกรรม"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__002",
        "title_th": "ครุศาสตร์อุตสาหกรรมบัณฑิต สาขาวิชาอุตสาหการ",
        "title_en": "ครุศาสตร์อุตสาหกรรมบัณฑิต สาขาวิชาอุตสาหการ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ค.อ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Industrial Education",
        "department_th": "คณะครุศาสตร์อุตสาหกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรได้รับการรับรองจากคุรุสภา",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "อุตสาหการ",
            "ครุศาสตร์อุตสาหกรรม"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__003",
        "title_th": "ครุศาสตร์อุตสาหกรรมบัณฑิต สาขาวิชาคอมพิวเตอร์และอิเล็กทรอนิกส์อัจฉริยะ",
        "title_en": "ครุศาสตร์อุตสาหกรรมบัณฑิต สาขาวิชาคอมพิวเตอร์และอิเล็กทรอนิกส์อัจฉริยะ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ค.อ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Industrial Education",
        "department_th": "คณะครุศาสตร์อุตสาหกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรได้รับการรับรองจากคุรุสภา",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "คอมพิวเตอร์",
            "อิเล็กทรอนิกส์อัจฉริยะ",
            "ครุศาสตร์อุตสาหกรรม"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__004",
        "title_th": "อุตสาหกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมอุตสาหการ (ต่อเนื่อง)",
        "title_en": "อุตสาหกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมอุตสาหการ (ต่อเนื่อง)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "อส.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Industrial Education",
        "department_th": "คณะครุศาสตร์อุตสาหกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรต่อเนื่อง",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิศวกรรมอุตสาหการ",
            "ต่อเนื่อง",
            "วิศวกรรมไฟฟ้า",
            "วิศวกรรมเครื่องกล"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__005",
        "title_th": "อุตสาหกรรมศาสตรบัณฑิต สาขาวิชาอิเล็กทรอนิกส์อัจฉริยะ (ต่อเนื่อง)",
        "title_en": "อุตสาหกรรมศาสตรบัณฑิต สาขาวิชาอิเล็กทรอนิกส์อัจฉริยะ (ต่อเนื่อง)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "อส.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Industrial Education",
        "department_th": "คณะครุศาสตร์อุตสาหกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรต่อเนื่อง",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "อิเล็กทรอนิกส์อัจฉริยะ",
            "ต่อเนื่อง"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__006",
        "title_th": "คหกรรมศาสตรบัณฑิต สาขาวิชาออกแบบแฟชั่นและการจัดการสินค้า",
        "title_en": "คหกรรมศาสตรบัณฑิต สาขาวิชาออกแบบแฟชั่นและการจัดการสินค้า",
        "degree_level": "ปริญญาตรี",
        "degree_name": "คศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Home Economics Technology",
        "department_th": "คณะเทคโนโลยีคหกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "ออกแบบแฟชั่น",
            "คหกรรมศาสตร์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__007",
        "title_th": "คหกรรมศาสตรบัณฑิต สาขาวิชาอาหารและโภชนาการ",
        "title_en": "คหกรรมศาสตรบัณฑิต สาขาวิชาอาหารและโภชนาการ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "คศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Home Economics Technology",
        "department_th": "คณะเทคโนโลยีคหกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "อาหารและโภชนาการ",
            "คหกรรมศาสตร์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__008",
        "title_th": "คหกรรมศาสตรบัณฑิต สาขาวิชาอุตสาหกรรมการบริการอาหาร",
        "title_en": "คหกรรมศาสตรบัณฑิต สาขาวิชาอุตสาหกรรมการบริการอาหาร",
        "degree_level": "ปริญญาตรี",
        "degree_name": "คศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Home Economics Technology",
        "department_th": "คณะเทคโนโลยีคหกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "อุตสาหกรรมการบริการอาหาร",
            "คหกรรมศาสตร์",
            "บริการอาหาร"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__009",
        "title_th": "คหกรรมศาสตรบัณฑิต สาขาวิชาคหกรรมศาสตร์",
        "title_en": "คหกรรมศาสตรบัณฑิต สาขาวิชาคหกรรมศาสตร์",
        "degree_level": "ปริญญาตรี",
        "degree_name": "คศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Home Economics Technology",
        "department_th": "คณะเทคโนโลยีคหกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "คหกรรมศาสตร์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__010",
        "title_th": "วิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีอาหาร",
        "title_en": "วิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีอาหาร",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Home Economics Technology",
        "department_th": "คณะเทคโนโลยีคหกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "เทคโนโลยีอาหาร"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__011",
        "title_th": "ศึกษาศาสตรบัณฑิต สาขาคหกรรมศาสตรศึกษา",
        "title_en": "ศึกษาศาสตรบัณฑิต สาขาคหกรรมศาสตรศึกษา",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศษ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Home Economics Technology",
        "department_th": "คณะเทคโนโลยีคหกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรได้รับการรับรองจากคุรุสภา",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "คหกรรมศาสตรศึกษา"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__012",
        "title_th": "เทคโนโลยีบัณฑิต สาขาวิชาเทคโนโลยีสื่อสารมวลชน",
        "title_en": "เทคโนโลยีบัณฑิต สาขาวิชาเทคโนโลยีสื่อสารมวลชน",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ทล.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Mass Communication Technology",
        "department_th": "คณะเทคโนโลยีสื่อสารมวลชน",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "เทคโนโลยีสื่อสารมวลชน"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__013",
        "title_th": "เทคโนโลยีบัณฑิต สาขาวิชาเทคโนโลยีสื่อสารมวลชน (หลักสูตรต่อเนื่อง)",
        "title_en": "เทคโนโลยีบัณฑิต สาขาวิชาเทคโนโลยีสื่อสารมวลชน (หลักสูตรต่อเนื่อง)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ทล.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Mass Communication Technology",
        "department_th": "คณะเทคโนโลยีสื่อสารมวลชน",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรต่อเนื่อง",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "เทคโนโลยีสื่อสารมวลชน",
            "ต่อเนื่อง"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__014",
        "title_th": "บัญชีบัณฑิต",
        "title_en": "บัญชีบัณฑิต",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บช.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Business Administration",
        "department_th": "คณะบริหารธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรได้รับการรับรองจากสภาวิชาชีพบัญชี",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "บัญชี"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__015",
        "title_th": "บริหารธุรกิจบัณฑิต สาขาวิชาการจัดการ",
        "title_en": "บริหารธุรกิจบัณฑิต สาขาวิชาการจัดการ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Business Administration",
        "department_th": "คณะบริหารธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การจัดการ",
            "บริหารธุรกิจ",
            "การตลาด"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__016",
        "title_th": "บริหารธุรกิจบัณฑิต สาขาวิชาการจัดการโลจิสติกส์และโซ่อุปทาน",
        "title_en": "บริหารธุรกิจบัณฑิต สาขาวิชาการจัดการโลจิสติกส์และโซ่อุปทาน",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Business Administration",
        "department_th": "คณะบริหารธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การจัดการโลจิสติกส์และโซ่อุปทาน",
            "บริหารธุรกิจ",
            "โลจิสติกส์",
            "โซ่อุปทาน"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__017",
        "title_th": "บริหารธุรกิจบัณฑิต สาขาวิชานวัตกรรมทางการเงินและการลงทุน",
        "title_en": "บริหารธุรกิจบัณฑิต สาขาวิชานวัตกรรมทางการเงินและการลงทุน",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Business Administration",
        "department_th": "คณะบริหารธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "นวัตกรรมทางการเงินและการลงทุน",
            "บริหารธุรกิจ",
            "นวัตกรรมการเงิน",
            "การลงทุน"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__018",
        "title_th": "บริหารธุรกิจบัณฑิต สาขาวิชาระบบสารสนเทศและนวัตกรรมดิจิทัล",
        "title_en": "บริหารธุรกิจบัณฑิต สาขาวิชาระบบสารสนเทศและนวัตกรรมดิจิทัล",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Business Administration",
        "department_th": "คณะบริหารธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "ระบบสารสนเทศ",
            "นวัตกรรมดิจิทัล",
            "บริหารธุรกิจ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__019",
        "title_th": "บริหารธุรกิจบัณฑิต สาขาวิชาการจัดการธุรกิจระหว่างประเทศ",
        "title_en": "บริหารธุรกิจบัณฑิต สาขาวิชาการจัดการธุรกิจระหว่างประเทศ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Business Administration",
        "department_th": "คณะบริหารธุรกิจ",
        "program_type": "นานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรนานาชาติ",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การจัดการธุรกิจระหว่างประเทศ",
            "นานาชาติ",
            "บริหารธุรกิจ",
            "ธุรกิจระหว่างประเทศ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__020",
        "title_th": "วิทยาศาสตรบัณฑิต สาขาวิชาการวิเคราะห์ข้อมูลทางธุรกิจ",
        "title_en": "วิทยาศาสตรบัณฑิต สาขาวิชาการวิเคราะห์ข้อมูลทางธุรกิจ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Business Administration",
        "department_th": "คณะบริหารธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การวิเคราะห์ข้อมูลทางธุรกิจ",
            "Data Analytics"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__021",
        "title_th": "บริหารธุรกิจบัณฑิต สาขาวิชาการเป็นผู้ประกอบการ",
        "title_en": "บริหารธุรกิจบัณฑิต สาขาวิชาการเป็นผู้ประกอบการ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Business Administration",
        "department_th": "คณะบริหารธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การเป็นผู้ประกอบการ",
            "บริหารธุรกิจ",
            "ผู้ประกอบการ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__022",
        "title_th": "บริหารธุรกิจบัณฑิต สาขาวิชานวัตกรรมธุรกิจบริการยั่งยืน",
        "title_en": "บริหารธุรกิจบัณฑิต สาขาวิชานวัตกรรมธุรกิจบริการยั่งยืน",
        "degree_level": "ปริญญาตรี",
        "degree_name": "บธ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Business Administration",
        "department_th": "คณะบริหารธุรกิจ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "นวัตกรรมธุรกิจบริการยั่งยืน",
            "บริหารธุรกิจ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__023",
        "title_th": "วิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์",
        "title_en": "วิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Science and Technology",
        "department_th": "คณะวิทยาศาสตร์และเทคโนโลยี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิทยาการคอมพิวเตอร์",
            "Computer Science"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__024",
        "title_th": "วิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์และเทคโนโลยีสิ่งแวดล้อม",
        "title_en": "วิทยาศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์และเทคโนโลยีสิ่งแวดล้อม",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Science and Technology",
        "department_th": "คณะวิทยาศาสตร์และเทคโนโลยี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิทยาศาสตร์และเทคโนโลยีสิ่งแวดล้อม"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__025",
        "title_th": "วิทยาศาสตรบัณฑิต สาขาวิชาวัสดุศาสตร์อุตสาหกรรม",
        "title_en": "วิทยาศาสตรบัณฑิต สาขาวิชาวัสดุศาสตร์อุตสาหกรรม",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Science and Technology",
        "department_th": "คณะวิทยาศาสตร์และเทคโนโลยี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วัสดุศาสตร์อุตสาหกรรม"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__026",
        "title_th": "วิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการข้อมูลและเทคโนโลยีสารสนเทศ",
        "title_en": "วิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการข้อมูลและเทคโนโลยีสารสนเทศ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Science and Technology",
        "department_th": "คณะวิทยาศาสตร์และเทคโนโลยี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิทยาการข้อมูล",
            "เทคโนโลยีสารสนเทศ",
            "Data Science",
            "IT"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__027",
        "title_th": "วิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีสุขภาพ เครื่องสำอางและการชะลอวัย",
        "title_en": "วิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีสุขภาพ เครื่องสำอางและการชะลอวัย",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Science and Technology",
        "department_th": "คณะวิทยาศาสตร์และเทคโนโลยี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "เทคโนโลยีสุขภาพ",
            "เครื่องสำอาง",
            "การชะลอวัย"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__028",
        "title_th": "วิทยาศาสตรบัณฑิต สาขาวิชาสถิติสารสนเทศ",
        "title_en": "วิทยาศาสตรบัณฑิต สาขาวิชาสถิติสารสนเทศ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Science and Technology",
        "department_th": "คณะวิทยาศาสตร์และเทคโนโลยี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "สถิติสารสนเทศ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__029",
        "title_th": "วิทยาศาสตรบัณฑิต สาขาวิชาการจัดการสภาพภูมิอากาศและสิ่งแวดล้อม",
        "title_en": "วิทยาศาสตรบัณฑิต สาขาวิชาการจัดการสภาพภูมิอากาศและสิ่งแวดล้อม",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Science and Technology",
        "department_th": "คณะวิทยาศาสตร์และเทคโนโลยี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การจัดการสภาพภูมิอากาศ",
            "สิ่งแวดล้อม"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__030",
        "title_th": "วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมไฟฟ้า",
        "title_en": "วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมไฟฟ้า",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Engineering",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรได้รับการรับรองจากสภาวิศวกร",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิศวกรรมไฟฟ้า",
            "วิศวกรรมศาสตร์",
            "วิศวกรรมอุตสาหการ",
            "วิศวกรรมโยธา"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__031",
        "title_th": "วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเครื่องกล",
        "title_en": "วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเครื่องกล",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Engineering",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรได้รับการรับรองจากสภาวิศวกร",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิศวกรรมเครื่องกล",
            "วิศวกรรมศาสตร์",
            "วิศวกรรมเมคคาทรอนิกส์",
            "วิศวกรรมเครื่องมือและแม่พิมพ์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__032",
        "title_th": "วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์",
        "title_en": "วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Engineering",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรต่อเนื่อง",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิศวกรรมคอมพิวเตอร์",
            "วิศวกรรมศาสตร์",
            "ต่อเนื่อง"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__033",
        "title_th": "วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมไฟฟ้าสื่อสารและระบบอัจฉริยะ",
        "title_en": "วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมไฟฟ้าสื่อสารและระบบอัจฉริยะ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Engineering",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรได้รับการรับรองจากสภาวิศวกร",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิศวกรรมไฟฟ้าสื่อสาร",
            "ระบบอัจฉริยะ",
            "วิศวกรรมศาสตร์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__034",
        "title_th": "อุตสาหกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมการผลิตเครื่องประดับ",
        "title_en": "อุตสาหกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมการผลิตเครื่องประดับ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "อส.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Engineering",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิศวกรรมการผลิตเครื่องประดับ",
            "วิศวกรรมศาสตร์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__035",
        "title_th": "อุตสาหกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเทคโนโลยีนวัตกรรมเพื่อความยั่งยืน (ต่อเนื่อง)",
        "title_en": "อุตสาหกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมเทคโนโลยีนวัตกรรมเพื่อความยั่งยืน (ต่อเนื่อง)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "อส.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Engineering",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรต่อเนื่อง",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "วิศวกรรมเทคโนโลยีนวัตกรรมเพื่อความยั่งยืน",
            "ต่อเนื่อง",
            "วิศวกรรมศาสตร์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__036",
        "title_th": "ศิลปศาสตรบัณฑิต สาขาวิชาอัญมณีรังสรรค์",
        "title_en": "ศิลปศาสตรบัณฑิต สาขาวิชาอัญมณีรังสรรค์",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศล.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Engineering",
        "department_th": "คณะวิศวกรรมศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "อัญมณีรังสรรค์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__037",
        "title_th": "ศิลปศาสตรบัณฑิต สาขาวิชาการท่องเที่ยว (ต่อเนื่อง)",
        "title_en": "ศิลปศาสตรบัณฑิต สาขาวิชาการท่องเที่ยว (ต่อเนื่อง)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Liberal Arts",
        "department_th": "คณะศิลปศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรต่อเนื่อง",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การท่องเที่ยว",
            "ต่อเนื่อง",
            "ศิลปศาสตร์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__038",
        "title_th": "ศิลปศาสตรบัณฑิต สาขาวิชาการท่องเที่ยวและการบริการ",
        "title_en": "ศิลปศาสตรบัณฑิต สาขาวิชาการท่องเที่ยวและการบริการ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Liberal Arts",
        "department_th": "คณะศิลปศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การท่องเที่ยวและการบริการ",
            "ศิลปศาสตร์",
            "การท่องเที่ยว",
            "การบริการ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__039",
        "title_th": "ศิลปศาสตรบัณฑิต สาขาวิชาการโรงแรมและธุรกิจบริการ",
        "title_en": "ศิลปศาสตรบัณฑิต สาขาวิชาการโรงแรมและธุรกิจบริการ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Liberal Arts",
        "department_th": "คณะศิลปศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การโรงแรมและธุรกิจบริการ",
            "ศิลปศาสตร์",
            "การโรงแรม",
            "ธุรกิจบริการ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__040",
        "title_th": "ศิลปศาสตรบัณฑิต สาขาวิชาภาษาอังกฤษเพื่อการสื่อสารสากล",
        "title_en": "ศิลปศาสตรบัณฑิต สาขาวิชาภาษาอังกฤษเพื่อการสื่อสารสากล",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Liberal Arts",
        "department_th": "คณะศิลปศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "ภาษาอังกฤษเพื่อการสื่อสารสากล",
            "ศิลปศาสตร์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__041",
        "title_th": "ศิลปศาสตรบัณฑิต สาขาวิชาภาษาไทยประยุกต์เพื่ออาชีพและนวัตกรรมการสื่อสาร",
        "title_en": "ศิลปศาสตรบัณฑิต สาขาวิชาภาษาไทยประยุกต์เพื่ออาชีพและนวัตกรรมการสื่อสาร",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Liberal Arts",
        "department_th": "คณะศิลปศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "ภาษาไทยประยุกต์",
            "นวัตกรรมการสื่อสาร",
            "ศิลปศาสตร์"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__042",
        "title_th": "เทคโนโลยีบัณฑิต สาขาวิชาเทคโนโลยีเสื้อผ้าและการจัดการธุรกิจแฟชั่น",
        "title_en": "เทคโนโลยีบัณฑิต สาขาวิชาเทคโนโลยีเสื้อผ้าและการจัดการธุรกิจแฟชั่น",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ทล.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Industrial Textiles and Fashion Design",
        "department_th": "คณะอุตสาหกรรมสิ่งทอและออกแบบแฟชั่น",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "เทคโนโลยีเสื้อผ้า",
            "การจัดการธุรกิจแฟชั่น"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__043",
        "title_th": "เทคโนโลยีบัณฑิต สาขาวิชานวัตกรรมและเทคโนโลยีสิ่งทอ",
        "title_en": "เทคโนโลยีบัณฑิต สาขาวิชานวัตกรรมและเทคโนโลยีสิ่งทอ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ทล.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Industrial Textiles and Fashion Design",
        "department_th": "คณะอุตสาหกรรมสิ่งทอและออกแบบแฟชั่น",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "นวัตกรรมและเทคโนโลยีสิ่งทอ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__044",
        "title_th": "เทคโนโลยีบัณฑิต สาขาวิชาออกแบบแฟชั่นและสิ่งทอ",
        "title_en": "เทคโนโลยีบัณฑิต สาขาวิชาออกแบบแฟชั่นและสิ่งทอ",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ทล.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Industrial Textiles and Fashion Design",
        "department_th": "คณะอุตสาหกรรมสิ่งทอและออกแบบแฟชั่น",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "ออกแบบแฟชั่นและสิ่งทอ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__045",
        "title_th": "เทคโนโลยีบัณฑิต สาขาวิชาการออกแบบผลิตภัณฑ์อุตสาหกรรม",
        "title_en": "เทคโนโลยีบัณฑิต สาขาวิชาการออกแบบผลิตภัณฑ์อุตสาหกรรม",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ทล.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Architecture and Design",
        "department_th": "คณะสถาปัตยกรรมศาสตร์และการออกแบบ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การออกแบบผลิตภัณฑ์อุตสาหกรรม",
            "สถาปัตยกรรมศาสตร์และการออกแบบ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__046",
        "title_th": "เทคโนโลยีบัณฑิต สาขาวิชาการออกแบบบรรจุภัณฑ์และเทคโนโลยีการพิมพ์",
        "title_en": "เทคโนโลยีบัณฑิต สาขาวิชาการออกแบบบรรจุภัณฑ์และเทคโนโลยีการพิมพ์",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ทล.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Architecture and Design",
        "department_th": "คณะสถาปัตยกรรมศาสตร์และการออกแบบ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "การออกแบบบรรจุภัณฑ์",
            "เทคโนโลยีการพิมพ์",
            "สถาปัตยกรรมศาสตร์และการออกแบบ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    },
    {
        "id": "rajamang_acad__047",
        "title_th": "สถาปัตยกรรมศาสตรบัณฑิต สาขาวิชาสถาปัตยกรรม",
        "title_en": "สถาปัตยกรรมศาสตรบัณฑิต สาขาวิชาสถาปัตยกรรม",
        "degree_level": "ปริญญาตรี",
        "degree_name": "สถ.บ.",
        "university": "Rajamangala University of Technology Phra Nakhon",
        "university_th": "มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร",
        "faculty": "",
        "faculty_th": "",
        "department": "Faculty of Architecture and Design",
        "department_th": "คณะสถาปัตยกรรมศาสตร์และการออกแบบ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "",
        "tuition_per_semester": "",
        "tuition_total": "",
        "description": "หลักสูตรได้รับการรับรองจากสภาสถาปนิก",
        "curriculum_highlights": [],
        "career_paths": [],
        "tags": [
            "สถาปัตยกรรม",
            "สถาปัตยกรรมศาสตร์และการออกแบบ"
        ],
        "website_url": "https://www.rmutp.ac.th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3/"
    }
]
