# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/ru_law_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "ramkhamhae_facultyofl_phurisinsit_001",
    "university": "Ramkhamhaeng University",
    "university_th": "มหาวิทยาลัยรามคำแหง",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sitthiphak",
    "last_name": "Phurisinsit",
    "full_name": "Sitthiphak Phurisinsit",
    "full_name_th": "ผศ.ดร. สิทธิภาคย์ ภูริสินสิทธิ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "ramkhamhae_facultyofl_phisuthangkun_002",
    "university": "Ramkhamhaeng University",
    "university_th": "มหาวิทยาลัยรามคำแหง",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Ratsak",
    "last_name": "Phisuthangkun",
    "full_name": "Ratsak Phisuthangkun",
    "full_name_th": "ผศ.ดร. รัฐศักดิ์ พิศุทธางกูร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "ramkhamhae_facultyofl_chotimanont_003",
    "university": "Ramkhamhaeng University",
    "university_th": "มหาวิทยาลัยรามคำแหง",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Preeda",
    "last_name": "Chotimanont",
    "full_name": "Preeda Chotimanont",
    "full_name_th": "รศ.ดร. ปรีดา โชติมานนท์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "ramkhamhae_facultyofl_sukhapisit_004",
    "university": "Ramkhamhaeng University",
    "university_th": "มหาวิทยาลัยรามคำแหง",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Pattaneti",
    "last_name": "Sukhapisit",
    "full_name": "Pattaneti Sukhapisit",
    "full_name_th": "อ. พัทธเนติห์ สุขะพิสิษฐ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "ramkhamhae_facultyofl_sisiwannakan_005",
    "university": "Ramkhamhaeng University",
    "university_th": "มหาวิทยาลัยรามคำแหง",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Sasiprapa",
    "last_name": "Sisiwannakan",
    "full_name": "Sasiprapa Sisiwannakan",
    "full_name_th": "อ. ศศิประภา ศิสศิ วรรณาการ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "ramkhamhae_facultyofl_nuwetwongsakamo_006",
    "university": "Ramkhamhaeng University",
    "university_th": "มหาวิทยาลัยรามคำแหง",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Nitinat",
    "last_name": "Nuwetwongsakamon",
    "full_name": "Nitinat Nuwetwongsakamon",
    "full_name_th": "ผศ. นิติณัฏฐ์ นุเวศวงษ์กมล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "ramkhamhae_facultyofl_paliyavet_007",
    "university": "Ramkhamhaeng University",
    "university_th": "มหาวิทยาลัยรามคำแหง",
    "faculty": "Faculty of Law",
    "faculty_th": "คณะนิติศาสตร์",
    "department": "คณะนิติศาสตร์",
    "department_th": "คณะนิติศาสตร์",
    "academic_title": "ผศ.",
    "academic_title_th": "ผศ.",
    "first_name": "Thanachat",
    "last_name": "Paliyavet",
    "full_name": "Thanachat Paliyavet",
    "full_name_th": "ผศ. ธนะชาติ ปาลิยะเวทย์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
