# -*- coding: utf-8 -*-
"""
Deduplicated Academic Faculty Dataset (backend/scripts/data_sources/siit_ai_extracted.py)
"""

EXTRACTED_FACULTIES = [
  {
    "id": "thammasatu_sirindhorn_iamprasertkun_001",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Bio-Chemical Engineering and Technology",
    "department_th": "School of Bio-Chemical Engineering and Technology",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pawin",
    "last_name": "Iamprasertkun",
    "full_name": "Pawin Iamprasertkun",
    "full_name_th": "รศ.ดร. ภาวินทร์ เอี่ยมประเสริฐกุล",
    "role": "อาจารย์ประจำ",
    "email": "pawin@siit.tu",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_wongnate_002",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Thanyaporn",
    "last_name": "Wongnate",
    "full_name": "Thanyaporn Wongnate",
    "full_name_th": "ผศ.ดร. ธัญญาภรณ์ วงศ์เนตร",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_panuwatwanich_003",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "",
    "department_th": "",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Kriengsak",
    "last_name": "Panuwatwanich",
    "full_name": "Kriengsak Panuwatwanich",
    "full_name_th": "รศ.ดร. เกรียงศักดิ์ ภานุวัฒนวงศ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_seesanea_004",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Adisak",
    "last_name": "Seesanea",
    "full_name": "Adisak Seesanea",
    "full_name_th": "ผศ.ดร. อดิศักดิ์ ซีเสงี่ยม",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_opaprakasit_005",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Pakorn",
    "last_name": "Opaprakasit",
    "full_name": "Pakorn Opaprakasit",
    "full_name_th": "อ. ปกรณ์ โอประประกิจ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "Ph.D. in Materials Science and Engineering from Pennsylvania State University"
    ],
    "research_interests": [
      "Materials Science and Engineering"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_kongprawechnon_006",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Information, Computer, and Communication Technology",
    "department_th": "School of Information, Computer, and Communication Technology",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Waree",
    "last_name": "Kongprawechnon",
    "full_name": "Waree Kongprawechnon",
    "full_name_th": "รศ.ดร. วารี คงประเวชชน",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_laitrakun_007",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Seksan",
    "last_name": "Laitrakun",
    "full_name": "Seksan Laitrakun",
    "full_name_th": "ผศ.ดร. เสกสรรค์ ลายไตรภพ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_usanavasin_008",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "",
    "department_th": "",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sasiporn",
    "last_name": "Usanavasin",
    "full_name": "Sasiporn Usanavasin",
    "full_name_th": "ผศ.ดร. ศศิพร อุสาหะวาสิน",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_hsu_009",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "",
    "department_th": "",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Shu-Han",
    "last_name": "Hsu",
    "full_name": "Shu-Han Hsu",
    "full_name_th": "ดร. ซู-ฮัน ซู",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "Ph.D."
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_racharak_010",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Teeradaj",
    "last_name": "Racharak",
    "full_name": "Teeradaj Racharak",
    "full_name_th": "อ. ธีรเดช รัชรักษ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [
      "Ph.D. in Engineering and Technology at Sirindhorn International Institute of Technology, Thammasat University, Thailand",
      "Ph.D. in Information"
    ],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_chucherd_011",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Applied Digital Technology",
    "department_th": "School of Applied Digital Technology",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Sirikan",
    "last_name": "Chucherd",
    "full_name": "Sirikan Chucherd",
    "full_name_th": "ผศ.ดร. สิริกานต์ ชูเชิด",
    "role": "อาจารย์ประจำ",
    "email": "sirikan@mfu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [
      "Ph.D. Computer Science, Sirindhorn International Institute of Technology"
    ],
    "research_interests": [
      "Computer Science"
    ],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_horanont_012",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "",
    "department_th": "",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Teerayut",
    "last_name": "Horanont",
    "full_name": "Teerayut Horanont",
    "full_name_th": "อ. ธีรยุทธ โหราศาสตร์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_bhooanusas_013",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Information, Computer, and Communication Technology (ICT)",
    "department_th": "School of Information, Computer, and Communication Technology (ICT)",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Nuntanut",
    "last_name": "Bhooanusas",
    "full_name": "Nuntanut Bhooanusas",
    "full_name_th": "ดร. นันทนัฐ ภู่อนุสรณ์",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_suksompong_014",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Information, Computer, and Communication Technology (ICT)",
    "department_th": "School of Information, Computer, and Communication Technology (ICT)",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Prapun",
    "last_name": "Suksompong",
    "full_name": "Prapun Suksompong",
    "full_name_th": "รศ.ดร. ประพันธ์ สุขสมปอง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_takahashi_015",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Bio-Chemical Engineering and Technology (BCET)",
    "department_th": "School of Bio-Chemical Engineering and Technology (BCET)",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Kaito",
    "last_name": "Takahashi",
    "full_name": "Kaito Takahashi",
    "full_name_th": "ผศ.ดร. Kaito Takahashi",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_nueangnoraj_016",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Bio-Chemical Engineering and Technology (BCET)",
    "department_th": "School of Bio-Chemical Engineering and Technology (BCET)",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Khanin",
    "last_name": "Nueangnoraj",
    "full_name": "Khanin Nueangnoraj",
    "full_name_th": "รศ.ดร. ขนิษฐ์ เนืองนอราช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_toochinda_017",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Bio-Chemical Engineering and Technology (BCET)",
    "department_th": "School of Bio-Chemical Engineering and Technology (BCET)",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Pisanu",
    "last_name": "Toochinda",
    "full_name": "Pisanu Toochinda",
    "full_name_th": "รศ.ดร. พิษณุ ตู้จินดา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_sreearunothai_018",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Bio-Chemical Engineering and Technology (BCET)",
    "department_th": "School of Bio-Chemical Engineering and Technology (BCET)",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Paiboon",
    "last_name": "Sreearunothai",
    "full_name": "Paiboon Sreearunothai",
    "full_name_th": "รศ.ดร. ไพบูลย์ ศรีอรุณโณทัย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_chiadamrong_019",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "department_th": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Navee",
    "last_name": "Chiadamrong",
    "full_name": "Navee Chiadamrong",
    "full_name_th": "รศ.ดร. นาวี ชีวดำรงค์กุล",
    "role": "อาจารย์ประจำ",
    "email": "navee@siit.tu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_kunnapapdeelert_020",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "department_th": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Siwaporn",
    "last_name": "Kunnapapdeelert",
    "full_name": "Siwaporn Kunnapapdeelert",
    "full_name_th": "ผศ.ดร. ศิวพร คุณปภากรเดช",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_rianmora_021",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "department_th": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Suchada",
    "last_name": "Rianmora",
    "full_name": "Suchada Rianmora",
    "full_name_th": "รศ.ดร. สุชาดา เหรียญโมรา",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_traipattanakul_022",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "department_th": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "academic_title": "อ.",
    "academic_title_th": "อ.",
    "first_name": "Bhawat",
    "last_name": "Traipattanakul",
    "full_name": "Bhawat Traipattanakul",
    "full_name_th": "อ. ภวัต ไตรพัฒนากุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_pannakkong_023",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "department_th": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Warut",
    "last_name": "Pannakkong",
    "full_name": "Warut Pannakkong",
    "full_name_th": "รศ.ดร. วรุฒ พรรณาก้ง",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_olapiriyakul_024",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "department_th": "School of Manufacturing Systems and Mechanical Engineering (MSME)",
    "academic_title": "รศ.ดร.",
    "academic_title_th": "รศ.ดร.",
    "first_name": "Sun",
    "last_name": "Olapiriyakul",
    "full_name": "Sun Olapiriyakul",
    "full_name_th": "รศ.ดร. สันต์ โอภาสพิริยะกุล",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_tangtermsirikul_026",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Civil Engineering and Technology (CET)",
    "department_th": "School of Civil Engineering and Technology (CET)",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Somnuk",
    "last_name": "Tangtermsirikul",
    "full_name": "Somnuk Tangtermsirikul",
    "full_name_th": "ศ.ดร. สมนึก ตั้งเติมศิริกุล",
    "role": "อาจารย์ประจำ",
    "email": "somnuk@siit.tu.ac.th",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_chaisomphob_027",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Civil Engineering and Technology (CET)",
    "department_th": "School of Civil Engineering and Technology (CET)",
    "academic_title": "ศ.ดร.",
    "academic_title_th": "ศ.ดร.",
    "first_name": "Taweep",
    "last_name": "Chaisomphob",
    "full_name": "Taweep Chaisomphob",
    "full_name_th": "ศ.ดร. ทวีป ไชยสมภพ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_sancharoen_028",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "School of Civil Engineering and Technology (CET)",
    "department_th": "School of Civil Engineering and Technology (CET)",
    "academic_title": "ผศ.ดร.",
    "academic_title_th": "ผศ.ดร.",
    "first_name": "Pakawat",
    "last_name": "Sancharoen",
    "full_name": "Pakawat Sancharoen",
    "full_name_th": "ผศ.ดร. ภาควัต สังข์เจริญ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_nanakorn_029",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "ภาควิชาวิศวกรรมโยธาและเทคโนโลยี",
    "department_th": "ภาควิชาวิศวกรรมโยธาและเทคโนโลยี",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Pruettha",
    "last_name": "Nanakorn",
    "full_name": "Pruettha Nanakorn",
    "full_name_th": "ดร. พฤทธา นาครทรรพ",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  },
  {
    "id": "thammasatu_sirindhorn_piantanakulchai_030",
    "university": "Thammasat University",
    "university_th": "มหาวิทยาลัยธรรมศาสตร์",
    "faculty": "Sirindhorn International Institute of Technology (SIIT)",
    "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
    "department": "ภาควิชาวิศวกรรมโยธาและเทคโนโลยี",
    "department_th": "ภาควิชาวิศวกรรมโยธาและเทคโนโลยี",
    "academic_title": "ดร.",
    "academic_title_th": "ดร.",
    "first_name": "Mongkut",
    "last_name": "Piantanakulchai",
    "full_name": "Mongkut Piantanakulchai",
    "full_name_th": "ดร. มงกุฎ Пиանտานակուլชัย",
    "role": "อาจารย์ประจำ",
    "email": "",
    "image_url": "",
    "profile_url": "",
    "education": [],
    "research_interests": [],
    "featured_publications": [],
    "scholar_url": "",
    "confidence_score": 0.95
  }
]
