# Source: sportsscience.kps.ku.ac.th/lecturer/ (page found via WP REST enumeration) — wave 3 Batch 91
# Auto-generated by SKILL.state agent (sparse-faculty wave 3), deterministic cleaning pass
KU_SPORTSCI_FACULTIES = [
    {
        "id": "kasetsartu_facultyofs_sriton_001",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Bhuwanat",
        "last_name": "Sriton",
        "full_name": "Bhuwanat Sriton",
        "full_name_th": "ผศ.ดร. ภูวนารถ ศรีทน",
        "role": "อาจารย์ประจำ",
        "email": "bhuwanat.s@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิทยาศาสตร์การกีฬา), มหาวิทยาลัยเกษตรศาสตร์, TH, 2566"
        ],
        "research_interests": [
            "วิทยาศาสตร์การกีฬา"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_prachakul_002",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Wimonmas",
        "last_name": "Prachakul",
        "full_name": "Wimonmas Prachakul",
        "full_name_th": "ผศ.ดร. วิมลมาศ ประชากุล",
        "role": "อาจารย์ประจำ",
        "email": "wimonmas.p@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิทยาศาสตร์การออกกำลังกายและการกีฬา), มหาวิทยาลัยบูรพา, TH, 2551"
        ],
        "research_interests": [
            "จิตวิทยาการกีฬา"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_tumnark_003",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Piyaporn",
        "last_name": "Tumnark",
        "full_name": "Piyaporn Tumnark",
        "full_name_th": "ผศ.ดร. ปิยาภรณ์ ตุ้มนาค",
        "role": "อาจารย์ประจำ",
        "email": "piyaporn.t@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor Degree (Sports Science), UNIVERSITY OF PORTO, PT, 2561"
        ],
        "research_interests": [
            "โภชนาการ"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_tiankaew_004",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Nanthawan",
        "last_name": "Tiankaew",
        "full_name": "Nanthawan Tiankaew",
        "full_name_th": "ผศ.ดร. นันทวัน เทียนแก้ว",
        "role": "อาจารย์ประจำ",
        "email": "nanthawan.t@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิทยาศาสตร์การออกกำลังกายและการกีฬา), มหาวิทยาลัยมหาสารคาม, TH, 2562"
        ],
        "research_interests": [
            "วิทยาศาสตร์การออกกำลังกายและการกีฬา"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_leewattananupho_005",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Siwa",
        "last_name": "Leewattananuphong",
        "full_name": "Siwa Leewattananuphong",
        "full_name_th": "อ. ศิวะ ลียวัฒนานุพงศ์",
        "role": "อาจารย์ประจำ",
        "email": "siwa.l@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "วิทยาศาสตรมหาบัณฑิต (วิทยาศาสตร์การกีฬา), มหาวิทยาลัยเกษตรศาสตร์, TH, 2553",
            "ปรัชญาดุษฎีบัณฑิต (วิทยาศาสตร์การกีฬา), มหาวิทยาลัยเกษตรศาสตร์, TH, 2561"
        ],
        "research_interests": [
            "วิทยาศาสตร์การกีฬา",
            "การเงินการบัญชีในธุรกิจกีฬา"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_pimphaporn_006",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Phornphon",
        "last_name": "Pimphaporn",
        "full_name": "Phornphon Pimphaporn",
        "full_name_th": "ผศ.ดร. พรพล พิมพาพร",
        "role": "อาจารย์ประจำ",
        "email": "phornphon.p@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิทยาศาสตร์การออกกำลังกายและการกีฬา), มหาวิทยาลัยบูรพา, TH, 2554"
        ],
        "research_interests": [
            "สรีรวิทยาการออกกำลังกายและการกีฬา"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_makaje_007",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Niromlee",
        "last_name": "Makaje",
        "full_name": "Niromlee Makaje",
        "full_name_th": "ผศ.ดร. นิรอมลี มะกาเจ",
        "role": "อาจารย์ประจำ",
        "email": "niromlee.m@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิทยาศาสตร์การกีฬา), มหาวิทยาลัยเกษตรศาสตร์, TH, 2555"
        ],
        "research_interests": [
            "Statistics and Research Method in Sports Science",
            "Physiology of Sports and Exercise"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_tanphanich_008",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Amnuay",
        "last_name": "Tanphanich",
        "full_name": "Amnuay Tanphanich",
        "full_name_th": "ผศ. ว่าที่ร้อยตรี ดร.อำนวย ตันพานิชย์",
        "role": "อาจารย์ประจำ",
        "email": "amnuay.t@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิทยาศาสตร์การออกกำลังกายและการกีฬา), มหาวิทยาลัยบูรพา, TH, 2553"
        ],
        "research_interests": [
            "จิตวิทยา",
            "วิทยาศาสตร์การกีฬาและการออกกำลังกาย",
            "พลศึกษา"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_permsubthavee_009",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Jatuporn",
        "last_name": "Permsubthavee",
        "full_name": "Jatuporn Permsubthavee",
        "full_name_th": "รศ.ดร. จตุพร เพิ่มทรัพย์ทวี",
        "role": "อาจารย์ประจำ",
        "email": "jatuporn.w@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (ชีวเวชศาสตร์), มหาวิทยาลัยขอนแก่น, TH, 2554"
        ],
        "research_interests": [
            "สรีรการออกกำลังกาย"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_thongpanya_010",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Ubon",
        "last_name": "Thongpanya",
        "full_name": "Ubon Thongpanya",
        "full_name_th": "ดร. อุบล ทองปัญญา",
        "role": "อาจารย์ประจำ",
        "email": "ubon.t@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ศึกษาศาสตรดุษฎีบัณฑิต (เทคโนโลยีการศึกษา), มหาวิทยาลัยเกษตรศาสตร์, TH, 2559"
        ],
        "research_interests": [
            "เทคโนโลยีดิจิทัล"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_somnuek_011",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Surasawadee",
        "last_name": "Somnuek",
        "full_name": "Surasawadee Somnuek",
        "full_name_th": "ผศ.ดร. สุรัสวดี สมนึก",
        "role": "อาจารย์ประจำ",
        "email": "surasawadee.so@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิทยาศาสตร์การแพทย์), มหาวิทยาลัยธรรมศาสตร์, TH, 2560"
        ],
        "research_interests": [
            "การส่งเสริมสุขภาพและการพยาบาล",
            "โภชนาการ",
            "การกำหนดอาหาร"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_worasettawat_012",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Tunyakarn",
        "last_name": "Worasettawat",
        "full_name": "Tunyakarn Worasettawat",
        "full_name_th": "ดร. ธันยากานต์ วรเศรษฐวัฒน์",
        "role": "อาจารย์ประจำ",
        "email": "tunyakarn.w@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "วิทยาศาสตรดุษฎีบัณฑิต (วิทยาศาสตร์การกีฬา : วิทยาการส่งเสริมสุขภาพ), จุฬาลงกรณ์มหาวิทยาลัย, TH, 2564"
        ],
        "research_interests": [
            "วิทยาการส่งเสริมสุขภาพ"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_ratsena_013",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "department_th": "ภาควิชาวิทยาศาสตร์การกีฬา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Pasawee",
        "last_name": "Ratsena",
        "full_name": "Pasawee Ratsena",
        "full_name_th": "อ. พศวีร์ ราชเสนา",
        "role": "อาจารย์ประจำ",
        "email": "pasawee.r@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "วิทยาศาสตรมหาบัณฑิต (วิทยาศาสตร์การกีฬา), มหาวิทยาลัยมหิดล, TH, 2568"
        ],
        "research_interests": [
            "วิทยาศาสตร์การกีฬา"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_kutintara_014",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "department_th": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Issadee",
        "last_name": "Kutintara",
        "full_name": "Issadee Kutintara",
        "full_name_th": "ผศ.ดร. อิษฎี กุฏอินทร์",
        "role": "อาจารย์ประจำ",
        "email": "issadee.k@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Philosophy (Sport and Exercise Science : Sport Administration), UNIVERSITY OF NORTHERN COLORADO, US, 2552"
        ],
        "research_interests": [
            "การจัดการการแข่งขันกีฬา",
            "การจัดการการกีฬา",
            "การตลาด"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_poolsawat_015",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "department_th": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Phennipha",
        "last_name": "Poolsawat",
        "full_name": "Phennipha Poolsawat",
        "full_name_th": "ผศ.ดร. เพ็ญนิภา พูลสวัสดิ์",
        "role": "อาจารย์ประจำ",
        "email": "phennipha.p@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "วิทยาศาสตรดุษฎีบัณฑิต (วิทยาศาสตร์การกีฬา แขนงวิชาวิทยาการบริหารจัดการกีฬาและนันทนาการ), จุฬาลงกรณ์มหาวิทยาลัย, TH, 2559"
        ],
        "research_interests": [
            "ท่องเที่ยว",
            "นันทนาการ",
            "การจัดการกีฬา"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_theerasorn_016",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "department_th": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Sid",
        "last_name": "Theerasorn",
        "full_name": "Sid Theerasorn",
        "full_name_th": "รศ.ดร. สิทธิ์ ธีรสรณ์",
        "role": "อาจารย์ประจำ",
        "email": "sid.t@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Business Administration (Business Adminstration), UNIVERSITY OF SARASOTA, US, 2546"
        ],
        "research_interests": [
            "บริหารธุรกิจ"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_noikasem_017",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "department_th": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Sarayut",
        "last_name": "Noikasem",
        "full_name": "Sarayut Noikasem",
        "full_name_th": "ดร. สรายุทธ์ น้อยเกษม",
        "role": "อาจารย์ประจำ",
        "email": "sarayut.n@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Business Administration (Management), UNIVERSITY OF SARASOTA, US, 2553"
        ],
        "research_interests": [
            "Business Management"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_youngseok_018",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "department_th": "ภาควิชาการจัดการการกีฬาและสุขภาพ",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Choi",
        "last_name": "Young Seok",
        "full_name": "Choi Young Seok",
        "full_name_th": "ดร. ชัชชัย เช",
        "role": "อาจารย์ประจำ",
        "email": "youngseok.c@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Sports Science (Taekwondo), DONG-A UNIVERSITY, KR, 2558"
        ],
        "research_interests": [
            "เทควันโด"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_noipan_019",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "department_th": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "academic_title": "ดร.",
        "academic_title_th": "ดร.",
        "first_name": "Wuttigrai",
        "last_name": "Noipan",
        "full_name": "Wuttigrai Noipan",
        "full_name_th": "ดร. วุฒิไกร น้อยพันธ์",
        "role": "อาจารย์ประจำ",
        "email": "wuttigrai.n@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor rerum humanarum (Experimentelle Arbeitsmedizin), UNIVERSITAT ROSTOCK, DE, 2559"
        ],
        "research_interests": [
            "Biomechanics of Cycling"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_kanchanasilanon_020",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "department_th": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Aris",
        "last_name": "Kanchanasilanon",
        "full_name": "Aris Kanchanasilanon",
        "full_name_th": "ผศ.ดร. อาริสร์ กาญจนศิลานนท์",
        "role": "อาจารย์ประจำ",
        "email": "aris.k@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิศวกรรมทางการแพทย์), มหาวิทยาลัยธรรมศาสตร์, TH, 2563"
        ],
        "research_interests": [
            "การวิเคราะห์การเคลื่อนไหว",
            "การนวดเพื่อบำบัดอาการ",
            "การนวดเพื่อสุขภาพ",
            "การนวดทางการกีฬา"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_sriyaphai_021",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "department_th": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Amphorn",
        "last_name": "Sriyaphai",
        "full_name": "Amphorn Sriyaphai",
        "full_name_th": "ผศ.ดร. กภ.อำพร ศรียาภัย",
        "role": "อาจารย์ประจำ",
        "email": "amphorn.s@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิทยาศาสตร์การกีฬา), มหาวิทยาลัยเกษตรศาสตร์, TH, 2557"
        ],
        "research_interests": [
            "การจัดการกีฬา",
            "กีฬากับการแพทย์"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_somthawin_022",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "department_th": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Sompiya",
        "last_name": "Somthawin",
        "full_name": "Sompiya Somthawin",
        "full_name_th": "ผศ. กภ.สมภิยา สมถวิล",
        "role": "อาจารย์ประจำ",
        "email": "sompiya.s@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "วิทยาศาสตรมหาบัณฑิต (วิทยาศาสตร์การกีฬา), มหาวิทยาลัยเกษตรศาสตร์, TH, 2542"
        ],
        "research_interests": [
            "กายภาพบำบัด"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_phueakphong_023",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "department_th": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Pailin",
        "last_name": "Phueakphong",
        "full_name": "Pailin Phueakphong",
        "full_name_th": "ผศ.ดร. กภ.ไพลิน เผือกประคอง",
        "role": "อาจารย์ประจำ",
        "email": "pailin.pu@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (วิศวกรรมทางการแพทย์), มหาวิทยาลัยธรรมศาสตร์, TH, 2564"
        ],
        "research_interests": [
            "การฟื้นฟูการบาดเจ็บ",
            "การประเมินท่าทาง",
            "การวิเคราะห์การเคลื่อนไหว",
            "การยศาสตร์"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "kasetsartu_facultyofs_boonyarom_024",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Sports Science and Health",
        "faculty_th": "คณะวิทยาศาสตร์การกีฬาและสุขภาพ",
        "department": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "department_th": "ภาควิชาวิยาศาสตร์สุขภาพและการเคลื่อนไหว",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Onuma",
        "last_name": "Boonyarom",
        "full_name": "Onuma Boonyarom",
        "full_name_th": "ผศ.ดร. กภ.อรอุมา บุณยารมย์",
        "role": "อาจารย์ประจำ",
        "email": "onuma.b@ku.th",
        "image_url": "",
        "profile_url": "",
        "education": [
            "Doctor of Philosophy (Physical Therapy), SAPPORO MEDICAL UNIVERSITY, JP, 2551"
        ],
        "research_interests": [
            "Rehabilitation Sciences",
            "Electrotherapy"
        ],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
