# Auto-generated from edu.ssru.ac.th TH/EN faculty pages + ssrudlp emails via SKILL.state Reducer (Session: ssru_edu_api_1789023187_8f454a)
EXTRACTED_FACULTIES = [
    {
        "id": "suansunand_facultyofe_phangsanga_001",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาการศึกษาปฐมวัย",
        "department_th": "สาขาวิชาการศึกษาปฐมวัย",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Disira",
        "last_name": "Phangsanga",
        "full_name": "Disira Phangsanga",
        "full_name_th": "อ. ดิษิรา ผางสง่า",
        "role": "อาจารย์ประจำ",
        "email": "disira.ph@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/2f3edb18aebf1e317c3f19f39b9d9a2facf0552b.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Disira_Phan",
        "education": [
            "ค.ม. (การศึกษาปฐมวัย) จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.บ. (การศึกษาปฐมวัย) มหาวิทยาลัยราชภัฎสวนสุนันทา (เกียรตินิยมอันดับ 2)"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_chongcharoen_002",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาการศึกษาปฐมวัย",
        "department_th": "สาขาวิชาการศึกษาปฐมวัย",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Duangkamol",
        "last_name": "Chongcharoen",
        "full_name": "Duangkamol Chongcharoen",
        "full_name_th": "อ.ดร. ดวงกมล จงเจริญ",
        "role": "อาจารย์ประจำ",
        "email": "duangkamol.ch@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/f243079ab3914b3af5e5fa1f54ba244d55850d77.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Duangkamol_Chon",
        "education": [
            "Ph.D. in Education, Keele University, UK",
            "ค.ม. (การศึกษาปฐมวัย) จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.บ. (การศึกษาปฐมวัย) มหาวิทยาลัยราชภัฏสวนสุนันทา"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_noichun_003",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาการศึกษาปฐมวัย",
        "department_th": "สาขาวิชาการศึกษาปฐมวัย",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Nantiya",
        "last_name": "Noichun",
        "full_name": "Nantiya Noichun",
        "full_name_th": "รศ.ดร. นันทิยา น้อยจันทร์",
        "role": "อาจารย์ประจำ",
        "email": "nuntiya.no@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/56c57a136be7b768758a27157e2ec624fcd4961c.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Nuntiya_Noic",
        "education": [
            "ปร.ด. (การบริหารการศึกษา) มหาวิทยาลัยศิลปากร",
            "ค.ม. (การศึกษาปฐมวัย) จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.บ.(การศึกษาปฐมวัย) จุฬาลงกรณ์มหาวิทยาลัย"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_waiyaroop_004",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาการศึกษาปฐมวัย",
        "department_th": "สาขาวิชาการศึกษาปฐมวัย",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Suphanwadee",
        "last_name": "Waiyaroop",
        "full_name": "Suphanwadee Waiyaroop",
        "full_name_th": "ผศ. สุพันธ์วดี ไวยรูป",
        "role": "อาจารย์ประจำ",
        "email": "suphanwadee.wa@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/b439e12db4d745980ca17e5a828b07261ef961dd.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Suphanwadee_Waiy",
        "education": [
            "ค.ม. (การศึกษาปฐมวัย) จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.บ. (การศึกษาปฐมวัย) จุฬาลงกรณ์มหาวิทยาลัย เกียรตินิยมอันดับ 1"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_thitisophonsak_005",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาการศึกษาปฐมวัย",
        "department_th": "สาขาวิชาการศึกษาปฐมวัย",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Thitikan",
        "last_name": "Thitisophonsak",
        "full_name": "Thitikan Thitisophonsak",
        "full_name_th": "อ. ธิติกาญจน์ ฐิติโสภณศักดิ์",
        "role": "อาจารย์ประจำ",
        "email": "thitikan.th@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/3566f0b24cb7ed2df60a12a59d409dca81880936.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Thitikan_Thit",
        "education": [
            "ค.ม. (การศึกษาปฐมวัย) จุฬาลงกรณ์มหาวิทยาลัย เกียรตินิยมอันดับ 2",
            "ค.บ. (การศึกษาปฐมวัย) จุฬาลงกรณ์มหาวิทยาลัย"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_yensiri_006",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาคณิตศาสตร์",
        "department_th": "สาขาวิชาคณิตศาสตร์",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Suranon",
        "last_name": "Yensiri",
        "full_name": "Suranon Yensiri",
        "full_name_th": "อ.ดร. สุรนนท์ เย็นศิริ",
        "role": "อาจารย์ประจำ",
        "email": "suranon.ye@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/2c0c81adcdb2be8b9257de836cbf75b9686e8603.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Suranon_Yens",
        "education": [
            "ปร.ด. (คณิตศาสตร์) มหาวิทยาลัยมหิดล",
            "วท.บ. (คณิตศาสตร์) มหาวิทยาลัยมหิดล"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_srisiriwat_007",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาคณิตศาสตร์",
        "department_th": "สาขาวิชาคณิตศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Tanawat",
        "last_name": "Srisiriwat",
        "full_name": "Tanawat Srisiriwat",
        "full_name_th": "ผศ.ดร. ธนวัฒน์ ศรีศิริวัฒน์",
        "role": "อาจารย์ประจำ",
        "email": "tanawat.sr@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/4fe8ac83dd96bb17324ad25abe7ca807faaa1fb7.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Tanawat_Sris",
        "education": [
            "ปร.ด (นวัตกรรมการจัดการ):มหาวิทยาลัยราชภัฏสวนสุนันทา",
            "ว.ทม.(สถิติประยุกต์) มหาวิทยาลัยธรรมศาสตร์",
            "ค.บ.(คณิตศาสตร์) เกียรตินิยมอันดับ 1 สถาบันราชภัฏสวนสุนันทา"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_jampawai_008",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาคณิตศาสตร์",
        "department_th": "สาขาวิชาคณิตศาสตร์",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Thanatyod",
        "last_name": "Jampawai",
        "full_name": "Thanatyod Jampawai",
        "full_name_th": "ผศ.ดร. ธนัชยศ จำปาหวาย",
        "role": "อาจารย์ประจำ",
        "email": "thanatyod.ja@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/adf6ea154e640fe8ab1df772ca37a88e11f08800.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Thanatyod_Jamp",
        "education": [
            "วทด.(คณิตศาสตร์) จุฬาลงกรณ์มหาวิทยาลัย",
            "วทม.(คณิตศาสตร์) จุฬาลงกรณ์มหาวิทยาลัย",
            "วทบ.(คณิตศาสตร์) จุฬาลงกรณ์มหาวิทยาลัย"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_tinprapa_009",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาคณิตศาสตร์",
        "department_th": "สาขาวิชาคณิตศาสตร์",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Teerawit",
        "last_name": "Tinprapa",
        "full_name": "Teerawit Tinprapa",
        "full_name_th": "ผศ. ตีรวิชช์ ทินประภา",
        "role": "อาจารย์ประจำ",
        "email": "teerawit.ti@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/3ccf72aa2b73a422e13541a017cc4786329f4809.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Teerawit_Tinp",
        "education": [
            "ค.ม. (การศึกษาคณิตศาสตร์) จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.บ. (คณิตศาสตร์) มหาวิทยาลัยราชภัฏสวนสุนันทา"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_fac_010_010",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาคณิตศาสตร์",
        "department_th": "สาขาวิชาคณิตศาสตร์",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "ผศ.",
        "role": "อาจารย์ประจำ",
        "email": "chouang.ut@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/8ea31a02339b07a226eb09298795a4199f888449.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Chouang_Utit",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (ปร.ด.) สาขาการวิจัยและพัฒนาหลักสูตร บัณฑิตวิทยาลัย มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "วท.ม. (การสอนคณิตศาสตร์) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
            "ค.บ. (คณิตศาสตร์) จุฬาลงกรณ์มหาวิทยาลัย",
            "ศษ.ม. (หลักสูตรและการสอน), มหาวิทยาลัยเกษตรศาสตร์",
            "กศ.บ.(สังคมศึกษา), มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "ค.ด.(หลักสูตรและการสอน) จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.ม.(การสอนสังคมศึกษา) จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.บ.(มัธยมศึกษา มนุษยศาสตร์และสังคมศาสตร์ วิชาเอกภาษาไทยและสังคมศึกษา) เกียรตินิยมอันดับ 2 จุฬาลงกรณ์มหาวิทยาลัย",
            "ศษ.ด (เทคโนโลยีการศึกษา) มหาวิทยาลัยเกษตรศาสตร์",
            "วท.ม(เทคโนโลยีสารสนเทศ) มหาวิทยาลัยศรีปทุม",
            "บธ.บ (คอมพิวเตอร์ธุรกิจ) เกียรตินิยมอันดับ1 มหาวิทยาลัยศรีปทุม"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_chanfoy_011",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาคณิตศาสตร์",
        "department_th": "สาขาวิชาคณิตศาสตร์",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Poonyapon",
        "last_name": "Chanfoy",
        "full_name": "Poonyapon Chanfoy",
        "full_name_th": "ผศ. ปุณยพล จันทร์ฝอย",
        "role": "อาจารย์ประจำ",
        "email": "poonyapon.ch@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/b2e26a3582578436c0593aba7996c2124092c5c3.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Poonyapon_Chan",
        "education": [
            "กศ.ม. (คณิตศาสตร์) มหาวิทยาศรีนครินทรวิโรฒ",
            "ค.บ. (คณิตศาสตร์) มหาวิทยาลัยราชภัฏบ้านสมเด็จเจ้าพระยา"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_puttapatimok_012",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาคณิตศาสตร์",
        "department_th": "สาขาวิชาคณิตศาสตร์",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Wariya",
        "last_name": "Puttapatimok",
        "full_name": "Wariya Puttapatimok",
        "full_name_th": "อ. วาริยา พุทธปฏิโมกข์",
        "role": "อาจารย์ประจำ",
        "email": "wariya.pu@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/76f9c867a005630702a3d623b39f6b0aca496701.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Wariya_Putt",
        "education": [
            "วท.ม. (คณิตศาสตร์ประยุกต์) จุฬาลงกรณ์ มหาวิทยาลัย",
            "วท.บ. (คณิตศาสตร์) มหาวิทยาลัยเกษตรศาสตร์"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_jullasapkaewmor_013",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาไทย",
        "department_th": "สาขาวิชาภาษาไทย",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Sirion",
        "last_name": "Jullasap Kaewmoragot",
        "full_name": "Sirion Jullasap Kaewmoragot",
        "full_name_th": "อ.ดร. สิริอร จุลทรัพย์ แก้วมรกฎ",
        "role": "อาจารย์ประจำ",
        "email": "sirion.ju@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/746222d3f9d84e89dc660d1f4ed0e8f3588bb1c2.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Sirion_Jull",
        "education": [
            "ปร.ด. (ไทยศึกษา) มหาวิทยาลัยบูรพา",
            "ค.ม. (การสอนภาษาไทย) จุฬาลงกรณ์มหาวิทยาลัย",
            "ศศ.บ. (ภาษาไทยเพื่อการสื่อสาร) มหาวิทยาลัยหอการค้าไทย"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_satthaphong_014",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาไทย",
        "department_th": "สาขาวิชาภาษาไทย",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Tasanee",
        "last_name": "Satthaphong",
        "full_name": "Tasanee Satthaphong",
        "full_name_th": "ผศ.ดร. ทัศนีย์ เศรษฐพงษ์",
        "role": "อาจารย์ประจำ",
        "email": "tasanee.sa@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/013f2891f9bc9b7ee567dd81314e6dda56a1c981.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Tasanee_Satt",
        "education": [
            "ค.ด. (หลักสูตรและการสอน) จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.ม. (การสอนภาษาไทย) จุฬาลงกรณ์มหาวิทยาลัย",
            "ศษ.บ. (ภาษาไทย) มหาวิทยาลัยศิลปากร เกียรตินิยมอันดับ 2"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_kheannil_015",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาไทย",
        "department_th": "สาขาวิชาภาษาไทย",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Sumana",
        "last_name": "Kheannil",
        "full_name": "Sumana Kheannil",
        "full_name_th": "อ. สุมนา เขียนนิล",
        "role": "อาจารย์ประจำ",
        "email": "sumana.kh@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/f47d0ed9e33e38d690259cda91990154aad1390f.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/SUMANA_KHEA",
        "education": [
            "ศศ.ม. (ภาษาไทย) มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "ศศ.บ. (ภาษาไทย) มหาวิทยาลัยศิลปากร"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_boonhok_016",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาไทย",
        "department_th": "สาขาวิชาภาษาไทย",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Saranpat",
        "last_name": "Boonhok",
        "full_name": "Saranpat Boonhok",
        "full_name_th": "ผศ.ดร. ศรัณย์ภัทร์ บุญฮก",
        "role": "อาจารย์ประจำ",
        "email": "saranpat.bo@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/4127f0d84d94d21105f4563135fb519b7efe0fa8.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Saranpat_Boon",
        "education": [
            "PhD (Cultural, Literary, and Postcolonial Studies) SOAS, University of London, UK,",
            "อ.ม. (ภาษาไทย) จุฬาลงกรณ์มหาวิทยาลัย",
            "PGCert (Learning and Teaching in Higher Education) University of London, UK",
            "อ.บ. (ภาษาไทย) เกียรตินิยมอันดับหนึ่ง จุฬาลงกรณ์มหาวิทยาลัย"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_dechsri_017",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาไทย",
        "department_th": "สาขาวิชาภาษาไทย",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Thidadow",
        "last_name": "Dechsri",
        "full_name": "Thidadow Dechsri",
        "full_name_th": "อ. ธิดาดาว เดชศรี",
        "role": "อาจารย์ประจำ",
        "email": "pdpa@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/ddbace7a11ca52672b9759ab2f11d25cb61eb49f.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Thidadow_Dech",
        "education": [
            "ศศ.ม. (ภาษาไทย) มหาวิทยาลัยธรรมศาสตร์",
            "ศศ.บ. (ภาษาไทย) มหาวิทยาลัยธรรมศาสตร์",
            "ศึกษาศาสตรดุษฎีบัณฑิต (การสอนภาษาอังกฤษสำหรับผู้พูดภาษาอื่น) มหาวิทยาลัยเอ็กซิเตอร์ สหราชอาณาจักร",
            "ศศ.ม. (การสอนภาษาอังกฤษเป็นภาษาต่างประเทศ) มหาวิทยาลัยธรรมศาสตร์",
            "ศศ.บ. (ภาษาฝรั่งเศส) มหาวิทยาลัยขอนแก่น"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_suthanaphinyo_018",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาไทย",
        "department_th": "สาขาวิชาภาษาไทย",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Suphakkhathat",
        "last_name": "Suthanaphinyo",
        "full_name": "Suphakkhathat Suthanaphinyo",
        "full_name_th": "อ. สุภัคธัช สุธนภิญโญ",
        "role": "อาจารย์ประจำ",
        "email": "suphakkhathat.su@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260312/04493414cbfdead1dc00dc0d440b7cda8ac7e7b7.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Suphakkhathat_Suth",
        "education": [
            "ศศ.ม.(ภาษาไทย) มหาวิทยาลัยขอนแก่น",
            "ศศ.บ.(ภาษาไทย) เกียรตินิยมอันดับหนึ่ง มหาวิทยาลัยขอนแก่น"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_praisorn_019",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาไทย",
        "department_th": "สาขาวิชาภาษาไทย",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Benjaporn",
        "last_name": "Praisorn",
        "full_name": "Benjaporn Praisorn",
        "full_name_th": "อ. เบญจพร ไพรศร",
        "role": "อาจารย์ประจำ",
        "email": "benjaporn.pr@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/98b5e397ce8453cc9bb50a779461344c93837de0.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Benjaporn_Prai",
        "education": [
            "ศศ.ม.(ภาษาไทย) มหาวิทยาลัยธรรมศาสตร์",
            "อ.บ.(เอเชียศึกษา) มหาวิทยาลัยศิลปากร"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_unnanantn_020",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาอังกฤษ",
        "department_th": "สาขาวิชาภาษาอังกฤษ",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Thassanant",
        "last_name": "Unnanantn",
        "full_name": "Thassanant Unnanantn",
        "full_name_th": "อ.ดร. ธรรศนันต์ อุนนะนันทน์",
        "role": "อาจารย์ประจำ",
        "email": "thassanant.un@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/4cc1dc9bf2513c15f749f5f04af90f0cedb1b2db.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/THASSANANT_UNNA",
        "education": [
            "ปร.ด. (หลักสูตรและการสอน) มหาวิทยาลัยเกษตรศาสตร์",
            "ศศ.ม. (ภาษาอังกฤษธุรกิจเพื่อการสื่อสารนานาชาติ) มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "ศศ.บ. (ภาษาอังกฤษ) มหาวิทยาลัยราชภัฏพระนคร"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_fac_021_021",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาอังกฤษ",
        "department_th": "สาขาวิชาภาษาอังกฤษ",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "รศ.ดร. วิภาดา ประสารทรัพย์",
        "role": "อาจารย์ประจำ",
        "email": "wipada.pr@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/d82c7c15d572d9ef128554ca46768a24be55b811.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/WIPADA_PRAS",
        "education": [
            "D.Ed.(TESOL Policy) The university of Melbourne, Australia",
            "กศ.ม. (การสอนภาษาอังกฤษ) มหาวิทยาลัยศรีนครินทรวิโรฒ ประสานมิตร",
            "กศ.บ. (ภาษาอังกฤษ) มหาวิทยาลัยศรีนครินทรวิโรฒมหาสารคาม เกียรตินิยมอันดับ 1"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_plailek_022",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาอังกฤษ",
        "department_th": "สาขาวิชาภาษาอังกฤษ",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Teeraporn",
        "last_name": "Plailek",
        "full_name": "Teeraporn Plailek",
        "full_name_th": "ผศ.ดร. ธีราภรณ์ พลายเล็ก",
        "role": "อาจารย์ประจำ",
        "email": "teeraporn.pl@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/ab4a3b76fdc93e0a05e4d6edef0630dc65a3726c.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Teeraporn_Plai",
        "education": [
            "ปรัชญาดุษฎีบัณฑิต (ภาษาศาสตร์ : การสอนภาษาอังกฤษเป็นภาษาต่างประเทศ) มหาวิทยาลัยราชภัฏสวนสุนันทา",
            "การศึกษามหาบัณฑิต (การสอนภาษาอังกฤษ) มหาวิทยาลัยนเรศวร",
            "ศิลปศาสตร์บัณฑิต (ภาษาอังกฤษธุรกิจ) มหาวิทยาลัยสวนดุสิต"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_thitivesa_023",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาอังกฤษ",
        "department_th": "สาขาวิชาภาษาอังกฤษ",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Duangkamol",
        "last_name": "Thitivesa",
        "full_name": "Duangkamol Thitivesa",
        "full_name_th": "ผศ.ดร. ดวงกมล ฐิติเวส",
        "role": "อาจารย์ประจำ",
        "email": "duangkamol.th@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/c2246e7b1c2b3a37ea5cb91d03c291b7aa04e2d7.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/DUANGKAMOL_THIT",
        "education": [
            "D.Ed. (TESOL Policy) The university of Melbourne, Australia",
            "M.S. in Ed. (Workforce Education)",
            "ศศ.บ. (ภาษาอังกฤษ) มหาวิทยาลัยธรรมศาสตร์"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_seubsang_024",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาอังกฤษ",
        "department_th": "สาขาวิชาภาษาอังกฤษ",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Pintipa",
        "last_name": "Seubsang",
        "full_name": "Pintipa Seubsang",
        "full_name_th": "อ.ดร. พิณทิพา สืบแสง",
        "role": "อาจารย์ประจำ",
        "email": "pintipa.se@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/f616faebafa9a51c3ca182614bfb3b3ac4c71b7a.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Pintipa_Seub",
        "education": [
            "Ph.D. in Education (Teaching English to Speakers of Other Languages), Monash University",
            "MA English as an International Language, The University of Melbourne",
            "ศศ.บ. (ภาษาอังกฤษ) มหาวิทยาลัยกรุงเทพ เกียรตินิยม"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_ngiwline_025",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาภาษาอังกฤษ",
        "department_th": "สาขาวิชาภาษาอังกฤษ",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Phuwitch",
        "last_name": "Ngiwline",
        "full_name": "Phuwitch Ngiwline",
        "full_name_th": "อ.ดร. ภูวิชญ์ งิ้วลาย",
        "role": "อาจารย์ประจำ",
        "email": "phuwitch.ng@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/9c4e492eab16654dd15424e43f8b3f5bfd069ae7.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Phuwitch_Ngiw",
        "education": [
            "ปร.ด.(ภาษาศาสตร์) มหาวิทยาลัยราชภัฏสวนสุนันทา",
            "กศ.ม.(ภาษาอังกฤษ) มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "ศน.บ.(ภาษาอังกฤษ) มหาวิทยาลัยมหามกุฏราชวิทยาลัย"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_sukrachan_026",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "department_th": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Thadcha",
        "last_name": "Sukrachan",
        "full_name": "Thadcha Sukrachan",
        "full_name_th": "อ.ดร. ธัชชา ศุกระจันทร์",
        "role": "อาจารย์ประจำ",
        "email": "thadcha.su@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/d90481a35ddbbd1bf44a29ddbee4eb7f266eaf55.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Thadcha_Sukr",
        "education": [
            "ทยาศาสตรดุษฎีบัณฑิต (เทคโนโลยีชีวภาพ) จุฬาลงกรณ์มหาวิทยาลัย"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_tientong_027",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "department_th": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Sumalee",
        "last_name": "Tientong",
        "full_name": "Sumalee Tientong",
        "full_name_th": "รศ.ดร. สุมาลี เทียนทองดี",
        "role": "อาจารย์ประจำ",
        "email": "sumalee.ti@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/a5c3a1191261cde968c07db34bdba90e6cdda658.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Sumalee_Tien",
        "education": [
            "Postdoctoral Research Fellow ( Physics Ed.) Harvard University, USA",
            "กศ.ด. (วิทยาศาสตรศึกษา/ฟิสิกส์) มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "M.S. (Physics) University of Rhode Island, USA",
            "ป.บัณฑิต (วิชาชีพครู) มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "วท.บ. ( ฟิสิกส์) มหาวิทยาลัยศรีนครินทรวิโรฒ"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_chuchuoy_028",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "department_th": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Kornkamol",
        "last_name": "Chuchuoy",
        "full_name": "Kornkamol Chuchuoy",
        "full_name_th": "ผศ.ดร. กรกมล ชูช่วย",
        "role": "อาจารย์ประจำ",
        "email": "kornkamol.ch@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/2390931682d603645c1131cab845242b453abb72.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Kornkamol_Chuc",
        "education": [
            "ปร.ด. (นวัตกรรมการจัดการ) มหาวิทยาลัยราชภัฎสวนสุนันทา",
            "วศ.ม. (เทคโนโลยีการจัดการพลังงานสิ่งแวดล้อม) มหาวิทยาลัยธรรมศาสตร์",
            "วท.บ. (เคมีทรัพยากรสิ่งแวดล้อม) สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_ratniyom_029",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "department_th": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "academic_title": "รศ.ดร.",
        "academic_title_th": "รศ.ดร.",
        "first_name": "Jadsada",
        "last_name": "Ratniyom",
        "full_name": "Jadsada Ratniyom",
        "full_name_th": "รศ.ดร. เจษฎา ราษฎร์นิยม",
        "role": "อาจารย์ประจำ",
        "email": "jadsada.ra@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/001b8ea8623dadbca040809a9d1a88dc8b42ad7b.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Jadsada_Ratn",
        "education": [
            "ปร.ด. (เคมีอนินทรีย์) มหาวิทยาลัยมหิดล",
            "วท.บ. (เคมี) มหาวิทยาลัยมหิดล"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_fac_030_030",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "department_th": "สาขาวิชาวิทยาศาสตร์ทั่วไป",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "ผศ.ดร. ภาวิณี รัตนคอน",
        "role": "อาจารย์ประจำ",
        "email": "pawinee.ra@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/b0809b328085294ba4c83df969994499cadaec8b.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Pawinee_Ratt",
        "education": [
            "ปร.ด. (วิทยาศาสตร์ศึกษา) มหาวิทยาลัยเกษตรศาสตร์",
            "วท.ม. (ชีววิทยา) มหาวิทยาลัยเกษตรศาสตร์",
            "วท.บ. (ชีววิทยา) มหาวิทยาลัยศรีนครินทรวิโรฒ"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_tipjaradmetha_031",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาสังคมศึกษา",
        "department_th": "สาขาวิชาสังคมศึกษา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Teerarat",
        "last_name": "Tipjaradmetha",
        "full_name": "Teerarat Tipjaradmetha",
        "full_name_th": "อ. ธีรารัตน์ ทิพย์จรัสเมธา",
        "role": "อาจารย์ประจำ",
        "email": "teerarat.ti@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/0baf49b838b633b40345b59e7e38e7e0a0db0460.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Teerarat_Tipj",
        "education": [
            "ศศ.ม. (ประวัติศาสตร์เอเชีย), มหาวิทยาลัยศรีนครินทรวิโรฒ ประสานมิตร",
            "ศศ.บ. (ประวัติศาสตร์),มหาวิทยาลัยศรีนครินทรวิโรฒ ประสานมิตร"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_piromrat_032",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาสังคมศึกษา",
        "department_th": "สาขาวิชาสังคมศึกษา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Kannika",
        "last_name": "Piromrat",
        "full_name": "Kannika Piromrat",
        "full_name_th": "ผศ.ดร. กรรณิการ์ ภิรมย์รัตน์",
        "role": "อาจารย์ประจำ",
        "email": "kannika.bh@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/5a19eac9cb9525ec2f6a1ec9a1e058a0dfc33eae.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Kannika_Bhir",
        "education": [
            "ปร.ด. (การวิจัยและพัฒนาการสอนเทคนิคศึกษา),มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ",
            "ศษ.ม. (การวิจัยการศึกษา), มหาวิทยาลัยรามคำแหง",
            "วท.บ. (ภูมิศาสตร์), มหาวิทยาลัยรามคำแหง"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_ruttanawarn_033",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาสังคมศึกษา",
        "department_th": "สาขาวิชาสังคมศึกษา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Weerapojt",
        "last_name": "Ruttanawarn",
        "full_name": "Weerapojt Ruttanawarn",
        "full_name_th": "อ. วีรพจน์ รัตนวาร",
        "role": "อาจารย์ประจำ",
        "email": "weerapoot.ru@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/15c346444a45a97901d13a840bb80b3ce11e65a3.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Weerapoot_Rutt",
        "education": [
            "ศศ.ม. (สังคมศาสตร์เพื่อการพัฒนา) สถาบันราชภัฏบ้านสมเด็จเจ้าพระยา",
            "นศ.บ. (โฆษณา) มหาวิทยาลัยสยาม"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_wongprasert_034",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาสังคมศึกษา",
        "department_th": "สาขาวิชาสังคมศึกษา",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Lanlana",
        "last_name": "Wongprasert",
        "full_name": "Lanlana Wongprasert",
        "full_name_th": "อ.ดร. ลัลนา วงษ์ประเสริฐ",
        "role": "อาจารย์ประจำ",
        "email": "lanlana.wo@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/58f965ab388b26fcb7aea0bc288ce9fd74980556.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Lanlana_Wong",
        "education": [
            "ปร.ด. (พัฒนศึกษา) มหาวิทยาลัยศิลปากร",
            "กศ.ม. (ประวัติศาสตร์) มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "นศ.บ. (วิทยุกระจายเสียงและวิทยุโทรทัศน์) มหาวิทยาลัยเซนต์จอห์น"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_jewpanich_035",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "department_th": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Chaiwat",
        "last_name": "Jewpanich",
        "full_name": "Chaiwat Jewpanich",
        "full_name_th": "อ.ดร. ชัยวัฒน์ จิวพานิชย์",
        "role": "อาจารย์ประจำ",
        "email": "chaiwat.je@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/783f2b1cbadd73fe91af0ddea90bb14d9f74b6c6.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Chaiwat_Jewp",
        "education": [
            "ปร.ด.(เทคโนโลยีสารสนเทศและการสื่อสารเพื่อการศึกษา) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ",
            "ค.อ.ม. (เทคโนโลยีเทคนิคศึกษา)มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ",
            "ค.บ. (คอมพิวเตอร์ศึกษา) สถาบันราชภัฏสวนสุนันทา"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_kaewrattanapat_036",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "department_th": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Nutthapat",
        "last_name": "Kaewrattanapat",
        "full_name": "Nutthapat Kaewrattanapat",
        "full_name_th": "ผศ.ดร. ณัฐภัทร แก้วรัตนภัทร์",
        "role": "อาจารย์ประจำ",
        "email": "nutthapat.ke@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/592efa98670d94f84b8fa7fce4b570f9674bcbd2.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Nutthapat_Kaew",
        "education": [
            "ปร.ด.(เทคโนโลยีสารสนเทศและการสื่อสาร) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ",
            "วิทยาศาสตรมหาบัณฑิต (สารสนเทศ) สถาบันเทคโนโลยีพระจอมเกล้าพระนครเหนือ"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_poolklai_037",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "department_th": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Sinchai",
        "last_name": "Poolklai",
        "full_name": "Sinchai Poolklai",
        "full_name_th": "ผศ.ดร. ศิลป์ชัย พูลคล้าย",
        "role": "อาจารย์ประจำ",
        "email": "sinchai.po@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/aac2ce7c44a3e8d7a732bbba74a4544062a2e3f3.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Sinchai_Pool",
        "education": [
            "ปร.ด. (เทคโนโลยีทางการศึกษา) มหาวิทยาลัยบรูพา",
            "ศษ.ม. (เทคโนโลยีทางการศึกษา) มหาวิทยาลัยเกษตรศาสตร์",
            "ศศ.บ. (พลศึกษา) มหาวิทยาลับเกษตรศาสตร์"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_intarapoo_038",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "department_th": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Aekkaphob",
        "last_name": "Intarapoo",
        "full_name": "Aekkaphob Intarapoo",
        "full_name_th": "อ. เอกภพ อินทรภู่",
        "role": "อาจารย์ประจำ",
        "email": "aekkaphob.in@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/c954f3e6f2bf809a535e1fe08140a55cedae2e19.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Aekkaphob_Inta",
        "education": [
            "ศษ.ม. (เทคโนโลยีทางการศึกษา) มหาวิทยาลัยเกษตรศาสตร์",
            "กศ.บ. (เทคโนโลยีทางการศึกษา) มหาวิทยาลัยศรีนครินทรวิโรฒ"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_srima_039",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "department_th": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Sudarat",
        "last_name": "Srima",
        "full_name": "Sudarat Srima",
        "full_name_th": "ผศ.ดร. สุดารัตน์ ศรีมา",
        "role": "อาจารย์ประจำ",
        "email": "sudarat.sr@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/084c591ed588a9ec9fea37c58670cf05c7df0156.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Sudarat_Srim",
        "education": [
            "ปร.ด.(เทคโนโลยีสารสนเทศและการสื่อสาร) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ",
            "กศม. (การศึกษามหาบัณฑิต) มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "ค.บ.(ครุศาสตร์บัณฑิต) มหาวิทยาลัยราชภัฏสวนสุนันทา"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_ploysri_040",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "department_th": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Wat",
        "last_name": "Ploysri",
        "full_name": "Wat Ploysri",
        "full_name_th": "ผศ.ดร. วัฒน์ พลอยศรี",
        "role": "อาจารย์ประจำ",
        "email": "wat.pl@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/4b55138c51ca492e5478f40d748b66cacdb1028d.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Wat_Ploy",
        "education": [
            "ครุศาสตร์อุตสาหกรรมดุษฎีบัณฑิต (ค.อ.ด.) สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_cheerapakorn_041",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "department_th": "สาขาวิชานวัตกรรมและเทคโนโลยีการศึกษา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Pasawut",
        "last_name": "Cheerapakorn",
        "full_name": "Pasawut Cheerapakorn",
        "full_name_th": "อ. พรรษวุฒิ ชีระภากร",
        "role": "อาจารย์ประจำ",
        "email": "pasawut.ch@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/24ee1d2b3c405bd1675c8863f5ac3632cb84e5a0.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Pasawut_Chee",
        "education": [
            "วท.ม (วิทยาศาสตร์มหาบัณฑิต) สาขาเทคโนโลยีสารสนเทศเพื่อการสื่อสารและการศึกษา มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_eakwonnang_042",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "กลุ่มวิชาชีพครู",
        "department_th": "กลุ่มวิชาชีพครู",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Wipawan",
        "last_name": "Eakwonnang",
        "full_name": "Wipawan Eakwonnang",
        "full_name_th": "ผศ.ดร. วิภาวรรณ เอกวรรณัง",
        "role": "อาจารย์ประจำ",
        "email": "wipawan.ea@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/c564ae510c0d6a264f00ac5d1e938540c52de9fb.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Wipawan_Eakw",
        "education": [
            "ศษ.ด. (การวิจัยและประเมินทางการศึกษา) มหาวิทยาลัยเกษตรศาสตร์",
            "ศษ.ม (การวิจัยและสถิติทางการศึกษา) มหาวิทยาลัยเชียงใหม่",
            "ศษ.บ (การวัดและประเมินผลทางการศึกษา มหาวิทยาลัยสงขลานครินทร์)"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_sivaskunraj_043",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "กลุ่มวิชาชีพครู",
        "department_th": "กลุ่มวิชาชีพครู",
        "academic_title": "ผศ.",
        "academic_title_th": "ผศ.",
        "first_name": "Panuwat",
        "last_name": "Sivaskunraj",
        "full_name": "Panuwat Sivaskunraj",
        "full_name_th": "ผศ. ภาณุวัฒน์ ศิวะสกุลราช",
        "role": "อาจารย์ประจำ",
        "email": "panuwat.si@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/17caabf47ffd29f74a27e166d57ecbadcd9e39a4.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/PANUWAT_SIVA",
        "education": [
            "ศศ.ม. (จิตวิทยาการปรึกษา) จุฬาลงกรณ์มหาวิทยาลัย",
            "วท.บ. (จิตวิทยาอุตสาหกรรม) มหาวิทยาลัยเกษตรศาสตร์"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_fac_044_044",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "กลุ่มวิชาชีพครู",
        "department_th": "กลุ่มวิชาชีพครู",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "ผศ.ดร. พัชราภรณ์ พิลาสมบัติ",
        "role": "อาจารย์ประจำ",
        "email": "patcharaporn.pi@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/d420489892e5c0728df6e040556becd8067436a9.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Patcharaporn_Pila",
        "education": [
            "ค.ด. (หลักสูตรและการสอน) จุฬาลงกรณ์มหาวิทยาลัย",
            "ศษ.ม. (วิจัยและประเมินผลการศึกษา) มหาวิทยาลัยเกษตรศาสตร์",
            "ศศ.บ. (ภาษาอังกฤษ) มหาวิทยาลัยราชภัฏพระนคร"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_petcharaporn_045",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "กลุ่มวิชาชีพครู",
        "department_th": "กลุ่มวิชาชีพครู",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Kalanyoo",
        "last_name": "Petcharaporn",
        "full_name": "Kalanyoo Petcharaporn",
        "full_name_th": "อ. กลัญญู เพชราภรณ์",
        "role": "อาจารย์ประจำ",
        "email": "kalanyoo.pe@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/05890cf694dca57a53fdccf95e4d44646d8957a0.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Kalanyoo_Petc",
        "education": [
            "ศศ.ม.(จิตวิทยาการศึกษาและการแนะแนว) มหาวิทยาลัยเกษตรศาสตร์",
            "ศศ.บ. (ศึกษาศาสตร์) วิชาเอกจิตวิทยาและการแนะแนว มหาวิทยาลัยสงขลานครินทร์"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_boonphadung_046",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "กลุ่มวิชาชีพครู",
        "department_th": "กลุ่มวิชาชีพครู",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Suttipong",
        "last_name": "Boonphadung",
        "full_name": "Suttipong Boonphadung",
        "full_name_th": "ผศ.ดร. สุทธิพงศ์ บุญผดุง",
        "role": "อาจารย์ประจำ",
        "email": "suttipong.bo@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/3fd388dd91816ae5be826fa8366f2da2c48f08a4.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/SUTTIPONG_BOON",
        "education": [
            "ศษ.ด.(หลักสูตรและการสอน) มหาวิทยาลัยเกษตรศาสตร์",
            "กศ.ม.(การวัดผลการศึกษา) มหาวิทยาลัยศรีนครินทรวิโรฒ ประสานมิตร",
            "ค.บ. (คณิตศาสตร์) วิทยาลัยครูสวนสุนันทา เกียรตินิยมอันดับ 2 Dip. in Educational Mathematics Hiroshima University, Japan Cert. in Applied Mathematics Newcastle University, Australia"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_suksomjit_047",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "กลุ่มวิชาชีพครู",
        "department_th": "กลุ่มวิชาชีพครู",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Anchana",
        "last_name": "Suksomjit",
        "full_name": "Anchana Suksomjit",
        "full_name_th": "ผศ.ดร. อัญชนา สุขสมจิตร",
        "role": "อาจารย์ประจำ",
        "email": "anchana.so@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/e8302b256abd15454dc3420b49edf7e296a61e8d.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Anchana_Sook",
        "education": [
            "ค.ด. (เทคโนโลยีและสื่อสารการศึกษา),จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.ม. (โสตทัศนศึกษา),จุฬาลงกรณ์มหาวิทยาลัย",
            "นศ.ม. (การสื่อสารมวลชน),จุฬาลงกรณ์มหาวิทยาลัย",
            "นศ.บ.(ภาพยนตร์),มหาวิทยาลัยสุโขทัยธรรมาธิราช",
            "ค.บ.(เทคโนโลยีการศึกษา),จุฬาลงกรณ์มหาวิทยาลัย"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_lertamornsak_048",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "กลุ่มวิชาชีพครู",
        "department_th": "กลุ่มวิชาชีพครู",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Ganratchakan",
        "last_name": "Lertamornsak",
        "full_name": "Ganratchakan Lertamornsak",
        "full_name_th": "ผศ.ดร. กัญญ์รัชการย์ เลิศอมรศักดิ์",
        "role": "อาจารย์ประจำ",
        "email": "ganratchakan.le@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/95ce32a0fc15a924b03c9cbfceac414f6d7a8757.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Ganratchakan_Lert",
        "education": [
            "ปร.ด. (บริหารการศึกษาและภาวะผู้นำ) คณะศึกษาศาสตร์ สาขาการบริหารการศึกษาและภาวะผู้นำ มหาวิทยาลัยเซนต์จอห์น",
            "นศ.ม. (นิเทศธุรกิจ) คณะนิเทศศาสตร์ สาขานิเทศธุรกิจ มหาวิทยาลัยธุรกิจบัณฑิต",
            "นศ.บ. (วิทยุ-โทรทัศน์) คณะนิเทศศาสตร์ สาขาวิทยุ-โทรทัศน์ มหาวิทยาลัยเซนต์จอห์น"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_fac_049_049",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "กลุ่มวิชาชีพครู",
        "department_th": "กลุ่มวิชาชีพครู",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "",
        "last_name": "",
        "full_name": "",
        "full_name_th": "ผศ.ดร. ปวรี กาญจนภี นิลผาย",
        "role": "อาจารย์ประจำ",
        "email": "pawaree.ni@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/fabd50a5f51a56a63256fb9876eb7a03c80c74c1.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Pawaree_Nilp",
        "education": [
            "ปร.ด. (การวิจัยพฤติกรรมศาสตร์ประยุกต์) มหาวิทยาลัยศรีนครินทรวิโรฒ",
            "ค.ม. (จิตวิทยาการศึกษา) จุฬาลงกรณ์มหาวิทยาลัย",
            "วท.บ. (ศึกษาศาสตร์-เกษตร) เกียรตินิยมอันดับ 2 มหาวิทยาลัยเกษตรศาสตร์"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_pradubsri_050",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาประถมศึกษา",
        "department_th": "สาขาวิชาประถมศึกษา",
        "academic_title": "อ.",
        "academic_title_th": "อ.",
        "first_name": "Malai",
        "last_name": "Pradubsri",
        "full_name": "Malai Pradubsri",
        "full_name_th": "อ. มาลัย ประดับศรี",
        "role": "อาจารย์ประจำ",
        "email": "malai.pr@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/e820b40518565847c3d19476cca9c0dbc429ed52.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Malai_Prad",
        "education": [
            "ศษ.ม.(จิตวิทยาการศึกษาพิเศษ) มหาวิทยาลัยรามคำแหง",
            "ค.บ.(การศึกษาพิเศษ) สถาบันราชภัฏสวนดุสิต"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_udomphol_051",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาประถมศึกษา",
        "department_th": "สาขาวิชาประถมศึกษา",
        "academic_title": "ผศ.ดร.",
        "academic_title_th": "ผศ.ดร.",
        "first_name": "Boonrudee",
        "last_name": "Udomphol",
        "full_name": "Boonrudee Udomphol",
        "full_name_th": "ผศ.ดร. บุญฤดี อุดมผล",
        "role": "อาจารย์ประจำ",
        "email": "boonrudee.ud@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/dbb0bcdf971584519a0e3ad5ab61709a2fb399b3.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Boonrudee_Udom",
        "education": [
            "พธ.ด.(พุทธบริหารการศึกษา) มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย",
            "ค.ม.(ประถมศึกษา) จุฬาลงกรณ์มหาวิทยาลัย",
            "ค.บ. (ประถมศึกษา) จุฬาลงกรณ์มหาวิทยาลัย"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_plailek_052",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาประถมศึกษา",
        "department_th": "สาขาวิชาประถมศึกษา",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Weerayuth",
        "last_name": "Plailek",
        "full_name": "Weerayuth Plailek",
        "full_name_th": "อ.ดร. วีรยุทธ พลายเล็ก",
        "role": "อาจารย์ประจำ",
        "email": "weerayuth.pl@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/8a0429434e627e856cec2ae42eb801c2d4a81270.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Weerayuth_Plai",
        "education": [
            "ปร.ด. :(หลักสูตรและการสอน) มหาวิทยาลัยศิลปากร",
            "กศ.ม. : (การประถมศึกษา) มหาวิทยาลัยศรีนครินทรวิโรฒ ประสานมิตร",
            "ค.บ. (การประถมศึกษา) สถาบันราชภัฏสวนสุนันทา"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    },
    {
        "id": "suansunand_facultyofe_untinagon_053",
        "university": "Suan Sunandha Rajabhat University",
        "university_th": "มหาวิทยาลัยราชภัฏสวนสุนันทา",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะครุศาสตร์",
        "department": "สาขาวิชาประถมศึกษา",
        "department_th": "สาขาวิชาประถมศึกษา",
        "academic_title": "อ.ดร.",
        "academic_title_th": "อ.ดร.",
        "first_name": "Pattra",
        "last_name": "Untinagon",
        "full_name": "Pattra Untinagon",
        "full_name_th": "อ.ดร. ภัทรา อุ่นทินกร",
        "role": "อาจารย์ประจำ",
        "email": "pattra.un@ssru.ac.th",
        "image_url": "https://edu.ssru.ac.th/useruploads/images/20260306/15de25f28b1af831f2cda96be30c690f3561a721.png",
        "profile_url": "https://ssrudlp.ssru.ac.th/teacher/Pattra_Unti",
        "education": [
            "ปร.ด. :(หลักสูตรและการสอน) มหาวิทยาลัยศิลปากร",
            "กศ.ม. : (การประถมศึกษา) มหาวิทยาลัยศรีนครินทรวิโรฒ ประสานมิตร",
            "ค.บ. (การประถมศึกษา) สถาบันราชภัฏสวนสุนันทา"
        ],
        "research_interests": [],
        "featured_publications": [],
        "scholar_url": "",
        "confidence_score": 0.95
    }
]
