# Complete Curricula Dataset for Srinakharinwirot (SWU), Silpakorn (SU), and Burapha (BUU)

SWU_SU_BUU_FULL_COURSES = [
    # =========================================================================
    # SWU (มศว ประสานมิตร & องครักษ์)
    # =========================================================================
    {
        "id": "swu_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Medicine",
        "department_th": "สาขาวิชาแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "252 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "ผลิตแพทย์ผู้เชี่ยวชาญการตรวจรักษาโรคและหัตถการคลินิก พร้อมศูนย์การแพทย์สมเด็จพระเทพรัตนราชสุดาฯ สยามบรมราชกุมารี และศูนย์การแพทย์ปัญญานันทภิกขุ ชลประทาน",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิก ณ ศูนย์การแพทย์สมเด็จพระเทพฯ มศว องครักษ์ และ รพ.ชลประทาน", "ศูนย์ฝึกทักษะการแพทย์เสมือนจริงและนวัตกรรมเวชพันธุศาสตร์", "โครงการร่วมผลิตแพทย์กับ University of Nottingham (UK)"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไปและแพทย์เฉพาะทาง", "แพทย์ประจำโรงพยาบาลรัฐและเอกชนชั้นนำ", "อาจารย์แพทย์และนักวิจัยทางการแพทย์"],
        "tags": ["Medicine", "Doctor", "Health Science", "SWU Medicine", "Nottingham"],
        "website_url": "https://med.swu.ac.th"
    },
    {
        "id": "swu_dent_dds",
        "title_th": "หลักสูตรทันตแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Dental Surgery Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ท.บ. (ทันตแพทยศาสตรบัณฑิต)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Dentistry",
        "department_th": "สาขาวิชาทันตแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "236 หน่วยกิต",
        "tuition_per_semester": "30,000 บาท",
        "tuition_total": "360,000 บาท",
        "description": "คณะทันตแพทยศาสตร์ใจกลางอโศก เพียบพร้อมด้วยโรงพยาบาลทันตกรรมและเทคโนโลยี Digital Dentistry ครบวงจร",
        "curriculum_highlights": ["โรงพยาบาลทันตกรรม คณะทันตแพทยศาสตร์ มศว ประสานมิตร", "การใช้ระบบ 3D Intraoral Scanner และการออกแบบรอยยิ้มดิจิทัล", "การฝึกทักษะคลินิกทันตกรรมเฉพาะทางทุกแขนง"],
        "career_paths": ["ทันตแพทย์ในโรงพยาบาลรัฐและเอกชน", "ทันตแพทย์เฉพาะทาง", "เจ้าของคลินิกทันตกรรม"],
        "tags": ["Dentistry", "Dental", "Doctor of Dental Surgery", "SWU Dentistry", "Asoke"],
        "website_url": "https://dent.swu.ac.th"
    },
    {
        "id": "swu_pt_bsc_physical_therapy",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชากายภาพบำบัด",
        "title_en": "Bachelor of Science Program in Physical Therapy",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (กายภาพบำบัด)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Physical Therapy",
        "faculty_th": "คณะกายภาพบำบัด",
        "department": "Department of Physical Therapy",
        "department_th": "สาขาวิชากายภาพบำบัด",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "คณะกายภาพบำบัดแห่งแรกและแห่งเดียวของไทยที่เป็นคณะอิสระ เชี่ยวชาญการฟื้นฟูกล้ามเนื้อ ระบบประสาท และกายภาพบำบัดทางการกีฬา",
        "curriculum_highlights": ["คลินิกกายภาพบำบัด มศว ประสานมิตร และ มศว องครักษ์", "การใช้นวัตกรรมวารีบำบัด (Hydrotherapy) และเครื่องมือกายภาพบำบัดระดับสูง", "การดูแลและฟื้นฟูสมรรถภาพนักกีฬาทีมชาติและผู้สูงอายุ"],
        "career_paths": ["นักกายภาพบำบัดประจำโรงพยาบาลรัฐและเอกชน", "นักกายภาพบำบัดประจำศูนย์เวชศาสตร์การกีฬาและสโมสรกีฬา", "เจ้าของคลินิกกายภาพบำบัด"],
        "tags": ["Physical Therapy", "Rehabilitation", "Hydrotherapy", "Sports Medicine", "SWU PT"],
        "website_url": "https://pt.swu.ac.th"
    },
    {
        "id": "swu_fa_bfa_acting_directing",
        "title_th": "หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาวิชาศิลปะการแสดง (การแสดงและกำกับการแสดง)",
        "title_en": "Bachelor of Fine Arts Program in Performing Arts (Acting and Directing)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศป.บ. (ศิลปะการแสดง)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Fine Arts",
        "faculty_th": "คณะศิลปกรรมศาสตร์",
        "department": "Department of Performing Arts",
        "department_th": "ภาควิชาศิลปะการแสดง",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "176,000 บาท",
        "description": "อันดับ 1 ด้านการผลิตนักแสดง ผู้กำกับ และคนเบื้องหลังในอุตสาหกรรมบันเทิง ละครเวที ละครโทรทัศน์ และภาพยนตร์ของไทย",
        "curriculum_highlights": ["โรงละครและสตูดิโอการแสดง Black Box มาตรฐานสากล", "การฝึกทักษะการแสดง Voice, Movement และ Method Acting ขั้นสูง", "ศิษย์เก่าดำรงตำแหน่งนักแสดงแถวหน้าและผู้กำกับมือรางวัลของประเทศ"],
        "career_paths": ["นักแสดงมืออาชีพ (Actor / Actress)", "ผู้กำกับการแสดง (Director)", "Acting Coach และผู้เขียนบท"],
        "tags": ["Performing Arts", "Acting", "Directing", "Fine Arts", "SWU Fine Arts"],
        "website_url": "https://fofa.swu.ac.th"
    },

    # =========================================================================
    # SILPAKORN UNIVERSITY (SU - วังท่าพระ & สนามจันทร์)
    # =========================================================================
    {
        "id": "su_dec_bfa_visual_comm",
        "title_th": "หลักสูตรศิลปบัณฑิต สาขาวิชาการออกแบบนิเทศศิลป์ (Visual Communication Design)",
        "title_en": "Bachelor of Fine Arts Program in Visual Communication Design",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศ.บ. (การออกแบบนิเทศศิลป์)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Decorative Arts",
        "faculty_th": "คณะมัณฑนศิลป์",
        "department": "Department of Visual Communication Design",
        "department_th": "ภาควิชาการออกแบบนิเทศศิลป์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "คณะมัณฑนศิลป์ วังท่าพระ เชี่ยวชาญการออกแบบกราฟิก อัตลักษณ์แบรนด์ ภาพประกอบ (Illustration) แอนิเมชัน และการออกแบบ UI/UX",
        "curriculum_highlights": ["การฝึกทักษะการออกแบบความคิดสร้างสรรค์ระดับประเทศ ณ วิทยาเขตวังท่าพระ", "การประกวดผลงานและแสดงนิทรรศการธีสิส ณ หอศิลปวัฒนธรรมแห่งกรุงเทพฯ (BACC)", "ศิษย์เก่าครองรางวัลด้านการออกแบบกราฟิกระดับโลก (D&AD, Red Dot, Cannes Lions)"],
        "career_paths": ["Creative Director / Art Director", "Brand Identity & Graphic Designer", "UI/UX Designer", "Professional Illustrator"],
        "tags": ["Visual Communication", "Graphic Design", "Decorative Arts", "Illustration", "Silpakorn"],
        "website_url": "https://dec.su.ac.th"
    },
    {
        "id": "su_dec_bfa_interior",
        "title_th": "หลักสูตรศิลปบัณฑิต สาขาวิชาการออกแบบภายใน (Interior Design)",
        "title_en": "Bachelor of Fine Arts Program in Interior Design",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศ.บ. (การออกแบบภายใน)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Decorative Arts",
        "faculty_th": "คณะมัณฑนศิลป์",
        "department": "Department of Interior Design",
        "department_th": "ภาควิชาการออกแบบภายใน",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "20,000 บาท",
        "tuition_total": "160,000 บาท",
        "description": "มุ่งเน้นการออกแบบตกแต่งภายในที่มีเอกลักษณ์ทางศิลปวัฒนธรรมผสานความทันสมัย โรงแรม รีสอร์ท และพื้นที่พาณิชยศิลป์",
        "curriculum_highlights": ["การออกแบบพื้นที่อยู่อาศัย โรงแรมระดับลักชัวรี และพื้นที่เชิงพาณิชย์", "การผสานงานช่างฝีมือไทยเข้ากับการออกแบบภายในร่วมสมัย", "การใช้ซอฟต์แวร์ 3D Rendering และ Lighting Simulation ขั้นสูง"],
        "career_paths": ["มัณฑนากรและนักออกแบบภายใน (Interior Designer)", "Commercial & Retail Space Designer", "Exhibition & Stage Designer"],
        "tags": ["Interior Design", "Decorative Arts", "Commercial Design", "Silpakorn"],
        "website_url": "https://dec.su.ac.th"
    },
    {
        "id": "su_pharm_bpharm_industrial",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาการวิจัยและพัฒนาผลิตภัณฑ์ยา (เภสัชกรรมอุตสาหการ)",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Research and Development",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (การวิจัยและพัฒนาผลิตภัณฑ์ยา)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Pharmaceutical Technology",
        "department_th": "ภาควิชาเทคโนโลยีเภสัชกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "224 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "264,000 บาท",
        "description": "คณะเภสัชศาสตร์ ม.ศิลปากร วิทยาเขตพระราชวังสนามจันทร์ เชี่ยวชาญเทคโนโลยีเภสัชกรรม การคิดค้นตำรับยา ยานาโน และเวชสำอาง",
        "curriculum_highlights": ["โรงงานต้นแบบผลิตยาและผลิตภัณฑ์สุขภาพที่ได้มาตรฐาน GMP", "การวิจัยระบบนำส่งยาระดับนาโน (Nanomedicine) และการสกัดสมุนไพร", "การฝึกงานกับบริษัทยาข้ามชาติและองค์การเภสัชกรรม (GPO)"],
        "career_paths": ["เภสัชกรวิจัยและพัฒนาสูตรตำรับยา (Pharmaceutical R&D)", "เภสัชกรควบคุมการผลิตและประกันคุณภาพโรงงานยา (QA/QC)", "เภสัชกรผู้เชี่ยวชาญการขึ้นทะเบียนตำรับยา"],
        "tags": ["Pharmacy", "Industrial Pharmacy", "Drug Formulation", "Nanomedicine", "Silpakorn"],
        "website_url": "https://pharmacy.su.ac.th"
    },

    # =========================================================================
    # BURAPHA UNIVERSITY (BUU - บางแสน & จันทบุรี)
    # =========================================================================
    {
        "id": "buu_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "Burapha University",
        "university_th": "มหาวิทยาลัยบูรพา",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Medicine",
        "department_th": "สาขาวิชาแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "250 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "ศูนย์กลางแพทยศาสตร์เขตเศรษฐกิจพิเศษภาคตะวันออก (EEC) พร้อมโรงพยาบาลมหาวิทยาลัยบูรพาและศูนย์เชี่ยวชาญโรคหัวใจและมะเร็ง",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิกในโรงพยาบาลมหาวิทยาลัยบูรพา และโรงพยาบาลศูนย์ชลบุรี/ระยอง", "เวชศาสตร์ใต้น้ำและเวชศาสตร์ทางทะเล (Hyperbaric & Marine Medicine)", "การแพทย์ปฐมภูมิและการดูแลสุขภาพแรงงานในเขตอุตสาหกรรม EEC"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไปและแพทย์เฉพาะทาง", "แพทย์ประจำโรงพยาบาลศูนย์ภาคตะวันออก", "แพทย์ผู้เชี่ยวชาญเวชศาสตร์อาชีวเวชศาสตร์และเวชศาสตร์ทางทะเล"],
        "tags": ["Medicine", "Doctor", "Marine Medicine", "EEC", "Burapha Medicine"],
        "website_url": "https://med.buu.ac.th"
    },
    {
        "id": "buu_chan_marine_tech",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีทางทะเล (การเพาะเลี้ยงสัตว์น้ำและเทคโนโลยีชีวภาพ)",
        "title_en": "Bachelor of Science Program in Marine Technology (Aquaculture and Marine Biotechnology)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคโนโลยีทางทะเล)",
        "university": "Burapha University",
        "university_th": "มหาวิทยาลัยบูรพา",
        "faculty": "Faculty of Marine Technology (Chanthaburi)",
        "faculty_th": "คณะเทคโนโลยีทางทะเล (วิทยาเขตจันทบุรี)",
        "department": "Department of Marine Technology",
        "department_th": "สาขาวิชาเทคโนโลยีทางทะเล",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "ศึกษาการเพาะเลี้ยงสัตว์น้ำเศรษฐกิจชายฝั่ง เทคโนโลยีการฟักไข่และเพาะพันธุ์กุ้ง ปลา สารสกัดจากสาหร่ายทะเล และการจัดการสิ่งแวดล้อมชายฝั่ง",
        "curriculum_highlights": ["สถานีวิจัยสัตว์น้ำชายฝั่งและฟาร์มเพาะเลี้ยงระบบน้ำหมุนเวียน (RAS)", "การสกัดสารออกฤทธิ์ทางชีวภาพจากสิ่งมีชีวิตใต้ทะเลเพื่ออุตสาหกรรมยาและเครื่องสำอาง", "ความร่วมมือกับอุตสาหกรรมแปรรูปอาหารทะเลชั้นนำภาคตะวันออก"],
        "career_paths": ["นักวิชาการประมงและเทคโนโลยีทางทะเล", "ผู้จัดการฟาร์มเพาะเลี้ยงสัตว์น้ำเศรษฐกิจ", "นักวิจัยเทคโนโลยีชีวภาพทางทะเล"],
        "tags": ["Marine Technology", "Aquaculture", "Marine Biotechnology", "Chanthaburi", "Burapha"],
        "website_url": "https://marine.chanthaburi.buu.ac.th"
    },
]
