# SWU & SU Official Curricula Dataset

SWU_SU_COURSES = [
    # =========================================================================
    # SWU (Srinakharinwirot University - มหาวิทยาลัยศรีนครินทรวิโรฒ มศว)
    # =========================================================================
    # --- คณะแพทยศาสตร์ (Faculty of Medicine - SWU) ---
    {
        "id": "swu_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Medicine",
        "department_th": "ภาควิชาแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "252 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "ผลิตแพทย์ที่มีคุณธรรม จริยธรรม และสมรรถนะการดูแลสุขภาพแบบองค์รวม มีทักษะคลินิกที่เชี่ยวชาญ และความร่วมมือกับมหาวิทยาลัยนอตทิงแฮม (Nottingham)",
        "curriculum_highlights": ["การเรียนรู้ทางคลินิก ณ ศูนย์การแพทย์สมเด็จพระเทพฯ (มศว องครักษ์) และศูนย์การแพทย์ปัญญานันทภิกขุ", "โครงการร่วมผลิตแพทย์กับ University of Nottingham (UK)", "การส่งเสริมการวิจัยทางการแพทย์ตั้งแต่ชั้นปรีคลินิก"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไป", "แพทย์เฉพาะทางทุกสาขา", "อาจารย์แพทย์และนักวิจัยทางการแพทย์"],
        "tags": ["Medicine", "Doctor", "Health Science", "SWU Medicine"],
        "website_url": "https://med.swu.ac.th"
    },
    # --- คณะทันตแพทยศาสตร์ (Faculty of Dentistry - SWU) ---
    {
        "id": "swu_dent_dds",
        "title_th": "หลักสูตรทันตแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Dental Surgery Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ท.บ. (ทันตแพทยศาสตรบัณฑิต)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Dentistry",
        "department_th": "สาขาวิชาทันตแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "230 หน่วยกิต",
        "tuition_per_semester": "32,000 บาท",
        "tuition_total": "384,000 บาท",
        "description": "มุ่งเน้นการสร้างทันตแพทย์ที่มีทักษะคลินิกทันตกรรมระดับสูง มีจรรยาบรรณวิชาชีพ และเชี่ยวชาญการดูแลสุขภาพช่องปากแบบสหสาขาวิชา",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิกทันตกรรม ณ โรงพยาบาลทันตกรรม มศว ประสานมิตร", "การใช้เทคโนโลยีทันตกรรมดิจิทัลและการบูรณะฟันขั้นสูง", "การบริการทันตกรรมชุมชนและการวิจัยทันตแพทยศาสตร์"],
        "career_paths": ["ทันตแพทย์ในโรงพยาบาลรัฐและเอกชน", "ทันตแพทย์เฉพาะทาง", "เจ้าของคลินิกทันตกรรม", "อาจารย์ทันตแพทย์"],
        "tags": ["Dentistry", "Dental", "Doctor of Dental Surgery", "SWU Dentistry"],
        "website_url": "https://dent.swu.ac.th"
    },
    # --- คณะเภสัชศาสตร์ (Faculty of Pharmacy - SWU) ---
    {
        "id": "swu_pharm_bpharm_care",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาการบริบาลทางเภสัชกรรม",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Care",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (การบริบาลทางเภสัชกรรม)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Clinical Pharmacy",
        "department_th": "สาขาวิชาเภสัชกรรมคลินิก",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "224 หน่วยกิต",
        "tuition_per_semester": "25,000 บาท",
        "tuition_total": "300,000 บาท",
        "description": "เน้นการบริบาลทางเภสัชกรรมแก่ผู้ป่วย การติดตามอาการไม่พึงประสงค์จากการใช้ยา และการประเมินการใช้ยาอย่างสมเหตุผลในโรงพยาบาล",
        "curriculum_highlights": ["การฝึกปฏิบัติงานคลินิกในศูนย์การแพทย์ มศว และโรงพยาบาลชั้นนำ", "การบริหารจัดการการใช้ยาในกลุ่มโรคไม่ติดต่อเรื้อรัง (NCDs)", "ทักษะการสื่อสารและให้คำปรึกษาด้านสุขภาพ"],
        "career_paths": ["เภสัชกรประจำโรงพยาบาล", "เภสัชกรคลินิก", "เภสัชกรชุมชน (ร้านยา)", "เภสัชกรผู้เชี่ยวชาญด้านยา"],
        "tags": ["Pharmacy", "Pharmaceutical Care", "Health Science", "SWU Pharmacy"],
        "website_url": "https://pharm.swu.ac.th"
    },
    # --- คณะกายภาพบำบัด (Faculty of Physical Therapy - SWU) ---
    {
        "id": "swu_pt_bsc_physical_therapy",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชากายภาพบำบัด",
        "title_en": "Bachelor of Science Program in Physical Therapy",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (กายภาพบำบัด)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Physical Therapy",
        "faculty_th": "คณะกายภาพบำบัด",
        "department": "Department of Physical Therapy",
        "department_th": "ภาควิชากายภาพบำบัด",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "138 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "176,000 บาท",
        "description": "ผลิตนักกายภาพบำบัดผู้เชี่ยวชาญการฟื้นฟูสมรรถภาพทางกาย การรักษาอาการปวดทางระบบกระดูกและกล้ามเนื้อ กายภาพบำบัดทางการกีฬา และระบบประสาท",
        "curriculum_highlights": ["คลินิกกายภาพบำบัด มศว ที่ให้บริการแก่ประชาชนและนักกีฬาชั้นนำ", "การฟื้นฟูสมรรถภาพทางระบบกระดูก กล้ามเนื้อ และระบบประสาทขั้นสูง", "การใช้เทคโนโลยีและเครื่องมือกายภาพบำบัดสมัยใหม่ (Hydrotherapy, Shockwave)"],
        "career_paths": ["นักกายภาพบำบัดประจำโรงพยาบาลและคลินิก", "นักกายภาพบำบัดประจำทีมกีฬาและศูนย์ฟิตเนส", "เจ้าของคลินิกกายภาพบำบัด"],
        "tags": ["Physical Therapy", "Rehabilitation", "Sports Medicine", "Physiotherapy"],
        "website_url": "https://pt.swu.ac.th"
    },
    # --- คณะศึกษาศาสตร์ (Faculty of Education - SWU) ---
    {
        "id": "swu_edu_bed_edtech",
        "title_th": "หลักสูตรการศึกษาบัณฑิต สาขาวิชาเทคโนโลยีการศึกษา",
        "title_en": "Bachelor of Education Program in Educational Technology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "กศ.บ. (เทคโนโลยีการศึกษา)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "Faculty of Education",
        "faculty_th": "คณะศึกษาศาสตร์",
        "department": "Department of Educational Technology",
        "department_th": "ภาควิชาเทคโนโลยีการศึกษา",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "สถาบันผลิตครูและนักเทคโนโลยีการศึกษาอันดับ 1 ของประเทศ เน้นการออกแบบสื่อนวัตกรรมการเรียนรู้ดิจิทัล E-Learning, AR/VR และ EdTech AI",
        "curriculum_highlights": ["การออกแบบและพัฒนานวัตกรรมการเรียนรู้ดิจิทัล (Instructional Design)", "การประยุกต์ใช้ Metaverse, AR/VR และ AI ในการศึกษา", "การฝึกปฏิบัติการสอนในโรงเรียนสาธิต มศว และสถาบันชั้นนำ"],
        "career_paths": ["ครูผู้สอนวิชาคอมพิวเตอร์และเทคโนโลยี", "นักออกแบบสื่อนวัตกรรมการศึกษา (Instructional Designer)", "ผู้เชี่ยวชาญด้าน EdTech และ E-Learning Developer"],
        "tags": ["Education", "Educational Technology", "EdTech", "Teacher", "SWU"],
        "website_url": "https://edu.swu.ac.th"
    },
    # --- วิทยาลัยนวัตกรรมสื่อสารสังคม (COSCI - SWU) ---
    {
        "id": "swu_cosci_ba_cinema",
        "title_th": "หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาภาพยนตร์และสื่อดิจิทัล",
        "title_en": "Bachelor of Arts Program in Cinema and Digital Media",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ. (ภาพยนตร์และสื่อดิจิทัล)",
        "university": "Srinakharinwirot University",
        "university_th": "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        "faculty": "College of Social Communication Innovation (COSCI)",
        "faculty_th": "วิทยาลัยนวัตกรรมสื่อสารสังคม",
        "department": "Department of Cinema and Digital Media",
        "department_th": "สาขาวิชาภาพยนตร์และสื่อดิจิทัล",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "360,000 บาท",
        "description": "หลักสูตรสื่อสร้างสรรค์ชั้นนำ ผลิตผู้กำกับภาพยนตร์ นักเขียนบท โปรดิวเซอร์ และครีเอเตอร์สื่อดิจิทัลคุณภาพระดับสากล",
        "curriculum_highlights": ["อุปกรณ์สตูดิโอดิจิทัล กล้องภาพยนตร์ และห้องตัดต่อเสียงมาตรฐานอุตสาหกรรม", "การเรียนรู้กระบวนการผลิตภาพยนตร์ครบวงจรตั้งแต่ Pre-production ถึง Post-production", "โอกาสส่งผลงานเข้าประกวดเทศกาลภาพยนตร์ระดับนานาชาติ"],
        "career_paths": ["ผู้กำกับภาพยนตร์และซีรีส์", "ผู้กำกับภาพ (Cinematographer)", "นักเขียนบทภาพยนตร์และคอนเทนต์ครีเอเตอร์", "โปรดิวเซอร์สื่อบันเทิง"],
        "tags": ["Cinema", "Film Production", "Digital Media", "COSCI", "Creative Arts"],
        "website_url": "https://cosci.swu.ac.th"
    },

    # =========================================================================
    # SU (Silpakorn University - มหาวิทยาลัยศิลปากร)
    # =========================================================================
    # --- คณะมัณฑนศิลป์ (Faculty of Decorative Arts - SU) ---
    {
        "id": "su_dec_bfa_interior_design",
        "title_th": "หลักสูตรศิลปบัณฑิต สาขาวิชาการออกแบบภายใน",
        "title_en": "Bachelor of Fine Arts Program in Interior Design",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศ.บ. (การออกแบบภายใน)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Decorative Arts",
        "faculty_th": "คณะมัณฑนศิลป์",
        "department": "Department of Interior Design",
        "department_th": "ภาควิชาการออกแบบภายใน",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "176,000 บาท",
        "description": "สถาบันการออกแบบภายในระดับตำนานของไทย สร้างมัณฑนากรที่มีความคิดสร้างสรรค์ ทักษะการจัดสรรพื้นที่ และความเข้าใจสุนทรียศาสตร์ชั้นสูง",
        "curriculum_highlights": ["สตูดิโอการออกแบบภายในที่เข้มข้น (Residential, Commercial, Hospitality)", "การประยุกต์ใช้วัสดุ แสง และเทคโนโลยีดิจิทัลในการออกแบบ", "ศิษย์เก่าครองความเป็นผู้นำในวงการออกแบบภายในของประเทศ"],
        "career_paths": ["มัณฑนากร / นักออกแบบตกแต่งภายใน (Interior Designer)", "ที่ปรึกษาด้านการออกแบบพื้นที่และเฟอร์นิเจอร์", "ผู้บริหารงานออกแบบและพัฒนาโครงการ"],
        "tags": ["Interior Design", "Decorative Arts", "Architecture", "Design", "Silpakorn"],
        "website_url": "https://dec.su.ac.th"
    },
    {
        "id": "su_dec_bfa_visual_comm",
        "title_th": "หลักสูตรศิลปบัณฑิต สาขาวิชาการออกแบบนิเทศศิลป์",
        "title_en": "Bachelor of Fine Arts Program in Visual Communication Design",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศ.บ. (การออกแบบนิเทศศิลป์)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Decorative Arts",
        "faculty_th": "คณะมัณฑนศิลป์",
        "department": "Department of Visual Communication Design",
        "department_th": "ภาควิชาการออกแบบนิเทศศิลป์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "22,000 บาท",
        "tuition_total": "176,000 บาท",
        "description": "สร้างนักออกแบบกราฟิก อัตลักษณ์แบรนด์ ภาพประกอบ แอนิเมชัน และ UI/UX ที่มีเอกลักษณ์และความคิดสร้างสรรค์ระดับสากล",
        "curriculum_highlights": ["การออกแบบอัตลักษณ์แบรนด์ (Brand Identity) และ Typography ขั้นสูง", "การออกแบบประสบการณ์ผู้ใช้ (UI/UX Design) และ Motion Graphic", "การประกวดผลงานออกแบบระดับประเทศและนานาชาติ"],
        "career_paths": ["Art Director / Creative Director", "Graphic & Brand Identity Designer", "UI/UX Designer", "Motion Graphic Designer"],
        "tags": ["Visual Communication", "Graphic Design", "UI/UX", "Brand Design", "Creative"],
        "website_url": "https://dec.su.ac.th"
    },
    # --- คณะโบราณคดี (Faculty of Archaeology - SU) ---
    {
        "id": "su_archaeo_ba_archaeology",
        "title_th": "หลักสูตรศิลปศาสตรบัณฑิต สาขาวิชาโบราณคดี",
        "title_en": "Bachelor of Arts Program in Archaeology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.บ. (โบราณคดี)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Archaeology",
        "faculty_th": "คณะโบราณคดี",
        "department": "Department of Archaeology",
        "department_th": "ภาควิชาโบราณคดี",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "16,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "คณะโบราณคดีแห่งเดียวในประเทศไทย ศึกษาประวัติศาสตร์ก่อนประวัติศาสตร์ โบราณคดีใต้น้ำ มานุษยวิทยา และการอนุรักษ์มรดกทางวัฒนธรรมระดับโลก",
        "curriculum_highlights": ["การขุดค้นทางโบราณคดีภาคสนามในแหล่งมรดกโลกและอุทยานประวัติศาสตร์", "การประยุกต์ใช้วิทยาศาสตร์และเทคโนโลยี 3D สแกนในงานโบราณคดี", "การศึกษาวิจัยมรดกวัฒนธรรมเอเชียตะวันออกเฉียงใต้"],
        "career_paths": ["นักโบราณคดีประจำกรมศิลปากร", "ภัณฑารักษ์ประจำพิพิธภัณฑ์", "นักวิชาการประวัติศาสตร์และมรดกวัฒนธรรม", "ที่ปรึกษาการจัดการแหล่งท่องเที่ยวเชิงประวัติศาสตร์"],
        "tags": ["Archaeology", "History", "Cultural Heritage", "Museum", "Silpakorn"],
        "website_url": "https://archae.su.ac.th"
    },
    # --- คณะเภสัชศาสตร์ (Faculty of Pharmacy - SU Sanam Chandra) ---
    {
        "id": "su_pharm_bpharm_industrial",
        "title_th": "หลักสูตรเภสัชศาสตรบัณฑิต สาขาวิชาวิทยาศาสตร์เภสัชกรรม (เภสัชกรรมอุตสาหการ)",
        "title_en": "Doctor of Pharmacy Program in Pharmaceutical Sciences (Industrial Pharmacy)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ภ.บ. (วิทยาศาสตร์เภสัชกรรม)",
        "university": "Silpakorn University",
        "university_th": "มหาวิทยาลัยศิลปากร",
        "faculty": "Faculty of Pharmacy",
        "faculty_th": "คณะเภสัชศาสตร์",
        "department": "Department of Pharmaceutical Technology",
        "department_th": "ภาควิชาเทคโนโลยีเภสัชกรรม",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "225 หน่วยกิต",
        "tuition_per_semester": "24,000 บาท",
        "tuition_total": "288,000 บาท",
        "description": "ศูนย์กลางเภสัชกรรมอุตสาหการและการผลิตยาชั้นนำ เน้นการวิจัยพัฒนาสูตรตำรับยา ยาชีววัตถุ และการควบคุมคุณภาพตามมาตรฐาน PIC/S",
        "curriculum_highlights": ["โรงงานผลิตยาต้นแบบมาตรฐาน GMP/PIC/S ภายในคณะ", "การพัฒนาระบบนำส่งยาขั้นสูง (Advanced Drug Delivery Systems)", "การวิจัยและพัฒนาผลิตภัณฑ์สมุนไพรและเครื่องสำอาง"],
        "career_paths": ["เภสัชกรฝ่ายวิจัยและพัฒนาผลิตภัณฑ์ยา (R&D)", "เภสัชกรฝ่ายผลิตและควบคุมคุณภาพในโรงงานยา (QA/QC)", "เภสัชกรฝ่ายขึ้นทะเบียนยาและเวชภัณฑ์"],
        "tags": ["Pharmacy", "Industrial Pharmacy", "Drug Formulation", "GMP", "Silpakorn"],
        "website_url": "https://pharmacy.su.ac.th"
    },
]
