# Top Universities & Regional Leaders Expansion Dataset
# (CU, TU, KU, KKU, CMU, UP, WU, MJU)

TOP_UNIS_EXPANSION_COURSES = [
    # =========================================================================
    # CU (Chulalongkorn University - จุฬาลงกรณ์มหาวิทยาลัย)
    # =========================================================================
    {
        "id": "cu_scii_bascii",
        "title_th": "หลักสูตรศิลปศาสตรและวิทยาศาสตรบัณฑิต สาขาวิชานวัตกรรมบูรณาการ (หลักสูตรนานาชาติ - BAScii)",
        "title_en": "Bachelor of Arts and Science in Integrated Innovation (International Program - BAScii)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ศศ.วท.บ. (นวัตกรรมบูรณาการ)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Chulalongkorn School of Integrated Innovation (ScII)",
        "faculty_th": "สถาบันนวัตกรรมบูรณาการแห่งจุฬาลงกรณ์มหาวิทยาลัย",
        "department": "Department of Integrated Innovation",
        "department_th": "สาขาวิชานวัตกรรมบูรณาการ",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "128 หน่วยกิต",
        "tuition_per_semester": "105,000 บาท",
        "tuition_total": "840,000 บาท",
        "description": "หลักสูตรนวัตกรรมข้ามศาสตร์ชั้นนำระดับโลกของจุฬาฯ ผสานเทคโนโลยี AI, Business Entrepreneurship และการออกแบบ เพื่อสร้างผู้ประกอบการสตาร์ทอัพยุคใหม่",
        "curriculum_highlights": ["การเรียนรู้โดยการลงมือสร้างสตาร์ทอัพจริง (Startup Incubation Project)", "ความร่วมมือกับมหาวิทยาลัยและ Tech Accelerator ระดับโลก", "อาจารย์และผู้เชี่ยวชาญจากองค์กรเทคโนโลยีชั้นนำระดับสากล"],
        "career_paths": ["Tech Startup Founder / Co-Founder", "Innovation Consultant", "Product Manager in Big Tech", "Venture Capital Analyst"],
        "tags": ["BAScii", "Innovation", "Entrepreneurship", "Startup", "International Program", "Chula"],
        "website_url": "https://scii.chula.ac.th"
    },
    {
        "id": "cu_eng_msc_ai_iot",
        "title_th": "หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมปัญญาประดิษฐ์และอินเทอร์เน็ตของสรรพสิ่ง",
        "title_en": "Master of Engineering Program in Artificial Intelligence and Internet of Things",
        "degree_level": "ปริญญาโท",
        "degree_name": "วศ.ม. (วิศวกรรมปัญญาประดิษฐ์และไอโอที)",
        "university": "Chulalongkorn University",
        "university_th": "จุฬาลงกรณ์มหาวิทยาลัย",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Computer Engineering",
        "department_th": "ภาควิชาวิศวกรรมคอมพิวเตอร์",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "45,000 บาท",
        "tuition_total": "180,000 บาท",
        "description": "เน้นการวิจัย AI ขั้นสูง, Deep Learning, Edge AI, IoT Architecture และการประยุกต์ใช้ใน Smart City, Smart Healthcare และ Industrial Automation",
        "curriculum_highlights": ["ศูนย์วิจัย AI และคอมพิวเตอร์ชั้นนำของจุฬาฯ (Chula AI Lab)", "การประยุกต์ใช้ AI ในภาคธุรกิจและการแพทย์ระดับแนวหน้า", "การทำงานร่วมกับองค์กรระดับโลก เช่น Google, Microsoft, Huawei"],
        "career_paths": ["Principal AI Engineer", "AI/IoT Solutions Architect", "อาจารย์และนักวิจัยวิศวกรรมคอมพิวเตอร์"],
        "tags": ["Artificial Intelligence", "AI", "IoT", "Computer Engineering", "Chula"],
        "website_url": "https://cp.eng.chula.ac.th"
    },

    # =========================================================================
    # TU (Thammasat University - มหาวิทยาลัยธรรมศาสตร์)
    # =========================================================================
    {
        "id": "tu_siit_beng_ai_data",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์และปัญญาประดิษฐ์ (SIIT นานาชาติ)",
        "title_en": "Bachelor of Engineering Program in Computer Engineering and AI (SIIT International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมคอมพิวเตอร์และปัญญาประดิษฐ์)",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "Sirindhorn International Institute of Technology (SIIT)",
        "faculty_th": "สถาบันเทคโนโลยีนานาชาติสิรินธร (SIIT)",
        "department": "School of Information, Computer, and Communication Technology",
        "department_th": "สาขาวิชาเทคโนโลยีสารสนเทศ คอมพิวเตอร์ และการสื่อสาร",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "85,000 บาท",
        "tuition_total": "680,000 บาท",
        "description": "สถาบันวิศวกรรมนานาชาติชั้นนำของไทย เน้นการเรียนการสอนเป็นภาษาอังกฤษ 100% ครอบคลุม AI, Cyber Security, Cloud Systems และ Data Engineering",
        "curriculum_highlights": ["คณาจารย์ปริญญาเอก 100% จากมหาวิทยาลัยชั้นนำระดับโลก", "ทุนการศึกษาและโอกาสแลกเปลี่ยนกับมหาวิทยาลัยในเยอรมนี ญี่ปุ่น และสหรัฐฯ", "ได้รับการรับรองมาตรฐานสากล ABET (USA)"],
        "career_paths": ["International Software Engineer", "AI Researcher & Engineer", "Cybersecurity Specialist", "Data Architect"],
        "tags": ["SIIT", "Computer Engineering", "AI", "International Program", "Thammasat"],
        "website_url": "https://siit.tu.ac.th"
    },
    {
        "id": "tu_cits_bsc_data_innovation",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชานวัตกรรมและการแปรรูปทางดิจิทัล (IDD/CDT นานาชาติ)",
        "title_en": "Bachelor of Science Program in Digital Innovation and Transformation (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (นวัตกรรมดิจิทัล)",
        "university": "Thammasat University",
        "university_th": "มหาวิทยาลัยธรรมศาสตร์",
        "faculty": "College of Interdisciplinary Studies",
        "faculty_th": "วิทยาลัยสหวิทยาการ",
        "department": "Department of Digital Innovation",
        "department_th": "สาขาวิชานวัตกรรมดิจิทัล",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "130 หน่วยกิต",
        "tuition_per_semester": "65,000 บาท",
        "tuition_total": "520,000 บาท",
        "description": "บูรณาการเทคโนโลยีดิจิทัล การออกแบบเกม อินเตอร์แอคทีฟมีเดีย และธุรกิจดิจิทัลเพื่อสร้างผู้เชี่ยวชาญการขับเคลื่อนนวัตกรรมดิจิทัล",
        "curriculum_highlights": ["การพัฒนาเกม แอนิเมชัน และ Virtual Reality (VR/AR)", "การออกแบบ User Experience (UX) และ Digital Transformation Strategy", "โอกาสรับปริญญาตรีสองใบ (Double Degree) ร่วมกับมหาวิทยาลัยในอังกฤษ"],
        "career_paths": ["Game Developer & Producer", "UI/UX & Product Designer", "Digital Transformation Consultant"],
        "tags": ["Digital Innovation", "Game Design", "VR/AR", "Thammasat", "International"],
        "website_url": "https://cis.tu.ac.th"
    },

    # =========================================================================
    # KU (Kasetsart University - มหาวิทยาลัยเกษตรศาสตร์)
    # =========================================================================
    {
        "id": "ku_eng_beng_aerospace",
        "title_th": "หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมการบินและอวกาศ (หลักสูตรนานาชาติ - IDDP)",
        "title_en": "Bachelor of Engineering Program in Aerospace Engineering (International Program - IDDP)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วศ.บ. (วิศวกรรมการบินและอวกาศ)",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Aerospace Engineering",
        "department_th": "ภาควิชาวิศวกรรมการบินและอวกาศ",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "4 ปี",
        "total_credits": "144 หน่วยกิต",
        "tuition_per_semester": "60,000 บาท",
        "tuition_total": "480,000 บาท",
        "description": "ภาควิชาวิศวกรรมการบินแห่งแรกของไทย ศึกษาอากาศพลศาสตร์ ระบบขับดันอากาศยาน การออกแบบดาวเทียม และเทคโนโลยีอวกาศ",
        "curriculum_highlights": ["โครงการสองปริญญา (Double Degree) ร่วมกับ RMIT University ประเทศออสเตรเลีย", "ห้องปฏิบัติการอุโมงค์ลมและสถานีควบคุมดาวเทียมขนาดเล็ก (CubeSat)", "ความร่วมมือกับ GISTDA และองค์กรการบินระดับโลก"],
        "career_paths": ["วิศวกรการบินและอวกาศ (Aerospace Engineer)", "วิศวกรซ่อมบำรุงอากาศยาน (Aircraft Maintenance Engineer)", "นักวิจัยเทคโนโลยีอวกาศและดาวเทียม"],
        "tags": ["Aerospace Engineering", "Aviation", "Satellite", "Space", "Kasetsart"],
        "website_url": "https://ase.eng.ku.ac.th"
    },
    {
        "id": "ku_agro_bsc_food_biotech",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเทคโนโลยีชีวภาพทางอาหาร",
        "title_en": "Bachelor of Science Program in Food Biotechnology",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เทคโนโลยีชีวภาพ)",
        "university": "Kasetsart University",
        "university_th": "มหาวิทยาลัยเกษตรศาสตร์",
        "faculty": "Faculty of Agro-Industry",
        "faculty_th": "คณะอุตสาหกรรมเกษตร",
        "department": "Department of Biotechnology",
        "department_th": "ภาควิชาเทคโนโลยีชีวภาพ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "136 หน่วยกิต",
        "tuition_per_semester": "18,000 บาท",
        "tuition_total": "144,000 บาท",
        "description": "มุ่งเน้นการประยุกต์ใช้จุลินทรีย์ เอนไซม์ และพันธุวิศวกรรมในการผลิตอาหารเพื่อสุขภาพ โปรตีนทางเลือก และสารชีวภาพมูลค่าสูง",
        "curriculum_highlights": ["เทคโนโลยีการหมักระดับอุตสาหกรรมและการผลิตเอนไซม์", "การพัฒนาโปรตีนทางเลือกและอาหารแห่งอนาคต (Future Food)", "ศูนย์ความเป็นเลิศด้านเทคโนโลยีชีวภาพระดับชาติ"],
        "career_paths": ["นักเทคโนโลยีชีวภาพและนักวิจัยอาหาร (Biotech Scientist)", "ผู้เชี่ยวชาญกระบวนการหมักอุตสาหกรรม (Fermentation Specialist)", "ผู้จัดการฝ่ายประกันคุณภาพชีวภาพ"],
        "tags": ["Biotechnology", "Food Biotech", "Future Food", "Fermentation", "Agro-Industry"],
        "website_url": "https://biotech.agro.ku.ac.th"
    },

    # =========================================================================
    # KKU (Khon Kaen University - มหาวิทยาลัยขอนแก่น)
    # =========================================================================
    {
        "id": "kku_dent_dds",
        "title_th": "หลักสูตรทันตแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Dental Surgery Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ท.บ. (ทันตแพทยศาสตรบัณฑิต)",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Dentistry",
        "department_th": "สาขาวิชาทันตแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "232 หน่วยกิต",
        "tuition_per_semester": "30,000 บาท",
        "tuition_total": "360,000 บาท",
        "description": "ศูนย์กลางทันตแพทยศาสตร์อันดับ 1 ของภาคตะวันออกเฉียงเหนือ มีโรงพยาบาลทันตกรรมขนาดใหญ่และการวิจัยโรคช่องปากระดับสากล",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิกทันตกรรมครบวงจรในโรงพยาบาลทันตกรรม มข.", "การประยุกต์ใช้เทคโนโลยี Digital Dentistry และ 3D Dental Printing", "การรักษาผู้ป่วยปากแหว่งเพดานโหว่ระดับศูนย์ความเป็นเลิศ (Tawanchai Center)"],
        "career_paths": ["ทันตแพทย์ทั่วไปในโรงพยาบาลรัฐและเอกชน", "ทันตแพทย์เฉพาะทางทุกสาขา", "อาจารย์ทันตแพทย์และนักวิจัย"],
        "tags": ["Dentistry", "Dental", "Doctor of Dental Surgery", "KKU Dentistry"],
        "website_url": "https://dentistry.kku.ac.th"
    },
    {
        "id": "kku_eng_msc_smart_city",
        "title_th": "หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิชาวิศวกรรมเมืองอัจฉริยะและโครงสร้างพื้นฐานดิจิทัล",
        "title_en": "Master of Engineering Program in Smart City and Digital Infrastructure Engineering",
        "degree_level": "ปริญญาโท",
        "degree_name": "วศ.ม. (วิศวกรรมเมืองอัจฉริยะ)",
        "university": "Khon Kaen University",
        "university_th": "มหาวิทยาลัยขอนแก่น",
        "faculty": "Faculty of Engineering",
        "faculty_th": "คณะวิศวกรรมศาสตร์",
        "department": "Department of Civil and Environmental Engineering",
        "department_th": "ภาควิชาวิศวกรรมโยธาและสิ่งแวดล้อม",
        "program_type": "ภาคปกติ / ภาคพิเศษ",
        "duration_years": "2 ปี",
        "total_credits": "36 หน่วยกิต",
        "tuition_per_semester": "32,000 บาท",
        "tuition_total": "128,000 บาท",
        "description": "มุ่งเน้นการวางแผนและพัฒนาเมืองอัจฉริยะ (Khon Kaen Smart City) การคมนาคมขนส่งดิจิทัล การจัดการพลังงานสะอาด และ IoT โครงสร้างพื้นฐาน",
        "curriculum_highlights": ["การประยุกต์ใช้ระบบข้อมูลเมืองและแบบจำลองสารสนเทศเมือง (CIM / GIS)", "การพัฒนาระบบขนส่งมวลชนอัจฉริยะ (Smart Mobility / LRT)", "การวิจัยเชิงปฏิบัติการในพื้นที่เมืองอัจฉริยะขอนแก่นจริง"],
        "career_paths": ["Smart City Consultant & Planner", "Digital Infrastructure Engineer", "นักวิเคราะห์และวางผังเมืองดิจิทัล"],
        "tags": ["Smart City", "Civil Engineering", "Digital Infrastructure", "IoT", "KKU"],
        "website_url": "https://en.kku.ac.th"
    },

    # =========================================================================
    # UP (University of Phayao - มหาวิทยาลัยพะเยา)
    # =========================================================================
    {
        "id": "up_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "University of Phayao",
        "university_th": "มหาวิทยาลัยพะเยา",
        "faculty": "School of Medicine",
        "faculty_th": "คณะแพทยศาสตร์",
        "department": "Department of Medicine",
        "department_th": "สาขาวิชาแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "250 หน่วยกิต",
        "tuition_per_semester": "28,000 บาท",
        "tuition_total": "336,000 บาท",
        "description": "ผลิตแพทย์เพื่อการพัฒนาสุขภาวะของชุมชนภาคเหนือตอนบน เน้นเวชศาสตร์ครอบครัว การแพทย์ปฐมภูมิ และการดูแลสุขภาพผู้สูงอายุ",
        "curriculum_highlights": ["การฝึกปฏิบัติการคลินิก ณ โรงพยาบาลมหาวิทยาลัยพะเยา และโรงพยาบาลศูนย์พะเยา-เชียงราย", "การเรียนรู้ชุมชนและการแพทย์เชิงรุกในพื้นที่ชนบท", "เทคโนโลยีการแพทย์ทางไกล (Telemedicine) เพื่อชุมชนห่างไกล"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไป", "แพทย์เฉพาะทาง", "แพทย์ชุมชนและเวชศาสตร์ครอบครัว"],
        "tags": ["Medicine", "Doctor", "Rural Health", "Health Science", "Phayao"],
        "website_url": "https://med.up.ac.th"
    },
    {
        "id": "up_dent_dds",
        "title_th": "หลักสูตรทันตแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Dental Surgery Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "ท.บ. (ทันตแพทยศาสตรบัณฑิต)",
        "university": "University of Phayao",
        "university_th": "มหาวิทยาลัยพะเยา",
        "faculty": "School of Dentistry",
        "faculty_th": "คณะทันตแพทยศาสตร์",
        "department": "Department of Dentistry",
        "department_th": "สาขาวิชาทันตแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "230 หน่วยกิต",
        "tuition_per_semester": "30,000 บาท",
        "tuition_total": "360,000 บาท",
        "description": "มุ่งเน้นการผลิตทันตแพทย์ที่มีทักษะคลินิกทันตกรรมครบถ้วน มีจิตสาธารณะ และพร้อมให้บริการทันตสุขภาพแก่ประชาชนในพื้นที่ภาคเหนือ",
        "curriculum_highlights": ["โรงพยาบาลทันตกรรมมหาวิทยาลัยพะเยาที่ทันสมัย", "การฝึกทักษะหัตถการคลินิกทันตกรรมขั้นสูง", "ทันตกรรมส่งเสริมป้องกันในโรงเรียนและชุมชน"],
        "career_paths": ["ทันตแพทย์ในโรงพยาบาลรัฐและเอกชน", "ทันตแพทย์เฉพาะทาง", "เจ้าของคลินิกทันตกรรม"],
        "tags": ["Dentistry", "Dental", "Doctor of Dental Surgery", "Phayao"],
        "website_url": "https://dentistry.up.ac.th"
    },

    # =========================================================================
    # WU (Walailak University - มหาวิทยาลัยวลัยลักษณ์)
    # =========================================================================
    {
        "id": "wu_med_md",
        "title_th": "หลักสูตรแพทยศาสตรบัณฑิต",
        "title_en": "Doctor of Medicine Program",
        "degree_level": "ปริญญาตรี",
        "degree_name": "พ.บ. (แพทยศาสตรบัณฑิต)",
        "university": "Walailak University",
        "university_th": "มหาวิทยาลัยวลัยลักษณ์",
        "faculty": "School of Medicine",
        "faculty_th": "สำนักวิชาแพทยศาสตร์",
        "department": "Department of Medicine",
        "department_th": "สาขาวิชาแพทยศาสตร์",
        "program_type": "ภาคปกติ",
        "duration_years": "6 ปี",
        "total_credits": "252 หน่วยกิต",
        "tuition_per_semester": "30,000 บาท (ระบบไตรภาค)",
        "tuition_total": "540,000 บาท",
        "description": "ผลิตแพทย์ที่มีความรู้ความเชี่ยวชาญตามมาตรฐานสากล UK-PSF เน้นการฝึกปฏิบัติในโรงพยาบาลศูนย์การแพทย์มหาวิทยาลัยวลัยลักษณ์ (ขนาด 750 เตียง)",
        "curriculum_highlights": ["การเรียนการสอนมาตรฐานสากล UK Professional Standards Framework (UK-PSF)", "โรงพยาบาลศูนย์การแพทย์มหาวิทยาลัยวลัยลักษณ์ โรงพยาบาลระดับตติยภูมิชั้นนำภาคใต้ตอนบน", "การวิจัยทางการแพทย์และเทคโนโลยีสุขภาพ"],
        "career_paths": ["แพทย์เวชปฏิบัติทั่วไป", "แพทย์เฉพาะทาง", "อาจารย์แพทย์และนักวิจัย"],
        "tags": ["Medicine", "Doctor", "UK-PSF", "Health Science", "Walailak"],
        "website_url": "https://med.wu.ac.th"
    },
    {
        "id": "wu_vet_dvm",
        "title_th": "หลักสูตรสัตวแพทยศาสตรบัณฑิต (หลักสูตรนานาชาติ)",
        "title_en": "Doctor of Veterinary Medicine Program (International Program)",
        "degree_level": "ปริญญาตรี",
        "degree_name": "สพ.บ. (สัตวแพทยศาสตร์)",
        "university": "Walailak University",
        "university_th": "มหาวิทยาลัยวลัยลักษณ์",
        "faculty": "School of Veterinary Medicine (Akkhraratchakumari Veterinary College)",
        "faculty_th": "วิทยาลัยสัตวแพทยศาสตร์อัครราชกุมารี",
        "department": "Department of Veterinary Medicine",
        "department_th": "สาขาวิชาสัตวแพทยศาสตร์",
        "program_type": "หลักสูตรนานาชาติ",
        "duration_years": "6 ปี",
        "total_credits": "235 หน่วยกิต",
        "tuition_per_semester": "50,000 บาท (ระบบไตรภาค)",
        "tuition_total": "900,000 บาท",
        "description": "วิทยาลัยสัตวแพทยศาสตร์นานาชาติชั้นนำ เน้นมาตรฐานสากล การรักษาสัตว์เลี้ยง สัตว์ปศุสัตว์ สัตว์ป่า และสัตว์น้ำ ด้วยโรงพยาบาลสัตว์ขนาดใหญ่ครบวงจร",
        "curriculum_highlights": ["การเรียนการสอนเป็นภาษาอังกฤษ 100% ตามมาตรฐานสากล (AVMA Accredited Standards)", "โรงพยาบาลสัตว์เพื่อการเรียนการสอน (สัตว์เล็ก สัตว์ใหญ่ สัตว์ป่า) ขนาดใหญ่ที่สุดในภาคใต้", "ความเชี่ยวชาญด้านโรคติดต่อระหว่างสัตว์และคน (One Health)"],
        "career_paths": ["สัตวแพทย์คลินิกสัตว์เลี้ยงและสัตว์ป่า", "สัตวแพทย์ควบคุมฟาร์มปศุสัตว์และสัตว์น้ำ", "นักวิจัยด้านสุขภาพหนึ่งเดียว (One Health Researcher)"],
        "tags": ["Veterinary Medicine", "DVM", "Animal Health", "One Health", "Walailak"],
        "website_url": "https://vet.wu.ac.th"
    },

    # =========================================================================
    # MJU (Maejo University - มหาวิทยาลัยแม่โจ้)
    # =========================================================================
    {
        "id": "mju_agr_bsc_organic_agriculture",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาเกษตรอินทรีย์และความปลอดภัยทางอาหาร",
        "title_en": "Bachelor of Science Program in Organic Agriculture and Food Safety",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (เกษตรอินทรีย์)",
        "university": "Maejo University",
        "university_th": "มหาวิทยาลัยแม่โจ้",
        "faculty": "Faculty of Agricultural Production",
        "faculty_th": "คณะผลิตกรรมการเกษตร",
        "department": "Department of Organic Agriculture",
        "department_th": "สาขาวิชาเกษตรอินทรีย์",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "132 หน่วยกิต",
        "tuition_per_semester": "15,000 บาท",
        "tuition_total": "120,000 บาท",
        "description": "สถาบันการเกษตรระดับตำนานของไทย (แม่โจ้) เน้นระบบการผลิตเกษตรอินทรีย์มาตรฐานสากล (IFOAM), Smart Organic Farming และการจัดการดินและน้ำยั่งยืน",
        "curriculum_highlights": ["แปลงทดลองเกษตรอินทรีย์และศูนย์วิจัยแม่โจ้ขนาดใหญ่", "มาตรฐานการรับรองเกษตรอินทรีย์สากล (IFOAM / USDA Organic)", "การเป็นผู้ประกอบการเกษตรอินทรีย์และการตลาดสินค้าสุขภาพ"],
        "career_paths": ["ผู้จัดการฟาร์มเกษตรอินทรีย์อัจฉริยะ", "ผู้ตรวจประเมินมาตรฐานเกษตรอินทรีย์ (Organic Auditor)", "ผู้ประกอบการธุรกิจเกษตรและอาหารปลอดภัย"],
        "tags": ["Organic Agriculture", "Smart Farming", "Maejo", "Agriculture", "Sustainability"],
        "website_url": "https://agripun.mju.ac.th"
    },
    {
        "id": "mju_fish_bsc_aquaculture_smart",
        "title_th": "หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาการเพาะเลี้ยงสัตว์น้ำอัจฉริยะและการจัดการประมง",
        "title_en": "Bachelor of Science Program in Smart Aquaculture and Fisheries Management",
        "degree_level": "ปริญญาตรี",
        "degree_name": "วท.บ. (การเพาะเลี้ยงสัตว์น้ำ)",
        "university": "Maejo University",
        "university_th": "มหาวิทยาลัยแม่โจ้",
        "faculty": "Faculty of Fisheries Technology and Aquatic Resources",
        "faculty_th": "คณะเทคโนโลยีการประมงและทรัพยากรทางน้ำ",
        "department": "Department of Aquaculture",
        "department_th": "สาขาวิชาการเพาะเลี้ยงสัตว์น้ำ",
        "program_type": "ภาคปกติ",
        "duration_years": "4 ปี",
        "total_credits": "134 หน่วยกิต",
        "tuition_per_semester": "15,000 บาท",
        "tuition_total": "120,000 บาท",
        "description": "เน้นเทคโนโลยีการเพาะพันธุ์สัตว์น้ำจืดและน้ำกร่อย ระบบหมุนเวียนน้ำประหยัดพลังงาน (Biofloc / RAS) และการจัดการสุขภาพสัตว์น้ำด้วยสารชีวภาพ",
        "curriculum_highlights": ["การประยุกต์ใช้เซนเซอร์ IoT และ AI ในการควบคุมคุณภาพน้ำและอาหารสัตว์น้ำ", "การเพาะเลี้ยงพันธุ์ปลาและสัตว์น้ำเศรษฐกิจมูลค่าสูง", "ศูนย์วิจัยสัตว์น้ำและฟาร์มต้นแบบแม่โจ้"],
        "career_paths": ["นักวิชาการเพาะเลี้ยงสัตว์น้ำ", "ผู้จัดการฟาร์มสัตว์น้ำอัจฉริยะ", "ผู้เชี่ยวชาญด้านอาหารและเวชภัณฑ์สัตว์น้ำ"],
        "tags": ["Aquaculture", "Fisheries", "Smart Farming", "Maejo", "Aquatic Science"],
        "website_url": "https://fishtech.mju.ac.th"
    },
]
