"""Wave 3 cleaner: all sparse exports -> data_sources datasets (with @ fix)."""
import io
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

BACKEND = r"C:\Users\chaya\Documents\Program\Project\Teacher\backend"
STATE = os.path.join(BACKEND, "data", "agent_states")
DS = os.path.join(BACKEND, "scripts", "data_sources")

THAI_RE = re.compile(r"[\u0E00-\u0E7F]")
LATIN_RE = re.compile(r"[A-Za-z]")
CONTAM_RE = re.compile(r"[^\u0E00-\u0E7FA-Za-z0-9 .,\-\(\)/'&:@]")

JOBS = [
    ("wave3_ku_sportsci.py", "sparse_ku_sportsci_skill_state_extracted.py", "KU_SPORTSCI_FACULTIES"),
    ("wave3_cu_ias.py", "sparse_cu_ias_skill_state_extracted.py", "CU_IAS_FACULTIES"),
    ("spa_kku_arch_export.py", "sparse_kku_arch_skill_state_extracted.py", "KKU_ARCH_FACULTIES"),
    ("spa_cmu_agro_export.py", "sparse_cmu_agro_skill_state_extracted.py", "CMU_AGRO_FACULTIES"),
    ("spa_cmu_finearts_export.py", "sparse_cmu_finearts_skill_state_extracted.py", "CMU_FINEARTS_FACULTIES"),
    ("spa_ku_vettech_export.py", "sparse_ku_vettech_skill_state_extracted.py", "KU_VETTECH_FACULTIES"),
    ("spa_mu_inmu_export.py", "sparse_mu_inmu_skill_state_extracted.py", "MU_INMU_FACULTIES"),
]


def cv(s):
    return CONTAM_RE.sub("", s or "").strip()


def clean_name(f):
    name = cv(f.get("full_name_th", ""))
    thai = len(THAI_RE.findall(name))
    latin = len(LATIN_RE.findall(name))
    if thai and thai >= latin:
        return name
    en = cv(f"{f.get('first_name', '')} {f.get('last_name', '')}".strip())
    if en:
        title = cv(f.get("academic_title_th", ""))
        return f"{title} {en}".strip() if title else en
    return name


total = 0
for src, dst, var in JOBS:
    p = os.path.join(STATE, src)
    if not os.path.exists(p):
        print(f"skip {src}")
        continue
    ns = {}
    exec(io.open(p, encoding="utf-8").read(), ns)
    fs = ns["EXTRACTED_FACULTIES"]
    seen = set()
    cleaned = []
    for f in fs:
        f["full_name_th"] = clean_name(f)
        if not f["full_name_th"]:
            continue
        for k in ["first_name", "last_name", "email", "department_th", "academic_title_th"]:
            f[k] = cv(f.get(k, ""))
        for k in ["research_interests", "featured_publications", "education"]:
            f[k] = [cv(x) for x in f.get(k, []) if cv(x)]
        key = (f.get("email") or f["full_name_th"]).lower()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(f)
    header = f"# Auto-generated by SKILL.state agent (sparse-faculty wave 3), deterministic cleaning pass\n{var} = "
    io.open(os.path.join(DS, dst), "w", encoding="utf-8").write(header + json.dumps(cleaned, ensure_ascii=False, indent=4) + "\n")
    print(f"{src}: {len(fs)} -> {len(cleaned)} -> {dst}")
    total += len(cleaned)
print("TOTAL:", total)
