"""
Deterministic post-extraction cleaner for SKILL.state exports.
- Strips non-Thai/non-Latin contamination (Cyrillic/Arabic mojibake from transliteration).
- Falls back to English name when the Thai transliteration is unusable.
- Normalizes academic titles.
Writes cleaned Python datasets into scripts/data_sources/.
"""
import io
import os
import re
import sys
import json

sys.stdout.reconfigure(encoding="utf-8")

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
STATE_DIR = os.path.join(BACKEND_DIR, "data", "agent_states")
DATASOURCES_DIR = os.path.join(BACKEND_DIR, "scripts", "data_sources")

THAI_RE = re.compile(r"[\u0E00-\u0E7F]")
LATIN_RE = re.compile(r"[A-Za-z]")
CONTAMINATION_RE = re.compile(r"[^\u0E00-\u0E7FA-Za-z0-9 .,\-\(\)/'&:]")

JOBS = [
    ("spa_cu_commarts_export.py", "sparse_cu_commarts_skill_state_extracted.py", "CHULA_COMMARTS"),
    ("spa_cu_arts_export.py", "sparse_cu_arts_skill_state_extracted.py", "CHULA_ARTS"),
    ("wave1_mu_pt.py", "sparse_mu_pt_skill_state_extracted.py", "MU_PT"),
    ("wave1_mu_music.py", "sparse_mu_music_skill_state_extracted.py", "MU_MUSIC"),
]

TITLE_MAP = [
    (re.compile(r"^(ศาสตราจารย์|ศ\.)\s*"), "ศ."),
    (re.compile(r"^(รองศาสตราจารย์|รศ\.)\s*"), "รศ."),
    (re.compile(r"^(ผู้ช่วยศาสตราจารย์|ผศ\.)\s*"), "ผศ."),
    (re.compile(r"^(อาจารย์|อ\.)\s*"), "อ."),
    (re.compile(r"^(ดร\.)\s*"), "ดร."),
]


def clean_value(s):
    if not s:
        return ""
    return CONTAMINATION_RE.sub("", s).strip()


def clean_name_th(f):
    name = clean_value(f.get("full_name_th", ""))
    if THAI_RE.search(name):
        # keep if mostly Thai
        thai_chars = len(THAI_RE.findall(name))
        latin_chars = len(LATIN_RE.findall(name))
        if thai_chars >= latin_chars:
            return name
    en = f"{f.get('first_name', '')} {f.get('last_name', '')}".strip()
    en = clean_value(en)
    if en:
        title = clean_value(f.get("academic_title_th", "")) or ""
        return f"{title} {en}".strip()
    return name


def main():
    os.makedirs(DATASOURCES_DIR, exist_ok=True)
    total = 0
    for src, dst, var in JOBS:
        p = os.path.join(STATE_DIR, src)
        if not os.path.exists(p):
            print(f"skip {src} (missing)")
            continue
        ns = {}
        exec(io.open(p, encoding="utf-8").read(), ns)
        fs = ns["EXTRACTED_FACULTIES"]
        seen = set()
        cleaned = []
        for f in fs:
            f["full_name_th"] = clean_name_th(f)
            if not f["full_name_th"] or not THAI_RE.search(f["full_name_th"]) and not LATIN_RE.search(f["full_name_th"]):
                continue
            for key in ["first_name", "last_name", "email", "department_th", "academic_title_th"]:
                f[key] = clean_value(f.get(key, ""))
            for key in ["research_interests", "featured_publications", "education"]:
                f[key] = [clean_value(x) for x in f.get(key, []) if clean_value(x)]
            key = (f.get("email") or f["full_name_th"]).lower()
            if key in seen:
                continue
            seen.add(key)
            cleaned.append(f)
        out = os.path.join(DATASOURCES_DIR, dst)
        header = f"# Auto-generated by SKILL.state agent (sparse-faculty wave 1), deterministic cleaning pass\n{var}_FACULTIES = "
        io.open(out, "w", encoding="utf-8").write(header + json.dumps(cleaned, ensure_ascii=False, indent=4) + "\n")
        print(f"{src}: {len(fs)} -> {len(cleaned)} cleaned -> {dst}")
        total += len(cleaned)
    print("TOTAL:", total)


if __name__ == "__main__":
    main()
