"""Wave 2: deterministic cleaner for cu_vet + tu_pharmacy exports (reuses wave 1 logic)."""
import io
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")
sys.path.insert(0, r"C:\Users\chaya\Documents\Program\Project\Teacher\backend")

BACKEND = r"C:\Users\chaya\Documents\Program\Project\Teacher\backend"
STATE = os.path.join(BACKEND, "data", "agent_states")
DS = os.path.join(BACKEND, "scripts", "data_sources")

THAI_RE = re.compile(r"[\u0E00-\u0E7F]")
LATIN_RE = re.compile(r"[A-Za-z]")
CONTAM_RE = re.compile(r"[^\u0E00-\u0E7FA-Za-z0-9 .,\-\(\)/'&:@]")

# Wave 1 files also suffered the @-strip bug; regenerate all with @ preserved.
JOBS = [
    ("wave2_cu_vet.py", "sparse_cu_vet_skill_state_extracted.py", "CU_VET_FACULTIES"),
    ("wave2_tu_pharmacy.py", "sparse_tu_pharmacy_skill_state_extracted.py", "TU_PHARMACY_FACULTIES"),
    ("spa_cu_commarts_export.py", "sparse_cu_commarts_skill_state_extracted.py", "CHULA_COMMARTS_FACULTIES"),
    ("spa_cu_arts_export.py", "sparse_cu_arts_skill_state_extracted.py", "CHULA_ARTS_FACULTIES"),
    ("wave1_mu_pt.py", "sparse_mu_pt_skill_state_extracted.py", "MU_PT_FACULTIES"),
    ("wave1_mu_music.py", "sparse_mu_music_skill_state_extracted.py", "MU_MUSIC_FACULTIES"),
]


def cv(s):
    return CONTAM_RE.sub("", s or "").strip()


def clean_name(f):
    name = cv(f.get("full_name_th", ""))
    thai = len(THAI_RE.findall(name))
    latin = len(LATIN_RE.findall(name))
    if thai and thai >= latin:
        return name
    en = cv(f"{f.get('first_name', '')} {f.get('last_name', '')}".strip())
    if en:
        title = cv(f.get("academic_title_th", ""))
        return f"{title} {en}".strip() if title else en
    return name


for src, dst, var in JOBS:
    p = os.path.join(STATE, src)
    if not os.path.exists(p):
        print(f"skip {src} (missing)")
        continue
    ns = {}
    exec(io.open(p, encoding="utf-8").read(), ns)
    fs = ns["EXTRACTED_FACULTIES"]
    seen = set()
    cleaned = []
    for f in fs:
        f["full_name_th"] = clean_name(f)
        if not f["full_name_th"]:
            continue
        for k in ["first_name", "last_name", "email", "department_th", "academic_title_th"]:
            f[k] = cv(f.get(k, ""))
        for k in ["research_interests", "featured_publications", "education"]:
            f[k] = [cv(x) for x in f.get(k, []) if cv(x)]
        key = (f.get("email") or f["full_name_th"]).lower()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(f)
    header = f"# Auto-generated by SKILL.state agent (sparse-faculty wave 2), deterministic cleaning pass\n{var} = "
    io.open(os.path.join(DS, dst), "w", encoding="utf-8").write(header + json.dumps(cleaned, ensure_ascii=False, indent=4) + "\n")
    print(f"{src}: {len(fs)} -> {len(cleaned)} -> {dst}")

# copy cmu_vet_api export too (already reducer-processed; only light clean)
p = os.path.join(STATE, "cmu_vet_api_export.py")
ns = {}
exec(io.open(p, encoding="utf-8").read(), ns)
fs = ns["EXTRACTED_FACULTIES"]
cleaned = []
seen = set()
for f in fs:
    for k in ["first_name", "last_name", "email", "department_th", "academic_title_th", "full_name_th"]:
        f[k] = cv(f.get(k, ""))
    if not f["full_name_th"]:
        continue
    key = (f.get("email") or f["full_name_th"]).lower()
    if key in seen:
        continue
    seen.add(key)
    cleaned.append(f)
header = "# Auto-generated from vmcmu.vet.cmu.ac.th JSON API via SKILL.state Reducer (wave 2)\nCMU_VET_FACULTIES = "
io.open(os.path.join(DS, "sparse_cmu_vet_api_extracted.py"), "w", encoding="utf-8").write(header + json.dumps(cleaned, ensure_ascii=False, indent=4) + "\n")
print(f"cmu_vet_api_export.py: {len(fs)} -> {len(cleaned)} -> sparse_cmu_vet_api_extracted.py")
