import sys
import time
from pathlib import Path

# Add backend directory to Python path
sys.path.append(str(Path(__file__).resolve().parents[2]))

from app.core.database import SessionLocal
from app.models.db_models import FacultyDB
from sqlalchemy.orm import defer
from scholarly import scholarly
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

ENGLISH_NAMES = {
    "ธราดล": ("Tharadol", "Komolmis"),
    "วัชริน": ("Watcharin", "Srirattanawichaikul"),
    "กสิณ": ("Kasin", "Prakobwaitayakit"),
    "เกษมศักดิ์": ("Kasemsak", "Uthaichana"),
    "ดลเดช": ("Doldet", "Tantraviwat"),
    "นิพนธ์": ("Nipon", "Theera-Umpon"),
    "อุกฤษฏ์": ("Ukrit", "Mankong"),
    "บุญศรี": ("Boonsri", "Kaewkham-ai"),
    "ปารเมศ": ("Paramet", "Wirasanti"),
    "พีรพล": ("Peerapol", "Jirapong"),
    "สมบูรณ์": ("Somboon", "Nuchprayoon"),
    "สิโรตม์": ("Sirote", "Khunkitti"),
    "เสริมศักดิ์": ("Sermsak", "Uatrongjit"),
    "พีรพนธ์": ("Perapon", "Anusarnsunthorn"),
    "ธนะพงษ์": ("Thanapong", "Thanasaksiri"),
    "ปณิดา": ("Panida", "Thararak"),
    "วิศรุต": ("Wisarut", "Atchariyawiriya"),
    "สรพล": ("Sorapon", "Kitsirisin"),
    "ยุทธนา": ("Yuttana", "Kumsuwan"),
    # Civil & Environmental Engineering CMU
    "นพดล": ("Nopadon", "Kronprasert"),
    "ปรีดา": ("Preda", "Pichayapan"),
    "ชินพัฒน์": ("Chinapat", "Buachart"),
    "ธวัชชัย": ("Tawatchai", "Tanchaisawat"),
    "สมจินตนา": ("Somjintana", "Kanangkaew"),
    "เสาหฤท": ("Saoharit", "Nitayavardhana"),
    "ปฏิรูป": ("Patiroop", "Pholchan"),
    "พิมพ์ลักษณ์": ("Pimluck", "Kijjanapanich"),
    "อรรณพ": ("Aunnop", "Wongrueng"),
    "พวงรัตน์": ("Puangrat", "Kaewlom"),
    "สิริชัย": ("Sirichai", "Koonaphapdeelert"),
    "ณภัทร": ("Napat", "Jakrawatana"),
    "ภาคภูมิ": ("Pharkphum", "Rakruam"),
    "สุลักษณ์": ("Sulak", "Sumitsawan"),
    "สรัลนุช": ("Sarunnoud", "Phupisut"),
    "พงศกร": ("Pongsakorn", "Wongchana"),
    "เกรียงไกร": ("Kriangkrai", "Arunotayanun"),
    "ชนะ": ("Chana", "Sinsabvaradom"),
    "เศรษฐพงศ์": ("Sethapong", "Sethabouppha"),
    "สุริยะ": ("Suriyah", "Thongmunee"),
    "อรรถวิทย์": ("Auttawit", "Upayokin"),
    "ปุ่น": ("Poon", "Thiangburanathum"),
    "กิตติคุณ": ("Kittikun", "Jitpirod"),
    "พุทธิพล": ("Puttipol", "Dumrongchai"),
    "ธนพร": ("Thanaporn", "Supriyasilp"),
    "พีรวัฒน์": ("Pheerawat", "Plangoen"),
    "ดำรงศักดิ์": ("Damrongsak", "Rinchumphu"),
    "นที": ("Natee", "Suriyanon"),
    "ปิติวัฒน์": ("Pitiwat", "Wattanachai"),
    "ธีวรา": ("Teewara", "Suwan"),
    "พุทธรักษ์": ("Bhuddarak", "Charatpangoon"),
    "ปิยะพงษ์": ("Piyapong", "Wongmatar"),
    "วรากร": ("Warakorn", "Tantrapongsatorn"),
    "พีรพงศ์": ("Peerapong", "Jitsangiam"),
    "ศักดิ์กษิต": ("Sakgasit", "Ramingwong"),
    # CMU Multidisciplinary & Health Sciences
    "อะนัฆ": ("Anak", "Iamaroon"),
    "กิตติพันธุ์": ("Kittipan", "Rerkasem"),
    "จิราภรณ์": ("Jiraporn", "Khorana"),
    "ลินดา": ("Linda", "Hansapinyo"),
    "วรรณนา": ("Wannana", "Suriyasathaporn"),
    "ชาติชาย": ("Chatchai", "Doungsa-ard"),
    "ปฏิสนธิ์": ("Patison", "Palee"),
    "กฤษณ์": ("Krit", "Khwanngern"),
    "กณิกนันท์": ("Kaniknun", "Intui"),
    "ปรีดิ์": ("Prid", "Thiengburanathum"),
    "พร้อมพงศ์": ("Prompong", "Sugunnasil"),
    "สาลินี": ("Salinee", "Thumronglaohapun"),
    "วรัญญา": ("Waranya", "Mahanan"),
    "พิษณุ": ("Pisanu", "Chiawkhun"),
    "พงศ์เดช": ("Pongdej", "Chaiyakut"),
    "ปาริชาต": ("Parichat", "Pattarapanichchai"),
    "ภวัต": ("Bhawat", "Bhaksaranuvat"),
    # CMU Batch 1: Dentistry, AMS, Masscomm, Economics
    "สุภัสสรา": ("Supassara", "Sirabanchongkran"),
    "ธีรัช": ("Teerat", "Sawangpanyangkura"),
    "ปิ่นปินัทธ์": ("Pinpinut", "Wanichsaithong"),
    "ดนุพงษ์": ("Danupong", "Chaiariyakul"),
    "จิตจิโรจน์": ("Jitjiroj", "Ittichaicharoen"),
    "ยุทธการ": ("Yuthakran", "Aschaitrakool"),
    "ภัทรณัฏฐ์": ("Phattharanat", "Banthitkhunanon"),
    "มารศรี": ("Marasri", "Chaiworawitkul"),
    "พัชราวรรณ": ("Patcharawan", "Silthampitag"),
    "อติศักดิ์": ("Atisak", "Chuengpattanawadee"),
    "ณัฐกานต์": ("Nattakan", "Chaipattanawan"),
    "กฤตานน": ("Kitanon", "Angkanawaraphan"),
    "ภัทรานันท์": ("Phattaranant", "Mahasantipiya"),
    "ชนัดดา": ("Chanutda", "Rattanakornphan"),
    "พิศักดิ์": ("Pisak", "Chinchai"),
    "อนุชาติ": ("Anuchart", "Kaunnil"),
    "ณัฐวิภา": ("Natwipa", "Wanicharoen"),
    "สุภาวดี": ("Supawadee", "Putthinoi"),
    "พรเพ็ญ": ("Pornpen", "Sirisatayawong"),
    "เพื่อนใจ": ("Phuanjai", "Rattakorn"),
    "กัลยาณี": ("Kalyanee", "Makarabhirom"),
    "ศศิธร": ("Sasithorn", "Sung-U"),
    "นภาลัย": ("Napalai", "Chaimaha"),
    "จนัญญา": ("Jananya Panyamee", "Dhippayom"),
    "จิรนันท์": ("Jiranan", "Griffiths"),
    "สุจิตรพร": ("Suchitporn", "Lersilp"),
    "สาวิตรี": ("Savitree", "Charununtakorn"),
    "สุภาพร": ("Supaporn", "Chinchai"),
    "สายฝน": ("Saifon", "Bunyachatakul"),
    "พัชญ์พิไล": ("Pachpilai", "Chaiwong"),
    "พีรยา": ("Peeraya", "Munkhetvit"),
    "ศุภลักษณ์": ("Supaluck", "Phadsri"),
    "สรินยา": ("Sarinya", "Sriphetcharawut"),
    "ปิยะวัฒน์": ("Piyawat", "Trevittaya"),
    "วีรภัทร": ("Weerabhat", "Boonma"),
    "ขวัญฟ้า": ("Kwanfa", "Sriprapandh"),
    "อุกฤษณ์": ("Ukrit", "Sanguanhai"),
    "เทพฤทธิ์": ("Teparit", "Maneekul"),
    "โชเซน": ("Shosen", "Yamahata"),
    "สุนันทา": ("Sunanta", "Yamthap"),
    "พิสิทธิ์": ("Pisit", "Sriprasert"),
    "นันทสิทธิ์": ("Nantasit", "Kittivarakul"),
    "อภิภู": ("Abhibhu", "Kitikamdhorn"),
    "อัคริมา": ("Acarima", "Nanthanasit"),
    "ศศิกานต์": ("Sasikarn", "Limpiti"),
    "วิทยา": ("Vithaya", "Panichlocharoen"),
    "พุทธชาติ": ("Puttachat", "Hongsakul"),
    "ลัดดาวัลย์": ("Laddawan", "Inthajak"),
    "ร่มธรรม": ("Romtham", "Srisukho"),
    "วิทวัส": ("Witavas", "Khattirat"),
    "พิมลพรรณ": ("Pimonpan", "Chaianun"),
    "ธีระพล": ("Teerapol", "Siritup"),
    "สุลิตา": ("Sulita", "Dhippayom"),
    "ไพรัตน์": ("Pairat", "Kosapalakij"),
    "ศิวพร": ("Siwaporn", "Sukritanon"),
    "นรินทร์": ("Narin", "Numcharoen"),
    "ศุภฤกษ์": ("Supparerk", "Pothipairatana"),
    "ณฐนันท์": ("Natanun", "Kanjanakuha"),
    "จันทรวรรณ": ("Jantarawan", "Thrakulphiw"),
    "ณหทัย": ("Nahathai", "Saenmongkhon"),
    "อนัสปรีย์": ("Anaspree", "Chaiwan"),
    "จารึก": ("Charuk", "Singhapreecha"),
    "ทศพร": ("Tossapond", "Kewprasopsak"),
    "วรวรรธ": ("Worrawat", "Saijai"),
    "อนุภาค": ("Anuphak", "Saosaovaphak"),
    "ปิยะลักษณ์": ("Piyaluk", "Buddhawongsa"),
    "จิราคม": ("Jirakom", "Sirisrisakulchai"),
    "ณพล": ("Napon", "Hongsakulvasu"),
    "พัชชา": ("Patcha", "Siwapornpitak"),
    "วรัทยา": ("Warattaya", "Chinnakum"),
    "ชัยวัฒน์": ("Chaiwat", "Nimanussornkul"),
    "พิฑูร": ("Pithoon", "Thanabordeekij"),
    "รสริน": ("Rossarin", "Osathanunkul"),
    "นภัสถ์": ("Napat", "Harnpornchai"),
    "ไพรัช": ("Pairach", "Piboonrungroj"),
    "เริงชัย": ("Roengchai", "Tansuchat"),
    "ภารวี": ("Paravee", "Maneejuk"),
    "มัทนา": ("Mattana", "Wongsirikajorn"),
    "ชนามาศ": ("Chanamart", "Intapan"),
    "เชาวนา": ("Chaowana", "Phetcharat"),
    "กันต์สินี": ("Kansinee", "Guntawongwan"),
    "วรลักษณ์": ("Woraluck", "Himakalasa"),
    "เสาวลักษณ์": ("Saowaluk", "Duangin"),
    "กัญญ์สุดา": ("Kunsuda", "Nimanussornkul"),
    "สุพรรณิกา": ("Supanika", "Leurcharusmee"),
    "เบญจพล": ("Benjapon", "Prommawin"),
    "ทัชชา": ("Tatcha", "Sudtasan"),
    "ชลระดา": ("Chonrada", "Nunti"),
    # CMU Batch 2: Faculty of Science (Chemistry, Biology, Physics)
    "กรธัช": ("Kornthach", "Ounnunkad"),
    "กฤษณะ": ("Kritsana", "Jitmanee"),
    "กัลยาวัสถ์": ("Kanlayawat", "Wangkawong"),
    "กาญจนา": ("Kanchana", "Damri"),
    "กิตติพันธ์": ("Kittipan", "Sivawannapong"),
    "กุลภา": ("Kullapa", "Chanawanno"),
    "ก้องเกียรติ": ("Kongkiat", "Trisuwan"),
    "คณารัฐ": ("Kanarat", "Nalampang"),
    "จตุพล": ("Jatupol", "Kampuansai"),
    "จารุณี": ("Jarunee", "Jungklang"),
    "จิดาภา": ("Jidapa", "Thinoi"),
    "จุฑารัตน์": ("Jutarat", "Panjakhan"),
    "ฉัตรดนัย": ("Chatdanai", "Boonrueng"),
    "ชนิดา": ("Chanida", "Puangpila"),
    "ชมนาด": ("Chomanad", "Swasdimitr"),
    "ชำนาญ": ("Chamnan", "Randorn"),
    "ชิตชล": ("Chitchol", "Phalaraksh"),
    "ฐปนีย์": ("Thapanee", "Sarakonsri"),
    "ณปภา": ("Napapa", "Promsawan"),
    "ทินกร": ("Tinnakorn", "Kanyanee"),
    "ธนวัฒน์": ("Tanawat", "Chaowasku"),
    "ธนียา": ("Thaneeya", "Chetiyanukornkul"),
    "ธัญวดี": ("Thanwadee", "Limtrakul"),
    "ธิติ": ("Thiti", "Chanphirom"),
    "ธีรบุญ": ("Theeraboon", "Pojankarun"),
    "นฎา": ("Nada", "Arayasakul"),
    "นพกาญจน์": ("Nopakarn", "Chandet"),
    "นัทธี": ("Nuttee", "Suree"),
    "นาวี": ("Nawee", "Kangwan"),
    "นิลิตา": ("Nilita", "Mookjaeng"),
    "นุชนิภา": ("Nuchnipa", "Nanthawong"),
    "บูรภัทร์": ("Burapat", "Inceesungvorn"),
    "ประพุทธ์": ("Praput", "Thavornyutikarn"),
    "ประสิทธิ์": ("Prasit", "Wangpakapattanawong"),
    "ปะราลี": ("Paralee", "Waenkaew"),
    "ปัญชิกา": ("Panchika", "Prangkio"),
    "ปิยรัตน์": ("Piyarat", "Nimmanpipak"),
    "พรรัตน์": ("Pornrat", "Wattanakasiwich"),
    "พัฒนพงศ์": ("Pattanapong", "Thangsunan"),
    "พิชญา": ("Pitchaya", "Mungkornasawakul"),
    "พิมลรัตน์": ("Pimonrat", "Tiansawat"),
    "พุฒินันท์": ("Puttinan", "Meepowpan"),
    "ภควรรณ": ("Pakawan", "Puangsombat"),
    "ภัทรพล": ("Pathrapol", "Lithanatudom"),
    "ภัทรสุดา": ("Phattrasuda", "Chayaphakdee"),
    "ภัทร์นฤน": ("Patnarin", "Worajittiphon"),
    "ภูมน": ("Phumon", "Sookwong"),
    "ภูมิศร์": ("Pumis", "Thaptimdang"),
    "มัสลิน": ("Maslin", "Osathanunkul"),
    "มุกดา": ("Mookda", "Pattarawarapan"),
    "รุ้งลาวัลย์": ("Runglawan", "Somsunan"),
    "ละอองนวล": ("Laongnuan", "Srisombat"),
    "วงศ์": ("Wong", "Phakhodee"),
    "วรอนงค์": ("Woranong", "Leewattana-phasuk"),
    "วราภรณ์": ("Waraporn", "Nuntiyakul"),
    "วศิน": ("Wasin", "Sombut"),
    "วิมล": ("Wimon", "Naksata"),
    "วีระเดช": ("Wiradej", "Thongsuwan"),
    "ว่าน": ("Wan", "Wiriya"),
    "ศิลา": ("Sila", "Kittiwachana"),
    "สตีเฟ่น": ("Stephen", "Elliott"),
    "สรพงษ์": ("Sorapong", "Chanhom"),
    "สิทธิชัย": ("Sittichai", "Wirojanupatump"),
    "สิทธิศักดิ์": ("Sitthisak", "Intasit"),
    "สิริพร": ("Siriphorn", "Jangsutthivorawat"),
    "สุทธาธร": ("Suttathorn", "Chairuangsri"),
    "สุภาพ": ("Supab", "Choopun"),
    "สุรินทร์": ("Surin", "Saipanya"),
    "สุลาวัลย์": ("Sulawan", "Kaowphong"),
    "อภินันท์": ("Aphinan", "Kanpiengjai"),
    "อภิวัฒน์": ("Apiwat", "Teerawutgulrag"),
    "อรุณฉาย": ("Aroonchai", "Saiai"),
    "อรุโณทัย": ("Arunothai", "Jampeetong"),
    "อลิส": ("Alice", "Sharp"),
    "อิสสระ": ("Issara", "Patawang"),
    "อุษรา": ("Aussara", "Panya"),
    "อุษาวดี": ("Usawadee", "Chanasut"),
    "เกียรติคุณ": ("Kiattikhun", "Manokruang"),
    "เดชา": ("Decha", "Thapanya"),
    "เดีย": ("Dia", "Shannon"),
    "เวสารัช": ("Veasarach", "Jonjaroen"),
    "แสงรวี": ("Saengrawee", "Sriwichai"),
    # CMU Batch 3: Faculty of Medicine & Agro-Industry
    "กนกกาญจน์": ("Kanokkarn", "Sunkonkit"),
    "กรกนก": ("Kornkanok", "Sukpan"),
    "กรณ์พงศ์": ("Kornpong", "Siripongpol"),
    "กลวิชย์": ("Konlawij", "Trongtrakul"),
    "กวีศักดิ์": ("Kaweesak", "Chittawatanarat"),
    "กสิสิน": ("Kasisin", "Klunklin"),
    "กัญญาณัฐ": ("Kanyanat", "Mahitthihan"),
    "กัมปนาท": ("Kampanat", "Wangsan"),
    "กำธน": ("Kamtone", "Chandacham"),
    "กีรติ": ("Kirati", "Watcharachan"),
    "กุลนันท์": ("Kulanan", "Nantasukkasem"),
    "คณิตศ์": ("Kanit", "Sananpanich"),
    "คมสันต์": ("Komson", "Wannasai"),
    "คเณศ": ("Kanes", "Chattipakorn"),
    "จงกลณี": ("Jongkolnee", "Settakorn"),
    "จรัสพงศ์": ("Jaraspong", "Vuthiwong"),
    "จักรกริช": ("Jakkrit", "Klaphajone"),
    "จักรพันธ์": ("Jakaparn", "Horsatidkul"),
    "จันทิมา": ("Juntima", "Pleumsamran"),
    "จิตร": ("Jit", "Jiraratsthit"),
    "จินต์จุฑา": ("Jinjuta", "Panumasvivat"),
    "จิรกานต์": ("Chirakan", "Charoenvicha"),
    "จิรกิตต์": ("Jirakit", "On-in"),
    "จิระพงศ์": ("Jirapong", "Vongsfak"),
    "จีน": ("Jean", "Thammaphaktrakul"),
    "จีระนันท์": ("Jeeranan", "Khunachiva"),
    "จุฬารัตน์": ("Chularat", "Duangkaew"),
    "ฉันท์ชนก": ("Chanchanok", "Aramrat"),
    "ชนะการ": ("Chanakarn", "Phornphutkul"),
    "ชนันธร": ("Chananthon", "Suwannapiroet"),
    "ชนิศา": ("Chanisa", "Thonusin"),
    "ชยาธร": ("Chayatorn", "Chansakaow"),
    "ชรินทร์": ("Charin", "Ya-in"),
    "ชลกานต์": ("Chollakarn", "Varopas"),
    "ชลลดา": ("Chonlada", "Mahakkanukrauh"),
    "ชวินทร์": ("Chawin", "Lerstsrimongkol"),
    "ชัยสิริ": ("Chaisiri", "Angkurawaranon"),
    "ชานน": ("Chanon", "Srihagulang"),
    "ชิน": ("Chin", "Thadadondhip"),
    "ชุติเทพ": ("Chutithep", "Teekaput"),
    "ฐิติรัตน์": ("Thitirat", "Sirirattakittikul"),
    "ณรงค์ศักดิ์": ("Narongsak", "Tangon"),
    "ณัชชา": ("Nutchar", "Wiwatkunupakarn"),
    "ณัฐ": ("Nut", "Koonrungsesomboon"),
    "ณัฐกฤช": ("Natthakritch", "Rungrueng"),
    "ณัฐชานนท์": ("Natchanon", "Simgam"),
    "ณัฐณภพ": ("Natnapob", "Isaradech"),
    "ณัฐนันท์": ("Nattanun", "Thiranont"),
    "ณัฐภัทร": ("Natthaphat", "Siri-angkul"),
    "ณัฐยาภรณ์": ("Nattayaporn", "Apaijai"),
    "ณัฐวรรณ์": ("Nattawan", "Arkarattanakul"),
    "ณัฐวุฒิ": ("Nattawut", "Chutiveerawattanakul"),
    "ณิชนันท์": ("Nichanan", "Osataphan"),
    "ต่อพงษ์": ("Torphong", "Bunmaprasert"),
    "ถวัลย์รัตน์": ("Thawalrat", "Ratanasiri"),
    "ทรงพล": ("Songphol", "Srisukho"),
    "ทรงเกียรติ": ("Songkiet", "Suwansirikul"),
    "ทศพล": ("Todsapon", "Praphanuwat"),
    "ธนกฤต": ("Thanakrit", "Rattanasiriwongwut"),
    "ธนฉัตร": ("Thanachat", "Yotruangsri"),
    "ธนธัส": ("Thanatas", "Rangphueng"),
    "ธนัฐ": ("Tanat", "Vaniyapong"),
    "ธนาวัฒก์": ("Thanawat", "Rattanathammethee"),
    "ธัญญา": ("Thunya", "Norasetthada"),
    "ธิดารัตน์": ("Tidarat", "Jirapongcharoenlap"),
    "ธิติพงศ์": ("Thitipong", "Tepsuwan"),
    "ธีรฉัตร": ("Teerachat", "Punnachet"),
    "ธีระ": ("Thira", "Sirisanthana"),
    "ธีร์ธัช": ("Theetouch", "Tosukhowong"),
    "ธเนศ": ("Taned", "Chitapanarux"),
    "นพคุณ": ("Nopakoon", "Nantsupawat"),
    "นพพล": ("Noppon", "Taksaudom"),
    "นพรัตน์": ("Noparat", "Thanachaikun"),
    "นภัส": ("Naphas", "Rungruangthanakit"),
    "นฤภร": ("Narueporn", "Pakowong"),
    "นลินี": ("Nalinee", "Yingchankul"),
    "นันทนา": ("Nuntana", "Kasitanon"),
    "นันทพร": ("Nantaporn", "Tiyapun"),
    "นันทวิช": ("Nantawit", "Sugandhavesa"),
    "นิชนันท์": ("Nitchanant", "Kitcharanant"),
    "นิดา": ("Nida", "Buawangpong"),
    "นิพิฐพนธ์": ("Niphitphon", "Phenphinan"),
    "นิรัชร์": ("Nirush", "Lertprasertsuke"),
    "นิศาชล": ("Nisachol", "Dejkriengkraikul"),
    "บุญหลง": ("Boonlong", "Sivasomboon"),
    "บุษยามาส": ("Busyamas", "Chewaskulyong"),
    "ปกรณ์": ("Pakorn", "Wivatvongvana"),
    "ประพันธ์": ("Prapan", "Jutavijittum"),
    "ประไพ": ("Prapai", "Dejkhamron"),
    "ปรัชญพร": ("Pratchayapon", "Kammuang-lue"),
    "ปวิธ": ("Pawit", "Sutharat"),
    "ปวีร์": ("Pawee", "Chalidapong"),
    "ปัญจพร": ("Phanchaporn", "Wongmaneerung"),
    "ปิยฉัตร": ("Piyachat", "Kanchanaphangka"),
    "ปิยชนน์": ("Piyachon", "Aramrat"),
    "ปิยพงษ์": ("Piyapong", "Khumrin"),
    "ปิยะหทัย": ("Piyahathai", "Niamsup"),
    "ปีติชา": ("Peticha", "Tanprasert"),
    "ปูรณ์": ("Poon", "Apichartpiyakul"),
    "ผจญ": ("Phachon", "Wongtra-ngan"),
    "พงศ์สันติ์": ("Pongson", "Yaicharoen"),
    "พงษ์ศักดิ์": ("Pongsak", "Mahanupab"),
    "พรรณนิภา": ("Pannipa", "Suwannasom"),
    "พรสุรีย์": ("Pornsuree", "Kuvijitsuwan"),
    "พัชรพงษ์": ("Patcharapong", "Pantiya"),
    "พันธุ์ภัทร์": ("Panpat", "Chakrabandhu"),
    "พิชญ์": ("Pitch", "Hansasiripoj"),
    "พิชามญุ์": ("Pichamon", "Suwannachat"),
    "พิชิตชัย": ("Pichitchai", "Atthakomol"),
    "พินิจ": ("Pinit", "Limsukon"),
    "พิมพ์ตะวัน": ("Pimtawan", "Chanduean"),
    "พิมพ์ทอง": ("Pimthong", "Jitsakulchaidej"),
    "พุดตาน": ("Puttan", "Wongtriratanachai"),
    "ภวพล": ("Pawapol", "Keratichewanun"),
    "ภัทรพงศ์": ("Pattarapong", "Satjaritanun"),
    "ภัทรภรณ์": ("Phattaraporn", "Adulkasem"),
    "ภูริลาภ": ("Purilarp", "Daoarunkiat"),
    "ภูเนตร": ("Punate", "Weerateerangkul"),
    "มติ": ("Mati", "Chuamanochan"),
    "มธุรมาศ": ("Mathuramat", "Seesen"),
    "มนธนา": ("Montana", "Buntragulpoontawee"),
    "มาริสา": ("Marisa", "Dechawijit"),
    "มุนี": ("Munee", "Kaewplang"),
    "รณภพ": ("Ronnaphob", "Uaphanthasath"),
    "รนกฤต": ("Ronnakrit", "Maethungkul"),
    "รมณีย์": ("Romanee", "Chaiwarith"),
    "รมิดา": ("Ramida", "Samode"),
    "รวิชญ์": ("Rawich", "Deechaiya"),
    "รักษ์สลิล": ("Raksalin", "Raktrakul"),
    "รัฐพงศ์": ("Rattapong", "Sungnoon"),
    "รุ่งนภา": ("Rungnapa", "Malasao"),
    "ลภทัศ": ("Loppatas", "Tangsanga"),
    "ลลิตา": ("Lalita", "Sathitsamitphong"),
    "ลัลนา": ("Lanlana", "Nimmankiatkul"),
    "วชิรนันท์": ("Wachiranun", "Sirikul"),
    "วชิระ": ("Wachira", "Mokamol"),
    "วรกิตติ": ("Worakitti", "Lapisatepun"),
    "วรผกา": ("Worapaka", "Manosroi"),
    "วรภัทร": ("Vorapat", "Siriworawit"),
    "วรรณวรางค์": ("Wanwarang", "Wongcharoen"),
    "วรวิทย์": ("Worawit", "Khangtragool"),
    "วริทธิ์": ("Warit", "Wangsuekul"),
    "วัชรีพร": ("Watchareepohn", "Palangmonthip"),
    "วัฒนา": ("Vattana", "Kattipattanapong"),
    "วิชชา": ("Witcha", "Vipudhamorn"),
    "วินัย": ("Vinai", "Suriyanont"),
    "วิมลรัฐ": ("Wimonrat", "Tharnnop"),
    "วีระศักดิ์": ("Weerasak", "Nawarawong"),
    "วุฒิภัทร": ("Wuttipat", "Kiratipaisarl"),
    "วุฒิเดช": ("Vuddhidej", "Ophascharoensuk"),
    "ศตวรรษ": ("Satawat", "Thongsawat"),
    "ศรัณย์": ("Saran", "Sanguanrangsirikul"),
    "ศราวุธ": ("Sarawut", "Kongkarnka"),
    "ศริญญา": ("Sarinya", "Kham-ai"),
    "ศศินี": ("Sasinee", "Hantrakool"),
    "ศิรชัช": ("Sirachat", "Suchattrakun"),
    "ศิรดา": ("Sirada", "Lo Boulyo"),
    "ศิรินาฎ": ("Sirinart", "Kumfu"),
    "ศิริพงค์": ("Siripong", "Chiewchantanakit"),
    "ศิวาพร": ("Siwaporn", "Chankrachang"),
    "ศุภณัฐ": ("Supanat", "Warunkul"),
    "ศุภพงษ์": ("Supapong", "Arworn"),
    "ศุภาพิชญ์": ("Supapitch", "Chanthong"),
    "สมชาย": ("Somchai", "Hansakunachai"),
    "สมภพ": ("Somphop", "Amornsrisakul"),
    "สมศักดิ์": ("Somsak", "Sumitsawan"),
    "สมเจริญ": ("Somcharoen", "Saeteng"),
    "สรัล": ("Sarun", "Kiratikanont"),
    "สักกาเดช": ("Sakkadech", "Limmahakhun"),
    "สังวรณ์": ("Sangworn", "Sombatmai"),
    "สัณหวิชญ์": ("Sunhawit", "Junrungsee"),
    "สารนาถ": ("Saranat", "Orrapin"),
    "สำเริง": ("Samreung", "Rangdaeng"),
    "สินธิป": ("Sintip", "Pattanakuhar"),
    "สิริกาญจน์": ("Sirikan", "Limpakan (Yamada)"),
    "สิรีกานต์": ("Sireekarn", "Chantakhow"),
    "สุทธิภาศ": ("Suthipas", "Pongmanee"),
    "สุภาณี": ("Suphanee", "Sukraroek"),
    "สุภาวิตา": ("Suphawita", "Pliannuom"),
    "สุมาลี": ("Sumalee", "Siriaunkgul"),
    "สุรพันธุ์": ("Surapan", "Khunamornpong"),
    "สุรศักดิ์": ("Surasak", "Boonyaritichaikij"),
    "สุรีย์": ("Suree", "Lekawanvijit"),
    "สุวรรณ": ("Suwan", "Sanmee"),
    "หนึ่ง": ("Nung", "Ekmahachai"),
    "หาญชัย": ("Hanchai", "Klibngern"),
    "ห้องสิน": ("Hongsin", "Trakultivakorn"),
    "อดิศักดิ์": ("Adisak", "Tantiworawit"),
    "อติรุจ": ("Atiruj", "Supphapipat"),
    "อธิป": ("Athip", "Pattanakarn"),
    "อธิวัฒน์": ("Atiwat", "Soontornpun"),
    "อนวัช": ("Anawat", "Wisetborisut"),
    "อภิชนา": ("Apichana", "Kovindha"),
    "อภิชาติ": ("Apichat", "Tantraworasin"),
    "อภิญญา": ("Apinya", "Leerapun"),
    "อภิรักษ์": ("Apiruk", "Sangsin"),
    "อภิเศรษฐ": ("Apisate", "Pleumsamran"),
    "อมรพัฐ": ("Amornphat", "Kitro"),
    "อมฤต": ("Amarit", "Phothikun"),
    "อลิชา": ("Alicha", "Chumintrachark"),
    "อัครวัฒน์": ("Akarawat", "Wongsuksomba"),
    "อัษรา": ("Asara", "Thepbunchonchai"),
    "อานนท์": ("Anon", "Chotirosniramit"),
    "อารีวรรณ": ("Areewan", "Somwangprasert"),
    "เกษม": ("Kasem", "Uttawichai"),
    "เจษฎา": ("Jesda", "Singhavejsakul"),
    "เฉลิม": ("Chalerm", "Liwsrisakun"),
    "เฉลิมวุฒิ": ("Chaloemwut", "Piyaphattachai"),
    "เติมพงศ์": ("Termpong", "Reanpang"),
    "เทอดชัย": ("Therdchai", "Jivacate"),
    "เนตินัย": ("Netinai", "Nakviboonwong"),
    "เปรมปรีดิ์": ("Prempree", "Sutthasupa"),
    "เพ็ญพิชชา": ("Penpitcha", "Rojpibulsathit"),
    "เมตตาภรณ์": ("Mattabhorn", "Phimphilai"),
    "เศรษฐบุตร": ("Setabud", "Srijai-in"),
    "เอกรินทร์": ("Ekkarin", "Supatrakul"),
    "โสภณ": ("Sophon", "Siwachat"),
    "โอภาส": ("Opart", "Pinchai"),
    "ไตรจักร": ("Trichak", "Sandhu"),
    "ไพศิษฎ์": ("Paisit", "Siriwittayakorn"),
}

def fix_english_names():
    with SessionLocal() as db:
        faculties = db.query(FacultyDB).options(defer(FacultyDB.embedding)).yield_per(500)
        for faculty in faculties:
            if not faculty.full_name_th:
                continue
            for th_first, (en_first, en_last) in ENGLISH_NAMES.items():
                if th_first in faculty.full_name_th:
                    faculty.first_name = en_first
                    faculty.last_name = en_last

                    # Update embedding text
                    if en_first not in (faculty.embedding_text or ""):
                        faculty.embedding_text = f"{en_first} {en_last} {faculty.embedding_text}"
                    break
        db.commit()
        logger.info("Updated English names in database!")

def fetch_scholar_for_yuttana():
    with SessionLocal() as db:
        yuttana = db.query(FacultyDB).filter(FacultyDB.first_name == "Yuttana").first()
        if not yuttana:
            return

        logger.info("Searching Google Scholar for Yuttana Kumsuwan...")
        try:
            search_query = scholarly.search_author("Yuttana Kumsuwan")
            author = next(search_query)
            author = scholarly.fill(author, sections=['publications'])
            
            top_pubs = []
            for p in author.get('publications', [])[:5]:
                pub_title = p.get('bib', {}).get('title', '')
                pub_year = p.get('bib', {}).get('pub_year', '')
                if pub_title:
                    top_pubs.append({"title": f"{pub_title} ({pub_year})" if pub_year else pub_title})
            
            if top_pubs:
                # Merge unique
                existing = yuttana.featured_publications or []
                existing_titles = [e.get("title").lower() for e in existing]
                for p in top_pubs:
                    if p["title"].lower() not in existing_titles:
                        existing.append(p)
                yuttana.featured_publications = existing
                db.commit()
                logger.info(f"Successfully added publications for Yuttana: {top_pubs}")
        except Exception as e:
            logger.error(f"Error fetching Yuttana's scholar: {e}")

if __name__ == "__main__":
    fix_english_names()
    fetch_scholar_for_yuttana()
